### ISSUE TITLE
Show species name in bold large ornate above table in popup

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#100]
Referring to:

![selection_029](https://user-images.githubusercontent.com/4530905/42160306-ed02aeec-7e20-11e8-9a7a-a2a2248ee9e6.png)

Can you put above the table in larger, bold font the species name like the mockup below:

![screen shot 2018-07-04 at 08 26 27](https://user-images.githubusercontent.com/178003/42260312-3440818c-7f64-11e8-8d83-d22d9cdffb56.png)

**Comment by timlinux** [comment]
See also https://github.com/kartoza/django-bims/pull/93

**Comment by gubuntu** [comment]
redundant, no species popup any more.
