### ISSUE TITLE
Update Landing Page, Log In, Sign Up & Navigation Bar

### ISSUE THREAD

**Issue by carina1000** [kartoza/django-bims#1021]
Please update Landing Page, Login/SignUp and Nav Bar according to new designs. Inspect the designs at https://avocode.com Username: pierrealix@kartoza.com Password: welovekartoza2018

Nav and LP for first time visitors:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988333/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

Nav and LP for Signed Up members:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988333/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

Nav and LP for administrative users:
[FBIS_Dashboard Mocks_18.03.19 (dragged) 15.24.15.pdf](https://github.com/kartoza/django-bims/files/2988361/FBIS_Dashboard.Mocks_18.03.19.dragged.15.24.15.pdf)

Log In Screen:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988355/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

**Comment by timlinux** [comment]
@dimasciput before we can finalise the release we need to make the site look consistent with @carina1000's mockups.
