### ISSUE TITLE
Update Search Flow

### ISSUE THREAD

**Issue by carina1000** [kartoza/django-bims#1022]
Please update search flow according to the designs. Note the point is to get rid of the "second tab" and display the results on the first tab. The toolbar needs to be shifted all the way to the corner of the map to maximise map space. Please copy the fonts, colours, icons, buttons, etc. from the designs by inspecting them at https://avocode.com Username: pierrealix@kartoza.com Password: welovekartoza2018

Search Flow example 1:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988383/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

Search Flow example 2:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988384/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

Search Flow example 3:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988389/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

Search Flow example 4:
[FBIS_Dashboard Mocks_18.03.19 (dragged).pdf](https://github.com/kartoza/django-bims/files/2988394/FBIS_Dashboard.Mocks_18.03.19.dragged.pdf)

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
