### ISSUE TITLE
Update Legend Colours

### ISSUE THREAD

**Issue by carina1000** [kartoza/django-bims#1023]
Note the current legend colours are NOT on the FBIS style guide - these are LEDET colours.. Please update colours as follows - Inspect the colours on  https://avocode.com Username: pierrealix@kartoza.com Password: welovekartoza2018

![Screen Shot 2019-03-20 at 15 33 38](https://user-images.githubusercontent.com/35214829/54688172-cdcabd80-4b25-11e9-823f-5c781fac23ac.png)

**Comment by dimasciput** [comment]
fixed
