### ISSUE TITLE
Dots/site clusters clutter the map 

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1025]
When zoomed out the dots/site clusters make the map look too cluttered. Is there a solution to display the data in a clearer way? Maybe a heat map or using smaller dots. @timlinux @dimasciput @carina1000 @jeremyshelton 

![Screen Shot 2019-03-22 at 8 35 44 AM](https://user-images.githubusercontent.com/43198125/54804871-c0c0e200-4c7d-11e9-9bf4-4c059ee994bd.png)

**Comment by dimasciput** [comment]
If we use heat map, then I think we are going to lose the ability to select the dot, because we don't have the accurate position of the site in the map.

**Comment by NyakudyaA** [comment]
@dimasciput cc @toniolsen We could maintain the clusters and just introduce rule-based rendering that will allow only rendering of the clusters at a specific scale threshold and then make the dots smaller at smaller scales and not render all of them.

**Comment by toniolsen** [comment]
We would like the site legend to be implemented:

![Screen Shot 2019-04-01 at 12 06 19 PM](https://user-images.githubusercontent.com/43198125/55320069-9be71e80-5476-11e9-8595-b50b4fef4b18.png)

We should only be able to see big brown dots when zoomed out and then as we zoom in the green dots appear. This was working for Version 1, but since the SASS data was ingested it is not. 

@dimasciput @NyakudyaA @timlinux @jeremyshelton @helendallas
