### ISSUE TITLE
Include Module

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1028]
Please include **Module** as per the freshwaterbiodiversity.org site. We want to be able to select fish, inverts and algae separately. @timlinux @dimasciput @helendallas @jeremyshelton 

![Screen Shot 2019-03-22 at 8 58 29 AM](https://user-images.githubusercontent.com/43198125/54805859-f0251e00-4c80-11e9-8704-3670367ed89c.png)

**Comment by dimasciput** [comment]
@toniolsen do we have inverts and algae species?

**Comment by jeremyshelton** [comment]
Hi @dimasciput yes we will be including invert and algae species in version 3, but not in version 2 (only SASS taxa and fish species in version 2)
