### ISSUE TITLE
Spatial filters

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1030]
We agreed to include the list of spatial layers (but flat, without layer hierarchies) in their specific categories for Version 2 (**see ticket number 805**). At present only a subset have been included and they have been strangely grouped. There are also issues with the layers at present, e.g. Geomorphological zones category has incorrect sub categories.

@timlinux @dimasciput @Christiaanvdm @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
@toniolsen the filters are based on the data we have on the site, for example Geomorphological zones only has 2 sub categories, because all the data we have is only grouped into those 2 sub categories.

**Comment by toniolsen** [comment]
@dimasciput, @timlinux , Please see ticket #805.
We provided Kartoza with the spatial layers we wanted to include as well as the actual layers...
**This is in the FRC_Kartoza Shared Folder for FBIS in the GIS Context Layers Folder.**

@jeremyshelton @helendallas

**Comment by timlinux** [comment]
@dimasciput @NyakudyaA Has the list of layers and all the data from FRC. We need to make sure they are all published to the site.

**Comment by NyakudyaA** [comment]
@timlinux I have commented on the other ticket.

**Comment by dimasciput** [comment]
redundant ticket
