### ISSUE TITLE
Upload data tab doesn't work

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1033]
The upload data tab doesn't seem to work. It takes us back into the log in page.

@timlinux @dimasciput @Christiaanvdm

**Comment by dimasciput** [comment]
You need to login first, it's not accessible for public user.

**Comment by dimasciput** [comment]
@toniolsen

**Comment by toniolsen** [comment]
I am logged in when I select the "Upload data" tab.
Then it takes me back to the login page and I press login again and it still keeps taking me back to the login page... 

@dimasciput @timlinux @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen ok I just added a permission to upload data to all logged in user, not just staff. Can you try it again?

**Comment by toniolsen** [comment]
@dimasciput, Thanks! Yes, it is working now.
