### ISSUE TITLE
Species single site overview panel needs detailed dashboard button

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1044]
We need a button on the overview panel to lead the user to the detailed dashboard.

@dimasciput @Christiaanvdm

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/54903233-072c7000-4f0e-11e9-8286-fe96df8d6dc1.png)

We already have, or am I missing something.

**Comment by toniolsen** [comment]
Sorry I was talking about these:

![Screen Shot 2019-03-25 at 10 44 05 AM](https://user-images.githubusercontent.com/43198125/54906012-00403600-4eeb-11e9-84b5-31cef80b1650.png)

Last week they didn't look like buttons, but they look great and work now :) Thanks!
@dimasciput @jeremyshelton
