### ISSUE TITLE
SASS data in Fish detailed dashboards

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1045]
The links below that Tim provided for the Fish detailed dashboards contain SASS data?
@timlinux @dimasciput @jeremyshelton 

Single Site Fish: http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=9937&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=&validated=

Multi Site Fish: http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=G1KROM&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&validated=true

**Comment by dimasciput** [comment]
@toniolsen so the dashboard is not only for fish, but for all species

**Comment by toniolsen** [comment]
Yes, but there should be a modules filter (Fish, Invertebrate and Algae) to differentiate between the taxon one can see in the dashboards?

**Comment by dimasciput** [comment]
Yes but that's a filter in search panel, the dashboard is still for all species that we have in table ( from SASS or not ).

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux @toniolsen @helendallas There should definitely be no invertebrate data in the fish single- and multi-site detailed dashboard. Please see new ticket 1056 for clarity on this issue.

**Comment by dimasciput** [comment]
> @dimasciput @timlinux @toniolsen @helendallas There should definitely be no invertebrate data in the fish single- and multi-site detailed dashboard. Please see new ticket 1056 for clarity on this issue.

So this is will become new feature. Not sure we will implement this before deadline.

**Comment by dimasciput** [comment]
@toniolsen @jeremyshelton @helendallas actually that link is not for species detailed dashboard, but site detailed dashboard. 

Here is the species detailed dashboard : http://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=244&search=Anguilla%20bengalensis%20labiata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&validated=true

**Comment by timlinux** [comment]
@toniolsen I have chatted with @dimasciput on this so that we are all on the same page. He will filter records accordingly.

**Comment by toniolsen** [comment]
Thanks @timlinux 

@jeremyshelton @helendallas
