### ISSUE TITLE
Multi site overview panel

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1046]
There is no multi-site overview panel for both Fish and SASS.

@Christiaanvdm @timlinux @dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
What do you mean @toniolsen ?

**Comment by dimasciput** [comment]
And if what you mean is the right panel, yes we don't have it.

**Comment by toniolsen** [comment]
Okay, yes that is what I was talking about. Will those not be ready for Version 2? 
See below the mock up.

<img width="323" alt="Fig 5 - Multi-site ('area') overview dashboard" src="https://user-images.githubusercontent.com/43198125/54810371-a2afad80-4c8e-11e9-9f85-d826bb34ad98.png">
