### ISSUE TITLE
Fish form sampling methods

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1049]
Please include this list of sampling methods in the fish form drop down.

**1.) electro-fishing

2.) snorkeling

3.) underwater video analysis

4.) gill net

5.) seine net

6.) fyke net

7.) hand net**

![Screen Shot 2019-03-22 at 11 04 04 AM](https://user-images.githubusercontent.com/43198125/54811849-59615d00-4c92-11e9-8920-9008a2c8f2bb.png)

@Christiaanvdm @timlinux @dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen Yes we can add it from admin, or you can try it?

**Comment by dimasciput** [comment]
@toniolsen http://testing.healthyrivers.kartoza.com/admin/bims/samplingmethod/

**Comment by toniolsen** [comment]
I am unable to login @dimasciput

**Comment by dimasciput** [comment]
added in testing
