### ISSUE TITLE
SASS multi-site dashboard graphs

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1055]
Graphs need axis labelled as with Single Site dashboard (but  orientation will be different) and then they need to be colour coded based on ecological categories.

![Screen Shot 2019-03-22 at 11 55 29 AM](https://user-images.githubusercontent.com/43198125/54814958-7b121280-4c99-11e9-9dd0-0287ed46bc8d.png)

@dimasciput @timlinux @helendallas

**Comment by dimasciput** [comment]
> @toniolsen Graphs need axis labelled as with Single Site dashboard (but orientation will be different) 

Can you elaborate more about this? I just followed the design from the mockup.

**Comment by toniolsen** [comment]
@dimasciput, I think what is wanted here is for each bar associated with the specific site must be the colour of it's corresponding ecological category? 
Is this right @helendallas?

**Comment by helendallas** [comment]
We don't need the green bar with each axis label and then bar colours for each correspond to the ecological category as per the ecological category graph - I have tried to show by modifying the graphic below. 
![image](https://user-images.githubusercontent.com/45286876/55938264-4dd2d780-5c3b-11e9-859d-a96283d571f8.png)
