### ISSUE TITLE
Clarity on dashboards and modules

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1056]
@timlinux @dimasciput @Christiaanvdm @toniolsen @helendallas This a new ticket to make sure we are all on the same page with the different overview panels and detailed dashboards, and with what data should feature in each. 

The schematic shows the options for a user searching by site (single or multi) or my a taxon (fish for v2 or invertebrate and algae in v3). 

Site overview panel is the only place where fish, invertebrate and algae data are displayed together. From there, the user then selects (using one of the buttons at bottom of overview panel in the 'biodiversity data table') either the fish, sass, invert or algae for the detailed dashboard. 

The user must also have an option to pre-decide which module they want in a tab like the one that used to be in filters.

@toniolsen is going to create and add a schema to help resolve this issue. 

[Modules and dashboards schema.pdf](https://github.com/kartoza/django-bims/files/2996825/Modules.and.dashboards.schema.pdf)

**Comment by toniolsen** [comment]
@timlinux @dimasciput @Christiaanvdm @jeremyshelton @helendallas 

[Modules and dashboards schema.pdf](https://github.com/kartoza/django-bims/files/2996425/Modules.and.dashboards.schema.pdf)

**Comment by dimasciput** [comment]
> Site overview panel is the only place where fish, invertebrate and algae data are displayed together. From there, the user then selects (using one of the buttons at bottom of overview panel in the 'biodiversity data table') either the fish, sass, invert or algae for the detailed dashboard.

@jeremyshelton we already have site detailed dashboard and species detailed dashboard, 

Here is the species detailed dashboard : http://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=244&search=Anguilla%20bengalensis%20labiata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&validated=true

**Comment by dimasciput** [comment]
implemented
