### ISSUE TITLE
Download Summary Data CSV

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1057]
CSV for “Download Summary Data” not yet correct:
As per our CSV file on dropbox

Filter history: all spatially filtered geocontext data
--
FBIS site code
Site description
River name
Latitude
Longitude
Sampling date
Time of day
Collector/assessor
Accredited: Y/N
SASS version: 4/5
Stones in current
Stones out of current
Bedrock
Marginal vegetation in current
Marginal vegetation out of current
Aquatic vegetation
Gravel
Sand
Mud
SASS Score
Number of taxa
ASPT
Ecological condition
Reference category
Study reference

@dimasciput @timlinux @helendallas

**Comment by dimasciput** [comment]
@toniolsen can you attach the file here? Thanks

**Comment by toniolsen** [comment]
[Fish and SASS csv_Feb 2019.xlsx](https://github.com/kartoza/django-bims/files/3067365/Fish.and.SASS.csv_Feb.2019.xlsx)

@dimasciput

**Comment by dimasciput** [comment]
@toniolsen thanks, but that's not a really proper csv format, it should be something like this : 
[data_example-10.csv.zip](https://github.com/kartoza/django-bims/files/3068065/data_example-10.csv.zip)

Can you make a csv template for me? It would really help me out.

**Comment by toniolsen** [comment]
@dimasciput I have emailed the CSV download templates to you.
For some reason Github does not support my csv. file type.
