### ISSUE TITLE
Common name incorrect

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#106]
It seems we are showing the scientific name where we should be showing the common name:

![screen shot 2018-07-04 at 10 07 25](https://user-images.githubusercontent.com/178003/42265037-aad5b9e4-7f72-11e8-940a-deee000b9eb8.png)

and in the popup:

![screen shot 2018-07-04 at 08 26 27](https://user-images.githubusercontent.com/178003/42265051-b31ad4b8-7f72-11e8-9d0c-c19c52224a7b.png)

Can we please show the common name here rather

**Comment by cchristelis** [comment]
# Problem

Since we don't actually have this as a popup, we should embed this info into the side panel.

# Proposed Solution

Add this info in an expandable element per record (at site level).

**Comment by meomancer** [comment]
i think this is fixed? (already put it at side panel)

**Comment by Vries14** [comment]
This is fixed with the gbif.org hyperlink on the side panel.
