### ISSUE TITLE
Issue with SASS dashboard returning all of the SASS data

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1065]
@helendallas navigated to a site with 39 known sampling dates - G2EERS-JONKE - but when the SASS dashboard opened only one sampling date was returned.

![Navigation 1](https://user-images.githubusercontent.com/43198125/54827432-a822ed00-4cba-11e9-9794-eb0a75eec1cb.jpg)

@dimasciput @timlinux

**Comment by dimasciput** [comment]
@toniolsen @helendallas this is not a bug, you open the multi site sass dashboard, it will only display latest date.
