### ISSUE TITLE
SASS form- "Data Source"

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1066]
We would like some more details on "Source" in the SASS form.
 
Some suggestions
**Reference Category:** A drop-down list of options as per our list.
**Study Reference:** The user then adds the reference in a standard format (e.g. Surname, Initial, date (Dallas, H.D., 2019).
**Upload pdf:** We need to give the user the option to upload a pdf of the report etc from where the data is from. 
 
This can wait for Version 3, but might be good to include now, to complete the SASS data entry form.

![Screen Shot 2019-03-22 at 4 03 35 PM](https://user-images.githubusercontent.com/43198125/54828311-8dea0e80-4cbc-11e9-8550-a8e0d0a65d80.png)

@dimasciput @timlinux @helendallas

**Comment by helendallas** [comment]
@timlinux 
Further clarity following our recent discussion on uploading pdfs of reports not available easily on the internet.

It good to get this working on the Add SASS Record. 

See ticket #1478

**Comment by timlinux** [comment]
See #1052

**Comment by dimasciput** [comment]
we will use the same logic from https://github.com/kartoza/django-bims/issues/1542
