### ISSUE TITLE
Overlays should get legends

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#107]
When we show the overlays e.g. veg map. we should make the legend available too so it is clear what the colours mean:

![screen shot 2018-07-04 at 10 25 47](https://user-images.githubusercontent.com/178003/42265749-bf4e7fe4-7f74-11e8-9f2e-10c4f19b0de9.png)

We can use the getLegendGraphic request for this in WMS sources

**Comment by gubuntu** [comment]
done
