### ISSUE TITLE
Tables cutting off text

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1075]
Some of the tables (example below) are cutting off the text. Can we make the column widths wider to fit in all the text?

![Screen Shot 2019-03-25 at 11 23 38 AM](https://user-images.githubusercontent.com/43198125/54908480-ab072300-4ef0-11e9-9ab0-887ed0cb2658.png)

@dimasciput @Christiaanvdm @carina1000

**Comment by dimasciput** [comment]
We could make the column wider, but if the browser screen is smaller it will still cut the text.

**Comment by toniolsen** [comment]
@dimasciput, any other solutions?

Maybe make the text smaller?

**Comment by dimasciput** [comment]
Fixed it on testing

**Comment by toniolsen** [comment]
The text is fitting in the columns, but now the tables look a bit strange. @dimasciput 

![Screen Shot 2019-04-11 at 9 01 30 AM](https://user-images.githubusercontent.com/43198125/55937186-9e950100-5c38-11e9-93bd-86409a9ac36b.png)
