### ISSUE TITLE
Endemism

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1083]
For all Endemism information in FBIS it must just include the 5 circled categories. 
"Micro-endemic" and "Regional endemic" are not categories.

![Screen Shot 2019-03-27 at 8 10 59 AM](https://user-images.githubusercontent.com/43198125/55054484-bd0bd180-5068-11e9-9326-78c4996bfe71.png)

@dimasciput @Christiaanvdm @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen this will be automatically gone when we update data with the new file here : https://github.com/kartoza/django-bims/issues/1024

The micro-endemic and regional endemic is from old data.
