### ISSUE TITLE
Fish Multi-site detailed dashboard - Number of sites and Endemism graphs

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1085]
Missing "Number of sites" and "Endemism" over time graphs here on the fish multi-site detailed dashboard:

![Screen Shot 2019-03-27 at 3 09 52 PM](https://user-images.githubusercontent.com/43198125/55078427-d03b9300-50a2-11e9-898d-6be5bf7e555f.png)

@dimasciput @jeremyshelton @timlinux

**Comment by dimasciput** [comment]
Added in testing
