### ISSUE TITLE
Marine fish species in FBIS

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1088]
We can see that there are some marine fish species in the system. Is there a way to cross check with our Master fish list and remove all the fish species not found in this Master list as this only contains freshwater species?

@timlinux @dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen do you have any example of the marine fish? I just checked, all the species that I fetched from gbif are from your list.

**Comment by toniolsen** [comment]
@dimasciput 
The only species off hand I was concerned about is _Clinus superciliosus_, but I can see it is in the Master list, therefore it is probably an estuarine species.
Thanks for checking, I am sure it is all fine now.

**Comment by dimasciput** [comment]
thanks, closing it now
