### ISSUE TITLE
We need to be able to make a link between a citation and a biological collection record

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#110]
Use case:

Joe finds a publication listing a number of occurrences and adds them to BIMS. Joe wants to refer to which publication these occurrences were described in.

child of https://github.com/kartoza/LEDET_BIMS/issues/210

**Comment by carina1000** [comment]
please see Resources mockup at #210

We will add the resources linked to the map on the side pannel under the "Resources" accordion
[Uploading Screen Shot 2018-08-01 at 15.32.43.png...]

**Comment by carina1000** [comment]
![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3561353333613539343330343439303031326239636662362f313235353136633636653832633732386163653231653064343664](https://user-images.githubusercontent.com/35214829/43892600-aa3ce4c8-9bcc-11e8-91b3-420733bb472f.png)

**Comment by carina1000** [comment]
@gubuntu it's open ended - please see comment at ticket #210
