### ISSUE TITLE
Permalink is not working for zoom extent when no filter is applied

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1140]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/178003/56192635-227f2c80-602f-11e9-865a-a62ed953c4b8.png">
 
If you dont have any filters but zoom in the map the permalink does not include zoom extents.

Works fine when you have filters applied

**Comment by dimasciput** [comment]
yes this is not a bug, we just didn't implement it.
