### ISSUE TITLE
Download data link is not working

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1141]
With no filters

<img width="559" alt="image" src="https://user-images.githubusercontent.com/178003/56192804-7c7ff200-602f-11e9-9c31-1dd9783eb967.png">

**Comment by timlinux** [comment]
@dimasciput can you just hide this icon for now? I suspect it hangs up the server when I hit it

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
