### ISSUE TITLE
Sites legend is wrong

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1144]
<img width="157" alt="image" src="https://user-images.githubusercontent.com/178003/56194983-514bd180-6034-11e9-840c-77949fec41cd.png">

Second entry should read 2-10 not 1-10

CC @helendallas

**Comment by NyakudyaA** [comment]
@timlinux this is not a get legend request.
![getlegend](https://user-images.githubusercontent.com/2510900/56195553-7f7de100-6035-11e9-9ca6-f0d8c02c5453.png)

 I think it's a static image in which the text can be changed in the code. cc @dimasciput
