### ISSUE TITLE
Study ref should not show all GBIF records

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1153]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/178003/56203488-a47a5000-6045-11e9-8483-93571727abe2.png">

Rather just show a single entry 'GBIF' or remove them from that list - having individual URLs is not useful.

**Comment by dimasciput** [comment]
I probably change this to autocomplete instead, much more cleaner and better performance because I don't need to get all the list.
