### ISSUE TITLE
Collector / assessor list does not include SASS data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1160]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/178003/56205873-3c2e6d00-604b-11e9-8ea5-9d920b44c2b5.png">

We should be able to find Dallas listed there from the SASS records

**Comment by helendallas** [comment]
This ticket is really important but was not assigned a Release Blocker status.  To reiterate, none of the SASS Assessors are coming through in the Collector/Assessor filter. For example there are no matches for "Helen Dallas" - 
![image](https://user-images.githubusercontent.com/45286876/58083316-0be16d80-7bb9-11e9-82f6-42f5e6e0f08e.png)

**Comment by dimasciput** [comment]
Hi @helendallas , you can put this ticket to ready here https://github.com/kartoza/django-bims/projects/2, and put it to the highest priority (top of the ready). Since I'm only working from the ready column.

**Comment by dimasciput** [comment]
@helendallas here's how : 

![Peek 2019-05-21 17-27](https://user-images.githubusercontent.com/1979569/58088883-cc814400-7bed-11e9-8485-5ac5eda46095.gif)
