### ISSUE TITLE
The sites should be listed from upslope to downslope

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1164]
List of sites should be ordered by altitude (descending)

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/178003/56213616-b0254100-605c-11e9-89b2-48ddc05793ee.png">

Then you will see the river quality moving from good to bad as you work downstream

**Comment by timlinux** [comment]
CC @helendallas

**Comment by helendallas** [comment]
Further to this issue above. Where a larger area is selected, for example an entire SA ecoregion level 1, it doesn't make sense really to order by altitude. A simpler option may be to sort on  Site Code, which includes the Secondary Catchment code at the start. It would help with finding a specific site in the list
![Screenshot_2019-04-26 Django BIMS SASS Dashboard Multiple Sites.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf7e253a38437001108d4c9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd6416733e7b52e30f7a84ed2fb0025928223c5ecf303b3c5488a8ca73f4e96d32de4c76a88d2906349a6801cfe1c64afc13a632cb0ddaece9d908d2e22f20b58ad9496d1a571f8cfd5c3da5994bc90bff4ae1455cac012a71a427682818c9473f7929752cb9fdd85c868065a2b8182955cee5ecfb1100ec.png)

**Comment by timlinux** [comment]
Only makes sense for 1 river.  Parked based on discussion with FRC - we can figure out a decent workflow for this if needed. For now dont implement.

**Comment by helendallas** [comment]
I am going to close this as it will be difficult to implement and for now not necessary
