### ISSUE TITLE
We need a better workflow for getting  to multisite SASS dashboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1167]
Currently if I do a multisite query I get to this

<img width="305" alt="image" src="https://user-images.githubusercontent.com/178003/56214618-8240fc00-605e-11e9-871d-5bc4fbfcece3.png">

Then I have to open the multisite dashboard:

http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Silvermine&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=true

Then I have to scroll down to open the multiple site sass dashboard

<img width="550" alt="image" src="https://user-images.githubusercontent.com/178003/56214694-a8669c00-605e-11e9-9ba9-62e68fd19c60.png">

It would be better to have a side panel when I click on the blue badge, that then shows a summary of the sites with a link to the multisite dashboard and a link to the multiple site SASS dashboard.

**Comment by dimasciput** [comment]
implemented
