### ISSUE TITLE
Sign up page tweaks over #1021

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1180]
This advice overrides #1021 

Needed for sign up:

Full Name (required):

Organisation (required)

Email:

Password:

Remove google and github sign ups.

Sign up requests should be approved by FRC

Sign up request notification should be addressed from "fbis@frcsa.org.za" to "fbis@frcsa.org.za". 

The signup notification should include a link that FRC (staff users) can go an approve the new user requests.

**Comment by timlinux** [comment]
For the user profile we need an extra checkbox on the user profile:

"SASS Accredited" 

That staff users can check to indicate if a user is accredited. 

When sass data is uploaded it should be flagged as to whether the user uploading it is accredited and this should be indicated on the on-screen sass from.

**Comment by dimasciput** [comment]
@helendallas @timlinux just to be clear, should we remove the username from login and signup page?

**Comment by helendallas** [comment]
My feeling is that ones email should become the username, so 
Email: helen@frcsa.org.za
Password: xxxxxx

Is all that is required to login.

Then to sign for the first time one completes all of the above.

Question @timlinux ; SASS accreditation is linked to a specific time period - 3 years - after which it expires unless the person undergoes accreditation again. We need a time stamp/period associated with SASS accreditation - just as it currently is in the Rivers DB.  Not sure where this is best placed?

**Comment by timlinux** [comment]
> Question @timlinux ; SASS accreditation is linked to a specific time period - 3 years - after which it expires unless the person undergoes accreditation again. We need a time stamp/period associated with SASS accreditation - just as it currently is in the Rivers DB. Not sure where this is best placed?

@dimasciput can you put a SASS Accreditation time stamp field in the user model that is used to indicated when they were last accredited?

**Comment by timlinux** [comment]
> @helendallas @timlinux just to be clear, should I remove the username from login and signup page?

Yes we can just use the email address as the user name @dimasciput
