### ISSUE TITLE
We need to record the uploader

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1181]
When a user ingests or uploads a collection or sass record, the person uploading the record should be attached to the record and the owner should be the original collector

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/178003/56349405-c8b26a00-61c8-11e9-9bbb-91e02084332d.png">

For SASS we should do some manual batch updates to make the 

uploader = to the uploader 

so that e.g. 

Dallas as the assessor is also the uploader recorded.

**Comment by dimasciput** [comment]
@timlinux 
We already have two fields, owner and collector. Owner is the original uploader in user object, collector is the original collector of the species in string format. Should we create another one for the uploader? 

```
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    collector = models.CharField(
        max_length=300,
        blank=True,
        default='',
        verbose_name='collector or observer',
    )
```
