### ISSUE TITLE
Additional filters for SASS, MiniSASS, GBIF, iNaturalist etc.

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1182]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/178003/56351816-36ad6000-61ce-11e9-8db6-64d3da860ec0.png">

We want to rearrange the drawers a bit:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/178003/56352772-31511500-61d0-11e9-97b9-a41550ca4f01.png">

Non-accredited SASS are data uploaded by a user who is not acredited - see #1180 

Additionally the search completion should not include search terms for unchecked data validation items and 'other data sources'.

For example, if GBIF is unchecked we should not show text-completion results for common names etc from GBIF imports.

**Comment by jeremyshelton** [comment]
Wow, this ticket has been moved around a lot!

@dimasciput @timlinux I think these tasks are now covered in #1859 and #1860

**Comment by dimasciput** [comment]
the panel has been added to testing

**Comment by helendallas** [comment]
Clsoing ticket as MiniSAASS and InWards wq data available as separate group on main map

**Comment by jeremyshelton** [comment]
Cool.
