### ISSUE TITLE
Common name search revision

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1183]
For common name searches, FRC only want common names from their master list to be used. There are lots of dodgy looking names coming from GBIF that they do not want to see in search results.

@dimasciput lets discuss this and see if it is easily managed on our side.

**Comment by dimasciput** [comment]
Need to discussed this first

**Comment by timlinux** [comment]
We discussed this today and confirm that common name searches should  use only the names from Taxonomic Group. @dimasciput  we also need a way for admin users to manage the master lists.

**Comment by timlinux** [comment]
Just to clarify : this logic should apply for all taxonomic groups.

**Comment by helendallas** [comment]
@dimasciput Common names are visible in search again - they should not be as per this ticket

![image](https://user-images.githubusercontent.com/45286876/74648609-b1486280-5186-11ea-97e1-d65757977e4b.png)

**Comment by dimasciput** [comment]
`python manage.py update_fish_species_data`

**Comment by dimasciput** [comment]
Please check it in testing server

**Comment by helendallas** [comment]
@dimasciput Common names still visible in testing site.  Seems to be fish only.

In Live site invertebrate and fish common names visible

**Comment by dimasciput** [comment]
@helendallas yes this is only for testing now, the common name comes from the master list provided by fbis, should I just delete all the common names?

**Comment by helendallas** [comment]
@jeremyshelton Please read string and confirm - we don't want to display common names on FBIS. 
But do we want to delete from Master list?   I am not including common names for invertebrates.  If this is the only way to exclude common names from FBIS then we will have to delete it. @dimasciput ?

**Comment by dimasciput** [comment]
@helendallas we don't need to delete it if you want, I could just hide it from the search results. My thinking is that common names are important if they come from fbis master list.

**Comment by helendallas** [comment]
@dimasciput for consistency lets hide for now, thanks

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput OK sure, agreed - if we can hide all common names, that's probably the best solution for now 👍

**Comment by jeremyshelton** [comment]
@dimasciput common name still showing on taxon dashboard, but don't think that's really a problem @helendallas ?
