### ISSUE TITLE
Former names on collection records and name report

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1184]
For adding new biological collection records we should look up what the current accepted name is and store the original species name to the side and reference the record for search and display by its current accepted name.

@dimasciput I think we already do this in the original model - I just want confirm that is the case with you.

Also, can you make an admin table or view that lists all taxa on the system along with their previously used names and common names?

**Comment by helendallas** [comment]
This is worth checking on for next FBIS phase and RBIS

**Comment by helendallas** [comment]
Closing ticket as actioned in Taxon Management
