### ISSUE TITLE
SASS Form taxon list should be styled like dashboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1191]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/178003/56360590-6f0c6880-61e5-11e9-80de-445e463907ef.png">

**Comment by timlinux** [comment]
CC @helendallas

**Comment by helendallas** [comment]
I went to check this but go following error:
![Screenshot_2019-05-06 testing healthyrivers kartoza com 520 Web server is returning an unknown error](https://user-images.githubusercontent.com/45286876/57214764-43fa8500-6feb-11e9-9692-cb4b87faea94.png)
