### ISSUE TITLE
Temporal Scale - resolution

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1207]

**Comment by helendallas** [comment]
I was trying to select records from 2007 onwards, and because the earliest record includes data as far back as the 1700s (I assume from GBIF) - it is impossible to get a fine enough resolution to select a more recent date range.  Please cna you try and improve this
![Screenshot_2019-04-26 Django BIMS Map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf7e253a38437001108d4c9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd6416733e7b52e30f7a84ed2fb0025928223c5ed110184d58eeb9cb74fce36f34985619e8836c0972953943abbd801eb704ba208a1c8cb7bc8245c8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee74f5dac103063e677316e0a.png)

**Comment by dimasciput** [comment]
I don’t really understand the issue, can you elaborate more? You can drag the year bar to 2007

**Comment by helendallas** [comment]
It is very hard on my screen to drag the screen to a resolution close to 2019, and the scale is so long, starting in 1700.....I am not sure if or how this can be sorted unless we exclude records before 1900. I am not even sure if the 1700 record is correct. I will ask Toni to check this on GBIF  Please an you connect her to this ticket Dimas as I am not sure how.

**Comment by dimasciput** [comment]
I think the solution is to make the year as input field, so we can change the year directly. 
What do you think @helendallas @timlinux ?

**Comment by helendallas** [comment]
I really like the slider option, and it may resolve itself if we can somehow exclude certain data that are questionable. e.g. I had a quick look to see what the data were from pre 1850. It is from GBIF - one record is incorrect: date is 1700, this is an obvious error.  Taxon | Pseudocrenilabrus philander; -- | --; Total records | 0
GBIF ID | 4285757; 

Then there are only 11 species pre 1900. see shot below
![image](https://user-images.githubusercontent.com/45286876/56889368-713cb580-6a76-11e9-9891-1ddd61962f33.png)

Thoughts @timlinux

**Comment by timlinux** [comment]
Our proposed fix for this is to add search in the admin interface so that @helendallas can jump to a specific record and edit / fix manually.

**Comment by dimasciput** [comment]
Added date range filter in biological collection record

![ford](https://user-images.githubusercontent.com/1979569/58468965-c7ca0c00-8168-11e9-8e98-cb72971fcda9.gif)

- Go to this link to edit the records data : 
http://testing.healthyrivers.kartoza.com/admin/bims/biologicalcollectionrecord/

- Click the filter button, there are two date input, date from and date to

- Click the calendar icon to select the date from calendar

- Staff can also input the date manually with format YYYY-MM-DD e.g. 2019-10-30

- Click the search button to filter to records

**Comment by dimasciput** [comment]
@helendallas

**Comment by timlinux** [comment]
Perfect, thanks @dimasciput !
