### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1208]

**Comment by helendallas** [comment]
The arrow for activating a search is not visible for me - I use Firefox
![Screenshot_2019-04-26 Django BIMS Map(1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf7e253a38437001108d4c9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd6416733e7b52e30f7a84ed2fb0025928223c5ed110184745e5eb9539e6f4632adf0f4fffdb7f5a26c76b17ffbcd018ba03bb288e4f85b7ef834dc0e0342df5979d0d6f405147d4a61760e28b41da59fe41e04850a2113e6be37e3e7d46930c38.png)

**Comment by dimasciput** [comment]
Redundant https://github.com/kartoza/django-bims/issues/1148
