### ISSUE TITLE
Downloadable graphs quality

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1217]
Please can we improve the quality of the graphs that can be downloaded?
@dimasciput @timlinux

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
The quality of the downloadable graphics is still far too low to be usable by most users. Is there a way to significantly increase the quality of these?
@helendallas

**Comment by dimasciput** [comment]
Please try it here : http://testing.healthyrivers.kartoza.com/sass/dashboard/10206/?taxon=&siteId=10206&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=%5B%22validated%22%5D&sourceCollection=&ecologicalCategory=

This is still only implemented for single site SASS dashboard

**Comment by dimasciput** [comment]
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600" height="600"><defs><clipPath id="DHMkTfcBtGlU"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="XkUemMJtGiJt"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="IpQKXMToBVoV"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="ffRGKTuiXXac"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="IhAOZTgqUkUS"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="HTGAfcrvtiPe"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="RpqZRAHZTfFc"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath><clipPath id="ETsBTAPIdgQt"><path fill="none" stroke="none" d=" M 77.3828125 122 L 590.326171875 122 L 590.326171875 572 L 77.3828125 572 L 77.3828125 122 Z"/></clipPath></defs><g><g><rect fill="none" stroke="rgb(0,0,0)" x="52.91943359375" y="10" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#1F4E7A" stroke="none" x="52.91943359375" y="10" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="79.91943359375" y="19" text-anchor="start" dominant-baseline="central">Stones in current (SIC)</text><g><rect fill="none" stroke="rgb(0,0,0)" x="272.98681640625" y="10" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#2E76B6" stroke="none" x="272.98681640625" y="10" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="299.98681640625" y="19" text-anchor="start" dominant-baseline="central">Stones out of current (SOOC)</text><g><rect fill="none" stroke="rgb(0,0,0)" x="39.388671875" y="38" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#375822" stroke="none" x="39.388671875" y="38" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="66.388671875" y="47" text-anchor="start" dominant-baseline="central">Aquatic vegetation</text><g><rect fill="none" stroke="rgb(0,0,0)" x="224.4931640625" y="38" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#B77282" stroke="none" x="224.4931640625" y="38" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="251.4931640625" y="47" text-anchor="start" dominant-baseline="central">Marginal vegetation in current (MVIC)</text><g><rect fill="none" stroke="rgb(0,0,0)" x="27.4013671875" y="66" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#18A090" stroke="none" x="27.4013671875" y="66" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="54.4013671875" y="75" text-anchor="start" dominant-baseline="central">Marginal vegetation out of current (MVOC)</text><g><rect fill="none" stroke="rgb(0,0,0)" x="403.544921875" y="66" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#4E7F31" stroke="none" x="403.544921875" y="66" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size="18px" font-style="normal" font-weight="normal" text-decoration="normal" x="430.544921875" y="75" text-anchor="start" dominant-baseline="central">Gravel</text><g><rect fill="none" stroke="rgb(0,0,0)" x="493.560546875" y="66" width="18" height="18" stroke-opacity="0.1" stroke-miterlimit="10" stroke-width="3"/><rect fill="#BE9001" stroke="none" x="493.560546875" y="66" width="18" height="18"/></g><text fill="#666" stroke="none" font-family="'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" font-size=
```

**Comment by timlinux** [comment]
[chart.zip](https://github.com/kartoza/django-bims/files/4254533/chart.zip)

**Comment by timlinux** [comment]
Note we walked through this with @jeremyshelton and our preferred approach is to download the chart as an SVG and advise the user to open the SVG in word. It gives a really nice product and is easy for users to follow.

@helendallas please confirm if this works for you.

**Comment by helendallas** [comment]
@timlinux @dimasciput @jeremyshelton 

As long the graphs look the same as what is displayed on the dashboard and the quality is good enough to include in reports, I am happy. If it is clear to users how to download and paste into their reports - it should be fine.

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput are we still rolling out the .svg download functionality to all dashboards?

**Comment by dimasciput** [comment]
@jeremyshelton yes it's only on testing for now, I will deploy it to live on weekend -> https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[18.96240234375,-32.08722870829662],[18.951416015625,-32.347482203218654],[19.072265624999996,-32.375322284319346],[19.16015625,-32.11514862261243],[18.96240234375,-32.08722870829662]]

**Comment by jeremyshelton** [comment]
@dimasciput ok cool - will test next week 👍

**Comment by timlinux** [comment]
@dimasciput just update the tooltip please to indicate that you should insert the image from file, not drag and drop it:

![image](https://user-images.githubusercontent.com/178003/76952157-96434c80-6904-11ea-982d-b5c940b9cfb6.png)

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
Some people may not be able to open a .svg, or even drag it into ms office, if they don't have a program that can do so. Is the best way around this to suggest they download a program for this? If so, which is easiest?

**Comment by jeremyshelton** [comment]
Without union photoshop, I was able to drag the .csv into powerpoint, but it seems do have done a weird crop?

<img width="1162" alt="Screenshot 2020-03-19 at 12 06 14" src="https://user-images.githubusercontent.com/44292029/77055809-36b77080-69da-11ea-9618-5566d8ddc6bf.png">

**Comment by jeremyshelton** [comment]
...same story with SASS charts:
https://testing.healthyrivers.kartoza.com/sass/dashboard/10206/?taxon=&siteId=10206&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=%5B%22validated%22%5D&sourceCollection=&ecologicalCategory=

<img width="1161" alt="Screenshot 2020-03-19 at 12 10 25" src="https://user-images.githubusercontent.com/44292029/77056146-ba715d00-69da-11ea-86dd-89a036d7665c.png">

**Comment by dimasciput** [comment]
@jeremyshelton did you zoom in the browser before downloading the chart? If so, please try use normal zoom level.

**Comment by dimasciput** [comment]
@jeremyshelton 
> @dimasciput @timlinux
Some people may not be able to open a .svg, or even drag it into ms office, if they don't have a program that can do so. Is the best way around this to suggest they download a program for this? If so, which is easiest?

Most browsers are able to open the svg.

**Comment by jeremyshelton** [comment]
> @jeremyshelton did you zoom in the browser before downloading the chart? If so, please try use normal zoom level.

No, I don't think I am zoomed in at all, but every time when I open the svg I get a support-cropped in image?

**Comment by jeremyshelton** [comment]
> @jeremyshelton
> 
> > @dimasciput @timlinux
> > Some people may not be able to open a .svg, or even drag it into ms office, if they don't have a program that can do so. Is the best way around this to suggest they download a program for this? If so, which is easiest?
> 
> Most browsers are able to open the svg.

OK, than that should be fine 👍

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/77646124-9a0e4900-6f6c-11ea-85db-8c09cf4796f7.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/77646300-f2dde180-6f6c-11ea-9d07-bf5e677d6919.png)

**Comment by helendallas** [comment]
https://freshwaterbiodiversity.org/sass/dashboard/11056/?taxon=&search=a1ngot&siteId=11056&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=11056&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@jeremyshelton can you try it again on the testing? I think I fixed it.

**Comment by dimasciput** [comment]
@jeremyshelton can you test this please?

**Comment by jeremyshelton** [comment]
@dimasciput, it's looking good now. I tested for fish and inverts and SASS. Thanks for fixing.

A few issues I picked up: with the pie charts it seems to down load the last graph only. Is there a way to download all off them together, or each individually? Also, the key (legend) needs to be included, like it is for other graph downloads. 

**On FBIS**
<img width="846" alt="Screenshot 2020-04-09 at 07 38 40" src="https://user-images.githubusercontent.com/44292029/78861780-f5910a00-7a35-11ea-94b2-0c0f6a146efb.png">

**Downloaded graph**
<img width="384" alt="Screenshot 2020-04-09 at 07 41 39" src="https://user-images.githubusercontent.com/44292029/78861802-0d688e00-7a36-11ea-8cf6-4f32ce723cdd.png">

@helendallas for the SASS, do you need a legend to come through with this graph download?
<img width="388" alt="Screenshot 2020-04-09 at 07 42 46" src="https://user-images.githubusercontent.com/44292029/78861862-3721b500-7a36-11ea-8283-a1afb94f0109.png">
