### ISSUE TITLE
Spatial Filters: NFEPA layers

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1219]
@dimasciput @NyakudyaA @timlinux @helendallas @toniolsen 

For the spatial filters, the subset of the NFEPA layers displayed is not correct. 

The correct layers to include are shown below. 

Layer descriptions can also be found here: http://bgis.sanbi.org/Search?searchterm=NFEPA

<img width="912" alt="Screenshot 2019-05-02 at 09 15 03" src="https://user-images.githubusercontent.com/44292029/57061472-42645080-6cbd-11e9-8832-a6ef7163702d.png">

**Comment by NyakudyaA** [comment]
> @dimasciput @NyakudyaA @timlinux @helendallas @toniolsen
> 
> For the spatial filters, the subset of the NFEPA layers displayed is not correct.
> 
> The correct layers to include are shown below.
> 
> Layer descriptions can also be found here: http://bgis.sanbi.org/Search?searchterm=NFEPA
> 
> <img alt="Screenshot 2019-05-02 at 09 15 03" width="912" src="https://user-images.githubusercontent.com/44292029/57061472-42645080-6cbd-11e9-8832-a6ef7163702d.png">

@jeremyshelton the layers are identical because we sourced them on the bgis site.
Example
![rivers-2011](https://user-images.githubusercontent.com/2510900/57087805-2aaebb80-6d01-11e9-871f-de3c1fedf4c1.png)

And for the metadata I had previously added the description only but i can also include the purpose of the layer as depicted on the metadata for the layer.
![metadata](https://user-images.githubusercontent.com/2510900/57087989-8d07bc00-6d01-11e9-8195-d15ed5f6b02b.png)

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @timlinux @helendallas @toniolsen

Thanks. Yes, would be useful to include the purpose of the layers also 

The main issue is that at the moment these four NFEPA spatial filters on not available, but they should be. As it stands, only three wetland layers are available (see image below), but this is not correct, and these should be removed. 

<img width="470" alt="Screenshot 2019-05-03 at 06 49 20" src="https://user-images.githubusercontent.com/44292029/57120183-d7278680-6d6f-11e9-975a-7203cade251c.png">

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @timlinux @toniolsen 

The NFEPA layers on the site are still incorrect:

<img width="377" alt="Screenshot 2019-05-07 at 07 28 51" src="https://user-images.githubusercontent.com/44292029/57273998-099bf100-709a-11e9-804b-4932d1c3a923.png">


The Correct layers to be included are listed below, and ALL WETLAND LAYERS NEED TO BE REMOVED:
 
NFEPA Rivers 2011
NFEPA River NFEPAs 2011
NFEPA Fish sanctuaries 2011
NFEPA Fish sanctuaries (all species) 2011

**Comment by dimasciput** [comment]
Yes, I will have to fetch all the new layer data, and this will take several days to finished.

**Comment by jeremyshelton** [comment]
👍
