### ISSUE TITLE
Dashboard - geomorphological zone

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1225]
Please correct Geomorphological Zones to read Geomorphological Zone
![Screenshot_2019-05-03 Django BIMS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/57125962-abb29500-6d8b-11e9-808f-47dc9ec36cbf.png)

**Comment by helendallas** [comment]
In addition, the actual zone description should always be singular, so Lowland river; Upper foothill; Lower foothill etc.  NOT Lower foothills etc.

**Comment by dimasciput** [comment]
updated
