### ISSUE TITLE
Geomorphological zones - imported from Rivers Database

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1226]
Currently the default Geomorphological Zone for a site is generated from the spatial layer. This was derived as a desktop excercise and is probably 80% accurate. 

![Screenshot_2019-05-03 Django BIMS Map(5)](https://user-images.githubusercontent.com/45286876/57126915-04cff800-6d8f-11e9-9d5c-778c05654879.png)

Where sites have been assessed/ground-truthed, e,g, SASS or fish, the user may decide that the Geomorphological Zone is incorrect and wish to update it.  The old Rivers Database sites all have a "Longitudinal Zone" associated with them - this is the same as Geomorphological Zone (a more recent and correct name for the zones). Mostly the zones in Geomorphological Zone match Longitudinal Zone except, Unclassified = Unspecified; and there are three additional ones in the Rivers DB (Rejuvenated Foothill, Rejuvenated bedrock fall / cascades, and Upland Floodplain).  

Two things need to happen in relation to this. The existing zones from the Rivers Db need to be imported and assigned to each site; the functionality needs to be included to allow a user to update the Geomorphological zone for the site. @timlinux you will remember this from the workshop.

**Comment by helendallas** [comment]
It struck me that I am not 100% sure that the Geomorphological Zone (GZ) is derived from the spatial layer. I did a check of fish sites, and they all have GZ assigned to them, but they dont always match the coding. e.g. G2BANG-00001. It should be an Upper foothill, but is listed as Transitional
![Screenshot_2019-05-03 Django BIMS Map(6)](https://user-images.githubusercontent.com/45286876/57127728-917bb580-6d91-11e9-9f60-ba8d0cdccbd4.png)
 Similarly MOSS-00008 should be Lower foothill but it is listed as Upper foothill
![Screenshot_2019-05-03 Django BIMS Map(7)](https://user-images.githubusercontent.com/45286876/57127889-0949e000-6d92-11e9-84d9-f9fead614e43.png)
Please cna you check this and revert

**Comment by dimasciput** [comment]
cc @NyakudyaA

**Comment by timlinux** [comment]
> The existing zones from the Rivers Db need to be imported and assigned to each site; the functionality needs to be included to allow a user to update the Geomorphological zone for the site. @timlinux you will remember this from the workshop.

Yes @helendallas thanks we are looking at how to make this happen. I guess we need a site edit form....

**Comment by NyakudyaA** [comment]
> cc @NyakudyaA

@dimasciput Please use  `"key": "geo_class"` for spatial filters

**Comment by timlinux** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/178003/57290638-b9328c80-70b5-11e9-9663-4cd6323c03c6.png">

@helendallas I had a look at this with @dimasciput today. I think there are 3 things to take care of here:

1) @dimasciput and @NyakudyaA to verify and re-update site GZ values to ensure they have been assigned the correct values.

2) Manual GZ editing support 


It is going to take a bit of work to achieve hand editing properties for a site. Basically we propose to add an edit button on the site side panel:

<img width="424" alt="Screenshot 2019-05-07 at 11 02 03" src="https://user-images.githubusercontent.com/178003/57291682-ccdef280-70b7-11e9-9328-0620c321c3b0.png">

And on the site details in the dashboard:

<img width="531" alt="Screenshot 2019-05-07 at 11 21 17" src="https://user-images.githubusercontent.com/178003/57292850-e7669b00-70ba-11e9-9d1f-2369b64bd6c5.png">

When clicking edit we would get a similar view to the second screenshot above but each key (field) would have a combo box/pick list with a list of permissible values for that key.

Saving the edit form would save the site model properties, including the context value attributes.

3) Whenever a site's properties have been hand edited, those properties should be flagged as 'user defined' or similar and further automated updated should be prevented, those values should only be able to be hand edited from that point forward.

**Comment by NyakudyaA** [comment]
@helendallas The following is the attribute table for the geomorphological zone layer.
![data-1](https://user-images.githubusercontent.com/2510900/57312938-d59eeb00-70ee-11e9-9ccb-18dba4347b60.png)

Please note that there are no classes depicted as Source Zone, Upper, Lower etc. Those classes are only specified in the style that is attached to the layer.

![labels](https://user-images.githubusercontent.com/2510900/57313082-1e56a400-70ef-11e9-8ccd-7e281949933d.png)

Can you please confirm if the classification is consistent with your understanding of the data.

**Comment by helendallas** [comment]
Re Editing - this will be great for some Keys (fields) but I am not sure we want to allow users to edit all keys (fields). Probably only: Site coordinates, Site description, FBIS Site Code, Geomorphological Zone, River.

The others should perhaps not be editable? 

Then re Geomorphological classification - These are mostly consistent with those in the Rivers Database, except for singular for Upper foothill, Lower foothill.  Is it possible to modify in FBIS to all be singular. Then GZ layer - "Unclassified" = Rivers DB "Unspecified".  

Then there are three additional zones in Rivers DB that are not in the spatial layer (because they could not be generated using DTM). These need to be included in the drop down option for a user to select - (Rejuvenated Foothill, Rejuvenated bedrock fall / cascades, and Upland Floodplain), and migrated from the Rivers DB where they occur.

**Comment by timlinux** [comment]
So we agreed in our call last week that we would add an extra site record property "Refined geomorphological classification" that if not null would be used in preference to the one discovered in geocontext. We need to be able to edit this from a simple 'edit site' form linked from the single site side panel.

**Comment by dimasciput** [comment]
@timlinux @helendallas if only admin can edit this data, why don't we just add a link to the admin page for the selected site? I will do that instead for now.

**Comment by helendallas** [comment]
All users who created the site (site owners) users should be able to edit the Refined Geomorphological Classification, not just admin.
