### ISSUE TITLE
Sites Search Result - Number of assessments/SASS records? ? not Occurrences?

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1227]
Where sites are listed on the Search Result - occurrences are given.  
![Screenshot_2019-05-03 Django BIMS Map(9)](https://user-images.githubusercontent.com/45286876/57128180-e2d87480-6d92-11e9-87d3-9b1f3641c99c.png)
There are 9 assessments  with 270 occurrences for A1NGOT-DINOK. Confirmed by downloading of all data and there are 270 occurrences.
It would be better to reflect the number of SASS records as per the SASS dashboard.
![Screenshot_2019-05-03 Django BIMS SASS Dashboard Single Site(1)](https://user-images.githubusercontent.com/45286876/57128501-e3253f80-6d93-11e9-8f88-636d5be79e70.png)
Or a more generic form  - difficulty where some fish data have a single record. Essentially we need to be able to show how many times the site has been assessed, so need an indication of date/SiteVisit 
@timlinux thoughts?

**Comment by dimasciput** [comment]
@helendallas currently SASS records is SASS assessment number not collection records. So you want to change that to collection records number instead?

**Comment by helendallas** [comment]
Ideally we need to know how many times a site has been sampled = (so number of sampling dates) = each of these equals a SASS assessment. It is less meaningful to know how may individual SASS taxa were recorded, as SASS works as a group of bugs found at a site.  We should keep the **Occurrences** as well since this is the fish currency, and will be the currency once the invertebrate species data are also in.  Does it then make sense to reflect the **SASS Assessments** as you have done on the landing page dashboard. Or will this make it to complicated? @dimasciput

**Comment by dimasciput** [comment]
@helendallas 
If this is only for sass dashboard, then that should be quick. But if we change the search results, that's going to take a while. And I'm going to need updated search results layout with occurrences and the sass assessment. The search process itself will take a longer, because we will also need to access the sass table.

So, dashboard only : 1 hour less 
All search : 1-2 days

**Comment by helendallas** [comment]
The **Number of SASS Records** is already on the SASS dashboard for single sites

![Screenshot_2019-05-23 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/58236674-acfc2f80-7d43-11e9-82b1-c8ac32c53314.png)

Battling to run multi Site  - stalls at overview panel.

![Screenshot_2019-05-23 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/58237006-707d0380-7d44-11e9-8500-3c6f02674c53.png)


It would be good to include in All Search eventually - but lets leave for this version. @timlinux what do you think?

**Comment by dimasciput** [comment]
> @helendallas Battling to run multi Site - stalls at overview panel.

What's the url?

**Comment by helendallas** [comment]
I propose we close this. While it is useful to see the number of SASS assessments in the search result, it doesnt really make sense to do this for SASS only, when the other record currency is occurrence. The user cán see in the SASS form the Number of SASS Records
