### ISSUE TITLE
SASS Quality Check - issue 1

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1228]
Data integrity check of data migrated from Rivers DB. Site G1BERG-FRANS has an extra data that has been created for the 10 Jan 2007. I cant find it in the original Rivers DB. Looks like a whole lot of cumulative taxon data as SASS Score and No Taxa unrealistic.

Please can you check.

![Screenshot_2019-05-03 Django BIMS SASS Dashboard Single Site(3)](https://user-images.githubusercontent.com/45286876/57133267-8da45f00-6da2-11e9-8b48-6a6be70eb432.png)
![Screenshot_2019-05-03 Django BIMS SASS Dashboard Single Site(2)](https://user-images.githubusercontent.com/45286876/57133272-909f4f80-6da2-11e9-9fbf-0983ea7bbdad.png)
![Screenshot_2019-05-03 Django BIMS SASS Dashboard Single Site(4)](https://user-images.githubusercontent.com/45286876/57133369-dfe58000-6da2-11e9-8dab-645cf59bc287.png)

![Screenshot_2019-05-03 Django BIMS SASS](https://user-images.githubusercontent.com/45286876/57133276-9301a980-6da2-11e9-9acb-ecd5d9fe53b6.png)

**Comment by dimasciput** [comment]
@helendallas Yes I can find it from database 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/1979569/57177818-5b722a80-6e92-11e9-82c3-befd50c61bdb.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1979569/57177797-485f5a80-6e92-11e9-9da3-da92584bc528.png">

You can see the date is 10-01-2007

**Comment by helendallas** [comment]
Ok thanks. I see it. I will need to delete this site and sitevisit. It is clearly wrong. Not sure how it got into Rivers DB?
