### ISSUE TITLE
Validate spatial data used in spatial filters or map layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#1243]
# Problem

We are serving data that is coming from Sanbi, FRC and other third parties. Sometimes the attributes do not make sense or cannot be easily understandable.

This presents problems in that:
* Styling the layers is a challenge. We need styles that communicate a particular message with to the end user. 
* Geocontext - which relies on the attributes of layers at a particular location become useless.

I will list a few of the layers that I know here.

* Ecoregion2
![ecoregion2](https://user-images.githubusercontent.com/2510900/57303513-c95e6200-70dd-11e9-8651-2100c7236fef.png)

* Freshwater ecoregion of the world
![frsh_water](https://user-images.githubusercontent.com/2510900/57303604-fc085a80-70dd-11e9-81e8-b2adb4bb0f4b.png)

* surface_strategic_water_source
![surface](https://user-images.githubusercontent.com/2510900/57304569-dda35e80-70df-11e9-9864-66bd9374b21f.png)

I will add more layers here if I find them

# Solution

* We could edit the data to add more meaning - Drawback of this is that it is time-consuming and you need to know what you are changing.
* Publish as they are

cc @jeremyshelton @helendallas

**Comment by helendallas** [comment]
Sorry, I am not understanding. What is meant by styling? Is it the column headers?  Please explain @NyakudyaA

**Comment by NyakudyaA** [comment]
> Sorry, I am not understanding. What is meant by styling? Is it the column headers? Please explain @NyakudyaA

@helendallas What I meant is that when we have attributes like these ones
![Screenshot 2019-05-08 at 10 48 06](https://user-images.githubusercontent.com/2510900/57362314-d1221300-717e-11e9-9113-971a79b84a4d.png)

When we do styling for the layers we use the `column headers` as a way to distinguish the data. In this case, we will not be able to apply symbolization that is meaningful because the data contains only numbers. We do not have any name or type as headers.

Also when we do a drill down for a particular point where eg you will only see a number like the following

![Screenshot 2019-05-08 at 11 05 47](https://user-images.githubusercontent.com/2510900/57363582-a9807a00-7181-11e9-8f2f-96579459892a.png)

**Comment by NyakudyaA** [comment]
This has been clarified in the meeting
