### ISSUE TITLE
Better side panel legend management

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1248]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/178003/57358748-fce8cd00-716d-11e9-8f5a-b2f4da3c2677.png">

How about we rather add a colspanned row underneath each pie line and have just the title to the left of the charts?

<img width="411" alt="Screenshot 2019-05-08 at 08 49 01" src="https://user-images.githubusercontent.com/178003/57358914-594bec80-716e-11e9-824a-588ce55e83a2.png">

**Comment by helendallas** [comment]
Closing ticket as already actioned.
