### ISSUE TITLE
All dashboards should have a nice header

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1253]
In SASS multisite we have a nice header like this:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/178003/57376007-d5f2c100-7196-11e9-89c4-dd417d9adb86.png">

Please make sure the other dashboards use a similar header

**Comment by jeremyshelton** [comment]
Fish dashboard: single site
Fish Dashboard: multiple sites
Invertebrate dashboard: single site
Invertebrate Dashboard: multiple sites
SASS dashboard: single site
SASS Dashboard: multiple sites
Algae dashboard: single site
Algae Dashboard: multiple sites

**Comment by jeremyshelton** [comment]
The heading here should be 'Taxon Dashboard'

<img width="951" alt="Screenshot 2019-05-26 at 10 38 00" src="https://user-images.githubusercontent.com/44292029/58379438-93592300-7fa3-11e9-8f92-f4939cbf456b.png">
