### ISSUE TITLE
Critical Biodiversity Area (CBA) Layer 

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1256]
Please remove the current Critical Biodiversity Area (CBA) layers (circled below):

![Screen Shot 2019-05-09 at 1 52 13 PM](https://user-images.githubusercontent.com/43198125/57451609-14a17d80-7262-11e9-8d94-dcd2ddd98703.png)

And

Add the Western Cape **Protected Areas** layer found here under the Critical Biodiversity Areas heading:
http://bgis.sanbi.org/SpatialDataset/Detail/649

Then
Under the same heading (i.e. Critical Biodiversity Areas) have:

**Critical Biodiversity Areas
Ecological Support Areas**

So it looks like this in the spatial filters:
![Screen Shot 2019-05-09 at 2 17 11 PM](https://user-images.githubusercontent.com/43198125/57453303-56342780-7266-11e9-83d9-365ebda30e85.png)

But grey out Critical Biodiversity Areas and Ecological Support Areas as these layers are not ready. We will try get these layers for the next version.

 @NyakudyaA @dimasciput @timlinux @jeremyshelton @helendallas

**Comment by NyakudyaA** [comment]
@dimasciput Have published this and it's available in the CBA group

**Comment by toniolsen** [comment]
@dimasciput @NyakudyaA @jeremyshelton 

We have made progress in tracking down the correct Critical Biodiversity Area (CBA) and Ecological Support Area (ESA) layers. We will (hopefully) give these layers to you next week.

For now, please include the Protected Area layer as per the ticket. Then the CBA and ESA layers that you have at the moment are incorrect so they can be deleted. We will hopefully give you the correct CBA and ESA layers next week, but for now they can be greyed out. Thanks!

**Comment by dimasciput** [comment]
@NyakudyaA I still couldn't get the new data from geocontext.

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @toniolsen @helendallas 

Hi Dimas and Admire. I am at SANBI today working out exactly which CBA layers we need to serve. I will send these to you later today or tomorrow. Please hold off on the CBA layers until then. Thanks

**Comment by jeremyshelton** [comment]
Here is the structure for the CBA layers:

**National CBA layers**
-National CBAs
-National ESAs
**Provincial CBA layers**
- Eastern Cape
- Free State
- Gauteng
- KwaZulu-Natal
- Limpopo
- Mpumalanga
- North West
- Northern Cape
- Western Cape
**National protected areas layer**
- National layer

We will be sending these to Admire via WeTransfer.

@timlinux @NyakudyaA 
The tricky thing with these layers is that some of them (particularly some of the the CBA's and Protected Areas) can change over time. Andrew Skowno from Sanbi suggests "I’d suggest a simple python script to grab the latest SAPAD from DEAs website (2 x a year, June and Jan for example), then “flatten it” by  dissolving on a PA Type field". 

See: https://egis.environment.gov.za/data_egis/data_download/current

We can look at this for v3 (I will make a ticket now), but for v2 lets just serve up the layers that SANBI have made available at this point.

**Comment by dimasciput** [comment]
@NyakudyaA are the layers ready on the geocontext?

**Comment by NyakudyaA** [comment]
@dimasciput here is the protected area
![protected_areas](https://user-images.githubusercontent.com/2510900/58073647-738cbe00-7ba3-11e9-80c7-81b8125a6ab8.png)

As for the CBA I am still working on ingesting it but the way the data is structured I will need to chat with @toniolsen because she instructed me to ingest them as they are and I am not sure if we will need to add all of them into geocontext as they are

**Comment by dimasciput** [comment]
@NyakudyaA do we need freshwater ecoregion of the world in CBA ?

**Comment by NyakudyaA** [comment]
@dimasciput No. I will remove it. For the CBA I will first need to upgrade the server for postgres because we have run out of space and secondly we will need to add more layers in the CBA like

Hi Admire,

Here are the definitions for the four layers that most provinces should have: CBA1, CBA2, ESA1 and ESA2:

<img width="747" alt="Screenshot 2019-05-10 at 07 10 34" src="https://user-images.githubusercontent.com/2510900/58080403-6f689c80-7bb3-11e9-895a-9d65113fe1a3.png">


<img width="759" alt="Screenshot 2019-05-10 at 07 10 53" src="https://user-images.githubusercontent.com/2510900/58080452-9030f200-7bb3-11e9-95f5-ce2c30111915.png">


However, not all provinces have done things in the same way. Not all provinces have ESA2 (eg KZN, NC), some just have ‘ESA’, which should be labelled as ‘ESA1’. Others like WC doesn’t have CBA2. WE NEED TO SERVE UP THE LAYERS EXACTLY AS THEY ARE FOR EACH PROVINCE - NO MERGING PLEASE. See direct responses to your queries below...

Then, for the National-level data sets,
- CBA 1 and 2 and terrestrial and aquatic all lumped
- ESA 1 and 2 also lumped nationally 

<img width="343" alt="Screenshot 2019-05-20 at 10 54 48" src="https://user-images.githubusercontent.com/2510900/58080553-b5bdfb80-7bb3-11e9-9165-f04f7c6ab7f4.png">

<img width="313" alt="Screenshot 2019-05-20 at 11 03 27" src="https://user-images.githubusercontent.com/2510900/58080575-c4a4ae00-7bb3-11e9-8994-fb26f25c53e7.png">

<img width="417" alt="Screenshot 2019-05-20 at 11 01 11" src="https://user-images.githubusercontent.com/2510900/58080711-fa499700-7bb3-11e9-92a4-d9cdff68985f.png">

So they might be more than one CBA layer and Protected Areas - I am not sure if they want all the layers to be added as spatial filters

**Comment by NyakudyaA** [comment]
@jeremyshelton Have you looked at the structure of the national cba dataset. The only attribute that is different seems to be the source.
![cba](https://user-images.githubusercontent.com/2510900/58242475-2baa9a00-7d4f-11e9-86c2-000bf4cd5d64.png)

If I publish this and the layer is to be used as a spatial filter it will only be filtered according to the source?

**Comment by dimasciput** [comment]
Hi @jeremyshelton , any comment for this?

**Comment by jeremyshelton** [comment]
@dimasciput @dimasciput @toniolsen 

The important thing is that the user needs be able to filter by the CBA and ESA layers that exist for each province separately. Then they can also have the option to filter using the national CBA and ESA layers we sent, as well as the National Protected Areas (PA) layer we sent (see below). Does that answer the question?

<img width="487" alt="Screenshot 2019-05-27 at 06 47 31" src="https://user-images.githubusercontent.com/44292029/58396185-dd95df00-804b-11e9-9ddb-5a58067d1bc4.png">

**Comment by dimasciput** [comment]
What do you think @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@dimasciput In Geocontext we currently do not have the concept of a subgroup. So what I have started doing is to put these in their individual groups and you can then nest them in the code. In the future, it would be nice to have nested groups in geocontext.

![groups](https://user-images.githubusercontent.com/2510900/58399306-0cb24d80-8058-11e9-80d3-79268fa6af5e.png)

So far I still have to add registry for the provincial layers

**Comment by jeremyshelton** [comment]
@NyakudyaA and @dimasciput do you guys think it is realistic to have the **provincial layers** ready for FBIS v2? If too complicated, then one option is to hold this back for v3, and for now just serve the **national layers**?

<img width="487" alt="58396185-dd95df00-804b-11e9-9ddb-5a58067d1bc4" src="https://user-images.githubusercontent.com/44292029/58401157-6406ec80-805d-11e9-8371-f07293d82b7a.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton I have been looking at the attributes of the provincial CBA and some of the national layers. They seem to be all repeated across the tables.

eg eastern cape CBA 2
![cba2](https://user-images.githubusercontent.com/2510900/58413493-362fa100-8079-11e9-89de-2fa5ce0de8af.png)

EC cba1
![ec_cba1](https://user-images.githubusercontent.com/2510900/58413541-53646f80-8079-11e9-8234-b7de6e66c3e1.png)

We need a column that is unique to drive the filters.

**Comment by NyakudyaA** [comment]
@dimasciput this is all sorted, but the sticking point still remains the timeout issue in geocontext. I will look at it today. I have tried it a couple of days before but didn't have any luck. I have a couple of solutions that I need to try out.
* Increase spatial confirgurations in postgis.kartoza.com
* Scale geoserver using load balancer etc

**Comment by NyakudyaA** [comment]
@dimasciput I can you take a look at #1428 https://github.com/kartoza/geocontext/issues/97

**Comment by dimasciput** [comment]
Added coming soon information for version 2, will move this ticket to version 3 instead.

**Comment by NyakudyaA** [comment]
@dimasciput cc @jeremyshelton 
We can get the values now from geocontext. Can you fetch tme for the respective filters
![provincial-cba](https://user-images.githubusercontent.com/2510900/64342519-f6b71000-cfea-11e9-8e74-4a775b0a3791.png)

**Comment by NyakudyaA** [comment]
@jeremyshelton I think from this ticket it seems that I have got the three groups as specified in the ticket.

![firs](https://user-images.githubusercontent.com/2510900/64697180-830c7b80-d4a0-11e9-8ee2-861fb75a9e91.png)

![sec](https://user-images.githubusercontent.com/2510900/64697198-8acc2000-d4a0-11e9-86f7-74fda51032af.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA ok thanks for clarifying. 

Just a reminder of what these layers should contain: 

**National CBA layers**
-National CBAs
-National ESAs

**Provincial CBA layers (which may include CBA1, CBA2, ESA1, ESA2, ESA depending on province)**
-Eastern Cape
-Free State
-Gauteng
-KwaZulu-Natal
-Limpopo
-Mpumalanga
-North West
-Northern Cape
-Western Cape

**National protected areas layer**
-National layer (from the DEA)

**Important notes**
Not all provinces have done things in the same way. Not all provinces have ESA2 (eg KZN, NC), some just have ‘ESA’, which should be labelled as ‘ESA1’. Others like WC doesn’t have CBA2. WE NEED TO SERVE UP THE LAYERS EXACTLY AS THEY ARE FOR EACH PROVINCE - NO MERGING PLEASE. 

Then, for the National-level data sets:
- CBA 1 and 2 and terrestrial and aquatic all lumped
- ESA 1 and 2 also lumped nationally

@NyakudyaA does that make sense?

@dimasciput would be good to deploy soon so I can test and see that we are on the right track :)

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA 

Here are the layer descriptions for the CBA layers:

**CBA LAYER INFORMATION**
 
**General**
A CBA Map is a spatial plan for ecological sustainability. It identifies a set of biodiversity priority areas, called Critical Biodiversity Areas (CBAs) and Ecological Support Areas (ESAs), which, together with protected areas, are important for the persistence of a viable representative sample of all ecosystem types and species as well as the long-term ecological functioning of the landscape as a whole. CBA Maps are typically developed at the provincial, district or metropolitan scale, and are based on a systematic biodiversity plan. Map categories include PA (Protected Areas), CBA (Critical Biodiversity) and ESA (Ecological Support Areas). 
 
**PA**
Landscape-level purpose:  Formal long-term protection for important biodiversity and landscape features. Together with CBAs, ensures that a viable representative sample of all ecosystem types and species can persist. 
Broad management objective: Must stay in largely natural ecological condition. Details determined by the management plan that is required for each protected area.
 
**CBA**
Landscape-level purpose: Together with protected areas, ensures that a viable representative sample of all ecosystem types and species can persist.
Broad management objective: Must stay in largely natural ecological condition.
 
**ESA**
Landscape-level purpose: Ensures the long-term ecological functioning of the landscape as a whole.
Broad management objective: Must retain ecological processes, which often requires at least semi-natural ecological condition.
 
 
The distinction between CBA1 and CBA2 is based on irreplaceability, while the distinction between ESA1 and ESA2 is based on ecological condition. 
 
•      CBA1 are considered irreplaceable or near-irreplaceable for meeting biodiversity targets. There are no or very few other options for meeting biodiversity targets for the features associated with these areas. 
 
•      CBA 2 are areas that have been selected as the best option for meeting biodiversity targets, based on complementarity, efficiency, connectivity and/or avoidance of conflict with other land or resources uses.
 
•      ESA1 areas are currently in either good or fair ecological condition, for which the objective is to retain them in at least fair ecological condition. 
 
•      ESA2 are currently in severely modified ecological condition but that nevertheless retain sufficient ecological functioning to fulfil the purpose for which the ESA was selected. The objective is to prevent further deterioration in ecological condition.
 
The CBA layers served here originate from SANBIs BGIS online resource, and the national PA layer comes from the Department of Environmental Affairs (DEA) site.

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @timlinux 
Hi guys, just following up on progress with the CBA filters. The plan was to get the CBAs up on the testing site so we can test them. I see they are not up yet. Have we hit a stumbling block, or is this still on track? I can sit with Admire and work though any queries if need be - let me know?
@toniolsen @helendallas

**Comment by dimasciput** [comment]
Hi @jeremyshelton , I'm currently fetching the cba layers in the testing server, it might take a while to show up on the site.

**Comment by NyakudyaA** [comment]
This should be ready to close

**Comment by jeremyshelton** [comment]
@NyakudyaA @dimasciput 

Spatial>Critical Biodiversity Area (CBA): National

- Change filter names as per screenshot 

![Picture3](https://user-images.githubusercontent.com/44292029/79850638-823bb080-83c4-11ea-8ede-8f0df8256c90.png)

- Ecological Support Areas (ESA): @NyakudyaA (1) should there not be more categories within the ESA drawer? (2) Map does not load when I select this layer?

- National Protected Areas (PA): blank category needs to be deleted.

![Picture2](https://user-images.githubusercontent.com/44292029/79850779-aeefc800-83c4-11ea-9856-ef96b1dc24b7.png)

 
Critical Biodiversity Area (CBA): Provincial

- Western Cape is missing
![Picture3](https://user-images.githubusercontent.com/44292029/79850800-b911c680-83c4-11ea-8e03-ab0d1cdc1409.png)

**Comment by NyakudyaA** [comment]
> @NyakudyaA @dimasciput
> 
> Spatial>Critical Biodiversity Area (CBA): National
> 
>     * Change filter names as per screenshot
> 
> 
> ![Picture1](https://user-images.githubusercontent.com/44292029/79850900-d6469500-83c4-11ea-9a08-4f1b85ec81cd.png)
> 
>     * Ecological Support Areas (ESA): @NyakudyaA (1) should there not be more categories within the ESA drawer? (2) Map does not load when I select this layer?
> 
>     * National Protected Areas (PA): blank category needs to be deleted.
> 
> 
> ![Picture2](https://user-images.githubusercontent.com/44292029/79850779-aeefc800-83c4-11ea-9856-ef96b1dc24b7.png)
> 
> Critical Biodiversity Area (CBA): Provincial
> 
>     * Western Cape is missing
>       ![Picture3](https://user-images.githubusercontent.com/44292029/79850800-b911c680-83c4-11ea-8e03-ab0d1cdc1409.png)

@dimasciput If I change these names in Geocontext do they automagically reflect in the front end and how does it affect fetching values. If you give the go ahead I can change the names
