### ISSUE TITLE
We need a 'report an issue' link on the menu bar

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1269]
We need to usher users who encounter issues over to the github issue tracker:

https://github.com/kartoza/django-bims/issues/new

**Comment by jeremyshelton** [comment]
Will this be a link via the menu bar?

**Comment by timlinux** [comment]
In discussion today we will rather:

* Add a Help link on top menu
* Link should point to a static page
* Tim to add initial content

**Comment by dimasciput** [comment]
@timlinux the link is in http://testing.healthyrivers.kartoza.com/pages/help/, you can edit the content here : http://testing.healthyrivers.kartoza.com/admin/flatpages/flatpage/2/change/

**Comment by timlinux** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/178003/60431574-00418780-9bf8-11e9-9378-d2fcc523fe8f.png">

**Comment by timlinux** [comment]
<img width="629" alt="Screenshot 2019-07-01 at 12 51 38" src="https://user-images.githubusercontent.com/178003/60441088-27a34f00-9c0e-11e9-9a29-08512ae5c855.png">

**Comment by toniolsen** [comment]
@timlinux @dimasciput 
We still don't see a tab on the menu bar for this?

@jeremyshelton

**Comment by dimasciput** [comment]
Report an issue button is in Help page
