### ISSUE TITLE
Freshwater Ecoregions of the World Layer

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1271]
@NyakudyaA @dimasciput @timlinux 
We have transferred the correct Freshwater Ecoregions of the World layer, with the attribute table that has the actual names of the Ecoregions.

Use this link: https://wetransfer.com/downloads/cd7d41dc7b4670f469152f04ae3f902520190513133402/dd05461cdb432795fa9a9e1f4cec626e20190513133402/034bc3
The shapefile to use is named: feow_gis.shp

@jeremyshelton @helendallas

**Comment by dimasciput** [comment]
@NyakudyaA is this ready?

**Comment by NyakudyaA** [comment]
@dimasciput this is ready you can see from the getfeature info you did earlier here
![image](https://user-images.githubusercontent.com/1979569/58070759-7d72e900-7bc4-11e9-87b0-be119f84cc83.png)

And also here
![protected_areas](https://user-images.githubusercontent.com/2510900/58073832-f281f680-7ba3-11e9-9c50-dbc9aad85ed0.png)

**Comment by dimasciput** [comment]
@NyakudyaA https://geocontext.kartoza.com/api/v1/geocontext/value/group/24.48/-33.78/freshwater_ecoregion_of_the_world/ still very slow at the moment, I couldn't update the site with this api.

**Comment by NyakudyaA** [comment]
@dimasciput closing this now as I have fixed this
![fixed-few](https://user-images.githubusercontent.com/2510900/58248496-91e9e980-7d5c-11e9-91d1-62787f8c541b.png)
