### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1274]
@dimasciput @timlinux @toniolsen 

Attached please see new text and images for the About page. This should replace the content currently on the about page.

[About page.docx](https://github.com/kartoza/django-bims/files/3175792/About.page.docx)

**Comment by dimasciput** [comment]
You can change this directly from the admin page.

**Comment by toniolsen** [comment]
Images for About Page:
1.)
![image](https://user-images.githubusercontent.com/43198125/57832995-4910be80-77b9-11e9-9508-433238d4e738.png)

2.) 

![image](https://user-images.githubusercontent.com/43198125/57833023-604fac00-77b9-11e9-9269-6704759e41d2.png)

3.)
![image](https://user-images.githubusercontent.com/43198125/57833072-81180180-77b9-11e9-8514-0872b5d3a149.png)

4.)
![image](https://user-images.githubusercontent.com/43198125/57833116-9db43980-77b9-11e9-86c9-79f3c1940a34.png)

5.)
![image](https://user-images.githubusercontent.com/43198125/57833178-be7c8f00-77b9-11e9-96d9-2ba81050be06.png)

**Comment by dimasciput** [comment]
Updated
