### ISSUE TITLE
Partners and funders logos 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1275]
Partners and funders logos section needs to be moved from the home page to the bottom of the about page. 
<img width="1398" alt="Screenshot 2019-05-14 at 06 35 28" src="https://user-images.githubusercontent.com/44292029/57671110-94d53380-7612-11e9-9b09-0959e63fdbf7.png">

**Comment by timlinux** [comment]
Makes https://github.com/kartoza/django-bims/issues/1269 redundant

**Comment by jeremyshelton** [comment]
Toni has updated the content on the abut page. Can you guys please move the partners and funders panel across to the About page? We are not sure how to do it...
