### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1286]
@dimasciput @toniolsen @timlinux 

**Menu bar and logo**
<img width="1440" alt="Screenshot 2019-05-20 at 12 06 04" src="https://user-images.githubusercontent.com/44292029/58013968-0bcd6900-7af8-11e9-928a-b5db7a808fa1.png">

![FBIS v2 Logo Dimas](https://user-images.githubusercontent.com/44292029/57827124-64be9980-77a6-11e9-9b1b-4daea154c387.png)

**Favicon**
Use this favicon for the website, please:

![FBIS favicon](https://user-images.githubusercontent.com/44292029/58014141-6cf53c80-7af8-11e9-87fa-a370ca04511d.png)

**Buttons on image**
<img width="673" alt="Screenshot 2019-05-15 at 13 16 06" src="https://user-images.githubusercontent.com/44292029/57790382-e8db3780-773a-11e9-8d0e-deaaa38a3b6f.png">

**Module icons**
Use new charcoal icons throughout, including dashboards and filters. I can email .eps files if needed?
![icons](https://user-images.githubusercontent.com/44292029/57790343-d52fd100-773a-11e9-9bf4-aaa0504a602b.png)

Please use Charcoal font (same colour as biodiversity records), and use #18A090 (from Carina's palette) where another font colour is needed.
<img width="845" alt="Screenshot 2019-05-15 at 18 52 22" src="https://user-images.githubusercontent.com/44292029/57793998-f2689d80-7742-11e9-92dd-5bada36a3330.png">

**Footer**
Swap out logo
<img width="1440" alt="Screenshot 2019-05-15 at 18 47 10" src="https://user-images.githubusercontent.com/44292029/57793630-1bd4f980-7742-11e9-95bd-416bb61903c7.png">

**Comment by dimasciput** [comment]
@jeremyshelton can you email me the module icons with transparent background ? Or just attached it here.

**Comment by jeremyshelton** [comment]
@dimasciput I have sent the icon image files to you in an email called ‘vectors’. Let me know if you would prefer them in a different format?

**Comment by dimasciput** [comment]
@jeremyshelton oh didn't notice that, sorry. Thanks, that will do.

**Comment by jeremyshelton** [comment]
@dimasciput 👍

**Comment by dimasciput** [comment]
@jeremyshelton 
> Please use Charcoal font (same colour as biodiversity records), and use #18A090 (from Carina's palette) where another font colour is needed.

Which text you want to change the color to #18A090 ?

**Comment by dimasciput** [comment]
@jeremyshelton here's what it look like now (still in my local) : 

![image](https://user-images.githubusercontent.com/1979569/58072365-a9dd3400-7bc9-11e9-8414-bc76f2069784.png)

**Comment by jeremyshelton** [comment]
Dimas, 

That still looks like the old icons? (see new ones in email called 'vectors'). The colour #18A090 should be used instead of the dark green colours currently in use (throughout the home page, map and dashboards). We need to try stick to Carina's colour palette for the font colours. Make sense?

<img width="208" alt="Screenshot 2019-05-22 at 09 24 38" src="https://user-images.githubusercontent.com/44292029/58155157-a1d9ce80-7c73-11e9-82a8-daf2d1daed89.png">

**Comment by jeremyshelton** [comment]
@dimasciput 

<img width="733" alt="Screenshot 2019-05-23 at 05 43 34" src="https://user-images.githubusercontent.com/44292029/58224511-57f9f280-7d1e-11e9-943f-32c337d3c6f5.png">

**Comment by jeremyshelton** [comment]
@dimasciput 
<img width="432" alt="Screenshot 2019-05-23 at 05 49 41" src="https://user-images.githubusercontent.com/44292029/58224613-bf17a700-7d1e-11e9-8bc8-f5f5e84a244f.png">

**Comment by jeremyshelton** [comment]
Please swap out home page image to this one (should be scaled correctly already)

![fbis homepage v2](https://user-images.githubusercontent.com/44292029/58452811-020bbd00-8119-11e9-933d-0a261dd1ea8e.JPG)

**Comment by dimasciput** [comment]
Updated https://github.com/kartoza/freshwaterbiodiversity.org/pull/320
