### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1289]
@dimasciput @timlinux @toniolsen 
**Graph colours**
Is it possible to use FBIS colour scheme in all graphs? This is an issue in both fish and SASS dashboards. 
<img width="883" alt="Fish dashboard - multiple sites" src="https://user-images.githubusercontent.com/44292029/57793360-6d30b900-7741-11e9-907e-c3d26ec0f77a.png">

**Graph format**
Some graphs on fish and SASS dashboards have inconsistent formatting
<img width="694" alt="Screenshot 2019-05-15 at 17 09 30" src="https://user-images.githubusercontent.com/44292029/57793482-b41eae80-7741-11e9-9faf-2bbb4358e0f2.png">

**Comment by dimasciput** [comment]
@jeremyshelton The colour we used is actually randomized for the taxa charts because there will be a lot variables.

**Comment by jeremyshelton** [comment]
OK, I understand. But would it be possible to somehow keep the colours within the FBIS palette, by using variations of these? 
<img width="751" alt="Screenshot 2019-05-07 at 14 52 40" src="https://user-images.githubusercontent.com/44292029/57827662-6f7a2e00-77a8-11e9-9a1d-c3404ac2838f.png">
