### ISSUE TITLE
Spatial layer sustainability 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1290]
@timlinux @helendallas @NyakudyaA 

For v3, we need come up with a plan to keep up to date with some of the conservation-type layers (like protected areas) that can change every few months. 

Only a subset of the layers will come with this challenge. 

For example, Protected areas: Andrew Skowno from Sanbi suggests "I’d suggest a simple python script to grab the latest SAPAD from DEAs website (2 x a year, June and Jan for example), then “flatten it” by dissolving on a PA Type field".

See: https://egis.environment.gov.za/data_egis/data_download/current

**Comment by NyakudyaA** [comment]
@jeremyshelton We can manage this by just adding a date field in the dataset whilst ingesting them then we serve up the latest one all the time unless there is need to also show the old layers

**Comment by jeremyshelton** [comment]
OK thanks Admire. That sounds perfect. This will probably be neccesary for the CBAs (BGIS), PAs (DEA) and NFEPAs (BGIS)m WMAs and WSAs.

**Comment by jeremyshelton** [comment]
We need to work towards including a hyperlink and metadata all layers and an algorithm that annually, checks for an update.

**Comment by helendallas** [comment]
Long term this should be addressed by training SANBI GIS personnel to manage the spatial layers. Closing this ticket
