### ISSUE TITLE
Search inconsistency when filtering by province

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1297]
Search for Clarias gariepinus with no spatial filters we can see a bunch of records in wcape:

<img width="1680" alt="Screenshot 2019-05-20 at 15 40 11" src="https://user-images.githubusercontent.com/178003/58030131-f0715680-7b15-11e9-85c4-665a3e227ab2.png">

Now add filter by western cape:

<img width="1680" alt="Screenshot 2019-05-20 at 15 40 30" src="https://user-images.githubusercontent.com/178003/58030617-c704fa80-7b16-11e9-83f2-507654e9bf48.png">

You see all the items that were previously shown in the wcape have gone. Are our context records for provinces correct?

**Comment by dimasciput** [comment]
@timlinux yes this is new sites when I reingest the fish data, I haven't fetched from geocontext again.

**Comment by dimasciput** [comment]
Fixed in testing 
![image](https://user-images.githubusercontent.com/1979569/67448248-a1899900-f640-11e9-9c38-9a29ded6629d.png)
