### ISSUE TITLE
Refined geomorphological zone needs a pick list

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1306]
Can you make a zone_type model so that it uses a pick list
and give Helen an admin page that she can manage the zones lookup
and pre-populate it with unique names from the zones shp?
I dont think it will work well just allowing free form text there

<img width="976" alt="Screenshot 2019-05-21 at 11 30 29" src="https://user-images.githubusercontent.com/178003/58089101-ee61d300-7bbb-11e9-8524-73d74f0cb8c9.png">

**Comment by helendallas** [comment]
It would be good to allow the user that created the Site to be able to select the Refined Geomorphological Zone from the picklist on the Site Form.

Then it should also be included in the fields that a superuser is able to edit

**Comment by helendallas** [comment]
DOne
