### ISSUE TITLE
Inconsistency in invert site count

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1307]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/178003/58090234-b0b27980-7bbe-11e9-90e8-1c6c3f292f0b.png">

<img width="639" alt="Screenshot 2019-05-21 at 11 51 23" src="https://user-images.githubusercontent.com/178003/58090291-cf187500-7bbe-11e9-9fb6-aeeb09d56dfa.png">

**Comment by dimasciput** [comment]
fixed
