### ISSUE TITLE
Landing page - Invertebrate records, sites, SASS assessments

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1308]
Please check the number here - they do not match with records when selected by filtering on module - invertebrate. We could leave it, but it sends a false message, so if relatively easy to figure out then please include in next version 2.
![Screenshot_2019-05-21 FBIS Home(1)](https://user-images.githubusercontent.com/45286876/58093594-160e6680-7bcf-11e9-9a55-9c99054cd54e.png)
![Screenshot_2019-05-21 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/58093680-4f46d680-7bcf-11e9-925e-1f33be4b0b9b.png)

**Comment by dimasciput** [comment]
Fixed in testing
