### ISSUE TITLE
SASS Site descriptions - wrong

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1310]
Site descriptions are not displaying correctly . e,g E2BOON-BILLB

Should be 
"Mainstream Boontjies River, u/s of main impoundment (at Bills Balcony) & d/s of confluence with the Perdekraal" 

but instead is
 
"SASS 4 total scores from report : A preliminary assesment of the current status of the Boontjies River, Bushmans Kloof Private Game Reserve, with particular reference to the translocation of indigenous fish species"

Many others are blank, whereas it was a compulsory field in the old Rivers DB.

See MS Access shot below:
![image](https://user-images.githubusercontent.com/45286876/58096873-57564480-7bd6-11e9-9804-4eccb1c07cc2.png)

**Comment by dimasciput** [comment]
@helendallas 
Yes that was site name in our database, 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1979569/58098566-0eb58000-7c04-11e9-883b-616ed857571f.png">

So you want that as site description instead?

**Comment by helendallas** [comment]
In the original Rivers db, it seems like the column "Site" is actually the "Site Description".  Which seems to be what is called Name in FBIS. I reckon lets keep it the same: so **Site Description**.
I reran the MS access query and what you have included as the Site Description in FBIS is actually "CommentsSiteGeneral"  in the Rivers DB, which should become our "Comments" field....do we have one?. DO we need one?  See MS access screenshot below where I generated a table from the legacy River DB
![image](https://user-images.githubusercontent.com/45286876/58103111-b621bb00-7be2-11e9-87f0-a41a05793815.png)

**Comment by helendallas** [comment]
In some instances the "Comment" is actually the Study Reference, so this may require some sorting out which we can do manually. As long as we have the Site Description correct for this release that should be fine
