### ISSUE TITLE
Download Summary SASS Data - accredited

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1311]
We need the following columns populated:

Accredited

**Comment by dimasciput** [comment]
@helendallas And where this is coming from? From the assessor accredited status?

**Comment by helendallas** [comment]
In the Rivers Database there was a table UserSASSValidation, which included a "Valid from", "Valid to" and "Status" columns.  This was used to specify if the data SASS data collected by done by a "Validated"person - in terms of status.

I am trying to generate an MS ACCESS query but battling to get it work.

**Comment by helendallas** [comment]
Okay got it to work, query then datasheet



![image](https://user-images.githubusercontent.com/45286876/58170063-b8dbe900-7c92-11e9-8ce2-027a63984bcc.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/58170215-17a16280-7c93-11e9-9c2b-5699d30c9efe.png)

**Comment by dimasciput** [comment]
@timlinux @helendallas ok, this is gonna take a while since we didn't imported the user_sass_validation to our db. And then I need to modify our user model. So probably it will take like half a day for this issue. If you think this is high priority, plus put this ticket higher. I will work on this next week.

**Comment by helendallas** [comment]
It is important especially since it will be included going forward because we need to know if the SASS data captured has been assessed by a person who is SASS Accredited or NOT. An accreditation is a test, the person has to pass, and then it is valid for 3 years. They need to redo the test before their accreditation expires. SASS data they upload then gets stamped as SASS Accredited (Yes) or Not SASS Accredited (No).  We are hoping users will upload data, so the system needs to be in place to flag all SASS data as coming as Y or N. I will move up list.

**Comment by helendallas** [comment]
I am happy for you to sort smaller tickets first, as long as there is still time to include this before the release. I moved it to the top, but feel free to restructure @dimasciput

**Comment by dimasciput** [comment]
Hi @helendallas, what status is used for (Quality assurance)? We can get the accreditation status just from valid from and valid to right?

**Comment by dimasciput** [comment]
Ok I will only stored the valid from and valid to dates.

**Comment by helendallas** [comment]
@dimasciput  - sorry traveling. Yes SASS accreditation is used for Quality Assurance - a user needs to be able to select SASS accredited or SASS non-accredited data for the quality control. All CSV files alsoneed to specify this.

I was trying to check the site to remind myself how it is used in validation.   @timlinux - please confirm work flow as per our previous discussions

**Comment by dimasciput** [comment]
@helendallas for now I only stored the valid_from and valid_to dates, here's the summary : https://github.com/kartoza/django-bims/pull/1358

I have updated it in testing.
