### ISSUE TITLE
SASS csv download - Download Summary data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1314]
Please revise the columns for the csv file. For single and multiple sites

![image](https://user-images.githubusercontent.com/45286876/58152066-d0ec4200-7c6b-11e9-92b4-20ff17ea6874.png)

**Fields are currently:**
Fbis site code
Site description (wrong needs to be updated as per ticket #1310)
River name         
Latitude               
Longitude            
Sampling date    
Time of day        
Accredited           
Sass version        
Sass Score           
Number of taxa 
Aspt       
Reference category         
Study reference
Assessor              
Stones in current              
Stones out of current      
Marginal vegetation in current    
Marginal vegetation out of current           
Aquatic vegetation          
Gravel   
Sand      
Mud       
Tertiary catchment area 
Water management area             
Primary catchment area
Secondary catchment area          
Nfepa wetlands 2011      
Geomorphological zones - recoded          
National critical biodiversity         
Ecological regions            
Strategic water source areas - surface     
Geomorphological zones              
Strategic water source areas - ground

**Fields should be:**
Filter history: all spatially filtered geocontext data
FBIS site code
Site description
River name
Geomorphological   zone (this is the one from the spatial layer)
Geomorphological   zone – ground-truthed (added by user)
Latitude
Longitude
Sampling date
Time of day
Accredited:   Y/N
SASS version: 4 or 5
Collector/Assessor
SASS Score
Number of taxa
Ecological category
Stones in current
Stones out of current
Bedrock
Marginal vegetation in current
Marginal vegetation out of current
Aquatic vegetation
Gravel
Sand
Mud
Reference category
Study reference

**Comment by dimasciput** [comment]
@helendallas 
no bedrock from database 
![image](https://user-images.githubusercontent.com/1979569/58165480-15023580-7cb2-11e9-85a3-24ff1520a3d1.png)
