### ISSUE TITLE
SASS Single Site - download png

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1319]
Please check and advise the user where this png goes? It is not obvious to the user
![image](https://user-images.githubusercontent.com/45286876/58152838-da76a980-7c6d-11e9-81f7-175aeb83acbf.png)

**Comment by dimasciput** [comment]
@helendallas 
It will download the png to your computer? I didn't get the question.

**Comment by helendallas** [comment]
It was not downloading on my pc. I will retest when FBIS is back online and also ask Toni to test as it may be my PC issue.
