### ISSUE TITLE
Ecological category - combined duplicated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1321]
Please check why there are two Western Bankenveld - combined graphs.  There should presumably only be one as ecological categories have not yet been developed for upper and lower zones.

Western Bankenveld only has a combined category – but sites are split into two different WB  -combined???

![image](https://user-images.githubusercontent.com/45286876/58153394-2fff8600-7c6f-11e9-9281-bf517bb40425.png)

**Comment by dimasciput** [comment]
@helendallas what the url for this? If you provide me the link or how to produce bugs, it will save me a lot of time.

**Comment by helendallas** [comment]
Filter on SA Ecoregion 1, select Western Backenberg; then select Invertebrate module, then go to detailed SASS Dashboard.

I am not sure how to send the url
