### ISSUE TITLE
Ecological category - SASS Multi Site dashboard 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1322]
Can you reorder A to E/F on Multi Site SASS dashboard as per Single Site dashboard . 

![image](https://user-images.githubusercontent.com/45286876/58153497-77861200-7c6f-11e9-9d53-f7e21146caea.png)

![image](https://user-images.githubusercontent.com/45286876/58153505-7bb22f80-7c6f-11e9-94df-cefe4b0cb885.png)

**Comment by dimasciput** [comment]
Fixed in testing
