### ISSUE TITLE
Ecological category - hover text

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1323]
Then can you add a “hover” explaining where this is derived from as follows:  
**Ecological categories are based on interpretation of SASS data using Dallas (2007) SASS data interpretation guidelines**
Hover over **Ecological Category**
![Screenshot_2019-08-01 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/62284088-3f5f3480-b453-11e9-82f4-270e7a196d26.png)
Please can you provide information about ecological categories: 

And if possible include a narrative as per the table originally sent: so A: Natural      B: Good    etc  or if easier do the hover over for each

Ecological Category | Ecological Category Name
A - Natural
B - Good
C - Fair
D - Poor
E/F - Seriously/Critically modified

**Comment by dimasciput** [comment]
Where do I put this text?

**Comment by helendallas** [comment]
SASS Dashboard @dimasciput 

![Screenshot_2019-07-29 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/62055757-8a433700-b21c-11e9-8053-2f21ec88ed68.png)

And on landing page:

![Screenshot_2019-07-29 FBIS Home](https://user-images.githubusercontent.com/45286876/62055840-a9da5f80-b21c-11e9-8803-3442bf9e8aac.png)

**Comment by helendallas** [comment]
![Screenshot_2019-08-01 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/62284189-746b8700-b453-11e9-9766-e2d6bc6a3f08.png)

Then can you add a “hover” explaining where this is derived from as follows:  
**Ecological categories are based on interpretation of SASS data using Dallas (2007) SASS data interpretation guidelines**
Hover over **Ecological Category**

**Comment by timlinux** [comment]
Lets use text under the legends etc instead of hovers so that the data shows up in the report.
