### ISSUE TITLE
Module selection - Fish / SASS reports

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1325]
If a user selects the Fish Module – the SASS Dashboard button should be greyed out on the overview panel, because if you then open it, there is no data shown.

Similarly if one select the Invertebrate Module, the Fish Dashboard button should be greyed out on the overview panel, because if you then open it, there is no data shown.

![image](https://user-images.githubusercontent.com/45286876/58154110-1c551f00-7c71-11e9-99a5-3c643296b02a.png)

**Comment by dimasciput** [comment]
Fixed in testing by removing some taxa from invert group : 
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1979569/58447542-dd224480-812e-11e9-8e19-4dc24e7e59a1.png">

**Comment by helendallas** [comment]
I checked now and SASS dashboard is still clickable, when fish module is selected - please check
![Screenshot_2019-05-28 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/58449232-edc0c380-810a-11e9-97d9-949b77348532.png)
![Screenshot_2019-05-28 FBIS Map](https://user-images.githubusercontent.com/45286876/58449235-ef8a8700-810a-11e9-8e6e-ef64737c8a89.png)

**Comment by helendallas** [comment]
@dimasciput

**Comment by timlinux** [comment]
Is it deployed @dimasciput ? I still see

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/178003/58474759-f8e41580-8143-11e9-83a2-330e7b61b9c0.png">


I would expect fish to be grayed out

**Comment by dimasciput** [comment]
@timlinux this is only for the multi site dashboard, that's why I only sized this ticket 1. For the single site dashboard, it will take longer time since I didn't make that one. I have to refactored Christiaan's code.

**Comment by helendallas** [comment]
This seems to be sorted.
