### ISSUE TITLE
We need to find out why the river names are in Afrikaans

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1328]
Please investigate whether we can obtain a rivers dataset with english names

**Comment by NyakudyaA** [comment]
Sent an email to NGI to ask about this and Also tried to call. Will keep on calling during the day to confirm the status of this

**Comment by NyakudyaA** [comment]
@timlinux I had a chat with one of the guys from NGI with regards to this. The names that occur in the rivers layers are the common names associated with that river. So the name can either be in English or Afrikaans based on the field verification.

And NGI does not have any dataset that distinguishes names in different languages, this is done by another department

**Comment by NyakudyaA** [comment]
Moved this to the backlog because no such dataset exists in SA

**Comment by MikeSilberbauer** [comment]
Sorry, I did not see this when it was first posted.
The river names were the most recent ones available at the time they were edited - see history on http://www.dwa.gov.za/iwqs/gis_data/river/rivs500k.aspx - when newer names or spelling were announced, the old name was moved to an alias field and the new version put in the name field. Official names are allocated by the South African Geographical Names Council, which used to operate a website with tables of old and new names. We used this resource until RQIS stopped editing the rivers in 2012. I have not been able to find the website recently.
Note that river names are in a multitude of languages, and many rivers have different names along their course, e.g. Senqu-Orange or Moreleta-Pienaars-Moretele.

**Comment by timlinux** [comment]
Thanks for this background info @MikeSilberbauer 
@NyakudyaA maybe you can track down someone from SAGNC and see if they can share a copy of the names database?

**Comment by NyakudyaA** [comment]
I am moving this to the backlog as we will not implement until we find such a dataset which is highly unlikely to be available

**Comment by helendallas** [comment]
Closing ticket as we will action only if and when we get a better dataset
