### ISSUE TITLE
We need an alias system for site codes

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1329]
When a user changes a site code, the old code should be preserved and made available as an alias. The search on site codes should use both current and aliases so that if there is, for example, a scientific paper that references a site code that has since been updated, we can still find the site by its original name.

The single site views should include the known aliases as an additional site metadata item.

**Comment by helendallas** [comment]
@timlinux 
I don't think this is necessary as long as we can include an Original Site Code below FBIS Site Code on the Create a Site form, and which is then shown on all detailed report dashboards. I will create a separate ticket for this now as it is different to this one.

The user then has access to their original Site Code (so they can back track to a report) but it forces them to standardise the Site Code name, which is what we need to do.
