### ISSUE TITLE
Quinary catchments need updating

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1331]
Please make sure we are using the correct quinary layer and update context etc. We should have a quinary catchment id.

<img width="615" alt="Screenshot 2019-05-22 at 10 45 52" src="https://user-images.githubusercontent.com/178003/58165020-d0a97200-7c7e-11e9-8742-c746c3980a9b.png">

**Comment by NyakudyaA** [comment]
Fixed
![catch](https://user-images.githubusercontent.com/2510900/58238776-29910d00-7d48-11e9-8d20-fab7eb9a7d8f.png)
