### ISSUE TITLE
Time stamp for data uploaded after the V2 Release

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1334]
@timlinux, as discussed today, we would like to have a time stamp or some way of knowing when people upload data after Version 2 has been released. 

A time stamp somewhere or even a "date captured" field on the SASS/fish form would be good for the user to fill in the exact date that they are uploading their data. This will help us differentiate between the data already in the system and newly uploaded data.

@dimasciput @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
We already have this field named 'collection_date', and it will automatically set the date to current if user didn't fill it.
