### ISSUE TITLE
Access control of users after V2 release

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1335]
Users can browse FBIS without creating an account/signing up, but if they would like to upload data they need to create an account/sign up.

We think the best way to control access to upload data initially would be for us to do it internally at FRC.

If someone wants to sign up, can an email be sent to FRC (at fbis@frcsa.org.za) and then from our side follow an easy process to give or refuse access to that user? Maybe we could follow a link or just click a button?

We also think the "Organisation" field should be a mandatory field. We will provide a list of organisations to include in a drop down box for the users to select. Down the line access will most probably be automated using the organisation field.

But for now, we will do it manually on our side. 

@timlinux @dimasciput @jeremyshelton @helendallas

**Comment by helendallas** [comment]
We will also need to a button for a user to "Add Organisation" if their's is not displayed in the drop-down list
