### ISSUE TITLE
SIte Information under map 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1338]
![Screenshot_2019-05-22 FBIS SASS Dashboard Single Site(2)](https://user-images.githubusercontent.com/45286876/58191227-6dd7cb00-7cbe-11e9-9084-aa762294dee3.png)

Why are some not populated, e.g. Province, Quaternary catchment
Also this is not yet the final list that we decided on.
Is this still under construction and will work once all the spatial layers are added?

**Comment by dimasciput** [comment]
Hi @helendallas , could you copy the final list here, thanks.

**Comment by timlinux** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/178003/58796798-30e0d200-85f6-11e9-83d3-84d3f389ff4f.png">

@dimasciput also we are still getting blank entries on sites

**Comment by timlinux** [comment]
Also adjusted geomorphological zone should be shown in the list.

**Comment by toniolsen** [comment]
![Screenshot 2019-06-03 at 15 46 11](https://user-images.githubusercontent.com/43198125/58806937-7792f400-8617-11e9-9598-0d8d13d3157b.png)

This is the list for the table in the site dashboards.
@dimasciput @timlinux @helendallas @jeremyshelton

**Comment by helendallas** [comment]
SO we need the original Geomorphological Zone, and then, in addition, Refined geomorphological zone.

@dimasciput  - also everything should be singular, not plural, so zone not zones, unit not units, etc
