### ISSUE TITLE
Add 'Endemism' to search bar on map

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1343]
@dimasciput @toniolsen @timlinux 

'Endemism' should feature in the search bar options on the map, and should include check boxes for all five endemism categories.

<img width="565" alt="Screenshot 2019-05-26 at 11 19 06" src="https://user-images.githubusercontent.com/44292029/58379772-87239480-7fa8-11e9-870d-fca9585b7f8c.png">

**Comment by dimasciput** [comment]
@jeremyshelton Is this high priority? Because it will probably take me half day to implement this new feature. If not, maybe we should leave it for version 3.

**Comment by jeremyshelton** [comment]
@dimasciput Yeah, it is rather important. I am not sure why it is not there already. It would be very good to have this for v2. However, I am aware that you have a lot of tickets to get through, so if need be this can be held over to v3...

**Comment by jeremyshelton** [comment]
@dimasciput please leave this for version 3. I forgot that Endemism filtering is available within the Origin tab, which is fine for now.
