### ISSUE TITLE
Switch Origin and Occurrences columns

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1345]
Please swap around the Origin column with the Occurrence column:

![image](https://user-images.githubusercontent.com/43198125/58407431-0cbc4880-806c-11e9-9f44-12402f43f10b.png)

@dimasciput @jeremyshelton

**Comment by helendallas** [comment]
@toniolsen Please can you provide screen shot...more detail needed

**Comment by toniolsen** [comment]
![Screenshot 2019-08-01 at 10 17 12](https://user-images.githubusercontent.com/43198125/62281435-ad046400-b445-11e9-9082-cae0f4bee401.png)

In the Occurrence data table in the site dashboards, it would be good if the columns were in this order:
Taxon; Occurrences; Origin, Endemism; Conservation Status

@helendallas @dimasciput
