### ISSUE TITLE
Use title case consistently

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1362]
**Describe the bug**
<img width="281" alt="image" src="https://user-images.githubusercontent.com/178003/58547660-b1bb5a80-81ff-11e9-88de-5c917cc32890.png">

Please update layer names to all use Title Case

**Comment by timlinux** [comment]
i.e. NFEPA Rivers not NFEPA rivers

**Comment by NyakudyaA** [comment]
Closed via https://github.com/kartoza/geocontext/pull/95/commits/34b0d54285148b98ec0a3b63a0cb9df0de0b8661
