### ISSUE TITLE
We need to redo the UI for layer order in Admin page

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#1367]
**Is your feature request related to a problem? Please describe.**
We have added a lot of layers in our layer list and rearranging them is become cumbersome as you have to drag each layer one after the other until you reach the desired position.

![drag](https://user-images.githubusercontent.com/2510900/58654059-6005f380-8317-11e9-93a9-1e7bd155928d.png)

**Describe the solution you'd like**
We should be able to drag a layer and position it on the exact position

**Comment by dimasciput** [comment]
won't fix for now - after discussion with Tim
