### ISSUE TITLE
Map layers render slow because we are using direct wms request

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#1368]
# Problem

In the map layer request, we are using direct wms request, we need to utilize the full capability of Geoserver caching so that map layers are rendered fast.

Example
http://testing.healthyrivers.kartoza.com/bims_proxy/https://maps.kartoza.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&layers=kartoza:cba_national_mview&format=image/png&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&STYLES=&BBOX=2661231.576776698,-3757032.814272985,2817774.610704739,-3600489.780344944

**We should add the following to the request.**
`tiled=true` This will ensure that request is fetched from the cache and if not they will be fetched from wms but then cached.

https://maps.kartoza.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&layers=kartoza:cba_national_mview&format=image/png&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&STYLES=&BBOX=2661231.576776698,-3757032.814272985,2817774.610704739,-3600489.780344944&tiled=true

https://docs.geoserver.org/latest/en/user/services/wms/vendor.html#tilesorigin

cc @dimasciput @timlinux 
I think this will improve the user experience for rendering map layers in the front end

**Comment by helendallas** [comment]
@NyakudyaA 
Has this been finalised, if yes, please comment and close the ticket.
