### ISSUE TITLE
Uploading SASS and Fish data issue

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1372]
I tested out the uploading of fish and SASS data and came across some big issues. I will first address the issues with the fish upload and then the SASS upload:

**Uploading Fish Data**
1.) I first used the "capturing single occurrence" icon. This completed and sent me the email to validate the data uploaded, however, the newly created site does not appear on the map??

2.) I tried the CSV upload. This said processing for about an hour and then I gave up:

![image](https://user-images.githubusercontent.com/43198125/58694322-07743c00-8393-11e9-969c-ecce9f966fa9.png)

3.) I used the fish form to add fish data to an already existing site. This worked.

Is the only way to add a new site for fish records by using the capture single occurrence icon? If so, we need a place on the form for the user to type in their coordinates. 

**Uploading SASS Data**
1.) I used the SASS form to add data to an already existing site. Once submitted this took me to this page and the data was not added to the site:
![image](https://user-images.githubusercontent.com/43198125/58694580-997c4480-8393-11e9-9d31-58efac964b40.png)

2.) Again, we need to be able to create new sites for SASS and not just add data to already existing sites. 

Perhaps we could link the "capture single occurrence" icon to take us to either the SASS or Fish form. Then users can go to the river they sampled, click on the river and change their coordinates accordingly? 

I am not sure how big these issues are and how long it will take to be sorted out, but I think our users are definitely going to want to upload their data after the release, so I think it is a very important issue to fix.

@dimasciput @timlinux @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
Hi @toniolsen 

> 1.) I first used the "capturing single occurrence" icon. This completed and sent me the email to validate the data uploaded, however, the newly created site does not appear on the map??

Have you validate the data?

> 2.) I tried the CSV upload. This said processing for about an hour and then I gave up:

What data did you use? 

>  Again, we need to be able to create new sites for SASS and not just add data to already existing sites.

This won't be possible for me to do next monday

**Comment by toniolsen** [comment]
Hi @dimasciput 

1.) Yes, I validated the data following the link sent to my email.

2.) I first downloaded the template and added a single occurrence of fish from a study I have done.

Okay, sure! Are these issues something that can be sorted out after FBIS has gone live and you return from your holiday?

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/58696559-01498400-83c2-11e9-92ab-4fe868493b50.png)
It seems you haven't validated the records, I validated it just now, can you try look for your record?

> 2.) I first downloaded the template and added a single occurrence of fish from a study I have done.

I can fix this on monday

> Okay, sure! Are these issues something that can be sorted out after FBIS has gone live and you return from your holiday?

Yes but I need the workflow on how we are going to add the site, we need to discuss this first.

**Comment by toniolsen** [comment]
Okay, yes. I can see my record now. Do you think it is an issue with my validation because I ticked it and it said validated. 

Here is a screenshot of the detailed dashboard. Why is the same species (i.e. Galaxias zebratus) listed as Native and Unspecified?
![Screenshot 2019-05-31 at 11 55 31](https://user-images.githubusercontent.com/43198125/58698218-37bfd880-839b-11e9-9820-517d295a1312.png)

**Comment by dimasciput** [comment]
The origin is attached to the collection record, not the taxonomy data.

**Comment by dimasciput** [comment]
@toniolsen these are steps to validate data : 

- user add a record
- user ticked ready to validate
- staff user / validator validate or reject the data

**Comment by toniolsen** [comment]
The word "indigenous" is being used for csv upload, so maybe that's why?
The capture single occurrence uses "Native"

This should be "Native" and alien should be "Non-native"

**Comment by toniolsen** [comment]
![image](https://user-images.githubusercontent.com/43198125/58704646-08b26280-83ad-11e9-84f7-042e5936b708.png)
