### ISSUE TITLE
We need a create site form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1376]
Like in the fish form but dedicated to making a new site.

![Screenshot 2019-06-03 at 11 42 06](https://user-images.githubusercontent.com/178003/58800754-989c1a80-8600-11e9-851b-fdbc6ecfb1d5.png)

Red text shows fields we want to include on the form.
Should not include date.
Collector should be person who first describes the site.
Site code should be autocalculated but overridable by user.
After creating the site, buttons should allow user to go on to capture fish, sass and later bugs, abiotic, inverts.

Same form should be used when editing a site.

**Comment by dimasciput** [comment]
For the consideration, to generate site code we need river catchment and river name data, to fetch this data from geocontext we need 5-10 seconds. 

Geomorphological zone need around 3 seconds.

So 8-13 seconds every time user change the coordinates. This is not including rainfall data and others.

**Comment by timlinux** [comment]
> Hi @timlinux , how do we generate a site code for new site? Because we need some data from geocontext (catchment), and it's not that quick to fetch data from geocontext.

It would be ideal to do that yes, and then let the user change it if they want to customise it. It should probably fail gracefully if geocontext times out though (in which case presenting a blank site name that user can populate).


> 
> > Collector should be person who first describes the site.
> 
> Ok it means we have two different collector? Collector of the site and collector of the collection?

I believe that is how @helendallas would like it, yes. So each biological collection record has a collector and the person who initially creates the site (we could call it site creator) gets assigned to the site. Note the site creator may not be the logged in user - it could be the person who first surveyed the site 100 years ago...

**Comment by timlinux** [comment]
> For the consideration, to generate site code we need river catchment and river name data, to fetch this data from geocontext we need 5-10 seconds.
> 
> Geomorphological zone need around 3 seconds.
> 
> So 8-13 seconds every time user change the coordinates. This is not including rainfall data and others.

Could we just havea. ticker displaying with a little update indicating what the user is waiting for? We can get @NyakudyaA to look at the respnse performance of GeoContext too to try to get the response faster. I think they user will not be creating 100s of sites manually at a time, so lets build it to work first (even if slowly) and optimise later if speed proves to be a pain point. Main thing is to keep the user informed as to why they are waiting....

**Comment by helendallas** [comment]
@timlinux @dimasciput 
Correct re site creator (all legacy Sites in Rivers DB have a Site Owner associated with them).
And then each biological record has a collector or is the case of SASS Collector of the collection (SASS assessment)

Best if the Secondary catchment and river name can be autocalculated via GeoContext (agree dont worry about speed at this stage)  - then user can add LOCALITY code (5 letters) - so Site code should be autocalculated but overridable by user.. A big issue in earlier Rivers DB was a user not knowing the Secondary catchment code, so essential that autocalculated plus rivername

**Comment by helendallas** [comment]
When creating a new site, a user will need to populate certain fields (compulsory), including
Site Code (generated as above)
Site description
Collector
Latitude
Longitude
Geomorphological Zone (populated automatically)

When the latitude and longitude are added - if there is a Site within 500m of the site being created, a warning message should be displayed saying :
"Site G2BERG-JIMFO is within 500 metres of your site - do you wish to create a new site or use the existing site?"

Then, in addition we need to allow a user to add:
Refined Geomorphological Zone (user is able to populate from a drop down list) as detailed below:

Source zone
Mountain headwater stream
Mountain stream
Transitional
Upper foothill
Lower foothill
Lowland river
Rejuvenated bedrock fall / cascades
Rejuvenated foothill
Upland floodplain

**Comment by toniolsen** [comment]
@dimasciput  I get this message when I fill out the fish form. I have completed all the fields and selected the species present:

![Screenshot 2019-06-19 at 09 01 14](https://user-images.githubusercontent.com/43198125/59744080-12bfd680-9272-11e9-81ef-dc9e1faf5efa.png)
