### ISSUE TITLE
Site deployment banner

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1377]
Can we have a landing page which is just a static page like the mockup below that we use when deploying new versions. Please enable it now until we have V2 ready.

No menu needed please.

![Screenshot 2019-06-03 at 12 35 03](https://user-images.githubusercontent.com/178003/58801131-96868b80-8601-11e9-80f1-082e1e0392bd.png)

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
