### ISSUE TITLE
Please add  delete button on the sass form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1379]
Nice read button next to the edit green button please to delete the current sass record (superusers only)

<img width="292" alt="PastedGraphic-5" src="https://user-images.githubusercontent.com/178003/58802826-07c83d80-8606-11e9-9d43-b98332d9848c.png">

**Comment by helendallas** [comment]
This is needed as there are some SASS records where no abundances are recorded, and these need to be deleted.

**Comment by dimasciput** [comment]
Added
