### ISSUE TITLE
Transparent background is not very good

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#138]
I don't think transparent background looks very good and clear : 

 
![screen shot 2018-07-16 at 11 42 01 am](https://user-images.githubusercontent.com/1979569/42743380-632b0426-88ed-11e8-9eb3-549771886fe4.png)

Should we just change it to solid background for better clarity?

![screen shot 2018-07-16 at 11 46 15 am](https://user-images.githubusercontent.com/1979569/42743424-dfdae84c-88ed-11e8-87b6-8288a256c89f.png)

**Comment by meomancer** [comment]
yes, i agree
when transparent, when there is word on map, it's quite hard to see the word in layer selector

**Comment by gubuntu** [comment]
+1 for opaque

**Comment by carina1000** [comment]
You're right - it's more clear. I've updated the mockups too!
