### ISSUE TITLE
Delete Helen gmail account

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1380]
We have two accounts for Helen

Please delete the gmail one, transferring any records owned by that user to the FRC account.

<img width="640" alt="PastedGraphic-6" src="https://user-images.githubusercontent.com/178003/58802956-46f68e80-8606-11e9-9675-477451c9bdaa.png">

**Comment by toniolsen** [comment]
@dimasciput 
Helen is still receiving validation emails. Emails should only be sent to fbis@frcsa.org.za please.

@helendallas

**Comment by dimasciput** [comment]
The gmail account has been deleted

**Comment by toniolsen** [comment]
Okay thanks @dimasciput!
Helen doesn't want to receive any validation emails either to her frc account (helen@frcsa.org.za), so just make sure that only emails are sent to fbis@frcsa.org.za regarding FBIS stuff.
