### ISSUE TITLE
SASS accreditation in SASS Form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1383]
![Screenshot 2019-06-03 at 12 24 24](https://user-images.githubusercontent.com/178003/58807323-ba50ce00-860f-11e9-8454-ad2473ffeded.png)

We need a checkbox under the Assessor field where the data capturer can indicate if the assessor was accredited at the time of the collection.

**Comment by dimasciput** [comment]
@timlinux how long is the duration of the accreditation? We need valid_from and valid_to dates.

**Comment by timlinux** [comment]
@dimasciput So @helendallas suggestio when we implemented the accreditation date was to keep it simple and not try to cater for discontinuous date ranges. So for example say Helen is accredited from 


2011-2014
and then again
2016-2019

We would record her date range in her user profile as 2011-2019 and not try to account for the missing years between accreditation periods.

When the user fills in the SASS form we just default to whether the collection date falls within the broad accreditation range and default it to 'yes' but let the data capturer change that determination if they 'know' that the user was not accredited at that specific time.

Does that make sense? @helendallas please confirm if my take above is correct.

**Comment by helendallas** [comment]
That sounds fine @timlinux @dimasciput . Thanks!
