### ISSUE TITLE
Remove common names from SASS taxon name list

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1385]
<img width="453" alt="Screenshot 2019-06-03 at 12 31 41" src="https://user-images.githubusercontent.com/178003/58808153-59c29080-8611-11e9-8d0c-b5a90ee8ab2c.png">

Items in Parentheses should be removed.

(should be done in all places where taxa are listed for SASS)

**Comment by dimasciput** [comment]
Removed in sass form
