### ISSUE TITLE
Ecological Condition filter

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1386]
Can we please get the Ecological Condition filter active for Version 2?

![Screenshot 2019-06-03 at 16 05 28](https://user-images.githubusercontent.com/43198125/58808266-00129400-861a-11e9-910c-ed120142ee8c.png)

@dimasciput @timlinux @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
@toniolsen yes we could, it will take me 4-8 hours for this.

**Comment by helendallas** [comment]
Please can you rename **Ecological Category** rather than Ecological Condition - as per previous comments

**Comment by dimasciput** [comment]
implemented
