### ISSUE TITLE
Filter - Spatial Scale - Primary, Secondary catchments - A, B; A1 etc 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1387]
Please can you check why A1 is not listed in the spatial scale filter  -there are sites in it.

![Screenshot_2019-06-04 FBIS Map](https://user-images.githubusercontent.com/45286876/58857770-457ca300-86a6-11e9-9b91-04389ca48587.png)

**Comment by NyakudyaA** [comment]
@dimasciput I can confirm that the data for those catchments do exist in the DB
![catchment](https://user-images.githubusercontent.com/2510900/58859101-57ac1080-86a9-11e9-9d2e-98497d41c288.png)

**Comment by dimasciput** [comment]
@NyakudyaA 

This site looks like in A1 secondary catchment
![image](https://user-images.githubusercontent.com/1979569/62020265-81d30800-b1ec-11e9-9b7f-4d9bb4c0e659.png)

But when I fetch from geocontext I got D4
https://geocontext.kartoza.com/api/v1/geocontext/value/group/25.8/-25.183/river_catchment_areas_group/

**Comment by NyakudyaA** [comment]
Yes @dimasciput the site should be in A1.
![site](https://user-images.githubusercontent.com/2510900/62030635-ceffab80-b1e5-11e9-90c3-f1f24ea7136f.png)

I will test in my local env first

**Comment by dimasciput** [comment]
so how is it @NyakudyaA ? Can you fix the geocontext?

**Comment by NyakudyaA** [comment]
Hi @dimasciput I didn't manage to dig through this yesterday, I didn't have power the whole afternoon but I will spend some time on it today

**Comment by NyakudyaA** [comment]
@dimasciput I am going to make a new PR in geocontext that improves how the data is generated. I have got it working on my local instance
![catchments](https://user-images.githubusercontent.com/2510900/63430810-cfbee280-c41d-11e9-978e-97c4a2c27340.png)

**Comment by NyakudyaA** [comment]
@dimasciput please reingest this and close when done.
![gif](https://user-images.githubusercontent.com/2510900/64340276-0bdd7000-cfe6-11e9-9b38-65c5f9c065b9.png)
