### ISSUE TITLE
Enable editing of latitude and longitude - superuser

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1391]
Please allow a superuser to edit the longitude and latitude - critical for the correcting of SASS data coordinates

![Screenshot_2019-06-06 Change location site Django site admin](https://user-images.githubusercontent.com/45286876/59014251-7989cc80-883c-11e9-9023-390f11ac08c2.png)

**Comment by timlinux** [comment]
@dimasciput can we simply remove them from the read only list here:

https://github.com/kartoza/django-bims/blob/develop/bims/admin.py#L124

Or do we need to update the JS for the for to move the dot on the map at the same time?
