### ISSUE TITLE
SASS form update not working correctly

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1392]
I tried to correct a SASS data entry, deleting Perlidae and replacing it with Notonemouridae.
Original screen: 

![image](https://user-images.githubusercontent.com/43198125/59090496-36e3f500-890d-11e9-90be-e749ae3c19ee.png)

Then I edited data:

![image](https://user-images.githubusercontent.com/43198125/59090537-52e79680-890d-11e9-8db6-3519cc5a883e.png)

After hitting Update – It asked if I want to submit the SASS form:

![image](https://user-images.githubusercontent.com/43198125/59090574-6a268400-890d-11e9-898c-363f6b7190e5.png)

Then when I went back into record, both Perlidae and Notonemouridae were recorded:

![image](https://user-images.githubusercontent.com/43198125/59090626-980bc880-890d-11e9-8317-0cd8558b89b5.png)

And it created a duplicate record: 16-04-2009. One has perlidae, and one has perlidae and notonemouridae – however you see the SASS Score, Number of Taxa and ASPT in the summary form are the same.
 
So the calculations are not working and this all needs a thorough check and revision:

![image](https://user-images.githubusercontent.com/43198125/59090663-b40f6a00-890d-11e9-85e7-dd54bf8497e7.png)

Thanks! @dimasciput @timlinux @helendallas

**Comment by dimasciput** [comment]
Fixed
