### ISSUE TITLE
SASS Taxon name - revise Helodidae to Scirtidae

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1394]
The original list I provided for SASS taxa showed the name change of Helodidae to Scirtidae.  It is correct in the SASS form but not in the summary data. Please change.

![Screenshot_2019-06-10 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/59179369-119bf480-8b62-11e9-9f39-c861a395cccb.png)

**Comment by dimasciput** [comment]
Fixed in testing
