### ISSUE TITLE
Unable to change coordinates

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1396]
When trying to change coordinates of SASS sites by clicking "Edit", changing the coordinates and then "Save" , this page come up...
![Screenshot 2019-06-14 at 08 49 43](https://user-images.githubusercontent.com/43198125/59489114-9730e480-8e81-11e9-89c7-3970e2d724d6.png)

@dimasciput

**Comment by dimasciput** [comment]
@toniolsen for which site? please add more information, so I can fix it faster.

**Comment by toniolsen** [comment]
I was having trouble with A2HENO-GLENA.
This site has no "Original Geomorphological Zone", so when I added "Refined Geomorphological Zone", it took me to the error page. So then I tried without adding the refined geomorph zone and it worked.

**Comment by toniolsen** [comment]
@dimasciput 
Okay, I think the problem is that I cannot add a "Refined Geomorphological Zone" if there is no "Original Geomorphological Zone". 
But if I add a "Refined Geomorphological Zone" that is different to the original geomorphological zone then it changes to the refined geomorph zone on the overview panel (which is correct).

**Comment by helendallas** [comment]
Checked - is working. Closed.
