### ISSUE TITLE
Adding SASS data to an existing site

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1409]
When I add SASS data to an already existing site, for example A2CROC-MOUNT. It says updated successfully, but when I go back into the SASS dashboard for that site the data is not there?

I have checked and there is also no validation action for me to complete the upload.
 
@dimasciput @timlinux @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
@toniolsen what kind validation?

**Comment by toniolsen** [comment]
Validation for the new SASS record added to the existing site.
@dimasciput

**Comment by dimasciput** [comment]
No currently we don't have validation system for SASS record, I never implemented it.

**Comment by toniolsen** [comment]
Okay, that is fine. 
But the SASS data added needs to be added to the SASS dashboard. At the moment it does not appear after it has said "updated successfully"

**Comment by dimasciput** [comment]
It works for me : 

![image](https://user-images.githubusercontent.com/1979569/59749952-2ede6a80-92a8-11e9-9559-cb895739b6cb.png)
![image](https://user-images.githubusercontent.com/1979569/59749969-3736a580-92a8-11e9-9e28-8623642b20fd.png)

**Comment by toniolsen** [comment]
That's strange that it is not showing up for me.
I have refreshed many times and logged out.
I only see the first two records and not the one I uploaded today:
![Screenshot 2019-06-19 at 10 46 56](https://user-images.githubusercontent.com/43198125/59750835-bf548500-927f-11e9-8782-9c47637a4e7a.png)
