### ISSUE TITLE
Changing coordinates

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1411]
I am having trouble changing the coordinates of sites. 
When I select the "Edit" button it takes me to a different page to last week. 
Then I change the coordinates and select "update coordinates" and this warning message pops up:
![Screenshot 2019-06-19 at 11 45 15](https://user-images.githubusercontent.com/43198125/59755533-5cb3b700-9288-11e9-8692-d9a8b1250ccf.png)
If I select "cancel" then it removes all the other details of the site and essentially creates a "new site", which I don't want.
if I select "use the existing site", it says site has updated successfully, but then when I check the coordinates haven't changed?

Anyway to change this process so I can do it the way I was doing it last week through the Admin page (I think?).
@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
This is intended, because when we change the coordinates, the site code and geo zone will be different. Or we can keep the value.
