### ISSUE TITLE
Please include a "Bedrock" category in the SASS Biotope ratings

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1415]
We need a "Bedrock" category for the Biotope ratings in the SASS form:

![Screenshot 2019-06-20 at 09 44 47](https://user-images.githubusercontent.com/43198125/59830982-1f5f3000-9341-11e9-9fb6-09cf4cef4dde.png)

@dimasciput

**Comment by dimasciput** [comment]
Added in testing

![image](https://user-images.githubusercontent.com/1979569/60396415-a7c4a880-9b6b-11e9-8efc-a400fb6583b5.png)
