### ISSUE TITLE
Image on fish site dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1416]
We need a place for the image of the site on the fish site detailed dashboards:
![Screenshot 2019-06-20 at 11 21 24](https://user-images.githubusercontent.com/43198125/59837662-e7aab500-934d-11e9-85de-fa22d4a505c4.png)
@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
has been added, I will close this ticket but still put it on the review column.

**Comment by helendallas** [comment]
@dimasciput 
When I open fish dashboard, I don't see the pace for the Site Image. It looks the same as Toni's screen shot above.

![Screenshot_2019-11-14 FBIS Map(3)](https://user-images.githubusercontent.com/45286876/68859312-aa293880-06ef-11ea-90d4-22c078f90462.png)

**Comment by helendallas** [comment]
@dimasciput 
On reflection I think the issue relates to existing sites, where perhaps one would want to add a photograph. I see when new data is added it works fine.

I ma not sure whether it would be relatively simple to allow the Owner and Admin persons to edit, including adding a photograph. Ina  similar way to SASS data is edited.  We will need this for the Invertebrate data as well

**Comment by timlinux** [comment]
Dimas and Tim to go and discuss how we will present this to our users - the idea is to add image management capabilities to the site edit page.
