### ISSUE TITLE
Repetition of Veliidae/Mesoveliidae in the SASS form

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1418]
Veliidae/Mesoveliidae has been repeated in the SASS form.
Please delete the first one, i.e. Veliidae/Mesoveliidae (RIPPLE BUGS):
![Screenshot 2019-06-20 at 11 59 28](https://user-images.githubusercontent.com/43198125/59840797-62c29a00-9353-11e9-929d-427c1d4752c4.png)

@dimasciput @helendallas

**Comment by dimasciput** [comment]
Updated in testing
![image](https://user-images.githubusercontent.com/1979569/60396723-469ed400-9b6f-11e9-939b-11deb3d9e8e4.png)
