### ISSUE TITLE
Origin terminology

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1419]
@dimasciput @timlinux @toniolsen 

We need to make some (slight) changes to the terminology used for the different categories within ‘Origin’. 

The attached .docx explains exactly what is needed, and the attached .xlsx is the updated fish master spreadsheet.

[Origin terminology.docx](https://github.com/kartoza/django-bims/files/3309939/Origin.terminology.docx)

[SA Master fish species list_Final.xlsx](https://github.com/kartoza/django-bims/files/3309944/SA.Master.fish.species.list_Final.xlsx)

**Comment by dimasciput** [comment]
Hi @jeremyshelton is this really important for version 2? Or can put this to version 3 instead? I'd rather we focus on fixing bugs.

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux it is an important change, and would be ideal if we could get it sorted out for v2 to avoid confusing the users. 

This is also linked to ticket #1420 which provides definitions for filters like Origin, Endemism, Conservation status etc.

Do you think there might be time to get to it next week, after some of the other bug-fixing?

That said, I should have picked up on it earlier (my bad), and realise that this is quite late in the sprint to be adding this issue....so if we have to hold it over, then so be it...

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux if it's a size 5 task, then I think we should try to prioritise it....
