### ISSUE TITLE
Add site - Lat and long autopopulate

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1424]
When adding a site, would it be possible to allow the user to click on a river on the map and for the latitude and longitude fields to auto populate? Similar to how we had it for the "capture single occurrence" function. (Sometimes users don't record their coordinates and just get them from Google Earth later).
![Screenshot 2019-06-21 at 16 27 36](https://user-images.githubusercontent.com/43198125/59929807-e1960080-9441-11e9-912b-23e128331797.png)

This would be a really nice function to have.
@dimasciput @timlinux @jeremyshelton

**Comment by toniolsen** [comment]
@dimasciput This isn't working for me?

**Comment by dimasciput** [comment]
@toniolsen try again

**Comment by toniolsen** [comment]
Okay great, it's working now. Thanks @dimasciput 
I created a test site, but when I want to validate the record by pressing "Validate Records", it takes me to the login page and then doesn't allow me to log in:

![Screenshot 2019-07-01 at 10 41 19](https://user-images.githubusercontent.com/43198125/60422675-cb7c0300-9bec-11e9-9455-bbd455769fac.png)

**Comment by dimasciput** [comment]
@toniolsen Yes because you are not the validator, only validator will get email. Only fbis@frcsa.org.za account can validate the data.

**Comment by toniolsen** [comment]
Okay so must I make an FBIS account then using the fbis@frcsa.org.za email? this whole time I was just validating records on my account.

**Comment by dimasciput** [comment]
@toniolsen we already have that account as superuser, I will reset the password and email you the password.

**Comment by toniolsen** [comment]
sorry @dimasciput.
Yes I see the FBIS account has been created, but I can't remember what I made the password...
