### ISSUE TITLE
Sites with no SASS data in the Ecological Category filter?

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1431]
I filtered for Seriously/Critically modified and sites with no SASS data showed up. These sites do have fish data though.

Some examples of sites that did this:
J2SUND-00001
J4GOUR-00024
L7GROO-00036
E1OLIF-00089

Ecological Category filter is a filter that only applies to SASS data. So all sites with just fish data should not be included in this filter.

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/60158866-23e18800-981c-11e9-9c37-9b044bdfceaf.png)

@toniolsen strange, it was normal for me

**Comment by toniolsen** [comment]
It's fine if you click on the filter, and then type in the site code. But if you click on the filter and then search a site randomly on the map by just clicking on it, this is what appears:
![Screenshot 2019-06-26 at 09 16 08](https://user-images.githubusercontent.com/43198125/60159375-51fea200-97f3-11e9-9710-1b9b79a36731.png)

**Comment by dimasciput** [comment]
@toniolsen , ok I found the but, there is two site with the same coordinate, and when you click the point it will get the wrong site. I'll fix it tomorrow, thanks for the report.

**Comment by helendallas** [comment]
I have checked this and it seems to be working fine now. Closing the issue.
