### ISSUE TITLE
Sites with both Fish and SASS data - Come up as two separate sites

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1434]
It seems that sites with both SASS and Fish data come up as two separate sites:
There should just be one overview panel (that has the fish and SASS pie graphs) and then from there specify whether you want to see the fish detailed dashboard or SASS detailed dashboard:
![Screenshot 2019-06-27 at 10 39 23](https://user-images.githubusercontent.com/43198125/60251670-44b3e700-98c9-11e9-8c95-15350a32e423.png)
![Screenshot 2019-06-27 at 10 39 41](https://user-images.githubusercontent.com/43198125/60251868-a4aa8d80-98c9-11e9-8c86-d884427451ec.png)

@dimasciput @timlinux @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen it looks like they are two different site with same SITE_CODE
