### ISSUE TITLE
SASS form errors

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1443]
Please delete the duplicate in the SASS form:
![Screenshot 2019-07-01 at 08 26 00](https://user-images.githubusercontent.com/43198125/60416347-e6934680-9bdd-11e9-987a-036eaf70d5d1.png)

Please delete the common name: "Emerald Damselflies"
![Screenshot 2019-07-01 at 08 26 16](https://user-images.githubusercontent.com/43198125/60416473-340fb380-9bde-11e9-8d6a-f08a1d3473e6.png)

@dimasciput

**Comment by dimasciput** [comment]
Fixed in testing
