### ISSUE TITLE
Issues with Native/Non-native categories

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1446]
I did some species searches to make sure that the species had the correct origin category, but came across some problems. For example I searched Galaxias zebratus, then in the overview panel the non-native category was highlighted:
![Screenshot 2019-07-01 at 10 48 58](https://user-images.githubusercontent.com/43198125/60424792-637beb80-9bf1-11e9-8e4b-bb9f5025b35f.png)
But it is native as in our Master list:
![Screenshot 2019-07-01 at 10 48 38](https://user-images.githubusercontent.com/43198125/60424851-83131400-9bf1-11e9-8833-5f675864a42d.png)
And then in the dashboard non of the categories were highlighted:
![Screenshot 2019-07-01 at 11 12 30](https://user-images.githubusercontent.com/43198125/60424920-af2e9500-9bf1-11e9-9ca4-99dc582a9766.png)

A similar issue was found for Sandelia capensis:
Marked as non-native in the overview panel:
![Screenshot 2019-07-01 at 10 49 40](https://user-images.githubusercontent.com/43198125/60424976-d2f1db00-9bf1-11e9-8635-eb51a1200c04.png)
But it is Native in our Master list:
![Screenshot 2019-07-01 at 10 50 46](https://user-images.githubusercontent.com/43198125/60425001-e3a25100-9bf1-11e9-9273-e378c3836e82.png)
But then in the detailed dashboard it is correctly marked as Native:
![Screenshot 2019-07-01 at 10 51 45](https://user-images.githubusercontent.com/43198125/60425062-0cc2e180-9bf2-11e9-9b6d-3faefd64eae1.png)

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen I have updated the data with the excel file again, can you try it?

**Comment by toniolsen** [comment]
I have checked a couple of the species and it all seems correct now.
Thanks @dimasciput
