### ISSUE TITLE
Ecoregion level 1 filter

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#1454]
From ticket https://github.com/kartoza/django-bims/issues/1288

> @jeremyshelton : There are still some Ecoregion level 1 categories missing (Numbers 2, 6 and 10). @NyakudyaA can you please check if these are correct on GeoContext?

![image](https://user-images.githubusercontent.com/1979569/60490406-abbe0b00-9cd0-11e9-8693-1e43e28adc1c.png)

**Comment by NyakudyaA** [comment]
@dimasciput You need to update this layer from geocontext. The data has been there for some time now.
![rows](https://user-images.githubusercontent.com/2510900/60492716-d6499d00-9cab-11e9-96f7-330c9db5e459.png)

**Comment by dimasciput** [comment]
@NyakudyaA ok, re-fetching the layer data for now. 

@jeremyshelton this process will take around 4 hours, so probably you will see empty ecoregion filter until the process finished.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput

**Comment by dimasciput** [comment]
we need to confirm the data

**Comment by helendallas** [comment]
@dimasciput @NyakudyaA 
Checked now - still missing

![Screenshot_2019-07-31 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/62213631-a6bdab80-b3a3-11e9-807c-1fe79c7fb067.png)

**Comment by dimasciput** [comment]
@helendallas @NyakudyaA I have refetched all the sites, so I think we don't have any data for those missing spatial filters.

**Comment by helendallas** [comment]
@NyakudyaA 

There are data in all these regions.....see screen shot below for 2 Soutpansberg; 6 Waterberg and 10 Northern Escarpment Mountains. 

![Screenshot_2019-08-01 FBIS Map](https://user-images.githubusercontent.com/45286876/62277273-1d12ea00-b446-11e9-8c3d-051783abf71f.png)

![Screenshot_2019-08-01 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/62277538-a3c7c700-b446-11e9-9234-9838ae7246ef.png)


![Screenshot_2019-08-01 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/62277543-a5918a80-b446-11e9-9f73-5bfe8b813747.png)

**Comment by dimasciput** [comment]
@NyakudyaA can you check from the geocontext side?

**Comment by NyakudyaA** [comment]
I will do so @dimasciput

**Comment by NyakudyaA** [comment]
@dimasciput there seems to be valid data for that area. Please check how the import script is working

I created a dummy point a region shown on the screenshot
![levels](https://user-images.githubusercontent.com/2510900/62282479-f194fd00-b44f-11e9-8da5-fcadff0f29f1.png)

I then took the coordinates and put them in geocontext
![levelsa](https://user-images.githubusercontent.com/2510900/62282596-1db07e00-b450-11e9-8b58-584dc2bc19ef.png)

**Comment by NyakudyaA** [comment]
@dimasciput here is the latest output from Geocontext
![eco-region](https://user-images.githubusercontent.com/2510900/64340140-bbfea900-cfe5-11e9-9d47-ca2bd555d722.png)

Perhaps you should reingest the data.

**Comment by dimasciput** [comment]
this has been fixed on testing
