### ISSUE TITLE
Colour change 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1455]
@dimasciput thanks for changing the green on the dots and search bar. However, seeing these o the map, colour #18A090 looks too dark, and does not match logo. If possible (and quick) would you mind changing these to the lighter colour #39B2A3?

**Comment by dimasciput** [comment]
@jeremyshelton done, please check the site again. If you're satisfied with the results, you can close this ticket.

**Comment by dimasciput** [comment]
on second thought, please let me know first, because I also need to change the legend color.

**Comment by jeremyshelton** [comment]
@dimasciput the dot colour is now correct. Thanks. Please go ahead and update the legend, search bar and buttons etc..
<img width="623" alt="Screenshot 2019-07-02 at 10 39 47" src="https://user-images.githubusercontent.com/44292029/60497944-0bf38380-9cb6-11e9-8c0c-fffd979af198.png">

**Comment by jeremyshelton** [comment]
@dimasciput Or maybe colour #6BC0B5? Whichever one is most similar to the colour of the logo...

**Comment by dimasciput** [comment]
@jeremyshelton it's up to you

**Comment by jeremyshelton** [comment]
@dimasciput lets go with #39B2A3 for this version. Thanks
