### ISSUE TITLE
Ecological Category Filter still not working

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1459]
The ecological category filter seems to have a problem again.
I filtered "Natural":
![image](https://user-images.githubusercontent.com/43198125/60567865-9813b280-9d6b-11e9-94fa-672fdd123c6a.png)

And the sites returned did not have a natural ecological category:

![image](https://user-images.githubusercontent.com/43198125/60567903-b4afea80-9d6b-11e9-85d1-2f4b787149c9.png)

I am unsure exactly what the issue is, but we can't release if it is not working properly. If the issue is too big to fix right now before we go to the live site, then perhaps disable the filter and put a "coming soon" pop up. 

@dimasciput @helendallas @jeremyshelton @timlinux

**Comment by dimasciput** [comment]
@toniolsen Ok this is because I forgot to handle the `combine` condition, it should be not too difficult

**Comment by dimasciput** [comment]
@toniolsen can you try again now?

**Comment by toniolsen** [comment]
@dimasciput 
I have done a few checks and it seems to be working now, thanks!

@helendallas @jeremyshelton
