### ISSUE TITLE
"Alien" comes up when I filter non-native species

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1460]
@dimasciput 

I filtered all non-native species. 
The graph was labelled correctly "Non-native", but the search criteria table had the word "alien" in it:
![Screenshot 2019-07-03 at 08 29 07](https://user-images.githubusercontent.com/43198125/60568403-073dd680-9d6d-11e9-8763-4560b4c884e8.png)

@jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen Can we leave this for now, this is only filter url name.

**Comment by toniolsen** [comment]
Okay sure @dimasciput, no problem!
