### ISSUE TITLE
Nothing shows up when I search 

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1463]
Nothing is showing up when I search items. I searched Fish and GBIF. I clicked Apply and then Search and then nothing comes up. I have refreshed many times.

![Screenshot 2019-07-03 at 13 57 48](https://user-images.githubusercontent.com/43198125/60589980-1e93b880-9d9b-11e9-94c7-f6e4cef08436.png)

@dimasciput @timlinux @jeremyshelton

**Comment by dimasciput** [comment]
Fixed
