### ISSUE TITLE
Unable to select "All endemic" within the Native filter

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1465]
I am unable to tick the All endemic box:
![Screenshot 2019-07-03 at 15 34 10](https://user-images.githubusercontent.com/43198125/60595876-23129e00-9da8-11e9-8c46-74cd3ee949ec.png)
 @dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
@toniolsen you don't need to click the checkbox, you can click the label. I don't think I can fix this in this version.

**Comment by toniolsen** [comment]
@dimasciput Okay perfect. That is fine.
