### ISSUE TITLE
Non-native issue

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1466]
A similar issue is popping up for Cyprinus carpio. Non-native is not highlighted in the overview panel, but it is highlighted in the detailed dashboard:

![Screenshot 2019-07-03 at 15 46 38](https://user-images.githubusercontent.com/43198125/60597464-4559eb00-9dab-11e9-8138-0c7f4f0e5338.png)

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
This is just data issue, I can fix it quickly

**Comment by dimasciput** [comment]
@toniolsen fixed on the live site
