### ISSUE TITLE
Help - Manual

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1468]
@timlinux @dimasciput @toniolsen 
Link to manual not working on the live site? 

<img width="847" alt="Screenshot 2019-07-03 at 16 33 54" src="https://user-images.githubusercontent.com/44292029/60601021-9ec51880-9db1-11e9-9773-403e26f7492e.png">

**Comment by dimasciput** [comment]
I will move this to version 3 since we need the design first.

**Comment by timlinux** [comment]
Lets make the target of the links in help open in a new tab
