### ISSUE TITLE
Remove janette@frcsa.org.za from FBIS "account activation" email list

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1471]
Hi @dimasciput 

Yesterday, I gave my colleague, Janette, superuser access to FBIS, so that she could help me upload some SASS data. But now she is receiving the FBIS "account activation" emails. Could you please remove her from receiving these emails? Her email is janette@frcsa.org.za.

fbis@frcsa.org.za must be the only account receiving the account activation emails.

Thank you!

**Comment by dimasciput** [comment]
Hi @toniolsen, we need to remove her from superuser if you want her to not receiving any email. Just set her as a staff, and choose staff group.

![2019-07-05_14-03](https://user-images.githubusercontent.com/1979569/60704158-d789fc80-9f2d-11e9-921e-47085cd58ba9.png)

**Comment by helendallas** [comment]
Issue closed.
