### ISSUE TITLE
Tool tip - Shift-drag a rectangle on the map to zoom somewhere quickly

### ISSUE THREAD

**Issue by MikeSilberbauer** [kartoza/django-bims#1472]
When you use a search on a site code to zoom into an area, then clear the search, the view changes to the full map.

It would be great to have a way of zooming in by searching on a known site, and being able to view all sites while at that zoom level. (Maybe you can, and I am selecting the wrong links.)

If you know the area well, and you are on a fast data line, then zooming in and panning around is feasible. If the line is slow, zooming and panning is sluggish.

An alternative is to open a separate window and search with Google Maps, then do pattern matching between Google Maps and FBIS until you find the spot.

**Comment by timlinux** [comment]
Hi @MikeSilberbauer 

Just a note that you can also shift-drag an arbitrary rectangle on the map to zoom somewhere quickly.

For the behaviour you requested - let us go and see if we can come up with an intuitive way to do that.

Regards

Tim

**Comment by MikeSilberbauer** [comment]
Hi Tim,

Thank you for the response: shift-drag is what I was looking for!

FBIS is a really impressive system, and a huge improvement on what we have had in the past.

Regards,
Mike

Michael Silberbauer
SilberbauerM@dwa.gov.za<mailto:SilberbauerM@dwa.gov.za> * www.dwa.gov.za/IWQS<http://www.dwa.gov.za/IWQS>
Resource Quality Information Services Tel: + 27 12 808 9605 (if broken, try 082 908 2895)
Fax: + 27 12 808 2702 or +27 12 808 0338

**Comment by dimasciput** [comment]
This should be fixed by the new lasso tool in the testing.
