### ISSUE TITLE
Collector/Assessor filter problem

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1474]
I entered SASS data for this site (G4BOTR-00009) and specified Justine Ewart Smith as the Assessor:
![Screenshot 2019-07-10 at 08 49 56](https://user-images.githubusercontent.com/43198125/60947056-f9013480-a2ef-11e9-89ca-9631a3239115.png)

Then when I search Justine Ewart Smith in the Collector/Assessor field the site that I entered data for (i.e. G4BOTR-00009) does not show up in the multi-site detailed dashboard:
![Screenshot 2019-07-10 at 08 50 47](https://user-images.githubusercontent.com/43198125/60947382-b429cd80-a2f0-11e9-9bcd-645364e4fea5.png)

@dimasciput

**Comment by dimasciput** [comment]
Fixed in http://freshwaterbiodiversity.org @toniolsen
