### ISSUE TITLE
Validate SASS data upload

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1475]
Can a validation action please be set up for the SASS data upload, similar to the fish?
We need to be notified when SASS data is added and then validate it.

@dimasciput

**Comment by timlinux** [comment]
@dimasciput based on our discussion with FRC please just send an email alert whenever a SASS record is added or changed (sent to fbis email)

**Comment by dimasciput** [comment]
Added notification in http://freshwaterbiodiversity.org @toniolsen @helendallas
