### ISSUE TITLE
Pop up notice when users sign up

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1476]
We would like a notice to pop up when people sign up to include some points that were in our release email. We are getting people signing up who didn't receive the release email so we just want to make sure people know not to add fake data etc.

**Could the pop up notice please say:**

Welcome to Version 2 of the Freshwater Biodiversity Information System (FBIS)!

The FBIS serves as a community platform for inventory and maintenance of freshwater biodiversity data with an end goal to assist the evaluation of long-term change in river biodiversity and ecosystem condition in South Africa.

This project, funded by the JRS Biodiversity Foundation and SANBI, and implemented by the FRC and Kartoza. System development is following an iterative process whereby user needs and feedback are incorporated in each of the three iterations of the system planned for the three-year (2018-2020) project.

This is not the final version (there is still a lot of refinement and additional functionality planned over the next year) so you may come across some bugs and errors. Please alert us to these by emailing a description and screenshot to fbis@frcsa.org.za. 

By signing up and creating an account you will be able to (1) explore the map, (2) download maps, data, graphs and reports, (3) create a site and upload data, (4) query the data in the system and (5) flag an issue or system bug. If you do not sign up, you will still have access to all the above functions except the ability to upload data. We encourage you to upload fish and SASS records, so long as they are 'real data' - so as to keep FBIS as clean and accurate as possible.

The FBIS V2 release includes access to FBIS, a FBIS V2 user manual (accessed via the 'Help' tab on the top bar of the site) and a short video demonstration here https://youtu.be/L_hkoE8fDgo. These aids should help you to navigate your way around the system and test out the main functions and features, as well as flag any issues you pick up on while testing. Any questions can be directed to fbis@frcsa.org.za.

Please remember when uploading data: **we only want real, non-fictitious data starting from now on.** 

Happy testing, and we look forward to receiving your feedback!

@dimasciput @timlinux @jeremyshelton @helendallas

**Comment by timlinux** [comment]
Just show once to the user and never show again after they dismiss it.

**Comment by dimasciput** [comment]
Added to freshwaterbiodiversity.org @toniolsen @helendallas

**Comment by jeremyshelton** [comment]
@dimasciput @ann26 

Pop-up notice on home page too long. Please replace with this shorter version. 

Welcome to Version 2 of the Freshwater Biodiversity Information System (FBIS)!
The FBIS serves as a community platform for evaluating long-term change in river biodiversity and ecosystem condition in South Africa.
System development is following an iterative process, so you may come across some bugs and errors. Please alert us to these by emailing a description and screenshot to fbis@frcsa.org.za.
The FBIS V2 release includes access to FBIS (by signing up and creating an account), a FBIS V2 user manual (accessed via the 'Help' tab on the top bar of the site) and a short video demonstration here https://youtu.be/L_hkoE8fDgo. These aids should help you to navigate your way around the system and test out the main functions and features, as well as flag any issues you pick up on while testing. Any questions can be directed to fbis@frcsa.org.za.
Please remember when uploading data: we only want real, non-fictitious data starting from now on.
Happy testing, and we look forward to receiving your feedback!

**Comment by dimasciput** [comment]
@jeremyshelton you can change it here : http://freshwaterbiodiversity.org/admin/bims/sitesetting/1/change/

I just updated it, closing this ticket now

**Comment by helendallas** [comment]
@dimas

**Comment by timlinux** [comment]
@helendallas you can modify it as needed at this link:

http://freshwaterbiodiversity.org/admin/bims/sitesetting/1/change/

Due to it not being a page we cant add it in flat pages.

How about we get @dimasciput to add a shortcut 'Change welcome message' to the Admin menu on the main site so you can find your way there easily. Only staff users would see that link.

**Comment by jeremyshelton** [comment]
@timlinux this link is not working for me. Any idea why that might be? @dimasciput

**Comment by dimasciput** [comment]
@jeremyshelton what is not working? only superuser can access this page, you need to login as superuser

**Comment by jeremyshelton** [comment]
@dimasciput ok, got it.

**Comment by jeremyshelton** [comment]
@dimasciput would it be possible to add me as a superuser?
