### ISSUE TITLE
Need more details from the user signing up

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1477]
I need more details from the user creating an account. At the moment only an email address is sent to me. 
It would be great if the users full name, institution and role (i.e. researcher, consultant) could be sent to fbis@frcsa.org.za along with the email, just so that I have more details and confidence in granting access to users. These details should be compulsory to fill in on sign up.

Is this possible? @dimasciput @timlinux @jeremyshelton @helendallas

**Comment by timlinux** [comment]
Also @dimasciput to make the full name and organisation to compulsory on sign up

**Comment by toniolsen** [comment]
On the signup page
Full name, Institution, Role and email address must be made compulsory.
For now people can type in their Institution freely. We will develop a dropdown list for this in the future.

But for Role the following options in a dropdown must be included:
1.) Water Resource Manager
2.) Researcher 
3.) Consultant
4.) Conservation Planner
5.) Citizen

@helendallas @dimasciput @jeremyshelton @timlinux
