### ISSUE TITLE
Big picture Ticket 1: Metadata table (aim for end of August)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1478]
@dimasciput @timlinux @toniolsen @helendallas 
- We need a table at bottom of all dashboards (including taxon, single and multisite dashboards for fish, SASS, invertebrates, algae), wherever it fits in best. 
- The table should include a list of all references linked to the data displayed in the dashboard (i.e. filtered by the user)
- In some cases, the references will link the user to a downloadable PDF (theses, reports), DOI for al journal articles (peer-reviewed scientific literature), URL for databases (like GBIF)

![IMG_5308](https://user-images.githubusercontent.com/44292029/61375268-bf579d00-a89e-11e9-967c-931134068e88.JPG)

**Comment by toniolsen** [comment]
@dimasciput, Please see the attached excel spreadsheet for the CFE fish data with associated DOIs.
[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3550326/CFR.Fish.Data_excl_SAIAB.xlsx)
This data may need to be re-ingested to link the already existing data/occurrence records in the system with the associated study reference/DOI.

Another important thing is to figure out a workflow of how to link already existing occurrence records in the system to PDFs that I will upload...

We also need to build a Metadata table at the bottom of all dashboards to show the study references that the occurrence records are linked to.

@jeremyshelton @helendallas @timlinux

**Comment by dimasciput** [comment]
Hi @toniolsen some data don't have valid doi number -> http://agris.fao.org/agris-search/search.do?recordID=XF2015028470, can you fix them?

**Comment by toniolsen** [comment]
Hi @dimasciput, apologies. Those ones may not have valid DOIs. I will delete those and then reupload the datasheet...

**Comment by toniolsen** [comment]
@dimasciput 
Here is the CFE fish data with the incorrect DOIs/links removed:
[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3565002/CFR.Fish.Data_excl_SAIAB.xlsx)
Thanks!

**Comment by toniolsen** [comment]
@dimasciput, I see that you have started creating the metadata table for the dashboards. Thanks! Here is a more clear mock-up of the table:
![Screenshot 2019-09-02 at 16 41 17](https://user-images.githubusercontent.com/43198125/64125157-09d69f80-cda1-11e9-939f-a5c7ce271269.png)
Would be great if we could get it into this format.

@jeremyshelton @helendallas @timlinux

**Comment by dimasciput** [comment]
Hi @toniolsen, @helendallas, @jeremyshelton 

1. Currently we don't have author field for unpublished data, should we add that?
2. We don't have source field for published report, should we add that too? 
3. Can we use current metadata table for now, and update it after we have migrated the biobase data? cc @timlinux 

It would be good to have this table before we implemented the document management.

**Comment by toniolsen** [comment]
Hi @dimasciput, 
1.) We can use the "Owner" field that is filled in when the user adds data as the "Author" field for the unpublished data. The "author" for unpublished data is just the person or organisation that collected the data.
2.) The source field for published reports and theses will have to be manually populated as this will have to be extracted from actual PDFs.
3.) Sure, getting the metadata into this table format can wait until after the biobase data has been migrated.

Apologies @dimasciput for only giving you this table mockup now. I should have provided it from the start. I will remember for next time.

@jeremyshelton @helendallas @timlinux

**Comment by timlinux** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/178003/66032539-79a18c80-e4fd-11e9-8ab8-1830f97a796f.png">

Let's rotate the table so that the record titles go down - that should make it handle long field contents better

**Comment by helendallas** [comment]
@timlinux @dimasciput @jeremyshelton 

I really don't like the idea of rotating the table. Can we not just exclude the Notes column, then make the DOI/URL available as a hyperlink on the author????

And spread the table over the whole of the bottom of page, not one column only.

Just my sixpence.....

**Comment by dimasciput** [comment]
@timlinux @helendallas @jeremyshelton 

So what should we do about the table? Can we leave it as it is until we have a clear design?

**Comment by dimasciput** [comment]
let's use this ticket instead https://github.com/kartoza/django-bims/issues/1660
