### ISSUE TITLE
Big picture Ticket 2: Import Rivers database abiotic data (aim for end of September)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1479]
@timlinux @dimasciput @helendallas @toniolsen 

- Import Rivers database abiotic data with guidance from @helendallas 
- See ticket ticket #1481 for presenting the abiotic data

**Comment by helendallas** [comment]
I have created a Master list of all physico-chemical data from Rivers DB and Biobase. It is long but lets keep as is so that we don't lose data form legacy datasets.

[Master List of Physico_Chemical Variables.xlsx](https://github.com/kartoza/django-bims/files/3406387/Master.List.of.Physico_Chemical.Variables.xlsx)

@dimasciput @timlinux @jeremyshelton @toniolsen

**Comment by dimasciput** [comment]
The chemical record/abiotic data has been imported to the testing, here is the migration diagram from old db to new one 

![image](https://user-images.githubusercontent.com/1979569/67179371-48cbbd80-f400-11e9-92f1-ca49bc145c8c.png)

The following is a list of tables that have been migrated : 
- BioSiteVisitChem
- BioChemDate
- BioSiteVisitChemValue

Here is the admin page for the chemical record : http://testing.healthyrivers.kartoza.com/admin/bims/chemicalrecord/

**Comment by helendallas** [comment]
@dimasciput 
Please can you add FBIS Site Code to admin page, and a way to search for a Site please. 

Is this where I would need to edit data that I observe to be incorrect, e.g. 
A1NGOT-DINOK, 3/15/2007, Dissolved oxygen, 23.7 mg/l

For this site, pH is missing, but it does have data

From original Rivers DB
SiteCode | SiteVisit | ChemCode | ChemDescription | ChemValue
A1NGOT-DINOK | 12/2/2005 | PH | pH | 8.07
A1NGOT-DINOK | 3/15/2007 | PH | pH | 8.12
A1NGOT-DINOK | 8/20/2007 | PH | pH | 8.05
A1NGOT-DINOK | 8/17/2009 | PH | pH | 8.44
A1NGOT-DINOK | 2/16/2012 | PH | pH | 7.72

Checked another site and pH is missing there to:
A2ELAN-KLIPB

**Comment by dimasciput** [comment]
@helendallas I just checked, actually we have that data, but somehow it has different unit (PH_UNIT), let me fix it, should be easy.

**Comment by dimasciput** [comment]
@helendallas fixed in testing
![image](https://user-images.githubusercontent.com/1979569/68448067-db4bc980-0214-11ea-800e-71a40d60aa3d.png)

**Comment by helendallas** [comment]
@dimasciput 

Please remove (pH_Unit) on y axis, for all pH graphs.

It is not necessary, thanks
