### ISSUE TITLE
Big picture Ticket 3: Import BioBase abiotic data (aim for end of September)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1480]
@timlinux @dimasciput @helendallas @toniolsen 

- Import Biobase abiotic data with guidance from @helendallas 
- See ticket ticket #1481 for presenting the abiotic data

**Comment by dimasciput** [comment]
![biobase_](https://user-images.githubusercontent.com/1979569/64004888-6b94d080-cb39-11e9-82be-1bedae931b06.png)

The ER diagram

**Comment by helendallas** [comment]
@dimasciput 
I need to make some changes - can you please send me the diagram so that I can edit/annotate

**Comment by helendallas** [comment]
@dimasciput 

here is a powerpoint file with comments and highlights, plus an extra page. Please have a look at this and then lets chat it though on wednesday.

[Biobase Relationships Dimas_HD.pptx](https://github.com/kartoza/django-bims/files/3589919/Biobase.Relationships.Dimas_HD.pptx)

**Comment by dimasciput** [comment]
![collection_record_migration](https://user-images.githubusercontent.com/1979569/64942226-b715e100-d892-11e9-813b-23c690d11b7e.png)
![chemical_record_migration](https://user-images.githubusercontent.com/1979569/64942227-b715e100-d892-11e9-8c94-0d9044ef1361.png)

**Comment by dimasciput** [comment]
The following is a list of migrated Biobase tables:

- BioSiteVisitBioBiotope
- BioBiotope
- BioReference
- BioSiteVisitBio
- BioSiteVisitBioBiotopeTaxon
