### ISSUE TITLE
Big picture Ticket 6: Invertebrate taxon, single site & multi-site dashboards (aim for end of October)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1483]
Meet with @carina1000 early September to finalise mock-ups

**Comment by timlinux** [comment]
Any update on this @jeremyshelton ?

**Comment by jeremyshelton** [comment]
@timlinux the update on this is that didn't need to meet with Carina because we decided to adapt existing dashboard designs from fish to invertebrate taxon, rather than mock-up new ones. 

There are still some refinements needed to get these dashboard designs standardised among modules, eg see ticket #1589, and then this big picture ticked can be closed 👍

**Comment by jeremyshelton** [comment]
@dimasciput @ann26 @timlinux 
The overview panel (table on left) of single site detailed dashboards needs to be standardised. At present, the one for SASS has a different layout & design to the one for fish or invertebrate taxa. 
See ticket #1589 for details.
