### ISSUE TITLE
Editing SASS forms (Perlidae to Notonemouridae)

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1487]
@dimasciput,
We are trying to edit our SASS forms. We need to delete some SASS records with Perlidae in them and change it to Notonemouridae. 
So I delete "1" for Perlidae, and put "1" for Notonemouridae and click "submit".
But then Both Perlidae and Notonemouridae fields are populated with "1". So both taxa are now recorded instead of just one.

So basically we cannot delete a taxon from the SASS sheets.

@helendallas

**Comment by dimasciput** [comment]
@toniolsen which data is this? I couldn't reproduce it from my local

**Comment by helendallas** [comment]
G2HOUT-ORANJ
I selected SASS module, searched Perlidae, and navigated to this site. I need to change the record by deleting Perlidae and adding Notonemouridae (misidentification as perlidae do not occu in this region). But Perlidae do not get deleted.

![Screenshot_2019-07-19 FBIS SASS](https://user-images.githubusercontent.com/45286876/61516519-7c640980-aa05-11e9-8013-1ced07213043.png)

**Comment by helendallas** [comment]
This is the form after I went it and deleted Perlidae, and added Notonemouridae. You see both are now shown

**Comment by dimasciput** [comment]
Fixed @helendallas @toniolsen

**Comment by helendallas** [comment]
@dimasciput 
There seems to be a problem now with the number of taxa.....see example below

![Screenshot_2019-07-19 FBIS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/61538656-29587980-aa3a-11e9-9e0c-25c12a0b7762.png)

**Comment by helendallas** [comment]
And all score calculations actually

**Comment by dimasciput** [comment]
@toniolsen what data is this? Can you copy the url here.

**Comment by dimasciput** [comment]
@helendallas actually that's not a bug, because you search Perlidae, it will only display for that taxa only. If you want me to change behavior, please create a new ticket, and I will update it when I return from leave.

**Comment by helendallas** [comment]
Ah okay. I assumes as I had navigated to the full SASS record it would display all. No problem, but probably best to update when back from your leave. Enjoy!
