### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1494]
Issue separated from #1468 
Create easier way to report an issue

Also, will we be able to give the users some guidance on how to report an issue, or is that being covered in ticket #1269? ...and perhaps a slicker report an issue 'button'?

<img width="621" alt="Screenshot 2019-07-04 at 10 24 51" src="https://user-images.githubusercontent.com/44292029/60651267-28bec100-9e46-11e9-95de-9f6ef755ffc0.png">

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput I don't think the 'report a bug' button should be in the help tab? 

Can we put it somewhere on the map instead?

<img width="806" alt="Screenshot 2019-10-02 at 15 38 57" src="https://user-images.githubusercontent.com/44292029/66049438-af5d6a00-e52b-11e9-8be5-070d837d09be.png">

GitHub is not ideal for user bug reports. Can the button instead lead to a place where the user can enter a brief description of the issue and then a screenshot of the bug?

**Comment by helendallas** [comment]
Looks fine - closing issue
