### ISSUE TITLE
Add SASS Record - Biotopes order needs changing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1496]
Please change order of Biotopes sampled, so that it matches the SASS spreadsheet - to ensure users don't enter data incorrectly.

![Screenshot_2019-08-02 FBIS SASS](https://user-images.githubusercontent.com/45286876/62366025-05129780-b526-11e9-8bbd-99512de90d48.png)

Aquatic vegetation needs to move up so that it is:

Bedrock
**Aquatic vegetation**
Marginal vegetation in current

**Comment by dimasciput** [comment]
Updated
