### ISSUE TITLE
Data ownership - Site and SiteVisit

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1498]
The person who creates the site becomes the Site Owner. This is the logged in User.  In some cases the Site Owner should be an organisation such as CapeNature (individuals move on buth the data should remain with the organisation).

How do we deal with this? 

The same applies for SiteVisit level data such as SASS data. In the legacy Rivers Database the person who created the SiteVisit, i.e. who was logged in, became the SiteVisit Owner (owner of the SASS data), not the Assessor.  The Assessor was recorded, as this is important for the SASS accreditation side.

The Rivers Database had the functionality for the logged in user to reassign Ownership at Site and SiteVisit Level. 

Please can you discuss this and revert.

**Comment by helendallas** [comment]
Further to this. Janette created a site, which then showed her as the Collector. However this is incorrect. We need a way to assign the Site Ownership to someone or an organisation.

Also Superusers / staffers need to be able to edit this, so that I can change the name Janette to the correct person.

![Screenshot_2019-08-15 FBIS Location Site Form](https://user-images.githubusercontent.com/45286876/63095516-bcb69900-bf6b-11e9-94c6-c500f645db3c.png)

**Comment by dimasciput** [comment]
this has been implemented
