### ISSUE TITLE
Assessor - Collector

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1505]
Collector (Fish) and Assessor (SASS) should always be the full name of the person, not first name only such as on the Single Site dashboard for fish.  Can we force this? 

![Screenshot_2019-08-06 FBIS Map](https://user-images.githubusercontent.com/45286876/62519951-d39f1200-b82c-11e9-849c-bcd5dd556731.png)

**Comment by helendallas** [comment]
I think the Username is what is used, and this can be anything. Can we change it that someone enters their First Name and Surname and we generate a username from this?  Sign up is designed this way.

See Toni below

![Screenshot_2019-08-06 Change user Django site admin](https://user-images.githubusercontent.com/45286876/62542841-e6c9d600-b85c-11e9-8c50-22ea5e9f5213.png)

![Screenshot_2019-08-06 FBIS Sign up](https://user-images.githubusercontent.com/45286876/62542923-1842a180-b85d-11e9-9193-83200a7f9ce2.png)

**Comment by dimasciput** [comment]
> Collector (Fish) and Assessor (SASS) should always be the full name of the person, not first name only such as on the Single Site dashboard for fish. Can we force this?

@helendallas so collector and assessor are different object, assessor refers to user object (they have full description of the user, e.g. first name, last name, email etc). Collector is just a string field (they don't have detailed description attached to them), this is because when we fetch data from GBIF, they have a collector's name. 

For this case, Michiel is a collector's name (I've checked it from the database), so we don't have any additional information.

**Comment by helendallas** [comment]
Thanks @dimasciput 
@timlinux @toniolsen @jeremyshelton 
Please can we chat about this is our zoom today. Its quite important as sign ups are ramping up, and we need to keep it clean and correct.

**Comment by helendallas** [comment]
As per our last zoom @dimasciput , Username needs to be automated based on the First Name + Surname when sign in happens. This then needs to be automated for the Assessor for SASS Form. At the moment if the user does not put this in then it is blank. It cannot be blank.

**Comment by helendallas** [comment]
@dimasciput 
I noticed now there is Collector and Assessor  on the Add SASS record form. 
@timlinux Do we perhaps need to chat through this some more. I don't want to add complexity but we need an Assessor for SASS data, not collector.

Then as per ticket #1498 a SiteVisit (= for example a SASS assessment) has to have a SiteVisit Owner (who may actually be an organisation).

![Screenshot_2019-08-15 FBIS SASS(1)](https://user-images.githubusercontent.com/45286876/63098546-68afb280-bf73-11e9-8fca-fad2d96b9af9.png)

**Comment by helendallas** [comment]
@dimasciput 

The SASS form cannot have a Collector and Assessor - it is going to confuse people. 
Please keep Assessor, but rename Collector to **Owner**. 

This person may be the same but not always and the Owner may be an organisation as per previous comment.
