### ISSUE TITLE
Detailed Dashboards - Overview needs standardising

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1510]
At the moment the Fish Dashboards (Single Site) and SASS dashboards (Single Site) look very different.  Some fields are common to both, while some are only included in one or the other, and the order, look and feel are different.

I propose that before moving on to the next dashboards (Invertebrate Species, Algae), we standardise. 

@dimasciput @timlinux 
How easy is this to do?  

![Screenshot_2019-08-06 FBIS SASS Dashboard Single Site(2)](https://user-images.githubusercontent.com/45286876/62524456-f7b32100-b835-11e9-98b7-3f370192f939.png)

![Screenshot_2019-08-06 FBIS Map(6)](https://user-images.githubusercontent.com/45286876/62524461-fa157b00-b835-11e9-9284-bbf89c021886.png)

**Comment by dimasciput** [comment]
@helendallas @timlinux 

This is because we implemented these dashboard differently. Since sass data is more complicated and have a lot more calculation, we place them on different page, that way we can easily manage them. 
Ideally, we should move all dashboards (species and site) to different pages just like SASS dashboard, not the other way around.

**Comment by helendallas** [comment]
Okay thanks @dimasciput 
I am only referring to the Overview sections in each. And not major things, just sort order, some were never added, some needs slight rewording- style less important.  

**For example Fish order should be:**
FBIS Site Code 
Site coordinates
Site description
River
Geomorphological zone
Refined Geomorphological zone
**Catchments** 
Primary
Secondary
Tertiary
Quaternary
**Management Areas**
Water Management Area
Sub Water Management Area
River Management Area
**SA Ecoregions**
Ecoregion Level 1
Ecoregion Level 2
Freshwater Ecoregion
Province

**Comment by helendallas** [comment]
I propose that this Overview order be rolled out for all Single Site dashboards

**Comment by dimasciput** [comment]
@helendallas ah ok, then that should be less difficult. Probably I will create an admin page to do this, so staff user can just reorder the overview order there, currently we did this manually in the code.

**Comment by helendallas** [comment]
That sounds great @dimasciput . If we were able to do these small edits, reorders, then we could happily take these off you plate :)

It may apply to quite a few of the "picklists"

**Comment by dimasciput** [comment]
updated in testing

**Comment by helendallas** [comment]
@dimasciput 
Much better but still need to correct last section of overview

![Screenshot_2019-11-14 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/68860596-84516300-06f2-11ea-9b96-965a03d25e9e.png)

Should be:

![Screenshot_2019-11-14 Cleaning up Single Site dashboards before we make more · Issue #1589 · kartoza django-bims](https://user-images.githubusercontent.com/45286876/68860575-74d21a00-06f2-11ea-941f-ca927c1e0c92.png)
