### ISSUE TITLE
Data Sources - FBIS, GBIF 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1515]
When you first open FBIS, the default is all sites are returned, 13207. But neither FBIS of GBIF are checked in the Data Sources Draw.  FBIS = 5689 sites; GBIF= 7649 sites.

The default should be FBIS checked only, then the user has the option to add in GBIF. Same will apply for other data going forward.

![Screenshot_2019-08-06 FBIS Map(11)](https://user-images.githubusercontent.com/45286876/62540444-eda21a00-b857-11e9-8618-803c689a57fa.png)

**Comment by helendallas** [comment]
@dimasciput 
I see you have closed this but it has not been implemented. When a user first login, the FBIS box should be ticked, and only FBIS data shown. The user is then able to add GBIF data if they want to see these as well.

![Screenshot_2019-08-15 FBIS Map](https://user-images.githubusercontent.com/45286876/63097498-e0301280-bf70-11e9-8089-639ae1160e34.png)

**Comment by dimasciput** [comment]
implemented on freshwaterbiodiversity.org
