### ISSUE TITLE
Sign Up - Existing Legacy User

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1516]
When a user signs up using the Same Name and email as what already exists in Users (from the legacy Rivers Database) - e.g. Gerhard Diedericks; then they need to be prompted that they are already registered, and then taken to the page where they can update their profile.

This will prevent us getting multiple sign ups by the same person.

![Screenshot_2019-08-06 FBIS Map(12)](https://user-images.githubusercontent.com/45286876/62541041-3efed900-b859-11e9-934e-c505027582aa.png)

**Comment by dimasciput** [comment]
@helendallas 
We have prevented users from registering with the same email. I think this is a different bug, let me fix it.
