### ISSUE TITLE
View SASS record - need a close X

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1517]
We need a Close (X) button for a user to close this form, which takes the user back to the previous form when they click it.

![Screenshot_2019-08-06 FBIS SASS(2)](https://user-images.githubusercontent.com/45286876/62541723-9fdae100-b85a-11e9-9141-06a81bb9c222.png)

**Comment by toniolsen** [comment]
Tested this. It's not working on the testing site.
@dimasciput

**Comment by toniolsen** [comment]
@dimasciput, it was working earlier on the live site and then it just stopped working?

**Comment by helendallas** [comment]
@dimasciput 
Once I have Update a SASS Record, hit Next, dorrected Source Reference, the option to Close by clicking the X does not work. I really need thi urgently as it takes me ages now as I have to go back to the map and type in the FBIS code etc. If the X button worked I would go from the Updated SASS data to the SASS Site, where I can then go and update another SASS Record

![Screenshot_2019-09-19 FBIS SASS(5)](https://user-images.githubusercontent.com/45286876/65259077-60174280-db04-11e9-92ed-c96f0feb3991.png)

**Comment by dimasciput** [comment]
This is only in testing server for now

**Comment by helendallas** [comment]
@dimasciput 
Is it possible to roll this out to the live site, it is really a long and laborious process to edit SASS data, without this X button working.

**Comment by dimasciput** [comment]
@helendallas yes it's possible, let me do that today

**Comment by dimasciput** [comment]
@helendallas deployed to live server since yesterday
