### ISSUE TITLE
Strange blue lines?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1519]
@dimasciput @timlinux @toniolsen @helendallas 

Some users are having this problem of these strange blue lines appearing when the map is opened, and then not going away. 

Not sure which OS, but I think it's mostly an issue on windows machines. 

On my Mac, using Safari, I also see them for a second or two while the map is opening up.

![image001](https://user-images.githubusercontent.com/44292029/62604566-3d342480-b8f0-11e9-9f36-0d498f96b64e.jpg)

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
This issue is still being reported by several users...

**Comment by dimasciput** [comment]
@timlinux @jeremyshelton this might be an issue with the map provider, we are using free version of https://www.maptiler.com, which can only display 800 views/day. I think we need to change the provider, what do you think @timlinux ?

**Comment by jeremyshelton** [comment]
@dimasciput yeah this seems to be a long-standing issue for certain users...

**Comment by dimasciput** [comment]
@jeremyshelton we can change the map tile, but the map will not be as goot as it is now.

**Comment by jeremyshelton** [comment]
@dimasciput what is the next best option for title map?

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux @NyakudyaA 

OK so at todays meeting we decided that Kartoza will work on building a new base layer for FBIS that shows rivers automatically. 

How about something like this, which shows terrain and rivers, provincial boundaries, towns and cities.....? Just a suggestion :)

<img width="1232" alt="Screenshot 2019-10-10 at 13 39 10" src="https://user-images.githubusercontent.com/44292029/66565815-af7ceb80-eb63-11e9-9d75-b9d2f39a53e3.png">

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
Thoughts in this?

**Comment by timlinux** [comment]
@NyakudyaA 

As discussed today in our call with @jeremyshelton 

For small scale:

* Rivers (main stem)
* Dams
* Provinces
* Main place names

As we zoom in show all rivers, place name etc,

At large scale we can show more details of rivers, district boundaries etc,

**Comment by jeremyshelton** [comment]
@NyakudyaA @timlinux any further progress with this base layer for map landing page?

**Comment by NyakudyaA** [comment]
@jeremyshelton I have done some work on this. 
![map-base](https://user-images.githubusercontent.com/2510900/69044162-19a76c80-09fd-11ea-968b-9ab0cdfa1363.png)

**Comment by jeremyshelton** [comment]
Looks interesting @NyakudyaA perhaps major towns and cities could also be displayed, and the brown rivers could be a different shade of blue? What does the user see if they zoom in?
Lets discuss this further at next weeks catch-up 👍

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @timlinux The blue 'blue line issue' is still an issue. Here is a screenshot of the map loaded on a mediocre internet connection today:


<img width="1440" alt="Screenshot 2020-01-12 at 14 02 44" src="https://user-images.githubusercontent.com/44292029/72218582-ef79b300-3544-11ea-983b-d9dd47e2e8e6.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton I am going to take a look at it tomorrow with Tim

**Comment by dimasciput** [comment]
@NyakudyaA any updates for this?

**Comment by NyakudyaA** [comment]
> @NyakudyaA any updates for this?

Hi @dimasciput It's currently working here https://maps.kartoza.com/kartoza/ with the layers coming from http://maps.kartoza.com:8280/ows/?map=kartoza/basemap.qgs 
I am still struggling with some Nginx config so that it can run under ssl
