### ISSUE TITLE
User registration confirmation email needed

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1520]
@dimasciput @helendallas @timlinux @toniolsen 
When a user signs up they should receive a  registration confirmation email. 

Perhaps including a link to the login page and a reminder of their username and password in the email would also be helpful?

**Comment by dimasciput** [comment]
@jeremyshelton currently they will only get an email when they have been activated. Could you give me the email format when they were first registered?

**Comment by jeremyshelton** [comment]
@dimasciput how about something like the following: 

Welcome, 

Thank you for registering with the Freshwater Biodiversity Information System (FBIS).

Your user name is: XXXXX
Your password is: XXXXX

You will receive an email as soon as you account has been activated. 

Please don't hesitate to contact us by emailing fbis@frcsa.org.za should you have any questions.

Regards,
The FBIS team
