### ISSUE TITLE
Log in error message

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1521]
@dimasciput @toniolsen @helendallas @timlinux 

When I log in, I get this error message. 

If I then go to the site, I am actually logged in - just weird that this error comes up instead of taking me straight to the site...

<img width="520" alt="Screenshot 2019-08-07 at 08 57 38" src="https://user-images.githubusercontent.com/44292029/62605325-c435cc80-b8f1-11e9-8df9-7b588b4f0698.png">

**Comment by dimasciput** [comment]
@jeremyshelton I couldn't reproduce this error, maybe you have some issues on your browser, or your internet connection. Can you try again multiple times?

**Comment by jeremyshelton** [comment]
@dimasciput it has been happening to be since the site has been live. 

@toniolsen @helendallas have you guys ever experienced this issue?

**Comment by toniolsen** [comment]
@jeremyshelton, no I have never seen that error message.

**Comment by helendallas** [comment]
Not I said the fly... @jeremyshelton Always works fine for me
