### ISSUE TITLE
Downloading CSV of some fish data

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1522]
I was alerted to this issue by a user.

When one downloads the csv for all the Micropterus salmoides data, the csv is returned with just the column headings and no data underneath?
I have attached the csv that was returned here:
[7e31ff6dcee9f56717f5d7c31a8b99aa.xlsx](https://github.com/kartoza/django-bims/files/3475896/7e31ff6dcee9f56717f5d7c31a8b99aa.xlsx)

And the URL: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Micropterus%20salmoides&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=[%22validated%22]&sourceCollection=&ecologicalCategory=

The same sort of thing happens with Sandelia capensis, although the csv doesn't download and then the page becomes unresponsive. 
The URL here: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Sandelia%20capensis&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=[%22validated%22]&sourceCollection=&ecologicalCategory=

@dimasciput @jeremyshelton @helendallas @timlinux

**Comment by dimasciput** [comment]
this has been fixed on testing
