### ISSUE TITLE
Users cannot log on to FBIS 

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1531]
A few users have emailed this morning saying they cannot log on to FBIS. And neither can I. The error page is this one below:

![Screenshot 2019-08-12 at 10 50 30](https://user-images.githubusercontent.com/43198125/62857408-79e88d00-bcef-11e9-90f9-351aa3ad81aa.png)

@dimasciput @timlinux @helendallas

**Comment by dimasciput** [comment]
@toniolsen is this on freshwaterbiodiversity? what is your username?

**Comment by toniolsen** [comment]
@dimasciput 

yes, this is on the live site: http://freshwaterbiodiversity.org/account/login/

Usename is just fbis

**Comment by dimasciput** [comment]
@toniolsen did you by any chance remove `AnonymousUser` ?

**Comment by toniolsen** [comment]
@dimasciput yes I think I might have

**Comment by dimasciput** [comment]
@toniolsen @helendallas ok I fixed it, please don't remove the `AnonymousUser`, we need that for the system.

**Comment by toniolsen** [comment]
@dimasciput 
I am really sorry! I thought it was just a random user. I have noted this.
Thanks!

**Comment by dimasciput** [comment]
@toniolsen no worries, it does look random. :smile:
