### ISSUE TITLE
Document management 

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1542]
@helendallas @jeremyshelton @toniolsen here is what we are going to implement for managing sources. Please give input if you would like to change the approach.

First of all the add fish etc. forms will have their 'Submit' button replaced with a 'next' button:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/178003/63025558-5c5b2500-bea1-11e9-86f2-b941eb102304.png">

When pressing next we will show you this form:

<img width="875" alt="Screenshot 2019-08-14 at 15 13 04" src="https://user-images.githubusercontent.com/178003/63033666-ead6a300-beaf-11e9-82fa-c3a5c6646c15.png">

The elements of this form will be hidden or shown depending on which Reference category is selected using the logic shown in the simple flow chart below:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/178003/63025918-1fdbf900-bea2-11e9-9f7c-4739848c0af0.png">

Not that in our logic, only one reference / DOI / Database can be associated with the records in the form. So if you want to enter data from two different sources, you must do two flows through the form, once for each source.

The biological collection model will have four fields added:

1. source_database_id -> links to a simple lookup table for source databases. In the case that the referenced database (e.g. RiversDB) does not already exist on the system, the user will be able to add it using a simple form:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/178003/63026581-59613400-bea3-11e9-9ab5-34cc4f06ee72.png">

2. doi -> will directly store the DOI which we can look up from the bibliography app. Any duplicates will be detected and managed seamlessly.

3. document_id -> links to an existing document in the document management system. The DMS must prevent a document being removed if there are biological collection records that reference it.

In the case that the user's referenced document is not already in the system, we will provide a simplified document upload tool that can be used to add it.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/178003/63026415-0dae8a80-bea3-11e9-8da3-8cb3df42aefa.png">

The documents uploaded will be browsable by staff users at http://freshwaterbiodiversity.org/documents/?limit=20

4. notes -> any biological collection record can have notes about the collection of that record added. In the case that a form captures multiple records, the note will be duplicated in each collection record.

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/178003/63026698-8a416900-bea3-11e9-8fd7-053c09606eed.png">

I hope that all makes sense? Please comment below if anything is unclear / needs tweaking.

**Comment by helendallas** [comment]
@timlinux @dimasciput 
This looks really great. Seems clear and simple, with the necessary provisions to ensure clean management of documents. 

Comments:
For New Document: We need to standardise this based on current fields. So Name should be Title
**Author
Year
Title
Journal/Source**??? = not sure what to call this?? @toniolsen 
or some equivalent for a user to provide details of the thesis/report, examples below

National Institute for Water Research, Research Report No 5 (Project 6.8.H. Ref W.6/6/8H)
or
University of Cape Town (in the case of a thesis)
or
Water Research Commission Report TT 123/22/08, Water research Commission, Pretoria.
--
Also standardise the way Authors are captured.....

**Comment by toniolsen** [comment]
@timlinux @dimasciput 
Great workflow! Thanks. Everything makes sense. I just have two comments on the reference category diagram:
<img width="506" alt="Ref category diagram" src="https://user-images.githubusercontent.com/43198125/63083985-0c806a80-bf42-11e9-9c36-6751282f178a.png">

@helendallas, I think we should call it "Source" so that covers journals, reports etc.

Authors should be captured in this format:
**Examples:**

Olsen, T., 2018

or

Dallas, H.F., Shelton, J.M., Olsen, T. and Sutton, T., 2019

**Comment by timlinux** [comment]
@toniolsen for your first comment I dont think we need to do that because when you enter a DOI our bibliography will. fetch you back a complete citation. And from our disucssion (FRC + Kartoza) we had agreed that we would not store physical copies of documents that are published in peer reviewed journals etc. right?

For your second comment, that is covered by the wireframe we provided above:


![](https://user-images.githubusercontent.com/178003/63026698-8a416900-bea3-11e9-8fd7-053c09606eed.png)

When the database you need to refer to is not already in the system, you can click a button and it will open the 'Add database' diagram as shown bottom right.

**Comment by timlinux** [comment]
@dimasciput  / @meomancer So based on @toniolsen and @helendallas comments, for the new document dialog we should add a field for date and include examples for the expected format for authors lists. See updated wireframe below.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/178003/63090392-0777e700-bf53-11e9-83ee-10f5de37050d.png">

**Comment by toniolsen** [comment]
@timlinux thanks for clarifying. Yes, that is correct, we don't want to store physical files of peer-reviewed articles, just the DOI.

@helendallas and I had a chat now and we need some clarification on this section:
![Screenshot 2019-08-15 at 11 53 43](https://user-images.githubusercontent.com/43198125/63090546-8cfb9700-bf53-11e9-94fe-e3c9c14f017c.png)

Would the user only fill this in if they wanted to add a new database not on the system? I am not sure if we should provide the URL to new databases? @helendallas 

And finally, in some instances for example someone will upload a PhD thesis, but this may have two or three peer reviewed articles linked to this PhD metadata. Is there an option to add "link to existing source" button so in these cases the PhD metadata can be linked to the paper?

**Comment by timlinux** [comment]
>Would the user only fill this in if they wanted to add a new database not on the system? 

Yes if it is already there they just choose it from the pick list.

> I am not sure if we should provide the URL to new databases? @helendallas

This can be an optional field.

> And finally, in some instances for example someone will upload a PhD thesis, but this may have two or three peer reviewed articles linked to this PhD metadata. Is there an option to add "link to existing source" button so in these cases the PhD metadata can be linked to the paper?

Is this really needed? I am worried it will add considerably to the system complexity  and we should be moving our focus on to bugs etc. rather than taking on anything too big in the document management side of things.

**Comment by helendallas** [comment]
I hear you. What about if users are encouraged to add this information (citations) in the Notes field.  So if papers are associated with a PHD dataset, then these are at least cited, or a DOI???

**Comment by timlinux** [comment]
> I hear you. What about if users are encouraged to add this information (citations) in the Notes field. So if papers are associated with a PHD dataset, then these are at least cited, or a DOI???

Perfect we can add a tooltip / hint about this.
