### ISSUE TITLE
Add Site - Collector should be changed to Site Owner

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1549]
The word Collector is incorrect in reference to a Site. Please change it to Site Owner

![Screenshot_2019-08-15 FBIS Location Site Form(1)](https://user-images.githubusercontent.com/45286876/63095682-233bb700-bf6c-11e9-95cf-c69bdf3e18e0.png)

The default should be the logged in User but should allow the logged in user to reassign the site to someone else

**Comment by dimasciput** [comment]
@helendallas then the site creator wouldn't be able to edit the site if the creator assign it to other user?

**Comment by helendallas** [comment]
@dimasciput 
This relates to the data capturer ticket # 1524. The person entering the data (creating a site, adding SASS data, adding fish data etc. is often not the person who did the assessment, or who first created the site.....so by allowing the data capturer to reassign ownership to an organisation or individual, then the correct person is listed. The data capturer should retain the rights to edit the data for this site/assessment only.  see ticket #1524.

Also The word "Collector" is going to create confusion here, so need to change to Site Owner.

**Comment by dimasciput** [comment]
@helendallas ok, then there will 2 users related to a site, the creator and the owner? Is that correct?

**Comment by helendallas** [comment]
Yes, that probably makes sense, as both the site owner and the data capturer may need to edit the data. It may often be the same person, but we need to include option for two users.
