### ISSUE TITLE
Standardisation of cartography for BIMS

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#155]
Last week I did some thinking about the cartography rules for BIMS. I drew up my thoughts into the above diagram. I think the current situation is not good because the user is not clear about what they are seeing and the cartography needs to change based on specific contexts

**Note** I don't mind if we lost the exploded marker in favour of some other paradigm, I am more concerned with what we show at different scales and that the colours of the markers remain uniform (not e.g. switching between red and yellow as we have it now)

![bims-sites-cartography](https://user-images.githubusercontent.com/178003/43063844-6dc6d7dc-8e5d-11e8-855f-6c359b87e799.png)

**Comment by cchristelis** [comment]
@carina1000, have a look at this. It is along the same theme that we chatted through last week.

**Comment by carina1000** [comment]
I like this @timlinux ! Although I don't understand everything, eg. when will the shape be a circle or polygon? "will be polygon if the geometry is polygon" (??)

Please see my suggestion of showing the different modules/species on a specific site on this ticket: https://github.com/kartoza/LEDET_BIMS/issues/169

**Comment by timlinux** [comment]
On Chatting with @carina1000 yesterday we propose a more simple approach:

![screen shot 2018-07-25 at 12 43 35](https://user-images.githubusercontent.com/178003/43248188-4c80650a-90b7-11e8-825c-ecda78e5fc8c.png)

> I like this @timlinux ! Although I don't understand everything, eg. when will the shape be a circle or polygon? "will be polygon if the geometry is polygon" (??)

Circle for multisites clusters, polygon when zoomed in close or doing species distributions

**Comment by timlinux** [comment]
Please ignore the 1:500 000 part in the note above left.

**Comment by timlinux** [comment]
Update diagram of above:

![screen shot 2018-07-30 at 10 42 04](https://user-images.githubusercontent.com/178003/43387133-f02cf0c0-93e5-11e8-979b-6bb2d45772de.png)

**Comment by carina1000** [comment]
@timlinux can we had this over to a developer?

**Comment by timlinux** [comment]
Just one more note @meomancer is that the 'single taxon' map should also be rendered in a different colour

@carina1000 to provide input on which colours to use

Might be nice to allow softcoding colours so that we can set them in admin UI or something to make it easy to share same code with different clients

**Comment by carina1000** [comment]
@meomancer It would be nice to use the LBIMS colours.

For the variable sized: #dbaf00
For the single Taxa colours: #1b900d

**Comment by meomancer** [comment]
hi @timlinux 
>Just one more note @meomancer is that the 'single taxon' map should also be rendered in a different colour
are the colours based on class or taxon? 

I see the cartography:
- If the clusters are not single, we give blue colors and sizing it depend on the number. Could you provide the calculation for this? 
- The single taxon is based on the colors, how about the single site marker? Because on default map (without filter and search), we are showing site instead records.

**Comment by meomancer** [comment]
hi @carina1000 @timlinux 
could you give feedback of my comment?

**Comment by timlinux** [comment]
> are the colours based on class or taxon? Because it will be a big list if it is based on taxon.

No just two colours as @carina1000 provided

> What is taxon stand for on the diagram? Is it biodiversity records? Because 1 site can have 1 taxon but that 1 taxon can has multiple records (occurrences). Is single taxon is single records or really single taxon regardless the number of records?

This is for cases where the search / filter resolves to only a single taxon. We want to use it to produce a dot distribution map and therefore the circles should be of constant size.


> I see the cartography:

> If the clusters are not single, we give blue colors and sizing it depend on the number. Could you provide the calculation for this?

In my last / final image, the size should be calculated as:

(current_count / max_count) * max_size

So that a circle can never exceed the max_size

> The single taxon is based on the colors, how about the single site marker? Because on default map (without filter and search), we are showing site instead records. And 1 site can has multiple records (although these records has same taxon, but now we can check list of taxon in side panel when this site clicked with it's occurences)
> Maybe here is how clusters done

Right so single taxon is just a different colour but only if the whole search / filter result is one for a single taxon. If the filter / search resolves to > 1 taxon the circle size should be variable up to max_size and the colour fixed at the first colour (in our case #dbaf00)

> When no search and filters, show site clusters. 1 cluster can has multiple records. When single site, can has multiple records.
> When search or filter, show records cluster.

Hopefully mu comments above clarified things.
