### ISSUE TITLE
Update SASS Record - Assessor

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1550]
I cannot update the Assessor when I edit the form. I need to change Patsy Scherman to Mandy Uys, and it is not possible.  It seems to change but then does not save the change.   

Is this because she is not yet registered on FBIS?  IF so, how do we deal with this?
@dimasciput @timlinux  

![Screenshot_2019-08-15 FBIS SASS](https://user-images.githubusercontent.com/45286876/63096357-06a07e80-bf6e-11e9-8555-28816d780cac.png)

**Comment by helendallas** [comment]
I just checked and Mandy Uys is registered on the system via the Rivers legacy DB

**Comment by dimasciput** [comment]
@helendallas this is actually has been resolved on the testing

**Comment by helendallas** [comment]
@dimasciput 

But on the testing site I change the assessor name from Patsy Scherman to Mandy Uys, then click submit. but when the form reopens it still say Patsy Scherman.

http://testing.healthyrivers.kartoza.com/sass/update/11400/

**Comment by dimasciput** [comment]
@helendallas I can update it fine, did you just write the name or waiting for the list to appear? 
![image](https://user-images.githubusercontent.com/1979569/63156506-02906180-c03f-11e9-8d29-4f5cccbd02db.png)

Maybe I need to make sure the user has to choose from the list. Ok, I will update it.

**Comment by helendallas** [comment]
ah, I wrote the name. I will test again and use the list.  Just tested it, working now, thanks!
