### ISSUE TITLE
Can't delete SASS record on testing site

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1580]
I tried to delete a SASS record that I created as a test on the testing site for site A2CROC-HARTB, record = 05-12-2017:
![Screenshot 2019-08-26 at 14 44 41](https://user-images.githubusercontent.com/43198125/63701377-bef6de00-c81c-11e9-83c8-34813f6e3e34.png)

But this page pops up:
![Screenshot 2019-08-26 at 14 44 23](https://user-images.githubusercontent.com/43198125/63701413-cc13cd00-c81c-11e9-89c6-173f128a24a8.png)

@dimasciput

**Comment by dimasciput** [comment]
Fixed by https://github.com/kartoza/django-bims/pull/1582
