### ISSUE TITLE
Data Sources: Captions needed for 'FBIS' and 'GBIF' data sources

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1585]
@dimasciput @timlinux 

Would be good to provide an explanation of what is meant by 'FBIS' and 'GBIF' in the Data Sources section. Please include the following definitions: 

**FBIS:** Data not available via GBIF that have been sourced and collated from reputable databases, peer-reviewed scientific articles, published reports, theses and other unpublished data sources. 

**GBIF:** Freshwater species occurrence data available for South Africa that are currently available via the Global Biodiversity Information Facility (GBIF). GBIF includes periodically-updated data from the South African Institute for Aquatic Biodiversity (SAIAB), as well as 'Research Grade' iNaturalist data (i.e. records from non-captive individuals, with a picture, locality and date, and with two or more IDs in agreement at species level).

@toniolsen @helendallas please add to this if need be?

<img width="517" alt="Screenshot 2019-08-28 at 08 48 33" src="https://user-images.githubusercontent.com/44292029/63833847-4014b900-c974-11e9-9686-ec73eaf87611.png">

**Comment by dimasciput** [comment]
Added
