### ISSUE TITLE
User profile style inconsistent with site

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#159]
![screen shot 2018-07-24 at 09 33 16](https://user-images.githubusercontent.com/178003/43123547-d564cdd2-8f24-11e8-87ed-df83b5bd312f.png)

Different fonts and colours make it look like an odd duck compared to the rest of the site.

Please consult with @carina1000 as to how it should look and then make it consistent.

**Comment by dimasciput** [comment]
Hi @timlinux , currently we redirected the profile page to the geonode profile page.

**Comment by dimasciput** [comment]
this is fixed
