### ISSUE TITLE
Filter History 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1590]
@dimasciput  The headings for this panel should be 'Category and 'Selection. Also, the category labels should be the same as those in the list of filters: eg 'Validated' on the left should say 'Validation Status', because that is what it is called in the filter list...

<img width="412" alt="Screenshot 2019-08-28 at 12 45 40" src="https://user-images.githubusercontent.com/44292029/63920653-9f8cca80-ca41-11e9-8788-d8d9238d0c16.png">

@toniolsen @helendallas @timlinux

**Comment by toniolsen** [comment]
@dimasciput 
![Screenshot 2019-09-02 at 12 52 06](https://user-images.githubusercontent.com/43198125/64157401-8fecf780-ce2e-11e9-9574-327d8afd6043.png)
@jeremyshelton
