### ISSUE TITLE
Big picture Ticket 7: Import national FRC fish data (aim for end of October)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1598]
@dimasciput @timlinux 

We will have the FRC national fish data set ready for import into the FBIS by the first week of October. This will be third big chunk of fish data, in addition to the FRC CFE fish data and national GBIF fish data that are already in the system. We will provide these data in exactly the same format as was done for the FRC CFE fish data, and the master list should stay the same. 

@toniolsen @helendallas

**Comment by timlinux** [comment]
Can you give us an update on the status of this @jeremyshelton ?

**Comment by jeremyshelton** [comment]
@timlinux yes, we will have this ready by the end of the month 👍
Our 'fish data team' are meeting early next week to make sure we meet this deadline. 
@dimasciput

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput We have just had a fish data meeting and here is the plan from our side:

1. Spreadsheet with all out consolidated SA fish data for all native species will be ready and sent to you by the end of October.

2. Data for the non-native species is more than we anticipated and will only be ready by mid January, so we can update the spreadsheet then. 

@helendallas

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
The SA fish data set and accompanying SA fish master list are now ready for ingestion:Dropbox link: https://www.dropbox.com/sh/hbnvth1i7bi7v34/AABEgNwjOM0_OHovJyJGPLkja?dl=0
Data on non-native species outside the CFE are not included, but will be ready for FBIS v3 in the new year. Let me know if any adjustments are needed once you've had a look at the sheets.
@helendallas @Aneri16

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
A new version of the national fish data with the columns Dimas requested is now ready for you on dropbox: https://www.dropbox.com/sh/5m9m46oimswkle5/AACbN4MBQnZ_JaK30cKEk2mPa?dl=0
@Aneri16 @helendallas 
<img width="363" alt="Screenshot 2019-11-25 at 10 39 51" src="https://user-images.githubusercontent.com/44292029/69525074-0140d000-0f70-11ea-8ea8-a57905d84b71.png">

**Comment by helendallas** [comment]
@jeremyshelton 
Please check that this has imported correctly then close the ticket.

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 

Yes, the import is complete, but there are still issues associated with querying the fish data like the data sources (ticket #1872 and #1868 ) and csv (ticket #1869 and #1888), so I think we should not close this yet....
