### ISSUE TITLE
Upload document page is buggy

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1600]
@dimasciput 

I am trying to upload the PDFs onto the live site, but I keep getting this error message and I am unable to fill in those mandatory fields? 
![Screenshot 2019-09-05 at 12 30 04](https://user-images.githubusercontent.com/43198125/64340061-2fe88380-cfdd-11e9-9256-ab839ad419e1.png)

Let me know what I should do?

@timlinux

**Comment by toniolsen** [comment]
But I see if I don't complete the upload until "step 3" it still uploads.
@dimasciput

**Comment by dimasciput** [comment]
fixed it
