### ISSUE TITLE
Ingest CFE Fish data with document upload links

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1601]
Hi @dimasciput 

Here is the CFE fish data to reingest (again). I have added the links for the PDFs for the records as per our discussion today:
[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3579933/CFR.Fish.Data_excl_SAIAB.xlsx)

I am just not sure what to do with some of the records that come from a database i.e. CapeNature Database, 2015.
Is there a place where I can add a database and then link to the records in the CFE fish data? Let me know.

I am going to start doing the same document uploads for the National fish data that we plan on ingesting at the end of October.

@timlinux @jeremyshelton @helendallas

**Comment by jeremyshelton** [comment]
@toniolsen is the issue with the databases like CapeNature that we have neither a pdf nor doing nor url to link too? In such cases should we not just provide the database details 'CapeNature State of Biodiversity (SOB) database' and a link to their web page?

**Comment by toniolsen** [comment]
@jeremyshelton Okay, good idea. Will do so.

**Comment by toniolsen** [comment]
@dimasciput 
This is the final version of the CFE fish data to ingest:
[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3583382/CFR.Fish.Data_excl_SAIAB.xlsx)

All other fish records, not in this spreadsheet, should get the "GBIF" reference.

**Comment by dimasciput** [comment]
Hi @toniolsen , can you update the xls : 
- create a new column for the document link, don't put it on the DOI
- if collection have a document link, please set the reference category to Published Report

**Comment by toniolsen** [comment]
Hi @dimasciput 
Please see the updated xls. I have put the links in the "Document Upload Link" column:

[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3589903/CFR.Fish.Data_excl_SAIAB.xlsx)


It's not only published reports that have an uploaded PDF. I have uploaded PDFs for theses and some peer reviewed articles that didn't have a DOI, and also added a URL for some databases that we included. 
@jeremyshelton

**Comment by dimasciput** [comment]
Hi @toniolsen, our application couldn’t do that in the moment. So only published report can have document, if we want to accommodate your request we will have to change a lot of things. I don’t think we should do that, it’s confusing too.

**Comment by dimasciput** [comment]
@toniolsen , here's the csv file : 
[CFR.Fish.zip](https://github.com/kartoza/django-bims/files/3600047/CFR.Fish.zip)

**Comment by toniolsen** [comment]
@dimasciput, thanks!
I downloaded the file, but there is no formula in the UID column either? 
Perhaps you could paste the formula here and I can just drag it down into the spreadsheet?

**Comment by dimasciput** [comment]
@toniolsen yes there is no formula, because we don't use a formula, what I meant was copying uuid to your file, I can't get the collections from uuid if they keep changing.

**Comment by toniolsen** [comment]
@dimasciput, okay I have copied the UIDs to this CFE spreadsheet:

[CFR Fish Data_excl_SAIAB.xlsx](https://github.com/kartoza/django-bims/files/3625355/CFR.Fish.Data_excl_SAIAB.xlsx)

Thanks!
