### ISSUE TITLE
Rivers Database - additional tables and data for importing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1610]
The following tables and data still need to be imported from the Rivers Database: All data are at the level of Sampling Date (SIteVisit) and not Site.

# Site Visit Level Changes

CanopyCover - Open, Closed, Partially Open

Chem - ChemCode, ChemDescription. This is linked to 
ChemUnit and to 
SiteVistiChem

Embeddeddness - 0-25, 26-50, 51-75, 76-100

StreamDimension - only import Water Surface Width (m). This is linked to
StreamDimensionCategory 

WaterLevel - Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood

WaterTurbidity - Clear, Discoloured, Opaque, Silty

# Site Changes

Then
ChannelType - Bedrock, Mixed bedrock and alluvial - dominant type(s), Alluvial with dominant type(s) - this is linked to 
ChannelTypeDetail - Boulder, Cobble, Gravel, Sand

These are currently at the Sampling Date (SiteVisit) level - but needs be be changed to the Site Level

Link to ticket #1479

**Comment by timlinux** [comment]
These are at site visit level and not the site

**Comment by dimasciput** [comment]
Only Chem related tables have been imported.

We still need to import these tables :
```
CanopyCover - Open, Closed, Partially Open

Embeddeddness - 0-25, 26-50, 51-75, 76-100

StreamDimension - only import Water Surface Width (m). This is linked to
StreamDimensionCategory

WaterLevel - Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood

WaterTurbidity - Clear, Discoloured, Opaque, Silty
```

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/67459324-7e6fe100-f662-11e9-99cc-8e85fbee966d.png)

Water level, water turbidity, canopy cover, and channel type are already in SiteVisit.

**Comment by dimasciput** [comment]
@helendallas , I couldn't find a link between site visit and stream dimension
![image](https://user-images.githubusercontent.com/1979569/67461456-985ff280-f667-11e9-98e6-a144aaf8206f.png)

![image](https://user-images.githubusercontent.com/1979569/67461528-c5aca080-f667-11e9-928f-f2cb3ebdc461.png)

**Comment by helendallas** [comment]
@dimasciput 
![image](https://user-images.githubusercontent.com/45286876/68862947-080d4e80-06f7-11ea-971c-95371a933b0d.png)

StreamDimension - only import Water Surface Width (m). This is linked to
StreamDimensionCategory

**Comment by helendallas** [comment]
It would also be good to see this data somewhere on the SASS Record:  Is it still possible to add this data?
At the moment having the Site Code, Date, Owner, Accredited at time of sampling, Site Image - are all squashed to the right side of the Biotopes sampled. It would be better to have it all above. Then additional info as per this ticket, then biotopes, then the SASS taxon capture form as it is.

Maybe the SASS Record and Add SASS Data needs a slight redesign to have it more aligned with the Fish and Invertebrate Data form - more spacious, with map,
@jeremyshelton 
Can we work on this together please. 
@dimasciput Is this an option?

![Screenshot_2019-11-14 FBIS SASS](https://user-images.githubusercontent.com/45286876/68863270-b2857180-06f7-11ea-8480-0c49c7e52040.png)

**Comment by timlinux** [comment]
Step 1: Add the map, lat, lon, date and owner in same layout as fish form

Step 2: Add new widgets for:

1. **CanopyCover** :  Open, Closed, Partially Open
1. **Water surface width** : StreamDimension - only import Water Surface Width (m). This is linked to
StreamDimensionCategory
1. **Embeddeddness** - 0-25, 26-50, 51-75, 76-100
1. **WaterLevel** - Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood
1. **WaterTurbidity** - Clear, Discoloured, Opaque, Silty

@jeremyshelton to confirm if these should be added on fish and invert (and algae when it comes) forms

**Comment by timlinux** [comment]
Also make the button rounding the same

![image](https://user-images.githubusercontent.com/178003/69135303-d575a400-0ab0-11ea-8f32-89fc1004de88.png)

![image](https://user-images.githubusercontent.com/178003/69135338-e0c8cf80-0ab0-11ea-9436-797a8d772644.png)

**Comment by timlinux** [comment]
We will wait for feedback from FRC before proceeding

**Comment by helendallas** [comment]
@dimasciput @timlinux 

On reflection lets keep things simple. 

For all data capture (algae, invertebrates, SASS and fish) we had envisaged capturing biodiversity data first, then prompting the user to **Add abiotic data**.  They would then go to the **Abiotic Data Form**, where they would have five **Categorical variables** populated with a dropdown list; and could then also add data from a list of **continuous abiotic variables**. If they had no abiotic data, they would just move straight on to adding the **Source reference for records**.

We envisaged these data being stored in the same way as Rivers DB and Biobase data is, and then served in abiotic graphs (DO, Cond, pH and Temp) and in the csv file.

**Categorical  variables populated with a dropdown list | Dropdown list**

**Water surface width** : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
**Water level** : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood
**Water turbidity** :  Clear, Discoloured, Opaque, Silty
**Canopy cover** :  Open, Closed, Partially Open
**Embeddeddness** :  0-25, 26-50, 51-75, 76-100


**Continuous variables populated with dropdown/predicted text**? Sorted alphabetically | Unit
Aluminium | mg/l
Ammonia nitrogen | mg/l
Ammonium nitrogen | mg/l
Bicarbonate | mg/l
Biological Oxygen Demand | mg/l
Calcium | mg/l
Carbonate | mg/l
Chemical Oxygen Demand | mg/l
Chloride | mg/l
Chlorophyll a | mg/l
Conductivity | mS/m
Depth | m
Dissolved inorganic nitrogen | mg/l
Dissolved organic nitrogen | mg/l
Dissolved oxygen | mg/l
Dissolved Oxygen: % saturation | %
Fluoride | mg/l
Iron | mg/l
Kjeldahl nitrogen | mg/l
Lead | mg/l
Magnesium | mg/l
Near bed velocity | m/s
Nitrate nitrogen | mg/l
Nitrite nitrogen | mg/l
Particulate organic matter | mg/l
pH |  
Potassium | mg/l
Silica | mg/l
Sodium | mg/l
Soluble reactive phosphate (=   PO4-P) | mg/l
Submerged macrophytes | %
Sulphate | mg/l
Temperature | deg C
Total alkalinity | meq/l
Total dissolved solids | mg/l
Total inorganic carbon | mg/l
Total nitrogen | mg/l
Total organic carbon | mg/l
Total organics in TSS | mg/l
Total phosphorus | mg/l
Total suspended solids | mg/l
Turbidity | NTU
Undercut bank | %
Woody debris | %

Excel data file of the above attached. 
[Abiotic Data Variables Master.xlsx](https://github.com/kartoza/django-bims/files/3863694/Abiotic.Data.Variables.Master.xlsx)

@dimasciput 
Please decide if this should form part of 2.6 or be held over for the next release.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton for the new abiotic form, let's held over for next release. For version 2.6, I will match the SASS form layout to be similar to other forms. What do you think?

**Comment by helendallas** [comment]
@dimasciput 
That is fine, but please can we make the next interim release soon in 2020, as we would like to be able to capture abiotic data with existing SASS data that is being captured.

**Comment by helendallas** [comment]
I am happy, thanks @dimasciput

**Comment by helendallas** [comment]
@dimasciput 
Abiotic data form - I cant see this anymore. I am sure you did it before release V2.6. 

Additional abiotic data still needs to be pulled into SASS record, so that it is visible when ones clicks on the SASS record. Layout to be as per the form designed last year.....really cant find it.

Please advice

**Comment by helendallas** [comment]
@dimasciput please update me on this ticket

**Comment by dimasciput** [comment]
we have abiotic data form, it just we need to add new collection/sass record before go to abiotic form

**Comment by helendallas** [comment]
@dimasciput 
But what happened to the 
Categorical variables populated with a dropdown list | Dropdown list

Water surface width : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
Water level : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood
Water turbidity : Clear, Discoloured, Opaque, Silty
Canopy cover : Open, Closed, Partially Open
Embeddeddness : 0-25, 26-50, 51-75, 76-100

All we have a re the Continuous variables 

![image](https://user-images.githubusercontent.com/45286876/75015663-d5ab8400-5491-11ea-921b-945269a39759.png)

see ticket 
Add Abiotic data form #1819

**Comment by dimasciput** [comment]
@helendallas yes haven't added that, because I was thinking that was for version 3. Can we please close this ticket then, and continue the discussion to other ticket instead.

**Comment by helendallas** [comment]
@dimasciput Okay, will do.  To confirm -  has the data in the Categorical variables above been imported from Rivers Database -  but are currently not show yet?  If this is the case then I will close the ticket as the data will be visible one Add Abiotic data form #1819 is done - Do I understand this correctly?

**Comment by dimasciput** [comment]
@helendallas yes, for example: http://freshwaterbiodiversity.org/admin/sass/sitevisit/137/change/?_changelist_filters=p%3D111, 
![image](https://user-images.githubusercontent.com/1979569/75017268-3c936200-54bf-11ea-96e8-986abeddb55c.png)

**Comment by dimasciput** [comment]
closing this ticket, the data has been imported but still not displayed. Continue to https://github.com/kartoza/django-bims/issues/1819
