### ISSUE TITLE
Add a category called ‘Multiple’ to Sampling Method.  

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1617]
@dimasciput @ann26 
We need a new Sampling Method category called 'Multiple' for the single and multi site dashboards. 

@toniolsen this will need to feature in the fish spreadsheet, correct? Will we do this when we ingest the new SA fish data?

<img width="720" alt="Screenshot 2019-09-13 at 13 32 48" src="https://user-images.githubusercontent.com/44292029/64859625-11ad0400-d62b-11e9-8e71-f31a75aca867.png">

**Comment by toniolsen** [comment]
@jeremyshelton Yes, the "multiple" category will only come in with the new SA fish data.

**Comment by dimasciput** [comment]
@jeremyshelton what does multiple means here?

**Comment by toniolsen** [comment]
@dimasciput, this just means that sometimes the collector doesn't specify which method they used and they list multiple methods in their study, e.g. "Fish were caught using seine nets, gill nets and electro-fishing". We want to be able to show when multiple methods have been used. 

However, we have only included a multiple category in the national fish data that will only be ingested at the end of October. So there is no data in the system at the moment that specifies "multiple" sampling methods.

**Comment by dimasciput** [comment]
Actually this will automatically be added to the chart if there is data with this category, so I don't think we need this ticket anymore.

**Comment by jeremyshelton** [comment]
OK Copy that 👍
