### ISSUE TITLE
Add four ‘Abiotic data’ graphs to single site dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1618]
@dimasciput @ann26 

Add four ‘Abiotic data’ graphs to single site (NOT multiple site) dashboards for all modules. They should Appear below the ‘Conservation status’ graph, and be in a different colour to the ‘occurrences’ graphs above (grey probably best). These four abiotic parameters are a subset of the larger number of abiotic parameters that will come in with the Biobase data. All parameters will be available by CSV download. 

<img width="762" alt="abiotic" src="https://user-images.githubusercontent.com/44292029/64952346-68f7e200-d880-11e9-8704-128f37eb7861.png">

@toniolsen @helendallas

**Comment by jeremyshelton** [comment]
@ann26 the abiotic graphs look great - thanks for a good job 👍
@dimasciput, a few issues I have picked up while testing

It seems that the conductivity (and temperature??) is not being displayed in the graphs, even though there are conductivity data in the spreadsheet? EG site A2JUKs-00016
http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=A2JUKs-00016&siteId=27706&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=



Site BRGROO-00040: this is an example of a site that was filtered as having abiotic data, but no abiotic data were distilled in the dashboard: http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=27686&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=["validated"]&sourceCollection=["fbis"]&abioticData=True&ecologicalCategory=

@helendallas

**Comment by dimasciput** [comment]
Hi @jeremyshelton,

> It seems that the conductivity (and temperature??) is not being displayed in the graphs, even though there are conductivity data in the spreadsheet? EG site A2JUKs-00016
http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=A2JUKs-00016&siteId=27706&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=

Should be fixed on testing, please try again. 

 > Site BRGROO-00040: this is an example of a site that was filtered as having abiotic data, but no abiotic data were distilled in the dashboard: http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=27686&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=["validated"]&sourceCollection=["fbis"]&abioticData=True&ecologicalCategory=

So this is actually a bug on the search, I have fixed it on testing, this site shouldn't appear on the results anymore.

**Comment by helendallas** [comment]
@dimasciput 
Is it possible to include these graphs on the SASS dashboard in a similar way as for the Invertebrates, Fish and algae?

This is especially important since 59516 physico-chemical records were in the original Rivers Database, which was SASS focused.

See attached spreadsheet:
[Uploading RIvers DB Extracted PhysicoChemical Data from Original.xlsx…]()

**Comment by dimasciput** [comment]
@helendallas yes they are already included on all the dashboard actually

**Comment by helendallas** [comment]
@dimasciput 
I cant see where...see below: 
![Screenshot_2019-11-07 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/68375153-fa802380-014e-11ea-8214-074bbf3490ea.png)

**Comment by helendallas** [comment]
@dimasciput 

Please can you remove the "header"above each abiotic graph - its not necessary.
@jeremyshelton do you agree?

![Screenshot_2019-11-14 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/68858418-aa283900-06ed-11ea-9319-74dd26edac45.png)

And Y axis require some attention with formatting. @jeremyshelton  - please cna you annotate for Dimas

**Comment by helendallas** [comment]
@dimasciput 

Also please remove (pH_Unit) on y axis, for all pH graphs.

It is not necessary, thanks

**Comment by dimasciput** [comment]
Chart has been updated

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - looks good to me 👍

Here is an example showing all graphs: http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=11784&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=&modules=21&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=

@helendallas you happy?
