### ISSUE TITLE
Big picture Ticket 8: Invertebrate and algae dashboards for (aim for end of October)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1620]
@ann26 @dimasciput 

Dashboards for invertebrates and algae will be identical to the fish dashboards, with one exception: algae dashboards (detailed single and multi-site) will have an additional graph called ‘Taxonomic division’ inserted above the ‘Origin’ graph. The Y-axis will show categories of taxonomic division, which will be uploaded with the algae data. 

Otherwise, the **Taxon dashboards**, **Single site dashboards** (both overview and detailed) and **Multisite dashboards** (both overview and detailed) will be identical to the fish. 

**So let’s first get the fish dashboards perfect, and then roll that template out to invertebrates and algae.** 

Outstanding fish dashboard tickets to be addressed before we create invertebrate and algae dashboards:

#1618
#1617
#1616
#1615
#1614
#1613
#1593
#1589
#1510
#1416

@toniolsen @helendallas @timlinux

**Comment by helendallas** [comment]
@jeremyshelton Have the Outstanding fish dashboard tickets been addressed? - if yes, then lets close this ticket as the algal dashboard should have its own one in Epic: Version 4

**Comment by jeremyshelton** [comment]
@helendallas yes, these have all now been addressed, and I am closing the ticket. 
@dimasciput

**Comment by jeremyshelton** [comment]
Algae dashboards replaced by #1857 in Project FVISv4
