### ISSUE TITLE
PDF uploads for theses and other reference category sources without a DOI

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1623]
Hi @dimasciput, 

Did we resolve the issue of being able to upload PDFs for theses (and other reference categories without a DOI), and not just published reports?
I think you wanted to run this by @timlinux  ? 

Let me know, thanks!

@jeremyshelton

**Comment by dimasciput** [comment]
I will add ability to add document to other reference category, but this is only for backend side at this time (to solve https://github.com/kartoza/django-bims/issues/1601), which means user can't upload document to other categories.

**Comment by timlinux** [comment]
Everything is ready - but we need to deploy the latest work to production and then upload the associated PDF's

**Comment by timlinux** [comment]
So we discussed this some more :-) 

We agreed it is better to add an option that allows the user to either upload the PDF or link to a PDF by URL - please modify this form to accommodate that:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/178003/67381789-645fd100-f584-11e9-833c-e44bce73df93.png">


Note we also checked the GeoNode docs management system and it does support URL based.

**Comment by timlinux** [comment]
Above should only be used when the doc cannot be found in a DOI database.

**Comment by jeremyshelton** [comment]
Agreed @timlinux 

@helendallas we need to make sure that we only upload PDFs not accessible online. This has not need the case thus far, as some of the these we have uploaded are available online! We also need to watch out for copyright infringements. Let's chat when you're back.

**Comment by helendallas** [comment]
@jeremyshelton Please can we assign an FRCer to check all documents in FBIS live. Aneri or Melandri?

**Comment by jeremyshelton** [comment]
@helendallas done - FRC ticket #

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput 
Just to be clear, we have decided that the only PDFs that should be uploaded are those that do not exist online, for example consulting reports, some other unpublished reports that never made it online (and are often very old). Perhaps this should be explained to the user somewhere in the data upload forms, alongside the request in #1799 ? @helendallas ?

**Comment by helendallas** [comment]
@jeremyshelton 
I think this has been resolved. Please close ticket if you agree.

**Comment by jeremyshelton** [comment]
@helendallas agreed
