### ISSUE TITLE
Update SASS Record - Order of Taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1629]
@dimasciput 

Something has gone wrong with the Taxa order for the SASS editing form - from Coleoptera and Diptera; should be Coleopteran taxa then Dipteran taxa.  This is for historical SASS4 data, so perhaps that is the reason.

![Screenshot_2019-09-19 FBIS SASS(1)](https://user-images.githubusercontent.com/45286876/65244610-3dc4fb00-daeb-11e9-9476-1a96b610da53.png)

**Comment by dimasciput** [comment]
Fixed on testing http://testing.healthyrivers.kartoza.com/sass/update/10/
