### ISSUE TITLE
SASS Record - space for Source Reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1630]
Please increase the space for the Source Reference, and include Full Study Reference.

@toniolsen 
Please confirm what this should read, Author, date, title, report?

![Screenshot_2019-09-19 FBIS SASS(2)](https://user-images.githubusercontent.com/45286876/65247020-ea08e080-daef-11e9-982e-8a6d6d58e609.png)

**Comment by toniolsen** [comment]
Yes ,
**For published reports it should read:** author, year, title, report 
(e.g. Harding, W.R. and Hart, R.C., 2011. Use of stable isotope analysis to describe aquatic foodwebs in the Kruger National Park. Report prepared for the Water Research Commission. Report no.: KV256/10)

**For peer-reviewed papers:** author, year, title, journal, vol, issue, pages. But the DOI should be pasted here. 

**For theses:** author, date, title, degree, university
(e.g. Grundlingh, M.J., 1996. Aspects of the morphology of Chonopeltis thiele, 1900 (Crustacea: Branchiura) with special reference to the reproductive systems. PhD. University of Johannesburg)

**For database:** Name of database, year

**For unpublished data:** Name of collector, year, "unpublished data"

@dimasciput @helendallas

**Comment by helendallas** [comment]
@dimasciput 
Probably best to revisit this once the SASS Record view has been revised in line with ticket #1610

**Comment by helendallas** [comment]
@dimasciput Noted

**Comment by helendallas** [comment]
@dimasciput 
Metadata Table still problematic with respect to layout for some study references. See example below.
DOI and notes overlapping

![Screenshot_2020-01-31 FBIS Multiple Sites Dashboard - SASS](https://user-images.githubusercontent.com/45286876/73518229-6698bd80-4406-11ea-862f-fdbc2cccdae9.png)

**Comment by dimasciput** [comment]
Hi @helendallas , this is a different issue with the original ticket. Can you create a new ticket instead, so we can track it better?

**Comment by helendallas** [comment]
Closed via new ticket
