### ISSUE TITLE
Detailed dashboards not loading on live site

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1639]
@dimasciput 
Detailed dashboards not loading on live site for anything larger than a small number of records. EG for the below selection I could not get the detailed dashboard to load. In fact even a dashboard with just 21 records isn't loading for me...

<img width="1440" alt="Screenshot 2019-09-24 at 12 48 38" src="https://user-images.githubusercontent.com/44292029/65505879-8c4b0e80-deca-11e9-9fb9-2c370a6d3e96.png">

@toniolsen

**Comment by jeremyshelton** [comment]
@dimasciput is it possible to get the detailed multi-site dashboards working again soon? I am presenting FBIS at a conference today and would like to show that functionality...

**Comment by dimasciput** [comment]
@jeremyshelton can you provide me the link?

**Comment by jeremyshelton** [comment]
@dimasciput 
http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["1051"]&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&ecologicalCategory=

**Comment by dimasciput** [comment]
@jeremyshelton I'm on it

**Comment by dimasciput** [comment]
@jeremyshelton fixed it

**Comment by jeremyshelton** [comment]
@dimasciput Awesome. Working perfectly now. Thanks!
