### ISSUE TITLE
Chemical Records should be called Abiotic Data

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1652]
Please change the heading "Chemical Records" to "Abiotic Data":

![Screenshot 2019-09-27 at 13 07 32](https://user-images.githubusercontent.com/43198125/65768182-1e038780-e128-11e9-8bfa-1530b34d450b.png)
@ann26 @dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
Renamed
