### ISSUE TITLE
Create National and Provincial drawers for the CBA layers

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1653]
Please can we create  "National" and "Provincial" drawers for the CBA layers:
![Screenshot 2019-09-27 at 13 11 53](https://user-images.githubusercontent.com/43198125/65768477-f6f98580-e128-11e9-932a-f06aeaeea18c.png)

This would make it easier for the user to differentiate between the national and provincial layers.
Thanks!
@dimasciput @NyakudyaA @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA
Let's get these CBA layers packaged into separate drawers for the National and Provincial layers. Please also adjust labels to match those below and make sure the provincial layers are listed in alphabetical order, as per below...
<img width="320" alt="Screenshot 2019-10-21 at 10 23 24" src="https://user-images.githubusercontent.com/44292029/67188605-f503a900-f3ec-11e9-9bcb-c2cea7f4df39.png">

**Comment by jeremyshelton** [comment]
@dimasciput OK. But what about the ESAs (We have National and Provincial) and PAs (We have National only)?

**Comment by dimasciput** [comment]
@jeremyshelton but the screenshot you shared, there is only ESA inside national?

**Comment by dimasciput** [comment]
@jeremyshelton it will look like this : 
![image](https://user-images.githubusercontent.com/1979569/67373369-b109d300-f5a9-11e9-818f-80f6070cb927.png)

**Comment by jeremyshelton** [comment]
@dimasciput looks perfect 👌

**Comment by jeremyshelton** [comment]
@dimasciput Nearly there - These two drawers should fall within a single drawer called 'Critical Biodiversity Areas (CBA)' on the filter list. Sorry if I wasn't clear on that.

<img width="386" alt="Screenshot 2019-10-25 at 07 14 42" src="https://user-images.githubusercontent.com/44292029/67544810-38b12800-f6f7-11e9-9881-b557f57e2a44.png">

**Comment by dimasciput** [comment]
@jeremyshelton  It would be a little hack to do that, is it okay if it's like this for now? and also the design will not have uniformity with the others

**Comment by dimasciput** [comment]
Because I automatically create this drawer programmatically, if you want to show different behaviour for CBA layer, then I will increase the effort and I don't know if it's really worth doing.

**Comment by jeremyshelton** [comment]
@helendallas @timlinux thoughts on this?

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 
My feeling is to be consistent, and this is the only layer that falls outside the format. Can we make a note to discuss please.
