### ISSUE TITLE
I am unable to validate records because of a 'login' issue?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1654]
@dimasciput 

Log in screen comes up when I click ‘validate records’ , even though I am already logged in?

Because of this, I am unable to validate records :(

<img width="1032" alt="Screenshot 2019-09-27 at 14 12 02" src="https://user-images.githubusercontent.com/44292029/65768798-48f2d900-e132-11e9-856c-9451baaae328.png">

**Comment by jeremyshelton** [comment]
@dimasciput please remember to change my status to staff so that I can validate records - thanks

**Comment by dimasciput** [comment]
@jeremyshelton ok, I set you as superuser, so you can edit data in the admin page too. But you will get a lot of emails.

**Comment by jeremyshelton** [comment]
@dimasciput great. Thanks.
