### ISSUE TITLE
Meta data table - SASS dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1660]
The metadata table for the SASS dashboard is looking untidy - text does not fit nicely into each column:
![Screenshot 2019-09-30 at 10 10 59](https://user-images.githubusercontent.com/43198125/65865114-d456af00-e36a-11e9-83dc-31ce3ea6607f.png)

Could the the table be made bigger or the text smaller?

@dimasciput @ann26 @helendallas

**Comment by jeremyshelton** [comment]
@dimasciput @ann26 
How about we put the metadata table at the bottom of all dashboards and make it wider, using the entire width of the dashboard instead of half the width of the dashboard (as is currently the case)? That should allow more space for the text...?
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton that would be weird, because the two columns above won't have the same height, 

![image](https://user-images.githubusercontent.com/1979569/66019716-b629b400-e50e-11e9-9b54-b943d8e0380c.png)

**Comment by jeremyshelton** [comment]
@dimasciput I hear you, but I still think it would be fine to have it at the bottom, down below the graphs despite the difference in column height.
@helendallas thoughts?

**Comment by jeremyshelton** [comment]
@dimasciput 

Can you try (1) exclude the Notes column from this table, then (2) make the DOI/URL available as a hyperlink on the title? That should give each text column more space. 

If still too narrow, then @helendallas and I agree that it is fine to just put it below across both columns: 

<img width="320" alt="Screenshot 2019-10-10 at 06 57 22" src="https://user-images.githubusercontent.com/44292029/66540249-7b85d400-eb2b-11e9-8065-d08058cc5214.png">

@timlinux

**Comment by dimasciput** [comment]
@jeremyshelton what about unpublished data? they only have note : 
![image](https://user-images.githubusercontent.com/1979569/66547278-1224b600-eb69-11e9-8440-5645b187e5e2.png)

I will just put it on the bottom, and leave the table format as it is.

**Comment by jeremyshelton** [comment]
@dimasciput oh yes, good point. This looks good to me 👍

<img width="1375" alt="Screenshot 2019-10-10 at 09 35 24" src="https://user-images.githubusercontent.com/44292029/66548314-5308d480-eb41-11e9-89c0-2ff530fde502.png">

**Comment by helendallas** [comment]
@dimasciput 
Not done for SASS dashboards, single or multiple. Table still sitting on right hand side.
Also inconsistency in where the Metadata Table is in the single vs Multiple SASS dashboards. Lets be consistent and always have at the bottom, please.

 
![Screenshot_2019-11-14 FBIS Single Site Dashboard - SASS(2)](https://user-images.githubusercontent.com/45286876/68868373-19a72400-0700-11ea-9ba6-6491550794dc.png)

![Screenshot_2019-11-14 FBIS Multiple Sites Dashboard - SASS](https://user-images.githubusercontent.com/45286876/68868386-20359b80-0700-11ea-941f-f857b325b9c0.png)

**Comment by dimasciput** [comment]
Fixed on testing
