### ISSUE TITLE
Please invite Janette and Aneri to GitHub

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1663]
@timlinux @dimasciput 
From now on Janette and Aneri will be working on Github from the FRC side. 
Janette uploaded her first ticket, but is not yet able to add labels. 

Do you perhaps need to invite them to join kartoza/django-bims first?

Janette: https://github.com/Janette-Lumley
Aneri: https://github.com/Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton no need, this is a public repo so everybody can join

**Comment by jeremyshelton** [comment]
@dimasciput OK cool. They are unable to add labels to their tickets - any idea why that might be?
...that's why I thought maybe they had to be invited...

**Comment by dimasciput** [comment]
Oh yea they need to be collaborator, hmm I thought everybody can add labels too. I just added them to collaborator.

**Comment by jeremyshelton** [comment]
Great - thanks :)
