### ISSUE TITLE
Please add a TAXONOMIC RANK filter below the MODULE filter

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1666]
@timlinux @dimasciput 

Please add a TAXONOMIC RANK filter below the MODULE filter. 
<img width="490" alt="Screenshot 2019-10-02 at 16 09 08" src="https://user-images.githubusercontent.com/44292029/66051305-fe58ce80-e52e-11e9-814b-2021d63de62c.png">
By selecting their desired taxonomic rank, the user can then filter by a broad rank like Order or Family and the search will return all occurrence data for all taxa that fall within this Order or Family.
For example, if the user filtered by Order and chose ‘Ephemeroptera’, the search would return occurrence data for all 291 of the different taxa that fall within this Order, and NOT just taxa called ‘Ephemeroptera’ which is what happens at the moment. The below screenshot is from the invertebrate master list and shows the first 50-odd of the 291 taxa within Ephemeroptera that would be served. 
<img width="916" alt="Screenshot 2019-10-02 at 16 04 58" src="https://user-images.githubusercontent.com/44292029/66051023-82f71d00-e52e-11e9-9255-11e8c6d7bef8.png">
Similarly, the user could do the same for the Baetidae, by selecting the taxonomic rank of Family. They would then receive available occurrence data for all 156 taxa that fall within that family. 

@helendallas

**Comment by dimasciput** [comment]
I don't think we need this filter, it will to confuse users, maybe we just need to update the search logic to handle this case. 

@timlinux @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput OK, but then how would the user distinguish between a taxon that is actually called 'Baetidae' vs a query for data for all the taxa falling within the Family Baetidae?

@helendallas thoughts?

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/66106364-d7120800-e5e7-11e9-9f1b-9342446789c8.png)

We could show the taxon rank in the autocomplete dropdown.

**Comment by jeremyshelton** [comment]
@dimasciput please elaborate: where exactly would the taxon rank show in the dropdown? Below the taxon name?

**Comment by dimasciput** [comment]
@jeremyshelton yes, so for example `Baetidae` will have `Family` under the taxon name.

**Comment by jeremyshelton** [comment]
@dimasciput that sounds like a good idea. Go for it.

**Comment by timlinux** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/178003/67384066-5ca22b80-f588-11e9-84aa-78311c32d71d.png">

As discussed today, please change the label from 'Record name' to 'Taxonomic Rank: Taxon'

**Comment by dimasciput** [comment]
Updated 
![image](https://user-images.githubusercontent.com/1979569/67448971-d860ae80-f642-11e9-810f-b8eccb14dcd5.png)

**Comment by jeremyshelton** [comment]
@dimasciput Looks good - however testing site still showing 'Record name'? Are you still busy updating this?

<img width="968" alt="Screenshot 2019-10-25 at 07 16 46" src="https://user-images.githubusercontent.com/44292029/67544912-8d54a300-f6f7-11e9-81a3-9c016466fc0e.png">

**Comment by dimasciput** [comment]
@jeremyshelton yes can you try again?

**Comment by jeremyshelton** [comment]
@dimasciput ok all good now 👍
