### ISSUE TITLE
Adding Site or Data - Owner not registered on FBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1670]
@dimasciput @timlinux @Aneri16 

Aneri is needing to create a Site and capture SASS data from reports etc. The Owner of the Site and SASS data is not registered on FBIS.

What is the best way to deal with this. It is most likely an issue during the data capture phase and not necessarily one that will continue into the long term, since new users will register on FBIS and then upload their data.

The way the system is set up at the moment is you can only select a name from the existing list.

**Comment by timlinux** [comment]
@helendallas normally she (or someone with staff rights if she does not have it) would go to the admin backend, create a user there to match the site owner then reload the site form and she should be able to pick it from there.

**Comment by helendallas** [comment]
Thanks @timlinux 

We did that, then had to create an email, but the user name disappeared. and was not in the dropdown.  Is it becasue we used an email that is already in the system?

**Comment by timlinux** [comment]
It could be - could you pop me an email with the details of the user you are trying to create?

**Comment by helendallas** [comment]
Hey Tim

 

Ntswaki Ditlhale is the name of the SASS data owner, and the site owner is Anso Le Roux

We created the user Ntswaki Ditlhale, and used Aneri’s email : aneri@frcsa.org.za

**Comment by dimasciput** [comment]
@helendallas 

This is because you didn't add first name and last name for that user, I just added them, should be fine now. 
In the normal use case, first name and last name are mandatory fields.

**Comment by helendallas** [comment]
Thanks @dimasciput 
@Aneri16 
Is it necessary to include the email? And if so can we just make it one of ours?

**Comment by dimasciput** [comment]
@helendallas It is required to login and get notifications.

**Comment by helendallas** [comment]
@dimasciput @timlinux @Aneri16 

So to confirm, if we need to create a user name to assign data to an "Owner", all we need to complete on the Administration/Users Pages is:

- Add username
- Add Name and Surname

**What about permissions?** 
Do I need to click Active and assign a Group? And if so what group?  
Please also explain what the different Group are in the Permissions.  

They do not require a login as they dont need notifications.

![Screenshot_2019-10-07 Change user Django site admin](https://user-images.githubusercontent.com/45286876/66288495-b85a8c80-e8d9-11e9-9e05-e66fb05b35e2.png)

**Comment by helendallas** [comment]
@dimasciput @timlinux 

Please see screenshot below. It seems I have to add all this data to add a Site Owner or Data Owner. 
Please advise on the way forward as we cannot continue capturing data for owners not registered on the system.

![Screenshot_2019-10-07 Add user Django site admin](https://user-images.githubusercontent.com/45286876/66296424-d8944680-e8ed-11e9-86db-2e7bdedeb54b.png)

Ideally we need a simple way to add and manage Owners of data captured by someone not registered on FBIS. that doesnt require email, password.  Is this possible?

**Comment by dimasciput** [comment]
@helendallas 

> Ideally we need a simple way to add and manage Owners of data captured by someone not registered on FBIS. that doesnt require email, password. Is this possible? 

No it's not possible, you can add a dummy password and email for that, it doesn't matter if they are the same as another account. You only need to enter a unique username.

> What about permissions?
Do I need to click Active and assign a Group? And if so what group?
Please also explain what the different Group are in the Permissions.

Just click active, no need to assign a group.

**Comment by dimasciput** [comment]
@helendallas 

Also username cannot contain a space, change the space to underscore.

**Comment by helendallas** [comment]
@dimasciput 
Thanks that helps a lot

**Comment by timlinux** [comment]
@dimasciput I think we should add an administrators guide either to the existing manual or as a new doc and note this kind of stuff there as it arises so that we capture all the knowledge that otherwise just stays in our heads after the ticket is closed. This is especially relevant if we start onboarding new projects like Rwanda.

**Comment by helendallas** [comment]
@timlinux @dimasciput 
That would be really useful. I would make it a separate Administrators Guide. In the end it will save you all time as then we will have a better sense of what we can do ourselves, versus rely on you to do for us.....

**Comment by helendallas** [comment]
@timlinux @dimasciput 

I am tagging this with an "Admin Manual"  label - so that the process discussed can be captured in the Admin Manual
