### ISSUE TITLE
Visualising the spatial filters? 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1698]
@dimasciput @timlinux 
When a user selects a spatial filter for querying the biodiversity data, how easy would it be to show the filtered area on the map? 

For example, if they filtered by a 'National Protected Areas', to then see that selection on the map in the same way that the 'Layer Selector' currently operates? 

Guess it just seems intuitive that the user should be able to see the areas that they are filtering....

What do you guys think?

**Comment by dimasciput** [comment]
@jeremyshelton it's a good idea but bit complicated since the spatial filter doesn't have any information about the layer itself. Let's talk about it on Wednesday.

**Comment by jeremyshelton** [comment]
@dimasciput OK cool. That makes sense. Have noted to chat about this on Wednesday....

**Comment by jeremyshelton** [comment]
@dimasciput 
Great that you have implemented this. 
Thanks!

**Comment by timlinux** [comment]
@dimasciput and @NyakudyaA can you guys get together and see why we dont get boundaries for all layers? Please collate a complete list of the layers here in the ticket and place a check box next to each as you confirm it is working.

**Comment by NyakudyaA** [comment]
| Filter        | Status    | 
| ------------- |:-------------:| 
|Geomorphological zone      | Not working | 
| Freshwater ecoregion of the world    | working      |   
| Province | Working   |  
| Management Area| Working   | 
| Catchment | Working   | 
| Ecoregion level 1 | Fixed - now works   | 
| CBA national (all) | Working   | 
| CBA Provincial (working but missing WC) | Working   | 
| NFEPA | Working   | 

@dimasciput there are two issues wit the Geomorphological zone 
* no layer name is passed to the request
![layer-not-rendering](https://user-images.githubusercontent.com/2510900/75265931-4e943e00-57fa-11ea-96b8-8c022c1ee837.png)

* Wrong cql_filter values being passed to the request

#1914

**Comment by NyakudyaA** [comment]
@dimasciput any comment here. Did you update this

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA red outlines still not showing for Quinary and Quarternary catchments, SA Ecoregion and Geomorphological Zone

**Comment by jeremyshelton** [comment]
Closing this ticked because it is covered in #2052
