### ISSUE TITLE
Ecoregion filter bug?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1699]
@dimasciput @timlinux @NyakudyaA looks like a few errors have crept into the **SA Ecoregion** and **Freshwater Ecoregion of the World** filter sets?  
<img width="648" alt="Screenshot 2019-10-21 at 13 10 15" src="https://user-images.githubusercontent.com/44292029/67200744-e923e100-f404-11e9-98e0-3b93b88af5fb.png">

**Comment by NyakudyaA** [comment]
@gubuntu on the missing ecoregions I think it might be because we actually have no data in those sites so they won't appear in the filters.

@dimasciput those numbers should not be there
![feow](https://user-images.githubusercontent.com/2510900/67202980-33f42780-f40a-11e9-969c-3e6b33456cab.png)

**Comment by dimasciput** [comment]
@jeremyshelton I updated the freshwater ecoregion filter : 

![image](https://user-images.githubusercontent.com/1979569/67256704-a9b3ce00-f4b2-11e9-9886-27d666d8f520.png)

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA and @dimasciput 👍

**Comment by dimasciput** [comment]
need to re-ingest in live once live site is updated

**Comment by jeremyshelton** [comment]
OK, cool. Lets keep this issue open until then.
