### ISSUE TITLE
'Change password' bug?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1700]
@dimasciput @timlinux 

Some users unable to change password (error message), and thus unable to log in to FBIS:

![image001](https://user-images.githubusercontent.com/44292029/67204290-81be5f00-f40d-11e9-88c4-b3fa60f44570.png)

We need to specify password requirements - i.e. at least 6 characters, one upper case, one lower case, and a number, no other special characters.....or remove thses password restrictions??

**Comment by dimasciput** [comment]
Fixed in testing by displaying password requirement in the form.

**Comment by jeremyshelton** [comment]
@dimasciput  👍
