### ISSUE TITLE
Tidy up GFI responses

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1731]
@NyakudyaA  Can you clean up the get feature infor responses so that they are 'humanistic':

<img width="455" alt="image" src="https://user-images.githubusercontent.com/178003/67847106-32a5b780-fafa-11e9-8a1e-931a225554b4.png">

**Comment by NyakudyaA** [comment]
@timlinux I think it's a case of ` WYSIWYG`. We took a decision not to edit the raw data. Maybe what we can do is choose what fields are meaning and map some of them in views so that we can serve the views

**Comment by NyakudyaA** [comment]
@timlinux For layers like NFEPA Wetlands they have attributes that are not populated but the metadata explains what each attribute means. Should I not show them in the getfeature info?

**Comment by NyakudyaA** [comment]
@dimasciput Is it easier for you to convert the GF responses for column names to title case because natively PostgreSQL has all the columns in lower case and here is an example of a tidy GF response
![name-gf-response](https://user-images.githubusercontent.com/2510900/75168982-6ef7c600-5730-11ea-9b48-3565b2fa48cd.png)

**Comment by jeremyshelton** [comment]
@jeremyshelton to check 'get feature info' fields reported for each layer and tell @NyakudyaA which to retain

**Comment by jeremyshelton** [comment]
@helendallas I have started looking through the different layers and noting which rows I think we should show the user in the 'get feature info' pop up. However, to complete this task I think we might need go through some of these together...

**Comment by NyakudyaA** [comment]
@jeremyshelton any update on this?

**Comment by jeremyshelton** [comment]
@helendallas would be good to get your thoughts on this? I think we need to give the users as little confusing information as possible. Just the name of the polygon (e.g. 'Western Cape' for Province, 'Boland Mountains' for surface water source areas etc?). 

However, for some layers the 'name' is still unclear and not useful. I think we need to go through these case-by-case. 

Unfortunately all layers and filters on the testing site are currently not available.

**Comment by helendallas** [comment]
@jeremyshelton Happy to do this via zoom today once the layers and filters are available on the testing site

**Comment by jeremyshelton** [comment]
@helendallas OK sounds good.

@dimasciput has restored the layers and filters on testing. 

However, there are still lots of issues with layers: NBA, CBA, SA Ecoregion, Management area, NFEPAs and others...I am wondering if we should wait for these to be fixed first?

@NyakudyaA and @dimasciput  will it help if I create a single ticket that links to all ticketed issues with layers and filters?

**Comment by NyakudyaA** [comment]
This has been completed and mentioned in https://github.com/kartoza/django-bims/issues/2052
