### ISSUE TITLE
SASS Dashboards - Ecological categories not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1737]
In testing site , for some reason the Ecological Categories are not working, so the colour coding etc is incorrect and the graph is not labelled

@dimasciput @ann26 
![Screenshot_2019-11-04 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/68106346-fd2e0f00-fee9-11e9-9a61-bd2162fece2a.png)

**Comment by dimasciput** [comment]
Fixed on testing
