### ISSUE TITLE
New SASS data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1738]
@dimasciput 
On the testing site, after I create a dummie Site and add SASS data, none of the Site information is completed on the SASS dashboard. Is this just because it is the testing site? not the live site? Or is this a bug?

![Screenshot_2019-11-04 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/68107886-db835680-feee-11e9-9cef-3d4502d62a28.png)

**Comment by dimasciput** [comment]
@helendallas yes this is a bug, should be fixed now 

http://testing.healthyrivers.kartoza.com/sass/dashboard/27889/?taxon=&search=&siteId=27889&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=[%22validated%22]&sourceCollection=&ecologicalCategory=

**Comment by helendallas** [comment]
@dimasciput 
I tested this by created a New Site - H7DORI-00004
![Screenshot_2020-01-31 Select location site to change Django site admin](https://user-images.githubusercontent.com/45286876/73517862-6d730080-4405-11ea-9f22-df48cea4c80d.png)

I didn't immediately add data but rather went to find it on the map - but the site was visible.  I thought I perhaps didnt save it so created another: ; H7DORI-00005.

Is the site not visible because there is no biological data? If so we need to either - change it so that sites with no biological data are visible; or not allow creators of sites to save and exit until they have added some biological data.

@dimasciput  please help and advice.

I cannot now find either site to add data.

**Comment by dimasciput** [comment]
> @helendallas Is the site not visible because there is no biological data? 

Yes, this is the current behavior. 

> Is the site not visible because there is no biological data? If so we need to either - change it so that sites with no biological data are visible; or not allow creators of sites to save and exit until they have added some biological data.

Let me discuss it first with @timlinux.
