### ISSUE TITLE
Biobase - Collector/Owner

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1741]
@dimasciput 

For all Biobase imported data:
Collector/owner should be the **Author**: Coetzer A. not FBIS. 

Visible in CSV file

**Comment by helendallas** [comment]
The Owner of a Site and Owner of Invertebrate data imported from the Biobase is now Helen Dallas, It needs to be the Author. as per the original Biobase column. 

Screenshot_2019-11-14 FBIS Location Site Form(1)

Screenshot_2019-11-14 FBIS Location Site Form

**Comment by dimasciput** [comment]
@helendallas the author can be more than one person, does this mean that one site can have more than one owner? Currently, we only support one owner and one collector for one site. 

cc @timlinux

**Comment by helendallas** [comment]
@dimasciput 
Okay. Two options: Use the first author only for historical data.....quite acceptable; or change to include more than one owner collector.

I favour making it one author . It will be simpler I suspect.   
@jeremyshelton Please add to out list to discuss at today's zoom, thanks

**Comment by timlinux** [comment]
Discussed with FRC team - we will use the first author as the owner

**Comment by dimasciput** [comment]
`python mange.py fix_biobase_owner`

**Comment by dimasciput** [comment]
Updated in live site
