### ISSUE TITLE
Upload form - Invertebrates

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1750]
@timlinux @dimasciput 
How do we deal with taxa that are not on our list, can we include a :

**Add new taxon**

option below the list of existing taxa.

Then it goes to GBIF to check? but if it does not exist in GBIF how do we deal with typos? incorrect taxa? or do we trust the capturer will only add if correct?

**Comment by dimasciput** [comment]
@helendallas 
I can add a form to check to gbif but it's not going to be an autocomplete form, it means user needs to click the button first then the system will check the name on gbif, and then user can choose from the list. Does it make sense?

**Comment by helendallas** [comment]
@dimasciput 
Yes that will work, with time we will have fewer and fewer taxa that are not on our list. 

How do we deal with taxa that are not on GBIF either?

**Comment by timlinux** [comment]
I think for taxa that are not in GBIF we could print a little message e.g.:

"Whilst FBIS will accept taxa that are not listed in GBIF, you should use the capability only for taxa where the classification is partly unresolved e.g. <helen give good example here>.

Click OK to add this taxon even though it is not listed in GBIF, alternatively press cancel to refine your GBIF search to obtain a valid taxon name."

**Comment by timlinux** [comment]
@dimasciput will also add a drop down to select the taxon rank.
