### ISSUE TITLE
Upload form - Invertebrates

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1752]
I created fictitious data - which when it is returned for validation, shows all the taxa listed as Category - Non-native

This should be blank, until we have assigned these to the Invertebrate Master list (still a work in progress)

![Screenshot_2019-11-05 Nonvalidated Records(1)](https://user-images.githubusercontent.com/45286876/68195880-5d8f8000-ffc0-11e9-8e53-e92c1a4d90b2.png)

The map is also not useful unless it shows the site.

Also please can we chat through the validation process at our next zoom - I am not clear on all the steps put in place.

**Comment by dimasciput** [comment]
> The map is also not useful unless it shows the site.

You can click the taxon name, it will show you the site on the map.

**Comment by dimasciput** [comment]
@helendallas 

> I created fictitious data - which when it is returned for validation, shows all the taxa listed as Category - Non-native

It is actually blank, just a bug in the frontend.

**Comment by helendallas** [comment]
Ah...perfect thanks
