### ISSUE TITLE
Update biodiversity record

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1753]
The record still has both Present and Absent boxes ticked.

![Screenshot_2019-11-05 Edit Records](https://user-images.githubusercontent.com/45286876/68196156-d4c51400-ffc0-11e9-868a-72b8ba903f79.png)

**Comment by dimasciput** [comment]
@helendallas Are we agreed to just use 'Present'?

**Comment by helendallas** [comment]
@dimasciput 
Yes, all taxa included thus far is only for confirmed presence. It is very hard to know if a taxon is trul absent, or if it is just inadequate sampling.

So we can just use: Present
