### ISSUE TITLE
Automate deployment to rancher

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#176]
On the successful merge of a PR to develop or master the following needs to happen (merge should only happen after tests pass):

* Docker autobuild with tag :latest if the merge was to develop
* Docker autobuild with tag :stable of the merge was to master

Subsequently a nightly cron job will run and use the rancher API to update testing server (from :latest) and staging server (from :stable).

Once we have something production ready, it should be deployed to the production server based on the. specific release tag. Production deployments should always be done manually.

CC @gubuntu @dimasciput

**Comment by dimasciput** [comment]
Who is ciptura?

**Comment by timlinux** [comment]
hehe no autocomplete when you write tickets in waffle

**Comment by timlinux** [comment]
![screenshot 2018-10-09 at 11 13 05](https://user-images.githubusercontent.com/178003/46659035-60992080-cbb4-11e8-8db7-e6aa1fcb8790.png)

**Comment by dimasciput** [comment]
done from teamcity http://teamcity.kartoza.com/project.html?projectId=DjangoBims&tab=projectOverview
