### ISSUE TITLE
FBIS Site Code

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1762]
Several sites have well established codes such as 
G1BERG-FRANS

But they have been allocated an FBIS Site Code:
G1BERG-00101

Where Original Site Codes that conform to the standard Site Code format existed in the Rivers DB, then the same site code should of been imported. I cant figure out why it is correct for some, but not for others. 

![Screenshot_2019-11-07 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/68373351-6791ba00-014b-11ea-85c0-2845c411bcdf.png)

**Comment by dimasciput** [comment]
@helendallas 

> Several sites have well established codes such as
G1BERG-FRANS

If there are only a few, we can edit it manually for now. What's important is that the original site code is not missing.

**Comment by helendallas** [comment]
@dimasciput 
Is there an easy way to extract all FBIS Site Codes with Original Site Codes so that we can check?

**Comment by dimasciput** [comment]
@helendallas you can check directly through the database if you want, I can show you how.

**Comment by helendallas** [comment]
@dimasciput 
Yes please, at our next zoom chat

**Comment by dimasciput** [comment]
`python manage.py fix_site_codes`

**Comment by dimasciput** [comment]
updated
