### ISSUE TITLE
Overview Panel

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1763]
@dimasciput 
Geomorphological Zone and Ecoregion not given for all sites

![Screenshot_2019-11-07 FBIS Map](https://user-images.githubusercontent.com/45286876/68373637-f6063b80-014b-11ea-9d56-33212439d9e3.png)

Bug? or other issue?

**Comment by dimasciput** [comment]
@helendallas this is because we didn't fetch all geocontext data in testing, since is going to be deleted.

**Comment by helendallas** [comment]
@dimasciput Ok, that makes sense
