### ISSUE TITLE
Biobase - updating Georeference and Refined Geomorphological Zone 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1783]
Please can you update some fields is the Biobase imported data file - all at Site level, using the Original Site Code as the link, including:

- Refined Geomorphological Zone - it is "Reach" in the original Biobase  -  several of these were still using the old classification system - I have revised in the attached spreadsheet.

- Original River Name - please include for all Sites (was called RiverName in Biobase)

- Corrected latitude and Corrected longitude 

Can this be done in the back-end before bringing Biobase data over to FBIS Live.

[Biobase Sites Corrected Georeference_Sent to Kartoza.xlsx](https://github.com/kartoza/django-bims/files/3846114/Biobase.Sites.Corrected.Georeference_Sent.to.Kartoza.xlsx)

**Comment by dimasciput** [comment]
`python manage.py update_sites_from_csv -f {csv_file}`

**Comment by helendallas** [comment]
@dimasciput 
This has not been done. I checked one site BRG01, Harrison & Elsworth study; 

1 | Harrison A.D. & Elsworth J.F | 1958 | BRG01

It still has the old latitude and longitude and not the corrected one as provided in the spreadsheet.
Similarly the Refined Geomorphological Zone I provided has not been updated.

![Screenshot_2020-01-31 FBIS Map(4)](https://user-images.githubusercontent.com/45286876/73541097-44209780-443a-11ea-89b6-49d5712de9b7.png)

**Comment by dimasciput** [comment]
@helendallas I have updated the data, please check the site again : /map/#search/BRG02/taxon=&search=BRG02&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27679&polygon=

**Comment by helendallas** [comment]
@dimasciput 
BRG01 is correct, but other sites are not. For example:

From the Biobase derived spreadsheet
Coetzer A. | 1982 | OL03A | Mountain stream | OLIFANTS   (CAPE) | Olifants | -32.622780 | 19.085000 | **-32.568095 | 19.022101**

Bold is the corrected lat long.

http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=OL03A&siteId=27948&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27948&orderBy=name&polygon=

And another one, neither the geomorphologcal zone or lat long have been updated correctly.

From the Biobase derived spreadsheet
Fowles   B.K | 1984A | T21 | **Upland floodplain** | BLOOD | Blood | -27.750000 | 30.500000 | **-27.889064 | 30.588304**

http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=T21&siteId=27389&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27389&orderBy=name&polygon=

In case you have the incorrect spreadsheet - here is the correct one. I have also loaded it onto our FRC/Kartoza dropbox folder

[Biobase Sites Corrected Georeference_Sent to Kartoza.xlsx](https://github.com/kartoza/django-bims/files/4234638/Biobase.Sites.Corrected.Georeference_Sent.to.Kartoza.xlsx)


https://www.dropbox.com/s/6q55ruhaanrw8cd/Biobase%20Sites%20Corrected%20Georeference_Sent%20to%20Kartoza.xlsx?dl=0

**Comment by dimasciput** [comment]
@helendallas oh yea, what you sent me in the first comment only had 50 sites. Ok I'll update it again.

**Comment by dimasciput** [comment]
@helendallas please check it again

**Comment by helendallas** [comment]
@dimasciput Geozones and lat longs look good now.

One question is the Original River Name and River don't seem correct.  The Original River Name needs to be populated from the **Original River Name** column in the same spreadsheet.  Then the River is derived from the Rivers spatial layer.

The rationale for this is we need to use the spatial Rivers layer for assigning the River, but don't want to loose the Original River Names as per the original study .

**Comment by dimasciput** [comment]
@helendallas but the name of the original river is the same as the one from xls

![image](https://user-images.githubusercontent.com/1979569/75014625-503bca00-54b9-11ea-8938-a67aaad2cc7f.png)

**Comment by helendallas** [comment]
@dimasciput 
Okay then the River is wrong......because the OLIFANTS (CAPE) is from the the Biobase column RiverName, but should be grabbed from the Rivers spatial coverage? right?

RiverName                       | Original River Name
OLIFANTS (CAPE)             | Olifants

**Comment by dimasciput** [comment]
@helendallas Okay, I will run the script to fetch from geocontext, it might take couple days because there are lot of sites.

**Comment by dimasciput** [comment]
Actually, not a lot, just 600 because it only for BioBaseData, should be quick

**Comment by helendallas** [comment]
@dimasciput Thanks

**Comment by dimasciput** [comment]
@helendallas can you check the dashboard again please? It should have been updated with data coming from geocontext.

**Comment by helendallas** [comment]
@dimasciput 
Rivers Names and Geomorphological zones all look correct now, thanks. Before I close this ticket please can you comment on why the other geocontext data below is not being populated. Water Management Area, Sub WMA, Province, Freshwater Ecoregion

![Screenshot_2020-02-24 FBIS Map](https://user-images.githubusercontent.com/45286876/75146287-75237d80-5703-11ea-8380-9241c012e521.png)

**Comment by helendallas** [comment]
http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=27812&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22143%22]&endemic=&conservationStatus=[]&modules=21&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27812&orderBy=-name&polygon=
