### ISSUE TITLE
SASS Data - FBIS Site Code vs description

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1785]
@dimasciput 
Autogenerated FBIS Site Code - has multiple descriptions and lat longs in testing site.

X3SABI-00117

Firstly I don't know why this hasn't retained the Site Code from the RIvers DB.
Secondly, the original data for the site description - Sanbonani, is:

SiteCode | Site | UserName | RiverName | LongitudinalZone
X3SABI-SANBO | Sanbonani | Johan Engelbrecht | Sabie | Lower Foothill

while for - At Zeederberg, in gorge area (Helmut's River Shack), it is

SiteCode | Site | UserName | RiverName | LongitudinalZone
X3SABI-ZEEDE | At Zeederberg, in gorge area (Helmut's River Shack) | Johan Engelbrecht | Sabie | Rejuvenated bedrock fall / cascades

Please can you follow up what has happened here.  It is likely to be a wider issue as many sites that should have an original RIvers DB SIte Code, no longer has it.

I just checked the FBIS Live - and X3SABI-ZEEDE exists, but is absent in the testing. Is this perhaps an issue related to the SASS data in the testing site?

Please close issue if this is the case

**Comment by dimasciput** [comment]
@helendallas can you check the testing again?

**Comment by helendallas** [comment]
@dimasciput 
Seems to be sorted, thanks
