### ISSUE TITLE
Site coordinates incorrect

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#1786]
Site is on the wrong river , corrce tco ords are:

---

User : <a href="http://testing.healthyrivers.kartoza.com/admin/people/profile/478">User information </a>
Device: Desktop
Referrer: http://testing.healthyrivers.kartoza.com/map/#
Screen resolution: 2208 x 1242
Browser: Firefox

**Comment by helendallas** [comment]
done is testing bug reporting ticket - ficticious. closed
