### ISSUE TITLE
Metadata issues

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1787]
**Metadata table coming up blank when GBIF data displayed:** http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=gilli&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**GBIF data not showing for species search:** 
We know that there are GBIF data for the below species, but no GBIF data are shown in the metadata table (both Fbis and Gbif data are 'switched on'), for example:

- Galaxias zebratus: http://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=302&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

- Sandelia capensis: http://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=310&search=Sandelia%20capensis&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Then, if I search GBIF data only, the metadata table is blank:**
For example, Galaxias zebratus: http://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=302&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

@helendallas @timlinux

**Comment by dimasciput** [comment]
> We know that there are GBIF data for the below species, but no GBIF data are shown in the metadata table (both Fbis and Gbif data are 'switched on'),

@jeremyshelton so you want gbif to be shown as metadata? I don’t really understand the issue.

**Comment by dimasciput** [comment]
gbif and fbis are source of collection, shouldn’t be displayed on the metadata table

**Comment by jeremyshelton** [comment]
@dimasciput yes, I think that it is important that we show GBIF in the metadata table, even though for example the actual data were uploaded by SAIAB. Perhaps we need to somehow indicate that the data come from e.g. SAIAB but are served via GBIF? @helendallas ?

**Comment by timlinux** [comment]
Tim and Dimas to go and poke around in GBIF and see if we can pull the upstream metadata from there and load it in our local database.

**Comment by dimasciput** [comment]
@jeremyshelton so I have been playing around with gbif api, and I can only get reference url from gbif. 
Here's one example of the occurrence data from gbif : http://api.gbif.org/v1/occurrence/1839230076.
So what do you suggest?

**Comment by jeremyshelton** [comment]
@dimasciput so that just takes the user to a page with a whole bunch of code? Not the page with the actual species records and associated information? 

What's important is that when a user queries GBIF data, the metadata table indicates that those data come from the Global Biodiversity Information Facility (GBIF) and indicates the year when we last 'synched FBIS with GBIF'. 

Then, if we can pull more detailed information on who and when the data come from etc, then great, but I don't think essential. Based on http://api.gbif.org/v1/occurrence/1839230076 it looks like this is not possible?

At the moment it still shows nothing in the metadata table:
http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=302&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Comment by jeremyshelton** [comment]
@dimasciput 
Metatada for GBIF occurrences need to say 'Global Biodiversity Information Facility (GBIF)', and the date the data were pulled, in the metadata table.

**Comment by dimasciput** [comment]
@jeremyshelton will do

**Comment by dimasciput** [comment]
Done in live site

**Comment by jeremyshelton** [comment]
@dimasciput thanks - looks good.
