### ISSUE TITLE
Landuse layer?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1788]
@NyakudyaA we are keen to include a SA land use layer on FBIS. In your opinion which is the best layer for this purpose, and what would it take to add this layer?
@helendallas @timlinux @dimasciput

**Comment by NyakudyaA** [comment]
@jeremyshelton we already have a land-use layer in our geoserver, we could add it there. I think I sourced it from sanbi or saeon .
![landuse](https://user-images.githubusercontent.com/2510900/68921454-7c8ccf80-0781-11ea-95c9-712da8c442a4.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA 
Looks good, perhaps you could investigate the source and then we can add it to the layer selector on FBIS @dimasciput?

**Comment by NyakudyaA** [comment]
@jeremyshelton here is the source http://www.sasdi.net/metaview.aspx?uuid=6ae256e56930a9d325f963592325211c. I will add it to the layer selector

**Comment by NyakudyaA** [comment]
![added](https://user-images.githubusercontent.com/2510900/68941286-19656200-07ae-11ea-9d36-33759f43c17d.png)
