### ISSUE TITLE
FBIS Live - DOI

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1795]
@dimasciput @Aneri16 
We tried to add the Source Rerenece for SASS data in the live site, but it is not accepting it. The DOI looks quite strange, but it is the one published with the paper.

https://doi.org/10.1899/0887-3593(2006)25[487:ACORBP]2.0.CO;2

![Screenshot_2019-11-19 FBIS Source Reference](https://user-images.githubusercontent.com/45286876/69121151-45c9f880-0aa4-11ea-886a-c9a60fdf3f16.png)

Please can you investigate

**Comment by dimasciput** [comment]
@helendallas can you try again on the testing, and please only use the DOI, so for your case : ```10.1899/0887-3593(2006)25[487:ACORBP]2.0.CO;2```

**Comment by helendallas** [comment]
@dimasciput Its working in testing now, thanks

![Screenshot_2019-11-21 FBIS Source Reference(1)](https://user-images.githubusercontent.com/45286876/69314132-0504e780-0c3c-11ea-8eb5-5f0638088e52.png)

![Screenshot_2019-11-21 FBIS SASS](https://user-images.githubusercontent.com/45286876/69314171-206ff280-0c3c-11ea-9ebe-a81c18e7f95c.png)
