### ISSUE TITLE
Update Biodiversity Record 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1796]
At the moment, ones add invertebrate or fish data using the **Add Invertebrates data** form, then after adding the **Source reference** for records, you are then asked to **Update Biodiversity Record** 

![Screenshot_2019-11-19 Nonvalidated Records(1)](https://user-images.githubusercontent.com/45286876/69142239-1086d000-0acf-11ea-823d-deec73117148.png)

At last weeks zoom, we agreed to remove this **Update Biodiversity Record**  
@timlinux correct?

**Comment by dimasciput** [comment]
@helendallas so what is the next flow after creating the record? Do we also need to remove the validation process?

**Comment by helendallas** [comment]
@dimasciput @timlinux 
We definately want to retain the validation process - which is done by the administrator - but perhaps loose the step between the user adding the data in the original form, and then the user having to hit **Ready to be Validated** for each individual record.  I would be keen to hear @timlinux  take on this before we change anything.

**Comment by dimasciput** [comment]
@timlinux can you comment on this? 

I think we have the **Ready to be validated** process is because we want users to make sure the data is correct before validator validates it.

**Comment by helendallas** [comment]
@dimasciput @timlinux 
I am happy to leave as is and see what feedback we get from users.  A double check is not a bad thing.
