### ISSUE TITLE
Add a disclaimer for users uploading PDFs?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1799]
@timlinux @dimasciput 
I think we should be adding a disclaimer to the end of the PDF upload form - a check box for the user that they 'own the report and agree to sharing the data within for use within the FBIS, or something to that effect?
@helendallas ?

**Comment by dimasciput** [comment]
@jeremyshelton yes that makes sense, can you make the wording?

**Comment by jeremyshelton** [comment]
@dimasciput OK, here is the draft text:

‘check box’ I hereby confirm that I am the owner of this document and/or data, and agree to these being shared via the FBIS platform for download by registered FBIS users. 

@helendallas anything further to add here? Perhaps something about citing data from a downloaded report?

**Comment by helendallas** [comment]
Closing via #1975
