### ISSUE TITLE
Problem with GeoNode celery implementation

### ISSUE THREAD

**Issue by lucernae** [kartoza/django-bims#180]
When I tried to fix GeoNode's issue with layer upload (SRID doesn't get recognized). I found several issues listed here. These issues might be related with other part of the system. So, for now I just list it here for confirmation.

1. Layer can't be uploaded because GeoNode pass the information to Celery worker to be processed. By setting the BROKER_URL, GeoNode thinks that there exists a worker. However since we didn't setup a worker, these layer won't be processed. So, for now I disabled this BROKER_URL

2. To setup a broker and worker we set a BROKER_URL and ASYNC_SIGNALS to True. However, GeoNode settings currently have circular dependencies where it tries to access settings but it is currently being initialized. The problem is on L1305 in geonode.settings:

```
if USE_GEOSERVER and ASYNC_SIGNALS:
    from geonode.messaging.queues import QUEUES
    CELERY_TASK_QUEUES += QUEUES
```

To handle this, maybe we should copy paste GeoNode settings to django bims, and modify accordingly so we can modify it instead of importing it from GeoNode settings.

**Comment by lucernae** [comment]
Since @dimasciput said we need celery. Then I suggest to delete this line from settings:

```
if USE_GEOSERVER and ASYNC_SIGNALS:
    from geonode.messaging.queues import QUEUES
    CELERY_TASK_QUEUES += QUEUES
```

Then create a celery_app for django BIMS where you add the task QUEUE. Also add other QUEUE needed by BIMS and other celery configuration, like routing for it to work with the worker.

**Comment by lucernae** [comment]
By the way, if you are able to setup celery worker it will also fix the problem about layer deletion. Currently, layer can't be deleted because it calls celery.

**Comment by lucernae** [comment]
I forgot. GeoNode settings are currently nested. So you have to create another file for geonode_generic.settings and geonode.settings too, or just combine them.

**Comment by dimasciput** [comment]
PR : https://github.com/kartoza/django-bims/pull/178

**Comment by gubuntu** [comment]
@dimasciput I don't have a way to testing this? I see the PR is merged. If this is deployed on testing and you are happy you can close. 

@NyakudyaA can you upload a layer in testing (with a valid EPSG code)?

**Comment by dimasciput** [comment]
Yes this is working now for the django-bims celery process.

**Comment by NyakudyaA** [comment]
@lucernae cc @dimasciput I have tested this with multiple layers and the layer uploads do not work. I tried to upload a layer using UI with EPSG code 4326,385,32734 and nothing works. All I get is the following.
![broken](https://user-images.githubusercontent.com/2510900/44076230-b2dc5f4c-9f9f-11e8-89e0-f09737fad12e.png)
You should see those errors in sentry

**Comment by dimasciput** [comment]
Can you try again @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@dimasciput  Uploads are now working on staging. Can you please deploy these changes on testing as swell. They are however various issues that are aligned to uploads that I will open up

**Comment by gubuntu** [comment]
why is staging ahead of testing? It should be the other way around...
