### ISSUE TITLE
Department of Water and Sanitation website address change

### ISSUE THREAD

**Issue by MikeSilberbauer** [kartoza/django-bims#1801]
Just advance warning of a website change, in case any FBIS links point to it:

The Department of Water and Sanitation website will be moving to a new secure server with a domain name change, 
e.g. http://www.dwa.gov.za/iwqs/ will become **https**://www.**dws**.gov.za/iwqs/

The change is planned to take place by the end of November 2019. The old server and domain will remain active for a short period.

**Comment by dimasciput** [comment]
Thanks @MikeSilberbauer , we will keep this in mind.
