### ISSUE TITLE
PES/EIS/Eco-status spatial layer for FBIS

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1807]
Hi @NyakudyaA 

Below are some layers that we have been waiting for SANBI to publish so that we can include in the FBIS. Our focus is on the PES/EIS/Eco-status spatial layer(s):

Find the final NBA 2018 river data for download at: http://filegooi.co.za/get2/f48139cb1aecc49a944062a0b15010a9/NBA2018_Rivers_Final_Sep2019.zip

For the metadata please follow this link and click on the right hand column under Metadata “download pdf”
 
http://bgis.sanbi.org/SpatialDataset/Detail/2692

Please have a look and lets chat about these at next week's zoom

@helendallas @timlinux

**Comment by jeremyshelton** [comment]
Hi @NyakudyaA 
Have you been able to have a look at these yet? Thoughts?
@helendallas

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA
> Have you been able to have a look at these yet? Thoughts?
> @helendallas

Hi @jeremyshelton, I am on it today and will uploa them for comments

**Comment by NyakudyaA** [comment]
@jeremyshelton I see this layer also has GeoZone in the attributes list. Are we going to use this to replace the geoclass layers already in use?

**Comment by jeremyshelton** [comment]
@NyakudyaA hhmmm not sure. I think lets pick this up with the group early in the new year & get Tims advice. Have made a note...

**Comment by NyakudyaA** [comment]
@jeremyshelton Here is the layer https://maps.kartoza.com/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:nba_2018_rivers&styles=&bbox=15.9057273864746,-34.796329498291,34.0566444396973,-19.8364105224609&width=768&height=632&srs=EPSG:4326&format=application/openlayers
The metadata from sanbi link has dissapeared.

In which spatial drawer would you like this to show up ?

**Comment by helendallas** [comment]
@jeremyshelton PLease can we chat about this and get our duck in a row before Admire adds

**Comment by jeremyshelton** [comment]
@NyakudyaA I will ask Nancy to resend the metadata. In the meantime, would you mind acting the layer to this folder on dropbox:http://filegooi.co.za/get2/f48139cb1aecc49a944062a0b15010a9/NBA2018_Rivers_Final_Sep2019.zip

**Comment by jeremyshelton** [comment]
@NyakudyaA here is the new link:https://bgis.sanbi.org/SpatialDataset/Detail/3697
Also PDF attached:
[NBA2018_Rivers_metadata.pdf](https://github.com/kartoza/django-bims/files/4249660/NBA2018_Rivers_metadata.pdf)

**Comment by jeremyshelton** [comment]
@NyakudyaA @dimasciput Present Ecological State (PES) Needs it's own (new) drawer in the 'Spatial' filters tab

**Comment by NyakudyaA** [comment]
> @NyakudyaA I will ask Nancy to resend the metadata. In the meantime, would you mind adding the layer to this folder on dropbox (so we can look at the columns and decide which columns we need to use and lose): https://www.dropbox.com/sh/uav5smvf4l3qx0i/AAAQ-4A4UELKaPraW3wYHoXna?dl=0

I do not have access to that dropbox but can you check it out here http://filegooi.co.za/get2/a986e926465159781ae032da5b882a53/NBA2018_Rivers.zip. Which

**Comment by NyakudyaA** [comment]
@jeremyshelton I do not see the Present Ecological State (PES) layer anywhere. Please send me the link to it

**Comment by jeremyshelton** [comment]
Is the PES layer not in here:  http://filegooi.co.za/get2/a986e926465159781ae032da5b882a53/NBA2018_Rivers.zip ?

That what was sent to us by SANBI. It is also in the Kartoza dropbox folder...

**Comment by jeremyshelton** [comment]
@NyakudyaA priority attributes and fields from the NBA 2019 layers:
<img width="567" alt="Screenshot 2020-02-28 at 09 26 28" src="https://user-images.githubusercontent.com/44292029/75519713-8a065680-5a0c-11ea-9511-e40f094c7c76.png">

**Comment by NyakudyaA** [comment]
> @NyakudyaA priority attributes and fields from the NBA 2019 layers:
> <img alt="Screenshot 2020-02-28 at 09 26 28" width="567" src="https://user-images.githubusercontent.com/44292029/75519713-8a065680-5a0c-11ea-9511-e40f094c7c76.png">

To add in its own drawer in the spatial filters. @NyakudyaA to split the NBA layer to generate those different types and populate them in geocontext

**Comment by NyakudyaA** [comment]
@dimasciput you can proceed to add this in the spatial filters list:
![river-management-group](https://user-images.githubusercontent.com/2510900/75626168-bfa66d80-5bcd-11ea-9f57-08bcf1c462bd.png)

**Comment by helendallas** [comment]
@jeremyshelton Please can you check this and close if all working correctly.

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA Could you give an update on progress with adding the this? Again, this would be a layer, as well as a drawer in the spatial filters.

**Comment by helendallas** [comment]
@NyakudyaA 
Please can you include the full name as per the table, not just the code. You have done it for some but not all of them.
![Screenshot_2020-04-07 FBIS Map](https://user-images.githubusercontent.com/45286876/78669284-54427080-78dc-11ea-91bc-58f2874296d8.png)

![image](https://user-images.githubusercontent.com/45286876/78669289-560c3400-78dc-11ea-8531-b6328c600814.png)

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> Please can you include the full name as per the table, not just the code. You have done it for some but not all of them.
> ![Screenshot_2020-04-07 FBIS Map](https://user-images.githubusercontent.com/45286876/78669284-54427080-78dc-11ea-91bc-58f2874296d8.png)
> 
> ![image](https://user-images.githubusercontent.com/45286876/78669289-560c3400-78dc-11ea-8531-b6328c600814.png)

@helendallas I would have to create separate lookups  tables for those values and join them to the respective tables for consistency sake because currently, I do not manipulate the raw data . I try to server it as is that's why you see it's inconsistent.
![threat-eco](https://user-images.githubusercontent.com/2510900/78672044-632b2200-78e0-11ea-967c-4be73157396f.png)

**Comment by helendallas** [comment]
If I updated the dbf file, would the correct labels come through?

@jeremyshelton Thoughts?

**Comment by NyakudyaA** [comment]
> If I updated the dbf file, would the correct labels come through?
> 
> We really want to avoid using abbreviations that may not be known by the user community. Obviously the dbf file should of been served correctly with the full names. Perhaps I can raise this with the NBA team as well.
> 
> @jeremyshelton Thoughts?

I will then have to ingest it in the DB again. Can you share the updated layer and will ingest it. it should be quick

**Comment by helendallas** [comment]
@NyakudyaA I am not a GIS expert, os wanted to check that I wont mess anything up if I rename codes in NBA2018_Rivers_Final_Sep2019.dbf to be the full label and not the abbreviation

**Comment by NyakudyaA** [comment]
> @NyakudyaA I am not a GIS expert, os wanted to check that I wont mess anything up if I rename codes in NBA2018_Rivers_Final_Sep2019.dbf to be the full label and not the abbreviation

What you have done is fine. I just need the shapefile including the DBF so that I can load it in the database again

**Comment by helendallas** [comment]
@NyakudyaA 
I am not able to save a dbf file in excel. So not sure that I will be able to do this. Suggestions welcome

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> I am not able to save a dbf file in excel. So not sure that I will be able to do this. Suggestions welcome

Do not worry about this. I will fix it on my side

**Comment by helendallas** [comment]
@NyakudyaA thanks so much!

**Comment by jeremyshelton** [comment]
@NyakudyaA @dimasciput 

Can we please action this soonest? I am busy testing the layers and see that we still have the erroneous labels. Can we please implement the correct labels, categories and details as per Alan's table provided above. 

Thanks!

@helendallas @timlinux

**Comment by NyakudyaA** [comment]
I have updated the layers here to show the correct labels, please test and revert. Maybe thy might need to be reingested again cc @dimasciput

**Comment by helendallas** [comment]
@NyakudyaA @dimasciput 
Still not correct on live site
![Screenshot_2020-04-21 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/79843658-d346a700-83ba-11ea-8ced-7205210f010a.png)


and spatial filters not available on testing site
![Screenshot_2020-04-21 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/79843613-c32ec780-83ba-11ea-8241-212b65befcd4.png)

**Comment by NyakudyaA** [comment]
> @NyakudyaA @dimasciput
> Still not correct on live site
> ![Screenshot_2020-04-21 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/79843658-d346a700-83ba-11ea-8ced-7205210f010a.png)
> 
> and spatial filters not available on testing site
> ![Screenshot_2020-04-21 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/79843613-c32ec780-83ba-11ea-8241-212b65befcd4.png)

@dimasciput Need to update geocontext values again

**Comment by helendallas** [comment]
@NyakudyaA Please confirm if you are still planning to expand labels for the categories as per this ticket.

**Comment by NyakudyaA** [comment]
> @NyakudyaA Please confirm if you are still planning to expand labels for the categories as per this ticket.

It's already implemented. 
@dimasciput please fetch for all the values for Spatial filters in the drawer National Biodiversity Assessment 2018

**Comment by helendallas** [comment]
@dimasciput Please fetch so we can check and close ticket, thanks

**Comment by jeremyshelton** [comment]
@dimasciput can you give an update on this ticket?

**Comment by dimasciput** [comment]
@jeremyshelton I'm still fetching catchment data, will do this later. I think we can do this in the background, so it should be fine if we want to open the site while fetching data from geocontext.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput - let us know when you are ready for us to test. Let's keep this ticket open until then 👍

**Comment by jeremyshelton** [comment]
@dimasciput is this now ready to test?

**Comment by dimasciput** [comment]
@jeremyshelton not yet, I'm still fetching other spatial data. 

@NyakudyaA I still couldn't get any data from https://geocontext.kartoza.com/api/v1/geocontext/value/group/19.18611/-33.98/national_biodiversity_assessment_2018/

**Comment by NyakudyaA** [comment]
> @jeremyshelton not yet, I'm still fetching other spatial data.
> 
> @NyakudyaA I still couldn't get any data from https://geocontext.kartoza.com/api/v1/geocontext/value/group/19.18611/-33.98/national_biodiversity_assessment_2018/

I will look it up @dimasciput still bust trying to fix qgis-server issues here

**Comment by helendallas** [comment]
@jeremyshelton 
PLease check if this has been resolved and close if you are happy.

**Comment by helendallas** [comment]
Not sure if sorted, moving to FBIS V5 project

**Comment by jeremyshelton** [comment]
This is not sorted yet. 

There are still a lot of incorrect category labels and use of letter cases (e.g. upper case vs lower case etc).

Here is a link (see sheet called 'NBA 2018') to a spreadsheet with all of the correct labels for the different categories within each filter group: https://www.dropbox.com/home/FRC_Kartoza%20Shared%20Folder%20for%20FBIS/Filters?select=FBIS+FILTER+TESTING_MAY2020.xlsx

I cannot correct these via the FBIS admin pages to @NyakudyaA I think this must be done your end?

@dimasciput @helendallas

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 
From my checking it seems that a few of the labels are all correct, but that some of the categories/details still need revision. 

@NyakudyaA are you able to correct these please?

Link provided above.

**Comment by helendallas** [comment]
I have linked this ticket to #2400
