### ISSUE TITLE
Unable to add new site

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1808]
@dimasciput @jeremyshelton 
I am unable to add a new site. When I click "add", the following screen pops up:

![FBIS bug](https://user-images.githubusercontent.com/55532903/69412494-a7de6400-0d17-11ea-84ee-204c7a90458e.png)

**Comment by dimasciput** [comment]
@Aneri16 can you add it in testing?

**Comment by Aneri16** [comment]
@dimasciput no, the same message pops up in Testing

**Comment by dimasciput** [comment]
Ah ok cool, let me check

**Comment by dimasciput** [comment]
@Aneri16 did you try it here http://testing.healthyrivers.kartoza.com/location-site-form/add/ ?

**Comment by Aneri16** [comment]
@dimasciput yes I did and tried again now but still not working...

**Comment by dimasciput** [comment]
@Aneri16 can you explain to me your steps? Because I couldn't reproduce this error.

**Comment by Aneri16** [comment]
@dimasciput I just tried again now on another computer and all is working fine :D might be my computer. Thanks for your help!
