### ISSUE TITLE
Add Abiotic data form 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#1819]
Continuing from this ticket https://github.com/kartoza/django-bims/issues/1610

@helendallas 
On reflection lets keep things simple. 

For all data capture (algae, invertebrates, SASS and fish) we had envisaged capturing biodiversity data first, then prompting the user to **Add abiotic data**.  They would then go to the **Abiotic Data Form**, where they would have five **Categorical variables** populated with a dropdown list; and could then also add data from a list of **continuous abiotic variables**. If they had no abiotic data, they would just move straight on to adding the **Source reference for records**.

We envisaged these data being stored in the same way as Rivers DB and Biobase data is, and then served in abiotic graphs (DO, Cond, pH and Temp) and in the csv file.

**Categorical  variables populated with a dropdown list | Dropdown list**

**Water surface width** : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
**Water level** : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood
**Water turbidity** :  Clear, Discoloured, Opaque, Silty
**Canopy cover** :  Open, Closed, Partially Open
**Embeddeddness** :  0-25, 26-50, 51-75, 76-100

**Continuous variables populated with dropdown/predicted text**? Sorted alphabetically | Unit
Aluminium | mg/l
Ammonia nitrogen | mg/l
Ammonium nitrogen | mg/l
Bicarbonate | mg/l
Biological Oxygen Demand | mg/l
Calcium | mg/l
Carbonate | mg/l
Chemical Oxygen Demand | mg/l
Chloride | mg/l
Chlorophyll a | mg/l
Conductivity | mS/m
Depth | m
Dissolved inorganic nitrogen | mg/l
Dissolved organic nitrogen | mg/l
Dissolved oxygen | mg/l
Dissolved Oxygen: % saturation | %
Fluoride | mg/l
Iron | mg/l
Kjeldahl nitrogen | mg/l
Lead | mg/l
Magnesium | mg/l
Near bed velocity | m/s
Nitrate nitrogen | mg/l
Nitrite nitrogen | mg/l
Particulate organic matter | mg/l
pH |  
Potassium | mg/l
Silica | mg/l
Sodium | mg/l
Soluble reactive phosphate (=   PO4-P) | mg/l
Submerged macrophytes | %
Sulphate | mg/l
Temperature | deg C
Total alkalinity | meq/l
Total dissolved solids | mg/l
Total inorganic carbon | mg/l
Total nitrogen | mg/l
Total organic carbon | mg/l
Total organics in TSS | mg/l
Total phosphorus | mg/l
Total suspended solids | mg/l
Turbidity | NTU
Undercut bank | %
Woody debris | %

Excel data file of the above attached. This is a simplified version of the abiotic datafile from Biobase.
[Abiotic Data Variables Master.xlsx](https://github.com/kartoza/django-bims/files/3863694/Abiotic.Data.Variables.Master.xlsx)

**Comment by helendallas** [comment]
@dimasciput 
Some variables missing in dropdown list for:
Water surface width : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
Water level : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood

Then for add abiotic data
Sometimes the variable is served twice....e.g pH,  please only return once for each variable.

Please add units in parenthesis after variable so that the user knows what measurement they need to capture the data in.  e.g. Total phosphorus (mg/l).

Please use the list above.

How easy would it be to add the option to Add new variable?  This could be for another version.

**Comment by dimasciput** [comment]
@helendallas 
> Some variables missing in dropdown list for:
Water surface width : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
Water level : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood

I will add it later for live site, this is only data issue.

> Then for add abiotic data
Sometimes the variable is served twice....e.g pH, please only return once for each variable.
Same for above, data issue

> Please add units in parenthesis after variable so that the user knows what measurement they need to capture the data in. e.g. Total phosphorus (mg/l).
Will do

> How easy would it be to add the option to Add new variable? This could be for another version.
Staff could add it easily from the admin page. No coding needed.

**Comment by helendallas** [comment]
@dimasciput We need to see these categorical variables before the Continuous variables populated with dropdown/predicted text?  In the Add Abiotic data form, please.  We need to be able to add Abiotic Data to existing Sites as well as new Sites.
@jeremyshelton 

Categorical variables populated with a dropdown list | Dropdown list

Water surface width : <1; 1-2; 2-5; 5-10; 10-20; 20-50; 50-100; >100 m
Water level : Dry, Isolated pools, Low flow, Moderate flow, High flow, Flood
Water turbidity : Clear, Discoloured, Opaque, Silty
Canopy cover : Open, Closed, Partially Open
Embeddeddness : 0-25, 26-50, 51-75, 76-100

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 
Updated on testing : http://testing.healthyrivers.kartoza.com/abiotic/?survey=2

Will deploy to live site on the weekend, since it will make the site down.

**Comment by dimasciput** [comment]
Updated in live site
