### ISSUE TITLE
SASS Accreditation Checking

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1826]
Can we please double check that the RiversDB SASS accreditation data was imported correctly. For example this person should be listed as accredited:

http://testing.healthyrivers.kartoza.com/admin/people/profile/496/change/?_changelist_filters=q%3Dchrista

You can see the balance of accredited vs non-accredited is heavily skewed towards non-accredited:

![Screenshot 2019-12-04 at 10 33 18](https://user-images.githubusercontent.com/178003/70135244-92efc200-1681-11ea-9c17-a00c73f89c48.png)
![Screenshot 2019-12-04 at 10 32 44](https://user-images.githubusercontent.com/178003/70135245-93885880-1681-11ea-8812-b5819c46540c.png)

**Comment by helendallas** [comment]
@dimasciput This has been on the to do list for ages. It really needs to be rexolved asap please.

**Comment by dimasciput** [comment]
Hi @helendallas please put this in top priority in ready column https://github.com/kartoza/django-bims/projects/3#card-33214225, I will finish this before others. This will take half to full day to finish.

**Comment by dimasciput** [comment]
- Updated the script to import sass validation status to correctly map the sass accreditation date
- Updated the search function, to filter collection records by SASS accreditation status correctly, now it will compare the date of collection of records with the owner's SASS accreditation date.

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/74929618-7a847d80-540e-11ea-8e6d-7fcf84107627.png)
Data sample for cross checking between database from riversdb and application database.

**Comment by helendallas** [comment]
@dimasciput I ma not sure where to check this. If I look up in People/Users on Admin, then the accreditation is different to what is above.
e.g. 
![Screenshot_2020-02-20 Change user Django site admin](https://user-images.githubusercontent.com/45286876/74956824-5ecda700-540f-11ea-8db3-51dc8ed9e128.png)

It is quite hard for me to check on the original Rivers DB.
This is perhaps something that will also need to be accessed by the administrator. Please cna you explain the process to me tomorrow.

**Comment by dimasciput** [comment]
@helendallas it's in the live site, I updated live site directly, http://freshwaterbiodiversity.org/admin/people/profile/1518/change/?_changelist_filters=q%3DHelen%26o%3D3.1

**Comment by helendallas** [comment]
@timlinux  @dimasciput 
Please can we confirm this is correct. I urgently need to edit Users on the Live Site, for SASS accreditation, as well as multiple records for same person.

Can you please create a detailed explanation of the best way to do this, and be sure that I am not deleting data.....
![Screenshot_2020-03-18 Select user to change Django site admin](https://user-images.githubusercontent.com/45286876/76938861-0c918000-6900-11ea-885a-80317e02e961.png)

**Comment by dimasciput** [comment]
@helendallas it's fine to edit any of the data now, but just don't delete them. I will create a script to merge the user data.

**Comment by helendallas** [comment]
This is waiting for Dimas to run user updates on live site

**Comment by helendallas** [comment]
@dimasciput Please confirm if you have run user update on the live site. I urgently need to edit users, and update SASS accreditation.

**Comment by helendallas** [comment]
Moving to FBIS V5 - as still need to be done.

**Comment by helendallas** [comment]
Closing this ticket via - User cleanup needs to include duplicate users (merging) #2201 as well as update SASS accreditation status
