### ISSUE TITLE
Biobase Data - Delete Dallas 1994

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1831]
Please delete all biological data associated with Study Reference: **Dallas 1994** from the FBIS Live site once Biobase data have been migrated  This is already captured as SASS data and has been imported from the Rivers Database.

Dallas   H.F.  1994  An evaluation   of SASS (South African Scoring System) as a tool for the rapid assessment of   water quality.  Msc Thesis.   Zoology Department, University of Cape Town, South Africa.

**Comment by dimasciput** [comment]
done in live site
