### ISSUE TITLE
FBIS v2.6: pre-release issues

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1834]
This is a list of issues detected during FRC testing of FBIS v2.6 before circulating the 'release' to the users & partners. 

**Spatial filters #1823**
Some spatial filters seem to have been lost?
- WSAs (Water Source Areas)?
- CBA?
- NFEPAs?

<img width="737" alt="Search" src="https://user-images.githubusercontent.com/44292029/71167396-4b5e5e00-225d-11ea-84a6-65e13da89f24.png">

**Metadata**

- Data from GBIF not clear in metadata table: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name
- Ticket #1787
￼
<img width="1377" alt="Metadata Table" src="https://user-images.githubusercontent.com/44292029/71167435-574a2000-225d-11ea-8c62-c810341e91ee.png">

**Problems loading taxon and single site dashboards**

- For example, the fish dashboard for Galaxias zebratus failed to load for me multiple times: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name
- Another example for a single site dashboard: Phttp://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=29987&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=29987&orderBy=name

**Filter names**

- We changed ‘Spatial scale’ to ‘Spatial’ and ’Temporal scale’ to ’Temporal’ etc in the testing site, but these seem to have reverted back to their previous labels in the live site?

<img width="737" alt="Search" src="https://user-images.githubusercontent.com/44292029/71167460-616c1e80-225d-11ea-8c37-c3fbf0f6af12.png">

**Adding data**

- Not able to select associated information (E.g. broad biotope etc) when adding a new (fish) occurrence: http://freshwaterbiodiversity.org/fish-form/?siteId=5717

<img width="1163" alt="12042019" src="https://user-images.githubusercontent.com/44292029/71167486-6e890d80-225d-11ea-9ec8-d47ba7ff6060.png">

- Default ‘Add abiotic data options not showing as per testing site:http://freshwaterbiodiversity.org/abiotic/?survey=2&next=/source-reference-form/?session=eb4db646-b4c7-4788-ad84-35488be83af8&identifier=fish-form
￼
<img width="1148" alt="Add New Abiotic Data For H1WIT-00011 (2019-12-04)" src="https://user-images.githubusercontent.com/44292029/71167491-72b52b00-225d-11ea-8dba-718bbf121824.png">

**Number of records**
Fish

- For our national fish data (CFE and SA combined), there should be 12058 + 173 = 12231 records. However, the live site is showing 17660 records? I this perhaps because the new data have been added to the previous CFE data? If so, the previous CFE data need to be deleted, because these now feature in the new updated spreadsheet that we shared. 

@helendallas @Aneri16

**Comment by dimasciput** [comment]
Thanks @jeremyshelton!
Will address this tomorrow.

**Comment by jeremyshelton** [comment]
@dimasciput thanks!
@helendallas please test the SASS work flows and add any issues to this ticket.

**Comment by helendallas** [comment]
When validated and non-validated are selected - there are some fish records from Namibia included.

![Screenshot_2019-12-19 FBIS Map](https://user-images.githubusercontent.com/45286876/71171009-67fe9400-2265-11ea-9f36-1cb2cc72a028.png)

**Comment by helendallas** [comment]
Add Site - generate Site Code not working correctly.
I added a fictitious site, and ask that the FBIS Site Code be generate .
The River name was not included as per the standardised naming format:

G2DISA-00001
but it came back as 
G2-00001

![Screenshot_2019-12-19 FBIS Location Site Form(1)](https://user-images.githubusercontent.com/45286876/71171476-8ca73b80-2266-11ea-834a-fa10b466954b.png)

**Comment by helendallas** [comment]
Abiotic CSV download - Location Site strange

![image](https://user-images.githubusercontent.com/45286876/71173345-2a9d0500-226b-11ea-8362-57abe4310f6d.png)

**Comment by helendallas** [comment]
![Screenshot_2019-12-19 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/71173542-aeef8800-226b-11ea-9d6e-f558d8aef7b1.png)

The SASS Taxa should be the same as the list in the SASS Form - not this one
![image](https://user-images.githubusercontent.com/45286876/71173574-c62e7580-226b-11ea-909c-b73c8486904d.png)

**Comment by helendallas** [comment]
Tried to add new SASS data to an existing Site but stumbled when said Add. Not working please check.

![Screenshot_2019-12-19 500 - Server Error(1)](https://user-images.githubusercontent.com/45286876/71173782-4bb22580-226c-11ea-9663-6897c986a4a1.png)

**Comment by dimasciput** [comment]
@jeremyshelton Metadata updated for gbif : 
![image](https://user-images.githubusercontent.com/1979569/71236503-bc6f4580-2331-11ea-8499-7b4eb98801f4.png)

http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=%5B%22validated%22%5D&sourceCollection=%5B%22gbif%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Comment by dimasciput** [comment]
#### Spatial filters have been added back

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1979569/71242776-41ae2680-2341-11ea-8a71-721d896dd463.png">

**Comment by dimasciput** [comment]
> For example, the fish dashboard for Galaxias zebratus failed to load for me multiple times: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

Fixed it

**Comment by dimasciput** [comment]
> We changed ‘Spatial scale’ to ‘Spatial’ and ’Temporal scale’ to ’Temporal’ etc in the testing site, but these seem to have reverted back to their previous labels in the live site?

#### Fixed

**Comment by dimasciput** [comment]
> Add Site - generate Site Code not working correctly.
I added a fictitious site, and ask that the FBIS Site Code be generate .
The River name was not included as per the standardised naming format:

@helendallas can you try it again? And please don't upload picture with large size, shouldn't be more than 5mb.

**Comment by jeremyshelton** [comment]
> @jeremyshelton Metadata updated for gbif :
> ![image](https://user-images.githubusercontent.com/1979569/71236503-bc6f4580-2331-11ea-8499-7b4eb98801f4.png)
> 
> http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=%5B%22validated%22%5D&sourceCollection=%5B%22gbif%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

Thanks @dimasciput - looking good 👍

**Comment by jeremyshelton** [comment]
> #### Spatial filters have been added back
> <img alt="image" width="378" src="https://user-images.githubusercontent.com/1979569/71242776-41ae2680-2341-11ea-8a71-721d896dd463.png">

👍

**Comment by jeremyshelton** [comment]
> > We changed ‘Spatial scale’ to ‘Spatial’ and ’Temporal scale’ to ’Temporal’ etc in the testing site, but these seem to have reverted back to their previous labels in the live site?
> 
> #### Fixed
> ![image](https://user-images.githubusercontent.com/1979569/71302835-aff6f580-23e2-11ea-9436-a5d742cc68fc.png)

👍

**Comment by jeremyshelton** [comment]
> > For example, the fish dashboard for Galaxias zebratus failed to load for me multiple times: [http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name](http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=%5B%22validated%22%5D&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name)
> 
> Fixed it

@dimasciput OK cool - looks good. Did notice a bug on that dashboard: All Galaxias are native. Red bar should be Non-native, and should show a zero value here.

<img width="854" alt="Screenshot 2019-12-21 at 07 55 46" src="https://user-images.githubusercontent.com/44292029/71303913-dc514880-23c7-11ea-8e9f-49c6dfd180b3.png">

**Comment by dimasciput** [comment]
> > > For example, the fish dashboard for Galaxias zebratus failed to load for me multiple times: [http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name](http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=%5B%22validated%22%5D&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name)
> > 
> > 
> > Fixed it
> 
> @dimasciput OK cool - looks good. Did notice a bug on that dashboard: All Galaxias are native. Red bar should be Non-native, and should show a zero value here.
> 
> <img alt="Screenshot 2019-12-21 at 07 55 46" width="854" src="https://user-images.githubusercontent.com/44292029/71303913-dc514880-23c7-11ea-8e9f-49c6dfd180b3.png">

@jeremyshelton fixed it

**Comment by jeremyshelton** [comment]
> > > > For example, the fish dashboard for Galaxias zebratus failed to load for me multiple times: [http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name](http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=%5B%22validated%22%5D&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name)
> > > 
> > > 
> > > Fixed it
> > 
> > 
> > @dimasciput OK cool - looks good. Did notice a bug on that dashboard: All Galaxias are native. Red bar should be Non-native, and should show a zero value here.
> > <img alt="Screenshot 2019-12-21 at 07 55 46" width="854" src="https://user-images.githubusercontent.com/44292029/71303913-dc514880-23c7-11ea-8e9f-49c6dfd180b3.png">
> 
> @jeremyshelton fixed it

Looks good now - thanks @dimasciput

**Comment by jeremyshelton** [comment]
> When validated and non-validated are selected - there are some fish records from Namibia included.
> @jeremyshelton it looks like it is one of Albert Chakona's studies - not sure why data from Namibia is included?
> 
> ![Screenshot_2019-12-19 FBIS Map](https://user-images.githubusercontent.com/45286876/71171009-67fe9400-2265-11ea-9f36-1cb2cc72a028.png)

@Aneri16 Can you please track down the data points (1) in Namibia and (2) in the ocean and either correct the coords or remove these from our fish data set? Thanks

**Comment by jeremyshelton** [comment]
> Abiotic CSV download - Location Site strange
> 
> ![image](https://user-images.githubusercontent.com/45286876/71173345-2a9d0500-226b-11ea-8362-57abe4310f6d.png)

@helendallas if possible please include url's for these issues in the future- makes following up much easier. Thanks

**Comment by Aneri16** [comment]
@jeremyshelton will do. Seems to be four data points outside of SA, and in the ocean too.

**Comment by jeremyshelton** [comment]
> @jeremyshelton will do. Seems to be four data points outside of SA, and in the ocean too.

Yes, rather odd 🤔 Please investigate and see if it is our error, or the author's error (in which case we should probably remove those records...)

**Comment by jeremyshelton** [comment]
FISH METADATA
@dimasciput in some cases there seem to be no metadata associated with a record, and Toni is the owner in the csv - the owner should be the study author, right?

**Comment by Aneri16** [comment]
@jeremyshelton @dimasciput 
I have corrected and or deleted the sites that were not in SA or were in the ocean. Should be all of them. Dimas might have to refresh on his side for the dots to disappear from the map.

**Comment by jeremyshelton** [comment]
> @jeremyshelton @dimasciput
> I have corrected and or deleted the sites that were not in SA or were in the ocean. Should be all of them. Dimas might have to refresh on his side for the dots to disappear from the map.

Thanks @Aneri16.
@dimasciput looks like its sorted now:
<img width="1207" alt="Screenshot 2020-01-10 at 13 58 56" src="https://user-images.githubusercontent.com/44292029/72151692-8b72b580-33b1-11ea-8eaf-c018748afe7c.png">
