### ISSUE TITLE
Spatial filters: National CBA 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1841]
@NyakudyaA please can you check that this is the correct National CBA layer? It looks more like like NFEPA information?

<img width="509" alt="Screenshot 2020-01-10 at 13 25 25" src="https://user-images.githubusercontent.com/44292029/72149993-21581180-33ad-11ea-94fe-f4b8ecc40e24.png">

@dimasciput

**Comment by NyakudyaA** [comment]
@dimasciput It seems this layer is also correctly defined in geocontext and the DB
![name](https://user-images.githubusercontent.com/2510900/72219970-9285f900-3554-11ea-982f-596b78900d46.png)

**Comment by dimasciput** [comment]
Should be fixed now 
![image](https://user-images.githubusercontent.com/1979569/72232291-b730ae00-35f2-11ea-99e4-ae2b7aa3d01d.png)

**Comment by jeremyshelton** [comment]
OK looks good. Thanks @dimasciput and @NyakudyaA 👍
