### ISSUE TITLE
Spatial filters: Freshwater ecoregion of the world

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1842]
@NyakudyaA @dimasciput looks like some strange numbers have crept in here - can we track down the names of the Ecoregion they represent?
<img width="397" alt="Screenshot 2020-01-10 at 13 29 32" src="https://user-images.githubusercontent.com/44292029/72150476-46994f80-33ae-11ea-9ef3-92b75fe39647.png">

**Comment by NyakudyaA** [comment]
@dimasciput the DB seems fine as well. Maybe you might need to rerun the geocontext for that spatial filter.
![names](https://user-images.githubusercontent.com/2510900/72219812-c3fdc500-3552-11ea-9ede-9f58449943c0.png)

**Comment by dimasciput** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/1979569/72232449-ccf2a300-35f3-11ea-8b61-92bf47e79ac2.png)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 👍
