### ISSUE TITLE
Author/Metadata issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1845]
@dimasciput Toni is listed as the collector for these records, but shouldn't be. She entered the data, but did not collect them...
http://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=["Toni%20Olsen"]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

@helendallas who should be the collector for Rivers Database records like these?

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 
I have manually edited these sites and reassigned ownership to Christa Thirion, which is correct.  I ma closing this ticket now.
