### ISSUE TITLE
Fish CSV and Data issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1847]
@dimasciput @timlinux I picked up two issues with the fish data, which can be seen in the .csv file for e.g. Sandelia capensis:
1. There is no reference and reference category for lots of the records,
2. Toni is still listed at the collector/owner, but she should not be. 

This is inconsistent with whats in the spreadsheet, which as far as I can tell is correct?

<img width="1032" alt="Screenshot 2020-01-14 at 08 09 05" src="https://user-images.githubusercontent.com/44292029/72318698-a4c37c80-36a5-11ea-9e34-83aa4b68b362.png">

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton I forgot to remove old data, sorry about that. Please try it again.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 

Looking good now. Just not sure about the collector/owner column - I think it should reflect the lead author @helendallas? How important is that column?

<img width="1132" alt="Screenshot 2020-01-16 at 16 05 58" src="https://user-images.githubusercontent.com/44292029/72531592-71861680-387a-11ea-9f95-8e643c669062.png">

**Comment by jeremyshelton** [comment]
OK @dimasciput , so what needs to happen is we need the collector/owner information from the excel spreadsheet to also appear in the csv. See below: 

<img width="1160" alt="Screenshot 2020-01-17 at 13 09 21" src="https://user-images.githubusercontent.com/44292029/72608213-e57ff780-392a-11ea-9801-4d0cabb69ba1.png">

**Comment by helendallas** [comment]
@jeremyshelton I am closing this ticket as it is replaced by #2040

**Comment by jeremyshelton** [comment]
OK 👍
