### ISSUE TITLE
Unable to submit feedback

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1848]
Unable to submit feedback for bug report. 

![Feedback bug 2](https://user-images.githubusercontent.com/55532903/72324201-08a07200-36b3-11ea-8ba3-a341310f64a6.jpg)

**Comment by dimasciput** [comment]
@Aneri16 fixed it, please try again

**Comment by Aneri16** [comment]
@dimasciput 
Sorted, thank you

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I don't seem to be able to hit the submit button?

<img width="727" alt="Screenshot 2020-01-14 at 10 05 38" src="https://user-images.githubusercontent.com/44292029/72325493-e3f9c980-36b5-11ea-9196-7e4c4fea5925.png">

**Comment by dimasciput** [comment]
@jeremyshelton min 4 characters for the title

**Comment by dimasciput** [comment]
sorry 5 chars

**Comment by jeremyshelton** [comment]
@dimasciput 👍
