### ISSUE TITLE
Zero records showing for Lestagella penicillata?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1854]
...but there should be lots
http://freshwaterbiodiversity.org/map/#search/Lestagella%20penicillata/taxon=&search=Lestagella%20penicillata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Comment by dimasciput** [comment]
@jeremyshelton uncheck the fbis in data source filter panel, you should get a lot

**Comment by jeremyshelton** [comment]
OK thank @dimasciput, but my understanding is that those records should all be FBIS data?
@helendallas please have a look?

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas also seems strange that there are no Lestagella penicillata post 1991?

**Comment by timlinux** [comment]
Proposed fix is for @dimasciput to do a batch update, assigning everything that is not a GBIF record as an FBIS record. See also #1872 which proposes removing the FBIS data source in the data sources drawer.

**Comment by jeremyshelton** [comment]
Yes, I think that fixing #1872 will also fix this issue :)

**Comment by dimasciput** [comment]
@jeremyshelton can you check this again, I already updated the data source

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas yes, thanks Dimas - this looks good now. Closing ticket.
