### ISSUE TITLE
SASS CSV data download bug (reported by a user)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1855]
Hi @dimasciput, please see user-reported bug below: 

To whom it may concern at the FBIS project,
 
My name is Dalal Hanna, I am a PhD Candidate at McGill University, in Canada, doing research on the effects of protection on freshwater ecosystem services.  I collaborate with Dirk Roux from SANParks who connected me with your network, as I'm looking for a large water quality dataset from South Africa I could use for one of my PhD projects.
I have been exploring the FBIS and the sites that have been attributed a SASS seem like a perfect fit for what I am looking (I was looking for this type of water quality indicator that combines a suite of different parameters). What a beautiful open platform you have built!
 
I would like to download a .csv with all the SASS 2063 records in the database:
<img width="702" alt="Screenshot 2020-01-20 at 09 27 41" src="https://user-images.githubusercontent.com/44292029/72706626-27957d00-3b67-11ea-84a6-ede337fd960b.png">

 
However, every time I've tried to download these on the multiple sites dashboard SASS page, the .csv never finished processing (as you will notice in the below screenshot). I've tried multiple times, even letting the page process over the course of multiple days, without success.  Is there any way you'd be able to extract this .csv for the relevant 2063 site records with SASS scores and send it to me? 
<img width="678" alt="Screenshot 2020-01-20 at 09 27 47" src="https://user-images.githubusercontent.com/44292029/72706631-2c5a3100-3b67-11ea-809f-63214bb58428.png">

@Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton I think the server couldn't handle to process 140k data for csv
cc @timlinux

**Comment by Aneri16** [comment]
@dimasciput @jeremyshelton 
Any solution for this issue? The user sent another email this morning asking for an update. Thanks!

**Comment by dimasciput** [comment]
@Aneri16 because this is very large data, it will take a long time to process. Let me try exporting it manually, and send the file to you.

**Comment by Aneri16** [comment]
@dimasciput Okay thank you

**Comment by dimasciput** [comment]
@Aneri16 @jeremyshelton apparently I need to create a script for this since the data is just too big, it will take me like 1-2 day just for this. Do they really need it now?

**Comment by Aneri16** [comment]
@dimasciput the user is hoping to use the data for his PhD research as soon as possible but I can explain that you are working on it and that it may take a while

**Comment by jeremyshelton** [comment]
@dimasciput the user has contacted us again. He still cant download the CSV. What he wants is to download a csv file of all the SASS records. This should be possible, right?
@helendallas @timlinux

**Comment by dimasciput** [comment]
it's not unfortunately, it's too big that's why we paginate the data in the dashboard. check here : http://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22,%22B%22,%22E%22,%22C%22,%22D%22]&rank=&siteIdOpen=&orderBy=name

I will need to create a script to generate all data to csv and manually send the file, this will take me around 3-4 hours.

**Comment by helendallas** [comment]
@dimasciput 
Given the time this will take, I will provide an old spreadsheet to the user so that you dont use up your time on this Dimas.
@Aneri16 please take note

**Comment by jeremyshelton** [comment]
OK thank @dimasciput for the update and @helendallas for addressing the request...
