### ISSUE TITLE
FBISv4 Big picture ticket 1: Algae dashboards and forms 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1857]
- Algae dashboards should be identical to the fish and invert taxon ones
- The additional information captured for algae (such as Chlorophyll a, and Ash Free Dry Mass (AFDM), and Autotrophic Index (AI)) will be uploaded in the spreadsheet with the algae data and served via the CSV download
- The algae form and drop-down options are slightly different to the others. See ticket #1655 for details. Dropdown spreadsheet available here: https://www.dropbox.com/s/jkuy2u970it4y20/Forms%20Dropdown%20options_Final%202019%2010%2004.xlsx?dl=0
- Here is the algae form - the only differences from the fish and invert taxon forms can be found at the Botton section:
<img width="609" alt="Screenshot 2020-01-29 at 13 57 13" src="https://user-images.githubusercontent.com/44292029/73354870-68943c80-429f-11ea-85ff-556fd6e4de49.png">
@helendallas @Aneri16 @philipfrenzel

**Comment by dimasciput** [comment]
@jeremyshelton can you tell me the workflow for the biomass data? Is it fixed table or not?

**Comment by jeremyshelton** [comment]
@dimasciput in the Algal biomass section please change the words 'Sampling location' to 'Sampling method'. The user will simply use the drop-downs to select sampling method, manually enter their measurement and then select the curation process (Frozen is the only option for biomass). Autotrophic index is a value manually entered by the user. Does that help? I am not sure what a fixed table means...?
