### ISSUE TITLE
FBISv4 Big picture ticket 2: Upload new data for algae, inverts, SASS and fish

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1858]
We will have the following data ready for upload for v3:
- Algae data: approx 6000 records (by 19 Feb 2020)
- Fish data: approx 6000 national non-native fish records (by 19 Feb 2020)
- Invert taxon data: new batch of data (25,000 new taxon records) (by 19 Feb 2020) @helendallas estimate of numbers of records?

@timlinux

**Comment by jeremyshelton** [comment]
@dimasciput new batch of fish data incoming Friday. Approx 2500 records, mostly Non-native species. We will let you know when it is ready...

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux the algae and fish data are in the [dropbox folder](https://www.dropbox.com/sh/3kcxib6ibykh90s/AACBy4-QQG0w03Unmdy0i-_Ba?dl=0) and ready for ingestion.  

@dimasciput for the fish data, we have just included a spreadsheet with the new data (i.e. excluding the data that we ingested last time). Is this OK, or would you prefer us to create a new sheet with the old and new data combined?

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas @timlinux 

What is the different between analyst and collector? Currently we don't have analyst in our system, where we should put this? 

![image](https://user-images.githubusercontent.com/1979569/75766713-2bc2d600-5d74-11ea-8da7-cd290c750014.png)

And I assume the institute is the institute of the user? Not the data? So I don't think I need this, because you can change it yourself in your profile page.

**Comment by helendallas** [comment]
@dimasciput 
It is important for quality to know who did the analysis and where they were based. So for algae these are two separate fields needed. 

The Analyst - is the person that did the analysis (not necessarily the same as the collector)
The Institute - is specific to the analyst - i.e. where they were based. 

We could combine these to have Analyst, Institution
so Liesl Phigland, Dept of Biological Science, UCT.


Please can you incldue both of these for algae.

**Comment by dimasciput** [comment]
@helendallas Ok, I will add a new field to collection record model

**Comment by dimasciput** [comment]
@helendallas do we need this abiotic data? 
![image](https://user-images.githubusercontent.com/1979569/75770024-be19a880-5d79-11ea-9a43-8e19282bd6b9.png)

**Comment by helendallas** [comment]
@dimasciput 
We spend time this morning revising the files to make it consistent with the other data, especially abiotic.

Here is the new file link:
https://www.dropbox.com/s/5nwze5e837o318u/CFR%20Algae%20Data%20for%20FBIS_final%20template_FINAL%20DATA.xlsx?dl=0

Sorry  -hope we havent wasted your time :(

**Comment by helendallas** [comment]
@dimasciput Apologies, A new CSV was not created. I will do  now and share

**Comment by jeremyshelton** [comment]
**Fish data update**
In today's chat with Dimas we decided that we will combine all the fish data into a single sheet, with all errors addressed and referencing standardised. We will aim to have this new .csv ready by the end of the week. @dimasciput can then delete all the fish data previously ingested, and replace it with this new file. We will aim to have this ready and shared by the end of the week, so Dimas you can focus on the inverts and algae, and hold off on the fish data for now. 
@dimasciput @Aneri16 @timlinux @helendallas

**Comment by helendallas** [comment]
@dimasciput 

I hope the fish data is now finally fixed and ready for ingestion.  It is here:
https://www.dropbox.com/sh/ap3m87jd53un46w/AAAZ0C368jC_jSIk7R_ZZAXsa?dl=0

File: SA fish & non-native combined for FBIS 13_3_2020.csv

Please ingest and confirm once done so that Aneri and jeremy can do some checking, thanks
@Aneri16 @jeremyshelton

**Comment by helendallas** [comment]
I am closing this ticket as each module has been separated into its own ticket. 

Please see
Algae: #1945 #1983 
Invertebrates:  #1935 #1937 
Fish: #2013
