### ISSUE TITLE
FBISv4 Big picture ticket 3: Adding 3 ’living layer’ options 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1859]
We would like to give the user the option to view spatial data from other online resources on the FBIS map, and then if the are interested an option to click a link that takes them to those data. 
- MiniSASS (http://www.minisass.org/en/): aquatic invertebrates
- iNaturalist (https://www.inaturalist.org): freshwater fish and aquatic invertebrates
- Gauging weirs (Mike Silberbauer): See ticket #891

@helendallas @Aneri16

**Comment by timlinux** [comment]
So when clicking on a guaging station we need to define what will be shown. We could do an in-place popup with guaging stats:

http://inwards.award.org.za/app_json/unverified_timeseries.php?stations=B7H015,B7H007&ed=2019-12-01-2019&sd=2019-12-31&type=0

**Comment by timlinux** [comment]
So here is our proposed plan to deal with this in a nice generic way:

1) All the 'living layers' are just added to the layers list as per usual
2) When the user clicks on the map, we do a GetFeatureInfo (format HTML) request for each layer that is enabled
3) We display the results underneath the sidepanel charts

Data specific notes:

# MiniSASS
For minisass we can simply hook into their published layers (someone should reach out to them about this). They already return an html formatted result:

![image](https://user-images.githubusercontent.com/178003/75859262-97975400-5df1-11ea-8386-e999b4b63605.png)

The WMS URL For MiniSASS is :

http://minisass.org:8080/geoserver/wms?LAYERS=miniSASS%3Aminisass_observations

Note: No data will be added to the BiologicalCollectionRecords table from miniSASS - this is a display only activity.


# Flow Guages

@NyakudyaA to publish the flow guages layer we received from Hugo - attached here:

[FlowGuages.zip](https://github.com/kartoza/django-bims/files/4286117/FlowGuages.zip)

When he publishes them they should be colour coded according to 'inwardsBoo' (InWards Boolean) attribute. Blue if true, red if false. For True entries the GFI should return an html snippet which is a link to a direct CSV download from Hugo's service. In future we can update the gauges layer when Hugo has backfilled the data for other provinces / WMA's. The GFI should also include the guage ID, starting date, place name and water body.

![image](https://user-images.githubusercontent.com/178003/75859675-56ec0a80-5df2-11ea-99a2-ff04e4ee15e6.png)

# iNaturalist

**Comment by timlinux** [comment]
Some more on iNaturalist:

https://api.inaturalist.org/v1/docs/#!/Observation_Tiles/get_points_zoom_x_y_png

Their newer API supports a map tiling request with many filter options. You can test it in QGIS by creating an XYZ layer like this:

https://api.inaturalist.org/v1/points/{z}/{x}/{y}.png


![image](https://user-images.githubusercontent.com/178003/75860848-65d3bc80-5df4-11ea-9bb3-f5e0dae9a38f.png)


We would need to figure out how to filter the layer to show only aquatic species and how to do equivalent of GFI requests.

**Comment by timlinux** [comment]
As another approach for iNaturalist we could have it use these API parameters:

![image](https://user-images.githubusercontent.com/178003/75861036-b519ed00-5df4-11ea-8523-cfff3339a608.png)


to pull in records close to the clicked point on the map using https://api.inaturalist.org/v1/docs/#!/Observations/get_observations and passing it the lat/lon/radius to filter observations to those close to the clicked point.

![image](https://user-images.githubusercontent.com/178003/75861252-0aee9500-5df5-11ea-8f0e-356a17ba52be.png)

**Comment by jeremyshelton** [comment]
Thanks Tim, 

The plan sounds good to me. Looking great for MiniSASS and flow stations. 

Your **points 1 and 2** sound good. 

**Point 3**
I wonder if we should somehow distinguish these layers from the rest of the layers that we are already serving? These give the user a different kind of functionality, and I worry that they might just 'get lost' in the layers list if we just somma put them there?

**MiniSASS**
@helendallas has already reached out to them and, in principal, they are supportive of FBIS hooking on and serving the data. Do you think we should look at a formal MOU?

**iNat**
So, we are already pulling and serving 'research grade' iNat data via GBIF. Do, this would not be adding the non-research grade data catalogue into the mix. @helendallas what are your thoughts on this, particularly WRT the inverts and their terrestrial and aquatic stages?

**Comment by helendallas** [comment]
@timlinux @jeremyshelton 
Mini-SASS - I already spoke to Mark Graham of GroundTruth - he is very happy to link MiniSASS with FBIS...loves FBIS!  Tim - will it be helpful if I send an email to him, or can the linking be done in the backend since kartoza did the initial development as far as I know....

DWS (Flow and Water quality) gauging stations -  sounds good

INaturalist - as I chatted to Jeremy about, GBIF serves all invertebrate data – no differentiation of terrestrial or aquatic. So that means for all taxa that have an aquatic phase , i.e. 90%, we will also get adult records, even if they have not been recorded in the aquatic phase.
 
This is both a blessing and a curse. 
- Blessing – because many aquatic stages cannot be identified beyond family or genus…..having insight into the adults is useful.
- Curse – the presence of adult/terrestrial taxa does not indicate anything about the “health of the river”. And some adults can fly some distance.

Jeremy's response: So I guess we have two options: (1) do not serve GBIF invert data, or (2) we serve it, but make it very clear that these records represent a mix of aquatic and terrestrial phases of those taxa. I would favour option 2, and then its up to the user how they want to use and interpret the data....from a freshwater biodiversity data perspective there is still value in those data.

I agree to serve the data but make it clear that invert includes aquatic and terrestrial phase.

For now I may be leaning to limit iNaturalist to fish????? given the complexity? OR Perhaps for now we park this......since we already pull down the research grade fish data.

**Comment by NyakudyaA** [comment]
@timlinux cc @jeremyshelton  I have already published the flow gauges 
![gauges](https://user-images.githubusercontent.com/2510900/75970823-96d9ed00-5ed9-11ea-9403-a7e55581699a.png)

Should I add it to the layer list? Is there any preference for the symbol ie icon for gauges

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA looks great!

@timlinux @helendallas @dimasciput I wonder if we should think about putting these layers in their own tab (perhaps below the layer selector) called '3rd party data' or something like that, because they are are different to both Layers and Filters? 

@helendallas GBIF approach sounds good 👍 We can make it clear that the aquatic and terrestrial 
taxa are mixed in the layer description...

@timlinux what are your thoughts on the iNat stuff? The map you showed in slack - was that for all non-research grade fish? Will this be a mission to include?

**Comment by timlinux** [comment]
Further discussion with FRC as of 18 March 2020:

1) Agreed to postpone iNaturalist data for the future
2) Remove the validate icon in the toolbar 
3) Remove the add point icon in the toolbar
4) Add a new icon below layer selector for 'Live layers' and add iNaturalist and minSass as options there
5) Tidy up the validation menu entries as below:

Validation
------------
Validate Records
Validate Data

**Comment by timlinux** [comment]
And one other thing discussed was to ask Hugo if we can get water quality as well as flow data for the guaging stations. Make available as CSV similar to proposed for the flow stations.

**Comment by jeremyshelton** [comment]
@timlinux are you going to check this with Hugo, or should we?

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput we still need a new icon below layer selector called '3rd party data' which should include MiniSASS and Flow Guages, as per Tim's point 4 above. 
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton I sized this ticket to 5, because it would take 3-4 hours to implement it. And a lot of my time has already been spent re-ingesting the data. Just FYI.

**Comment by timlinux** [comment]
@dimasciput for Water Quality can you please add:

- [ ] InWARDS Water Quality as a new layer
- [ ] Grab the data for sites from Inwards and show as a GeoJSON layer
- [ ] When clicking a point from that layer show in the side panel like MiniSASS basic site info
- [ ] Have a link to grab the data for the site using url form of http://inwards.award.org.za/app_json/wq_csv.php?id=90407 where last param is site id - using the link will download a CSV
- [ ] Have a link in the side panel that takes you to InWARDS project page in a new tab

**Comment by jeremyshelton** [comment]
Looking good @timlinux @dimasciput 
Can we add an 'explanation in a drawer' below each of these, like we have for other layers, to tell the user exactly what data these are? 
Also, in the overview panel maybe 'Data shared with permission from http://award.org.za/', instead of 'taken' and that text could be a bit bigger. 

<img width="1440" alt="Screenshot 2020-05-20 at 09 25 09" src="https://user-images.githubusercontent.com/44292029/82417941-9d114b80-9a7c-11ea-9d13-62b088665ccc.png">

**Comment by dimasciput** [comment]
@jeremyshelton updated

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
It's a bit too long. Please replace it with:

MiniSASS is a citizen science tool which can be used by anyone to monitor the health of a river. The data are served with permission from http://www.minisass.org/en/, and further information about the tool is available via this website.

Thanks
