### ISSUE TITLE
FBISv4 Big picture ticket 4: Adding three new spatial layers

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1860]
- PES: see ticket #1807
- RMU: see ticket #1856
- Land use: @NyakudyaA  - are the LADA land use classes which we are currently serving the most up-to-date layer?

@timlinux @helendallas @Aneri16

**Comment by NyakudyaA** [comment]
@jeremyshelton The Lada land use is the most current layer we have, it comes from the following URL
http://www.sasdi.net/metaview.aspx?uuid=6ae256e56930a9d325f963592325211c If you have any other layer please indicate so

**Comment by helendallas** [comment]
I am closing this ticket as issues dealt with in individual tickets
