### ISSUE TITLE
FBISv4 Big picture ticket 5: Add validation rules for new data

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1861]
- @helendallas  to check phys-chem parameters from bio base, and advise on which can be used
- @helendallas @jeremyshelton  need to provide ranges for fish (Regional and catchment endemics) and inverts (regional endemics)
- We probably need to add some broad-level spatial rules e.g. ocean, beyond SA etc

@dimasciput @Aneri16

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/74322562-0564d880-4d7c-11ea-834c-f9a75f4409fb.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/74322673-30e7c300-4d7c-11ea-9621-02996f54d344.png)

Note pH is just an example we should constrain all physchem value ranges in this way

**Comment by timlinux** [comment]
Scope is to form only, batch uploader not....for now

**Comment by jeremyshelton** [comment]
@helendallas the ranges would correspond to the endemism column, but would need another column defining 'where' it is endemic to? All other species = SA distribution.

**Comment by helendallas** [comment]
@dimasciput 
Here is the spreadsheet of min and max values based on Biobase and Rivers Database
[Abiotic Data Variables .xlsx](https://github.com/kartoza/django-bims/files/4198019/Abiotic.Data.Variables.xlsx)

**Comment by helendallas** [comment]
@dimasciput I will provide an new file for this . Please wait for now

**Comment by timlinux** [comment]
Discussion of 18 March 2020:

@jeremyshelton and @helendallas to discuss what catchment level to use and revert to @dimasciput

**Comment by jeremyshelton** [comment]
Let's roll with primary catchment level, unless @helendallas feels strongly otherwise?

**Comment by helendallas** [comment]
I agree. Primary catchment level makes the most sense

**Comment by jeremyshelton** [comment]
👍

**Comment by dimasciput** [comment]
Please test it in testing after the ingestion done

**Comment by jeremyshelton** [comment]
OK will do. Thanks @dimasciput

**Comment by helendallas** [comment]
@dimasciput For the Validation ranges for Abiotic variables - 

At the moment if you add a value greater than the range maximum it defaults to the maximum. What is preferred here is to alert the user to the fact that they have added a value greater than the maximum range, and ask whether they still want to add it.

If this is an easy fix, then please action, if not then lets hold over for Version 5. Please just let me know and I will create a new ticket.

**Comment by helendallas** [comment]
@dimasciput 
As per text above, please indicate how long it will take to implement. If this is an easy fix, then please action, if not then lets hold over for Version 5 or RBIS. Please just let me know and I will create a new ticket.

At the moment if you add a value greater than the range maximum it defaults to the maximum. What is preferred here is to alert the user to the fact that they have added a value greater than the maximum range, and ask whether they still want to add it.

If this is an easy fix, then please action, if not then lets hold over for Version 5. Please just let me know and I will create a new ticket.

So, If a user adds a value less than or greater than our ranges, they get a pop up message saying:

**The value you have entered is outside of our range, please confirm if this is correct**

Option to select **Accept** or **Revise**

Then if they say Accept, then number is accepted, if they select Revise, then they correct the value.

Also the minimum value should not be the **default**. It should rather be **blank**.
![Screenshot_2020-04-21 FBIS Abiotic Form](https://user-images.githubusercontent.com/45286876/79842709-7ac2da00-83b9-11ea-8d08-ad12414e9ee6.png)

**Comment by dimasciput** [comment]
@helendallas added a warning for now, I hope this is enough for this version : 
![image](https://user-images.githubusercontent.com/1979569/81048931-733a1f80-8ee7-11ea-9783-0a67e9a13db4.png)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
@helendallas I think this is fine. Are you happy with that?

**Comment by helendallas** [comment]
@dimasciput I am happy with this. I will shift to RBIS as it is important for RBIS too.

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput I am moving this to done and labelling as checked by FRC.
