### ISSUE TITLE
FBISv4 Big picture ticket 7: Final background layer

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1863]
- The new base layer is one of the key features for v3, and is already underway in ticket #1519
- Admire is already developing this
- It includes rivers, with increasing level of detail as the user zooms in
- Can we also include dams in this layer?

@timlinux @helendallas @Aneri16

**Comment by NyakudyaA** [comment]
The current map is visible from https://maps.kartoza.com/kartoza/

**Comment by dimasciput** [comment]
@NyakudyaA is it ready to use now?

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA, looking nice!

A few questions:
1. What are the different polygons?
2. What are the black line boundaries?
3. Personally, I would want to see some landscape relief, clear rivers (scales by thickness, like on the google earth SA river layer, with labels?) and clear dams (also labelled). 
4. No river names?
5. Rivers seem quite faint?
6. Names are double if one zoomed in. 
<img width="186" alt="Screenshot 2020-03-01 at 12 59 15" src="https://user-images.githubusercontent.com/44292029/75624410-84e80980-5bbc-11ea-86b0-ec247e66dadb.png">

...overall looking good, but I would like to see the freshwater ecosystems (rivers, dams and their lables) stand out a bit more clearly - its a freshwater platform, after all? Those are just some initial thoughts...@timlinux @helendallas ?

**Comment by NyakudyaA** [comment]
> Thanks @NyakudyaA, looking nice!
> 
> A few questions:
> 
>     1. What are the different polygons?
National protected areas

> 
>     2. What are the black line boundaries?
Admin boundaries - Provincial, district etc
> 
>     3. Personally, I would want to see some landscape relief, clear rivers (scales by thickness, like on the google earth SA river layer, with labels?) and clear dams (also labelled).
> 
>     4. No river names?
I have added them and some of them will only show when zoomed in close to reduce clatter
> 
>     5. Rivers seem quite faint?
Will increase their thickness
> 
>     6. Names are double if one zoomed in.
I will check it and rectify it.
> 
> 
> <img alt="Screenshot 2020-03-01 at 12 59 15" width="186" src="https://user-images.githubusercontent.com/44292029/75624410-84e80980-5bbc-11ea-86b0-ec247e66dadb.png">
> 
> ...overall looking good, but I would like to see the freshwater ecosystems (rivers, dams and their lables) stand out a bit more clearly - its a freshwater platform, after all? Those are just some initial thoughts...@timlinux @helendallas ?

I have update it @jeremyshelton 
![rivers](https://user-images.githubusercontent.com/2510900/75625539-caf69a80-5bc7-11ea-8bbe-9986bfa9b99f.png)

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA Looking good! A few more moments:

1. Could you include province names on the map
2. Thanks for adding the river lables. Any way to make them a little clearer?
<img width="481" alt="Screenshot 2020-03-02 at 10 54 00" src="https://user-images.githubusercontent.com/44292029/75660776-d8b62980-5c74-11ea-9203-fe813f68c260.png">

3. River names disappear when zoomed in?
<img width="183" alt="Screenshot 2020-03-02 at 10 54 13" src="https://user-images.githubusercontent.com/44292029/75660789-de137400-5c74-11ea-8e8f-8e7b3820c0d1.png">

4. Could you include Dam names when zoomed in?

@helendallas thoughts?

**Comment by NyakudyaA** [comment]
> Thanks @NyakudyaA Looking good! A few more moments:
> 
>     1. Could you include province names on the map

I have added them. Will update the map later during the night

![labels-prov](https://user-images.githubusercontent.com/2510900/75977878-fa6a1780-5ee5-11ea-9bd4-65c2a9d88613.png)

> 
>     2. Thanks for adding the river labels. Any way to make them a little clearer?

![changed-label-position](https://user-images.githubusercontent.com/2510900/75977987-356c4b00-5ee6-11ea-8604-70c0b721ea28.png)

> 
> 
> <img alt="Screenshot 2020-03-02 at 10 54 00" width="481" src="https://user-images.githubusercontent.com/44292029/75660776-d8b62980-5c74-11ea-9203-fe813f68c260.png">
> 
>     1. River names disappear when zoomed in?

Not anymore,  they are two types of river layers. DWA rivers and NGI rivers. for a small scale, I show the DWA rivers but for a large scale, I show the ngi rivers. Some of the rivers do not have names according to the DB
> 
> 
> <img alt="Screenshot 2020-03-02 at 10 54 13" width="183" src="https://user-images.githubusercontent.com/44292029/75660789-de137400-5c74-11ea-8e8f-8e7b3820c0d1.png">
> 
>     1. Could you include Dam names when zoomed in?

Have added them
> 
> 
> @helendallas thoughts?

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA I see you have added the new base map to the live site. Can we rather please finalise the new base map and then only add once complete? We still need to refine it quite a bit, and get input from @helendallas...

**Comment by jeremyshelton** [comment]
@timlinux @NyakudyaA @dimasciput I know you guys are keen on developing your own custom base layer for the FBIS. But as it stands, using google earth with the DWS rivers layer added (with lables) is in my opinion a far superior user experience to what's currently on offer on the FBIS. 

User experience is key. 

@timlinux I know you had some reservations about using google earth layers, but would this not be a way to get a great map with basic features and rivers  for users to explore with relative ease? Don't mean to open a can of worms, but lets rather revisit this now that further down the line. 
<img width="1440" alt="Screenshot 2020-03-06 at 07 09 49" src="https://user-images.githubusercontent.com/44292029/76054667-1d460b80-5f7a-11ea-852e-dd706a5a1815.png">

**Comment by helendallas** [comment]
@jeremyshelton @timlinux @NyakudyaA @dimasciput 

I like the option of the cleaner less busy layer given we have the option to select a Bing Satellite hybrid  -and if you select rivers and dams, then you have the river network.

![Screenshot_2020-03-06 FBIS Map](https://user-images.githubusercontent.com/45286876/76065633-a9fdc300-5f94-11ea-8e83-f5cc042462e0.jpg)


I don't know the pros and cons of google earth versus Bing. 

Happy to discuss further but reckon for now, what we have is fine. @jeremyshelton  please select Bing and Rivers and Dams.

One comment for @NyakudyaA @dimasciput ?
Can Rivers layer and Dams layer be moved up the Layer Selector to immediately below Sites.
Also not sure what River Labels layer adds, just seems to duplicate river names - please check.

**Comment by NyakudyaA** [comment]
> @jeremyshelton @timlinux @NyakudyaA @dimasciput
> 
> I like the option of the cleaner less busy layer given we have the option to select a Bing Satellite hybrid -and if you select rivers and dams, then you have the river network.
> 
> ![Screenshot_2020-03-06 FBIS Map](https://user-images.githubusercontent.com/45286876/76065633-a9fdc300-5f94-11ea-8e83-f5cc042462e0.jpg)
> 
> I don't know the pros and cons of google earth versus Bing.

Google satellite vs bing offers the same satellite but the main difference is which one has more recent data. Using these services which are not free have a limit on the number of hits the website has and after that you will need to start paying to use their service
> 
> Happy to discuss further but reckon for now, what we have is fine. @jeremyshelton please select Bing and Rivers and Dams.
> 
> One comment for @NyakudyaA @dimasciput ?
> Can Rivers layer and Dams layer be moved up the Layer Selector to immediately below Sites.

Yes, You can move them or remove any layer from the admin page 
https://freshwaterbiodiversity.org/admin/bims/nonbiodiversitylayer/
> Also not sure what River Labels layer adds, just seems to duplicate river names - please check.

The river labels were put there just for cases where the user is using a base map ie google earth and it has rivers that are not labeled. This can be removed if you do not need it.

I am going to improve the labels for the rivers so that they are clearly visible

**Comment by helendallas** [comment]
@NyakudyaA Wonderful thanks. Useful to know re order. Please add to the Admin manual

**Comment by jeremyshelton** [comment]
@helendallas OK cool. You raise some good points. 

@NyakudyaA thanks for developing the custom FBIS base map. Lets try get it as clean, clear and user-friendly as possible!

One thing that might help is to have clearer land and provincial boundary lines?
<img width="839" alt="Screenshot 2020-03-07 at 22 38 42" src="https://user-images.githubusercontent.com/44292029/76152108-6f934380-60c4-11ea-9d34-7bca66fc9afd.png">

Also, perhaps showing a little terrain relief or ocean different colour might help orientate the user a bit better? Check out WWF's Water Source areas base-map as an example:

<img width="867" alt="Screenshot 2020-03-07 at 19 23 50" src="https://user-images.githubusercontent.com/44292029/76152149-d0228080-60c4-11ea-96c3-3e566cd33631.png">

**Comment by NyakudyaA** [comment]
> @helendallas OK cool. You raise some good points.
> 
> @NyakudyaA thanks for developing the custom FBIS base map. Lets try get it as clean, clear and user-friendly as possible!
> 
> One thing that might help is to have clearer land and provincial boundary lines?
> <img alt="Screenshot 2020-03-07 at 22 38 42" width="839" src="https://user-images.githubusercontent.com/44292029/76152108-6f934380-60c4-11ea-9d34-7bca66fc9afd.png">

I have added them . Will update the map tomorrow.
> 
> Also, perhaps showing a little terrain relief or ocean different colour might help orientate the user a bit better? Check out WWF's Water Source areas base-map as an example:

Please take a look at the base map on https://maps.kartoza.com/kartoza/ and choose the relief basemap. I could add that if you want and change the colors to your preference 
> 
> <img alt="Screenshot 2020-03-07 at 19 23 50" width="867" src="https://user-images.githubusercontent.com/44292029/76152149-d0228080-60c4-11ea-96c3-3e566cd33631.png">
> 
> Just throwing around some ideas - don't all necessarily need to be implemented :)

Definitely the map will be improved by user inputs. We will have many iterations before the final agreed cartography

**Comment by jeremyshelton** [comment]
Great, thanks @NyakudyaA. 

That makes sense. 

A few further suggestions and requests:
- Hill shade map looks good & should help users navigate around the country and find rivers more easily. Perhaps a version with a slightly more earthy or muted colour scheme so the sites and river names etc stand out well against it?
- Can we see major river names (e.g. Breede, Berg, Orange etc) when zoomed out? 
- Can we increase the quality of city names text (its still quite pixelated). 
- Can we add names of smaller towns (e.g. Stellenbosch) and suburbs (e.g. Kuils River) so that they appear when a user zooms in? This should also help orientate the user.
- Can we add a scale bar?

Then, for #1931 (User experience: navigating map and visualising spatial layers) is this something to work on with @ or @NyakudyaA?

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @timlinux any further thoughts on this?

**Comment by NyakudyaA** [comment]
> @dimasciput @NyakudyaA @timlinux any further thoughts on this?

Hi, @jeremyshelton I will add the hillshade and other changes you suggested above.

**Comment by jeremyshelton** [comment]
@NyakudyaA OK great - shout when you're ready for us to have a look. You welcome to join the chat at 11h00 today if you'd like to discuss any aspects of this with the group :)

**Comment by jeremyshelton** [comment]
> Great, thanks @NyakudyaA.
> 
> That makes sense.
> 
> A few further suggestions and requests:
> 
> * Hill shade map looks good & should help users navigate around the country and find rivers more easily. Perhaps a version with a slightly more earthy or muted colour scheme so the sites and river names etc stand out well against it?
> * Can we see major river names (e.g. Breede, Berg, Orange etc) when zoomed out?
> * Can we increase the quality of city names text (its still quite pixelated).
> * Can we add names of smaller towns (e.g. Stellenbosch) and suburbs (e.g. Kuils River) so that they appear when a user zooms in? This should also help orientate the user.
> * Can we add a scale bar?
> 
> Then, for #1931 (User experience: navigating map and visualising spatial layers) is this something to work on with @dimasciput or @NyakudyaA?

Hi @NyakudyaA how close are we to ticking off the above points raised for finalising the base map?

**Comment by jeremyshelton** [comment]
@NyakudyaA keen to get the base layer finalised. Do you think we can wrap it up this week?

**Comment by NyakudyaA** [comment]
> @NyakudyaA keen to get the base layer finalised. Do you think we can wrap it up this week?

Yes, will work on it thursday

**Comment by jeremyshelton** [comment]
Great. Thanks.

**Comment by jeremyshelton** [comment]
@NyakudyaA have you had a chance to get to this yet?

**Comment by NyakudyaA** [comment]
> @NyakudyaA have you had a chance to get to this yet?

Yes, I haven't pushed to the server yet but hopefully today.
![map](https://user-images.githubusercontent.com/2510900/79322032-896a4680-7f0c-11ea-9609-3df9cf17876b.png)

**Comment by jeremyshelton** [comment]
OK. Thank you. 

@dimasciput @NyakudyaA @timlinux 

We are busy testing the site, and having the base map for this will be very helpful.

Please make sure that the following have been implemented so that we don't have to do it again:

1. - Hill shade map looks good & should help users navigate around the country and find rivers more easily. Perhaps a version with a slightly more earthy or muted colour scheme so the sites and river names etc stand out well against it?
2. - Can we see major river names (e.g. Breede, Berg, Orange etc) when zoomed out?
3. - Can we increase the quality of city names text (its still quite pixelated).
4. - Can we add names of smaller towns (e.g. Stellenbosch) and suburbs (e.g. Kuils River) so that they appear when a user zooms in? This should also help orientate the user.
5. - Can we add a scale bar?

Thank you

**Comment by NyakudyaA** [comment]
> OK. Thank you.
> 
> @dimasciput @NyakudyaA @timlinux
> 
> We are busy testing the site, and having the base map for this will be very helpful.
> 
> Please make sure that the following have been implemented so that we don't have to do it again:
> 
>     1. * Hill shade map looks good & should help users navigate around the country and find rivers more easily. Perhaps a version with a slightly more earthy or muted colour scheme so the sites and river names etc stand out well against it?

Can you provide a color ramp you need me to use if your have a preference.
> 
>     2. * Can we see major river names (e.g. Breede, Berg, Orange etc) when zoomed out?

How do we define major river names. Do you have a list or should I do a quick search from google
> 
>     3. * Can we increase the quality of city names text (its still quite pixelated).

Will be solved
> 
>     4. * Can we add names of smaller towns (e.g. Stellenbosch) and suburbs (e.g. Kuils River) so that they appear when a user zooms in? This should also help orientate the user.

We can do this.
> 
>     5. * Can we add a scale bar?

@dimasciput can add this in the front end
> 
> 
> Thank you

**Comment by jeremyshelton** [comment]
**Colour ramp**: can we do one like this: http://www.journeyofwater.co.za/watersourceareas

**Major river names**: @helendallas can you please assist @NyakudyaA with where to find major river names to show when zoomed out on the base map? Breede, Berg, Olifants, Doring, Palmiet...etc. Then, when the user zooms in they will get all the river names.

**Other issues**: 
Aside from the rivers and their names, we only want 
-province boundaries (I still don't see them)
-cities and towns 
-dams and dam names
- @helendallas  anything else? 

When testing the current map in the Kartoza map gallery, I am seeing several issues:
- river names disappear
- town names become unclear
- colourful polygons have not been removed (they need to be)

![Screenshot 2020-04-17 at 13 00 16](https://user-images.githubusercontent.com/44292029/79562694-ba34b200-80ab-11ea-8423-c2beaaab53e1.png)

-then wen one zooms in all the way the map becomes un-navigable (at least for me). The satellite is super-cluttered with heaps of features and no legend. 

![Screenshot 2020-04-17 at 13 01 52](https://user-images.githubusercontent.com/44292029/79562709-c02a9300-80ab-11ea-9dc1-5c309a9907b3.png)

-I suggest we remove the satellite and just have the relief shade (or white map) with clear rivers, river names, dams, dam names, cities, towns, provinces and boundaries, @helendallas anything else?

@NyakudyaA @timlinux @dimasciput

**Comment by helendallas** [comment]
I find at the lowest resolution the dot showing the site is very hard to see. Maybe the size can be increased or the colour enhanced to increase visibility

I dont offhand know where to harvest a list of major river names, perhaps one can use rivers with an order >5

**Comment by timlinux** [comment]
Ok so summary from our call on 22 April 2020:


![image](https://user-images.githubusercontent.com/178003/79972336-b6c76f00-848d-11ea-8cd6-83fe4fe2416e.png)

At this level we should see majror river names, major places, **relief** and provinces with labels

We need damn labels on the dams :-)

Make  the town labels a couple of points larger

When zooming in, swap in the NGI Imagery layer.

Make the sites stand out more when you are zoomed in e.g.

![image](https://user-images.githubusercontent.com/178003/79973010-baa7c100-848e-11ea-8af4-2c17f2910644.png)

**Comment by timlinux** [comment]
Also please make country and province boundaries bolder.

**Comment by jeremyshelton** [comment]
@NyakudyaA when we zoom in close on the base layer, would it be possible to show these rivers (from the 'rivers' layer you uploaded for FBIS)

<img width="1440" alt="Screenshot 2020-04-22 at 15 57 20" src="https://user-images.githubusercontent.com/44292029/79991179-4252f700-84b2-11ea-9bd3-757c81398100.png">

rather than these ones (very fine network currently shown on your base layer)?

<img width="1440" alt="Screenshot 2020-04-22 at 15 58 02" src="https://user-images.githubusercontent.com/44292029/79991076-27808280-84b2-11ea-88af-759127f5d7be.png">
<img width="1440" alt="Screenshot 2020-04-22 at 15 57 20" src="https://user-images.githubusercontent.com/44292029/79991082-294a4600-84b2-11ea-913b-f96fcb6c3853.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton I have uploaded a sample project with some customisations
https://maps.kartoza.com/kartoza/

Can you comment on it.

**Comment by NyakudyaA** [comment]
> @NyakudyaA when we zoom in close on the base layer, would it be possible to show these rivers (from the 'rivers' layer you uploaded for FBIS)
> 
> <img alt="Screenshot 2020-04-22 at 15 57 20" width="1440" src="https://user-images.githubusercontent.com/44292029/79991681-dde46780-84b2-11ea-8fd5-f1cf0012db99.png">
> 
> rather than these ones (very fine network currently shown on your base layer)?
> 
> <img alt="Screenshot 2020-04-22 at 15 58 02" width="1440" src="https://user-images.githubusercontent.com/44292029/79991076-27808280-84b2-11ea-88af-759127f5d7be.png">
> 
> @helendallas

The finer scale rivers are for showing when you are zoomed in quite close. For navigation, it makes sense to include them. Anyway I have excluded them for now

**Comment by NyakudyaA** [comment]
Another issue is that the color ramp for the hillshade is difficult to extract from the image in the link

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA, I think it's getting there. 

Some comments on the current version: 
1. Rivers (and labels) not clearly visible (don't pop out enough) against relief map and NGI, both when zoomed out and in. Maybe make relief hillside darker, and/or rivers bolder? (or make relief lighter and rivers darker?)
<img width="616" alt="Screenshot 2020-04-29 at 06 13 18" src="https://user-images.githubusercontent.com/44292029/80560300-b3c60480-89e0-11ea-8e96-b3600e110324.png">

2. Looks like there are two different river layers showing at once? I agree with your suggestion to rather just use the finer blue ones. Labels not readable (too small, pixelated, obscured by the rivers themselves)
<img width="318" alt="Screenshot 2020-04-29 at 05 53 37" src="https://user-images.githubusercontent.com/44292029/80559789-03a3cc00-89df-11ea-9ef1-d646d8e08a08.png">

3. Dams: they  disappear when zoomed in, have no names, and are a different colour to the rivers?
<img width="808" alt="Screenshot 2020-04-29 at 05 53 09" src="https://user-images.githubusercontent.com/44292029/80559798-08688000-89df-11ea-939e-26b059be92a3.png">

5. Some strange names. Also not all symbols have labels? Also, not all towns have icons?
<img width="100" alt="Screenshot 2020-04-29 at 05 54 06" src="https://user-images.githubusercontent.com/44292029/80560165-3d290700-89e0-11ea-9ef8-f1462c31e4d4.png">
![Uploading Screenshot 2020-04-29 at 06.14.13.png…]()



6. Province boundaries not clear. 
<img width="800" alt="Screenshot 2020-04-29 at 06 10 47" src="https://user-images.githubusercontent.com/44292029/80560159-369a8f80-89e0-11ea-8576-613ec0b40b9a.png">


7. SA outline looks smudgy/pixelated
<img width="287" alt="Screenshot 2020-04-29 at 05 54 42" src="https://user-images.githubusercontent.com/44292029/80560128-208ccf00-89e0-11ea-80f9-e96f0ef36814.png">

@timlinux @helendallas

**Comment by timlinux** [comment]
@NyakudyaA ok so I had another chat with @jeremyshelton can you please update it like this:

![image](https://user-images.githubusercontent.com/178003/80584219-424e7c00-8a09-11ea-9fae-0411ca5d39db.png)


- [ ] Small scale, show smoothed DEM from natural earth with washed-out look and main river tributaries over top as rendered in the current live site
- [ ] All scales, use solid country border like in my screenshot above
- [ ] Medium scale, swap smoothed dem for SRTM dem, keeping the washed-out look
- [ ] Get rid of the blue halo around place labels - use a white one if needed - you can use the new qgis conditional masking for labels to make them pop when over a darker background
- [ ] Center the black dot in teh place name marker - just make the black circle one unit smaller or the white one unit bigger
- [ ] At large scales <= 100k, swap out the rivers for the 50k one rather so we dont get angular river lines. Its okay if there are extra river lines there
- [ ] At large scales, swap the terrain for the aerial mosaic

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/80585355-19c78180-8a0b-11ea-859c-da4008820d43.png)

@NyakudyaA can you also make the rivers fatter when you zoom in?

**Comment by NyakudyaA** [comment]
> ![image](https://user-images.githubusercontent.com/178003/80585355-19c78180-8a0b-11ea-859c-da4008820d43.png)
> 
> @NyakudyaA can you also make the rivers fatter when you zoom in?

I will use map units for river layers and this should sort it out
> 
> And dont use blue for the labels
Ok, Nay preference, Was copying from the ngi specifications for 1:50k

**Comment by jeremyshelton** [comment]
@timlinux @NyakudyaA are we nearly there with the base map? Let me know when you are ready for me to test?

One quick observation: @timlinux that grey relief layer when zoomed all the way out looks rather strange & Star Wars-esque?

<img width="1018" alt="Screenshot 2020-05-05 at 12 32 05" src="https://user-images.githubusercontent.com/44292029/81057540-e84c2b80-8ecc-11ea-8557-415e4c5b39c8.png">

I think that this actually looks better, not that we can see the rivers...otherwise no relief at all might actually be cleanest?

<img width="1282" alt="Screenshot 2020-05-05 at 12 32 20" src="https://user-images.githubusercontent.com/44292029/81057545-ec784900-8ecc-11ea-80a1-387ecc98d7bd.png">

**Comment by NyakudyaA** [comment]
> @timlinux @NyakudyaA are we nearly there with the base map? Let me know when you are ready for me to test?

Will let you know.
> 
> One quick observation: @timlinux that grey relief layer when zoomed all the way out looks rather strange & Star Wars-esque?

Haven't modified the relief as yet
> 
> <img alt="Screenshot 2020-05-05 at 12 32 05" width="1018" src="https://user-images.githubusercontent.com/44292029/81057540-e84c2b80-8ecc-11ea-8557-415e4c5b39c8.png">
> 
> I think that this actually looks better, not that we can see the rivers...otherwise no relief at all might actually be cleanest?

We need to be decisive on what we want, going back and forth won't help me in finishing this background
> 
> <img alt="Screenshot 2020-05-05 at 12 32 20" width="1282" src="https://user-images.githubusercontent.com/44292029/81057545-ec784900-8ecc-11ea-80a1-387ecc98d7bd.png">
> 
> Also, @NyakudyaA it would be ideal to see these river names when zoomed all the way out - not sure how easy that is to do?

Label should only be visible together with a feature
> 
> <img alt="Screenshot 2020-05-05 at 12 37 48" width="541" src="https://user-images.githubusercontent.com/44292029/81057753-542e9400-8ecd-11ea-890d-3be5b9fd4dc4.png">

**Comment by jeremyshelton** [comment]
@NyakudyaA ok cool. What feature are you currently using for river names when zoomed out?

**Comment by NyakudyaA** [comment]
> @NyakudyaA ok cool. What feature are you currently using for river names when zoomed out?

I am using labeling based on the map scale. the labels should increase in size as you zoom in

**Comment by jeremyshelton** [comment]
@NyakudyaA OK - miscommunication. Sorry. What I actually meant is that it would be great if we could show all 19 of those river names when the map is zoomed out? At the moment it looks like only a 4 or 5 are showing on your map?

**Comment by jeremyshelton** [comment]
I am not sure if all of those labels in the colourful map are correct - but was just using that as an example of the river label coverage for the zoomed out view, if possible? I can send you a list of the main river names if need be?

**Comment by NyakudyaA** [comment]
> @NyakudyaA OK - miscommunication. Sorry. What I actually meant is that it would be great if we could show all 19 of those river names when the map is zoomed out? At the moment it looks like only a 4 or 5 are showing on your map?

I can do that but I highly discourage from that because at that scale the rivers will look disconnected from the labels. Currently, the software has an algorithm that shows labels based on the features visible on the map. It hides labels so that they won't be clustered labels

**Comment by jeremyshelton** [comment]
@NyakudyaA OK - happy to go with your recommendation on this 👍

**Comment by jeremyshelton** [comment]
@timlinux at our catch up last wednesday you mentioned a list of refinements to that base layer that are still needed, and that you are working on with Admire. I am not these changes yet on staging, but perhaps they are being worked on elsewhere? 
I think these included:
- clearer river labels
- river labels need to show when zoomed in close 
- 'cut-off' tables fixed
- fix white border/edge of map showing
- missing place name labels (white markers, but no labels?)
- others?

Do you think maybe we need to create a checklist to work through?

**Comment by NyakudyaA** [comment]
> @timlinux at our catch up last wednesday you mentioned a list of refinements to that base layer that are still needed, and that you are working on with Admire. I am not these changes yet on staging, but perhaps they are being worked on elsewhere?
> I think these included:
> 
>     * clearer river labels

Increased the font and put a halo
> 
>     * river labels need to show when zoomed in close, or to any degree (it seems that there are some zoom levels where no river labels are available)

All river labels are visible unless that river doesn't have a name at all
> 
>     * 'cut-off' tables fixed
> 
>     * fix white border/edge of map showing
Already fixed, now showing on live site
> 
>     * missing place name labels (white markers, but no labels?)
I have fixed this
> 
>     * When zoomed out, some major rivers have no labels, and those that do have names beginning with lowercase letters, for example 'Bree'. If possible, could all the main rivers visible when zoomed out have labels begin with capital letters.

What do you consider as major rivers? For DWA rivers we could identify them using strahler order but with NGI rivers it is a bit difficult.

> 
>     * others?
> 
> 
> Do you think maybe we need to create a checklist to work through?

**Comment by NyakudyaA** [comment]
@jeremyshelton cc @helendallas I have made some changes to the basemap. Can you please test and revert if anything still needs to be changed

**Comment by jeremyshelton** [comment]
Hi @NyakudyaA and @timlinux 

There seem to be some issues with river names

1. When zoomed out, only some river names are showing. 
2. When zoomed in past a certain point, no river names are showing
3. There is mis-matching between the different layers at the edge of the map

<img width="1034" alt="Screenshot 2020-05-25 at 18 33 22" src="https://user-images.githubusercontent.com/44292029/82831017-8f622880-9eb7-11ea-8837-282371a45a26.png">

@helendallas

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA and @timlinux
> 
> Thanks for your work on this. It's getting there.
> 
> There seem to be some issues with river names and map edges
> 
>     1. When zoomed out, only some river names are showing.
I will look at it but I am only labelling major rivers with a strahler order > at small scale.
> 
>     2. When zoomed in past a certain point, no river names are showing
I can look into this and rectify.
> 
>     3. There is mis-matching between the different layers at the edge of the map

Does this occur as you zoom in and out or all the time. I will look at it and rectify today
> 
> 
> <img alt="Screenshot 2020-05-25 at 18 33 22" width="1034" src="https://user-images.githubusercontent.com/44292029/82831017-8f622880-9eb7-11ea-8837-282371a45a26.png">
> 
> @helendallas
