### ISSUE TITLE
FBISv4 Big picture ticket 8: An admin manual in non-geek language for FRC to make basic adjustments

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1864]
Please add an admin manual in non-geek language for FRC to make basic adjustments, e.g.
- updating a biotope category
- making a users old email inactive
- changing the words in descriptions of things

.....basically whatever Kartoza wants to let FRC loose on... 

@helendallas @Aneri16

**Comment by helendallas** [comment]
I am closing this ticket and making a new on on RBIS-  User manual using wagtail

See ticket #2198
