### ISSUE TITLE
Rivers visible on Update a location site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1866]
It is difficult to edit the locality of a site on the Update a location site screen as no rivers are visible.

@dimasciput @NyakudyaA 

Is there something that can be done to assist?
In this example the site is not on the correct river, Klein Keurbooms River, and it has assigned it the Woodville river, which is incorrect. As we can see the rivers, it is impossible to edit.

![Screenshot_2020-01-21 FBIS Location Site Form](https://user-images.githubusercontent.com/45286876/72795417-44ed4880-3c46-11ea-957b-7c197a53cbc2.png)

**Comment by NyakudyaA** [comment]
@helendallas maybe we just need to make the rivers layer visible at that scale. We are currently serving two layers one from DWA and the other from NGI. Maybe at that scale we can show the 1:50k rivers

**Comment by NyakudyaA** [comment]
@dimasciput is there anything that you would like from me for this to happen. I guess it's just adding the rivers layer as part of that base map and users can click to get the river name.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton the river is visible now http://testing.healthyrivers.kartoza.com/location-site-form/update/?id=8288

**Comment by jeremyshelton** [comment]
@dimasciput thanks, looks good to me 👍
