### ISSUE TITLE
Duplicate Study Reference and River Names changed

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1867]
@dimasciput 
Please can you check why there are two references fro Dallas 1995.

![Screenshot_2020-01-21 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/72797239-6c91e000-3c49-11ea-977e-80a5ce1f7f33.png)

And why the Original Site Code was overwritten for some sites..  When the original Site code adheres to the required format it should be retained.

![Screenshot_2020-01-21 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/72797308-8b907200-3c49-11ea-9927-fe14d24cc283.png)

**Comment by dimasciput** [comment]
@helendallas duplicated references has been fixed

**Comment by helendallas** [comment]
@dimasciput Please can you check why site codes changed again.
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22622%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

See earlier comment : _And why the Original Site Code was overwritten for some sites.. When the original Site code adheres to the required format it should be retained._

![Uploading image.png…]()

**Comment by helendallas** [comment]
@dim and @helen to discuss tomorrow at 09h00. Closing ticket.
