### ISSUE TITLE
Error with site coordinates in .csv file

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1869]
1. If you download the .csv from this dashboard, you will see that Longitude has a minus '-' sign, and longitude does not. This should be the other way around. Latitude should have the minus
<img width="874" alt="Screenshot 2020-01-28 at 14 36 30" src="https://user-images.githubusercontent.com/44292029/73264500-a29c0a80-41db-11ea-9b5e-935929c24ed9.png">

2. Notes column absent from csv for fish data?

3. River name absent from csv for fish data?

4. DOI/URL/doc upload columns absent from csv for fish data?

**Comment by dimasciput** [comment]
@jeremyshelton fixed with https://github.com/kartoza/django-bims/pull/1891, currently only deployed to testing.

**Comment by jeremyshelton** [comment]
@dimasciput thanks, can we action on the live site too?

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 
Apologies - I deleted your comment Jeremy, Dimas please deploy to live site. This is really important as users are already using the data and a negative longitude is problematic. The issue of Collector/Owner should be sorted at the same time.  It should not be FBIS, but rather that as per the spreadsheet

**Comment by jeremyshelton** [comment]
@dimasciput I think this is looking good now on the live site. I tested a few .csv downloads and the lats and longs look correct. Are you still working on this, or can we close the ticket?

**Comment by dimasciput** [comment]
Yes deployed on live and testing.

**Comment by jeremyshelton** [comment]
Cool 👍
