### ISSUE TITLE
Insert FBIS citation suggestion at bottom of the landing page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1870]
Wou be great if we could have a suggested FBIS citation suggestion at bottom of the landing page, so users know how to cite the system. 

**Freshwater Biodiversity Information System (FBIS). 2020. FBIS Version 3. Downloaded from https://www.freshwaterbiodiversity.org on 1 February 2020**

- Would be great to get the date to automatically update.

@helendallas

**Comment by helendallas** [comment]
Agree. I will shift to FBIS V4

**Comment by dimasciput** [comment]
Hi @jeremyshelton @helendallas can you give me a rough visual guide about where to put this citation? 
![image](https://user-images.githubusercontent.com/1979569/80465761-c7805500-8965-11ea-8fab-4f93de8defc8.png)

**Comment by helendallas** [comment]
@jeremyshelton Please advice soonest

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 

I think it needs to go here, linking to a page where we explain to the user how to cite the FBIS? That's the way GBIF does it.

<img width="1440" alt="Screenshot 2020-04-28 at 13 10 47" src="https://user-images.githubusercontent.com/44292029/80482040-cfcf9480-8953-11ea-9732-b5429f008526.png">

**Comment by dimasciput** [comment]
@jeremyshelton can you add the citation guidelines here : 
https://freshwaterbiodiversity.org/admin/flatpages/flatpage/3/change/

User will able to access the page from here : https://freshwaterbiodiversity.org/pages/citation-guidelines/

I will add a link later.

**Comment by jeremyshelton** [comment]
Perfect. Thanks @dimasciput

**Comment by jeremyshelton** [comment]
I have added the citation information to the new 'Citations guidelines' flat page:

**Guidelines for citing data accessed via the FBIS

Data accessed through the FBIS are free for all—but not free of obligations. Under the terms of the FBIS data users agreement, users who download individual datasets or search results and use them in research or policy agree to cite them using the referencing information provided in the metadata for each data record. 

Good citation practices ensure scientific transparency and reproducibility by guiding other researchers to the original sources of information. They also reward data-publishing institutions and individuals by reinforcing the value of sharing open data and demonstrating its impact to their stakeholders and funders. Datasets published through GBIF are authored electronic data publications and, as such, should be treated as first-class research outputs and correctly cited.

Users are strongly encouraged to cite data retrieved from the GBIF network according to the recommended citation:

"Freshwater Biodiversity Information System (FBIS). 2020. FBIS Version 3. Downloaded from https://www.freshwaterbiodiversity.org on 1 February 2020"**

@helendallas please edit as you see fit. 

Also, I think we need to add a 'Data users agreement' checkbox as a pre-requisite for anyone downloading .csv files. Thoughts on this @helendallas & @timlinux? Is this quick & easy to do, or should I ticket for the next version instead?

**Comment by dimasciput** [comment]
> Also, I think we need to add a 'Data users agreement' checkbox as a pre-requisite for anyone downloading .csv files. Thoughts on this @helendallas & @timlinux? Is this quick & easy to do, or should I ticket for the next version instead?

Let's park it for next version.

**Comment by jeremyshelton** [comment]
@dimasciput sure thing, I have ticketed for FBISv5

**Comment by dimasciput** [comment]
Added link to citation in testing

**Comment by jeremyshelton** [comment]
Looks good. Thanks @dimasciput
