### ISSUE TITLE
Site code issues

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1871]
1.  When a site already had the standardised code that conforms to the FBIS format (e.g.a  rivers database site), then that needs to be retained presented, so that users can track back to that site. 
2. Sometimes created sites don’t stick to the FBIS format eg: http://freshwaterbiodiversity.org/map/#site/siteIdOpen=27609 ??
4. Or a search for Eastern Cape sites gives back incorrect site names, EG:

![Screenshot 2020-01-28 at 11 15 50](https://user-images.githubusercontent.com/44292029/73266262-39b69180-41df-11ea-8da9-4e0d046dec72.png)
…looks like it's taken the original code, and hasn’t generated an FBIS site code? 

5. Please change the role for auto-creating a site code 'includes first 4 characters' instead of 'first 4 letters', so that eg WIT- is accepted

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 
Many (most?) of these sites are those that have been imported from Biobase. We need to give each site an FBIS Site Code, and retain the Original Site Code

**Comment by jeremyshelton** [comment]
@helendallas agreed 👍

**Comment by dimasciput** [comment]
@jeremyshelton Please test it again in live site, thanks.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - looking good 👍
