### ISSUE TITLE
DATA SOURCES issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1872]
There is a big issue with the data assigned to the different data sources: FBIS data should include ALL data not coming from GBIF, however this is not the case. 

<img width="441" alt="Screenshot 2020-01-28 at 15 35 40" src="https://user-images.githubusercontent.com/44292029/73268609-e6930d80-41e3-11ea-8e5b-ab44c67c6df9.png">

For example, Lestagella penicillata:

FBIS only selected returns 1 record (this should include ALL non-GBIF records)

FBIS and GBIF data selected returns 1 record

GBIF only selected returns 0 records

Neither FBIS nor GBIF selected returns 202 records ???? (this should have zero records)

...I suggest removing the FBIS button, so that all 'non-GBIF' data are always 'turned on', and then the user just has the choice of whether or not to torn the GBIF data on or off.  

@helendallas

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/73343307-4804bc00-4278-11ea-9e14-41bb4eefe66f.png)

**Comment by timlinux** [comment]
@dimasciput as discussed in our call, please remove the FBIS tick box there and make FBIS 'always on'.

Also please confirm if you GBIF fetcher for all the new taxa that have been added in the last updates.

Also all non GBIF records should be 'owned' by FBIS.

**Comment by dimasciput** [comment]
can you test it in live site @jeremyshelton ? 
![image](https://user-images.githubusercontent.com/1979569/75151570-943d0200-5739-11ea-9e65-0d132178c6c6.png)
 I made the checkbox always on.

**Comment by jeremyshelton** [comment]
Thanks for fixing @dimasciput - looks good now :)
