### ISSUE TITLE
Problem filtering fish by province

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1876]
@dimasciput 
http://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["value,sa_provinces,Western%20Cape"]&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

If I select fish module and Spatial filter > Western Cape Province, then the system only returns 13 records, and zero records for some other provinces like Free State and Northern Cape?

There should be far more records than this for these searches.

**Comment by jeremyshelton** [comment]
@dimasciput I think that fixing #1872 will sort out this problem.

**Comment by dimasciput** [comment]
@jeremyshelton can you check it again?

**Comment by jeremyshelton** [comment]
@dimasciput thanks - looks good now.
