### ISSUE TITLE
SA Ecoregion 2 label issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1877]
@NyakudyaA looks like something is not right with the labels in the 'Ecological Region 2' drawer? Also, please check whether 'Ecological Region' is indeed the correct terminology for these drawers?
<img width="396" alt="Screenshot 2020-01-29 at 15 57 31" src="https://user-images.githubusercontent.com/44292029/73362998-8918c280-42b0-11ea-804c-83417db48761.png">

**Comment by timlinux** [comment]
See also https://github.com/kartoza/django-bims/issues/1842

Needs to re-harvest GeoContext for these sites.

**Comment by timlinux** [comment]
Please do a unique values query like you did on the SANBI table to ensure the data in the upstream layer is in fact correct.

**Comment by NyakudyaA** [comment]
@jeremyshelton cc @timlinux This is not a bug. This is the way the data shows from upstream. Data Source http://www.dwa.gov.za/iwqs/gis_data/ecoregions/get-ecoregions.aspx

The actual layer http://www.dwa.gov.za/iwqs/gis_data/ecoregions/lev2-0105.zip

![attributes](https://user-images.githubusercontent.com/2510900/74916170-0f1abb80-53ce-11ea-85dc-aba9ae226935.png)

If you have a better source for this I can replace this.

**Comment by jeremyshelton** [comment]
<img width="282" alt="Screenshot 2020-02-21 at 05 45 02" src="https://user-images.githubusercontent.com/44292029/75002520-5efc8f80-546d-11ea-9f7c-c9f209a91a3e.png">

@NyakudyaA seems like a strange set of ecoregion names for 'Ecological Region 2'......but if that is correct, then that's fine. 

Also, can you confirm that 'Ecological Region' the correct terminology for these drawers?

Thanks

**Comment by NyakudyaA** [comment]
> <img alt="Screenshot 2020-02-21 at 05 45 02" width="282" src="https://user-images.githubusercontent.com/44292029/75002520-5efc8f80-546d-11ea-9f7c-c9f209a91a3e.png">
> 
> @NyakudyaA seems like a strange set of ecoregion names for 'Ecological Region 2'......but if that is correct, then that's fine.
> 
> Also, can you confirm that 'Ecological Region' the correct terminology for these drawers?
> 
> Thanks

cc @dimasciput 
I think it should be renamed `Ecoregion level 1` and `Ecoregion level2`

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA agreed

**Comment by dimasciput** [comment]
Updated in live site

**Comment by NyakudyaA** [comment]
@jeremyshelton to check ecoregions 2 labels with dwa

**Comment by jeremyshelton** [comment]
@NyakudyaA can you check if the correct labels can be found here: http://www.sasdi.net/metaview.aspx?uuid=6e4f618a622bec48a6b01ab3b23dac8f&dlonly=true

**Comment by NyakudyaA** [comment]
> @NyakudyaA can you check if the correct labels can be found here: http://www.sasdi.net/metaview.aspx?uuid=6e4f618a622bec48a6b01ab3b23dac8f&dlonly=true

Same story @jeremyshelton 
![same-source](https://user-images.githubusercontent.com/2510900/75624607-9500e880-5bbe-11ea-9df4-e6c539a09976.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA @timlinux OK, well if that is correct, then maybe best to rather hide from the users, because those drawers are not meaningful and will just be confusing for the user. 

@helendallas I think we need to make a call on which sets of layer attributes we want to make visible to the users? I will make a ticket in the FRC GitHub project for this...

**Comment by helendallas** [comment]
@NyakudyaA @jeremyshelton 
The correct column to display for Ecoregion level 2 is what is displayed in the column labelled LEVEL.  These relate to Ecoregion level 1, with a subcategory, and the folks that use this layer, know what these numbers mean.  This was previously explained in an earlier ticket. No other columns need to be displayed for this.

LEVEL
1.01
2.02
3.04
1.02
2.04
2.03
3.05
3.03
1.03
3.02
3.01
2.01
5.01
1.03
4.02
4.01
12.01
1.03
6.01
4.02
5.02

**Comment by NyakudyaA** [comment]
@dimasciput maybe you need to update the entries here, the values 1,2,7 should not show up here, Geocontext and geoserver are working  properly
![context-geo](https://user-images.githubusercontent.com/2510900/75966805-9b030c00-5ed3-11ea-9bf6-db229e3aa322.png)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput and @NyakudyaA. 

@helendallas & I are going to meet and have a good look at what we need to include/exclude for layers.

**Comment by helendallas** [comment]
@NyakudyaA @jeremyshelton
The correct column to display for Ecoregion level 2 is what is displayed in the column labelled LEVEL. These relate to Ecoregion level 1, with a subcategory, and the folks that use this layer, know what these numbers mean. This was previously explained in an earlier ticket. No other columns need to be displayed for this.

LEVEL
1.01
2.02
3.04
1.02
2.04
2.03
3.05
3.03
1.03
3.02
3.01
2.01
5.01
1.03
4.02
4.01
12.01
1.03
6.01
4.02
5.02

This has not yet been actioned on the live site.  We dont need further discussion. This is the correct column to display for Ecoregion level 2

**Comment by NyakudyaA** [comment]
> @NyakudyaA @jeremyshelton
> The correct column to display for Ecoregion level 2 is what is displayed in the column labelled LEVEL. These relate to Ecoregion level 1, with a subcategory, and the folks that use this layer, know what these numbers mean. This was previously explained in an earlier ticket. No other columns need to be displayed for this.
> 
> LEVEL
> 1.01
> 2.02
> 3.04
> 1.02
> 2.04
> 2.03
> 3.05
> 3.03
> 1.03
> 3.02
> 3.01
> 2.01
> 5.01
> 1.03
> 4.02
> 4.01
> 12.01
> 1.03
> 6.01
> 4.02
> 5.02
> 
> This has not yet been actioned on the live site. We dont need further discussion. This is the correct column to display for Ecoregion level 2

Tha map layer already uses this column. even Geocontext uses this. They are a couple of odd values in the spatial filters. @dimasciput needs to update the values

**Comment by jeremyshelton** [comment]
OK great. Thanks @NyakudyaA

**Comment by helendallas** [comment]
okay because it is still showing as: 1, 2, 3 are all wrong...I checked the lev2-0105.dbf file and they are not there....

![Screenshot_2020-03-18 FBIS Map](https://user-images.githubusercontent.com/45286876/76940092-45325900-6902-11ea-98bd-f8071aa41218.png)

**Comment by NyakudyaA** [comment]
> okay because it is still showing as: 1, 2, 3 are all wrong...I checked the lev2-0105.dbf file and they are not there....
> 
> ![Screenshot_2020-03-18 FBIS Map](https://user-images.githubusercontent.com/45286876/76940092-45325900-6902-11ea-98bd-f8071aa41218.png)

When it is updated then those values will not show

**Comment by dimasciput** [comment]
@helendallas 
Ok I'll run the script again, please understand that overwriting spatial data is not automatic process, but when there is new site it will be automatic.

**Comment by helendallas** [comment]
@dimasciput Please confirm if this has been done on the live site so that I can check

**Comment by NyakudyaA** [comment]
You need to test this @jeremyshelton and close if it's working

**Comment by helendallas** [comment]
@NyakudyaA @dimasciput 

Admire, please see earlier comment checking if it has been deployed on live site. Its is still showing the following on live:
![Screenshot_2020-04-15 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/79335189-e15f7800-7f21-11ea-94af-ced3abe91a0a.png)
Cannot check on testing as no spatial layers are visible 
![Screenshot_2020-04-15 FBIS Map(3)](https://user-images.githubusercontent.com/45286876/79335245-fcca8300-7f21-11ea-89b2-6fa1b2d8e5e4.png)

@timlinux I thought the testing site was going to be a mirror image of the live site

**Comment by NyakudyaA** [comment]
@jeremyshelton You can close after checking this as well, Dimas updated geocontext

**Comment by helendallas** [comment]
@NyakudyaA @dimasciput 

Sorry, but still not correct on live site. Please confirm once fixed.

![Screenshot_2020-04-21 FBIS Map](https://user-images.githubusercontent.com/45286876/79843316-66331180-83ba-11ea-8bbc-c36a62e439ca.png)

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA @helendallas 

Agreed.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas @timlinux 
Still not correct in staging.
