### ISSUE TITLE
Change icon for invertebrate taxon dashboard

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1878]
@dimasciput the icon for invertebrate taxon dashboards should be the crab, not the fish:
http://freshwaterbiodiversity.org/map/#search/Leptophlebiidae/taxon=&search=Leptophlebiidae&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

<img width="1440" alt="Screenshot 2020-01-29 at 16 11 13" src="https://user-images.githubusercontent.com/44292029/73363927-4a840780-42b2-11ea-903f-c8afad03e197.png">

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 
Many (most?) of these sites are those that have been imported from Biobase. We need to give each site an FBIS Site Code, and retain the Original Site Code

**Comment by dimasciput** [comment]
Please test it on the testing server.

**Comment by helendallas** [comment]
@dimasciput Checked - all good.
