### ISSUE TITLE
Extra row in a search for a fish taxon?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1879]
@dimasciput there should only be one row for Pseudobarbus burchelli in this search?
<img width="751" alt="Screenshot 2020-01-29 at 16 19 27" src="https://user-images.githubusercontent.com/44292029/73364383-2d9c0400-42b3-11ea-89eb-ce760daa5178.png">

**Comment by dimasciput** [comment]
Fixed, please try again http://freshwaterbiodiversity.org/map/#search/Pseudobarbus%20burchelli/taxon=&search=Pseudobarbus%20burchelli&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=[%22validated%22]&sourceCollection=&abioticData=&ecologicalCategory=&rank=ORDER&siteIdOpen=&orderBy=name

**Comment by jeremyshelton** [comment]
@dimasciput thanks, looks good 👍
