### ISSUE TITLE
Site Photographs - sizing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1881]
Can you adjust the size of the photographs so that the full photographs is visible on the report/dashboard.

Original Photograph I uploaded
![Eerste River @ Witbrug 2017_04_22 Upstream](https://user-images.githubusercontent.com/45286876/73429267-e7db4c00-4343-11ea-9c7a-79e23662c447.jpg)

What is visible on the site below:
![Screenshot_2020-01-30 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/73429317-0d685580-4344-11ea-9fae-8537b36c4815.png)

**Comment by dimasciput** [comment]
http://testing.healthyrivers.kartoza.com/sass/dashboard/10425/?siteId=10425

**Comment by helendallas** [comment]
@dimasciput dimensions better but can you please make background white not gray

**Comment by dimasciput** [comment]
@helendallas updated, please check it again thanks.

**Comment by helendallas** [comment]
@dimasciput Thanks looks great,
