### ISSUE TITLE
Geomorphological Zone

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1883]
@dimasciput 
Geomorphological zone data is not being shown in either the Overview dashboard or detailed dashboards

![Screenshot_2020-01-31 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/73531001-41b24380-4422-11ea-9071-30ef7401404e.png)

![Screenshot_2020-01-31 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/73531010-44ad3400-4422-11ea-8511-1b1025ad3696.png)

Seems to be for where only fish data are available

**Comment by dimasciput** [comment]
@helendallas please test it again

**Comment by helendallas** [comment]
@dimasciput 
Geomorphological zones now showing but other geocontext data missing:
see ticket #1783 

Link:
http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=E1ROND-00153&siteId=30688&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=30688&orderBy=-name&polygon=

**Comment by dimasciput** [comment]
@helendallas I will run the script again to fetch all missing geocontext, I only fetched geomorphological zone for this ticket.
