### ISSUE TITLE
Rivers Database - River Name

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1885]
The River Name column in the Rivers Database needs to be pulled into the Original River Name in FBIS.

This is useful for river practitioners as the Site Code is based on this river name. Allow for reflection back on historical data.

I have created a spreadsheet from the Rivers DB. 

[RIvers Site Codes and Original River Names for importing into FBIS.xlsx](https://github.com/kartoza/django-bims/files/4139400/RIvers.Site.Codes.and.Original.River.Names.for.importing.into.FBIS.xlsx)

**Comment by dimasciput** [comment]
@helendallas updated on testing site : http://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=A2APIE-BRIDG&siteId=10154&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=10154&orderBy=name&polygon=

Will deploy to live site later.
