### ISSUE TITLE
CSV downloads missing some fields?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1888]
@dimasciput the .csv files seem to be missing some fields, such as 'Sampling Method' and 'Biotope'.

For example, see the csv download for this query: http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Pseudobarbus%20burgi&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name 

@Aneri16 @helendallas

**Comment by helendallas** [comment]
@dimasciput 
This applies to CSV files for Invertebrates, and will in the future apply to Algae.  
All algal, invertebrate and fish data need to include  'Sampling Method' and 'Broad Biotope', 'Specific Biotope' and 'Substratum'.

**Comment by dimasciput** [comment]
Fixed in testing - https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Pseudobarbus%20burgi&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Looks like you have also updated the .csv downloads on the live site too?

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 
Whats critical is that the columns included in the .csv user downloads are the same as those in the  .csv file that we used to upload the data. For example, for fish, columns like 'sampling effort' and 'abundance' are missing from the .csv download. For example, see download for the fish Enteromius pallidus:

<img width="1079" alt="Screenshot 2020-03-09 at 12 33 45" src="https://user-images.githubusercontent.com/44292029/76205475-f9492b00-6202-11ea-8796-8e450aab700c.png">
