### ISSUE TITLE
3000 records without study reference

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1893]
We have 3000 records (from Biobase?) that have no study reference. These need to be updated.

CC @helendallas 

![image](https://user-images.githubusercontent.com/178003/74321457-2fb59680-4d7a-11ea-9a57-b588ec673f06.png)

**Comment by helendallas** [comment]
Very strange - they should all have a study reference. How can I view these. @dimasciput can you send me a spreadsheet of the 3000 records.

**Comment by helendallas** [comment]
@dimasciput Please get back to me on this.

**Comment by dimasciput** [comment]
@helendallas 
![image](https://user-images.githubusercontent.com/1979569/79682619-e9832480-824d-11ea-9a4a-f8a73018b9b5.png)
there are 1623 biobase data without reference

**Comment by dimasciput** [comment]
But let me check it again on Monday

**Comment by helendallas** [comment]
@dimasciput All biobase records has a study reference in the original Biobase. I hope this is resolved when the Biobase references have been updated,

**Comment by dimasciput** [comment]
@helendallas apparently this is because we remove this reference :
```
H.F. Dallas, “An evaluation of SASS (South African Scoring System) as a tool for the rapid assessment of water quality.”, Msc Thesis. Zoology Department, University of Cape Town, South Africa., 1994.
```
Should I re-create this reference, and add it to the collection records?

**Comment by dimasciput** [comment]
Done, all biobase records now have reference

**Comment by helendallas** [comment]
@dimasciput Thanks
