### ISSUE TITLE
Unable to edit/add abiotic data to existing SASS records (Non Super-Users)

### ISSUE THREAD

**Issue by Janette-Lumley** [kartoza/django-bims#1894]
@dimasciput Go to an existing site with SASS data and then to the SASS dashboard. Click on date to get to the SASS record screen. Click 'edit', then click 'next'. It kicks me out and into the login screen where I try to log in again but cannot. Note: This works fine for super users.

![image](https://user-images.githubusercontent.com/55576335/74425453-6237c000-4e5c-11ea-97d1-7e56f9dcb541.png)

![image](https://user-images.githubusercontent.com/55576335/74425680-c064a300-4e5c-11ea-9c01-ebb720ca0637.png)

![image](https://user-images.githubusercontent.com/55576335/74425812-f73ab900-4e5c-11ea-83b0-89f5a209bf79.png)

![image](https://user-images.githubusercontent.com/55576335/74425951-2e10cf00-4e5d-11ea-9774-98f144a4ce15.png)

![image](https://user-images.githubusercontent.com/55576335/74426175-9a8bce00-4e5d-11ea-9016-b45588919fd6.png)

**Comment by helendallas** [comment]
@dimasciput 
As discussed previously the person who captures the data (Data Capturer), the Data Owner both need to be able to edit the SASS data.

PLease check that this is working as users who have added data have not been able to edit their data, which they should be able to do.

Janette is a Staff User.

**Comment by dimasciput** [comment]
@Janette-Lumley @helendallas I can open the form with Janette account, can you check the form again?

**Comment by dimasciput** [comment]
Ah sorry I see my mistake, found the error, fixing it now.

**Comment by dimasciput** [comment]
@Janette-Lumley please test it again, thanks.

**Comment by Janette-Lumley** [comment]
@dimasciput works great, thanks!
