### ISSUE TITLE
Adding DOI, URL, pdf, for existing Study References imported from Biobase

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1895]
@dimasciput @timlinux 
At the moment there is no way for us to add or update the Study Reference Details, such as adding a DOI, or URL, or uploading a pdf for a study that already exists in FBIS, and which has data attached to it.

Examples are all the Biobase study references.  Rather that providing Dimas with a spreadsheet and this happens in the back-end, can you develop the functionality for us to search for a Study Reference - and then add the missing information and or upload a pdf in the case of the report.

The obvious place is here:

![Screenshot_2020-02-13 Explore Documents - Freshwaterbiodiversity](https://user-images.githubusercontent.com/45286876/74434988-2c023c80-4e6c-11ea-9153-274ba8bf2d96.png)

Or is it here: In which case none of the filters are working. Please assist as we need to add details for Biobase data

![Screenshot_2020-02-13 FBIS Bibliography](https://user-images.githubusercontent.com/45286876/74435217-a0d57680-4e6c-11ea-8fab-3e1f06e575ab.png)

**Comment by dimasciput** [comment]
@timlinux this is actually pretty complicated, will probably take 1 day

**Comment by helendallas** [comment]
@dimasciput    Noted - It is very important from a system perspective and long term sustainability. So please add it to you "to do" list, thanks

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 
I added search, and fix the filters for the bibliography page. You can't still upload pdf from here, but you can add DOI and other stuff.

https://testing.healthyrivers.kartoza.com/bibliography/?year=&author=&doi_exist=False&q=

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - very helpful :)

**Comment by timlinux** [comment]
Discussed on 18 March 2020:

1) Helen upload any PDFs or URL based documents needed to the document manager on the live site

![image](https://user-images.githubusercontent.com/178003/76950706-5da27380-6902-11ea-966f-a24761332ec1.png)

2) Helen instruct Dimas to batch update records meeting specific criteria to reference the uploaded PDF's

Alternatively, if the publication has a DOI:

1) Helen insert the DOI in the citation database
2) Helen instruct Dimas to batch update records meeting specific criteria to reference the Citation

**Comment by timlinux** [comment]
Dimas will stand by for a spreadsheet from @helendallas with the above associations then batch update.

**Comment by helendallas** [comment]
@dimasciput 
I am going through the Biobase references and came across a case where the reference is a published report  and we need to upload the pdf which we have.  The study reference is in the citation manager
https://freshwaterbiodiversity.org/admin/td_biblio/entry/55/change/
But is not on the documents.  Please confirm the steps I need to take to ensure that the data associated with study get assigned to the correct document and how I proceed.

**Comment by helendallas** [comment]
@dimasciput Once you have answered above we can complete our side and then it will be ready for ingestion.  

File thus far:
[Biobase Study Reference Table For DOI URL - 06-03-20.xlsx](https://github.com/kartoza/django-bims/files/4388972/Biobase.Study.Reference.Table.For.DOI.URL.-.06-03-20.xlsx)

**Comment by dimasciput** [comment]
> @helendallas I am going through the Biobase references and came across a case where the reference is a published report and we need to upload the pdf which we have. The study reference is in the citation manager

There is no way to do this from the website, I have to do it with a script.


![image](https://user-images.githubusercontent.com/1979569/78117698-2c609200-7430-11ea-9b72-0299196f6f3f.png)

Also published report need to have link of document or URL, without it I can't create a document. Please fix it.

@helendallas @jeremyshelton

**Comment by helendallas** [comment]
@dimasciput 

Most published reports do not have a url. These are old historical reports that were around befroe digitisation. In the column 

Do we   have PDF?  those with a Yes, will need you to manually upload the PF, which we have. The other should remain as a published report but no pdf. As it is not available anywhere.  

So it is a published report, but not available as url or pdf....how do we deal with these. Add a category "Not available"?

I have added pdfs in this folder:
Pdf of Biobase References in our shared folder

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 
> Most published reports do not have a url. These are old historical reports that were around befroe digitisation. In the column

Probably add a link to fbis for now, I don't want to change current model because it will affect other components.

**Comment by helendallas** [comment]
@dimasciput I am trying to upload pdfs on the documents in admin.  How do I search for a reference to check if the document has already been uploaded. I am afraid I am battling to understand the workflow. What do I add to the Biobase table for refs that dont have a pdf?

**Comment by dimasciput** [comment]
@helendallas https://freshwaterbiodiversity.org/documents/, and probably upload the document from there.

**Comment by timlinux** [comment]
As discussed in our call 8 April 2020, for docuemtns which are not physically available we will attache a place holder image as below:

![image](https://user-images.githubusercontent.com/178003/78768979-97581e80-7984-11ea-94f1-0ea4f0b4bb81.png)

**Comment by helendallas** [comment]
@dimasciput I have uploaded all the reports and also some others that are not available online.
[Biobase Study Reference Table For DOI URL - 06-03-20.xlsx](https://github.com/kartoza/django-bims/files/4450752/Biobase.Study.Reference.Table.For.DOI.URL.-.06-03-20.xlsx)

I was unsure what to do for unpublished data - -please go through and check

**Comment by helendallas** [comment]
@dimasciput Has this been done? Where should I check? testing or live.

**Comment by helendallas** [comment]
@dimasciput Please respond to this - I need to know if and where I should check as I dont know if it has been  done yet

**Comment by dimasciput** [comment]
@helendallas no not yet sorry, will do it on Monday

**Comment by helendallas** [comment]
@dimasciput I am adding this to FBIS V4 as it still has to be done and I really dont want it dropping off the radar

**Comment by helendallas** [comment]
@dimasciput The Reference Category is still not correct for the legacy Biobase records.

For example:

![image](https://user-images.githubusercontent.com/45286876/82914736-2b4f6b00-9f70-11ea-9ad2-5e3984c0d24c.png)

This should be a Published Report - it is on the Documents.

Moore   C.A. & Chutter F.M. | 1988 | CSIR and National Institute for   Water Research (NIWR) Contract report, Pretoria. | A survey of the conservation   status and benthic biota of the major rivers of the Kruger National Park. | Published report |   |   | https://freshwaterbiodiversity.org/documents/217

Another example:
![image](https://user-images.githubusercontent.com/45286876/82915178-b892bf80-9f70-11ea-8af0-14f3dc08a212.png)

Please can you update all the Reference Categories according to that provided in the excel spreadsheet provided. Here it is again.

[Biobase Study Reference Table For DOI URL - 06-03-20.xlsx](https://github.com/kartoza/django-bims/files/4682988/Biobase.Study.Reference.Table.For.DOI.URL.-.06-03-20.xlsx)

**Comment by dimasciput** [comment]
@helendallas I updated the source references but it may have different authors, you can change it directly from the documents page.

**Comment by helendallas** [comment]
@dimasciput Thanks I will work through documents.

**Comment by helendallas** [comment]
@dimasciput I am still getting erro when I edit documnt.

http://staging.freshwaterbiodiversity.org/documents/241
I changed owner, to include author, then added date and selected update.

I think it is updating on the system, just giving me an error message

**Comment by helendallas** [comment]
@dimasciput I cant find document after I update it? Please can you check they are still there.

Also can I add Owner if they dont exist. I need these to be shown correctly in the Metadata Table, so until you add the Authors field, I am adding the authors to Owner. This is not correct, but the best for now.

Please advice soonest.

**Comment by dimasciput** [comment]
@helendallas 

> Also can I add Owner if they dont exist. I need these to be shown correctly in the Metadata Table, so until you add the Authors field, I am adding the authors to Owner. This is not correct, but the best for now.

No we can't for now I'm sorry, can you provide me the user list, I will make them first.

**Comment by dimasciput** [comment]
@helendallas 

> http://staging.freshwaterbiodiversity.org/documents/241
I changed owner, to include author, then added date and selected update.

It's still missing the owner, can you tell me how did you update this document?

**Comment by dimasciput** [comment]
![Peek 2020-05-28 14-04](https://user-images.githubusercontent.com/1979569/83129704-68019a80-a107-11ea-9ad2-4a78d7fafd99.gif)
@helendallas this is how you should update the owner

**Comment by helendallas** [comment]
@dimasciput Okay I added author even though it wasnt there. I think some study references are now compromised. I cnat find on documents to check and correct.

Sorry:  Please can you check

Allanson 1961. An introductory note on the chemistry and biology of the Great Fish River. Directors Report:  Institute for Freshwater Studies, Rhodes University, South Africa.


De   Decker H.P. | 1981 | Changes in the   community structure of benthic macroinvertebrates in the stony-bed areas of   the Palmiet River, in relation to the physical and chemical characteristics   of the river.


Forbes   A.T. | 1968 | Contributions   to the ecology of the Sundays River.


Ractliffe   G. | 1991 | The effects of   suspended sediments on the macroinvertebrate community structure of a river   ecosystem.
I am not going to edit any more. I will rather wait until the author issue is resolved
Thanks

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 
Without the authors option added it doesnt make sense to edit the historical Biobase.

Unfortunately the study reference are shown incorrectly in filter and metadata table.
![image](https://user-images.githubusercontent.com/45286876/83132322-82c11880-a0e1-11ea-9ca5-8b595f0ee8db.png)
 @dimasciput Not sure what it will take to correct this in the backend. Ideally authors added, and owner remains FBIS, othersie we have hundreds of "Owners" who are either dead or irrelevant, what is important is to get the Authors right.

I am happy to park this but and get the live site up, but please cna it be addressed sooner than later as I really would like to fix the documents on FBIS so they are cited correctly.

**Comment by dimasciput** [comment]
@helendallas I will update it now

**Comment by dimasciput** [comment]
@helendallas please check the site again

**Comment by dimasciput** [comment]
@helendallas wait, there is still an error

**Comment by dimasciput** [comment]
@helendallas ok fixed

**Comment by helendallas** [comment]
@dimasciput thanks, one more not coming through
Ractliffe G. | 1991 | The effects of suspended sediments on the macroinvertebrate community structure of a river ecosystem.

**Comment by helendallas** [comment]
@dimasciput 
Moore and Chutter disappeared now??

**Comment by dimasciput** [comment]
@helendallas which doc?

**Comment by helendallas** [comment]
Moore   C.A. & Chutter F.M. | 1988 | A survey of the   conservation status and  benthic biota   of the major rivers of the Kruger National Park.
-- | -- | --

**Comment by dimasciput** [comment]
@helendallas we can only have one owner for document, try search by the title.

**Comment by helendallas** [comment]
@dimasciput @timlinux @jeremyshelton 
Please can this be prioritised for fixing asap. A lot of the metadata is incorrect for documents. 

We need to be able to add **Author(s)** in the Documents before **Title**. These authors are then displayed on the metadata, both in Study Reference Filter, and Metadata Table.

The Owner then becomes much less important for published data and can in many cases simply be FBIS - especially for historical data. 
![Screenshot_2020-06-03 None — Freshwaterbiodiversity](https://user-images.githubusercontent.com/45286876/83606718-5d695a00-a57a-11ea-8b8b-855d0220da2a.png)

**Comment by helendallas** [comment]
From DImas

I have added a new form to add multiple authors for a document. Follow these steps to update the author list : 

- Open the document page
https://freshwaterbiodiversity.org/documents/238
- Click `Edit BIMS Document`
 
- You will see this form page : 
 
- The author input is autocomplete to help you find the existing user, but you can also write new name there

**Comment by helendallas** [comment]
@dimasciput Thanks for this Dimas.

I have edited this document in BIMS as suggested, however the citation is still incorrect in the Study Reference filter although it is correct in the Metadata Table. 

![image](https://user-images.githubusercontent.com/45286876/84147411-a8450f00-aa5d-11ea-88b2-477ef1e314a8.png)

![image](https://user-images.githubusercontent.com/45286876/84147460-bc890c00-aa5d-11ea-92a2-6e27acf5d24f.png)

**Comment by dimasciput** [comment]
@helendallas it should be fixed now

**Comment by helendallas** [comment]
@dimasciput I am still finding some study references that are from Biobase e.g. 

Gale   B.A | 1992 | University of Cape Town PhD   Thesis | The effect of regulation by two   impoundments on an acid, blackwater, Cape mountain stream. | Thesis | http://hdl.handle.net/11427/22130

That were sent to you in 
Biobase Study Reference Table For DOI URL - 06-03-20.xlsx

But the study is not in the Study Reference Filter

![image](https://user-images.githubusercontent.com/45286876/84509440-fc512d00-acc3-11ea-9f95-40030baa77e5.png)

**Comment by helendallas** [comment]
@dimasciput Please can you check the following Biobase study references - they are here: 

Three have the wrong Reference category - they need to be changed to "Unpublished data"

Two do not come up in the Study Reference Filter , and do not have metadata or any actual data.  They are both theses and may have been moved from documents to citations with url.


![image](https://user-images.githubusercontent.com/45286876/86141146-0069b100-baf2-11ea-9da7-327e83618314.png)

**Comment by dimasciput** [comment]
@helendallas for unpublished, currently we can't add author and year to the upublished data. So if I changed the reference to unpublished category, the author and year will be gone.

**Comment by dimasciput** [comment]
> @helendallas Two do not come up in the Study Reference Filter , and do not have metadata or any actual data. They are both theses and may have been moved from documents to citations with url.

Did you remove the document before I changed the reference from document to thesis?

**Comment by helendallas** [comment]
@dimasciput Okay, then for the Unpublilshed, lets leave as is, and I will make a comment somewhere on the document file.
For the thesis, I suspect it was removed from documents, before we were aware of the repurcussions of doing this, sorry

**Comment by helendallas** [comment]
@dimasciput For the unpublished  - should I add the unpublilshed "report" as a document, then upload a "report not available"pdf.
Or is this not necessary?

**Comment by helendallas** [comment]
@dimasciput The metadata for these still need to be revised to reflect - "report" not "peer-reviewed scientific article". Please advice how to best do this. Perhaps once the new functionality is rolled out to FBIS. Lets chat today.
![image](https://user-images.githubusercontent.com/45286876/90601089-eac25f00-e1f7-11ea-97fd-452e38900417.png)

**Comment by helendallas** [comment]
Moving to FVIS V5

**Comment by helendallas** [comment]
Closing this by way of new ticket #2286
