### ISSUE TITLE
Flat Pages

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1896]
At the moment the Flat Pages cannot be accessed. The following error message is received
![Screenshot_2020-02-17 500 - Server Error](https://user-images.githubusercontent.com/45286876/74664184-e9ab6900-51a5-11ea-9936-889fc22d6948.png)

It would be really useful or FRC to be able to edit the screen that shows when you land on our FBIS page. This is important from a sustainability perspective as it allows us to update the message ourselves and not be reliant on Kartoza (Dimas).  For example it would be good to add the Recommended Citation on this page.

Please also check why it is not working.

**Comment by timlinux** [comment]
Were you using this link @helendallas ?

https://freshwaterbiodiversity.org/admin/flatpages/flatpage/

BTW @dimasciput I see the admin menu link takes you to non ssl equivalent of the above when you go to admin.

@helendallas can you confirm you are logged in when trying to open flatpages?
And can you confirm which user you were logged in as - I will check the permissions.

Regards

Tim

**Comment by helendallas** [comment]
@timlinux Yes I was logged in , helen@frcsa.org.za I am a superuser, just checked now and same error message.

**Comment by dimasciput** [comment]
fixed in testing
