### ISSUE TITLE
Validation Status

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1897]
At the moment only Validated data is shown as the default. I just had a user saying he has added data but cant see his site. The site is only visible once the Non Validated box is ticked.

My preference is for the default to be: All boxes ticked - Valildated, Non Validated, SASS Accredited and NON SASS Accredited.  That way when a user adds data it will be immediately visible and can then be edited by them. 

Please can this be be included in the V3 as it pertains to existing live site and users capturing data

**Comment by timlinux** [comment]
Can we hold this over to next week so @dimasciput can focus on the Biobase stuff otherwise the poor chap is going to be trying to deal with too many different issues at once?

**Comment by dimasciput** [comment]
@helendallas I will set all boxes unchecked instead, so it will get all data.
