### ISSUE TITLE
Geocontext data not visible on Live Site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1898]
A user added SASS data - geo context data did not appear after saving.
@NyakudyaA Please can you check why?
@dimasciput 

![Screenshot_2020-02-19 FBIS Map](https://user-images.githubusercontent.com/45286876/74837768-e7bee280-532a-11ea-8d80-6d741e3b757a.png)

![Screenshot_2020-02-19 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/74837870-1c329e80-532b-11ea-81cb-df74abd1fe3d.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/74837915-366c7c80-532b-11ea-99dc-3234a695c93a.png)

Sorry neither download or image seems to be displayed  - catchments, management areas, ecoregions and provinces are all listed as Undefined.

**Comment by dimasciput** [comment]
@helendallas please also paste the link, so it's easier for us to check the bug. If this is a new site, it might take some time to get all data from GeoContext.

**Comment by helendallas** [comment]
@dimasciput 
I cant see how to copy the link when I am on the SASS dashboard. Yes it is a new site. I will check again later

**Comment by helendallas** [comment]
http://freshwaterbiodiversity.org/sass/dashboard/31388/?taxon=&search=A2APIE-ERASM&siteId=31388&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=[%22validated%22]&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=31388&orderBy=name

**Comment by timlinux** [comment]
Yes you can see it populating now:

![image](https://user-images.githubusercontent.com/178003/74845012-403fb100-5326-11ea-9bd8-77eb59900c48.png)


In order to make that instant, we would need to do some performance tuning on the geocontext side.

**Comment by timlinux** [comment]
I guess the WMS's are still coming in...

**Comment by dimasciput** [comment]
Yes the water management area from geocontext is broken, I already asked @NyakudyaA about this. 
The link https://geocontext.kartoza.com/api/v1/geocontext/value/group/28.2409948111/-25.8186723606/water_management_area/

**Comment by NyakudyaA** [comment]
> Yes the water management area from geocontext is broken, I already asked @NyakudyaA about this.
> The link https://geocontext.kartoza.com/api/v1/geocontext/value/group/28.2409948111/-25.8186723606/water_management_area/

I have fixed it @dimasciput

**Comment by dimasciput** [comment]
@helendallas please check the dashboard again

**Comment by helendallas** [comment]
@dimasciput All populated now, thanks
