### ISSUE TITLE
We need a simple spreadsheet uploader

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1902]
**Two phases:**

**Phase 1:**

* Just a simple button with a link to the template spreadsheet
* FRC to add a header row in the sheet with detailed notes (or maybe we can do this in a new flatpage) for each column's requirements
* FRC to add dropdowns etc. for columns e.g. for geomorphological zones to ensure data is captured cleanly
* user sends spreadsheet to FRC who then liaise with Kartoza to manage importing process.

**Phase 2:**

As above but the last step is completed by having an upload page for the spreadsheet which the user or FRC can upload the prepared data directly.

Note this is not in scope for v4.

CC @jeremyshelton

**Comment by helendallas** [comment]
Closing as already actioned.
