### ISSUE TITLE
We need a dams layer

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1913]
@NyakudyaA can we add a layer for SA dams?

**Comment by NyakudyaA** [comment]
> @NyakudyaA can we add a layer for SA dams?

We already have it, you can just specify where you need the layer to be added. As a map layer, spatial filter?

https://maps.kartoza.com/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:dams500g&styles=&bbox=18.3333282470703,-34.7518119812012,32.8811225891113,-22.1872138977051&width=768&height=663&srs=EPSG:4326&format=application/openlayers

**Comment by jeremyshelton** [comment]
Cool. I think just as a map layer. thanks

**Comment by NyakudyaA** [comment]
This has been added in live site
![dams](https://user-images.githubusercontent.com/2510900/75251110-9b6c1a80-57e2-11ea-8750-aaf4040b05ed.png)
