### ISSUE TITLE
Investigate why they are multiple repeated values for geomeophological zone in spatial filter

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#1914]
# problem

When doing spatial filter you can see they are repeated values here.
![spatial-filter](https://user-images.githubusercontent.com/2510900/75258402-10dde800-57ef-11ea-8a28-04c8acdc75e8.png)

**Comment by NyakudyaA** [comment]
@dimasciput I am not sure why we have duplicated values from the above. In the DB it looks fine
![no-repetition](https://user-images.githubusercontent.com/2510900/75262180-d119ff00-57f4-11ea-9dd9-a12b26205573.png)

**Comment by NyakudyaA** [comment]
This should be fixed by updating the geocontext. You can close this after testing @jeremyshelton

**Comment by jeremyshelton** [comment]
@NyakudyaA OK thanks, will do.

**Comment by helendallas** [comment]
Checked, fixed, closed
