### ISSUE TITLE
User experience: navigating map and visualising spatial layers

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1931]
@dimasciput @timlinux @NyakudyaA the following came to my attention when exploring the map and spatial layers/filters:
1. On the map, can we use a double-click to zoom in and a right click on the layer to show layer properties? (at the moment a double click seems to do both, which is confusing?)
2. To me it still seems odd to not see the actual spatial layer on the map when a filter is selected. The red outlines don't give quite the same user experience as actually seeing the real layer that one is filtering with....what do you guys think?

For example, if we select Ecoregion level 1, we see the following:
Layer:

<img width="1440" alt="Screenshot 2020-03-01 at 10 28 17" src="https://user-images.githubusercontent.com/44292029/75622320-878c3400-5ba7-11ea-899b-85edb1e262a7.png">

Filter:

![Uploading Screenshot 2020-03-01 at 10.28.26.png…]()

To me the red lines are not that helpful, and I would rather see the actual layer that I am using to filter.

**Comment by dimasciput** [comment]
Let's park this ticket, I'm not sure how to achieve this now.

**Comment by jeremyshelton** [comment]
@dimasciput ok sure. Ticket closed.
