### ISSUE TITLE
Ecoregion 2 layer not showing on map

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1932]
@dimasciput @NyakudyaA when I select the Ecoregion level 2 layer it does not show on the map

<img width="1440" alt="Screenshot 2020-03-01 at 10 36 47" src="https://user-images.githubusercontent.com/44292029/75622426-a8a15480-5ba8-11ea-876f-65eff6756a5a.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton this is working now
![fixed](https://user-images.githubusercontent.com/2510900/75626406-ff6e5480-5bcf-11ea-9404-c75f95dd9de7.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA yeah OK thanks for fixing 👍
