### ISSUE TITLE
Strategic water source areas layer - all areas showing the same colour

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1933]
@dimasciput @NyakudyaA 

Surely each of the different water source areas should show a different colour? 
<img width="1440" alt="Screenshot 2020-03-01 at 10 41 00" src="https://user-images.githubusercontent.com/44292029/75622478-5ca2df80-5ba9-11ea-9e30-73ebebbc3ce8.png">

I would expect to see something more like this:
<img width="461" alt="Screenshot 2020-03-01 at 10 43 27" src="https://user-images.githubusercontent.com/44292029/75622487-89ef8d80-5ba9-11ea-9101-aa68c4e59ff3.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton here is the list of attributes for the layer.
![attributes](https://user-images.githubusercontent.com/2510900/75624164-7dbffc00-5bba-11ea-8064-b341ed18b462.png)

I have styled it using the name 
![areas-surfaces](https://user-images.githubusercontent.com/2510900/75624437-c082d380-5bbc-11ea-8882-7650665c9d6d.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA OK thanks. Looks good 👍
