### ISSUE TITLE
Strange-looking tables for NFEPA fish sanctuaries

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1934]
@NyakudyaA @dimasciput the layers in these spatial filter drawers look odd?

<img width="280" alt="Screenshot 2020-03-01 at 10 52 26" src="https://user-images.githubusercontent.com/44292029/75622601-eb642c00-5baa-11ea-819a-0d6750bcc424.png">
<img width="253" alt="Screenshot 2020-03-01 at 10 52 34" src="https://user-images.githubusercontent.com/44292029/75622600-e99a6880-5baa-11ea-85ae-8aefe2b11fc3.png">

**Comment by NyakudyaA** [comment]
@jeremyshelton same story here with the attributes from upstream
![fish_sanc_all](https://user-images.githubusercontent.com/2510900/75624548-e9579880-5bbd-11ea-9466-77c005972101.png)

![river-condition](https://user-images.githubusercontent.com/2510900/75624554-faa0a500-5bbd-11ea-8960-88f68ad301a5.png)

Maybe we should make a decision not to show the filter with attributes that will be confusing to the users unless you can ping the guys from sanbi about the attributes you expect on the nfepa layers

**Comment by jeremyshelton** [comment]
@NyakudyaA yeah I don't think that is useful for the user & thus may be better to hide. @timlinux thoughts on this?

**Comment by jeremyshelton** [comment]
@NyakudyaA I would expect that each fish sanctuary would have a code, and that is what we would want to display to the user. Can you confirm that each fish sanctuary does not have a unique code?

**Comment by NyakudyaA** [comment]
> @NyakudyaA I would expect that each fish sanctuary would have a code, and that is what we would want to display to the user. Can you confirm that each fish sanctuary does not have a unique code?

Hi, @jeremyshelton I have had a look at the metadata for this,  there is a lookup table with the species code which I can add for all sanctuaries. But you will still need to check which column you need to use
![fish_sanc](https://user-images.githubusercontent.com/2510900/75957546-efea5680-5ec2-11ea-8244-c63657a38ade.png)

[NFEPA_metadata_fishsanctuaries_all.pdf](https://github.com/kartoza/django-bims/files/4291488/NFEPA_metadata_fishsanctuaries_all.pdf)

**Comment by NyakudyaA** [comment]
@jeremyshelton I have created a lookup here
![lookup](https://user-images.githubusercontent.com/2510900/75964352-c4ba3400-5ecf-11ea-9e77-5dfdb21f7408.png)

When you have decided which attribute you will use then ping me and will update the table

**Comment by NyakudyaA** [comment]
Ping @jeremyshelton still waiting for your input here

**Comment by jeremyshelton** [comment]
@NyakudyaA we (myself and @helendallas) still have to decide which attributes to show for lots of the layers. For now, let's focus on this one. My understanding is that there are different categories of fish sanctuaries based on the number of threatened species found in the river. See explanation [here](http://biodiversityadvisor.sanbi.org/planning-and-assessment/environmental-assessments/using-bgis/using-bgis-to-determine-if-your-farm-falls-within-a-fish-sanctuary/). I think we need to see if we can get those categories from the shape file? Can you see anything that  might fit that description?

**Comment by jeremyshelton** [comment]
We basically want to be able to filter by these different categories of fish sanctuary available via BGIS:

![Screenshot 2020-04-15 at 17 02 50](https://user-images.githubusercontent.com/44292029/79353207-0ad8cd80-7f3b-11ea-949e-981132e85db2.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA I think we can remove all the wetland layers for now and just focus on these two: (1) Fish sanctuaries (all species) and (2) Fish sanctuary. You can follow the link (in my previous ticket) to the BGIS Map viewer, where these layers can be viewed: 

![Screenshot 2020-04-16 at 14 48 27](https://user-images.githubusercontent.com/44292029/79458195-c3f9df00-7ff1-11ea-80e4-181fae631620.png)

**Comment by NyakudyaA** [comment]
@jeremyshelton You can remove the layers you do not need in the map viewer https://freshwaterbiodiversity.org/admin/bims/nonbiodiversitylayer/

![fish-sanc](https://user-images.githubusercontent.com/2510900/79746996-35e06a00-830b-11ea-987e-6b18eab27bf9.png)

**Comment by jeremyshelton** [comment]
@NyakudyaA OK, will do 👍

Any progress with correcting the Fish sanctuaries (all species) and Fish sanctuaries layers?

**Comment by NyakudyaA** [comment]
> @NyakudyaA OK, will do +1
> 
> Any progress with correcting the Fish sanctuaries (all species) and Fish sanctuaries layers?

That legend is the same as the SANBI site. anything you need me to change there

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA 

Layer looks good!

Filter still has odd-looking categories in the drawers. Maybe we just hide these?

<img width="308" alt="Screenshot 2020-04-21 at 14 44 47" src="https://user-images.githubusercontent.com/44292029/79867466-aad0a400-83de-11ea-89e3-5a17e1e2ce40.png">

**Comment by NyakudyaA** [comment]
> Thanks @NyakudyaA
> 
> Layer looks good!
> 
> Filter still has odd-looking categories in the drawers. Maybe we just hide these?
> 
> <img alt="Screenshot 2020-04-21 at 14 44 47" width="308" src="https://user-images.githubusercontent.com/44292029/79867466-aad0a400-83de-11ea-89e3-5a17e1e2ce40.png">

The values need to be updated in geocontext cc @dimasciput

**Comment by jeremyshelton** [comment]
Closing this ticket as this issue is covered in: FILTERS & LAYERS (V4 testing) #2052
