### ISSUE TITLE
Master List  - Aquatic invertebrates

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1935]
@dimasciput 

Is it possible to extract the Scientific name and Authority for the taxa in the list - where they are on GBIF, and add it as a new column to my Master spreadsheet. This will allow me to cross check the taxa.

I could carry on editing for another week or so but am aware of the time deadline and don't want to hold the importing of the invertebrate species data up.

Here is the link to the **FBIS Invertebrate Master List Final 2020 03 02 All in Southern Africa.xlsx**
https://www.dropbox.com/sh/u302jtojrjbrlj3/AABJHOtx_lsZ1H4yukzfzoAca?dl=0

It includes some taxa without records in South Africa  - which I would like to leave in, but exclude using the South Africa as a filter.  Is this possible?

**Comment by dimasciput** [comment]
> It includes some taxa without records in South Africa - which I would like to leave in, but exclude using the South Africa as a filter. Is this possible?

I'm not sure I fully understand, we can only filter collection records, so as long as there aren't taxa in the South African records, they won't be found.

**Comment by helendallas** [comment]
@dimasciput 

Yes I know they wont be fond but I am thinking forward where some species in the master list may be recorded in the future and added to GBIF and also for when FBIS is perhaps expanded to southern Africa. Then it saves me having to redo this master list for some groups.

If it really doesnt make sense to you then I can edit them out and send you one for SA only and keep the Southern Africa one offline.

Thoughts?

**Comment by dimasciput** [comment]
@helendallas yes I think it would be better to just ingest the SA data for now, we can always add new taxa later.

**Comment by helendallas** [comment]
@dimasciput Okay, I will revise and upload new master

**Comment by dimasciput** [comment]
@helendallas what is in the Distribution column?

**Comment by helendallas** [comment]
@dimasciput I am revising the master. The distribution column is for future validation. I think it best that we serve all the data but it will take some more time to clean the data. Just because there is no record at the moment in GBIF, does not mean it has not been recorded in South Africa, as many taxa are not yet on GBIF. Invertebrates don't use country borders, so from a biological perspective it makes sense to view Southern Africa holistically. You can just bring in the records in South Africa, using your filter as you have done with fish.

**Comment by helendallas** [comment]
@dimasciput 

I have revised the Invertebrate Master file. I have excluded those taxa that are noted as being outside of South Africa. I have removed extra columns so that it now matches the fish master list with the exception of :

- Common Name - not included for Invertebrates
- SubSpecies - included immediately after species and only SubSpecies provided in the column
- Former scientific names - these are not separate columns, but rather combined in one column; separated by a semi-colon.

The Scientific name and authority -  is incomplete. Please can you grab these from GBIF where they exist and add a new column to our sheet for the future and for comparison please.  Please remember ticket re including higher taxonomy such as family in the grab so that the correct authority is returned.

Endemism - this has not been completed. Aneri will be working on it over the next week. Can we add later?

Conservation status - please grab this from IUCN where the data exists for taxa. I think it may only be for some Odonata. Again please add back to our master list.

File is: SA Invertebrate Master List FBISv3_03 Mar 2020.xlsx
Link is:
https://www.dropbox.com/sh/u302jtojrjbrlj3/AABJHOtx_lsZ1H4yukzfzoAca?dl=0

**Comment by dimasciput** [comment]
@helendallas 

thanks, yes we can add endemism later.

**Comment by dimasciput** [comment]
@helendallas @timlinux 

Doesn't origin depends on the collection record not taxonomy? 

![image](https://user-images.githubusercontent.com/1979569/75776098-e7d8cc80-5d85-11ea-9445-8cdfad98aa5a.png)

**Comment by helendallas** [comment]
@dimasciput I think I am still waiting for the updated GBIF download of invertebrate Master list so that I can cross check with mine. Please confirm

**Comment by helendallas** [comment]
@dimasciput @timlinux 

Thanks for the GBIF extracted data sent by email. Attached. 
[GBIF Extracted invertebrates 2020_03_27.xlsx](https://github.com/kartoza/django-bims/files/4392042/GBIF.Extracted.invertebrates.2020_03_27.xlsx)

This file only has 621 taxa listed. In comparison my Master file has 3773, of which around 3000 have already been previously manually checked on GBIF, and for SA records.

Please can you check why so few records have come down from GBIF.
The Master file is on our shared folder:
https://www.dropbox.com/s/hqcodomk003oeis/SA%20Invertebrate%20Master%20List%20FBISv3_27%20Mar%202020%20Edited%20for%20Ingestion.csv?dl=0

PLease cna you check urgently as I need to do this today.

**Comment by dimasciput** [comment]
@helendallas ah ok, it was actually all the invert data that was ingested to our system which have collection record. 

Let me ingest the master list first, I'm not sure if I can finish it today, will weekend or Monday fine work for you?

**Comment by helendallas** [comment]
@dimasciput Please do as soon as you can, I can tackle on monday as I realise it is quite a task. Thanks

**Comment by dimasciput** [comment]
@helendallas will do, my electricity goes out, so I will work on Bims tickets this weekend.

**Comment by dimasciput** [comment]
Hi @helendallas here's the file : 
[invertebrates.csv.zip](https://github.com/kartoza/django-bims/files/4394200/invertebrates.csv.zip)

There are 3046 data, I'm not sure why it's missing like 700 data. Maybe can you check what's missing from Excel.

**Comment by dimasciput** [comment]
And is this really important right now? Because I have other things to do like ingesting the sites and fixing the bugs. If this is more important than that, I can focus on this first.

**Comment by helendallas** [comment]
@dimasciput @timlinux 
The quality of the data hinges on the accuracy of the master list, so yes it is very important. Not only does it speak to the integrity of the FBIS data, but it will also serve as the master list for future harvesting of the GBIF invertebrate data.

It is going to take me a long time to systematically work through these lists, so far I have picked up the following issues:
Scientific name & Authority - is often strange due to specific symbols etc.

Berosus   corrugatus RÃ©gimbart, 1906
--
Berosus crassipes SchÃ¶dl,   1995
Berosus cuspidatus Erichson,   1843
Berosus dunguensis SchÃ¶dl,   1994
Berosus furcatus Boheman, 1851
Berosus maximiliani SchÃ¶dl,   1994
Berosus neumanni Knisch, 1922
Berosus obesus SchÃ¶dl, 1995
Berosus pudens   J.Balfour-Browne, 1954
Berosus punctulatus Boheman,   1851
Berosus rubiginosus Kuwert,   1890
Berosus spretus J.Balfour-Browne, 1954
Berosus tetracanthus RÃ©gimbart, 1906

More to follow once I have gone through more records

**Comment by dimasciput** [comment]
@helendallas ok then I probably need to fix my script, I was thinking this is just an optional ticket so I only write a quick script to ingest species then fetch the gbif. Most of these species won't be available to the general user because they don't have collection data.

**Comment by dimasciput** [comment]
@helendallas is this more important than ingesting the collection data? If so then I can focus on this first. It probably will take half-day.

**Comment by helendallas** [comment]
@dimasciput yes this is extremely important. I have just spent an entire day wading through your data compared to my data and I am only one quarter of the way. Many issues.  I dont want to have to waste my time unnecessarily, so please confirm once the scrip has been improved and tested form your side.

I am showing the two fields for your information so that you can get a sense of what the issues are:
My master list includes extra columns that I have on my version, but delete before sending to you.

The colour coding is as follows:
Green shading - master and GBIF list match
Red shading - Synonymous names
Blue shading - In master, but not on GBIF
Orange shading -  problem, either missing or wrong taxon

[Invertebrates extracetd from GBIF 2020_30.xlsx](https://github.com/kartoza/django-bims/files/4403067/Invertebrates.extracetd.from.GBIF.2020_30.xlsx)


[SA Invertebrate Master List FBISv3_27 Mar 2020.xlsx](https://github.com/kartoza/django-bims/files/4403061/SA.Invertebrate.Master.List.FBISv3_27.Mar.2020.xlsx)

**Comment by dimasciput** [comment]
@helendallas ok what should we do if it's red, blue or orange?

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 

So Tim and I made this diagram of how we ingest the species in the background, I hope you can get a better idea how complicated the process is. I'm still working on it right now, hopefully I can finish it tomorrow.

https://files.slack.com/files-pri/T9ZKRM41X-F0113QEN5AL/bims-name-resolution.png

**Comment by helendallas** [comment]
@dimasciput Thanks, I am sure it is. Sorry I am not using slack

**Comment by helendallas** [comment]
@dimasciput I have decided to check through all the records that you extracted from GBIF. It is a good double check for the taxon master list, so although it is taking a while to do, I believe it iwill be worth it.
I should finish this tomorrow.

**Comment by helendallas** [comment]
@dimasciput 
The red ones seems to come through with the new name automatically. Please check why orange are not coming through. It seems it is sometimes:
- Exists on GBIF but not brought down? e.g. Afronemoura spinulata (Balinsky, 1967)
- Is a SubSpecies: e.g. Agriocnemis angolensis subsp. angolensis ; Agriocnemis angolensis subsp. spatulae Pinhey, 1974
- Higher order taxon - e.g. Order Anostraca
- Sometimes brings incorrect higher taxon as indicated previously, e.g. Crambidae, toehr examples below:

Animalia | Chordata | Reptilia | - | - | Ceratophallus | - | Ceratophallus | Ceratophallus Cope, 1893 | https://gbif.org/species/8281867 | Wrong taxon, should be Mollusca,   Gastrapoda, Planorbidae

Animalia | Porifera | Demospongiae | Poecilosclerida | Crambidae | Calamoschoena | - | Calamoschoena | Calamoschoena Hampson, 1916 | https://gbif.org/species/1883694 | Wrong higher taxonomy, should be   Arthropoda, Insecta, Lepidoptera

Animalia | Porifera | Demospongiae | Poecilosclerida | Crambidae | Calamoschoena | Calamoschoena stictalis | Calamoschoena stictalis | Calamoschoena stictalis Hampson, 1919 | https://gbif.org/species/1883695 | Wrong higher taxonomy, should be Arthropoda, Insecta,   Lepidoptera


Animalia | Chordata | Mammalia | Cetacea | Balaenidae | - | - | Balaenidae | Balaenidae | https://gbif.org/species/9682 | This   is a mammal- whale!

**Comment by dimasciput** [comment]
[extracted-inverts.zip](https://github.com/kartoza/django-bims/files/4414017/extracted-inverts.zip)

**Comment by helendallas** [comment]
@dimasciput Thanks. I have gone through all of these and picked up a few issues. The issues are highlighted in orange in this file:
Invertebrates extracted from GBIF 2020_04_01 From Dimas.xlsx

[Invertebrates extracted from GBIF 2020_04_01 From Dimas.xlsx](https://github.com/kartoza/django-bims/files/4415584/Invertebrates.extracted.from.GBIF.2020_04_01.From.Dimas.xlsx)

There are still fewer records ( 3690, minus a few that need to be deleted) here compared to the master list ( 3739)

**Comment by helendallas** [comment]
@dimasciput Final Master list is:
SA Invertebrate Master List FBISv3_2020_04_01.xlsx

In this folder:
https://www.dropbox.com/s/03i0aq08phvm7af/SA%20Invertebrate%20Master%20List%20FBISv3_2020_04_01.xlsx?dl=0

I have included the extra columns used for editing, they are not needed in import,
(On GBIF | South Africa records | Comments | Source | Taxon Rank)

**Issue with below remains.**
Scientific name & Authority - is often strange due to specific symbols etc.
Berosus corrugatus RÃ©gimbart, 1906

Berosus crassipes SchÃ¶dl, 1995
Berosus cuspidatus Erichson, 1843
Berosus dunguensis SchÃ¶dl, 1994
Berosus furcatus Boheman, 1851
Berosus maximiliani SchÃ¶dl, 1994
Berosus neumanni Knisch, 1922
Berosus obesus SchÃ¶dl, 1995
Berosus pudens J.Balfour-Browne, 1954
Berosus punctulatus Boheman, 1851
Berosus rubiginosus Kuwert, 1890
Berosus spretus J.Balfour-Browne, 1954
Berosus tetracanthus RÃ©gimbart, 1906

**Comment by helendallas** [comment]
@dimasciput 
The first testing I did on testing site, and downloaded the csv files and I get this!

Lestagella is not a plant!!!!

Please revert asap


Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon

Plantae | Tracheophyta | Magnoliopsida | Ranunculales | Papaveraceae | Lestagella | penicillata | Lestagella penicillata

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Lestagella%20penicillata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Also why is this species listed as Native and unspecified....it should  be based on the master list, where it is listed as native.
![Screenshot_2020-04-15 FBIS Map](https://user-images.githubusercontent.com/45286876/79328871-06022280-7f17-11ea-8585-5804890571d3.png)
![Screenshot_2020-04-15 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/79328891-10242100-7f17-11ea-865c-56b333a05601.png)

**Comment by helendallas** [comment]
Still random issues with taxonomy, even when no possibility of misclassification in GBIF.

E,g, From FBIS testing site:

Fungi | Basidiomycota | Agaricomycetes | Agaricales | Cortinariaceae | Chimarra | Cortinarius sp.7973 | **Chimarra**

Should be : 
Animalia | Arthropoda | Insecta | Trichoptera | Philopotamidae | Chimarra | Unspecified | **Chimarra**

Only two options in GBIF and both Family Philopotamidae
![Screenshot_2020-04-16 Succineidae](https://user-images.githubusercontent.com/45286876/79445593-3613f900-7fdd-11ea-891a-cb1fe64a9704.png)

Another example:
E,g, From FBIS testing site:
Fungi | Basidiomycota | Agaricomycetes | Agaricales | Cortinariaceae | Dolophilodes | urceolus | Dolophilodes urceolus

Should be : 
Animalia | Arthropoda | Insecta | Trichoptera | Philopotamidae | Dolophilodes | urceolus | Dolophilodes urceolus

![Screenshot_2020-04-16 Succineidae(1)](https://user-images.githubusercontent.com/45286876/79445864-a458bb80-7fdd-11ea-8b66-49a4e49aca3e.png)

**Comment by dimasciput** [comment]
Thanks @helendallas , it should be fixed when I reingested all the species list tomorrow.

**Comment by helendallas** [comment]
@dimasciput Great thanks

**Comment by helendallas** [comment]
Still duplicate taxa in testing site - with different Origin, Endemism and /or Conservation status
![Screenshot_2020-04-20 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/79758595-e0fa1f00-831d-11ea-9a22-38ca1ce18a8d.png)

**Comment by helendallas** [comment]
@dimasciput The master file looks like it has imported correctly on testing. No more duplicates. Thanks

**Comment by helendallas** [comment]
Closing ticket even though the data still needs to be ingested to live site.

**Comment by helendallas** [comment]
Duplicate taxa back in testing site

![Screenshot_2020-04-28 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/80493814-2cd44600-8966-11ea-9e92-a2bff5711a9b.png)

**Comment by dimasciput** [comment]
@helendallas it's not duplicated, just one taxa with different origin. Let me fix it quickly.

**Comment by helendallas** [comment]
@dimasciput There a re several taxa. The origin needs to come from my master list, then duplicates should be resolved. I see Aeshna and Aeschna are spelt differently

**Comment by dimasciput** [comment]
@helendallas 
> @dimasciput There a re several taxa. The origin needs to come from my master list, then duplicates should be resolved. I see Aeshna and Aeschna are spelt differently

I will do a quick temporary fix on the testing, but when we ingest data to live site this wouldn't be an issue.

**Comment by helendallas** [comment]
@dimasciput Thanks, closing now
