### ISSUE TITLE
Biobase - Replace Biobase taxon name with Correct Taxon Name

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1936]
@dimasciput 
In doing the master list I picked up quite a few errors in the Biobase Taxon Names.

Please can you replace the Biobase Taxon Names in the spreadsheet below, with the Correct Taxon Names for FBIS.

[Biobase Taxon Data for Correcting.xlsx](https://github.com/kartoza/django-bims/files/4276231/Biobase.Taxon.Data.for.Correcting.xlsx)

Link: https://www.dropbox.com/s/zlekzjvf1x7c4hy/Biobase%20Taxon%20Data%20for%20Correcting.xlsx?dl=0

**Comment by dimasciput** [comment]
@helendallas I'm not sure what should I do, is the red one the name of the taxon it should be?
 It seems it's already using the name in the red column in http://freshwaterbiodiversity.org/

**Comment by helendallas** [comment]
@dim yes the Red column is the correct one. The differences are subtle....e.g. 

Triaenodes   falculat**a** | Triaenodes falculat**us**

Please just run on FBIS live and where Biobase Taxon Name =  taxon listed in black; search and replace with Correct   Taxon Name in FBIS = taxon listed in red.

**Comment by helendallas** [comment]
@dimasciput I am assuming the new taxa will still need to harvested from GBIF as I am not seeing these species yet.

**Comment by dimasciput** [comment]
@helendallas yes that's correct, it will be updated with the value from gbif if the data is found.

**Comment by helendallas** [comment]
@dimasciput Please update me on this - Is it in the live version.

**Comment by dimasciput** [comment]
Yes, it's on live site, please check it.

**Comment by timlinux** [comment]
See also #1887

**Comment by helendallas** [comment]
Closing ticket as I need to check on live site and edit taxa in admin section once FBIS finalised
