### ISSUE TITLE
Abiotic Data - Names displayed

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1943]
@dimasciput 

Please confirm you have included the name as per the FBIS_Name as per the file linked here.
https://www.dropbox.com/s/pt31d9b87b5jcvw/Master%20List%20of%20Abiotic%20Data%20Variables%20with%20FBIS%20Names%20and%20Validation%20Limits%202020_02_25.xlsx?dl=0

Master List of Abiotic Data Variables with FBIS Names and Validation Limits 2020_02_25.xlsx

Also we needed to add in three new variables to be displayed please. They are highlighted in the spreadsheet.

Ammonia   nitrogen
Chlorophyll   a: water column
Chlorophyll a: benthic

**Comment by dimasciput** [comment]
@helendallas yes they are coming from the master list, you can add new unit here : http://freshwaterbiodiversity.org/admin/bims/chem/

**Comment by helendallas** [comment]
@dimasciput Thanks added, I can add new unit...needs to be mg/m2

milligrams per metre squared.  Wont accept.  For Chlorophyll a: benthic

**Comment by helendallas** [comment]
@dimasciput 
Also can we edit descriptions here?

**Comment by dimasciput** [comment]
@helendallas 

> milligrams per metre squared. Wont accept. For Chlorophyll a: benthic
Ah yes, I need to do it from the system, will have to wait. I'm still working on importing algae data. 

> Also can we edit descriptions here?
Yes you can

**Comment by helendallas** [comment]
thanks

**Comment by dimasciput** [comment]
@helendallas Are there important units that might be added in the future?

**Comment by helendallas** [comment]
@dimasciput 
I hope we have got most of them, but there may be some I am not aware of.

We will manually revise the Chem description, so please ignore earlier request.

**Comment by dimasciput** [comment]
@helendallas @Aneri16 

The mg/m2 unit has been added to the system.
