### ISSUE TITLE
River Management Unit - add to Layer Selector

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1953]
@NyakudyaA 
Please can you add the River Management Unit to the Layer Selector - immediately after Sub  Water management Area

**Comment by NyakudyaA** [comment]
![rmu](https://user-images.githubusercontent.com/2510900/76068935-bd139180-5f9a-11ea-95e7-f9717e79d50c.png)

done @helendallas

**Comment by helendallas** [comment]
@NyakudyaA 
Thanks - live or testing site. Not yet visible my side?

**Comment by helendallas** [comment]
@NyakudyaA okay seen it, need to just shift it into place. I will do now that I know how :)

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> Thanks - live or testing site. Not yet visible my side?

We agreed that adding layers should be done directly on live site. Glad you can see it
