### ISSUE TITLE
Layers - CBAs

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1954]
@NyakudyaA @jeremyshelton 
The layer currently in the Layer Selector is:
National Critical Biodiversity
![Screenshot_2020-03-06 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/76071382-cbfc4300-5f9e-11ea-8b78-72a94aab0981.png)

How does this relate/match the ones in the filters:

![Screenshot_2020-03-06 FBIS Map](https://user-images.githubusercontent.com/45286876/76071404-d61e4180-5f9e-11ea-941e-232c5536c59e.png)

**Comment by NyakudyaA** [comment]
@helendallas 

![national-cba](https://user-images.githubusercontent.com/2510900/76072112-10d4a980-5fa0-11ea-81d0-9aa4f7af028b.png)


The selected layer is the one visible in the layer selector. All the other layers are not shown in the layer selector

**Comment by helendallas** [comment]
@NyakudyaA Thanks, got it now
