### ISSUE TITLE
Cannot assign username due to errors

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1957]
I am struggling to activate a new user due to errors with the user name. What is wrong with the username as it meets the requirements?
See below:

![User name error](https://user-images.githubusercontent.com/55532903/76281947-fdc32180-629e-11ea-9998-d7ce50226eed.png)

**Comment by dimasciput** [comment]
@Aneri16 username cannot have spaces, see other users for example in the admin page. Treat it like username in github or  instagram.

**Comment by Aneri16** [comment]
@dimasciput Thanks got it
