### ISSUE TITLE
Testing - SASS data editing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1959]
@dimasciput 
The order of the SASS taxa seem to have changed for the SASS form when I go in and edit.

For example:
![Screenshot_2020-03-12 FBIS SASS](https://user-images.githubusercontent.com/45286876/76497057-f8064100-6442-11ea-91f1-1b9baee1e20f.png)

Should be:
![Screenshot_2020-03-12 FBIS SASS(1)](https://user-images.githubusercontent.com/45286876/76497107-09e7e400-6443-11ea-8763-c08901d3017f.png)

And incorrect - testing:
![Screenshot_2020-03-12 FBIS SASS(2)](https://user-images.githubusercontent.com/45286876/76497529-d22d6c00-6443-11ea-8ebf-6773ef0ff817.png)

Should be :
![Screenshot_2020-03-12 FBIS SASS(3)](https://user-images.githubusercontent.com/45286876/76497534-d6f22000-6443-11ea-9932-9c9181ff0c35.png)

**Comment by dimasciput** [comment]
@helendallas can you test it again?

**Comment by helendallas** [comment]
@dimasciput looks fine now.
