### ISSUE TITLE
Testing - SASS Taxa per Biotope

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1960]
@dimasciput 

The latest SASS Taxa per Biotope is incorrect on the testing site.  Here is the testing site:
![Screenshot_2020-03-12 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/76498311-4b798e80-6445-11ea-85dc-6045cc8445c4.png)

Here is the live site data: 
![Screenshot_2020-03-12 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/76498342-5d5b3180-6445-11ea-881a-8615318ff404.png)

When you view the details - they are the same:
testing site:
![Screenshot_2020-03-12 FBIS SASS(4)](https://user-images.githubusercontent.com/45286876/76498436-88458580-6445-11ea-9563-60f349f6a851.png)

live site:
![Screenshot_2020-03-12 FBIS SASS(5)](https://user-images.githubusercontent.com/45286876/76498441-8b407600-6445-11ea-81eb-1f04ed23f11f.png)

**Comment by dimasciput** [comment]
@helendallas can you paste the url here?

**Comment by helendallas** [comment]
https://testing.healthyrivers.kartoza.com/sass/view/11029/

**Comment by dimasciput** [comment]
Can you check it again @helendallas ?

**Comment by helendallas** [comment]
@dimasciput 
![Screenshot_2020-03-12 FBIS SASS(7)](https://user-images.githubusercontent.com/45286876/76517092-4cbab380-6465-11ea-81fc-ac636402274f.png)

not yet fixed, coleoptera fixed
![Screenshot_2020-03-12 FBIS SASS(8)](https://user-images.githubusercontent.com/45286876/76517118-5cd29300-6465-11ea-8c48-5c31e64c4f5b.png)

https://testing.healthyrivers.kartoza.com/sass/update/11029/

**Comment by dimasciput** [comment]
@helendallas can you test it again?

**Comment by helendallas** [comment]
@dimasciput all working
