### ISSUE TITLE
Validating Records - add reject button and FBIS Site Code

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1964]
Please add option to reject record.
Please add FBIS Site Code

**Comment by helendallas** [comment]
@dimasciput When I hit the X button, nothing happens
@dimasciput Also please dont close issue until we have checked it is working

**Comment by dimasciput** [comment]
@helendallas yes, I accidentally closed the issue, that's why I reopened it again.

**Comment by dimasciput** [comment]
@helendallas please try again, it just takes some time to update in testing
