### ISSUE TITLE
Site codes not showing/generated for new ingested invert data

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1966]
When searching by collector name for the new invert data that was ingested, site codes are not displayed under the Sites tab, only occurrence for each site is displayed.
@dimasciput @helendallas 

![Site codes not showing](https://user-images.githubusercontent.com/55532903/76852430-f7f7ae00-6853-11ea-8264-7763816ce205.png)

**Comment by dimasciput** [comment]
@Aneri16 yes, already answered this in another thread. Basically I didn't run the script to get the site codes, since this is only testing site it will be wasteful of resources. But I can do that if you need it.

**Comment by Aneri16** [comment]
@dimasciput 
Okay thanks, makes sense! I didn't see the other thread.
