### ISSUE TITLE
Algae testing - dropdown options

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1967]
Hi @dimasciput ,

I have noticed that several dropdown options are incorrect/incomplete when I want to add algae data to a site. 

Please add/change the following dropdown options to:
*Add **Artificial substrate** to "Broad biotope" 
*Add **Artificial** to "Substratum"
*Change "Sampling method" dropdown to the following list: Unspecified, Multiple, Scrubbing, Soft bottom, Vegetation, In situ.
*Add **Frozen** to "Curation Process" list
*Change the "sampling location" dropdown options for Chl A biomass indicator to: Whole cobble; Soft bottom; **In situ**; **Artificial substrate**.
*Change the "sampling location" dropdown options for AFDM biomass indicator to: Whole cobble; Soft bottom; **Artificial substrate**
*Change "Abundance" dropdown options to: Species valve/frustule count; Percentage abundance; Density (cells/m2); Density (cells/mL)

On a related topic, I see that there is no space/box to enter the abundance data and observed data. Is this correct? Screenshot below:

![image](https://user-images.githubusercontent.com/45286840/76858565-59be1500-6860-11ea-8cbb-e2fd3ae3d624.png)

Many thanks.

**Comment by dimasciput** [comment]
@philipfrenzel you need to wait for the autocomplete dropdown to appear, then select that species.

**Comment by philipfrenzel** [comment]
@dimasciput thanks, could be an internet speed issue from my side at the moment. I see that the autocomplete option doesn't even feature as we speak. 

Thanks for fixing the biomass section. Looks good! I see that the other dropdown issues haven't been resolved yet (i.e. the other dropdown issues raised earlier in this thread). Can you please fix this when you have a chance?

**Comment by helendallas** [comment]
@dimasciput Dropdown options still need to be fixed as per earlier in this ticket.
![Screenshot_2020-04-17 FBIS Algae Form](https://user-images.githubusercontent.com/45286876/79552977-18599900-809c-11ea-90dc-4e09f5308654.png)


Please add/change the following dropdown options to:

- Add **Artificial substrate** to "Broad biotope"
- Add **Artificial** to "Substratum"
- Add **Unspecified** and **In situ** to "Sampling method". Change Rock scrubbing to **Scrubbing**
- Add **Frozen** to "Curation Process" list

![Screenshot_2020-04-17 FBIS Algae Form(1)](https://user-images.githubusercontent.com/45286876/79553758-468ba880-809d-11ea-9b06-773d0731db4d.png)
- Change the "sampling location" dropdown options for Chl A biomass indicator for **CHLA-B** to: **Whole cobble; Soft bottom; In situ; Artificial substrate**.
- Change the "sampling location" dropdown options for AFDM biomass indicator for **AFDM-B** to: **Whole cobble; Soft bottom; Artificial substrate**


- Change "Abundance" dropdown options to: **Species valve/frustule count; Percentage abundance; Density (cells/m2); Density (cells/mL)**

![Screenshot_2020-04-17 FBIS Algae Form(2)](https://user-images.githubusercontent.com/45286876/79553892-83579f80-809d-11ea-87eb-150820c5855c.png)

If this is generic across fish and invertebrates, then just add extras, which the user can select for algae only.

**Comment by helendallas** [comment]
@dimasciput 
This really needs to be done before we go live. None of this has been implemented on the testing or live site. Please revert soonest.

**Comment by helendallas** [comment]
@dimasciput Thanks -  all fixed except:

Change the "sampling details" dropdown options for Chl A biomass indicator for 
**CHLA-B** to:   **Whole cobble; Soft bottom; In situ; Artificial substrate.**

**Comment by dimasciput** [comment]
@helendallas added, please check again

**Comment by helendallas** [comment]
@dimasciput 
Just to fix:
![image](https://user-images.githubusercontent.com/45286876/82888151-45c21e00-9f49-11ea-9311-ea1818f4cf36.png)


Should be **Whole cobble**

**Comment by dimasciput** [comment]
@helendallas sorry, fixed

**Comment by helendallas** [comment]
@dimasciput Thanks
