### ISSUE TITLE
Algae testing - dashboard images

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1968]
Hi @dimasciput ,

I noticed that the little images for inverts and algae have disappeared on the dashboards. Can you have a look into this? Please see screenshot below: 

![image](https://user-images.githubusercontent.com/45286840/76859928-d7832000-6862-11ea-9d07-22da747d84ca.png)

**Comment by dimasciput** [comment]
Yes this is only broken in the testing, don’t worry about it. It will not transfer to the live site.
