### ISSUE TITLE
Algae testing - data query 

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1969]
Hi @dimasciput 

I have noticed that when I search for algae data on rivers that I know have algae data, no occurrences/data appear in the dashboard e.g. the Molenaars River. Screenshot below:

![image](https://user-images.githubusercontent.com/45286840/76860909-6ba1b700-6864-11ea-8c55-d4847709080e.png)

But if I search for an algal species, the data shows across multiple sites in the dashboard. Screenshot below:
 
![image](https://user-images.githubusercontent.com/45286840/76861173-d652f280-6864-11ea-9552-176cb3a24052.png)

Not sure why this is the case? Seems strange that the algal data is not visible if you do a location search, but only a species search.

@helendallas @jeremyshelton

**Comment by dimasciput** [comment]
Again this is because I didn’t fetch the river name from GeoContext. @Aneri16 @philipfrenzel @helendallas 

Please let me know if you want the data from geocontext, it will be ready by the end of the week, since the process will take some time. 

And I will do the same thing again when we deploy to the live site, all the testing data will be deleted.

**Comment by dimasciput** [comment]
All the geocontext related data include : 

- Fbis site code
- River name 
- Other spatial data e.g. geomorphological data, ecoregion data

**Comment by philipfrenzel** [comment]
Thanks for pointing that out. I wasn't 100% sure what the geocontext issue specifically related to - therefore thought I'd make a ticket for this to make you aware of it. But if this will be resolved before this version goes live, then that sounds good to me.

**Comment by dimasciput** [comment]
@philipfrenzel no worries.

So this is my workflow regarding testing and live site : 
- copy live site data to testing
- ingest data to the testing
- check data in testing, check sass form, site form, etc
- if everything is ok, then do ingestion in the live site
- fetch geocontext data in live site
- finally copy data from live to testing again

**Comment by philipfrenzel** [comment]
@dimasciput thanks for clarifying. Sounds good to me.

**Comment by dimasciput** [comment]
Will be fix by https://github.com/kartoza/django-bims/issues/1995
