### ISSUE TITLE
Weird taxon names in fish data?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1971]
@dimasciput on testing, if I select ['data source: FBIS data', 'module: fish' and 'origin:non-native',](https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=["alien"]&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=) I get a bunch of weird taxa names for non-native species like Cyprinus carpio and Oncorhynchus mykiss:

<img width="780" alt="Screenshot 2020-03-19 at 08 59 32" src="https://user-images.githubusercontent.com/44292029/77040162-14b0f480-69c0-11ea-8820-ace2c0e7bc03.png">

...but if you look at the FBIS data spreadsheet that was ingested, none of these weird taxon names exist. To me these look like GBIF taxon names, but those should only be showing when 'data source: GBIF' is selected? 

<img width="969" alt="Screenshot 2020-03-18 at 08 56 25" src="https://user-images.githubusercontent.com/44292029/76934333-9f79ec80-68f7-11ea-9fb7-30c1ef1d64d4.png">

@timlinux @helendallas @Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton I think this will be solved when we ingest new combined fish data, because the old data will be deleted.

**Comment by jeremyshelton** [comment]
@dimasciput OK, let's see. Please let us know when we can start looking at the new fish data on testing...

**Comment by dimasciput** [comment]
@jeremyshelton can you test it again

**Comment by jeremyshelton** [comment]
Looks good 👍 Closing ticket.
