### ISSUE TITLE
Need to change "Cancel" button to "Create new site"

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1973]
@jeremyshelton @dimasciput 
When adding a new site that is close to another site, the "Cancel" button should read "Create new site" instead to align with the question.
![Site co-ordinates ticket](https://user-images.githubusercontent.com/55532903/76938404-339b8200-68ff-11ea-9525-b132231ce6d6.png)

**Comment by helendallas** [comment]
Checked, and working
