### ISSUE TITLE
Add disclaimer for users when they add data

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1975]
@timlinux @dimasciput We need to add a check dox panel to all data upload forms saying 'I agree to these data being shared via the FBIS platform for visualisation and download by registered FBIS users'. I think this should be the last step in the data upload process?

@helendallas anything to add?

**Comment by helendallas** [comment]
We should include the following (@dimasciput  please switch to have URL first):

Provide URL (please add link to website where document or thesis are available online)
Upload a file 

If the user selects "Upload a file"

![Screenshot_2020-04-20 FBIS Source Reference](https://user-images.githubusercontent.com/45286876/79746265-fd8c5c00-8309-11ea-9b18-c6b02e44aadd.png)



Then the final Step should be a check box confirming that:


- [ ] **'I agree to these data being shared via the FBIS platform for visualisation and download by registered FBIS users'**
