### ISSUE TITLE
Algal testing - browser title error

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1976]
Hi @dimasciput 

A minor thing. I was trying to add algae data to a site and noticed on the browser tab that it says "fish form" (and not "Algae form"). Screenshot below:

![image](https://user-images.githubusercontent.com/45286840/76941642-110c6780-6905-11ea-987f-2c896fe33d9e.png)

Might have something to do with the fact that it's the testing site and not the live site? If irrelevant, please ignore.

**Comment by dimasciput** [comment]
Should be fixed now @philipfrenzel

**Comment by dimasciput** [comment]
In testing

**Comment by helendallas** [comment]
Thanks, working, Checked and closing
