### ISSUE TITLE
Algal testing - biomass indicators

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1977]
Hi @dimasciput ,

I am trying to add biomass indicator (i.e. Chl A and AFDM) data and see that there is only one type of data that you can add i.e. data with the mg.m2 unit. Screenshot below is the same for both the testing and the live site:

![image](https://user-images.githubusercontent.com/45286840/76973178-44b4b500-6938-11ea-9cfa-39c8e23d8fe0.png)

Under the column "Indicators", one should be able to choose between one of two Chl A options and one of two AFDM options. For Chl A, it is either CHLA-B or CHLA-W. And for AFDM, it is either AFDM-B or AFDM-W. If someone chooses either CHLA-B or AFDM-B, the measurement unit needs to automatically be **mg/m2**. If someone chooses either CHLA-W or AFDM-W, the measurement unit needs to automatically be **mg/L**. 

The "-B" stands for benthic and then the user can choose only from the following dropdown options under "sampling location": 
* For CHLA-B, the dropdown options should only be: Whole cobble; Soft Bottom; In situ and Artificial substrate. 
* For AFDM-B, the dropdown options should only be: Whole cobble; Soft Bottom and Artificial substrate.

The "-W" stands for water column and then the user can choose only from the following dropdown option under "sampling location": water column. If this can be automated, then that would be perfect i.e. if a user clicks on either CHLA-W or AFDM-W, then the "water column" options exists.

Helen has added these two types of measurement units and options in the background. @dimasciput , can you please make sure that the above-mentioned options appear when trying to add different types of biomass data on both the testing and live site?

Please let me know if there is anything unclear.

@helendallas

**Comment by dimasciput** [comment]
@philipfrenzel ok thanks, because it was not pretty clear in the first requirement.

**Comment by helendallas** [comment]
@philipfrenzel Please can you clarify:

"sampling location" is confusing as it speak to sampling site location - please can you an alternative- perhaps : sampling substrate? but then in situ? doesnt work

Please clarify what you mean by in situ with respect to this - it doesnt seem to fit with others - is it a measure by the benthotorch? 

Perhaps we can have **Detail**?  or **Sampling specifics**

Also, If I understand it correctly only CHLA-B and AFDM-B, should have these dropdowns: Whole cobble; Soft Bottom; In situ and Artificial substrate.

If CHLA-W and AFDM-W only relates to the water column then it doesnt need a dropdown?

I have asked Dimas to write in full:

**Chlorophyll A - benthic
Ash Free Dry Mass (AFDM) - benthic
Chlorophyll A - water column
Ash Free Dry Mass (AFDM) - water column**

Is this correct?

**Comment by philipfrenzel** [comment]
Hi @helendallas 

Good suggestion to make "sampling location" clearer for the biomass indicators. I think "sampling details" is a good alternative.

The "in situ" option relates to Chl A-B only and is measured with a BenthoTorch machine (alternatively known as an in situ fluorometer). The BethoTorch machine was designed to take a quick Chl A measurement whilst in the field i.e. in situ (as opposed to scrubbing rocks and taking a sample back to the lab). Unfortunately, a BethoTorch cannot measure AFDM as the process to get this value requires taking a sample back to the lab and processing it there.

In terms of the dropdown arrows for CHLA-B and AFDM-B: the dropdown options will differ because the "in situ" option only relates to CHLA-B (and not AFDM-B). But the other dropdown options are same i.e. 

* For CHLA-B, the dropdown options should only be: Whole cobble; Soft Bottom; In situ and Artificial substrate.
* For AFDM-B, the dropdown options should only be: Whole cobble; Soft Bottom and Artificial substrate.

Re the CHLA-W and AFDM-W query: correct, no dropdown option needed. "Water column" should automatically appear if this option is chosen.

Re the full names, this is correct. 

@helendallas  and @dimasciput , should I change these headings in the raw data file? I'll wait for a response before making any changes. Please let me know if you have any further questions or need me to explain something in more detail.

**Comment by dimasciput** [comment]
> @helendallas and @dimasciput , should I change these headings in the raw data file? I'll wait for a response before making any changes. Please let me know if you have any further questions or need me to explain something in more detail.

@philipfrenzel no please, for the raw data please keep using the code.

**Comment by philipfrenzel** [comment]
@dimasciput  Okay, no problem.

**Comment by helendallas** [comment]
Closing ticket, all issues captured in #1967

**Comment by helendallas** [comment]
@dimasciput @philipfrenzel 
On further discussion with Phil, please cna we explore the option of making these data linked to a Site+Sampling Date, rather than a taxon. In the same way that other Site+Sampling Date are captured and served on FBIS. 

All of the data in the screenshot below is lined to Site+Sampling Date, and it makes sense for Biomass data to be the same.

Perhaps the issue Phil / Dimas can be resolved from the data side if the sites that only have Biomass data are not ingested with Algal data, but rather captured manually by you on the live FBIS site.



![Screenshot_2020-04-20 FBIS Algae Form](https://user-images.githubusercontent.com/45286876/79743252-899b8500-8304-11ea-98ac-cfeea0db4866.png)

**Comment by helendallas** [comment]
This is Phil's explanation / justification for this:
Currently, the section which is dedicated to adding biomass data, only works if other abundance data is uploaded too. The dedicated biomass section is crucial to allow the user to specify which biomass indicator (i.e. Chl A/AFDM) they are adding as well as the sampling details (i.e. whole stone/water column/etc.) plus the correct unit.  

If adding only biomass data to a site is simplified to the “adding new taxon” route , then we need to add dropdown options such as “CHL-A – Whole Stone – mg/m2”, “CHL-A – Soft Bottom – mg/m2” etc. to a the “Abundance” block to account for all the variations of biomass data - which is somewhat confusing to me (and I’d imagine the user too).

I’d recommend that Dimas explores another way to allow the user to add biomass data (only biomass – no other data per se) via the dedicated biomass section (as opposed to “adding new taxon” route) to prevent confusion.
