### ISSUE TITLE
Algae master list - input required re certain taxa

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1983]
Hi @helendallas and @jeremyshelton 

I'll give a proper update on the algae master list on Monday during the Zoom, but I would like to ask for your input on a few algal species:

Regarding the following taxa:
* "**Craticula buderi**": If you search for this species in GBIF (https://www.gbif.org/species/8173190), the following taxonomic backbone is provided: 

![image](https://user-images.githubusercontent.com/45286840/77169473-32ff1900-6ac2-11ea-9504-d8d6fa26e5f7.png)

You will see that the genus varies (or rather that Craticula and Navicula are synonyms). What genus to I note down in the taxonomic backbone list? Craticula or Navicula? All data was recorded as Craticula.

Another aspect of this specific species is that the family classification is different even though there are species from the same genus (i.e. Craticula) in the master list. Do I keep the family classification as "Naviculaceae" (as per GBIF - screenshot above) or should I change it to "Stauroneidaceae" because all of the other species are from this family (screenshot below)?

![image](https://user-images.githubusercontent.com/45286840/77169926-faac0a80-6ac2-11ea-9de0-505a6fdcd009.png)

* "**Heteroleibleinia**": In GBIF (https://www.gbif.org/species/3217980), this species has not been assigned an order. Is it OK to leave this blank in the master list?

![image](https://user-images.githubusercontent.com/45286840/77170591-e7e60580-6ac3-11ea-983e-402c746d1d4f.png)

The same is true for the following taxa: **Trichodesmium** (https://www.gbif.org/species/3218406)

* **Chlorococcus**, which was recorded in the TMG data, is classified as an insect on GBIF (which is clearly not correct). When you search on Google, it does come up as a freshwater algal species though. So I have emailed Phumelele who analysed the algae samples for the taxonomic backbone. I await to hear from her so that I can update the master list.

Please advise on the other taxa. Thanks.

**Comment by helendallas** [comment]
@philipfrenzel Has this been resolved. Can the ticket be closed?

**Comment by philipfrenzel** [comment]
Hi @helendallas , all the issues, except the Chlorococcus taxonomy, has been resolved. I'll follow up with Phumelele once more, but you can close the comment already.

**Comment by philipfrenzel** [comment]
@helendallas I've heard back from Phumelele re the Chlorococcus app. He had made a spelling mistake. I've made the corrections in the master list as well as the data file. Just thought I'd let you know.
