### ISSUE TITLE
FBIS v3 pop-up site notice

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1989]
@dimasciput here is a pop-up site notice for FBISv3. @helendallas and @Aneri16 please have a look and edit if necessary before v3 release. 

[FBISv3 pop up site notice.docx](https://github.com/kartoza/django-bims/files/4373004/FBISv3.pop.up.site.notice.docx)

**Comment by helendallas** [comment]
@jeremyshelton Looks fine to me. Maybe remove track changes and clean for Dimas

**Comment by jeremyshelton** [comment]
Cool. Here it is. Cleaned and ready for Dimas 👍

[FBISv3.pop.up.site.notice.docx](https://github.com/kartoza/django-bims/files/4379900/FBISv3.pop.up.site.notice.docx)

**Comment by jeremyshelton** [comment]
@dimasciput I need to edit this a bit. How do I do that?

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton It would really be good if the pop up notice could be managed and edited from the admin section.  It adds to sustainability of FBIS and RBIS etc. 

Is this possible?

**Comment by jeremyshelton** [comment]
@dimasciput is it easy for you to give us access to edit this via admin?

**Comment by dimasciput** [comment]
@jeremyshelton https://freshwaterbiodiversity.org/admin/bims/sitesetting/1/change/ check the `Site Notice` one.

**Comment by jeremyshelton** [comment]
Fantastic. Thanks @dimasciput
