### ISSUE TITLE
Update biodiversity record

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1991]
![Screenshot_2020-03-24 Nonvalidated Records(1)](https://user-images.githubusercontent.com/45286876/77420315-77e0c380-6dd2-11ea-9620-772a34565281.png)

Not sure what Category is? I recommend removing it as it relates to Native/Non-native so should at least be renamed Origin. Is this something the use needs to add? or should it be populated fomr our master list

@jeremyshelton ?

**Comment by helendallas** [comment]
Also need to add a close/x after this step. To take one back to the map

**Comment by jeremyshelton** [comment]
@helendallas is this on testing or live site?

**Comment by helendallas** [comment]
@jeremyshelton Live site

**Comment by jeremyshelton** [comment]
@dimasciput do you know what kind of information might be found under 'category'?

**Comment by dimasciput** [comment]
@jeremyshelton category is the origin of the species, native vs non-native

**Comment by dimasciput** [comment]
Should be fixed in testing

**Comment by dimasciput** [comment]
in 10 minutes from the time I wrote this comment.

**Comment by helendallas** [comment]
@dimasciput Can you remove Origin column - it is not necessary, or hide. A user will never complete this in this form as it is linked to the master list

**Comment by helendallas** [comment]
@dimasciput Ignore comment above, don't need to do now. Closing ticket.
