### ISSUE TITLE
Optimising the ingestion process

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1995]
We want to test the new fish/invert/algae data on FBIS on testing before deploying to live

- [x] @dimasciput to split the ingestion so that sites are ingested in a separate process
- [x] @helendallas @philipfrenzel and @jeremyshelton to provide near final lists for alg/new inverts/fish
- [x] @dimasciput to ingest just the new sites on livefrom the above lists
- [x] @dimasciput to run geocontext updates on the new sites
- [x] @dimasciput make a snapshot from live site after doing above
- [x] @dimasciput restore live snapshot to testing
- [x] @dimasciput new lists to be ingested on testing
- [x] FRC to 'gorilla test' on testing knowing that it is as near possible to live
- [x] Once testing is finished, the new data to be ingested on live, which should be quick since the geocontext should be harvested already

**Comment by timlinux** [comment]
@timlinux to capture the process for ingestion in the admin manual

**Comment by philipfrenzel** [comment]
Thanks @timlinux 

I have placed the final algal data spreadsheet in the following shared Dropbox folder: FRC_Kartoza Shared Folder for FBIS\Data to Ingest 2020_02\Algae. It is the .xlsx file with "26 March 2020" at the end:

![image](https://user-images.githubusercontent.com/45286840/77651892-1ce7d180-6f76-11ea-98b7-1e49ddcc7fd2.png)

I will be able to have the algal species master list completed by Monday, 30th March and will upload it in the same folder. I will comment on this thread once I have uploaded it.

@helendallas  @jeremyshelton  @dimasciput

**Comment by jeremyshelton** [comment]
Thanks @philipfrenzel. I have created a csv file for @dimasciput and put the older versions of the spreadsheet in a different folder.

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 
Currently working on this : `ingest just the new sites on live from the above lists`

**Comment by dimasciput** [comment]
@jeremyshelton 
Currently fetching geocontext data in live site, it might be finish tomorrow.

**Comment by jeremyshelton** [comment]
@dimasciput thanks, sounds good. 

Let us know when you are ready. 

And let us know if there are any issues with the new fish data ingestion...

**Comment by philipfrenzel** [comment]
@dimasciput I forgot to mention on this ticket that I uploaded the master algal list on Friday. I did, however, make a comment in the following ticket with the Dropbox links to both final (and cleaned) files: Algal Data - Ready for ingestion  #1945 

Please let me know if you have any questions.

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 

blocked by other ticket -> https://github.com/kartoza/django-bims/issues/1935. Will continue again this ticket later.
