### ISSUE TITLE
Incorrect coordinate for 8 sites

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2001]
These are the records where latitude is positive
```
gis=# select site_CODE from bims_locationsite where latitude > 0;
  site_code
--------------
 LIMP-00042
 Q5LIMP-00001
 H6LIMP-00001
 U3LIMP-00001
 W4LIMP-00001
 B8LIMP-00001
 B8LIMP-00002
 C8LIMP-00001
(8 rows)
```

These can be checked after re-ingestion because they may be fixed already with @helendallas 's cleanups.

**Comment by Aneri16** [comment]
Thanks, noted.

**Comment by helendallas** [comment]
@Aneri16 @jeremyshelton Can you please check if this have been corrected

**Comment by Aneri16** [comment]
@helendallas doesn't look like they were fixed with re-ingestion. Should they be corrected manually in live site then?

**Comment by helendallas** [comment]
@Aneri16 No, are they correct in your master file? I thought all the data ingested into testing matches your fish data file.

**Comment by Aneri16** [comment]
@helendallas those sites are linked to invert data..

**Comment by helendallas** [comment]
@Aneri16 Noted. I will correct. thanks

**Comment by helendallas** [comment]
Site coordinates corrected on live site as follows:
LIMP-00042 -  corrected with fish ingestion
 Q5LIMP-00001 - Biobase, corrected
 H6LIMP-00001 - Biobase, corrected
 U3LIMP-00001 - Biobase, corrected
 W4LIMP-00001 - Biobase, corrected New code W4PHON-00130
 B8LIMP-00001 - Biobase, corrected New code B8GROO-00053
 B8LIMP-00002 - Biobase, corrected New code B8LETA-00028
 C8LIMP-00001 - Biobase, corrected New code C8MEUL-00006
Bree04 - - Biobase, corrected New code H4BREE-00020
