### ISSUE TITLE
Geomorphological zones - 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2002]
@NyakudyaA @dimasciput 
@Aneri16 @jeremyshelton @philipfrenzel 

I noticed repetition in the geomorphological zones. I this because of inconsistencies in the data ingested? There needs to be one of each...

![Screenshot_2020-04-02 FBIS Map](https://user-images.githubusercontent.com/45286876/78219923-d425a080-74c0-11ea-8236-d301616e7a01.png)

This is what they should be:

Refined   geomorphological zone

Source zone
Mountain headwater stream
Mountain stream
Transitional
Upper foothill
Lower foothill
Lowland river
Rejuvenated bedrock fall /   cascades
Rejuvenated foothill
Upland floodplain

**Comment by NyakudyaA** [comment]
Hi @helendallas the data is correct from the database. This should be addressed by just updating the geocontext. I think @dimasciput is running updates

**Comment by dimasciput** [comment]
@helendallas @NyakudyaA updating it now.

**Comment by dimasciput** [comment]
Fixed in live site

**Comment by helendallas** [comment]
@dimasciput Is there a way to order the zones as per this list:

Source zone
Mountain headwater stream
Mountain stream
Transitional
Upper foothill
Lower foothill
Lowland river
Rejuvenated bedrock fall / cascades
Rejuvenated foothill
Upland floodplain

**Comment by dimasciput** [comment]
@helendallas sorry we try to make it as generic as possible, so we order it by name. If we want to have different behavior only for goemorphological zone, then I need more time to do it.

**Comment by helendallas** [comment]
@dimasciput In the case of geomorphological zones it is quite important as it starts from upstream to downstream. For now I suggest you leave sorted alphabetically, we can re-evaluate after V3 release. Thanks.  I will close this ticket and create one for V5 project
