### ISSUE TITLE
Algal testing - biomass data entry

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#2005]
Hi @dimasciput 

I am in the process of trying to add fictitious biomass data and cannot seem to be able to submit it on the testing site (screenshot below). This issue I am describing relates to adding biomass only (no other biotic or abiotic data).

![image](https://user-images.githubusercontent.com/45286840/78363498-28617b00-75bc-11ea-9c2f-809c0c13524c.png)

I suspect that the above error is a result of no taxon information being uploaded at the bottom of the form i.e. the below:

![image](https://user-images.githubusercontent.com/45286840/78364014-0f0cfe80-75bd-11ea-8c01-7aaf6ba31134.png)

Biomass doesn't have one specific taxon relating to it because it is a measure of the sum of all the algae at a site. I seem to recall you seeking clarity on this a while ago? I think someone (either @helendallas or @jeremyshelton ) suggested adding "Multiple" as an option for when only biomass is added? Users should be able to add only biomass data to a site if this is all that they measured. Can you please attend to this? Thanks.

**Comment by dimasciput** [comment]
@philipfrenzel @helendallas @jeremyshelton 
Yes currently it is not possible to do this, you need to have at least one taxon since this collection data form, I'm not sure what "Multiple" is, can someone elaborate more? 

If the user can add a collection without a taxon it will create an inconsistency, because from the map view the button is called 'Add Algae' not 'Add biomass'. So we need a different form for this, please create another ticket and I will estimate how long I will complete it.

**Comment by philipfrenzel** [comment]
Hi @dimasciput 

I trawled through my emails now to find the discussion we had about how to deal with the taxon column when there is only biomass data are added. 

Just as a point of interest, a biomass measurement is the amount/quantity of algae in a sample. For this measurement, individual taxa are not identified and therefore we cannot assign a taxon to this. 

But having said that, I agree with Helen's suggestion to assign "Taxa not identified" for the biomass records (which I have now added). The taxon rank column is currently empty for these biomass records which I suspect needs to be filled in too even though it is not particularly relevant to these data? Can you comment this please Dimas? If yes, I would suggest adding a dropdown option of "Not applicable" or "Not relevant" under taxon rank to circumvent the issue of creating another form completely for adding biomass data. Would you agree @helendallas and @jeremyshelton? Would that help, Dimas?
