### ISSUE TITLE
Algal testing - autopredict issue with species names

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#2006]
Hi @dimasciput 

Previously, the system autopredicted species names when I tried adding abundance data in the section below (screenshot). It appears that this isn't working - a bug perhaps?

![image](https://user-images.githubusercontent.com/45286840/78365475-7035d180-75bf-11ea-9433-beea9eea7fdb.png)

Can you please have a look at this?

**Comment by dimasciput** [comment]
@philipfrenzel please wait when the site is ready for testing, I'm still re-ingesting the algal data.

**Comment by dimasciput** [comment]
Please try it again

**Comment by philipfrenzel** [comment]
Hi @dimasciput 

This doesn't seem to be solved as the entire list of species is now visible under this section (please see screenshot):

![image](https://user-images.githubusercontent.com/45286840/78533526-6394c180-77e9-11ea-96bb-ac2cef299a0e.png)

Most importantly, I see that this list has both algae and invertebrate taxa. It should only have algae taxa. Not sure why this is so?

**Comment by dimasciput** [comment]
@philipfrenzel yes this is intended, we filter the species by catchment area. See other species form.
cc @helendallas, @jeremyshelton 

Again, we try to make this as generic as possible, so please if you want to have different behavior for different species let me know, and I will need more time to update it.

**Comment by dimasciput** [comment]
@philipfrenzel which one is invertebrate?

**Comment by dimasciput** [comment]
@helendallas can we have two different species group with same Class or Genus? Like invert and algae with same Class?

**Comment by philipfrenzel** [comment]
> @philipfrenzel which one is invertebrate?

There are a lot of invertebrate species in that algae list on the testing site. From the screenshot alone, Acentrella, Adenophlebia x2. I noticed this because there are algal species missing too e.g. many species from the Achnanthes family (screenshot from the master list):

![image](https://user-images.githubusercontent.com/45286840/78536251-d4d67380-77ed-11ea-8e16-947faee6e328.png)

**Comment by helendallas** [comment]
Closing this ticket as we are not using auto predict but rather serving a list of algae . Seems like only algae are being returned now.
