### ISSUE TITLE
URGENT - SASS data problematic

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2012]
@dimasciput Please can you urgently check what has happened to the SASS data on the live site. I was checking data from my thesis, and found some major issues.

Taxon numbers are wrong, not adding from biotope to Site etc.
Here is an example site:
![Screenshot_2020-04-07 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/78665917-dc257c00-78d6-11ea-88e7-d731ee9d6ab6.png)

https://freshwaterbiodiversity.org/sass/dashboard/9887/?taxon=&search=G1BERG-PIKET&siteId=9887&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9887&orderBy=name&polygon=

This is from my data - also in Rivers Database and imported to FBIS. 

RHP Site Code | Sampling Date | Site Visit Owner | River Name | SASSDataVersion | SASS Score | No of Families | ASPT
G1BERG-PIKET | 9/1/1993 | Helen Dallas | Berg | 4 | 71 | 13 | 5.5
G1BERG-PIKET | 11/1/1993 | Helen Dallas | Berg | 4 | 57 | 12 | 4.8
G1BERG-PIKET | 12/1/1993 | Helen Dallas | Berg | 4 | 64 | 10 | 6.4
G1BERG-PIKET | 2/1/1994 | Helen Dallas | Berg | 4 | 54 | 9 | 6
G1BERG-PIKET | 3/1/1994 | Helen Dallas | Berg | 4 | 59 | 11 | 5.4
G1BERG-PIKET | 9/1/1994 | Helen Dallas | Berg | 4 | 37 | 8 | 4.6
G1BERG-PIKET | 11/1/1994 | Helen Dallas | Berg | 4 | 63 | 12 | 5.3
G1BERG-PIKET | 3/1/1995 | Helen Dallas | Berg | 4 | 62 | 12 | 5.2
G1BERG-PIKET | 7/1/1995 | Helen Dallas | Berg | 4 | 49 | 9 | 5.4
G1BERG-PIKET | 11/27/2001 11:30:00 AM | Justine Ewart-Smith | Berg | 4 | 115 | 23 | 5

I checked a lot of SASS data when it was first ingested and it was all correct. so a bit alarming that nw this is so incorrect. 

Also the the abundances from each biotope are no longer being totalled correctly for Total
https://freshwaterbiodiversity.org/sass/view/1685/

![Screenshot_2020-04-07 FBIS SASS](https://user-images.githubusercontent.com/45286876/78666315-771e5600-78d7-11ea-8743-cadeb8fc9545.png)

Please check urgently and revert asap

**Comment by timlinux** [comment]
@dimasciput please add unit tests for this kind of stuff so that we can ensure that there are no regressions.

**Comment by dimasciput** [comment]
@helendallas 
> Also the the abundances from each biotope are no longer being totalled correctly for Total
https://freshwaterbiodiversity.org/sass/view/1685/

Which total? If you refer to the totals on the right side, they are coming from the old SASS database so sometimes there are missing data.

**Comment by helendallas** [comment]
@dimasciput Yes the total where abundances from all biotopes are added together. That is strange that it was not provided in Rivers DB.

**Comment by dimasciput** [comment]
@helendallas for the missing SASS data, I will check it tomorrow. Probably I will try to re-import data from a river database just to make sure everything is correct.

**Comment by helendallas** [comment]
@dimasciput Reimporting wont work as I have already done quite a lot of editing of the data

**Comment by dimasciput** [comment]
@helendallas that's fine, it will only adding missing data

**Comment by dimasciput** [comment]
@helendallas I'm currently running a process that will cross-check the sass data from the river database with the fbis database, if something is missing it will add data to fbis. This might take 1 day, because we have 150k + data.

**Comment by dimasciput** [comment]
@helendallas can you check the site again please? This is only on live site, so the testing site is still have same missing data.

**Comment by helendallas** [comment]
@dimasciput This looks like it has been fixed. Thanks

This is from my data - also in Rivers Database and imported to FBIS.

RHP Site Code | Sampling Date | Site Visit Owner | River Name | SASSDataVersion | SASS Score | No of Families | ASPT
G1BERG-PIKET | 9/1/1993 | Helen Dallas | Berg | 4 | 71 | 13 | 5.5
G1BERG-PIKET | 11/1/1993 | Helen Dallas | Berg | 4 | 57 | 12 | 4.8
G1BERG-PIKET | 12/1/1993 | Helen Dallas | Berg | 4 | 64 | 10 | 6.4
G1BERG-PIKET | 2/1/1994 | Helen Dallas | Berg | 4 | 54 | 9 | 6
G1BERG-PIKET | 3/1/1994 | Helen Dallas | Berg | 4 | 59 | 11 | 5.4
G1BERG-PIKET | 9/1/1994 | Helen Dallas | Berg | 4 | 37 | 8 | 4.6
G1BERG-PIKET | 11/1/1994 | Helen Dallas | Berg | 4 | 63 | 12 | 5.3
G1BERG-PIKET | 3/1/1995 | Helen Dallas | Berg | 4 | 62 | 12 | 5.2
G1BERG-PIKET | 7/1/1995 | Helen Dallas | Berg | 4 | 49 | 9 | 5.4
G1BERG-PIKET | 11/27/2001 11:30:00 AM | Justine Ewart-Smith | Berg | 4 | 115 | 23 | 

![Screenshot_2020-04-09 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/78885252-8e3a8080-7a5c-11ea-8bff-3209af94bc46.png)

**Comment by helendallas** [comment]
Checked and data seems to sorted now, thanks
