### ISSUE TITLE
Fish data and master list ready for ingestion

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2013]
The final version of the fish master list and fish data for FBIS v3 are now saved as .csv files on [dropbox](https://www.dropbox.com/sh/ilfrbn6klyesv3k/AAA520tmniByikaY-Of2CCr9a?dl=0) and ready for ingestion. 

These need to replace the previous versions in FBIS. 

You will see that the eco-tolerance column is included in the master list. This is the field discussed last week. Maybe we can look to include as a filter in a later version.

@dimasciput  let us know once you have an ingestion report & if there are any errors that need fixing. 

Also see ticket #1858

**Comment by dimasciput** [comment]
Hi @jeremyshelton , can you please update the master fish species to just use one column for 'Former species name'.

![image](https://user-images.githubusercontent.com/1979569/78749024-92e93100-7997-11ea-9484-a70f418e0524.png)

If there are multiple names, just separate them with semicolons. e.g 'Barbus nigrolinea;Barbus salmo'.

**Comment by jeremyshelton** [comment]
@dimasciput ok will do. Anything else that needs to be adjusted before ingestion?

**Comment by dimasciput** [comment]
@jeremyshelton That's it for the fish, thanks.

**Comment by jeremyshelton** [comment]
👍

**Comment by jeremyshelton** [comment]
Hey @dimasciput , 
Fish [data](https://www.dropbox.com/s/jythqzqvkptis9t/SA%20fish%20data%20for%20FBIS%20v3_8Apr2020.csv?dl=0) and [master list](https://www.dropbox.com/s/bqli42h9ae8pi9x/SA%20Master%20fish%20species%20list%20for%20FBIS%20v3_8Apr2020.csv?dl=0) fixed. 
Ready for re-ingestion. 
Thanks!

**Comment by jeremyshelton** [comment]
@dimasciput 

**Strange fish taxa**

- There seems to be something strange happening with the fish taxa: there are a lot of taxa being served that are not listed in our master list. 
- It is critical that we only have data (from both FBIS and GBIF) for the taxa specified in the master list, and no additional taxa. I wonder if the below error has anything to do with it?

**Error in fish master list**

- I found an error in the master list (SA Master fish species list for FBIS v3_8Apr2020) and have replaced it with an updated version ([SA Master fish species list for FBIS v3_15Apr2020](https://www.dropbox.com/s/df02w85gz17bd92/SA%20Master%20fish%20species%20list%20for%20FBIS%20v3_15Apr2020.csv?dl=0)) on dropbox. 
- The only difference is that the more recent one includes the Scientific name and authority and the Common name, while the older one does not. 
- Please use the scientific name and authority when pulling from GBIF.

- Also, do we need to include the Scientific name and authority in the data spreadsheet ([SA fish data for FBIS v3_8Apr2020](https://www.dropbox.com/s/jythqzqvkptis9t/SA%20fish%20data%20for%20FBIS%20v3_8Apr2020.csv?dl=0)) also, or is it fine to just have the taxon? 

@Aneri16

**Comment by jeremyshelton** [comment]
@dimasciput fixed [fish data](https://www.dropbox.com/s/x79zdg0bdvydvwx/SA%20fish%20data%20for%20FBIS%20v3_3May2020.csv?dl=0) and [master list](https://www.dropbox.com/s/ltfj2snondiaose/SA%20Master%20fish%20species%20list%20for%20FBIS%20v3_3May2020.csv?dl=0) ready for reingestion.

**Comment by jeremyshelton** [comment]
@dimasciput I found a few issues with fish data that we should fix before deploying to live site?

1. There is one record for Enteromius brevidorsalis  in the data sheet but it is not meant to be there. It is not found in SA and is therefore not own the master list. I have thus deleted I from the data sheet. 
2. There are 240 records for Enteromius marequensis in the data sheet. This taxon is incorrectly named. The correct name is Labeobarbus marequensis, as per the master list. I have thus renamed it in the data sheet.

**BOTH OF THESE CHANGES HAVE BEEN IMPLEMENTED IN A NEW FILE DATED 6 MAY.** 

3. None of the endemism data are showing for the fish in testing: https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

@Aneri16

**Comment by jeremyshelton** [comment]
@dimasciput The updated fish DATA and MASTER LIST (both dated 19 May) are now on dropbox and ready for you to ingest.

<img width="715" alt="Screenshot 2020-05-19 at 10 24 29" src="https://user-images.githubusercontent.com/44292029/82303356-22ccc280-99bb-11ea-871a-e67f12b12fa7.png">

@timlinux @helendallas

**Comment by jeremyshelton** [comment]
@dimasciput Fish data on staging looking good. Only issue is that the following two taxa seem to have lost the Authority in their name. Is this an easy fix?

Petrocephalus wesselsi (Kramer & van der Bank, 2000)
Anguilla bicolor McClelland, 1844

Once that is fixed we can start pulling from GBIF with this new master list 👍

**Comment by dimasciput** [comment]
@jeremyshelton fixed, I already pulled some data from gbif

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput 
let me know when you are finished pulling from GBIF and then we can test that 👍

**Comment by dimasciput** [comment]
on it

**Comment by dimasciput** [comment]
@jeremyshelton fetched all fish data from gbif, not all species has occurrences from gbif.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - will check that now.
Do you perhaps have a list of which 13 fish species that have zero records?
