### ISSUE TITLE
Endemism category missing on live site?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2023]
@dimasciput looks like micro endemic level 2 category is missing from the live site?
<img width="550" alt="Screenshot 2020-04-09 at 12 46 01" src="https://user-images.githubusercontent.com/44292029/78887848-db205600-7a60-11ea-911c-c6e599335443.png">

**Comment by dimasciput** [comment]
@jeremyshelton this will be fixed when we have ingested new data to live site

**Comment by jeremyshelton** [comment]
@dimasciput OK thanks
