### ISSUE TITLE
Ec in datadownload

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2025]
Please may you make the ecological category available in the sass summary .csv download. alternatively, please provide the ecoregion available in the csv for us to calculate it based on the dallas bands. 

many thanks,
wesley evans

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/1990">User information </a>
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,surface_swsas,Southern%20Drakensberg%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22,%22B%22,%22C%22,%22D%22,%22E%22]&rank=&siteIdOpen=&orderBy=name&polygon=
Screen resolution: 1600 x 900
Browser: Chrome

**Comment by helendallas** [comment]
@dimasciput 
As per the user request please include the Ecological Category derived from graph below in the SASS Summary CSV files.
![Screenshot_2020-04-20 FBIS Single Site Dashboard - SASS](https://user-images.githubusercontent.com/45286876/79755132-e2751880-8318-11ea-828a-6a5aeb37b1e6.png)

As per ticket #2040 please include more detailed geocontext data 
![Screenshot_2020-04-20 FBIS Single Site Dashboard - SASS(1)](https://user-images.githubusercontent.com/45286876/79755737-ddfd2f80-8319-11ea-90e0-9382f6e7d571.png)

**Comment by helendallas** [comment]
@dimasciput Thanks EC now in SASS Summary Table.

Please can you also standardise as you have with other CSV that Original Site Code and Original River Name are also included.

**Comment by helendallas** [comment]
@dimasciput Please add **Original Site Code** and **Original River Name** to this csv. It can happen after the site goes live, thanks

**Comment by helendallas** [comment]
Closing ticket and creating a new one for SASS Summary CSV
SASS Summary CSV #2192
