### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2026]
**Live Site:** 
References added to Documents are not being cited correctly in the Metadata Table
Download not visible even when pdf is available.

![Screenshot_2020-04-15 Brand P A J Kemp P H Pretorius S J Schoonbee H J 1967 Water quality and abatement of pollution in Nat](https://user-images.githubusercontent.com/45286876/79337617-1c63aa80-7f26-11ea-8890-06580498912c.png)

![Screenshot_2020-04-15 FBIS Map(4)](https://user-images.githubusercontent.com/45286876/79337620-1f5e9b00-7f26-11ea-8af1-02ccff1ed89e.png)

**Testing site:**
Incorrect Owner in Metadata Table. It is given as the person who added the document, and not the actual authors of the study s included in the Invertebrate data table.

![Screenshot_2020-04-15 FBIS Map(5)](https://user-images.githubusercontent.com/45286876/79338211-2fc34580-7f27-11ea-85ff-26583f3554dd.png)

**Comment by dimasciput** [comment]
For testing site, the owner is correct : 
![image](https://user-images.githubusercontent.com/1979569/80679625-74cea680-8ae7-11ea-9b6f-96964eddd8b2.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/80693890-fd434c00-8ad3-11ea-851d-04266ec7efaa.png)
Nope its showing Janette Lumley 2019 is the author, Not Dallas et al. This is happening fro all see, me as authors of several study references that were entered under my name, but should not list me as author.
![Screenshot_2020-04-30 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/80694142-5e6b1f80-8ad4-11ea-8fbd-f5d07b237b17.png)
![Screenshot_2020-04-30 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/80694151-62973d00-8ad4-11ea-9ad0-e84c120579c7.png)
![Screenshot_2020-04-30 FBIS Map](https://user-images.githubusercontent.com/45286876/80694160-66c35a80-8ad4-11ea-863e-56b5b8dc38ae.png)

**Comment by dimasciput** [comment]
> Nope its showing Janette Lumley 2019 is the author, Not Dallas et al. This is happening fro all see, me as authors of several study references that were entered under my name, but should not list me as author.

@helendallas yes because in the Document page here : https://testing.healthyrivers.kartoza.com/documents/103, the owner is Janette.

You can change the owner yourself : 
- Open this page : https://testing.healthyrivers.kartoza.com/documents/103/metadata_advanced

- Click x icon
![image](https://user-images.githubusercontent.com/1979569/80699938-16192500-8b07-11ea-8576-256aa0310520.png)

- Search your name, use the name with capital : 
![image](https://user-images.githubusercontent.com/1979569/80699979-26c99b00-8b07-11ea-99a6-3360113500bb.png)

- Click update located at the very bottom page

PS: You can also update the date here

**Comment by helendallas** [comment]
@dimasciput Is the stuff shown on the live and testing sites different for documents. I thoughtit had been corrected by us on live site?

**Comment by dimasciput** [comment]
@helendallas ah yes did you just updated it? Ok then this should be fixed on live.

**Comment by helendallas** [comment]
@dimasciput Yes, we have corrected loads on the live site, so will close this ticket now.
