### ISSUE TITLE
Geomorphological zones not displaying 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2027]
Added the layer, but it did not appear anywhere in sa. altered the opaque tool and still nothing. 

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/531">User information </a>
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/
Screen resolution: 1366 x 768
Browser: Chrome

**Comment by helendallas** [comment]
@dimasciput This appears to be all the layers. Not working at all. Email sent

**Comment by dimasciput** [comment]
Fixed on testing

**Comment by helendallas** [comment]
@dimasciput 
Is there a reason many layers are not working on the live site?

**Comment by dimasciput** [comment]
@helendallas There is a bug that I have fixed on testing, but I haven't deployed it yet to live

**Comment by helendallas** [comment]
@dimasciput Thanks
