### ISSUE TITLE
Site photographs - Multiple Sites Dashboards 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2029]
It doesn't make sense to have photographs of sites in the Multiple Sites Dashboards for fish, inverts or algae

@jeremyshelton Do you agree?

Here i searched Order Odonata - over 2,500 sites
![Screenshot_2020-04-16 FBIS Map](https://user-images.githubusercontent.com/45286876/79446563-ae2eee80-7fde-11ea-9a9d-fe8ac0e9f35a.png)

**Comment by jeremyshelton** [comment]
@helendallas agreed.
