### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2033]
Additional fixes and functionality needed to effectively manage the Citations in FBIS.  

1. Many of the publications in the Citations have URLs not DOIs. At the moment you can only search on publications with missing DOIS.  Please update this filter to include missing DOIs and URLs.  This makes it difficult for us to check which studies are missing an online link.

2. Add a close button to return to the previous screen after **Change entry** screen.  At the moment you have to go back to Citations and navigate again.
![Screenshot_2020-04-17 Change Entry Django site admin](https://user-images.githubusercontent.com/45286876/79546697-2525bf00-8093-11ea-8240-334d36a5ae61.png)

2. Authors listed multiple times. I have previously engaged with Dimas around this and he indicated that the reason for this is because the citations are derived from DOIs. However as a user this is problematic as if you want to select studies from one author, it is impossible, without selecting each one at a time and then going backwards and forwards.  

If it is not possible to consolidate authors so that only one is visible per actual person, then you at least need to allow users to select multiple names using the control button or something that is explained to the user. @timlinux  Perhaps some of this improved functionality can be billed to the RBIS project as a document / citation manager is one of their deliverables.

![image](https://user-images.githubusercontent.com/45286876/79546574-f3145d00-8092-11ea-9bcb-73d210b24a48.png)

@jeremyshelton @dimasciput

**Comment by helendallas** [comment]
In addition some citations come through strangely, even thought they are correct in the data to be ingested.
![image](https://user-images.githubusercontent.com/45286876/79547916-ebee4e80-8094-11ea-906e-a5e87b69a67c.png)

**Comment by helendallas** [comment]
Reference to #2033

**Comment by timlinux** [comment]
In addition we need to add an Author field to the GeoNode document management model so that the author can be displayed properly in the metadata table.

**Comment by helendallas** [comment]
Link to tickets #2286 #2273

**Comment by timlinux** [comment]
Discussed with @dimasciput - he has already added a merge tool like we have for taxa so that multiple authors can be combined into one author. The list of authors and publications are going to eventually land up in our own source references view and then we can manage the behaviour better.

![image](https://user-images.githubusercontent.com/178003/98095402-6ee4c400-1e82-11eb-93ab-4b7c2f018d60.png)

**Comment by timlinux** [comment]
You can also see why we get these systematic issues

![image](https://user-images.githubusercontent.com/178003/98095545-a2275300-1e82-11eb-9b61-c9cb2728f7ed.png)


When we harvest the authors from the citations API we can't guarantee that author names are captured in a uniform way.

**Comment by timlinux** [comment]
For now I have moved the lable to RBIS v2 because I think this is not critical for the release of RBIS v1

**Comment by helendallas** [comment]
@timlinux @dimasciput That's fine but this is really important for FBIS citation integrity and this ticket has been around since April. It would really be good to get the citations etc fixed and rolled out.

**Comment by helendallas** [comment]
I am going to close this issue as it is covered in other tickets and by the new document management system of Dimas
