### ISSUE TITLE
Adding abiotic data to exsiting sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2034]
As I understand FBIS now, it is not possible to add abiotic data to an existing site. (one can add it after adding biotic data, and SASS data)

It would be useful to be able to add abiotic data from the overview panel, in a similar manner to adding fish, invertebrate, algal and SASS data.  

@timlinux This can potentially be included in the RBIS project as their is a water quality module that needs to be developed.

![Screenshot_2020-04-17 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/79549416-3d97d880-8097-11ea-91c7-726449a4f116.png)

**Comment by dimasciput** [comment]
@helendallas this could be done in the new version,  you can test in on the testing. 

1. Go to the the site dashboard https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Anguilla%20bicolor&siteId=29763&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=29763&orderBy=name&polygon=
2. Check the Site Visit Data
![image](https://user-images.githubusercontent.com/1979569/95552801-8e313280-0a37-11eb-813f-9216bdd68b57.png)
3. Click the site code, if you're an admin or the owner of the site visit, you can add edit the site visit.

**Comment by helendallas** [comment]
Thanks, working well
