### ISSUE TITLE
Add Site - spatial integrity

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2037]
@timlinux 
I added a site in the Atlantic Ocean, and managed to retrieve both a river name and a site code. No warning. When I clicked Add, I then got the second screenshot "Invalid site code format"

Do we need something to prevent this happening or do we rely on the brain of the user not to salp a site in the ocean?
@jeremyshelton fyi

![Screenshot_2020-04-17 FBIS Location Site Form](https://user-images.githubusercontent.com/45286876/79557547-09c2b000-80a3-11ea-88f5-bd1e442fcd71.png)

![Screenshot_2020-04-17 FBIS Location Site Form(1)](https://user-images.githubusercontent.com/45286876/79557623-2bbc3280-80a3-11ea-80a0-28038b7058be.png)

**Comment by helendallas** [comment]
I then delete the - in Latitude, and was able to update the site.  I thought we had agreed to include a South African boundary for adding sites and data.

![Screenshot_2020-04-17 FBIS Location Site Form(2)](https://user-images.githubusercontent.com/45286876/79557978-c4eb4900-80a3-11ea-943e-e9c5b7ef7fda.png)

**Comment by timlinux** [comment]
@dimasciput can you do this simply by doing a GFI check to ensure the country is SA, Lesotho or Swaziland otherwise give a spatial validation fail. Later we can use the same logic for other regions.
