### ISSUE TITLE
Add Algae - needed after adding a new site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2038]
@dimasciput 
Please add option to Add algae

![Screenshot_2020-04-17 FBIS Location Site Form(3)](https://user-images.githubusercontent.com/45286876/79558842-1a742580-80a5-11ea-98ea-77b3967a1298.png)

Can you also reword all as follows:

- Add fish data
- Add invertebrate data
- Add SASS data
- Add algal data

**Comment by dimasciput** [comment]
already added in the testing
