### ISSUE TITLE
Add new taxon - extra taxonomic hierarchy needed

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2039]
At the moment the user can add a taxon that is not in GBIF, but is only able to add the Taxon name, and Taxon rank.

Going forward we need to expand this to allow user to capture full taxonomic hierarchy:

Kingdom | Phylum | Class | Order | Family | Genus | Species | SubSpecies ] Taxon

Not sure how validation of this would work though.

@timlinux I have labelled this RBIS in case we can improve it through that project.

**Comment by helendallas** [comment]
@timlinux  @dimasciput 
Please confirm if this is doable in RBIS as it will be needed across multiple modules. 

It is related to #2058 in that the Master List of all Modules (fish, invertebrates, algae, birds, wetland plants, frogs, adult odonates etc.) will need to be updateable.

**Comment by helendallas** [comment]
Linked to #2333

**Comment by timlinux** [comment]
Hi @helendallas 

Yes this is doable and makes sense. We just want to confirm if this is critical for version 1?

**Comment by helendallas** [comment]
@timlinux @dimasciput 
Given the data are currently ingested using the upload template, it is not a blocker for RBIS v1. It perhaps needs some collective chatting though.

**Comment by helendallas** [comment]
I am closing this ticket as Taxon Management now allows for adding a taxon not on GBIF.
