### ISSUE TITLE
CSV files - general

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2040]
The taxon data CSV files for fish, invertebrate and algae are not correct. They need to resemble the data ingestion file for each specific taxon group. plus possibly some additional spatial fields.

@philipfrenzel @jeremyshelton Can we please provide @dimasciput with a plan for this. Please check the data ingestion files and see if these are adequate.

**Comment by jeremyshelton** [comment]
@helendallas yeah I think the csv should be identical format to the columns in the data spreadsheets that were ingested. That way differences in columns for the different modules (e.g. algal biomass, fish abundance etc can be included).

I don't think we should look to include additional spatial fields at this stage. 

Please see ticket #777 for our previous discussion on this topic.

**Comment by philipfrenzel** [comment]
Agreed. Ideally, the downloadable CSVs should resemble the format of the ingested data files. 

In terms of the spatial fields to be included in the CSVs, I would recommend the fields in the overview dashboard (screenshot below) as well as: Original site code (i.e. the one in the study - I think this is NB) and maybe the original river name and refined geomorphological zone (last two suggestions not as crucial).

![image](https://user-images.githubusercontent.com/45286840/79689948-4388e780-8258-11ea-917c-b6fb44fe18e9.png)

@helendallas @jeremyshelton

**Comment by helendallas** [comment]
I agree - the data exported in the CSV should resemble the format of the ingested data. 

Then please include the data summarised in the the Detailed dashboards - which are already standardised - excluding the columns that are already in the ingested file.  That way all the geocontext data is included and the user has maximum power for interrogating the csv file.

![Screenshot_2020-04-20 FBIS Map](https://user-images.githubusercontent.com/45286876/79742004-7982a600-8302-11ea-8f80-9e4531d7dc06.png)

@dimasciput Is this possible?

**Comment by dimasciput** [comment]
@helendallas it's possible, but might take some time. I think probably around 3-4 hours to do this.

**Comment by helendallas** [comment]
@dimasciput I definately think it needs to be done as this is the only way a power user can extract the data, with the associated geocontext data. Lets clear the other easier tickets, then focus on the ones that will take longer.

**Comment by jeremyshelton** [comment]
@dimasciput if possible, I think this should be a priority once the fish ingestion is complete 👍

**Comment by dimasciput** [comment]
@jeremyshelton it's on testing already

**Comment by jeremyshelton** [comment]
@dimasciput OK thanks. CSV downloads not working at the moment, but I will test as soon as those are back up and running...

**Comment by helendallas** [comment]
@dimasciput Cant check this as CSV not working for invertebrate

**Comment by helendallas** [comment]
@dimasciput Looks good for invertebrates and algae
@jeremyshelton please check for fish

**Comment by jeremyshelton** [comment]
@helendallas fish looks good too. 

The only error I picked up is that quinary catchment column is absent for all csv's. @dimasciput is there an easy way to include this?

Also, @helendallas just a question: is there a good reason why we are not including units for columns like 'abundance value' or the physio-chem parameters at the end?

**Comment by helendallas** [comment]
@jeremyshelton 
We should be including all abiotic data, as per the ingestion table. I did also subsequently notice a few other issues such as :
Density instead of Density with details as per spreadsheet  (cells/m2)

It may be worth goign through these all unless @dimasciput has a quick way to check?
--

**Comment by dimasciput** [comment]
@jeremyshelton 
> The only error I picked up is that quinary catchment column is absent for all csv's. @dimasciput is there an easy way to include this?

Yes, I'm still fetching this data from geocontext, there was an error this morning from geocontext and @NyakudyaA just fixed it.

**Comment by dimasciput** [comment]
@helendallas 
> We should be including all abiotic data, as per the ingestion table.

I already added this. 
![image](https://user-images.githubusercontent.com/1979569/82902224-55615700-9f89-11ea-9f9a-4c8750bf46b3.png)

> Density instead of Density with details as per spreadsheet (cells/m2)
I made it the same as the other modules, is it vital now? Or can I update this later?

**Comment by helendallas** [comment]
@dimasciput happy for it to updated later, not vital, thanks

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton I am moving this now to FBIS V5. The scv files still need some final fixing, but 90% is fine, so dont want tit to hold up the reopening of FBIS site.

**Comment by helendallas** [comment]
@dimasciput 
Still to please fix in the csv files:

### **MultiSite**
**Invertebrate csv:**

- Sampling effort -  should be **Sampling effort measure**
- Study reference -  should be **Title**
- Need to include all available abiotic data Only main ones included so far)

**Fish csv**

- Sampling effort -  should be **Sampling effort measure**
- Study reference -  should be **Title**
- Need to include all available abiotic data

**Algae csv**

_**I could not check these as the email with the csv file never arrived. They all need to be the same as the multiSites**_

### **Single Site**

**Invertebrate csv**

**Fish csv**

**Algal csv**

**Comment by dimasciput** [comment]
Updated in live

**Comment by helendallas** [comment]
@dimasciput Please check why Algae csv file never sent via email.

**Comment by dimasciput** [comment]
@helendallas are you trying to download all algae files? it might take a while to process

**Comment by helendallas** [comment]
No only one site

**Comment by helendallas** [comment]
Tested again and it is working - closing

**Comment by helendallas** [comment]
@dimasciput I am reopening this as the csv files are still missing fields, They need to resemble the Data occurrence Upload file for each group, plus the associated abiotic data, 

So for algae:

Original   River Name | Original Site Code | FBIS Site Code | Site description | Refined Geomorphological Zone | Latitude | Longitude | Sampling Date | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon | Taxon rank | Present | Sampling method | Sampling effort measure | Sampling effort value | Abundance measure | Abundance value | Curation process | Biomass Indicator: Chl A | CHLA-B | Biomass Indicator: AFDM | AFDM | Autotrophic Index (AI) | Broad biotope | Specific biotope | Substratum | Water Level | Water Turbidity | Embeddedness | Depth | Near Bed Velocity | TEMP | COND | PH | DOPER | DO | TURB | SRP | TOT-P | SI | NH4-N | NH3-N | NO3+NO2-N | NO2-N | NO3-N | TIN | Collector/Owner | Institute | Analyst | Institute | Author(s) | Year | Source | Title | Reference category | URL | DOI | Document Upload Link | Notes

For abiotic it should really be everything that is associated with the site visit

**Comment by helendallas** [comment]
@dimasciput Is it possible to order the returned data in the csv files as per the upload template, followed by the contextual data. Significant thought was given to the layout of the upload templates so best to return the data in the same way.

Also please check why Abundance measure is returned as **Number** when they should be **Species valve/frustule count**
e.g. A2SAND-00014; 7/27/2018
