### ISSUE TITLE
Abiotic data not displayed on SASS dashboard after being added

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2043]
We added abiotic data to this site  (and others) via the Edit SASS dashboard:
https://freshwaterbiodiversity.org/sass/dashboard/27264/?taxon=&search=&siteId=27264&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%22362%22%5D&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27264&orderBy=name&polygon=

But the abiotic graphs are not being presented.

I checked and the data are there.
https://freshwaterbiodiversity.org/abiotic/?survey=203&next=/source-reference-form/?session=2fdd7eda-f441-4144-964c-5acd1fdc6b59&identifier=sass-form&next=/sass/update/11553/

**Comment by dimasciput** [comment]
thanks, it shown in site detail : https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=K3DUIW-00004&siteId=27264&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27264&orderBy=name&polygon=

but not on SASS dashboard, I'll investigate it

**Comment by dimasciput** [comment]
check here : https://testing.healthyrivers.kartoza.com/sass/dashboard/27264/?taxon=&search=&siteId=27264&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%22362%22%5D&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27264&orderBy=name&polygon=

**Comment by helendallas** [comment]
@dim Abiotic data is now visible, thanks
