### ISSUE TITLE
Collector/Owner

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2049]
Please change Collector/Assessor to Collector/Owner on filter

![Screenshot_2020-04-21 FBIS Map(3)](https://user-images.githubusercontent.com/45286876/79865368-54159b00-83db-11ea-9071-b26676832ad3.png)

Also please check why there are so many strange Collector/Owner -  I dont think the old ones have been cleaned out before the ingestion of the new ones.

![image](https://user-images.githubusercontent.com/45286876/79865428-71e30000-83db-11ea-812d-15cb65946fe9.png)

**Comment by dimasciput** [comment]
@helendallas 

> Also please check why there are so many strange Collector/Owner - I dont think the old ones have been cleaned out before the ingestion of the new ones.

The strange ones are coming from gbif, should I exclude collector names from gbif?

**Comment by helendallas** [comment]
@dimasciput Yes please, it doesnt make sense to include GBIF collectors, only FBIS.

**Comment by helendallas** [comment]
Still looks like some GBIF collectors coming through although there are loads fewer.

Collector/owner - B.A.S.S.
Study reference - Global Biodiversity Information Facility   (GBIF), 2019-03-13

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=[%22B.A.S.S.%20%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by helendallas** [comment]
@dimasciput please exclude all collector/owner from GBIF. such as 

![image](https://user-images.githubusercontent.com/45286876/82921261-7a010300-9f78-11ea-8dbe-c62967243a55.png)

![image](https://user-images.githubusercontent.com/45286876/82921445-aae13800-9f78-11ea-8d13-9e288da9ac10.png)

![image](https://user-images.githubusercontent.com/45286876/82921539-c9dfca00-9f78-11ea-913e-d4b26bd7570d.png)

**Comment by dimasciput** [comment]
@helendallas done, please try again

**Comment by helendallas** [comment]
@dimasciput looks mostly fixed, except odd one. from FBIS
http://staging.freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=[%22M%20%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/82987408-c0497700-9ff7-11ea-81a0-a3d1a700ba70.png)

Comes through as:
![image](https://user-images.githubusercontent.com/45286876/82987456-d5bea100-9ff7-11ea-8170-78367fc69c99.png)

Looks like the only strange one

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
@dimasciput Looks good now, closing ticket
