### ISSUE TITLE
Layer selector

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2050]
@timlinux As per one of our online discussion please can the Layer Selector be tidied. Suggestion was to 
remove Maps.Kartoza.com
and reduce the amount of space each takes.

At the moment the no metadata comes up, and instead **Abstract information available** appears.
![Screenshot_2020-04-21 FBIS Map(6)](https://user-images.githubusercontent.com/45286876/79868517-4f071a80-83e0-11ea-8478-4a8ee9663e5f.png)

If this is too onerous to do before V3 release , can we assign to the RBIS project to refine?  Although the metadata issue needs to be resolved.

**Comment by dimasciput** [comment]
@helendallas The metadata has been resolved on testing, but the layout is still the same. Can we move it to RBIS please?

**Comment by helendallas** [comment]
@dimasciput Done

**Comment by helendallas** [comment]
This has been done, closing
