### ISSUE TITLE
Validate Records - Non admin users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2051]
I thought that regular users were not meant to be able to validate records.  Surely they should only be able to see Update records on the top menu bar.

Administration and Validate Records should be reserved for users assigned admin rights.

![Screenshot_2020-04-21 FBIS Map(7)](https://user-images.githubusercontent.com/45286876/79875535-1704d500-83ea-11ea-8b6c-478e5bb700df.png)

@timlinux @dimasciput Is this correct?

Or I am missing something related to

**Comment by dimasciput** [comment]
Yes they can see the menu but it's not accessible for them. Ok let me hide it instead
