### ISSUE TITLE
OVERVIEW DASHBOARD (V4 testing)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2054]
@dimasciput @helendallas 

- Can we make overview dashboard a bit wider so that the category labels are not so squashed? The other option is to use abbreviations (Critically Endangered = CR), but that might be inconsistent with the rest of the site?
<img width="119" alt="image" src="https://user-images.githubusercontent.com/44292029/79959419-68fa3900-8484-11ea-858b-4f1275f8ffb6.png">

- Can we make the heading text in bold?
<img width="96" alt="image" src="https://user-images.githubusercontent.com/44292029/79959474-79121880-8484-11ea-9efc-d73c6af2e64f.png">

- 'GBIF' and 'FBIS' ned to be upper case, here and in detailed dashboard.
<img width="229" alt="image" src="https://user-images.githubusercontent.com/44292029/79959631-a4950300-8484-11ea-8043-70b0d023143a.png">

**Comment by helendallas** [comment]
It would also be good to increase the space in the right hand column of the Site Details section (and reduce the width of the left hand column) so that text is clearer. This will also reduce the length of the overview panel.

![image](https://user-images.githubusercontent.com/45286876/80219759-364a6f00-8643-11ea-9fa0-8a5f5c5bb163.png)

**Comment by jeremyshelton** [comment]
@dimasciput thanks very much. Mostly looking good now. Can we make overview dashboard a bit wider se text on left (e.g. 'Regional endemic level 2') doesn't need to be squashed into three lines?

<img width="414" alt="Screenshot 2020-05-04 at 09 00 31" src="https://user-images.githubusercontent.com/44292029/80942761-e65b6d00-8de5-11ea-98e1-f1a3dd9fb68d.png">

**Comment by jeremyshelton** [comment]
Also, format of top section of multisite detailed dashboard looks like something has gone wrong. It should be same as the other tables below (overview, occurrence data), in terms of font size, cell style etc. 

<img width="455" alt="Screenshot 2020-05-04 at 09 07 33" src="https://user-images.githubusercontent.com/44292029/80943278-1c4d2100-8de7-11ea-9ab9-7a670e5ec0fd.png">

**Comment by jeremyshelton** [comment]
@dimasciput the following still need attention:

1. Make overview panel wider to give text on left a bit more space.
2. reduce the gap size in the 'Site details column, as per @helendallas 's request.
3. Standardise format of table in top left of multisite dashboard.

Thanks

**Comment by jeremyshelton** [comment]
Looks good now. Thanks @dimasciput
