### ISSUE TITLE
DETAILED DASHBOARDS (testing v4)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2055]
@dimasciput @helendallas 

**Charts**
- The taxa graph becomes meaningless when there are too many taxa to display. @dimas is there a way to limit the display to the (top 20?) most abundant taxa instead? @helendallas ?https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=
<img width="284" alt="image" src="https://user-images.githubusercontent.com/44292029/79960727-0a35bf00-8486-11ea-88a6-c01875d5a5b3.png">

- For occurrence charts can we please flip the legend and title? Title should be on top, legend below:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/44292029/79960795-20dc1600-8486-11ea-905e-d70e5524073b.png">

**Metadata table**
- There need to be spaces after the commas
- Please delete ‘housing development’
<img width="451" alt="image" src="https://user-images.githubusercontent.com/44292029/79961095-8203e980-8486-11ea-9ced-8127dc01ed88.png">

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Multi Site dashboards**
- Remove photographs panel #2029 

**Single Site Dashboards**
- Quinary catchment missing. 
- Categories under Management areas should read: Water Management Area, Sub Water Management Area, River Management Unit.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/44292029/79963060-2c7d0c00-8489-11ea-9f8c-c4d24ad2c0c9.png">

- Header should say: ‘Single Site – Invertebrates’ (**single site fish and algae headers also need to be adjusted accordingly**)

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=32867&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=&modules=21&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=&polygon=

<img width="280" alt="image" src="https://user-images.githubusercontent.com/44292029/79962387-44a05b80-8488-11ea-9158-eb13fd0f2776.png">

**Dashboard downloads**
- Pie charts: Need a way to download more than one pie chart. Maybe add a download button for each? Also, the pie chart needs its legend to be downloaded with it. 

<img width="451" alt="image" src="https://user-images.githubusercontent.com/44292029/79961960-b330e980-8487-11ea-82f8-252e823a4f68.png">

- Remove download option for overview and occurrence data
<img width="235" alt="image" src="https://user-images.githubusercontent.com/44292029/79963266-71a13e00-8489-11ea-932e-be4d2e313a82.png">

- Axis labels in graphs: Can we get the y-axis labels properly lined up, and a bit of space between x-axis and its labels?

<img width="453" alt="image" src="https://user-images.githubusercontent.com/44292029/79963144-49194400-8489-11ea-91e8-279280c9351c.png">

**Comment by dimasciput** [comment]
- [x] For occurrence charts can we please flip the legend and title? Title should be on top, legend below

**Metadata**
- [x] There need to be spaces after the commas
- [x] Please delete ‘housing development’

**Single Site Dashboards**
- [x] Quinary catchment missing.
- [x] Categories under Management areas should read: Water Management Area, Sub Water Management Area, River Management Unit.

> - Axis labels in graphs: Can we get the y-axis labels properly lined up, and a bit of space between x-axis and its labels?

Sorry, I can't do that, this is all automatically generated to svg.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput for fixing some of these issues. 
Getting there. Fine that graph axes can't be fixed.

A few outstanding issues:
- Single site fish dashboard says 'Single Site - Invertebrates' but it should say 'Single Site - Fish' (same thing for algae) http://staging.freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=30895&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["value,sa_provinces,North%20West"]&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=30895&orderBy=name&polygon=
- There are still inconsistencies in referencing format in metadata table. How do we fix this?
<img width="1143" alt="Screenshot 2020-05-20 at 10 47 39" src="https://user-images.githubusercontent.com/44292029/82426479-3134e000-9a88-11ea-8fea-cd437f92847d.png">
- Pie charts downloads (see above): Need a way to download more than one pie chart. Maybe add a download button for each? Also, the pie chart needs its legend to be downloaded with it.

- The taxa graph becomes meaningless when there are too many taxa to display. @timlinux suggested a limiter at our meeting two weeks back? Is there a way to limit the display to the (top 20 or ?) most abundant taxa instead? If difficult, we can park for a later version.
- https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=1&validated=&sourceCollection=%5B%22fbis%22,%22gbif%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@jeremyshelton 
> There are still inconsistencies in referencing format in metadata table. How do we fix this?

That was the name ingested from the master data : 

![image](https://user-images.githubusercontent.com/1979569/82887153-cc8af100-9f71-11ea-8cb5-dae53d708d13.png)

**Comment by jeremyshelton** [comment]
@dimasciput I don't see that format in the data spreadsheet - all the reference formats are standardised, but the metadata table on staging is still giving inconsistent reference formats. Any idea why that might be?

[SA fish data for FBIS v3__19 May2020.xlsx](https://github.com/kartoza/django-bims/files/4681416/SA.fish.data.for.FBIS.v3__19.May2020.xlsx)

Here is an example of three different author formats in the metadata table on staging...

<img width="1243" alt="Screenshot 2020-05-26 at 12 10 06" src="https://user-images.githubusercontent.com/44292029/82888742-02b47a80-9f4a-11ea-82bc-a9fc3630cfc4.png">

**Comment by dimasciput** [comment]
@jeremyshelton Ah probably the reference data is still using old data, I didn't know that you also changed the reference data. They are different table. Would you like to update it manually from admin page? I'll show you how, then we don't need to re-harvest the data.

**Comment by jeremyshelton** [comment]
OK we can try that and see how do-able it is. 
@Aneri16 perhaps this is something you can help with? (see above comments for the gist of this issue)

**Comment by Aneri16** [comment]
@jeremyshelton sure I can look into that

**Comment by jeremyshelton** [comment]
Cool! @dimasciput can you please show @Aneri16 how to update references on FBIS?

**Comment by dimasciput** [comment]
@Aneri16 
If the reference type is a peer-reviewed scientific article then follow this steps :
- Go to this page http://staging.freshwaterbiodiversity.org/bibliography/
- Search the reference by the title
- Click edit in admin page (you need to be a super user for this, use fbis account)
- Go to the bottom of the page, check the Author entry rank panel : 
![image](https://user-images.githubusercontent.com/1979569/82897570-fcda8b80-9f81-11ea-9ffc-e473b3355c1b.png)
Change the author by choosing the correct name from the dropdown, save when finish. 

If the reference is not a peer-reviewed scientific article, just write the reference here, I'll fix it later. Thanks.

**Comment by dimasciput** [comment]
@jeremyshelton 
> The taxa graph becomes meaningless when there are too many taxa to display. 
Let's do this in next version or I can fix it in RBIS then bring the changes to FBIS.

**Comment by jeremyshelton** [comment]
> @jeremyshelton
> 
> > The taxa graph becomes meaningless when there are too many taxa to display.
> 
> Let's do this in next version or I can fix it in RBIS then bring the changes to FBIS.

@dimasciput no problem 👍

**Comment by dimasciput** [comment]
@jeremyshelton 
> Pie charts: Need a way to download more than one pie chart. Maybe add a download button for each? Also, the pie chart needs its legend to be downloaded with it.

Updated https://github.com/kartoza/django-bims/pull/2139

**Comment by helendallas** [comment]
@jeremyshelton PLease check this ticket, there is a separate ticket for the pie charts, so if the other items have been sorted, then please close the ticket.
