### ISSUE TITLE
MAP & GENERAL (testing v4)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2056]
@dimasciput @helendallas @timlinux 

**Landing page**
- can we replace the current banner image with [this one](https://www.dropbox.com/s/sq5nxjum4po5x7e/landing%20page%20banner.JPG?dl=0)

**Contact page**
- Please make font size and style consistent with rest of site. 
- Please use #18AO90 instead of dark green where possible
- Please replace background image with [this one](https://www.dropbox.com/s/vucmbygilkborf6/fishpic9.JPG?dl=0)

**Map** 
- @dimasciput please add a scale bar for the map @NyakudyaA  
On the map, can we use a double-click to zoom in and a right click on the layer to show layer properties? (at the moment a double click seems to do both, which is confusing?)
- Can you make the size of the site dots a bit smaller?
- Sites legend: do we still need those brown categories? They don't seem to be in use on the map? Maybe we need new categories: 1 site, 2-10 sites, >100 sites, or something like that ? @timlinux @dimasciput 
- Buttons: can we make all button spill shape, and this colour (or grey) throughout site?
<img width="89" alt="Sites overview" src="https://user-images.githubusercontent.com/44292029/79966065-2ab54780-848d-11ea-9a9e-d8a15982b340.png">
- Please replace the dark green colour with #18AO90 throughout if possible?
<img width="1440" alt="Site Dashboard" src="https://user-images.githubusercontent.com/44292029/79966219-64864e00-848d-11ea-8c64-1d521ef54073.png">
- Can we make the menu bar text size a bit smaller please?
<img width="1060" alt="Screenshot 2020-04-22 at 11 40 07" src="https://user-images.githubusercontent.com/44292029/79966706-1c1b6000-848e-11ea-8158-5598d05838b5.png">

**Flat pages** (contact, login, add site etc)
- Can we make sure font and colours are consistent with the rest of the site?
- Are we able to adjust the background image? Can we do it in Admin panel?

**Icons**
Would be cool if we could replace current icons with these (see ticket #1286)
Light grey when unselected, #18AO90 when selected, or on home page & dashboards.
These files are on dropbox here:
- [fish](https://www.dropbox.com/s/8tgghcdgja0w8uo/fish%20icon.png?dl=0)
- [invertebrate](https://www.dropbox.com/s/z3er0ib70uzagk6/invertebrate%20icon.png?dl=0)
- [algae](https://www.dropbox.com/s/1ho5j3p2g2xighg/algae%20icon.png?dl=0)

**Logo**
Please replace old logo with new one, available [here](https://www.dropbox.com/s/6ox6g5wrfxp73qn/Freshwater%20Biodiversity%20Information%20System%20%28FBIS%29%20v3-02.png?dl=0)
**Favicon**
Favicon for the website is available [here](https://www.dropbox.com/s/u6n0cbg4ymb43qc/fav.png?dl=0)

**Profile**
- @helendallas I think we can simplify the user profile
- less categories might encourage more people to complete them
- I think al we need is: headshot, name, affiliation, position at affiliation, address, phone number, email address?

**Comment by timlinux** [comment]
> @dimasciput @helendallas @timlinux
> 
> **Landing page**
> 
> * can we replace the current banner image with [this one](https://www.dropbox.com/s/sq5nxjum4po5x7e/landing%20page%20banner.JPG?dl=0)
> 

OK

> **Contact page**
> 
> * Please make font size and style consistent with rest of site.
> * Please use #18AO90 instead of dark green where possible
> * Please replace background image with [this one](https://www.dropbox.com/s/vucmbygilkborf6/fishpic9.JPG?dl=0)
> 

OK

> **Map**
> 
> * @dimasciput please add a scale bar for the map @NyakudyaA

OK - or maybe just a numeric scale?

>   On the map, can we use a double-click to zoom in and a right click on the layer to show layer properties? (at the moment a double click seems to do both, which is confusing?)

Right click is reserved for the browser itself and would go against normal expectations of how a user should interact with a web page.

> * Can you make the size of the site dots a bit smaller?

Yes - I will make them small at small scale, larger at large scale

> * Sites legend: do we still need those brown categories? They don't seem to be in use on the map? Maybe we need new categories: 1 site, 2-10 sites, >100 sites, or something like that ? @timlinux @dimasciput

You get the brown showing if you zoom out. I will look and see if I can tweak the categories easily.

![image](https://user-images.githubusercontent.com/178003/80580672-d61d4980-8a03-11ea-8e18-76e4c11bc731.png)


> * Buttons: can we make all button spill shape, and this colour (or grey) throughout site?
> 

I think this is going to be a huge job - let's try to upstream this into our RBIS work where we focus on theming etc.

> <img alt="Sites overview" width="89" src="https://user-images.githubusercontent.com/44292029/79966065-2ab54780-848d-11ea-9a9e-d8a15982b340.png">
> 
> - Please replace the dark green colour with #18AO90 throughout if possible?
> <img alt="Site Dashboard" width="1440" src="https://user-images.githubusercontent.com/44292029/79966219-64864e00-848d-11ea-8c64-1d521ef54073.png">
> 

OK

> - Can we make the menu bar text size a bit smaller please?
> <img alt="Screenshot 2020-04-22 at 11 40 07" width="1060" src="https://user-images.githubusercontent.com/44292029/79966706-1c1b6000-848e-11ea-8158-5598d05838b5.png">

OK

> 
> **Flat pages** (contact, login, add site etc)
> 
> * Can we make sure font and colours are consistent with the rest of the site?
> * Are we able to adjust the background image? Can we do it in Admin panel?
> 

Just note that contact, login etc are not flat pages, so can't be tweaked from the admin panel.

Do you mean the lilly pad pic?

Let's hold this until another release ok?

![image](https://user-images.githubusercontent.com/178003/80580946-44faa280-8a04-11ea-8490-25f54892bcb2.png)

Can we leave this for now and focus on higher value changes?

> **Icons**
> Would be cool if we could replace current icons with these (see ticket #1286)
> Light grey when unselected, #18AO90 when selected, or on home page & dashboards.
> These files are on dropbox here:
> 
> * [fish](https://www.dropbox.com/s/8tgghcdgja0w8uo/fish%20icon.png?dl=0)
> * [invertebrate](https://www.dropbox.com/s/z3er0ib70uzagk6/invertebrate%20icon.png?dl=0)
> * [algae](https://www.dropbox.com/s/1ho5j3p2g2xighg/algae%20icon.png?dl=0)

OK

> 
> **Logo**
> Please replace old logo with new one, available [here](https://www.dropbox.com/s/6ox6g5wrfxp73qn/Freshwater%20Biodiversity%20Information%20System%20%28FBIS%29%20v3-02.png?dl=0)

OK

> **Favicon**
> Favicon for the website is available [here](https://www.dropbox.com/s/u6n0cbg4ymb43qc/fav.png?dl=0)
> 

OK

> **Profile**
> 
> * @helendallas I think we can simplify the user profile
> * less categories might encourage more people to complete them
> * I think al we need is: headshot, name, affiliation, position at affiliation, address, phone number, email address?

Can we park this for now?

**Comment by jeremyshelton** [comment]
Thanks @timlinux. Sounds good to me. Happy to park the biker tasks you identified for the next version.

**Comment by dimasciput** [comment]
From my side : 

**Landing Page**

- [x] can we replace the current banner image with this one

**Contact Page**

- [x] Please make font size and style consistent with rest of site.
- [x] Please use #18AO90 instead of dark green where possible
- [x] Please replace background image with this one

**Map**
- [x] please add a scale bar for the map

**Others**
- [x] Please replace the dark green colour with #18AO90 throughout if possible?
- [x] Can we make the menu bar text size a bit smaller please?

**Icons**
- [x] Icon updated in landing page

> Light grey when unselected, #18AO90 when selected, or on home page & dashboards.

@jeremyshelton sorry you can only change color of svg images, not png. We can only make png image brighter/darker, which what we did now. 

**Logo**
- [x] Please replace old logo with new one, available here

**Favicon**
- [x] Favicon for the website is available here

**Comment by jeremyshelton** [comment]
@dimasciput thank you. 

The image on the contact us page looks very zoomed in: 

<img width="1440" alt="Screenshot 2020-05-04 at 10 06 06" src="https://user-images.githubusercontent.com/44292029/80946826-2e32c200-8def-11ea-8f97-4a10297e0943.png">

It should look like this:

![fishpic9](https://user-images.githubusercontent.com/44292029/80946845-3ee33800-8def-11ea-97d3-cc24638ddc69.JPG)

Also, text in log pout page can be standardised to match other pages:

<img width="1414" alt="Screenshot 2020-05-04 at 10 06 37" src="https://user-images.githubusercontent.com/44292029/80946880-57ebe900-8def-11ea-8e85-86041786c79a.png">

**Comment by jeremyshelton** [comment]
@dimasciput the log out page is still very zoomed-in. Please adjust it like you did for the other pages (see above). Then we can close the ticket.
