### ISSUE TITLE
Develop option to download complete Master List of Species or Taxa for each module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2058]
We need to be able to download the Master List of Species or Taxa for algae, invertebrates and fish.  This list needs to look like the ones ingested and include the following columns:

**Algae:**
Taxon rank | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon |  Scientific Name and authority | GBIF URL | Division | Growth form | Origin | Endemism | Conservation status

**Invertebrates:**
Taxon Rank | Kingdom | Phylum | Class | Order | Family | Genus | Species | SubSpecies | Taxon | Scientific name and authority | GBIF URL | Origin | Endemism | Conservation status | Former scientific names

**Fish:**
Taxon rank | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon | Scientific name and authority | GBIF URL | Common name | Origin | Endemism | Conservation status | Eco-tolerance | SANBI NBA List | Recorded in SA | _Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies_ | Former scientific name
@jeremyshelton Please consider creating separate rows for each subSpecies as I did in Invertebrates.

@dimasciput @timlinux If this is an easy task it would be good to include in V3, but alternatively we can include it in RBIS.

We need to decide where it is best served fro FBIS users to download and use.

**Comment by jeremyshelton** [comment]
@helendallas for fish everything in bold does not need to be included in this. We are only working with one fish subspecies (Anguilla bengalensis labiata), which is currently represented in the the 'taxon' column (this subspecies does have its own row). Hesitant to change the master list at this stage?

Fish:
Taxon rank | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon | Scientific name and authority | GBIF URL | Common name | Origin | Endemism | Conservation status | Eco-tolerance | **SANBI NBA List | Recorded in SA | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies | Subspecies |** Former scientific name

**Comment by helendallas** [comment]
@timlinux Current download option on Taxa Management in RBIS staging needs fixing. Please see file attached.
[From RBIS Odonata Adults.xlsx](https://github.com/kartoza/django-bims/files/5282480/From.RBIS.Odonata.Adults.xlsx)

Also please see details for each module described above.

**Comment by helendallas** [comment]
The CSV Download file needs to exactly as the Master List of Taxa for the group please.

Also still some old terminology such as "alien-non-invasive"

**Comment by dimasciput** [comment]
this can be done on RBIS
