### ISSUE TITLE
Harvest GBIF invertebrate and algae data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2059]
We need to harvest GBIF data using the Master List of Invertebrates and Algae. GBIF data need to be kept separated as it is with fish using the Data Sources. 

All FBIS data should be served by default, while GBIF data should only be served when the user clicks the GBIF box in Data Sources. 

Importantly, for invertebrates, GBIF data includes both freshwater and terrestrial taxa, as GBIF do no differentiate between occurrence records of aquatic taxa and aerial phases. So we need this to be expressed somewhere.

**Comment by dimasciput** [comment]
Hi @helendallas, 

> We need to harvest GBIF data using the Master List of Invertebrates and Algae. GBIF data need to be kept separated as it is with fish using the Data Sources.

Should I fetch gbif data for all taxon rank? I think we should limit it to SPECIES? If not we will getting huge data.

> Importantly, for invertebrates, GBIF data includes both freshwater and terrestrial taxa, as GBIF do no differentiate between occurrence records of aquatic taxa and aerial phases. So we need this to be expressed somewhere.

I'm not sure how to differentiate this, is there a list of species that belongs to aquatic taxa or aerial?

**Comment by helendallas** [comment]
@dimasciput 
Yes, I agree, lets limit GBIF data to species only. 

There is not list, but we can add a note informing users that GBIF data is aquatic and aerial, thanks (not sure exactly where. I will add it to the manual but perhaps below: by adding the following:
**Invertebrate data includes both aquatic and aerial stages.**
![Screenshot_2020-04-28 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/80473414-65642780-8946-11ea-81cd-47db32755c12.png)

**Comment by helendallas** [comment]
@dimasciput **Was algal data also harvested?**  I can see invertebrates and updated text.

**Comment by dimasciput** [comment]
@helendallas yes you are correct, only 16 data for algae species.

**Comment by helendallas** [comment]
@dimasciput 
I dont think there are any GBIF data fro invertebrates or algae as the number of records and taxa are exactly the same . 
Algae:
![Screenshot_2020-05-18 FBIS Map(5)](https://user-images.githubusercontent.com/45286876/82213521-8ea82000-9914-11ea-992a-1ac2aa9d6328.png)

![Screenshot_2020-05-18 FBIS Map(6)](https://user-images.githubusercontent.com/45286876/82213542-9b2c7880-9914-11ea-91ca-11eaa7570bff.png)

Invertebrates
![Screenshot_2020-05-18 FBIS Map(7)](https://user-images.githubusercontent.com/45286876/82213582-ae3f4880-9914-11ea-9042-e3404cd87cbd.png)

![Screenshot_2020-05-18 FBIS Map(8)](https://user-images.githubusercontent.com/45286876/82213604-bb5c3780-9914-11ea-8814-3e05315847cf.png)

**Comment by helendallas** [comment]
@dimasciput Difficult to check as map freezes. Can the GBIF invertebrate and algal data be cropped so that only data in South Africa, Lesotho and Swaziland are shown please.

Algal records have some in the ocean, which we need to hide.

**Comment by dimasciput** [comment]
@helendallas done, removed all gbif records outside south africa

**Comment by helendallas** [comment]
@dimasciput @NyakudyaA 
I cant test because as soon as I hit the search button to return all records it takes me here and freezes.
![image](https://user-images.githubusercontent.com/45286876/82987823-80cf5a80-9ff8-11ea-9d3d-a7be71788175.png)

Perhaps update rogue records, since some of these have already had georeferences corrected see #2135 and then I can retry

**Comment by helendallas** [comment]
@dimasciput Looking great and also fast.
Question:
Site codes - is this still being " fetched"
![image](https://user-images.githubusercontent.com/45286876/83106407-b3db2200-a0bc-11ea-9d0e-47123d55fa1c.png)

**Comment by dimasciput** [comment]
@helendallas can you check it again now, it's missing code from the catchment data but it should fixed when geocontext is ready again.

**Comment by helendallas** [comment]
@dimasciput All workingthanks
