### ISSUE TITLE
Citation erors

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2060]
@dimasciput there seems to be an issue with the following citations, in that the format is not the same as the rest. Any idea why that might be? Best way to fix? Is it maybe old references?

![ref bug](https://user-images.githubusercontent.com/44292029/80209399-4d349580-8632-11ea-966c-884e83547fcf.png)

@helendallas @Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton the missing name between the commas is a journal name, let me just hide it if there is no journal name

**Comment by helendallas** [comment]
@dimasciput I think Jeremy meant the strange Authors....

B.M and A.A
etc, it is not like this in the imported data

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/80469760-39a76880-896b-11ea-8d4e-56cf47fad1ce.png)

Is this better?

**Comment by helendallas** [comment]
Some still some coming through strangely  - a few examples
![Screenshot_2020-04-28 FBIS Bibliography](https://user-images.githubusercontent.com/45286876/80470126-d8b76a80-8941-11ea-832c-4d4943350fd4.png)

![Screenshot_2020-04-28 FBIS Bibliography(4)](https://user-images.githubusercontent.com/45286876/80470281-13210780-8942-11ea-8a79-0b72406a9f02.png)
![Screenshot_2020-04-28 FBIS Bibliography(2)](https://user-images.githubusercontent.com/45286876/80470290-161bf800-8942-11ea-9a9b-a5bf449ee20b.png)
![Screenshot_2020-04-28 FBIS Bibliography(2)](https://user-images.githubusercontent.com/45286876/80470301-17e5bb80-8942-11ea-81c1-bfa83454e0b0.png)

**Comment by dimasciput** [comment]
@helendallas no I haven't deployed it yet, it's still on my computer. I was only asking if the citation I posted is better.

**Comment by helendallas** [comment]
@dimasciput ah, Yes, then that is much better, thanks

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

Unable to test this at present because reference search bar not working. Also, the first entry is 'Houseing Development', which of course is not an FBIS reference :)

<img width="285" alt="Screenshot 2020-05-13 at 09 39 45" src="https://user-images.githubusercontent.com/44292029/81784925-e5b98980-94fd-11ea-9e36-1fc84d53d848.png">

**Comment by helendallas** [comment]
> 
> 
> @dimasciput @helendallas
> 
> Unable to test this at present because reference search bar not working on staging. Also, the first entry is 'Houseing Development', which of course is not an FBIS reference :)
> 
> <img alt="Screenshot 2020-05-13 at 09 39 45" width="285" src="https://user-images.githubusercontent.com/44292029/81784925-e5b98980-94fd-11ea-9e36-1fc84d53d848.png">

@jeremyshelton This is a different issue. I am referring to the Citations in the Admin Section.

When you go to Author...strange abbreviation of authors are returned.

@dimasciput Still an issue in the filter although the citation seems to be corrected.

![image](https://user-images.githubusercontent.com/45286876/82217200-5e638000-991a-11ea-972e-11a22e730726.png)

**Comment by helendallas** [comment]
@dimasciput Using the Citation filter - Author is really problematic as the same author is expressed multiple times.

Please see #2033 

It needs to be worked on in RBIS please. I am going to close this ticket.
