### ISSUE TITLE
Add an option to enable / disable visibility of non biodiversity layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#2072]
# Problem

In some cases, we might want to disable visibility for some layers without actually deleting the definitions. 

Adding a checkbox would help in this regard

![delete](https://user-images.githubusercontent.com/2510900/80465564-8ecb8600-893b-11ea-8e62-eaf1047e3bf8.png)

**Comment by timlinux** [comment]
@NyakudyaA I am going to close this since I cannot see a concrete need for it right now. Please reopen if I am missing something.
