### ISSUE TITLE
Data users agreement

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2082]
We need to add a 'Data users agreement' checkbox as a pre-requisite for anyone downloading .csv files. 

Thoughts on this @helendallas & @timlinux? Is this quick & easy to do, or should I ticket for the next version instead?

We can look at GBIF for guidance

**Comment by helendallas** [comment]
@jeremyshelton It is a good idea. I would also like to explore how we an keep track of what FBIS data is used for. ie.e What reports are produced, papers written etc. Perhaps a form that a user can elect to complete after downloading data? not that everyone will but its worth thinking about
