### ISSUE TITLE
Correct Near bed velocity to m/s

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2091]
Near bed velocity units should be m/s

<img width="199" alt="Screenshot 2020-05-04 at 16 54 19" src="https://user-images.githubusercontent.com/44292029/80979921-3f4bf500-8e28-11ea-8146-d6f6bd3ec18e.png">

We need a 'back' button alongside the 'next' button at the bottom of each page of the add data work flow 

<img width="902" alt="Screenshot 2020-05-04 at 16 54 26" src="https://user-images.githubusercontent.com/44292029/80980008-61de0e00-8e28-11ea-81e8-0a523908bd56.png">

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 
- We need a 'back' button alongside the 'next' button at the bottom of each page of the add data work flow

Please not on this version, this will take a long time to implement, because the previous form has been submitted and we cannot edit it from there.

- Near bed velocity units should be m/s

This can be fixed on the admin page. https://testing.healthyrivers.kartoza.com/admin/bims/chem/

**Comment by dimasciput** [comment]
That's why I added this when user try submitting the form : 
![image](https://user-images.githubusercontent.com/1979569/81029011-ad86cb00-8ead-11ea-876f-f33be0022b96.png)

**Comment by jeremyshelton** [comment]
@dimasciput OK that should be fine. Inly problem is if user wants to go back more than one step?

**Comment by timlinux** [comment]
@jeremyshelton can we park this for future work please? We can keep it in the backlog and try to work it in through future work. Thanks

**Comment by jeremyshelton** [comment]
Sure. I'll shift the ticket to v5.

**Comment by helendallas** [comment]
@dimasciput I cannot fix near bed velocity as there is no m/s option
![image](https://user-images.githubusercontent.com/45286876/86472147-fc7e9e80-bd3e-11ea-9273-51b9b96be15f.png)

For long term sustainability the administrator should be able to add a new **Chem unit.**

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/95534387-e5231180-0a0f-11eb-9c79-ad831108d832.png)

Updated to m/s

**Comment by dimasciput** [comment]
@jeremyshelton
