### ISSUE TITLE
We need to deploy a blank version for RBIS

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2101]

**Comment by dimasciput** [comment]
@timlinux can you create a new Repo for RBIS?

**Comment by timlinux** [comment]
RBIS Skin repo is here:

https://github.com/kartoza/rwanda-biodiversity-portal

**Comment by timlinux** [comment]
And @dimasciput has access:

![image](https://user-images.githubusercontent.com/178003/82898862-e7e60400-9f51-11ea-940a-aa10d38b0ce8.png)
