### ISSUE TITLE
Taxon summary download should be CSV not image

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2106]
It will be more useful if we can download this list as CSV:

![image](https://user-images.githubusercontent.com/178003/81786388-7b054f80-94f7-11ea-89d4-31724d381d46.png)

**Comment by helendallas** [comment]
@timlinux You can already download the data as a csv. It is also useful to have the option to download as a png, so please can we retain as is.  Please close ticket if you agree.

![image](https://user-images.githubusercontent.com/45286876/94895354-8d266100-048b-11eb-8e1b-cc8dbe346f22.png)

**Comment by timlinux** [comment]
Thanks Helen, agreed
