### ISSUE TITLE
Strange grey colour in pie charts?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2117]
Strange grey categories in pie charts, not shown in legend?

<img width="854" alt="Screenshot 2020-05-15 at 11 55 35" src="https://user-images.githubusercontent.com/44292029/82041852-243f7780-96a9-11ea-9a1e-45d3f7084eff.png">

**Comment by dimasciput** [comment]
@jeremyshelton fixed

**Comment by jeremyshelton** [comment]
Nice. Closing.
