### ISSUE TITLE
Remove map border

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2119]
@NyakudyaA @dimasciput 
As per our call on wednesday, please van you fix the borders on the live site.
![Screenshot_2020-05-18 FBIS Map](https://user-images.githubusercontent.com/45286876/82192684-9952bd00-98f4-11ea-8cf0-9a31583d4753.png)

We need to open the site soonest, and outstanding issues need to be fixed asap.
@timlinux 
@dimasciput @jeremyshelton

**Comment by timlinux** [comment]
![Screenshot 2020-05-25 at 10 57 45](https://user-images.githubusercontent.com/178003/82802410-bfd5a280-9e76-11ea-8696-c836b2b46371.png)

Looks like this now on Testing @helendallas

**Comment by timlinux** [comment]
At mid scale:

![image](https://user-images.githubusercontent.com/178003/82802605-1216c380-9e77-11ea-9772-0bee2eb44dbc.png)

Note we have a rogue fish record in the sea there.

**Comment by timlinux** [comment]
Note that rendering will be a bit slow initially while the tile cache builds up

**Comment by jeremyshelton** [comment]
Thanks @timlinux 
Don't think Dimas has done the new data fish yet, so let's check for rogues once he's done with that. I have listed some map issues on #1863

**Comment by dimasciput** [comment]
@jeremyshelton I have ingested the fish data to staging

**Comment by jeremyshelton** [comment]
Thanks @dimasciput We are checking it now. Will send a message when we are done checking and then we can pull GBIF fish data from the new master list 👍
