### ISSUE TITLE
Spatial filter not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2120]
@dimasciput I selected Primary region = G
sites in E and G returned
![Screenshot_2020-05-18 FBIS Map(9)](https://user-images.githubusercontent.com/45286876/82214491-370ab400-9916-11ea-857e-723c73115c7d.png)

http://staging.freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20G%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=11215&polygon=

**Comment by dimasciput** [comment]
@helendallas re-fetching data from geocontext, should be done in Thursday
