### ISSUE TITLE
Duplicate taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2121]
@dimasciput There are still duplicate taxa being returned for the same reason as I indicated before - different Origins Unknown versus Native. All origins should be based on the master list.

![Screenshot_2020-05-18 FBIS Map(10)](https://user-images.githubusercontent.com/45286876/82214994-f2cbe380-9916-11ea-945d-0b30ac034933.png)

**Comment by helendallas** [comment]
Some issues are fixed but still a problem at family - may be related to taxa being in SASS and the master list?

Another example:
http://staging.freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,secondary_catchment_area,E1%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=
See 
![image](https://user-images.githubusercontent.com/45286876/82420528-20806c00-9a80-11ea-83fa-a548cc73f823.png)

![image](https://user-images.githubusercontent.com/45286876/82420598-3857f000-9a80-11ea-82b3-fbb1b5cc34d7.png)
![image](https://user-images.githubusercontent.com/45286876/82420684-5b829f80-9a80-11ea-8ce6-5e0dc651fc89.png)

@dimasciput What can I do to help?

**Comment by helendallas** [comment]
@dimasciput Still duplicates at family level e.g
Athericidae
Blephariceridae
Ceratopogonidae
etc.

http://staging.freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,secondary_catchment_area,E1%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=21&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
@dimasciput Looks okay on the dashboard. but I cannot download the csv to check

**Comment by helendallas** [comment]
@dimasciput Thanks checked, all looks fine
