### ISSUE TITLE
Detailed dashboard - map not visible

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2122]
@dimasciput The map is not visible

![Screenshot_2020-05-18 FBIS Map(11)](https://user-images.githubusercontent.com/45286876/82215364-9b7a4300-9917-11ea-85b4-322ecc684752.png)

http://staging.freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,secondary_catchment_area,G1%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@helendallas Please try again

**Comment by helendallas** [comment]
@dimasciput working thanks
