### ISSUE TITLE
Documents - error message on editing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2123]
I am trying to correct wrong owners. get error message, 

![image](https://user-images.githubusercontent.com/45286876/82217996-82739100-991b-11ea-9208-44444003c055.png)

**Comment by helendallas** [comment]
@dimasciput I am still getting the error message

![image](https://user-images.githubusercontent.com/45286876/82914936-66ea3500-9f70-11ea-9cd8-ecee90480b70.png)

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
Sorry reopening - 
![image](https://user-images.githubusercontent.com/45286876/82985875-1a950880-9ff5-11ea-9431-aa8d97df312f.png)

In Documents, I tried to edit by removing the authors from title and adding it to Owner, and changing data to 2002. This resulted in an error message.

![image](https://user-images.githubusercontent.com/45286876/82985646-b4a88100-9ff4-11ea-9cd8-0f2a35c958ac.png)

I really dont understand where I need to edit this reference and how to get it to be cited correctly in the Metadata table.

The owner can be FBIS in the case of many historical document,s but there is no where to include the authors then unless we include it in the title, which is wrong. This has been an issue for some time and is driving me nuts

Please help and guide me how to get the citation correct.

**Comment by dimasciput** [comment]
@helendallas I think it's already updated, just need some time for the system to update the metadata table.
![image](https://user-images.githubusercontent.com/1979569/82989463-f2250280-a024-11ea-96d7-ad6b1178e977.png)
Just ignore the 500 now, I will investigate it later, but your edits should be saved.

**Comment by helendallas** [comment]
@dimasciput  Not sure, as now the document is not visible on filter:
![image](https://user-images.githubusercontent.com/45286876/82991692-5c767c80-9ffe-11ea-87f3-3bc4cf3f7758.png)

**Comment by dimasciput** [comment]
@helendallas 
![image](https://user-images.githubusercontent.com/1979569/82992099-dde30480-a028-11ea-9dfc-7e1deb61f849.png)
Yes correct, the filter is only for the title of the document and since you remove the authors from the title it will not visible.

**Comment by helendallas** [comment]
@dimasciput Ok of course. 

I prefer the authors in the title, nut then it comes out wrong in the metadata table....**_### What are you recommendations?_**

I almost always search using authors, and unless authors are in the title, its very hard to find a reference

**Comment by dimasciput** [comment]
@helendallas I will update the filter for version 5, so you can search with the author too. What do you think?

**Comment by helendallas** [comment]
@dimasciput 

I would be keen to sit with you and smooth out document and citations, to make it easier to manage and filter, so yes, let park for RBIS. Similar ticket already exists #2033 

Thanks

I will close this ticket for now

**Comment by dimasciput** [comment]
@helendallas thanks, I also have some ideas to make it all more easier, just need more time to do that.
