### ISSUE TITLE
The print button is broken

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2133]
**Describe the bug**
When I try to print, nothing happens.

**To Reproduce**

1. Go to http://freshwaterbiodiversity.org/foo/bar
2. Click on 'Print'
3. Wait

**Expected behavior**
When I press the print button, I expect to see a map printed out of my printer.

**Screenshots**

![Screenshot 2020-05-26 at 08 30 32](https://user-images.githubusercontent.com/178003/82872619-32a05580-9f2b-11ea-8229-b5114762f6c4.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser  Safari
 - Version  13.1

**Smartphone (please complete the following information):**

**Additional context**
There is an article on printing from web pages here: http://someinterestingarticle.com

**Comment by timlinux** [comment]
This is a first comment

![Screenshot 2020-05-26 at 08 36 23](https://user-images.githubusercontent.com/178003/82873158-fcafa100-9f2b-11ea-8b1a-e8b1bd6d1a0a.png)

http://kartoza.com

**Comment by dimasciput** [comment]
@timlinux I assume this is not a real issue

**Comment by timlinux** [comment]
@dimasciput correct we are just using this issue for training

**Comment by mmindje** [comment]
@Tim can you again define what you are calling Ticket?

**Comment by timlinux** [comment]
@mmindje A ticket is another name for an issue or a story - something that needs to be achieved on the system by the team.

**Comment by helendallas** [comment]
@mmindje  Ticket = issue

**Comment by mmindje** [comment]
@timlinux Thank you. I get it now

**Comment by timlinux** [comment]
@Deborahcyu Can you add your comment please?

**Comment by DanielIgirimbabazi** [comment]
@timlinux Is there any specific video tutorial for using GitHub for beginners that you may recommend after the meeting?

**Comment by Deborahcyu** [comment]
i get it, ticket is like an issue but there is another name you gave it @timlinux  ...what was that?

**Comment by timlinux** [comment]
@Deborahcyu we also sometimes call them 'stories'

**Comment by helendallas** [comment]
Issues are listed in the Issue column
![image](https://user-images.githubusercontent.com/45286876/82874546-63d25300-9f36-11ea-95ca-5b9c7336e246.png)

The most recent issue is listed first
![image](https://user-images.githubusercontent.com/45286876/82874598-79e01380-9f36-11ea-9e47-77f6d373e314.png)

**Comment by bakaplin** [comment]
how do we find the handles (names) for the project people so we use the correct name  @timlinux

**Comment by mmindje** [comment]
@bakaplin I am using the **@** then a list of participants is shown and you can click on the one you refer to .....or if you know the username after @ then type it and there you go.

**Comment by cembonace** [comment]
@mmindje : You are right.

**Comment by timlinux** [comment]
#2134 I closed this because it was a test ticket

**Comment by timlinux** [comment]
We need to support birds:

- [ ] #1207 - Add a legend
- [ ] #2119 - Remove the map border

**Comment by timlinux** [comment]
[GitHubIssueManagementOverview.pdf](https://github.com/kartoza/django-bims/files/4680846/GitHubIssueManagementOverview.pdf)
