### ISSUE TITLE
Rogue biodiversity records

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2135]
We have some records in the sea or outside the study domain.

- [x] @dimasciput to share latest database dump with Tim
- [x] Tim to compile a list and then 
- [ ] pass on to @helendallas for review

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/82902286-24682e80-9f57-11ea-84bd-7fe21b8aa81e.png)

So @helendallas the map above shows three colours:

1. Gree circles are 'good' records inside SA boundaries
2. Yellow is the invers selection of everything outside SA
3. Red is yellow minus records which are on the terrestrial borders (Namibia etc) and also Lesotho and eSwatini removed.

**Comment by timlinux** [comment]
Some of the red may still be good but are doubtful e.g.

![image](https://user-images.githubusercontent.com/178003/82902528-7c9f3080-9f57-11ea-968a-8399e171367d.png)

Attached are the outliers as XLS sheet 

[fbis-outliers.xlsx](https://github.com/kartoza/django-bims/files/4682285/fbis-outliers.xlsx)

**Comment by timlinux** [comment]
You can also explore the outliers interactively here on a map:

https://gist.github.com/timlinux/a7f6520c159ec69b0490b7519bbceaa3

If you click on clusters they will zoom in and eventually show individual records.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/82903300-a86ee600-9f58-11ea-85ca-7e48a369619a.png)

**Comment by helendallas** [comment]
@timlinux @dimasciput 
A number of these which are invertebrates were fixed in version2. I am not sure why they are now wrong again. 

Maybe because Dimas rolled back from a backup at some stage. He will need to please update all coordinates again suing this spreadsheet, then we can check again which records are rogue.

see #915
I am attaching the georeference excel file for updating.
![image](https://user-images.githubusercontent.com/45286876/82906192-2a650c00-9f65-11ea-8d59-cc7a5b77642d.png)

Some are for fish data, but might be brought in through the fish data ingested that were from the RIvers database, in which case if the Site code was the same the existing site should of been used.

[RIvers Database Corrected SiteCodes.xlsx](https://github.com/kartoza/django-bims/files/4682501/RIvers.Database.Corrected.SiteCodes.xlsx)

**Comment by dimasciput** [comment]
@helendallas I have run the script again, please test it

**Comment by helendallas** [comment]
@dimasciput 
This has fixed some, some are still rogue . Are you able to send me a new list so I can manually work through the rogue records.

An excel file as tim sent is best, then I just punch in the code in FBIS and check the description, then the study reference to update the location.

@timlinux

**Comment by dimasciput** [comment]
@helendallas ok, will create a script for this.

**Comment by dimasciput** [comment]
Sites outside SA : 
[sites_outside_sa.xlsx](https://github.com/kartoza/django-bims/files/4688446/sites_outside_sa.xlsx)

**Comment by helendallas** [comment]
@dimasciput Some are correct and in SA

![image](https://user-images.githubusercontent.com/45286876/83015012-0dd9da00-a020-11ea-9532-ed959d146d5d.png)

Please cna you check.

And some already updated on live site yesterday

A2CROC-MOUNT
--
B7OLIF-EWR2
B8SHIN-ALTEI

**Comment by dimasciput** [comment]
@helendallas ah sorry I run this script on testing! Let me run it from staging.

**Comment by dimasciput** [comment]
Here is the updated sites @helendallas : 
[sites_outside_sa_updated.xlsx](https://github.com/kartoza/django-bims/files/4688539/sites_outside_sa_updated.xlsx)

**Comment by helendallas** [comment]
@dimasciput Thanks

**Comment by helendallas** [comment]
@dimasciput none of the first 4 sites come up. zero records

![image](https://user-images.githubusercontent.com/45286876/83016562-732eca80-a022-11ea-8bc3-68b4fb158a57.png)

**Comment by helendallas** [comment]
@dimasciput is this because a buffer has already been created. If so I should be able to fix first.

**Comment by dimasciput** [comment]
@helendallas apparently they are data from GBIF (but not all of them), and heads up the site is very slow at the moment, admire is still fixing the layers.

**Comment by helendallas** [comment]
@dimasciput is there a way to show which are FBIS sites. I cannot edit GBIS data

**Comment by helendallas** [comment]
@dimasciput GBIF data falling outside the SA boundary need to be excluded automatically

**Comment by dimasciput** [comment]
@helendallas let me just delete them, one sec. I'll give you updated sites

**Comment by dimasciput** [comment]
[sites_outside_sa_updated.xlsx](https://github.com/kartoza/django-bims/files/4688599/sites_outside_sa_updated.xlsx)
@helendallas

**Comment by helendallas** [comment]
@dimasciput 
Please can you do the following in the back end:
Combine sites below: they are the same. Please use the site details for the site with the most records (111).

![Screenshot_2020-05-27 FBIS Map](https://user-images.githubusercontent.com/45286876/83031504-eb05f080-a034-11ea-9ca5-da9412df6826.png)


Please combine K4WOLW-BARNA
with K4WOLW-BARND - use K4WOLW-BARND site details

**Comment by dimasciput** [comment]
@helendallas done
