### ISSUE TITLE
Need to update Broad biotope, Specific biotope and Substratum legacy Biobase data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2136]
@dimasciput I have searched through the tickets for this but cannot find it.  I was sure I created a ticket for this.

Legacy biobase data is not showing any biotopes, although the data are in the legacy database. 

Broad   biotope | Specific biotope | Substratum - are all blank in csv file.

A while back I created a Table showing what each Biobase Biotope needs to be c=reclassified as for FBIS.  Here is the file:

[Biotopes Table from Biobase - with New Broad Biotope_Specific_Subtsratum.xlsx](https://github.com/kartoza/django-bims/files/4683150/Biotopes.Table.from.Biobase.-.with.New.Broad.Biotope_Specific_Subtsratum.xlsx)

Please can you update this for V5.

**Comment by dimasciput** [comment]
Fixed in live

**Comment by helendallas** [comment]
Thanks looks good
