### ISSUE TITLE
Need to update Abundance measure for Legacy Biobase data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2137]
**Legacy** Biobase data exported in the csv file show the Abundance measure to be:
**Number**

This is incorrect.

Please update all Biobase data to be **Abundance measure = Percentage abundance**

**Comment by dimasciput** [comment]
Updated to percentage

**Comment by helendallas** [comment]
@dimasciput Thanks. DO you know why some data have a "-". I suspect they were absent not present.

Abundance measure | Abundance value
Percentage | -
Percentage | -
Percentage | -
Percentage | -

**Comment by helendallas** [comment]
Checked and its fine. Taxa in old database without abundance
