### ISSUE TITLE
Bathymetry must go behind countries

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2138]
![image](https://user-images.githubusercontent.com/178003/83000608-7e71fe00-a002-11ea-99b6-05517f319656.png)

**Comment by NyakudyaA** [comment]
> ![image](https://user-images.githubusercontent.com/178003/83000608-7e71fe00-a002-11ea-99b6-05517f319656.png)

That's already the situation @timlinux , maybe we need to add swaziland polygon so that the outline doesn't show.

![layer-order](https://user-images.githubusercontent.com/2510900/83002108-ed545480-a00c-11ea-8f4f-6d19d9c69bd4.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/83002550-18d34100-a005-11ea-9d67-3514ba837123.png)


Also the buffer is still now showing tucked in under the land @NyakudyaA

**Comment by helendallas** [comment]
Resolved, closing ticket
