### ISSUE TITLE
We need an initial list of datasets in the dataset tracker

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2141]
Following the demo session by @helendallas we need to get the initial overview of available datasets. We will review the first draft next thursday.

**Comment by helendallas** [comment]
Completed on RBIS Data Management Github

**Comment by helendallas** [comment]
@mmindje It would be good to keep this ticket open and updated with the data set tracker.
Please can you update and add the file to this ticket so that we can see where we are. Please can you ask Maurice to add the spatial layer to be used for filtering and contextualising he biodiversity data.

**Comment by helendallas** [comment]
Data set tracker is maintained in the Data-management-FRC-RBIS project, ticket #3
