### ISSUE TITLE
FBIS Mobile view

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2143]
FBIS mobile view not working well. 

Header bar looks squished & map not working on my phone.

@timlinux in your opinion is this something we need to try get right?

<img width="341" alt="Screenshot 2020-06-01 at 12 27 53" src="https://user-images.githubusercontent.com/44292029/83401061-4dc80500-a404-11ea-8a7b-e9c9b11f44a5.png">

**Comment by timlinux** [comment]
@jeremyshelton This is a definite 'park  for future' item for me

**Comment by jeremyshelton** [comment]
@timlinux @dimasciput this is an issue reported by a user - that the site looks jumbled on mobile. Figured it best to make a ticket, but happy to park for future if you think that's best. A lot of people do use mobile to check out a site, so it would be nice to clean up the mobile view a little at some point if possible.
