### ISSUE TITLE
Fish CSV downloads

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2144]
I tried to do a data download of all the data currently on FBIS but the CSV file only has ~17 000 records (see SA fish data.csv), but there should be 313359 records. I then tried to download the FBIS only data, but the CSV file only has ~700 records (see SA fish data_FBIS), but there should be 13709. 
[SA fish data.xlsx](https://github.com/kartoza/django-bims/files/4710811/SA.fish.data.xlsx)
[SA fish data_FBIS.xlsx](https://github.com/kartoza/django-bims/files/4710818/SA.fish.data_FBIS.xlsx)

**Comment by dimasciput** [comment]
@jeremyshelton can you do smaller data? I think our system is not capable to do more than 100k data

**Comment by dimasciput** [comment]
@timlinux what do you think of this? Should we limit the download? Even big platform like twitter will take days to download my data.

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux but fish data (FBIS + GBIF data) is about 33 000 records, which is quite a bit less than 100 000? 

Quite an important thing for users to be able to download this data set. 

Some users are already asking why the search for all fish data (FBIS + GBIF) shows over 33 000 records, but the .csv download of that data set only gives about 17 000?

@timlinux any creative ideas on how we might get big .csv downloads to work correctly?

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton sorry I think more than thousand data is still too much. Let's say one row of data takes 1 second to process, it means for 1000 data it will take 1000*1 = 1000 seconds = 16 minutes. There is no quick solution for this, the only solution is to email the data to user but limit to only one download per user, if not the server will break.

**Comment by jeremyshelton** [comment]
OK thanks for that info @dimasciput 
Let's add this to the agenda for today's 11h00 meeting.
@timlinux @helendallas

**Comment by jeremyshelton** [comment]
**10 June 2020 update:**

Fish .csv download (all data, FBIS + GBIF) now giving 33561 records, but the correct number should be 33641....so we're about 100 records short?

@dimasciput

**Comment by helendallas** [comment]
This has been resolved by the email option added by Dimas.
