### ISSUE TITLE
Map and ocean go grey?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2146]
Map and ocean go grey and lose features (1) after searches and (2) when zoomed out?

<img width="1439" alt="Screenshot 2020-06-01 at 13 04 40" src="https://user-images.githubusercontent.com/44292029/83403276-a7323300-a408-11ea-8356-1369c1411ae7.png">

**Comment by timlinux** [comment]
@jeremyshelton That reflects how the cartography was set up. @NyakudyaA can you try to mask out the sea pixels from the DEM?

@jeremyshelton can we hold this off till next week - I don't think it is too urgent?

**Comment by jeremyshelton** [comment]
@timlinux @NyakudyaA OK - agreed, not urgent - happy to hold this off for a week. It does look quite odd.

**Comment by jeremyshelton** [comment]
@timlinux the map takes on that weird grey appearance each Tim a filter is applied to the data, which definitely looks odd/wrong?

**Comment by NyakudyaA** [comment]
> @timlinux the map takes on that weird grey appearance each Tim a filter is applied to the data, which definitely looks odd/wrong?

![map-dis](https://user-images.githubusercontent.com/2510900/83502394-c9d45280-a4c1-11ea-901c-373aaeec686b.png)

You want it to be like this @jeremyshelton

**Comment by jeremyshelton** [comment]
@NyakudyaA yes, I think that is correct. Basically the map should keep the same appearance, even when zoomed out a bit. Do you agree? @timlinux
