### ISSUE TITLE
Remove farm portion from locate options (again)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2147]
This issue was fixed in testing, but is now back. 
<img width="353" alt="Screenshot 2020-06-01 at 14 39 32" src="https://user-images.githubusercontent.com/44292029/83412959-4cee9d80-a41b-11ea-9004-69147646ac10.png">

**Comment by timlinux** [comment]
Are you sure this was removed? I remember discussing this and agreeing to leave it there even though it was not directly useful to you (it is part of the base FBIS platform).

**Comment by timlinux** [comment]
Also it is still present on testing.

**Comment by jeremyshelton** [comment]
@timlinux OK all good. It seems a bit out of place, but happy to keep it. I must have forgotten that we decided that....
@helendallas @dimasciput
