### ISSUE TITLE
Change 'All endemic' to 'All native' (again) 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2149]
Change 'All endemic' to 'All native' in Origin and endemism tab. This issue was fixed in staging but is now back??

<img width="335" alt="Screenshot 2020-06-01 at 15 31 01" src="https://user-images.githubusercontent.com/44292029/83414408-c38c9a80-a41d-11ea-9805-f977d97ba0f3.png">

**Comment by helendallas** [comment]
fixed
