### ISSUE TITLE
Correct the latitude description in Locate Options

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#2150]
Latitude should be "negative degrees South" not "positive degrees North"

![InkedLocate error_LI](https://user-images.githubusercontent.com/55532903/83522651-462a5e00-a4e1-11ea-8969-6e308c748df5.jpg)

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
Fixed in testing

**Comment by helendallas** [comment]
@dimasciput needs to be Latitude should be "negative degrees South" not "negative degrees North"

![image](https://user-images.githubusercontent.com/45286876/95727749-e7d56f00-0c7a-11eb-9002-faac7965af00.png)
