### ISSUE TITLE
River Names

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2151]
Geocontext is using NGI 50k rivers to get the river name that is closest to a point. In this case at that particular point you mention it is actually nearest to the river with that name.
![image](https://user-images.githubusercontent.com/45286876/83607185-12037b80-a57b-11ea-80c7-fede92b43434.png)

As depicted from the picture above NGI hasn't captured that river and the closest point to that one is the one with that name. The main reason we initially decided to get the rivers name from the NGI was because we thought it would cater for even the smaller tributaries which would have names as well and they would be spatially accurate at that scale.

I guess the discussion should now concentrate on which river data-set to use to get the names bearing in mind the differences in accuracy at different scales.

**Comment by NyakudyaA** [comment]
I am going to import again the ngi rivers

![import-new-data](https://user-images.githubusercontent.com/2510900/83611599-7c1f1f00-a581-11ea-8e44-eb71ac4f7be2.png)

However, the names are still going to be an issue.
![ngi-names](https://user-images.githubusercontent.com/2510900/83612170-55adb380-a582-11ea-8a4a-1e5488e0fbd0.png)

As depicted above some of the rivers from NGI have funny names that I intentionally exclude from using.


Rivers from DWA without names
![names](https://user-images.githubusercontent.com/2510900/83612736-1764c400-a583-11ea-852c-01a20944bd57.png)

Maybe we should find out if we can update ngi river names with names from dwa

**Comment by timlinux** [comment]
[Data for tim.xlsx](https://github.com/kartoza/django-bims/files/4722345/Data.for.tim.xlsx)

Example points with issues from @helendallas

**Comment by NyakudyaA** [comment]
![rivers-dwa](https://user-images.githubusercontent.com/2510900/83622292-0ff7e780-a590-11ea-9e54-ac7e605b1b0d.png)

**Comment by timlinux** [comment]
Update from chat on 3 June 2020: We need to find an official dataset where the data are at 1:50 000 and have names. Currently the DWS data is 1:500k by the looks of things. @helendallas will compose an email to Nancy and stakeholders from DWS with Tim in CC. @timlinux to forward on to Aslam Parker (NGI) and FC Basson (Dept Agriculture) to see if they have any insights or access to better datasets.

Tim will also ask Seabilwe to do a simple overlay analysis with river intersections, scoring each river by the number of times it intersects with the DWS river, then assigning the DWS name to the NGI river with the most intersections.

**Comment by helendallas** [comment]
**Response from various individuals:**

**From Nancy Job - SANBI**
I think an option is to serve both NGI and DWS data sets for the time being.
 
We are aware of the issue and, for the long term, my team is already working on a cross-walk of the NBA 2018 information (which is applied to the DWS 1:500 000 rivers) across to the 1:50 000 NGI rivers data set. SANBI team have already completed a first draft for 2 full secondary catchments and now waiting for my review and next steps. 

**From Heidi van Deventer - CISR:**
The NGI 50k is not a hydrologically and topogically corrected layer

**From Thiru Chetty - DWS**
The Department of Water and Sanitation has a joint custodianship with the NGI with regard to the river data. The NGI is the custodian of the geometry and DWS is the custodian of the attributes. The DWS also was involved in a project to correct the 50k data for hydrological flow and topology as per primary drainage area.

We are not busy with aligning the attributes with the geometry at the moment.
 
However, we are busy with a river editing project. 
 
The tool was developed by the ARC. The river editing pre-processing is processing performed on raw river data (as from NGI) to prepare it for use in the river editing tool processing procedures. It is so that the river lines are in a format that will be more easily and effectively processed by the tool. 
 
The  river editing tool is mainly for processing rivers after they have been cleaned (pre-processed), Its main functionality is to: 
• Automatically applying flow direction of stream lines from a DEM. 
• Automatically applying flow direction from the mouth of a river network. 
• Finding loops in the river network. 
• Selecting upstream or downstream line segments from a specified position. 
• Assigning attributes to all selected stream lines 
• Calculating stream order of river segments in a river network. 
 
It is a long process and we are still busy with project.
You can send an email to Susette Martin to get the 50k river dataset. Her email address is martins@dws.gov.za.

**And Nancy Job - SANBI again:**
If I understand the goal it is for location accuracy and river names. Most especially for names.
So the questions for Susette Martin are a) are we right to assume location of this new dataset = 1:50 000 DWS and 1:50 000 river lines, which seems almost certainly should be the case and b) does this updated river lines dataset include river names.
Maybe b) is the only question. 
Or/and c) can you have permission to serve it on FBIS (it sounds like it is still in prep).

If b) answer is yes, it might be worth pursuing.
If b) answer is no – you might need to build two separate queries? Ie the query for names will have to use the 1:500 K rivers and you will have to say name of a river within 500 m of the query? Or Tim you probably have a much more sophisticated approach / answer.

@timlinux @NyakudyaA @jeremyshelton 
So the decision is where to from here?

**Comment by helendallas** [comment]
@timlinux Thanks for following up on this. My feeling is this also needs to be fixed before we send release email as wrong river names, and subsequently wrong FBIS Site Codes are being generated.
@jeremyshelton FYI

**Comment by helendallas** [comment]
Awaiting further information re licencing from DWS legal department.

**Comment by helendallas** [comment]
Closing ticket as dependent on SANBI and DWS. We have also implemented a work around whereby a user can add the Original River Name
