### ISSUE TITLE
Links at bottom home page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2156]
@timlinux @helendallas which of these links do you think are still useful?

@dimasciput the link to Document & Reports leads to the 'fbis closed for maintenance' window?

<img width="811" alt="Screenshot 2020-06-04 at 16 37 45" src="https://user-images.githubusercontent.com/44292029/83771195-53328300-a682-11ea-8500-d9046b69a78b.png">

**Comment by helendallas** [comment]
@jeremyshelton 
I think we ontl really need the Citation actually since this is not visible anywhere else. the others either dont work, are for admin or duplicated in top menu.

**Comment by helendallas** [comment]
**Please Remove** 
External Resources
Bibliography
GIS Catalogue

**Retain all others including:**
Documents & Reports  -  under construction - keep for FBIS Phase 2
