### ISSUE TITLE
Geomorphological zone not showing for fish single site dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2157]
@dimasciput Geomorphological zone not showing for fish single site dashboards

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=33479&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=&modules=1&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=&polygon=

<img width="419" alt="Screenshot 2020-06-05 at 18 38 58" src="https://user-images.githubusercontent.com/44292029/83902028-facfb400-a75b-11ea-98ba-c6257c527f1e.png">

**Comment by dimasciput** [comment]
@jeremyshelton fixed
