### ISSUE TITLE
Show a date for site photographs

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2158]
At the moment one cannot determine when a photograph was taken. This limits value of photographs for evaluating long term change.

Please can you include a date (day, month, year) on the photograph (or under the photograph)

**Comment by dimasciput** [comment]
@helendallas I'll do this on RBIS instead, I think it will valuable to them too. I will add a date for site images in site dashboard and sass dashboard.

**Comment by timlinux** [comment]
@dimasciput will test on testing then deploy to live.

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput The date shown is now the date of the first assessment, not the date of the assessment where the photo was added.

For example:
https://freshwaterbiodiversity.org/sass/view/11485/
![image](https://user-images.githubusercontent.com/45286876/140044464-6c2dcd3d-b585-47d5-a094-b3c8737dd89c.png)

Instead we have the first date 
![image](https://user-images.githubusercontent.com/45286876/140044256-6918ed0d-0818-4650-9a81-56ac14b9cecb.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Anything further on this? Is it possible to grab the data of the assessment to which the photo is attached and show this. @dimasciput ?

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput Looks good on testing. Please roll out to live when possible

**Comment by helendallas** [comment]
Thanks look good on live, closing ticket
