### ISSUE TITLE
Please check sort order of abiotic data in upload form -  pH

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2160]
pH is listed last in the list

Please ensure display order is alphabetical based on variable name
https://freshwaterbiodiversity.org/abiotic/?survey=12352&next=/source-reference-form/?session=cd21a829-15bd-475e-af00-05d88c429b5c&identifier=fish-form

![image](https://user-images.githubusercontent.com/45286876/84130913-298fa800-aa44-11ea-855b-94a327eda1bb.png)

**Comment by dimasciput** [comment]
@helendallas fixed in the testing
