### ISSUE TITLE
My sites and data from 2019 and 2018 have disappeared??

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2163]
@dimasciput @timlinux 
I created multiple sites (and entered fish data) in the Witrivier in 2018 and 2019, but these are no longer present on the FBIS?

This screenshot shows there that a search for records from Jeremy Shelton shows no records post 2015, which is incorrect. Are these perhaps data that got lost when collector/owner names were cleaned up recently?

<img width="679" alt="Screenshot 2020-06-11 at 12 30 12" src="https://user-images.githubusercontent.com/44292029/84375450-df432e00-abdf-11ea-827f-10092fef6b9b.png">

@Aneri16 @helendallas

**Comment by dimasciput** [comment]
@jeremyshelton I just checked, I think I removed all fish data including data manually entered by user. Are there a lot of data?

**Comment by jeremyshelton** [comment]
@dimasciput I think there might have been quite a bit of important data - is this easily retrievable?

**Comment by helendallas** [comment]
I think other non FRC users also added fish data. as well as SASS data

**Comment by dimasciput** [comment]
hi @helendallas this is only for fish.

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux I know that some of the SA fish experts like Darragh Woodford and others have spend quite a bit of time uploading fish records to FBIS. In my opinion it is important we do whatever we can to retrieve these records otherwise we risk losing user confidence & support. 
@helendallas what do you think?

**Comment by helendallas** [comment]
@dimasciput @timlinux @jeremyshelton 
I agree 100%. We have to retrieve all data captured directly onto FBIS. I am aware of a number of user who have added data.

**Comment by helendallas** [comment]
Data retrieved by Dimas - Checked by Jeremy
