### ISSUE TITLE
SASS data incorrect

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2165]
Something strange is going on with the SASS Scores.  see example below:

![image](https://user-images.githubusercontent.com/45286876/84393149-81bcda80-abfb-11ea-893b-6d14b21d7e21.png)

https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=

But in the drill down:
![image](https://user-images.githubusercontent.com/45286876/84393333-be88d180-abfb-11ea-8691-8998bd4df75d.png)

https://freshwaterbiodiversity.org/sass/view/2403/
 @dimasciput Please can you check if this is a bug and correct, thanks

**Comment by helendallas** [comment]
We had this issue once before

**Comment by dimasciput** [comment]
@helendallas will investigate this next week

**Comment by dimasciput** [comment]
@helendallas I think I know the problem, but may I deploy it early next week if you don't mind? The data itself is fine, it's the issue with how the data displayed on the dashboard.

**Comment by helendallas** [comment]
@dimasciput Thats fine thanks

**Comment by dimasciput** [comment]
@helendallas I fixed it, please check again

**Comment by helendallas** [comment]
@dimasciput Thanks is fine now. What was the cause? Is it something that may happen again?
