### ISSUE TITLE
We need to able to edit abiotic data - e.g. conductivity

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2166]
As an administrator I need to be able to edit abiotic data such as conductivity when it is incorrect.

I can access the SASS data, but then when I get to the abiotic data, there is none shown, even though it is there for the site.

https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=

See graph, where data is obvioisly incorrect.
![image](https://user-images.githubusercontent.com/45286876/84394472-46231000-abfd-11ea-9b3a-9e604ca89cff.png)

But when I go through to abiotic forms, there is no data shown for this site and sampling date

![image](https://user-images.githubusercontent.com/45286876/84394208-edec0e00-abfc-11ea-81f5-e44a295e2a29.png)

@dimasciput Is this feasible?

**Comment by dimasciput** [comment]
@helendallas 
I added search and filter function for Chemical Record in the admin page, only on testing. 
First you need the Site Code and the date of the chemical record collected, then follow these steps : 
- Go to chemical record admin page http://testing.healthyrivers.kartoza.com/admin/bims/chemicalrecord/
- Search the site code, in your case it's G2EERS-JONKE
![image](https://user-images.githubusercontent.com/1979569/95553231-5080d980-0a38-11eb-8005-6d688f9f0771.png)
- Click the search icon
- It will filter all the records for that particular site
- Now we want to filter by specific date, first click the year in this section
![image](https://user-images.githubusercontent.com/1979569/95553335-8de56700-0a38-11eb-98f9-11f7b0f1b58a.png)
- Do the same with month and date
- Finally you will get these records
![image](https://user-images.githubusercontent.com/1979569/95553423-c2f1b980-0a38-11eb-992a-ae727332fb53.png)
- We can also filter by chemical unit
![image](https://user-images.githubusercontent.com/1979569/95553512-ec124a00-0a38-11eb-9a8c-b4c4175e252a.png)

**Comment by helendallas** [comment]
Thanks
