### ISSUE TITLE
A user needs to be able to edit their site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2167]
I added a site as a regular user (hfdallas@gmail.com) to check is once a user added a site, it was possible to edit the site data.
 
This is the site I added:
![image](https://user-images.githubusercontent.com/45286876/84396545-aa929f00-abfe-11ea-9126-4303a8f8ccd7.png)

We had a ticket previously saying creators/owners of a site and creators/owners of data  -should enable them to edit the data, as well as data capturers.

I am able to edit the SASS data, just not the Site data

I am not sure why this is not working now?  Is it to do with the user settings?
@dimasciput  please can you check?

**Comment by dimasciput** [comment]
@helendallas yes currently only admin is able to edit the site, I will re-label this to feature-request and move to RBIS project instead.
