### ISSUE TITLE
We need a training session to administer Taxonomy on BIMS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2169]
I don't fully understand the process for editing / updating a taxon in the Bims/Taxa section
![image](https://user-images.githubusercontent.com/45286876/84492206-209e1100-aca6-11ea-82ef-8122a898ff26.png)

Please can you run a training session on this
@jeremyshelton @timlinux @dimasciput

**Comment by dimasciput** [comment]
@helendallas I can you show at next week meeting
