### ISSUE TITLE
Deleting a duplicate document

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2173]
I have found duplicate documents in the Documents admin section.
@Aneri16 FYI

![image](https://user-images.githubusercontent.com/45286876/84506980-6b2c8700-acc0-11ea-9c5f-4b1656f632c4.png)

How do I know which one is linked to the data? And which one is safe to delete. 
In this case the Metadata Table gives a URL, which doesnt have an active link.

![image](https://user-images.githubusercontent.com/45286876/84507383-058cca80-acc1-11ea-8898-f7bda6d13842.png)

**Comment by helendallas** [comment]
@Aneri16 @dimasciput There are actually a lot of duplicate documents, I am not sure why? Perhaps ingested more than once with each itteration of the data ingestion?

**Comment by Aneri16** [comment]
@helendallas hmm that is good point... which one to delete then?

**Comment by Aneri16** [comment]
@helendallas I've done a bit of digging - in the case you mentioned (thesis by Taylor GC) two different links for the thesis are given in the fish data spreadsheet: 
![image](https://user-images.githubusercontent.com/55532903/84634845-af06d280-aef2-11ea-948e-7a57f793783f.png)
Not sure why... maybe extracted on two different occasions for some reason, or by different people? The data is correct though (ie no duplicate data). Anyway so that duplication is due to an error in the spreadsheet. I am not sure why there is a third duplicate document though... maybe to do with name format? One document is G.C. Taylor while the other two are GC Taylor. Not sure

**Comment by helendallas** [comment]
@Aneri16 Thanks, All these data need to be linked with the same document, and then duplicates removed
@dimasciput How do we do this?

**Comment by helendallas** [comment]
@dimasciput Thanks for your offer to delete duplicates in the back end. And to make sure that any data remain linked to the correct document in the process.

**Comment by helendallas** [comment]
@dimasciput Here is one example of duplicated reports, two of which have records associated with it.

![image](https://user-images.githubusercontent.com/45286876/98694009-a61f0d80-2379-11eb-9662-9f900fdca1a6.png)

**Comment by helendallas** [comment]
Further checking showed that only the 14 records from the second report are returned, all 25 records from the third report are missing.

**Here is the link to the FBIS query:**
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22408%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Here is the csv data returned:**
[Taylor Fish data from FBIS.xlsx](https://github.com/kartoza/django-bims/files/5596000/Taylor.Fish.data.from.FBIS.xlsx)

**Comment by dimasciput** [comment]
@helendallas I merged the source references
![image](https://user-images.githubusercontent.com/1979569/101140461-95467c80-3645-11eb-8091-be7e77f481d3.png)

Should be good now for this case

**Comment by helendallas** [comment]
@dimasciput Thanks, but there are more - how can we check and fix for all?
![image](https://user-images.githubusercontent.com/45286876/101140998-5cde7880-361c-11eb-921e-078de4ec951d.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/101141215-a3cc6e00-361c-11eb-8723-40e44e687414.png)

**Comment by dimasciput** [comment]
@helendallas please give me all the duplicated documents, I will fix it from the backend for now.

**Comment by helendallas** [comment]
If you can add merge functionality here, I can manually go through and check
![image](https://user-images.githubusercontent.com/45286876/101141401-ebeb9080-361c-11eb-840a-473a5780f70c.png)

**Comment by helendallas** [comment]
I would also nee to be able to sort this alphabetically, which is not possible at the moment

**Comment by dimasciput** [comment]
@helendallas ok let me add it now

**Comment by dimasciput** [comment]
@helendallas ok I think it will take more time and effort than I thought, how about I give you all the source references in excel format, then you can just send me the duplicates. I'll fix it from the backend.

**Comment by helendallas** [comment]
@dimasciput Sure, that is fine. If you extract all source references, and send to me as an excel file, I can send back duplicate/triplicates.
Thanks

**Comment by helendallas** [comment]
@dimasciput I think the reason for the duplicates is sometimes that the author format is different.
I have generally selected the more recent one, which conforms to the format specified for ingesting occurrence data, although sometimes this does not include the thesis details.

In the attached file I have added two columns:

**Correct ID** - this is the ID of the correct Source Reference

**ID to merge** - these source references must be merged with the number provided.

- There are some where I have ? Not details? Not sure if they have records?
- One incorrect title - ID 549
- One wrong DOI - I have provided the correct Source reference for this to merge with


Excel file attached.

[FBIS Source References 2020_12_04.xlsx](https://github.com/kartoza/django-bims/files/5643456/FBIS.Source.References.2020_12_04.xlsx)

**Comment by helendallas** [comment]
@dimasciput Following still need to be changed: bold one is correct

### Databases
Correct  ID | ID to merge | ID | Title
 183 | 154 | Cape Nature State of Biodiversity Database, 2015
**183 |  183 | Cape Nature State of Biodiversity Database, 2019**

Blank database - delete
![image](https://user-images.githubusercontent.com/45286876/104413864-cdf84080-5577-11eb-8ff5-a84f77c2a894.png)

### Unpublished Data
There are several with no records - that should be deleted, e.g.
![image](https://user-images.githubusercontent.com/45286876/104413986-1b74ad80-5578-11eb-8e6c-d4e63ca1a964.png)

Also all the following should become **River EcoStatus Monitoring Programme**
**Correct one**
![image](https://user-images.githubusercontent.com/45286876/104414290-b2416a00-5578-11eb-8976-83e973cff265.png)

**Incorrect ones**
![image](https://user-images.githubusercontent.com/45286876/104414106-52e35a00-5578-11eb-972b-29a4e9349e38.png)
![image](https://user-images.githubusercontent.com/45286876/104414120-5d055880-5578-11eb-8e51-b4c364be6b4f.png)
![image](https://user-images.githubusercontent.com/45286876/104414146-68588400-5578-11eb-8724-f1fe28322761.png)
![image](https://user-images.githubusercontent.com/45286876/104414172-74dcdc80-5578-11eb-8abf-cbe136a54533.png)
![image](https://user-images.githubusercontent.com/45286876/104414191-7f977180-5578-11eb-9003-9f2c42a4687b.png)

**This raises a previous point on allowing drop downs in unpublished data so that users dont keep creating new ones that mean the same thing.**

**_There are many more. For now can you please just delete source references that have no records._**

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/104435956-e9b61380-5584-11eb-9796-436f0c56af7d.png)

As discussed in our call today, we should formalise the unpublish data source list, making the user first try to pick from an existing source and if they dont find what they are looking for, let them 'Add new' to create a new unpublished data source.

**Comment by dimasciput** [comment]
@helendallas now user can choose from most used unpublished data
![Peek 2021-02-23 17-17](https://user-images.githubusercontent.com/1979569/108829718-184ef180-75fb-11eb-8cb0-d975a384acd4.gif)

**Comment by helendallas** [comment]
@dimasciput Thanks. How do we consolidate existing entries.

River Ecostatus Monitoring Programme is correct, but others including **REMP Monitoring**, **REMP**,  and **Monitoring** should all become **River Ecostatus Monitoring Programme** 

![image](https://user-images.githubusercontent.com/45286876/109131537-91fdf100-775b-11eb-8206-403241763296.png)

Similar cleanup needed for Databse category
![image](https://user-images.githubusercontent.com/45286876/109132039-1486b080-775c-11eb-9312-f610f9976228.png)


I did send details a while back for this. Let me know if I need to create separate tickets. Utimately, it would be good to for admin to be able to do this.

**Comment by dimasciput** [comment]
Hi @helendallas my plan is to add that feature in edit reference page so admins can do it themselves, maybe we can close this ticket.

**Comment by helendallas** [comment]
@dimasciput Happy to close ticket if this functionality is already on your horizon, thanks
