### ISSUE TITLE
Exclude unpublished data from Filter= Study Reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2174]
At the moment, unpublished data is included in the filter : Study Reference

![image](https://user-images.githubusercontent.com/45286876/84512069-bbf3ae00-acc7-11ea-919c-cb236655a217.png)

Please can you exclude this as since it is unpublished, it should not have a study reference
@jeremyshelton Do you agree?

**Comment by dimasciput** [comment]
I re-labeled to feature-request since this is not a bug.

**Comment by helendallas** [comment]
Closing ticket as better solution is to include dropdown for unpublished data, see ticket #2197
