### ISSUE TITLE
SASS dates not matching data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2177]
Dates on SASS dashboard
![image](https://user-images.githubusercontent.com/45286876/84634023-83371d00-aef1-11ea-8f7a-8bcb8b913381.png)

https://freshwaterbiodiversity.org/sass/dashboard/9793/?taxon=&search=G2EERS&siteId=9793&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=
not matching actual underlying SASS from dates and data
https://freshwaterbiodiversity.org/sass/view/1929/
![image](https://user-images.githubusercontent.com/45286876/84634143-b11c6180-aef1-11ea-9f00-0ab555ee59fe.png)

![image](https://user-images.githubusercontent.com/45286876/84634188-c2656e00-aef1-11ea-8c6b-03e6d054c0fe.png)

![image](https://user-images.githubusercontent.com/45286876/84634231-d14c2080-aef1-11ea-8c94-f4120d86c65b.png)

**Comment by dimasciput** [comment]
@helendallas I'll check it tomorrow morning

**Comment by dimasciput** [comment]
@helendallas fixed, please check again

**Comment by helendallas** [comment]
@dimasciput Thanks looks fine now
