### ISSUE TITLE
SASS Record Source Reference wrong

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2178]
@dimasciput 
The Source reference on the SASS record is not showing the correct citation, even though it is correct in documents and in the metadata table
![image](https://user-images.githubusercontent.com/45286876/84644750-dfa13900-aeff-11ea-8a8e-9e492e20ffb0.png)

https://freshwaterbiodiversity.org/sass/view/11538/

![image](https://user-images.githubusercontent.com/45286876/84644796-edef5500-aeff-11ea-97f3-807912e20f66.png)

https://freshwaterbiodiversity.org/sass/dashboard/27263/?taxon=&search=K3KLEI-00005&siteId=27263&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27263&orderBy=name&polygon=

Please canyou check why.

**Comment by dimasciput** [comment]
@helendallas fixed, please check again

**Comment by helendallas** [comment]
@dimasciput Thanks working now.
@Janette-Lumley Should be fixed , please confirm with a few other refs your captured.

**Comment by Janette-Lumley** [comment]
@helendallas Yes I have checked a few and they are all correct. Thanks.
