### ISSUE TITLE
RELEASE BLOCKERS FOR FBIS V3

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2182]
1. - [ ] Finalise manual & link manual and youtube tutorials to the site
2. - [ ] Bring back the 'lost' user-entered fish data
3. - [ ] Finalise map
4. - [ ] Fix SASS accreditation issues, see ticket #1826  -it would be great if this was resolved before release but I don’t know if feasible?
5. - [ ] Fix duplicate users etc
6. - [ ] Fix document and citation issues
7. - [ ] Fix taxa, where problematic

@dimasciput @timlinux @NyakudyaA @helendallas @Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas I'm currently working on the this ticket https://github.com/kartoza/django-bims/issues/2180, so I don't have time this week until mid next week to resolve any of this. 

> Fix duplicate users etc

Is this really problematic to users right now?

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux @NyakudyaA 
From my side **point 2 is essential** & point 3 preferable. 
@helendallas?

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput @timlinux @NyakudyaA 

As per separate email to Jeremy, exclude 4, 5, 6 and 7. These can be done after the release:  

1. - [ ] Finalise manual & link manual and youtube tutorials to the site - Helen and Jeremy
2. - [ ] Bring back the 'lost' user-entered fish data - Dimas
3. - [ ] Finalise map - Admire and Tim

@NyakudyaA @timlinux  - please get back to us on the time line for this - that will determine if we wait or not, ditto @dim for 2.

**Comment by helendallas** [comment]
@timlinux @NyakudyaA @jeremyshelton 
Another NB issue is the river name as per ticket #2151

**Comment by helendallas** [comment]
I think sorting point 3 **out** is important as in my web interface, Firefox,

![image](https://user-images.githubusercontent.com/45286876/85007414-cc8aa500-b15b-11ea-8885-fb03cfd3f29e.png)

**Comment by jeremyshelton** [comment]
@timlinux @NyakudyaA I've seen looking at the map on Cape Farm Mapper and that seems quite fast and user-friendly with rivers and dams turned on, and has most of the info needed. 
I'm sure you're both familiar with this, but if might be worth a fresh look & maybe getting in touch with them to see what layer(s) they used?
Maybe we need to simplify things a bit if we can't get the FBIS baseman to load?
Just some ideas...
