### ISSUE TITLE
Adding option to extract full list of SASS taxa showing recorded SASS taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2185]
Christa Thirion emailed me:
She extract SASS data as CSV to us in her ecostatus assessments. At the moment, only SASS taxa recorded are returned.
She uses this CSV data to populate an excel spreadsheet for MIRAI - ecostatus assessments.

She has asked if it is possible to include an option (perhaps a click box), where a user has the option to download the entire SASS taxon list (just as it is in the SASS form), and then to include the abundance ratings for the recorded SASS taxa from the assessment.

**Comment by dimasciput** [comment]
Please give it a test on testing.

**Comment by helendallas** [comment]
Thanks @dimasciput I am awaiting feedback from Christa re this. So on hold for now

**Comment by helendallas** [comment]
So @dimasciput After discussion with our department of water and sanitation about their requirements, this is what is needed and the workflow:

- The user will select a site or sites (possibly by applying filters)
- Then the user will click the SASS dashboard
- Then the user will select the following:
 **Download Site level SASS data for populating the River Ecostatus Monitoring MIRAI model**  with a Download as csv 
![image](https://user-images.githubusercontent.com/45286876/194532948-ea0bca36-07b9-4ed9-b288-f29445b09aa1.png)


( I suggest this is this is included as a button between "Download all data for this site" and the Metadata table -  but am happy for you to position it higher if it works better from your side) 


![image](https://user-images.githubusercontent.com/45286876/194524238-e2455137-fd06-4c1a-800b-03e76507a209.png)

- The user clicks this CSV download

What is returned is Site level SASS data (not biotope level), with each Site/Sampling Date in a separate column.  I have created a spreadsheet to show exactly what is needed.

 
[REMP Template for FBIS.xlsx](https://github.com/kartoza/django-bims/files/9733082/REMP.Template.for.FBIS.xlsx)

Please remove the Include all taxon button that is on the form now - it does not return the correct data.

![image](https://user-images.githubusercontent.com/45286876/194532684-58c5a756-1125-4d32-8644-096dd1efff85.png)

We need this completed beforeour end of October reporting period, s please prioritise, thanks

**Comment by dimasciput** [comment]
@helendallas ok, I'm working on it today

**Comment by helendallas** [comment]
@dimasciput Tried on live but nothing happens when I hit download as CSV
![image](https://user-images.githubusercontent.com/45286876/195793478-64328f52-87a0-4c71-834b-bf27b211efd1.png)

**Comment by helendallas** [comment]
Tested, but download request not provided.
I am not getting the email

https://github.com/kartoza/django-bims/issues/2185

Download link:
[https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=&thermalModule=&dst=](https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5b%5d&modules=&validated=&sourceCollection=%5b%22fbis%22,%22gbif%22,%22virtual_museum%22%5d&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=&thermalModule=&dst=)

It wasn’t a large and no progress is shown here
https://freshwaterbiodiversity.org/admin/bims/downloadrequest/729/change/

Please can you check if it is working.

**Comment by dimasciput** [comment]
@helendallas please give it another try on production or testing.

**Comment by helendallas** [comment]
Thanks @dimasciput Received email etc with data. Looks fine. 

Only please remove 
TRICHOPTERA   (CASE CADDIS 2 TYPES)

This is not a SASS 5 taxon and should be removed, I created a ticket for this ages ago.
https://github.com/kartoza/django-bims/issues/3233

**Comment by helendallas** [comment]
Thanks, working great now, closing ticket
