### ISSUE TITLE
Geocontext for edited site not updating

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2186]
Please can you check why SA Ecoregion 1 and 2 are not biing grabbed for this edited site where I edited the georef.

https://freshwaterbiodiversity.org/sass/dashboard/33261/?taxon=&search=B6BLYD-&siteId=33261&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33261&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/85011945-9270d180-b162-11ea-8ff4-0b91d89c8f40.png)

**Comment by dimasciput** [comment]
@helendallas can you view the dashboard again, the geocontext process might take some time to complete.

**Comment by helendallas** [comment]
@dimasciput Thanks it is sorted. Approximately how long does it take to bring down the geocontext later
