### ISSUE TITLE
SASS Summary CSV needs two extra columns

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2192]
Please can you also standardise as you have with other CSV that **Original Site Code** and **Original River Name** are also included.

**Comment by helendallas** [comment]
This is for both the single site and multi site SASS Summary CSV

**Comment by dimasciput** [comment]
Updated in live

**Comment by helendallas** [comment]
@dimasciput Thanks. Is is possible to reorder as follows:

FBIS Site Code | Original Site Code | River Name | Original River Name | Site Description | Geomorphological Zone | Refined Geomorphological Zone etc.

**Comment by helendallas** [comment]
Closing as more important issues to deal with
