### ISSUE TITLE
Fish data errors

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2195]
@dimasciput 

It looks like some serious problems have recently appeared in the fish data.

Everything was good when last I checked, but now all of a sudden there are the following problems:
1. Several taxa are duplicated (e.g. Amphilius natalensis Boulenger, 1917).
2. Some of these duplicates have incorrect origin and endemism (and perhaps also conservation status?) labels, and are thus inconsistent with the master list.
3. The list of fish taxa in FBIS does not match that in our master list.
4. I presume there are now also issues with the data (occurrences and abundances) as a result of issues 1-3

These are all issues that have only appeared recently. I wonder if these problems arose when you were working on bringing back the 'user-entered' fish data? 

We put in a big effort to get the list of taxa (and associated data accurate), so it is critical that we get the taxon list and data set correct (like it was before). 

@timlinux @helendallas @Aneri16

**Comment by dimasciput** [comment]
Hi Jeremy, 

I think this is because of the legacy data that I restored, should I remove them again?

**Comment by dimasciput** [comment]
Fixed
