### ISSUE TITLE
SASS  CSV download not going to email when large

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2196]
I am trying to download SASS Summary data for checking a large number of site. 

![image](https://user-images.githubusercontent.com/45286876/86437355-b1e03080-bd04-11ea-81cd-4bd188c9e4d0.png)

Please can you check why it does not do as per other csv files, and confirm that the data will be emailed when ready.

Same for 
![image](https://user-images.githubusercontent.com/45286876/86437458-e3f19280-bd04-11ea-819e-325172e80fcf.png)

I never got the data in the end

**Comment by dimasciput** [comment]
@helendallas this is not a bug, currently this feature only works for site dashboard.

**Comment by jeremyshelton** [comment]
@dimasciput csv files still coming to email spam folder

@timlinux @helendallas

**Comment by helendallas** [comment]
Please can you allow large amounts of SASS data to be downloaded as csv file which is then emailed to users as per the fish, invert and algal data. From ticket #2267

**Comment by dimasciput** [comment]
@helendallas unfortunately I can't do this today, I will make this task top priority for the next maintenance day.

**Comment by helendallas** [comment]
@dimasciput 
I tested this on FBIS testing. The **SASS Summary** email was received in inbox
![image](https://user-images.githubusercontent.com/45286876/97542326-39962d00-19cf-11eb-9af9-73294fcd8f57.png)

The **All SASS data** email went to spam folder
![image](https://user-images.githubusercontent.com/45286876/97542381-4fa3ed80-19cf-11eb-8feb-45a9288674e2.png)

Both also show processing even though email has been received.

**Comment by dimasciput** [comment]
@helendallas the testing will always go to spam folder, since it's not using correct email provider like production.

> Both also show processing even though email has been received.

Yes because there is no way to know the email has been received so I did this to avoid multiple downloads by users.

**Comment by helendallas** [comment]
@dimasciput Thanks, then it is all working greta thanks. Closing ticket.
