### ISSUE TITLE
There are duplicate sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2200]
This site occurs twice

https://freshwaterbiodiversity.org/map/#search/B6TREU-00011/taxon=&search=B6TREU-00011&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/86468776-6a739780-bd38-11ea-90df-121184d5af0f.png)

One has SASS data and one has fish data - although lots of details missing from fish site - details are different as well
![image](https://user-images.githubusercontent.com/45286876/86468947-b9b9c800-bd38-11ea-9d4a-a34a4fdf9ce8.png)

![image](https://user-images.githubusercontent.com/45286876/86468980-c76f4d80-bd38-11ea-9705-575396500606.png)

**Comment by helendallas** [comment]
These are definately two different sites that have been given the same FBIS Site Code - I suspect because of river naming issues. see screenshot below
![image](https://user-images.githubusercontent.com/45286876/90609310-24996280-e204-11ea-921a-61de81a7d208.png)

**Comment by helendallas** [comment]
@dimasciput What happened to the second site? Only one now, but they were definately two different sites

**Comment by dimasciput** [comment]
Fixed it
