### ISSUE TITLE
We need a 'back' button alongside the 'next' button at the bottom of each page of the add data work flow

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2202]
When a user adds data, they are asked for confirmation at each stage via the 
![image](https://user-images.githubusercontent.com/45286876/86472538-98a8a580-bd3f-11ea-8d6d-d6a3e31236a8.png)

@jeremyshelton requested including a "Back"button with the next button, so that a user can go back to the previous form if they need to.

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas This is a big feature, basically overhaul the entire form. Let's put this ticket for RBIS v2.

**Comment by jeremyshelton** [comment]
@dimasciput OK that makes sense 👍

**Comment by helendallas** [comment]
Lets close this ticket as not critical
