### ISSUE TITLE
Administrators need a way to merge sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2204]
Sometimes two sites need to be merged. Although the **lasso control** allows a user to do this on the fly, there are instances when it would be better to permanently merge sites.

So we need to be able to select two sites, then select which site should be the "Primary"Site ( i.e. the one that becomes the site going forward), and then the data from the "Secondary"Site, is attached to the primary site.

**Comment by dimasciput** [comment]
Hi @helendallas , I forgot about this ticket, I have deployed this to testing if you want to test it.
Here's the demo:

https://user-images.githubusercontent.com/1979569/122375061-184d7580-cf8d-11eb-93c8-05f8c08c444f.mp4

**Comment by helendallas** [comment]
@dimasciput Looking great, easy and clear. Thanks

Happy for you to deploy to live site.
