### ISSUE TITLE
Map Issues

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2207]
# Admire

Labels cut off:

![image](https://user-images.githubusercontent.com/178003/86902666-2dc3e980-c106-11ea-9a1b-7171984ce490.png)

Duplicate labels:

![image](https://user-images.githubusercontent.com/178003/86902773-50ee9900-c106-11ea-841b-d51013672a79.png)

![image](https://user-images.githubusercontent.com/178003/86905183-9c567680-c109-11ea-91d9-960e155c2175.png)

(please use the label distance vendor tag to fix this)

Place names z-order:

Label z-order so that labels are on top - render the place names layer separately from the base map

![image](https://user-images.githubusercontent.com/178003/86904206-43d2a980-c108-11ea-9c7e-f3f63562c1c5.png)

Coastline not 'tucked in':

![image](https://user-images.githubusercontent.com/178003/86903468-4a145600-c107-11ea-9b1d-6dbfabae13b8.png)

Blue tinge:

![image](https://user-images.githubusercontent.com/178003/86904091-18e85580-c108-11ea-86e6-75576a2d02fb.png)

Creeping zombie blue colour:

![image](https://user-images.githubusercontent.com/178003/86904971-58637180-c109-11ea-97de-ef0122443c65.png)

# Tim to look at:

Missing labels:

![image](https://user-images.githubusercontent.com/178003/86902935-8c896300-c106-11ea-9e6d-d2597a1c754f.png)

**Comment by NyakudyaA** [comment]
> # Admire
> 
> Labels cut off:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902666-2dc3e980-c106-11ea-9a1b-7171984ce490.png)

I am already using the option to show labels at the edge of the tiles

![tiles-cutoff](https://user-images.githubusercontent.com/2510900/86908494-e1cd7080-c116-11ea-97c8-571d1e7bf62a.png)

> 
> Duplicate labels:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902773-50ee9900-c106-11ea-841b-d51013672a79.png)
> 
> ![image](https://user-images.githubusercontent.com/178003/86905183-9c567680-c109-11ea-91d9-960e155c2175.png)
Those are two label positions. I will remove one of them


![orignial-distance](https://user-images.githubusercontent.com/2510900/86908787-60c2a900-c117-11ea-8efa-79d43fe03657.png)
The original distance I had was 500 but now have made it twice as much

> 
> (please use the label distance vendor tag to fix this)
> 
> Place names z-order:
> 
> Label z-order so that labels are on top - render the place names layer separately from the base map
> 
> ![image](https://user-images.githubusercontent.com/178003/86904206-43d2a980-c108-11ea-9c7e-f3f63562c1c5.png)
> 
> Coastline not 'tucked in':
> 
> ![image](https://user-images.githubusercontent.com/178003/86903468-4a145600-c107-11ea-9b1d-6dbfabae13b8.png)
> 
> Blue tinge:
> 
> ![image](https://user-images.githubusercontent.com/178003/86904091-18e85580-c108-11ea-86e6-75576a2d02fb.png)
> 
> Creeping zombie blue colour:
> 
> ![image](https://user-images.githubusercontent.com/178003/86904971-58637180-c109-11ea-97de-ef0122443c65.png)
> # Tim to look at:
> 
> Missing labels:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902935-8c896300-c106-11ea-9e6d-d2597a1c754f.png)



> # Admire
> 
> Labels cut off:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902666-2dc3e980-c106-11ea-9a1b-7171984ce490.png)
> 
> Duplicate labels:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902773-50ee9900-c106-11ea-841b-d51013672a79.png)
> 
> ![image](https://user-images.githubusercontent.com/178003/86905183-9c567680-c109-11ea-91d9-960e155c2175.png)
> 
> (please use the label distance vendor tag to fix this)
> 
> Place names z-order:
> 
> Label z-order so that labels are on top - render the place names layer separately from the base map

@dimasciput you can already add this layer `fbis:cities_and_towns_fbis`
> 
> ![image](https://user-images.githubusercontent.com/178003/86904206-43d2a980-c108-11ea-9c7e-f3f63562c1c5.png)
> 
> Coastline not 'tucked in':
> 
> ![image](https://user-images.githubusercontent.com/178003/86903468-4a145600-c107-11ea-9b1d-6dbfabae13b8.png)

I do not see this anymore. I think this is jus ta rendering effect when you navigate to that place.

> 
> Blue tinge:
> 
> ![image](https://user-images.githubusercontent.com/178003/86904091-18e85580-c108-11ea-86e6-75576a2d02fb.png)
> 
> Creeping zombie blue colour:
> 
> ![image](https://user-images.githubusercontent.com/178003/86904971-58637180-c109-11ea-97de-ef0122443c65.png)
> # Tim to look at:
> 
> Missing labels:
> 
> ![image](https://user-images.githubusercontent.com/178003/86902935-8c896300-c106-11ea-9e6d-d2597a1c754f.png)

I only labeled the major rivers. If you need all rivers to have at least a label it can be also done. But beyond level 7 the natural labels will kick in depending on how they will fit on the line

**Comment by timlinux** [comment]
@dimasciput or @NyakudyaA can you please not show the orthophotos until we are at the correct level.

**Comment by NyakudyaA** [comment]
> @dimasciput or @NyakudyaA can you please not show the orthophotos until we are at the correct level.

@dimasciput can you set the orthophoto to render with `minZoom: 13`

**Comment by timlinux** [comment]
Also do we still have the NGI orthosheets that we render ourselves available? Can you add it as an option for the base map?

**Comment by timlinux** [comment]
Closing as stale, we can reopen when we want to spend time on the map again.
