### ISSUE TITLE
Getting the map ready for release

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2211]
So @NyakudyaA and @dimasciput 

We are still not happy with the map used on the landing page.

We still need to sort out the issues in #2207 over the longer term but for now we would like to do this:

![image](https://user-images.githubusercontent.com/178003/87308703-8256d280-c513-11ea-9771-5babc413a40f.png)

- [x] @dimasciput Go back to making the bing map baselayer on by default
- [x] @dimasciput Turn the rivers on by default
- [x] @NyakudyaA Make the river lines thicker through all zoom levels so they stand out well against the bing imagery
- [x] @NyakudyaA Make the river lines a lighter blue so they pop out from the map more
- [x] @dimasciput set the zoom so that you cant zoom past the maximum tile resolution of bing

The current basemap can you keep it as an option in the base map selector.

Thanks

CC @helendallas @jeremyshelton

**Comment by dimasciput** [comment]
- [x] @dimasciput Go back to making the bing map baselayer on by default
- [x] @dimasciput Turn the rivers on by default
- [x] @dimasciput set the zoom so that you cant zoom past the maximum tile resolution of bing

I'm done from my end.
@jeremyshelton @helendallas

**Comment by jeremyshelton** [comment]
Great. Thanks @dimasciput - looking good
@NyakudyaA let us know when you are done 👍

**Comment by NyakudyaA** [comment]
I have made the changes @jeremyshelton

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA 
Rivers looking good. 
Is it possible to get the clearer labels instead? (I see Tim put this in the ticket, but not as an item in the check boxes...)
<img width="803" alt="Screenshot 2020-07-14 at 10 03 34" src="https://user-images.githubusercontent.com/44292029/87400685-6ad22500-c5b9-11ea-87e4-9b39ccbd5f7e.png">

**Comment by jeremyshelton** [comment]
@NyakudyaA we are planning to release FBIS v3 today - so please let us know when the river labels are ready. All we need is for the current labels to be more visible & readable. Thank you

**Comment by NyakudyaA** [comment]
> @NyakudyaA we are planning to release FBIS v3 today - so please let us know when the river labels are ready. All we need is for the current labels to be more visible & readable. Thank you

Done @jeremyshelton

**Comment by jeremyshelton** [comment]
Thanks @NyakudyaA  👍
