### ISSUE TITLE
1:50 000 rivers are sometimes joined together across catchment boundaries

### ISSUE THREAD

**Issue by FBIS-issues** [kartoza/django-bims#2221]
An example is the bokramspruit, which flows westwards from red hill towards ocean view and kommetjie. somewhere around -34.1715, 18.3807 the river arc is joined to the upper reaches of the elsies or else river upstream of kleinplaas dam. there were several such instances that we corrected at the sources of rivers in the 1:500 000 data, but this is the only one that i have noticed so far in the 1:50 000 rivers.

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/526">User information </a>
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/
Screen resolution: 1920 x 1080
Browser: Chrome

**Comment by helendallas** [comment]
Closing this ticket as it cannot be resolved with the current rivers layers issues
