### ISSUE TITLE
Combine source reference pages

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2231]
## Problem

Currently we have separate pages for different type of source references : 
- published report and thesis in /document/
- peer reviewed article in /bibliography/ 

And some references don't even have pages, this makes the process of finding and editing references very difficult.

## Solution

Create one page to show all references of different types.

**Comment by timlinux** [comment]
This is what we have to date:

![image](https://user-images.githubusercontent.com/178003/98093813-570c4080-1e80-11eb-8819-0e0936e82b86.png)


The final part of uploading / editing both citations and documents is somewhat more complex and we would like to keep that on the back burner for now if possible.
