### ISSUE TITLE
Fish CSV error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2244]
Hi Dimas,
We have picked up an error in the fish CSV download files: for all taxa within the genus Enteromius the full taxon name appears in the 'species' column, but e.g. this column should have 'anoplus', not 'Enteromius anoplus'. Also, for taxa within this genus, the columns for Kingdom, Phylum.....etc are blank?

<img width="724" alt="Screenshot 2020-08-26 at 06 34 00" src="https://user-images.githubusercontent.com/44292029/91256654-303adb00-e768-11ea-8d85-bb6f29c0cc65.png">

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton not sure why, but somehow 'Enteromius' got removed from the system. I have re-added it manually, please check it again.

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton still an issue with in csv mulsisite fish export

Species | Taxon
-- | --
Lacustricola myaposae | Lacustricola myaposae
Lacustricola katangae | Lacustricola katangae
Lacustricola katangae | Lacustricola katangae
Lacustricola katangae | Lacustricola katangae

**Comment by helendallas** [comment]
Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon
-- | -- | -- | -- | -- | -- | -- | --
- | - | - | - | - | - | Lacustricola myaposae | Lacustricola myaposae
- | - | - | - | - | - | Lacustricola katangae | Lacustricola katangae
- | - | - | - | - | - | Lacustricola katangae | Lacustricola katangae
- | - | - | - | - | - | Lacustricola katangae | Lacustricola katangae

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
@dimasciput Still as above


Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon
Animalia | Chordata | Actinopterygii | Cyprinodontiformes | Poeciliidae | - | Lacustricola katangae | Lacustricola katangae
Animalia | Chordata | Actinopterygii | Cyprinodontiformes | Poeciliidae | - | Lacustricola katangae | Lacustricola katangae
Animalia | Chordata | Actinopterygii | Cyprinodontiformes | Poeciliidae | - | Lacustricola katangae | Lacustricola katangae
Animalia | Chordata | Actinopterygii | Cyprinodontiformes | Poeciliidae | - | Lacustricola myaposae | Lacustricola myaposae

**Comment by dimasciput** [comment]
@helendallas sorry... missing genus, should be ok now.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I downloaded the full fish data CSV and found a few more issues:

1. Missing provinces
<img width="218" alt="province" src="https://user-images.githubusercontent.com/44292029/92077240-4bd36080-edbc-11ea-8bcb-caa637bc1fe8.png">


2. Missing geomorphological zones
<img width="468" alt="geomorph zone" src="https://user-images.githubusercontent.com/44292029/92077248-4ece5100-edbc-11ea-93d7-608c22374a2d.png">


3. Some weird row formatting
<img width="1033" alt="row spacing" src="https://user-images.githubusercontent.com/44292029/92077255-5261d800-edbc-11ea-8c6a-62f9ae081b70.png">


...please have a look and let's see if we can find out where the errors crept in?

**Comment by dimasciput** [comment]
@jeremyshelton the province and geo zone might be resolved with re-fetching the geocontext data, I'll do that later.

The row formatting issue might be just because of your app (excel?), since csv doesn't provide any layout formatting. It's basically just text and comma.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput  - lets see if re-fetching the geocontext data fixes the province and geozone 👍

**Comment by jeremyshelton** [comment]
@dimasciput any updates on these missing fields in csv downloads yet?

**Comment by dimasciput** [comment]
@jeremyshelton can you check again?

**Comment by jeremyshelton** [comment]
OK looking good now 👍
