### ISSUE TITLE
CSV email notification

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2255]
@dimasciput can we set up the csv emails to come from fbis@frcsa.org.za instead of your email address?

<img width="977" alt="Screenshot 2020-09-03 at 06 46 13" src="https://user-images.githubusercontent.com/44292029/92072359-605e2b80-edb1-11ea-9deb-39325e97b1d8.png">

@Aneri16 can you please share the login details with Dimas?

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton @Aneri16 please share the details via email since github is public. Also I need to know what email provider you using? Is it gmail or not?

**Comment by jeremyshelton** [comment]
@dimasciput it is a webmail account: https://webmail.konsoleh.co.za/login
@Aneri16 please email Dimas the login details.

**Comment by jeremyshelton** [comment]
@helendallas OK that's fine. 
My message that you deleted just had a link to the email login page, no login details...
