### ISSUE TITLE
Taxon management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2268]
Please add ability to sort taxa, and if possible include higher taxonomic groups so one can filter, hierarchically.

Question re Bird data in https://rbis.kartoza.com/taxa-management/

There are only 479 Avian taxa - but 599 in Avian module, revised now in staging, see ticket #2283 
![image](https://user-images.githubusercontent.com/45286876/92923245-6b5f2e80-f437-11ea-8c7d-aeb2ec2e39fe.png)

**Comment by timlinux** [comment]
Looking this morning:

![image](https://user-images.githubusercontent.com/178003/94787209-eaf27480-03c9-11eb-9b9c-cad6ea77e90a.png)

**Comment by helendallas** [comment]
@dimasciput I am closing this as with the exception of the hierarchical filtering it is sorted.  It is possible to filter in the backend, so closing for now.
