### ISSUE TITLE
Please zoom in more to sites on map

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2270]
please can you zoom in more to the sites once a filter has been applied. see this shot below. It is sometimes hard to see where the sites are:
![image](https://user-images.githubusercontent.com/45286876/93056192-61724100-f66c-11ea-86a9-c34414aa42f1.png)

Should rather be at this scale
![image](https://user-images.githubusercontent.com/45286876/93056475-bf9f2400-f66c-11ea-869e-546c9ea4de01.png)

**Comment by dimasciput** [comment]
@helendallas
It's because there is a site in here 
![image](https://user-images.githubusercontent.com/1979569/95542954-6e8f0f80-0a21-11eb-9744-3bbb0346fc3d.png)

**Comment by helendallas** [comment]
Interesting, site incorrectly associated with this report. I have unlinked it.
