### ISSUE TITLE
Testing site New functionality - Explore Source References:  

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2273]
I checked metadata table for 

Here is my link to make things easier to figure out.

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

On testing site, metadata table returns error for these references - it is for old legacy refs as well as some new ones
![image](https://user-images.githubusercontent.com/45286876/93079592-a9a15b80-f68c-11ea-93aa-103c5676579d.png)

404 Not Found
nginx/1.17.10
It is in the source reference but not clickable
![image](https://user-images.githubusercontent.com/45286876/93079430-65ae5680-f68c-11ea-982a-42739e0493db.png)

On live site:
It is available and I could download the report from the metadata table
![image](https://user-images.githubusercontent.com/45286876/93079436-69da7400-f68c-11ea-8b80-ea24c97108e2.png)

This one takes you to the map
![Uploading image.png…]()

Unpublished data should not have option to download
![image](https://user-images.githubusercontent.com/45286876/93079891-22a0b300-f68d-11ea-8ddb-c7ccf78d6e82.png)

**Comment by helendallas** [comment]
Theses seem to be working, some DOIs but not all, and report downloads, not working, so documents.
Other examples where link is not working:
https://testing.healthyrivers.kartoza.com/map/10.1080/00359190909519248
https://testing.healthyrivers.kartoza.com/map/10.1897/04-222r.1
https://testing.healthyrivers.kartoza.com/map/10.1016/j.jtherbio.2011.06.001
https://testing.healthyrivers.kartoza.com/uploaded/documents/Ewart-Smith_J._2017._Nema_section_24_G_rectification_application_for_a_weir_and_pipeline_on_farm_781_Botrivier_rIexuPo.pdf
https://testing.healthyrivers.kartoza.com/uploaded/documents/Ewart-Smith_J._2018._Assessment_of_the_Groot_River_Meiringspoort_following_diesel_contamination._2nd_Monitoring_Report.pdf
https://testing.healthyrivers.kartoza.com/uploaded/documents/Document_Not_available_xKFV09K.pdf

**Comment by dimasciput** [comment]
@helendallas please don't test it on testing site, the files does not exist there.

**Comment by helendallas** [comment]
@dimasciput So sorry, my bad, I used the link in the ticket and didnt realise it went to testing. I have rechecked on production and its all working. Clsing ticket
