### ISSUE TITLE
Taxonomic integrity of legacy Biobase data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2274]
I was doing some checks on the biobase data change from number to percentage and picked up another issue:
 
Biobase legacy data for the following study, site and date:
Author and year: Coetzer A., 1982
Site: OL03A
Sampling date: 1978-1979.12-02 (given as 1/1/1978 in FBIS)
Taxon: Hydrobaeninae (REF36)   10.38
This is missing completely from FBIS. 
 
This taxon is now considered a SubFamily Orthocladiinae. How do we check these and deal with them?

Other examples:
Author | Year | RiverName | Reach | SiteCode
Coetzer A. | 1978 | BERG | Transitional | BRG11

Chironomini
Nematoda
Orthocladiinae
Tanypodinae
Tanytarsini

**Comment by dimasciput** [comment]
Fixed from backend, the data are still there but the taxon was incorrect.
https://freshwaterbiodiversity.org/map/#search/Orthocladiinae/taxon=&search=Orthocladiinae&siteId=&collector=&category=&yearFrom=1977&yearTo=1979&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by helendallas** [comment]
@dimasciput 
The taxa appear in the filter, but not in the list or the csv file. See e.g. Tanypodinae

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22145%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=
![image](https://user-images.githubusercontent.com/45286876/95551395-01707f80-0a0b-11eb-9444-64eed7a92f45.png)


![image](https://user-images.githubusercontent.com/45286876/95551366-f3226380-0a0a-11eb-870b-63fc12598c8f.png)

[Coetzer 1978 Berg Missing taxa.xlsx](https://github.com/kartoza/django-bims/files/5352997/Coetzer.1978.Berg.Missing.taxa.xlsx)

**Comment by dimasciput** [comment]
@helendallas please try again

**Comment by helendallas** [comment]
Thanks, working fine now
