### ISSUE TITLE
Base maps not all showing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2276]
We noted a month or two ago that not all base maps are working - these are still not working.

Please can you check and fix

@tim @dimasciput Any ideas what is happening?
We have a demonstration of FBIS tomorrow for AWARD.

**Comment by dimasciput** [comment]
@helendallas checking it now

**Comment by dimasciput** [comment]
@helendallas unfortunately this will take longer than I expected, should I just hide the layers for now? Only two base layers not working.

**Comment by helendallas** [comment]
@dimasciput I think just leave as is, and @jeremyshelton can just leave out demonstration of others. @jeremyshelton  okay with you?

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput no problem 👍
