### ISSUE TITLE
Check and revise all base maps

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2277]
Please check and update base maps - and remove any that are not working

Also Re Terrain: The base map named terrain doesn't look anything like the terrain base map we had before...

Old one

![image](https://user-images.githubusercontent.com/45286876/93748799-1ff80d80-fbf9-11ea-91d4-ac46214dbd89.png)

New one:
![image](https://user-images.githubusercontent.com/45286876/93748923-50d84280-fbf9-11ea-908a-08f5f97f4237.png)

**Comment by dimasciput** [comment]
@helendallas we updated it to use the Kartoza base map terrain, the old one is not free that's why we changed it.

**Comment by helendallas** [comment]
@NyakudyaA , @timlinux 
Is it possible to include the Kartoza Base map that was being worked on- and which I requested be included as a base map option before we switched to satellite. The default should stay as is, but it would be good to include a terrain option.

**Comment by dimasciput** [comment]
@helendallas all the basemap layers should work in the testing, I removed the greyscale one because it's not free anymore.

**Comment by helendallas** [comment]
Thanks, looking good
