### ISSUE TITLE
Geomorphological zone - why only upper and lower

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2279]
In the demonstration today with award I noticed that the spatial filter - Geomorphological zone only has Upper and Lower - 

What happened to the original ones? and why have these been changed?
@dimasciput  @jeremyshelton 

![image](https://user-images.githubusercontent.com/45286876/93861843-76c91a00-fcc1-11ea-998a-4d61c45ffbb2.png)

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 
fixed in live 
![image](https://user-images.githubusercontent.com/1979569/95532623-1816d680-0a0b-11eb-9ced-834196ee12a7.png)
