### ISSUE TITLE
Taxon Overview dashboard - common name missing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2280]
The common name is missing in the overview dashboard

![image](https://user-images.githubusercontent.com/45286876/93863011-3f5b6d00-fcc3-11ea-8fa5-332741607878.png)

**Comment by helendallas** [comment]
Also - Correct number of records does not show if GBIF data has been clicked - should be 1231 records

https://freshwaterbiodiversity.org/map/#search/Clarias%20gariepinus/taxon=&search=Clarias%20gariepinus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=-total&polygon=
 

![image](https://user-images.githubusercontent.com/45286876/93863465-d0324880-fcc3-11ea-8685-9fea42b00026.png)

**Comment by dimasciput** [comment]
@helendallas 
> Also - Correct number of records does not show if GBIF data has been clicked - should be 1231 records

It is correct now ( on live )
![image](https://user-images.githubusercontent.com/1979569/95534547-55319780-0a10-11eb-95ea-27d87b66fe57.png)

> The common name is missing in the overview dashboard

Will update this on testing

**Comment by helendallas** [comment]
@dimasciput Name showing is the scientific name, not the common name.  These were provided in the Master list for fish, and will be for odonate in the future. Not all invertebrates or algae have common names for now. So the common name should be included when it has been provided in the master list. 

![image](https://user-images.githubusercontent.com/45286876/95727130-130b8e80-0c7a-11eb-94cb-7c3fa4098df8.png)


![image](https://user-images.githubusercontent.com/45286876/95727095-08e99000-0c7a-11eb-8364-5762a575840b.png)

![image](https://user-images.githubusercontent.com/45286876/95727256-36ced480-0c7a-11eb-8585-cc20a5df8094.png)

![image](https://user-images.githubusercontent.com/45286876/95727210-2b7ba900-0c7a-11eb-8df4-55cc691bf0ce.png)

**Comment by helendallas** [comment]
@dimasciput I noticed a strange one:

![image](https://user-images.githubusercontent.com/45286876/98643601-e8bff600-2337-11eb-9fd7-eb3fcd7f8da3.png)

https://freshwaterbiodiversity.org/map/#

![image](https://user-images.githubusercontent.com/45286876/98643740-1c028500-2338-11eb-9666-de8fcacef047.png)

The common names are all available in the Master list of Fish species that jeremy sent you @jeremyshelton

**Comment by helendallas** [comment]
Here is the latest master list :
[SA Master Species List for Fish_19 May 2020.xlsx](https://github.com/kartoza/django-bims/files/5515699/SA.Master.Species.List.for.Fish_19.May.2020.xlsx)

**Comment by dimasciput** [comment]
@helendallas I think the system picking up the vernacular names from gbif, for now can I just show first common name instead? I don't want to use a lot of my time tomorrow to reingest fish data.

**Comment by helendallas** [comment]
@dimas This is the same list as is already in FBIS production. You just need to point the Common Name to the name provided by us, not GBIF. GBIF is often wrong

**Comment by helendallas** [comment]
@dimasciput Please confirm if the Common Name shown in the FBIS, is derived from the Vernacular Name in the screenshot below. If it is, then we can check these behind the scenes @jerem or @Aneri16 

![image](https://user-images.githubusercontent.com/45286876/98685303-dc578f80-236f-11eb-95de-4e9de109d91c.png)

![image](https://user-images.githubusercontent.com/45286876/98685495-19bc1d00-2370-11eb-93e5-3c27ce795d02.png)

**Comment by jeremyshelton** [comment]
@Aneri16 can you check this - I will focus on #2052

**Comment by helendallas** [comment]
@jeremyshelton @Aneri16 This can wait until @dimasciput  checks it tomorrow and gets back to us as to where the Common Name is derived from. Then if it is from the admin Vernacular names, we cna fix it ourselves once his work day is finished. So no rush on this ticket. I just wanted to keep you both in the picture :)

**Comment by Aneri16** [comment]
@helendallas thanks, I've just brought myself up to speed on this ticket.

**Comment by helendallas** [comment]
@dimasciput Please confirm where the common name comes from and how we deal with names that are incorrect in GBIF. Ideally we want to grab names from the master list uploaded to FBIS.

**Comment by dimasciput** [comment]
@helendallas I have removed all common names that coming from gbif. Now it only shows common names from master list.

**Comment by Aneri16** [comment]
@dimasciput @helendallas looks like there are still a number of common names from the masterlist that are displayed as "Unknown" for example: Amphilius natalensis, Anguilla bengalensis etc. Some are also incorrect - for example Austroglanis sclateri common name should be "Rock catfish" not "Barnard's rock catfish". These names are all there in the masterlist.

**Comment by jeremyshelton** [comment]
> @helendallas I have removed all common names that coming from gbif. Now it only shows common names from master list.

@dimasciput @helendallas common names still not correct. They do not match the master list and several show 'unknown'

My understanding is that the plan was to use the names from our master list .csv only?

**Comment by jeremyshelton** [comment]
> @dimasciput @jeremyshelton The Fish master on FBIS production includes 163 species, while Jeremy's master list is only 134 species. I understand from Jeremy that this is still a work in progress, so can I suggest that we don't waste hours reingesting and fixing these now - -accepting that we have more species on FBIS than we should have. The common names are also not all correct.
> 
> For now @dimasciput - if it is not possible to grab the common name from the FBIS production list - which is the most accurate - then we will have to settle on common name from GBIF. Going forward though the common name we provide in the Master List needs to be shown. I actually thought this was how it worked Dimas. How complex will it be to change it?

@helendallas  I am seeing 134 fish taxa on live site, which is correct?

**Comment by dimasciput** [comment]
@jeremyshelton 

> @dimasciput @helendallas common names still not correct. They do not match the master list and several show 'unknown'

Can you give me an example which one is not correct?

**Comment by jeremyshelton** [comment]
@dimasciput 

Example:
On FBIS Austroglanis Sclateri has the incorrect common name **Barnards rock catfish**.
The correct common name (as per the fish master list) is **Rock catfish**

@helendallas @Aneri16

**Comment by dimasciput** [comment]
@jeremyshelton would it be fine if I added some kind of tool to let you update the common names easily?

**Comment by jeremyshelton** [comment]
@dimasciput 
Best would be if we can just use the common names from the fish master list spreadsheet - that way we will know that they are all correct. 
If that is not possible, then I guess we will need to check through all 121 taxa and do them manually via a tool...
@helendallas

**Comment by helendallas** [comment]
@jeremyshelton Most seem to be there, although a few show as Unknown - please can you check and update as per demonstration from Dimas.

**Comment by jeremyshelton** [comment]
@helendallas yes will do.

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput I manually updated/updated all of the common names a week or two back. 
Certain fish taxa do not have common names, hence 'unknowns', so we can close this ticked now.
