### ISSUE TITLE
We need to come up with a generic scheme for site naming 

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2287]

**Comment by timlinux** [comment]
We are proposing to use OSM Nominatum e.g.

https://nominatim.openstreetmap.org/reverse?lon=29.51857&lat=-1.70792

```xml
<reversegeocode timestamp="Thu, 01 Oct 20 08:20:44 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="lon=29.51857&lat=-1.70792">
<result place_id="178452867" osm_type="way" osm_id="402010354" lat="-1.70972661820111" lon="29.51967488224987" boundingbox="-1.7139941,-1.7045063,29.4977492,29.5506644">Rambura, Nyabihu, Western Province, Rwanda</result>
<addressparts>
<village>Rambura</village>
<county>Nyabihu</county>
<state>Western Province</state>
<country>Rwanda</country>
<country_code>rw</country_code>
</addressparts>
</reversegeocode>
```

**Comment by timlinux** [comment]
We could also use a QDS referencing scheme:

https://en.wikipedia.org/wiki/QDGC

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/94788874-1ece9980-03cc-11eb-9f61-4e6b06266234.png)

**Comment by timlinux** [comment]
Handing over to Maurince and RBIS team to approve the proposal:

L2Catchment-UniqueNumber

e.g.

NAKN_2-00001

**Comment by helendallas** [comment]
@dimasciput Please can you action this soonest

**Comment by helendallas** [comment]
@dimasciput 

Not all Site codes not correct: It looks like these sites are very close to country boundary
![image](https://user-images.githubusercontent.com/45286876/99640785-0b49c180-2a52-11eb-994f-1ae9a6a4ce0d.png)

Other site codes are fine:
![image](https://user-images.githubusercontent.com/45286876/99640936-3e8c5080-2a52-11eb-9803-6f03f57fbf5d.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/99651876-0fc0ab00-2a4f-11eb-931e-a5c37a15ba82.png)

**Comment by helendallas** [comment]
Here is the link to the sites outside Rwanda - amphibians
https://rbis.ur.ac.rw/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=8&validated=&sourceCollection=[%22RBIS%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[29.494119286537167,-1.4401695324158794],[29.4921612739563,-1.442598844861422],[29.493083953857422,-1.4446581275522732],[29.495041966438297,-1.4449530767432464],[29.49638307094574,-1.4405985502547054],[29.49550867080688,-1.439681524526037],[29.494119286537167,-1.4401695324158794]]

**Comment by timlinux** [comment]
We are going to close this out for now. The problem is unresolvable if we have no geocontext data over the points external to Rwanda.
