### ISSUE TITLE
We need to get the odonates ingested for end September

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2289]

**Comment by helendallas** [comment]
Completed, master list and occurrence data uploaded

![image](https://user-images.githubusercontent.com/45286876/95735044-9af69600-0c84-11eb-9df5-1243078db15e.png)


![image](https://user-images.githubusercontent.com/45286876/95735015-8e723d80-0c84-11eb-90f6-a33553b5db50.png)

**Comment by helendallas** [comment]
Data harvested from GBIF

![image](https://user-images.githubusercontent.com/45286876/95740647-355ad780-0c8d-11eb-93c9-99896f3a0ced.png)

### Stats: 

**RBIS: 92 sites, 94 taxa, 580 records**
![image](https://user-images.githubusercontent.com/45286876/95740854-87036200-0c8d-11eb-9ac6-c8cf7d236a69.png)

**GBIF: 71 sites, 28 taxa, 251 records**
![image](https://user-images.githubusercontent.com/45286876/95740930-a9957b00-0c8d-11eb-839e-93ce45cd932a.png)
