### ISSUE TITLE
We need to complete preparation of the Anuran data. Due for end September

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2291]

**Comment by mmindje** [comment]
@timlinux Yes, the Anuran data also is ready. The draft shall be sent to @helendallas today

**Comment by helendallas** [comment]
The amphibian master list of taxa and the occurrence data file have been uploaded to RBIS. One species was manually added (the error noted below) - as it would not upload as normal.

![image](https://user-images.githubusercontent.com/45286876/95740533-ff1d5800-0c8c-11eb-9a1d-690b0bef6a1c.png)

**Comment by helendallas** [comment]
Data harvested from GBIF

![image](https://user-images.githubusercontent.com/45286876/95741446-90d99500-0c8e-11eb-84a7-cc6eb2ba9076.png)

### Stats:

**RBIS: 731 sites, 23 taxa, 1366 records**

![image](https://user-images.githubusercontent.com/45286876/95741267-46581880-0c8e-11eb-8e9e-0898087ef656.png)


**GBIF: 42 sites, 22 taxa, 93 records**

![image](https://user-images.githubusercontent.com/45286876/95741385-76072080-0c8e-11eb-92c6-53436d9b7784.png)
