### ISSUE TITLE
Duplicate taxa uploaded

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2302]
Please check why duplicate taxa are being uploaded using the Upload Taxa functionality. Here is a csv download of the amphibian master list after importing data twice. Not all taxa were overwritten. The highlighted duplicates were not edited before uploading the file the second time.

[RBIS Amphibian Master CSV download showing duplicate records uploaded.xlsx](https://github.com/kartoza/django-bims/files/5316290/RBIS.Amphibian.Master.CSV.download.showing.duplicate.records.uploaded.xlsx)

Should be 51 taxa only, second upload created 5 duplicates, then there are an extra 3 taxa? not sure where from?
![image](https://user-images.githubusercontent.com/45286876/94894456-afb77a80-0489-11eb-9f0c-4b5947f206b5.png)

**Comment by helendallas** [comment]
See also #2283

**Comment by dimasciput** [comment]
@helendallas I think it's because they have different scientific name, did you update the master list before re-uploading the data? 
But yea, it should overwrite the existing data.

**Comment by helendallas** [comment]
@dimasciput 
No thats the thing the only thing I changed was to remove the GBIF link and make No for 

Sclerophrys   regularis

**Comment by helendallas** [comment]
Seems okay now, closing ticket
