### ISSUE TITLE
Fix text in csv export - all

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2303]
When unusual letters are exported in the csv files, they get corrupted. Here are some examples:

Hyperolius ocellatus Günther, 1858 - becomes **Hyperolius ocellatus GÃ¼nther, 1858**

Hyperolius viridiflavus Duméril & Bibron, 1841 -  becomes 
**Hyperolius viridiflavus DumÃ©ril & Bibron, 1841**

I suspect this is happening for all letters with special characters associated with them.

**Comment by dimasciput** [comment]
@helendallas I think this because when you export the excel to csv the encoding is not supported in the system. Can you follow these steps to export the excel to csv : https://stackoverflow.com/questions/4221176/excel-to-csv-with-utf8-encoding#:~:text=In%20Excel%2C%20choose%20%22CSV%20(,and%20save%20as%20that%20type.&text=Then%20choose%20%2D%3E%20Save%20As.,you%20lose%20all%20accents%20etc).

**Comment by dimasciput** [comment]
@helendallas please wait, let me find the easier way to do that from excel.

**Comment by dimasciput** [comment]
@helendallas I can't open excel in the Windows at the moment, but can you check if there is an option like this when you exporting to csv from excel : 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1979569/94896988-f2dd1200-04b8-11eb-937f-a4a8eac6b6e6.png">

**Comment by helendallas** [comment]
@dimasciput  Yes I have this option -  is this the csv format we should be saving files in before uploading?

![image](https://user-images.githubusercontent.com/45286876/94897695-73d3e380-0490-11eb-8339-1a30458f5d5e.png)

**Comment by dimasciput** [comment]
@helendallas yes please, it will solve this issue.

**Comment by helendallas** [comment]
@dimasciput Okay, I will do for all RBIS data that is uploaded, but not sure what we do with the FBIS data that is already ingested?

**Comment by dimasciput** [comment]
@helendallas the fbis on the live site? That's fine, I actually fixed the file manually for FBIS.

**Comment by dimasciput** [comment]
@helendallas would you like me to clear all data from staging?

**Comment by helendallas** [comment]
@dimasciput I suppose it would be good to do another test upload of all taxa before doing it on the live site for RBIS?  If yes, then please remove all data from RBIS staging and I will upload gaain, thanks

**Comment by dimasciput** [comment]
@helendallas ok I cleared the data from staging.

**Comment by helendallas** [comment]
@dimasciput Thanks, I will reingest the master lists and data files using the correct csv encoding as recommended.

**Comment by helendallas** [comment]
@dimasciput I created the new CSV files using the correct encoder but when I downloaded the csv there were still issues with special letters:

![image](https://user-images.githubusercontent.com/45286876/94910201-a8519a80-04a4-11eb-8636-58a9b249224d.png)


Lamprotornis   purpuroptera RÃ¼ppell, 1845

**Comment by timlinux** [comment]
@helendallas I agree this is an issue but I dont think it should block v1 release. I am moving it to v2 ok?

**Comment by helendallas** [comment]
ok

**Comment by helendallas** [comment]
I dont think this is solvable. Closing ticket
