### ISSUE TITLE
Lasso tool - close Lasso Control not working:

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2306]
Lasso tool - close Lasso Control not working:

![Screenshot 2020-10-06 at 12 13 22](https://user-images.githubusercontent.com/44292029/95188872-5de65b80-07cd-11eb-8b3b-b38d631e72b6.png)

**Comment by dimasciput** [comment]
@jeremyshelton fixed in testing

**Comment by jeremyshelton** [comment]
@dimasciput thanks. Looks good. That can be rolled out to live 👍
