### ISSUE TITLE
Background image: log out

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2307]
Background image for the log out screen should look the same as the log in screen. It the moment it is very zoomed in and doesn't look good. 

<img width="1440" alt="Screenshot 2020-10-07 at 07 21 34" src="https://user-images.githubusercontent.com/44292029/95290914-ac980200-086e-11eb-8e14-25ffe160f520.png">
![Uploading Screenshot 2020-10-07 at 07.26.19.png…]()

**Comment by dimasciput** [comment]
Fixed in testing @jeremyshelton

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput looks fine on testing. That can be rolled out to live.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton to roll out latest bims to live we might want to shut down the live site for a day, because the changes are quite big. And I also need to thoroughly test it. 
I think it's better to do it on my second maintenance day.

**Comment by jeremyshelton** [comment]
Makes sense @dimasciput , I am happy with that approach.
