### ISSUE TITLE
CSV downloads coming to email spam folder

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2312]
@dimasciput CSV download emails are still coming to email spam folder. Is there an easy way to get these to come into the inbox instead?

<img width="1058" alt="Screenshot 2020-10-09 at 10 35 39" src="https://user-images.githubusercontent.com/44292029/95561705-69c75d00-0a1b-11eb-932c-a9d50373b66d.png">

@helendallas @timlinux

**Comment by dimasciput** [comment]
@jeremyshelton I fixed it in live site

**Comment by jeremyshelton** [comment]
Great. Thanks @dimasciput
