### ISSUE TITLE
Too many fields in side panel

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2325]
@mumaurice and @mmindje 

Can you please refine the list of context items shown in the side panel and dashboard

![image](https://user-images.githubusercontent.com/178003/96102505-80aff880-0ece-11eb-90aa-5f57e430ee70.png)

These can be managed using the admin panel here:

https://geocontext.kartoza.com/admin/geocontext/contextserviceregistry/1460/change/

![image](https://user-images.githubusercontent.com/178003/96102739-c40a6700-0ece-11eb-8224-c349ec8a17e5.png)

https://geocontext.kartoza.com/admin/geocontext/contextserviceregistry

We can see all of the enabled panel and dashboard context items in the list view:

![image](https://user-images.githubusercontent.com/178003/96102837-e0a69f00-0ece-11eb-9ef0-a41a73cbbeae.png)

**Comment by mumaurice** [comment]
Hi @timlinux ,

Thank you bring this important aspect, up. Yesterday we had a meeting in the afternoon, and we agreed that only three geocontext layers (Catchment Level 1, Province and Rivers) will remain shown on the side panel. Obed has fixed that this morning and updates are visible on the system.

**Comment by helendallas** [comment]
These have been re-evaluated and fixed. Closing ticket
