### ISSUE TITLE
improve validation workflow

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#233]
- [x] add option for the validator to edit the record
- [x] add option for the validator to 'return' the record to the contributor with a comment or request
  - [x] notify the contributor...
  - [x] add the record back to the contributor's 'update' list
- [x] show the contributor's contact details (e.g. when hovering over the contributors username in the record in the validation page) since the validator might want to clear a question up quickly by phoning or messaging the contributor

**Comment by dimasciput** [comment]
This has been implemented in django-bims.

**Comment by gubuntu** [comment]
last item in OP not implemented
