### ISSUE TITLE
Cannot add new taxon not in GBIF in Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2333]
At the moment it is impossible to add a taxon if it is not in GBIF. We need this functionality as not all taxa are correct or on GBIF.

Workflow needs to be revised, so the full taxon hierarchy can be added for taxa no in GBIF

https://testing.healthyrivers.kartoza.com/taxa-management/

**Comment by timlinux** [comment]
As discussed today, minor tweaks needed:

- [ ] Add a combo to left of taxon input box allowing to select an existing Family (will be nice to have type ahead filter on that)
- [ ] Limit the rank list to only species or genus
- [ ] Make it clearer how to add a new family if the family does not exist

**Comment by helendallas** [comment]
@dimasciput Where can I test this? RBIS? FBIS? production? testing?

**Comment by dimasciput** [comment]
@helendallas RBIS and FBIS production

**Comment by helendallas** [comment]
@dim I dont see this in FBIS.  I addedd the taxon Test to Algae in Taxon Management, but it did not give option to add non GBIF Taxon

![image](https://user-images.githubusercontent.com/45286876/107619441-d9648780-6c5b-11eb-8370-819c7a66e866.png)

Please can you clarify process.
