### ISSUE TITLE
Freshwater ecoregions needs i information

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2334]
Please can you add the following abstract information to the :

![image](https://user-images.githubusercontent.com/45286876/96705407-89ed0980-1395-11eb-92b9-48215de61394.png)

The Freshwater Ecoregions Of the World (FEOW) provide a global biogeographic regionalization of the Earth's freshwater biodiversity. FEOW were published in 2008 by the The Nature Conservancy. TNC is the originator of this version of the FEOW. Ecoregion names, codes, and boundaries are identical to those in the published version by TNC and WWF, Inc.  Citation for the Ecoregions: Abell et al. 2008. Freshwater Ecoregions of the World: A New Map of Biogeographic Units for Freshwater Biodiversity Conservation. BioScience. Vol. 58 No. 5: 403-414. Link: https://www.feow.org/

**Comment by helendallas** [comment]
Better still - show us how and where we can edit the metadata ourselves.

**Comment by dimasciput** [comment]
Hi @NyakudyaA can you update the metadata text for this layer? Thanks

**Comment by NyakudyaA** [comment]
![fresh-eco](https://user-images.githubusercontent.com/2510900/106279913-db831b00-6245-11eb-91ad-747f938de8a6.png)

Done and working in production
