### ISSUE TITLE
FBIS Site code not working for all sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2335]
Please check why some codes are not being generated correctly. I think this is GBIF data.

![image](https://user-images.githubusercontent.com/45286876/96837910-697d8780-1447-11eb-8321-cf5427f9f76d.png)

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/98690425-98678900-2375-11eb-938c-d867f5b344fe.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=28441&polygon=

**Comment by helendallas** [comment]
Some GBIF data are in the sea, not sure how we can buffer these?

**Comment by dimasciput** [comment]
@helendallas this is because we couldn't retrieve any catchment data for these sites, I'm not sure how to solve this issue. Let's discuss it next week.

**Comment by helendallas** [comment]
@dimasciput do you know why the catchment data cant be retrieved as most of these sites are within the SA border.

**Comment by dimasciput** [comment]
@NyakudyaA do you know why I'm getting no data from this catchment https://geocontext.kartoza.com/api/v1/geocontext/value/group/31.767556/-28.963398/river_catchment_areas_group/

**Comment by NyakudyaA** [comment]
@dimasciput cc @timlinux This is a case of a political demarcation. The `river catchment group` layers do not have an extent that matches that of the SA provincial boundaries as demarcated by the municipal demarcation board.
![Irregular-border](https://user-images.githubusercontent.com/2510900/106279258-cd80ca80-6244-11eb-9637-5fd851ed8736.png)

As depicted by the image above the solid area is a provincial border while the red outline is the border for the river catchments. This result's in the point lying outside the river catchment and hence we cannot find anything.

@timlinux any idea of what could be an easy solution. We do not want to manually edit the boundary of the river layers

**Comment by helendallas** [comment]
@timlinux @dimasciput @NyakudyaA 

Please can we try and resolve this .

**Comment by helendallas** [comment]
I manually fixed the sites that were falling out of the borders. Not an ideal long term solution but at least now we don't have any strange site codes.
