### ISSUE TITLE
Adding Filter interactions

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2338]
Create functionality for filter interactions. E.g. Spatial Filter X Temporal Filter X Conservation Status X Ecological Category. This will allow the user to harness the full power of the system, allowing for full customisation when filtering for subsets of data.

And within different Spatial filters: One such request was Ecoregion Level 1 + Geomorphological zone.

There is clearly a need for this filter interaction.

Link to #1523

**Comment by jeremyshelton** [comment]
@helendallas @timlinux @dimasciput 

It seems that some interactions are already working, such as endemism x origin x province: https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=["indigenous"]&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["value,sa_provinces,Western%20Cape"]&reference=&endemic=["Micro-endemic%20level%201","Micro-endemic%20level%202","National%20Endemic","Regional%20endemic%20level%201","Regional%20endemic%20level%202"]&conservationStatus=["CR","EN"]&modules=1&validated=&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

...but, then if I add another spatial filter (like protected areas), then the province filter falls away: https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=["indigenous"]&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["value,sa_provinces,Western%20Cape","group,npa_layer"]&reference=&endemic=["Micro-endemic%20level%201","Micro-endemic%20level%202","National%20Endemic","Regional%20endemic%20level%201","Regional%20endemic%20level%202"]&conservationStatus=["CR","EN"]&modules=1&validated=&sourceCollection=["fbis","gbif"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=-total_survey&polygon=

**Comment by jeremyshelton** [comment]
Interestingly, it is not possible to query the interaction of a SASS ecological category and a spatial filter like province: https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=&orderBy=-total_survey&polygon=

**Comment by jeremyshelton** [comment]
@helendallas and @jeremyshelton need to check interactions work (that we need) and which don't (that we need)

**Comment by timlinux** [comment]
I think we can close this one since it is already back referenced from #1168
