### ISSUE TITLE
Suggesting some changes

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2340]
@dimasciput we have got some discussion on the naming of some features,
Look at the screenshot

is there a way **owner** can be changed to **Users** and also, the data collection dates, on the first page, we see collection dates in November 2020 yet we are in October, may be we can revise this in our meeting to have all the notes

![image](https://user-images.githubusercontent.com/64961274/97441534-81ff0d80-1931-11eb-9802-1b82925cf081.png)

**Comment by mmindje** [comment]
The new names @dimasciput and @timlinux can be straight after the site code/GBIF locality names and we add a column for updated names/RBIS names

**Comment by mmindje** [comment]
@dimasciput , so we agreed that owner would be rather GBIF than Dimas
Great!

**Comment by helendallas** [comment]
Resolved with ticket #2347
