### ISSUE TITLE
SASS Scores not correct in CSV Summary table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2341]
I noticed some very low SASS Scores in the CSV when testing #2196 . Then I checked on FBIS Live, and noted the following issues that needs urgent checking please.

Single Site Dashboard - SASS: https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=

Date: 15-02-2002
https://freshwaterbiodiversity.org/sass/view/6499/
![image](https://user-images.githubusercontent.com/45286876/97541586-0ef7a480-19ce-11eb-9964-3266ef024418.png)

But CSV Summary is incorrect for this date. 
![image](https://user-images.githubusercontent.com/45286876/97541861-86c5cf00-19ce-11eb-9629-2c5544d3edd8.png)

This is just one example to demonstrate the issue.

Sampling Date |Sass Score | Number Of Taxa | ASPT
15-02-2002    | 9              | 2                        | 4.5

[G2EERS-JONKE SASS Summary data.xlsx](https://github.com/kartoza/django-bims/files/5456908/G2EERS-JONKE.SASS.Summary.data.xlsx)

**Comment by helendallas** [comment]
@dimasciput Some are fixed, but not all. Here is an example: G2EERS-JONKE 22-10-2000

**Screen from SASS Records:**

![image](https://user-images.githubusercontent.com/45286876/98920261-8fdb9380-24d8-11eb-9831-f1faa8e7f827.png)

**Scores from Site form and csv:**
![image](https://user-images.githubusercontent.com/45286876/98920390-b7326080-24d8-11eb-9a27-8dfa0ad9289d.png)

It may be because data is SASS4 so the taxon TRICHOPTERA (CASE CADDIS 2 TYPES) is not in SASS5, but it needs to be added to the scores for SASS4.  As 132 + 15 = 147

Sensitivity weightings as follows:
TRICHOPTERA   (CASE CADDIS 1 TYPE) | **8**
TRICHOPTERA   (CASE CADDIS 2 TYPES) | **15**
TRICHOPTERA   (CASE CADDIS 3 TYPES) **20**

I am sure I checked this before and it was working fine?

**Comment by dimasciput** [comment]
@helendallas please check again

**Comment by helendallas** [comment]
@dimasciput Thanks, seems correct now

**Comment by helendallas** [comment]
@dimasciput I did some edits of y old SASS data, just adding biotope ratings, and changing the source reference, but then all the SASS totals changed. Here is the link to one:

https://freshwaterbiodiversity.org/sass/view/2388/

The TRICHOPTERA (CASE CADDIS 2 TYPES)  are missing again.

Please can you recheck what is going on wand why data are changing after editing even when I haven't changed SASS data.

**Comment by dimasciput** [comment]
@helendallas can you check again?

**Comment by jeremyshelton** [comment]
@helendallas I am not sure how to check this - so I'll leave it to you.
