### ISSUE TITLE
Dashboard data visualization

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2345]
@dimasciput , the data visualization on the landing page (Number of records, sites and visited sites) also could be made a quick summative figure for data by taxon group that just a single total number of records and sites / site visited.

Instead of 
![image](https://user-images.githubusercontent.com/64961274/97680051-c22fce80-1a9e-11eb-84d2-cfcc47f0f523.png)

we can have something similar for FBIS

![image](https://user-images.githubusercontent.com/64961274/97680121-dbd11600-1a9e-11eb-88d2-c5659c710ed5.png)

**Comment by timlinux** [comment]
So discussed with @dimasciput about this. He will add configuration options in the site settings panel so that you can have either of the above dashboards (or both) as desired. Same thing for the explore map button.

**Comment by DanielIgirimbabazi** [comment]
@mmindje , just tagging here for you to retrieve the lost tickets

**Comment by helendallas** [comment]
All done, closing ticket
![image](https://user-images.githubusercontent.com/45286876/99640489-9ecec280-2a51-11eb-8d5e-5d041c005d58.png)
