### ISSUE TITLE
We need a column to update locality names

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2346]
@dimasciput 

A column is needed just between the site code names and collection date just for the updated RBIS names (these are especially the data from GBIF whose names are older ones)

![image](https://user-images.githubusercontent.com/64961274/97681117-72520700-1aa0-11eb-998e-817e633a00e1.png)

**Comment by helendallas** [comment]
@mmindje We also need the new Site description to override the GBIF one on the dashboards and in the csv files.

![image](https://user-images.githubusercontent.com/45286876/97707018-4c882a80-1abf-11eb-95ae-9a62452adbd1.png)

**Comment by mmindje** [comment]
Yes that is correct.

**Comment by helendallas** [comment]
Functionality created whereby the locality details can be updated in the Site description via the Site Visit . Edit Site

![image](https://user-images.githubusercontent.com/45286876/99642863-ac397c00-2a54-11eb-9d76-26e4855c7fdc.png)
