### ISSUE TITLE
Changing some column names

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2347]
@dimasciput 

The owner title name can changed repository so that the end user gets to be clear about who has the data.
Also, where it is Dimas can be made as GBIF as a repository for all GBIF harvested data

![image](https://user-images.githubusercontent.com/64961274/97684027-484d1480-1aa1-11eb-9afb-848596f63fa3.png)

**Comment by helendallas** [comment]
I suggest the following revisions:

### Columns
Include:

- Site Code: This is the automatically generated Site Code
- Site description: This is the description uploaded in the Occurrence Data upload file for RBIS data, or the new site description generated by the RBIS team for GBIF data (see ticket #2346 )
- Source Collection: This is either GBIF or RBIS (not Dimas)
- Collector/Owner: This is blank for GBIF, and the name in the Collector/Owner in the Occurrence Data upload file. The column needs to be wide to accommodate multiple persons

### Filters
These look fine

**Comment by helendallas** [comment]
Checked, closing
