### ISSUE TITLE
fine-tune groups and group categories for validation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#235]
# problem

- validators are too broad (a whole group is assigned to the validator group category when they are not all validators)
- all records go to all validators instead of Class rcords going to Class-specific validators

# solution

ensure that Groups and Group categories (and the BIMS code that uses them) can be set up in a way that the following workflow happens:

This example is for fish but must work with any Class.

1. contributor uploads fish (Class Pisces) data, reviews and sends to validator
1. only fish validator(s) get notified and see the new fish records on their validation page (there might be fish validators in one or more groups - we might need several more groups and group catgories....)

**Comment by dimasciput** [comment]
We can do this but this will need to be done in admin page, assigning permission for groups. 

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/1979569/45079980-0375ff00-b11e-11e8-8461-fde52b87d5c3.png">

**Comment by gubuntu** [comment]
This looks good for assigning validation permission to a group.

But how do you assign that permission for one or more specified taxa? (to satisfy the OP)

**Comment by gubuntu** [comment]
you've implemented this, right @dimasciput

**Comment by dimasciput** [comment]
still only in backend @gubuntu , the front end not yet ready.

**Comment by gubuntu** [comment]
waiting for @NyakudyaA to test

**Comment by NyakudyaA** [comment]
I think this is implemented here.

![screenshot 2019-01-16 at 18 22 17](https://user-images.githubusercontent.com/2510900/51262784-b81d0880-19bb-11e9-889c-204592cda375.png)

@gubuntu can you give me sample data for this so that I can go through the whole process to test it

**Comment by dimasciput** [comment]
implemented
