### ISSUE TITLE
only send to validator after contributor review

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#236]
# problem

validator sees new records after upload, whether the contributor has reviewed them or not

# solution

the validator must only see new records after the contributor has reviewed / confirmed them

**Comment by cchristelis** [comment]
@gubuntu, this looks like a "Next, Next" workflow, where a user has already looked at the data (while entering or uploading) and will either already have checked or wouldn't check. Either case the second confirmation is something that most users will just "next, next" or "ok, ok" past...

**Comment by gubuntu** [comment]
In that case give the contributor an option to submit all records for validation with one click if they are confident they don't need to check again. Or make it clear that once they leave the update screen, all records will be submitted for validation.

**Comment by gubuntu** [comment]
@Vries14 please add a comment with a reason for closing for every issue you close

**Comment by Vries14** [comment]
One click submission for validation and option for validating records in edit screen  upon updating are given.
