### ISSUE TITLE
FBIS Manual link broken

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2364]
I tried to download the manual on FBIS production/Help.
Please can you check. I cant find it on Source References: This is where it was on the earlier version:
https://freshwaterbiodiversity.org/documents/2

![image](https://user-images.githubusercontent.com/45286876/98647028-eb711a00-233c-11eb-8c03-7d42c96ba1a4.png)

**Comment by dimasciput** [comment]
@helendallas fixed

**Comment by helendallas** [comment]
@dimasciput Please make this an automatic download , not being taken to the :

![image](https://user-images.githubusercontent.com/45286876/98818122-c8756180-2433-11eb-8e9a-e6491c706e82.png)

**Comment by helendallas** [comment]
@dimasciput Please can you change this to an automatic download please.

**Comment by dimasciput** [comment]
It should be fixed now @helendallas
