### ISSUE TITLE
River labels and searches

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2365]
(1) river labels not showing at all zoom view levels
(2) searches by river name eg 'EERSTE' not returning the data that they should. 

@helendallas @dimasciput

**Comment by helendallas** [comment]
@timlinux @dimasciput @jeremyshelton 

Also how do we deal with issues such as: two river names, one in English and one in Afrikaans.  For now I assume lasso is the only way.

![image](https://user-images.githubusercontent.com/45286876/100212517-1ac77f80-2f16-11eb-9afa-d33d4f590a1d.png)

**Comment by jeremyshelton** [comment]
@helendallas yeah I think until we upgrade to a new rivers layer the lasso is the best way. Also check #2365 for other issues linked to river name searches...

**Comment by timlinux** [comment]
Agreed re lasso. In future we can expect issues that field collection assignment of site codes may not gel with official river names. As discussed with FRC we will close this for now.
