### ISSUE TITLE
We need to replace 'Docs' menu item

### ISSUE THREAD

**Issue by iPelino** [kartoza/django-bims#2373]
On landing page menu, Docs item point to a more technical documentation. It would be better if it can only be viewed by logged in users. We need have some help/documentation for non-technical users.

**Comment by helendallas** [comment]
@dimas This is linked to #2407 
When I log in normally on RBIS I don't see all the admin wagtail pages.

**Comment by helendallas** [comment]
The docs in the docs menu are all for technical and admin users. The docs for ordinary users still have to be produced. I will make a separate ticket for this and close this ticket for now.
