### ISSUE TITLE
Please sort Site Visit by Site Code then Sampling Date

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2379]
To enable users to see multiple sampling dates for the same site, please sort site visit data by:
Site Code
Sampling Date
![image](https://user-images.githubusercontent.com/45286876/99043932-a268d200-2597-11eb-85be-33856d2fc4c3.png)

**Comment by timlinux** [comment]
Can we do it like this @dimasciput 


![image](https://user-images.githubusercontent.com/178003/104439634-3a2f7000-5589-11eb-99fa-ba7f84f858ce.png)

**Comment by dimasciput** [comment]
@helendallas in addition to order button, I've also added site code filter

**Comment by helendallas** [comment]
@dimasciput Thanks Dimas, filter by Site Code is very useful. Please can you roll this extra functionality out to RBIS.
![image](https://user-images.githubusercontent.com/45286876/107614591-46275400-6c53-11eb-8fe5-658e391d5288.png)

**Comment by dimasciput** [comment]
This has now been deployed to RBIS

**Comment by helendallas** [comment]
@dimasciput Thanks, please can you also include Owner in the sort

![image](https://user-images.githubusercontent.com/45286876/108347533-4bebdf00-71e9-11eb-8174-192da306ec33.png)

**Comment by helendallas** [comment]
@dimasciput Checked on RBIS, working thanks, closing ticket
