### ISSUE TITLE
update geometry edit not practical

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#238]
# problem

in Update UI, you click on a new location to move the point but the scale is way to small and there are no other map controls

# solution

- zoom in closer first
- allow user to choose another basemap 
- allow user to choose edit control so they know that their action will be moving the point
- add the ability to enter coordinates instead of clicking on the map

**Comment by Vries14** [comment]
- Able to zoom into the map
- user able to change to another basemap
- edit control implemented
- Able to enter coordinates
