### ISSUE TITLE
Algal CSV files

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2382]
This ticket follows #2040 

@dimasciput Is it possible to order the returned data in the csv files as per the upload template, followed by the contextual data. Significant thought was given to the layout of the upload templates so best to return the data in the same way.

Also please check why Abundance measures - should be Species valve/frustule count not Number (in Detail Algae data and csv) e.g. A2SAND-00014; 7/27/2018

And another example:
H1MOLE-00051 ; 15/10/2010 - Abundance measure should be Density (cells/m2) not Species valve/frustule count (in Detail Algae data and csv)

https://freshwaterbiodiversity.org/site-visit/detail/1523/

![image](https://user-images.githubusercontent.com/45286876/99045255-b9102880-2599-11eb-86d2-d30526cd815c.png)

**Comment by dimasciput** [comment]
> @dimasciput Is it possible to order the returned data in the csv files as per the upload template, followed by the contextual data. Significant thought was given to the layout of the upload templates so best to return the data in the same way.

It's possible but it will take some time, maybe let's do that in next version.

> Also please check why Abundance measures - should be Species valve/frustule count not Number (in Detail Algae data and csv) e.g. A2SAND-00014; 7/27/2018
And another example:
H1MOLE-00051 ; 15/10/2010 - Abundance measure should be Density (cells/m2) not Species valve/frustule count (in Detail Algae data and csv)

This should be fixed now.

**Comment by dimasciput** [comment]
@helendallas

**Comment by helendallas** [comment]
@dimasciput That sounds fine
