### ISSUE TITLE
Climate data on Overview dashboard not showing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2388]
Not sure if climate data exists for Rwnada  - I assume so, but it is not showing in the overview dashboard.

![image](https://user-images.githubusercontent.com/45286876/99641796-6b8d3300-2a53-11eb-94dc-80731e03ca41.png)

**Comment by NyakudyaA** [comment]
@helendallas there is no climate data loaded in GeoServer for this, They will need to be sourced from https://www.worldclim.org/ or any local data custodians from Rwanda

**Comment by timlinux** [comment]
I propose that we use WorldClim for now until a local data is available:

https://www.worldclim.org/data/worldclim21.html

![image](https://user-images.githubusercontent.com/178003/100996638-330c4f80-3551-11eb-885a-fd264603d9ae.png)

**Comment by mmindje** [comment]
@Obed, we still need to get the meteorological data after meeting the DG this next week

**Comment by timlinux** [comment]
As discussed in today's meeting, @bimeobed will use the worldclim data for the mean time. He is simultaneously trying to obtain official data from the Meteorological Agency of Rwanda.

**Comment by timlinux** [comment]
@NyakudyaA Can you please set up a 2 hour session with  @bimeobed 

Topics to cover:

* QGIS workflow for prepping WorldClim data
* Sorting our legends for Agriculture and  Landuse layers

**Comment by timlinux** [comment]
Checked in with OBED again - he will check Beth to decide if we want to use a global dataset in the interim.

**Comment by timlinux** [comment]
Any news on this @mmindje - it would be great to have this added to the platform.

**Comment by mmindje** [comment]
> Any news on this @mmindje - it would be great to have this added to the platform.

So far, we have not received the meteo data- we still following up with this.

**Comment by timlinux** [comment]
@NyakudyaA can you please meet up with @bimeobed and help him get the context setup for the climate layers he has published on geonode.

**Comment by NyakudyaA** [comment]
@bimeobed  Are you available tomorrow for me to walk your through this

**Comment by bimeobed** [comment]
Thank you @NyakudyaA  Now I am on field could we plan on Monday?

**Comment by timlinux** [comment]
@NyakudyaA can you please meet up with @bimeobed and help him get the context setup for the climate layers he has published on geonode.

**Comment by NyakudyaA** [comment]
@bimeobed I am setting up a 10 am meeting on Monday to complete this. Will send the calendar invite

**Comment by bimeobed** [comment]
Thank you  @NyakudyaA   I got the invitation , I confirm my attendance  tomorrow .

**Comment by dimasciput** [comment]
Climate data is now visible on the live site:
![image](https://user-images.githubusercontent.com/1979569/179904696-06c0cadd-6d9f-4ea5-b05b-c275265d2cb2.png)

https://rbis.ur.ac.rw/map/#search/CKIV3307-00179/taxon=&search=CKIV3307-00179&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22RBIS%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=11158&dst=

**Comment by bimeobed** [comment]
@dimasciput Many thanks the data has been successfully uploaded
