### ISSUE TITLE
Add GBIF locality to Site Description for GBIF Sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2389]
For data harvested from GBIF, the locality information needs to be included and used to populate the Site description.

![image](https://user-images.githubusercontent.com/45286876/99643294-2e29a500-2a55-11eb-9922-d4ead89c5f3d.png)

Also: The Owner should be blank or say GBIF, not the person who harvested the data.
![image](https://user-images.githubusercontent.com/45286876/99643130-fe7a9d00-2a54-11eb-8bf0-1c5292ae5c37.png)

**Comment by timlinux** [comment]
Check if this is because the locality does not exist in GBIF or if it is not being ingested. @dimasciput please check.

**Comment by dimasciput** [comment]
Fixed
