### ISSUE TITLE
Red outlines for filter selections have disappeared

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2398]
The red outline showing which data are filtered using the spatial filter is not visible anymore

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20G%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/100201091-46436d80-2f08-11eb-9b7e-383714340d01.png)

**Comment by helendallas** [comment]
From issue #2052

**Comment by dimasciput** [comment]
@helendallas it should be showing again now

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

Still not working my side?
<img width="1169" alt="Screenshot 2020-12-04 at 05 46 44" src="https://user-images.githubusercontent.com/44292029/101119680-8be0f400-35f4-11eb-944b-d3ba84631ea8.png">

**Comment by dimasciput** [comment]
@jeremyshelton 
![image](https://user-images.githubusercontent.com/1979569/101122571-615b5f00-3625-11eb-9f04-941bdb3fd959.png)

**Comment by jeremyshelton** [comment]
@dimasciput aahhh ok working now 👍
