### ISSUE TITLE
Please correct label for Ecological region 1 and Ecological region 2 in Algal Detailed dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2401]
Ecological region 1 should be Ecoregion Level 1
Ecological region 2 should be Ecoregion Level 2

Where is this managed in the Admin - I could not find where to correct it.

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=H1MOLE-00051&siteId=33354&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33354&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/100205276-92dd7780-2f0d-11eb-94b6-a3a1dba95d64.png)

It should be as below: and it is correct in the Fish, Invert and sometimes for algae????

![image](https://user-images.githubusercontent.com/45286876/100205591-febfe000-2f0d-11eb-9a87-b4aaf053ce5e.png)

**Comment by dimasciput** [comment]
@helendallas should be fixed now
