### ISSUE TITLE
Fix text in detailed dashboards

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2402]
**Remove None:**
None Site Code  - Site Code

![image](https://user-images.githubusercontent.com/45286876/100209213-447ea780-2f12-11eb-8457-f89e0f35d94c.png)

**Make Capital:**
Management **A**rea

**Make singular:**
- Sub Water Management Area
- River Management Unit

![image](https://user-images.githubusercontent.com/45286876/100209301-5f511c00-2f12-11eb-88fc-03bc3a1b96a2.png)

Change to group header to **South African Provinces**
and then Province

![image](https://user-images.githubusercontent.com/45286876/100209670-d7b7dd00-2f12-11eb-8089-621c5b13638c.png)

### **Please also show us in Admin where one can administer these small edits ourselves.**

**Comment by dimasciput** [comment]
@helendallas fixed
