### ISSUE TITLE
Please add ability to filter by author in Explore Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2404]
We need to be able to find a source reference by filtering on Author. At the moment it is not possible.

![image](https://user-images.githubusercontent.com/45286876/100216318-cecb0980-2f1a-11eb-8e68-32c1958fd371.png)

**Comment by helendallas** [comment]
Sometimes it works:
![image](https://user-images.githubusercontent.com/45286876/100216546-1356a500-2f1b-11eb-9a46-4b6e99a8e6ab.png)

Other times not:
![image](https://user-images.githubusercontent.com/45286876/100216653-34b79100-2f1b-11eb-8774-aa9543490151.png)

Might be related to reference category?

**Comment by timlinux** [comment]
@dimasciput would need to add a filter for author for this.

**Comment by helendallas** [comment]
@dimasciput Depending on how the authors are presented in the DOI, etc, the same author appears with different formats. Is it possible to allow selection of multiple names, by using the shift enter key as one does in excel. Then we can add a tool tip:

  **To select multiple names please use "SHIFT ENTER" and click on each name for selection**  

See example below.

![image](https://user-images.githubusercontent.com/45286876/108463304-d0d90600-7286-11eb-93eb-3a69bf002744.png)

**Comment by dimasciput** [comment]
@helendallas added multiple selection in the source reference page
![image](https://user-images.githubusercontent.com/1979569/113981109-7a914800-9871-11eb-9023-e7efdfdbcfad.png)

**Comment by helendallas** [comment]
Working well thanks, closing ticket
