### ISSUE TITLE
We need a Validate Records option on Admin/Profile menu

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2408]
The administrators need to be able to validate records added by users. This needs to be added:
![image](https://user-images.githubusercontent.com/45286876/100323851-05625c00-2fcf-11eb-92b3-1023c0092cb1.png)

**Comment by helendallas** [comment]
For FBIS, please can **Validate Records** and **Update records** be moved to Administration drop down

![image](https://user-images.githubusercontent.com/45286876/112457529-89053d00-8d64-11eb-8360-0e2dece8fc7e.png)

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary 
Please can you add tool tips/ hover over text for these buttons, View, Update, Send for validation

![image](https://user-images.githubusercontent.com/45286876/123966867-171d3f00-d9b6-11eb-9121-d5da2a75e0fd.png)


![image](https://user-images.githubusercontent.com/45286876/123966672-ea692780-d9b5-11eb-90d3-0ba9933af726.png)

Please confirm when this is done so I can check again, thanks

**Comment by dimasciput** [comment]
@helendallas this is deployed to live.

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary Closing ticket
