### ISSUE TITLE
Check spatial filter - Rwanda Catchments Level 2 and 3

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2409]
The filters shown in these two levels look identical. Please can these be checked as they should be hierarchical I think. 

@mmindje I am tagging in you so that you get an idea about the pre-release checks that need to be done.

![image](https://user-images.githubusercontent.com/45286876/100324452-f334ed80-2fcf-11eb-921c-a333dfd9f232.png)

![image](https://user-images.githubusercontent.com/45286876/100324490-021ba000-2fd0-11eb-9045-e976acb3d286.png)

**Comment by helendallas** [comment]
Also for Rwanda Catchments Level 3, multiple spatial units are returned.

![Uploading image.png…]()

**Comment by mmindje** [comment]
> The filters shown in these two levels look identical. Please can these be checked as they should be hierarchical I think.
> 
> @mmindje I am tagging in you so that you get an idea about the pre-release checks that need to be done.
> 
> ![image](https://user-images.githubusercontent.com/45286876/100324452-f334ed80-2fcf-11eb-921c-a333dfd9f232.png)
> 
> ![image](https://user-images.githubusercontent.com/45286876/100324490-021ba000-2fd0-11eb-9045-e976acb3d286.png)

@bimeobed i THINK YOU CAN CHECK if these spatial layer filters are not identical. Thank you
