### ISSUE TITLE
Some filters such as Agro-ecology filter are blank

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2411]
fyi @mmindje 

![image](https://user-images.githubusercontent.com/45286876/100325500-6db23d00-2fd1-11eb-803c-8fd3da2aab0d.png)

**Comment by helendallas** [comment]
Also
![image](https://user-images.githubusercontent.com/45286876/100326554-c9c99100-2fd2-11eb-9aeb-92c7ab8fa3b9.png)

![image](https://user-images.githubusercontent.com/45286876/100326727-fda4b680-2fd2-11eb-8925-40ca7ea3d2d9.png)

![image](https://user-images.githubusercontent.com/45286876/100326755-07c6b500-2fd3-11eb-8394-76cad22487a2.png)

![image](https://user-images.githubusercontent.com/45286876/100326779-11e8b380-2fd3-11eb-9e5d-3c2aeaac49c9.png)

Some of these may in fact be more suited to being spatial layers rather than filters. The RBIS team need to decide if it is important to know what sites are in each geology type/soil type/road etc.

**Comment by bimeobed** [comment]
This issue will be dressed in our weekly local meeting to decide whether it will be spatial layers rather than filters. Thank you
