### ISSUE TITLE
Layers - Land use layer is duplicated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2413]
There are two land use layers, the first is only black and white, the second, below, is in colour. I suggest deleting the first.
![image](https://user-images.githubusercontent.com/45286876/100329009-cdaae280-2fd5-11eb-9315-1c87fff9e879.png)

@mmindje FYI

**Comment by mmindje** [comment]
The background is still black.
**Admire** needs to help in this case @bimeobed .

**Comment by NyakudyaA** [comment]
> The background is still black.
> **Admire** needs to help in this case @bimeobed .

Will check it now and rectify

**Comment by mmindje** [comment]
Sure, thank you @NyakudyaA
