### ISSUE TITLE
Locate by coordinate needs revising for Rwanda

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2415]
It would be good to revise text to show Rwanda not Cape Town

![image](https://user-images.githubusercontent.com/45286876/100329788-cc2dea00-2fd6-11eb-8cd1-b17a4cc1054d.png)

**Comment by iPelino** [comment]
Hi Dimas

Please be informed that the RBIS servers have been temporarily unavailable
due to security reasons. We are actively working to resolve these issues
and expect the servers to be back online soon.

Pelin.
