### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2417]
At the moment, when one download a CSV file, a request is sent to the RBIS team who then approve or reject the request.

Two issues:

The Download returns a file that I cannot read, it needs to be the normal csv file, please.
![image](https://user-images.githubusercontent.com/45286876/100334224-2aa99700-2fdc-11eb-823f-12713f91180f.png)

Once it is approved, the email end sup in the spam folder

**Comment by dimasciput** [comment]
> The Download returns a file that I cannot read, it needs to be the normal csv file, please.

This is fixed

> Once it is approved, the email end sup in the spam folder

@iPelino can you send me an email account details that I can use for the site?

**Comment by dimasciput** [comment]
This should be fixed, email is not sent to spam anymore.
