### ISSUE TITLE
Admin need to be able to edit/delete a study reference from Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2421]
At the moment one gets directed to the reference if one clicks on the title. As administrators we need to be able to edit the reference and/or delete the reference in the case where there are no records associated with it.

This may only be relevant for categories except peer-reviewed scientific papers

![image](https://user-images.githubusercontent.com/45286876/100601727-a0c73a00-330b-11eb-9a15-4f5b0064c456.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/104436508-9abcae00-5585-11eb-92fa-d8dd807d3cc3.png)

**Comment by dimasciput** [comment]
Delete button has been added

**Comment by helendallas** [comment]
@dimasciput Thanks, working for most but for some reason not for the two listed below, not sure why?

![image](https://user-images.githubusercontent.com/45286876/111600133-bf2d4480-87d9-11eb-955f-5d13db1d642b.png)

**Comment by dimasciput** [comment]
@helendallas this is fixed now, there's a hidden space in one of the source reference's title.

**Comment by helendallas** [comment]
Fixed closing ticket
