### ISSUE TITLE
Amphibian data ingested but sites not showing in RBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2433]
I ingested the new amphibian file: but sites not visible. Please can you check - sites normally show up straight away.
![image](https://user-images.githubusercontent.com/45286876/101143311-60273380-361f-11eb-8506-c0075fe35c2f.png)

![image](https://user-images.githubusercontent.com/45286876/101143454-949aef80-361f-11eb-9fab-8e64db1aade3.png)

**Comment by dimasciput** [comment]
@helendallas check again, sometimes it may take a moment.

**Comment by helendallas** [comment]
@dimasciput Okay, its through now thanks
