### ISSUE TITLE
SASS Accreditation missing from filter for FBIS 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2435]
The Validation Status filter was modified for RBIS and the SASS Accreditation removed. This needs to be added back as before for FBIS please

![image](https://user-images.githubusercontent.com/45286876/101328424-a5926d80-3878-11eb-85d2-107c686adfb3.png)

**Comment by dimasciput** [comment]
the filter is now shows up

**Comment by helendallas** [comment]
@dimasciput Nope SASS Accreditation still missing - used to be:

![image](https://user-images.githubusercontent.com/45286876/106871236-b45f9a00-66da-11eb-9c22-e38c338c6c68.png)

**Comment by dimasciput** [comment]
@helendallas please try again now.

**Comment by helendallas** [comment]
@dimasciput Thanks its back now, closing ticket
