### ISSUE TITLE
Please check and confirm base maps

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2436]
During revision of base maps for RBIS, the terrain one generated for FBIS has disappeared. Please can this be added in again.

![image](https://user-images.githubusercontent.com/45286876/101329624-4afa1100-387a-11eb-920d-aa5cd8c6171f.png)

**Comment by helendallas** [comment]
@dimasciput I thought we had settled on:
five base layers - Bing satellite hybrid, terrain (the new one created by Kartoza), topography, aerial photograph, plain B and W

The aerial photograph seems to have disappeared

**Comment by dimasciput** [comment]
@helendallas I added the aerial layer, please test.

**Comment by helendallas** [comment]
@dimasciput Thanks looks fine, closing
