### ISSUE TITLE
Kwazulu Natal appears twice in the province spatial filter

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2437]
@dimasciput 
<img width="336" alt="Screenshot 2020-12-07 at 11 21 23" src="https://user-images.githubusercontent.com/44292029/101332908-9dd5c780-387e-11eb-90c4-6634917c48ba.png">

**Comment by dimasciput** [comment]
@jeremyshelton should be fixed now

**Comment by jeremyshelton** [comment]
@dimasciput 

Fixed. Thanks 👍
