### ISSUE TITLE
spatial filters not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#244]
maybe just not implemented yet

**Comment by gubuntu** [comment]
yes that's part of it

it's also https://github.com/kartoza/LEDET_BIMS/issues/30 - when  zoomed in to view a subset, the search results weren't filtered by the new extent (might be fixed by now)

Now with the admin boundaries in https://github.com/kartoza/LEDET_BIMS/issues/211 the spatial filter must act on the intersection of the chosen admin boundaries and the view extent.

**Comment by Vries14** [comment]
Spatial filters working. Also able to add filters with boundary of spatial search and access records of sites.
Fixed in #311
