### ISSUE TITLE
GBIF data paper trail?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2441]
When data from GBIF are served for a query, is it possible to provide more details in the metadata, including (1) where the data came from (e.g. SAIAB, iNaturalist etc)?

...as it stands, there is no way of knowing where the 'GBIF' data came from, but this is actually very important information.

<img width="1301" alt="Screenshot 2020-12-07 at 14 01 12" src="https://user-images.githubusercontent.com/44292029/101349405-fbc1d980-3895-11eb-9faf-db1c7804a558.png">

**Comment by helendallas** [comment]
Closing ticket as already resolved
