### ISSUE TITLE
SASS dashboard - colour category legend needed for SASS charts

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2442]
The SASS charts in the SASS dashboard are currently presented without a legend. 
Would be great to have the legend (from the 'Ecological category' panel) up front with the SASS charts so the user knows what these colours mean?
@helendallas ?
@dimasciput 

<img width="446" alt="Screenshot 2020-12-07 at 15 15 14" src="https://user-images.githubusercontent.com/44292029/101355683-9541b900-389f-11eb-8988-5055090159e1.png">

**Comment by helendallas** [comment]
@dimasciput Please add legend for SASS charts as suggested by Jeremy:

![image](https://user-images.githubusercontent.com/45286876/114889623-8ef1b980-9e0a-11eb-96dc-43dcc0e26bfa.png)
<img width="446" alt="Screenshot 2020-12-07 at 15 15 14" src="https://user-images.githubusercontent.com/44292029/101355683-9541b900-389f-11eb-8988-5055090159e1.png">

**Comment by dimasciput** [comment]
@Fanevanjanahary here's one of the SASS dashboard ``/sass/dashboard/11776/?taxon=&search=&siteId=11776`

**Comment by helendallas** [comment]
@dimasciput  Please confirm where I can view this?

**Comment by dimasciput** [comment]
@helendallas it's not done yet, I reassigned this ticket to Faneva.
