### ISSUE TITLE
Chart downloads not working in dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2444]
@dimasciput 
@helendallas 

When I click on download chart, nothing happens.

<img width="854" alt="Screenshot 2020-12-08 at 06 11 57" src="https://user-images.githubusercontent.com/44292029/101439165-9cf37300-391c-11eb-933a-bdbf11097294.png">

**Comment by helendallas** [comment]
@dimasciput  the following downloads do not work:

**Fish, invertebrate, algae dashboard:**

- Distribution
- Occurrence data
- Occurrences
- Metadata table
- Abiotic data

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=9621&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=True&ecologicalCategory=&rank=&siteIdOpen=9621&orderBy=-total_survey&polygon=

**SASS Dashboard - please add download for** 

- Overview
- Metadata tabl

e

https://freshwaterbiodiversity.org/sass/dashboard/9499/?taxon=&search=&siteId=9499&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,sa_provinces,Gauteng%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=%5B%22E%22%5D&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by helendallas** [comment]
@dimasciput the following downloads do not work:

**Fish, invertebrate, algae dashboard: still not downloadable**

    
    Abiotic data

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=9621&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=True&ecologicalCategory=&rank=&siteIdOpen=9621&orderBy=-total_survey&polygon=

**SASS Dashboard - please add download for**

    Overview
    Metadata table

https://freshwaterbiodiversity.org/sass/dashboard/9499/?taxon=&search=&siteId=9499&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,sa_provinces,Gauteng%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=%5B%22E%22%5D&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by dimasciput** [comment]
Hi @Fanevanjanahary can you address this ticket? The sass dashboard is here : https://freshwaterbiodiversity.org/sass/dashboard/9499/?taxon=&search=&siteId=9499

**Comment by dimasciput** [comment]
@helendallas please test

**Comment by jeremyshelton** [comment]
Hi @dimasciput @Fanevanjanahary 
Chart downloads now working for me on Chrome but not on Safari.
No download button available for metadata table in taxon dashboard and SASS dashboard.

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 

I use Firefox - all downloads working on fish, invert, algal and odonata adults dashboards.

Still no download option for SASS dashboard:
Overview
Metadata table

![image](https://user-images.githubusercontent.com/45286876/122354383-39907080-cf51-11eb-992f-d6b3fd542146.png)


![image](https://user-images.githubusercontent.com/45286876/122354405-41501500-cf51-11eb-9d4d-c9a0bc94ad88.png)

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas please test on the testing site, Faneva should have fixed it.

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary 

All downloads now working. However **Ecological category** has some extra blocks? And please make font of axis larger and darker, and dots larger.

![image](https://user-images.githubusercontent.com/45286876/122753841-1c320e00-d293-11eb-97c9-2c6cfff443fe.png)

Also with the SASS charts, the title (SASS charts - ASPT) is not needed, and the colour coding should say the ecological category not ASPT etc.  as below the SASS chart at the moment.

See here - 
![image](https://user-images.githubusercontent.com/45286876/122754476-03762800-d294-11eb-97a6-e90777b9f7b2.png)

![image](https://user-images.githubusercontent.com/45286876/122753968-4edc0680-d293-11eb-855a-90e58d56f8d2.png)

General: Is it possible to make the text for the axis larger and bold. I know if is possible to edit using a graphics tool, but it would be much more user friendly if the graphs were ready for reports etc. The way they are now the user still needs to do quite a bit of editing once they are inserted in a report.

**Comment by dimasciput** [comment]
@Fanevanjanahary can you check Helen's feedback.

**Comment by dimasciput** [comment]
> General: Is it possible to make the text for the axis larger and bold. I know if is possible to edit using a graphics tool, but it would be much more user friendly if the graphs were ready for reports etc. The way they are now the user still needs to do quite a bit of editing once they are inserted in a report.

This might be bit tricky with our charting library. Can we park this for later?

**Comment by dimasciput** [comment]
@helendallas

**Comment by helendallas** [comment]
@dimasciput Happy to park reformatting of graphs. I will create a ticket in FBIS 2.
@Fanevanjanahary Have you fixed the issues with the SASS graphs?

However Ecological category has some extra blocks? can you delete these?


![image](https://user-images.githubusercontent.com/45286876/122753841-1c320e00-d293-11eb-97c9-2c6cfff443fe.png)

**Comment by Fanevanjanahary** [comment]
Hi @helendallas I've already removed it, the PR is not merged yet since I'm changing the legend in SASS charts

![image](https://user-images.githubusercontent.com/12623986/123948418-0d8dda00-d9aa-11eb-8625-5d747951670e.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Thanks, please confirm when it is ready to be checked.

**Comment by jeremyshelton** [comment]
@Fanevanjanahary @dimasciput 
Is this now ready to be tested?

**Comment by dimasciput** [comment]
@jeremyshelton not ready yet

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Will wait for your signal before testing.

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Please let me know when this is ready for testing. Its been two weeks

**Comment by timlinux** [comment]
As discussed in our meeting today we can hold out on fixing this in favour of implementing https://www.highcharts.com

That will take a couple of days of @dimasciput tims so we will move that over to FBIS2.

**Comment by helendallas** [comment]
I am closing this ticket

**Comment by helendallas** [comment]
Same issue is back with ecological categories chart...fixed by @Fanevanjanahary in June 30 2021.....please check
