### ISSUE TITLE
search is too fuzzy

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#245]
e.g. unrelated taxa (Gerrosaurus) come up with 'Agama' search

**Comment by cchristelis** [comment]
I'm moving this out of ready, because I have found that resolving fuzziness can be a big fiddle and a huge time drain. Let's revisit when we've gotten a better handle on our backlog.

**Comment by Vince-Egan** [comment]
Could we set this to look for the search term as part of the taxon/species field rather than something that is similar?

**Comment by dimasciput** [comment]
@Vince-Egan @gubuntu how about first we do exact search, then if there are no results we do the similarity search? Just like google

**Comment by dimasciput** [comment]
@Vince-Egan what do you think about this https://github.com/kartoza/django-bims/pull/276 ?

**Comment by Vries14** [comment]
Reproduced on testing, unrelated taxa no longer come up with searches
