### ISSUE TITLE
We need to create a general README that gets sent with any downloaded data.

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2452]
@dimasciput  could we maybe do a little templating so we can include the site url etc in a generic way?

**Comment by timlinux** [comment]
Things to include:

- license of data see https://creativecommons.org/choose/ to select an appropriate creative commons license
- source of the data / web site
- contact points
- citation of the data e.g. data downloaded from RBIS on <date> from https://rbis.ur.ac.rw 
- refer to individual citation of occurrence record for per-record citations
- call for contribution

**Comment by helendallas** [comment]
@timlinux Please can you provide us with an example from one you have previously generated if possible.

**Comment by helendallas** [comment]
@mmindje Are you able to create this using the guidance provided by Tim in the ticket?

**Comment by timlinux** [comment]
> @timlinux Please can you provide us with an example from one you have previously generated if possible.

Here is the one we ship with healthsites.io:

```

Provenance:

This data was generated as an extract from the OpenStreetMap global open database
(http://openstreetmap.org) by the Healthsites.io (http://healthsites.io) project. 

Caveats:

This data is an extract from OpenStreetMap and may differ in part or substantially from the
current state of the upstream OpenStreetMap project. In particular, entities deleted in 
OpenStreetMap may still be present in this extract, and changes to entities in OpenStreetMap
may not yet be reflected in this extract.

Healthsites.io provides these extracts as a convenience to people and organizations 
interested in supporting access to healthcare. In addition to the provisions laid out
in the ODBL license, Healthsites.io takes no responsibility for any inadequacies in the
data provided here. All data is provided on a best effort basis. 



Please make sure to credit the OpenStreetMap project whenever using this data using the text 
in the 'data credits' section below. Although not required, we would appreciate it if you 
additionally mention the HealthSites.io project (and link to our web site at http://healthsites.io) when citing this
data - it will help to support and publicise our work.

License:

Data: Open Database License http://opendatacommons.org/licenses/odbl/ - see accompanying LICENSE.txt 
    file for a complete copy of this license.
Data credits : © OpenStreetMap contributors (http://www.openstreetmap.org/copyright)

Our intention is to foster widespread usage of the data that we provide. 
Please use this data in the interests of humanity and not for nefarious purposes.
```

**Comment by helendallas** [comment]
@mmindje Here are some details from Tim for the document you wanted to produce

**Comment by mmindje** [comment]
Thanks again to bring this to attention.
We has an internal meeting and discussed further on the read me before data download and produced a data user agreement that has to be signed. IT team on our side can work with Dimas to have this finalized.

It will be a simple online form to fill after someone downloads data- just names and ticking Terms and conditions applying to the purpose of using data.

**Comment by helendallas** [comment]
Closing this as RBIS as project closed
