### ISSUE TITLE
Landing page feedback icon not yet connected to GitHub

### ISSUE THREAD

**Issue by DanielIgirimbabazi** [kartoza/django-bims#2456]

**Comment by DanielIgirimbabazi** [comment]
Hi all,

If possible you may see if this issue can be fixed;👇

![image](https://user-images.githubusercontent.com/64969680/102507671-32b19f80-408d-11eb-9f84-98c8e18a07d8.png)

And the result.....

![image](https://user-images.githubusercontent.com/64969680/102507799-5543b880-408d-11eb-9648-acd29e8f001d.png)

**Comment by mmindje** [comment]
Hi @DanielIgirimbabazi, and @dimasciput I think connecting to Github will require the link to our repository which is https://github.com/mmindje/Data-management-FRC-RBIS/projects

**Comment by helendallas** [comment]
This link is now working. Closing ticket.
