### ISSUE TITLE
Improve site security

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2458]
@dimasciput @timlinux 

fbis@frcsa.org.za is receiving a lot of spam - approx 20 emails a day. Anything we do to minimise this?

**Comment by dimasciput** [comment]
@jeremyshelton I have fixed it, did you still receive spam emails?

**Comment by jeremyshelton** [comment]
@dimasciput yeah it was still getting spammed yesterday when I checked. When did you fix?

**Comment by dimasciput** [comment]
@jeremyshelton last week, can you email me some of the spams

**Comment by jeremyshelton** [comment]
@dimas done

**Comment by dimasciput** [comment]
@jeremyshelton will check it later today

**Comment by dimasciput** [comment]
Should be fixed now

**Comment by jeremyshelton** [comment]
Thanks @dimasciput
