### ISSUE TITLE
We need to validate new sites created by users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2460]
At the moment a user can create a new site, without it being validated by FBIS Admin.  

Please can we add functionality that forces new sites to be validated so that we can avoid erroneous sites.

**Comment by helendallas** [comment]
@dimasciput How do I validate a site?

**Comment by Fanevanjanahary** [comment]
@helendallas you can find it here https://freshwaterbiodiversity.org/nonvalidated-site/

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Following this link takes me to this page:

 ![image](https://user-images.githubusercontent.com/45286876/127978324-08f9a688-11fe-42f3-a7a0-0d4737851028.png):


then when I click on the site I get the screen below, which has lots of data missing

![image](https://user-images.githubusercontent.com/45286876/127978535-c8696353-4f56-4c86-b4dc-d09d1d2cd948.png)

I need to be able to zoom in on the location to check for accuracy, then need to see details as in the Site edit form, especially owner, site description etc., and then I need to be able to fix coordinates if they are incorrect, and save the site.

The View Site Detail should open up the Site Edit form as per 👍 https://freshwaterbiodiversity.org/location-site-form/update/?id=42861

We also need this added as a dropdown option to the Administration:
**Validate site**

Also filters don't seem to work -

**Comment by dimasciput** [comment]
@Fanevanjanahary can you add the link to site edit?

**Comment by dimasciput** [comment]
@helendallas I added the menu to go to this page in the testing site, I haven't deployed it yet to live. Probably end of today.

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary We still don't have **Validate Site** as a dropdown on the admin, so it cannot be accessed easily. I havent been able to check this.

**Comment by helendallas** [comment]
Ok thanks, I will check on testing

**Comment by helendallas** [comment]
Seems to be a problem
https://testing.healthyrivers.kartoza.com/nonvalidated-site/?page=2

![image](https://user-images.githubusercontent.com/45286876/130739959-10842081-d73c-4e1d-8db0-d43aa6b9001b.png)

**Comment by helendallas** [comment]
@dimasciput Please jump in and help here. we need site validation fixed and rolled out onto FBS live asap, please

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Please give me an update on this. I see it is on testing but not as we need it. Clearly it still needs rmore work

![image](https://user-images.githubusercontent.com/45286876/132341087-86ec4aee-c58f-49af-8e95-cd91062ee016.png)

**Comment by dimasciput** [comment]
@helendallas it's on live now, we could improve the style/layout later, but I think this should be enough for this ticket.

**Comment by helendallas** [comment]
@dimasciput Thanks. Where there is no Owner? How can these be blank? 

When I view and edit, I get an error message when saving
![image](https://user-images.githubusercontent.com/45286876/132455771-d686bf4e-117d-40cc-9845-946374687d46.png)

**Comment by dimasciput** [comment]
@Fanevanjanahary can you check this issue?

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary 

Also there are now over 3,500 sites to validate. This cant be right???? Sites for validation should only include sites that a user add themselves using the FBIS online platform. Not sites migrated through Biobase, Rivers database or by FBIS admin uploading them.

**Comment by dimasciput** [comment]
> Also there are now over 3,500 sites to validate. This cant be right???? Sites for validation should only include sites that a user add themselves using the FBIS online platform. Not sites migrated through Biobase, Rivers database or by FBIS admin uploading them.

@helendallas I will fix this one.

**Comment by dimasciput** [comment]
@helendallas what about sites that created from GBIF? Should we also automatically validated them?

**Comment by helendallas** [comment]
No, we cnat validate GBIF sites, as we know they are often wrong, but we can also not fix them in FBIS. We need to exclude from Site Validation, van you include the filter as for records?

**Comment by dimasciput** [comment]
> No, we cnat validate GBIF sites, as we know they are often wrong, but we can also not fix them in FBIS. We need to exclude from Site Validation, van you include the filter as for records?

@helendallas can we do it on different ticket, and let's close this one?

**Comment by helendallas** [comment]
Fine @dimasciput . I will close this ticket now, and will recheck site validation once the GBIF site have been removed.
