### ISSUE TITLE
Fish master list in Taxon Managament csv still has alien and indigenous 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2461]
When I download master list from Taxon Management for fish, alien , idigenous still shown.

@jeremyshelton Please can you check if this matches the master list of fish

[Fish Master csv downloaded from FBIS Taxon Managament 2020_01_13.xlsx](https://github.com/kartoza/django-bims/files/5807395/Fish.Master.csv.downloaded.from.FBIS.Taxon.Managament.2020_01_13.xlsx)

**Comment by jeremyshelton** [comment]
@helendallas this list that you downloaded from taxon management is not correct. A comparison with the master list (attached) shows lots of differences between the two. @dimasciput any idea why this might be the case & how best to resolve it?

[Fish_FBIS master vs taxon management download.xlsx](https://github.com/kartoza/django-bims/files/5807550/Fish_FBIS.master.vs.taxon.management.download.xlsx)

**Comment by timlinux** [comment]
Dimas: Just a backend issue since the table columns are still called alien, indigenous etc.

**Comment by helendallas** [comment]
@dimasciput This si actually for all modules, Also common names are often missing

**Comment by helendallas** [comment]
New ticket created #2557 , closing this one
