### ISSUE TITLE
Sites outside of geographic area needing review

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2462]
As per 20 Dec 2020

![image](https://user-images.githubusercontent.com/178003/104441497-ad39e600-558b-11eb-91b8-2ba5aed6e969.png)

wkt_geom | id | name | geometry_line | geometry_polygon | geometry_multipolygon | location_type_id | location_context_document | site_description | site_code | latitude | longitude | additional_data | land_owner_detail | map_reference | river_id | location_context | legacy_site_code | refined_geomorphological | original_geomorphological | creator_id | owner_id | legacy_river_name
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Point (19.11070000000000135 31.52439999999999998) | 30795 | Oorlogskloof |   |   |   | 1 |   | No description | LIMP-00042 | 31.5244 | 19.1107 |   |   |   | 4143 |   | S25 |   |   | 1886 | 1886 |  
Point (0 0) | 33258 | No details given |   |   |   | 2 |   |   | A2CROC-LEEUW | 0 | 0 |   |   | 2427 AC Makoppa | 64 |   |   |   |   | 0 | 0 |  
Point (79.62890625 -45.46013063792100439) | 40393 | C2Klip-00020 |   |   |   | 1 |   |   | C2Klip-00020 | -45.460130637921004 | 79.62890625 |   |   |   | 6191 |   | C2Klip-00020 | Lower foothill | b'Lower foothill' | 2558 | 2558 | KLIPRIVIER
Point (2.39501953125 -23.14035998788610016) | 40398 | C2twee-00020 |   |   |   | 1 |   | Hippo Dam | C2twee-00020 | -23.1403599878861 | 2.39501953125 |   |   |   | 6194 |   | C2twee-00020 |   |   | 2558 | 2558 | robinson lake
Point (-28.10408642831869841 -30.71350399035500089) | 40400 | C4Beat-00020 |   |   |   | 1 |   | Beb | C4Beat-00020 | -30.713503990355 | -28.1040864283187 |   |   |   | 6196 |   | C4Beat-00020 | Lower foothill | Lower foothill | 2558 | 2558 | Vetrivier
Point (38.25439453125 -33.55970664841197504) | 40403 | C4Beat-00020 |   |   |   | 1 |   | EBZ | C4Beat-00020 | -33.559706648411975 | 38.25439453125 |   |   |   | 6198 |   | C4Beat-00020 |   |   | 2558 | 2558 | MASAMBULE

**Comment by helendallas** [comment]
@timlinux I checked for each of these sites on FBIS, and they do not come up???  Any idea why?  I cannot check and edit them if I cant see them.

![image](https://user-images.githubusercontent.com/45286876/111624584-8a7ab680-87f4-11eb-8511-849a869460ec.png)

![image](https://user-images.githubusercontent.com/45286876/111624614-923a5b00-87f4-11eb-92c0-da30ba00965d.png)

![image](https://user-images.githubusercontent.com/45286876/111624735-bb5aeb80-87f4-11eb-8254-fb9cc7337f97.png)

**Comment by helendallas** [comment]
@dimasciput As discussed in our recent chats, we suspect these sites no longer exist or dont have data in FBIS.  If correct, please remove in backend, alert Tim and close the ticket.

**Comment by dimasciput** [comment]
Hi @helendallas should we also remove records inside Lesotho?

**Comment by helendallas** [comment]
@dimasciput For the above, can you check if these sites have data?  If they do then I need to somehow be able to fix the coordinates, which I cant do at the moment as they dont come up on FBIS.

Re Lesotho and Swaziland: No we need to include all records in Lesotho and eSwatini (previously called Swaziland). It is also important that these data are downloadable.

The reason for this is the rivers are highly linked to SA

**Comment by helendallas** [comment]
@dimasciput Please cna you update me on this ticket.

**Comment by dimasciput** [comment]
@helendallas checking...

**Comment by timlinux** [comment]
Checked with the backup from PG_bims_gis.02-August-2021.dmp

![image](https://user-images.githubusercontent.com/178003/128140284-715388a7-1a55-4be1-98ef-7ca83153d1e1.png)

But it still has Africa-wide data

![image](https://user-images.githubusercontent.com/178003/128140209-ff56dd5d-ea09-4a12-9752-315601bf598e.png)

**Comment by timlinux** [comment]
Also looking on FBIS we have 20,628 sites:
![image](https://user-images.githubusercontent.com/178003/128140734-c65297e8-35de-4f91-8c67-6ad9afabec37.png)

But in the database we have:

```
freshwaterbiodiversity.org=# select count(*) from bims_locationsite;
 count 
-------
 47197
(1 row)
```

**Comment by helendallas** [comment]
@tim I suspect this may be OdonataMap data which Dimas filters out......

**Comment by dimasciput** [comment]
@helendallas @timlinux Ok I have removed all the sites without occurrences outside SA, will check it in the QGIS later.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton there are some sites outside boundary that has occurrences, I didn't remove them. Can you check if we can remove it or not.

**Comment by jeremyshelton** [comment]
@dimasciput we are trying to do this, but it is not working.
Please see ticket #2721.

**Comment by dimasciput** [comment]
Can we close this one @jeremyshelton ?

**Comment by helendallas** [comment]
@dimasciput We can close this although Tim had a note to check co-ords. Happy to leave for now
