### ISSUE TITLE
Dashboard designer module sizes do not match rendered dashboard module sizes

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2464]
![image](https://user-images.githubusercontent.com/178003/104442688-51705c80-558d-11eb-83d5-8939152fa7c0.png)

Renders to:

![image](https://user-images.githubusercontent.com/178003/104442994-bb890180-558d-11eb-8d67-794a10d4015f.png)

Can we make the module heights match?

**Comment by dimasciput** [comment]
Fixed
