### ISSUE TITLE
Odonate import side codes not set

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2465]
![image](https://user-images.githubusercontent.com/178003/104443666-a1035800-558e-11eb-9685-56c474d27aa1.png)

**Comment by helendallas** [comment]
@dimasciput If I recall we decided to let the normal FBIS Site Code be generated. This will be done in Production after import of data, right. DO we still need this ticket?

**Comment by dimasciput** [comment]
@helendallas yes that's correct, I'll close this one
