### ISSUE TITLE
Include FRC and CoE in copyright

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2469]
@helendallas and @bakaplin To provide text.

**Comment by timlinux** [comment]
You can manage this in the partners section and footer section in the landing page now.

**Comment by helendallas** [comment]
@timlinux Please show me where this is done. I tried the landing page but it does not update

![image](https://user-images.githubusercontent.com/45286876/166915213-502cf029-50aa-42d5-9e7c-ba20ddc947e0.png)

but it is still showing as:


![image](https://user-images.githubusercontent.com/45286876/166915268-656134ff-c24d-41fc-be79-ea41ef671d90.png)

**Comment by helendallas** [comment]
Please be explicit as to where this can be updated thanks @dimasciput

**Comment by dimasciput** [comment]
@helendallas you can edit it here https://testing.rbis.kartoza.com/admin/bims/sitesetting/1/change/, find 'Copyright text'.

**Comment by helendallas** [comment]
Got it thanks

**Comment by helendallas** [comment]
Please deploy to live

**Comment by dimasciput** [comment]
deployed to live
