### ISSUE TITLE
The Download Requests is not working when activate

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2472]
I tested the Download request button and it worked for me. But then when a user tried to download a csv and I went to approve it, no records were shown.

![image](https://user-images.githubusercontent.com/45286876/105008663-321c7800-5a42-11eb-84c0-3c8ab13c874b.png)

![image](https://user-images.githubusercontent.com/45286876/105008764-5415fa80-5a42-11eb-998b-149625751b89.png)

Please can you check,  Ideally I would like the download request details logged automatically by recording:

Date | Person | Organisation | Details

And then the request is automatically approved so that there is little delay and does not require human intervention.

I have subsequently deactivated this functionality
![image](https://user-images.githubusercontent.com/45286876/105008694-3c3e7680-5a42-11eb-8a86-5318222b2748.png)

**Comment by dimasciput** [comment]
Hi @helendallas this should be fixed now, but the user need to request again, sorry

**Comment by dimasciput** [comment]
```
Ideally I would like the download request details logged automatically by recording:

Date | Person | Organisation | Details
```
Regarding this, please create a different ticket

**Comment by helendallas** [comment]
Download request working. New ticket created to automatic logging
