### ISSUE TITLE
Correct Metadata for Odonata Map records

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2478]
Here is the correct metadata from Rene

Author(s) | Underhill L
Year | 2021 - **this should be updated automatically depending on the date of the update**
Source | OdonataMap Virtual Museum, FitzPatrick Institute of   African Ornithology, University of Cape Town
Reference category | Database

URL for Source:   http://vmus.adu.org.za/?vm=OdonataMAP

**Comment by helendallas** [comment]
It is currently shown as

![image](https://user-images.githubusercontent.com/45286876/105483994-559a2980-5cb3-11eb-9070-bc732ef4faff.png)

**Comment by dimasciput** [comment]
@helendallas at the moment we can't add author and year in database reference.

**Comment by helendallas** [comment]
@dimasciput Okay, I understand, then don't worry about this given the amount of time it will take. Please can you just correct the 
Source | OdonataMap Virtual Museum, Fitz Patrick Institute of African Ornithology, University of Cape Town

And close the ticket

**Comment by dimasciput** [comment]
will be fixed on live
