### ISSUE TITLE
Odonata Adult Master List

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2479]
Here is the Master List of Odonata Species to use in FBIS.

It includes the species names, origin and endemism categories, as well as some common names. These should be used, not the GBIF ones.

The BDI Link is also provided. This needs to be added to the Taxon dashboard.

[Master List of Adult Odonata_Final_fo FBIS 2021_01_22.xlsx](https://github.com/kartoza/django-bims/files/5854973/Master.List.of.Adult.Odonata_Final_fo.FBIS.2021_01_22.xlsx)

**Comment by dimasciput** [comment]
@helendallas please always use the correct header format, Common_name -> Common Name

**Comment by helendallas** [comment]
@dim Yes I know this is new functionality that is specific to Odonata Adults. This was discussed at the project start. Please can you set aside time for this soonest. It would be good to have the link when we go live with the Odonates

**Comment by helendallas** [comment]
@dimasciput Sorry

**Comment by helendallas** [comment]
Master list ingested to production, closing ticket.
