### ISSUE TITLE
Add BDI link to Odonata Adult Taxon Dashboards

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2480]
An extra link for adult odonate taxa is the BDI link in the Master list of Odonata Adults.

Is it possible to include this on the Taxon dashboard. Both overview dashboard and detailed dashboard.

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput just a heads up that it's 'DBI', not 'BDI' - Dragonfly Biotic Index.
I have changed it in the title of this ticket.

**Comment by helendallas** [comment]
@jeremyshelton Not thats incorrect. It stands for:Biodiversity Development Institute (BDI) with a link to info on each species. 
http://thebdi.org/2020/02/13/smoky-spreadwing-lestes-virgatus/

It is NOT the Bioditc Dragonfly index.

**Comment by jeremyshelton** [comment]
Ah OK got it. Haha - that's confusing :)

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton it's possible, but this is a new feature request, and it will take some time.

**Comment by helendallas** [comment]
@dimasciput  Yes I know this is new functionality that is specific to Odonata Adults. This was discussed at the project start. Please can you set aside time for this soonest. It would be good to have the link when we go live with the Odonates

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/106131847-c51d8680-6195-11eb-8f47-bfc5b1cc89c1.png)
@helendallas added in side panel and dashboard

**Comment by helendallas** [comment]
@dimasciput Excellent, thanks Dimas!
