### ISSUE TITLE
Use Master list of Odonate adults for origin, endemism

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2481]
The testing site does not have the correct endemism and origins for the species.

![image](https://user-images.githubusercontent.com/45286876/105483416-7f9f1c00-5cb2-11eb-890e-45e1a137de26.png)

**Comment by dimasciput** [comment]
Will be fixed in testing

**Comment by helendallas** [comment]
@dimasciput Endemism still not showing in FBIS production

![image](https://user-images.githubusercontent.com/45286876/106273016-a02f1f00-623a-11eb-8ae8-d91d9270eedc.png)

**Comment by dimasciput** [comment]
@helendallas please wait until the import is finished

**Comment by dimasciput** [comment]
This is fixed

**Comment by helendallas** [comment]
Seems fine, closing
