### ISSUE TITLE
IUCN Conservation status not populated for all and no link

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2482]
Please check that correct IUCN  conservation status is shown and link to IUCN is show. May be correct in live?

![image](https://user-images.githubusercontent.com/45286876/105483493-9ba2bd80-5cb2-11eb-8a83-a9a125baa7f9.png)

**Comment by helendallas** [comment]
@dimasciput 

Category showing but link still missing;
![image](https://user-images.githubusercontent.com/45286876/106273375-395e3580-623b-11eb-88e5-8e8ae16e81b8.png)

As per fish:
![image](https://user-images.githubusercontent.com/45286876/106273345-29deec80-623b-11eb-9877-3469abc09810.png)

**Comment by dimasciput** [comment]
Fixed in production 
![image](https://user-images.githubusercontent.com/1979569/108310312-bb5fcf80-71e5-11eb-88e7-a5d63491f42e.png)
