### ISSUE TITLE
Too many endemism categories 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2483]
Here is what is on testing:
![image](https://user-images.githubusercontent.com/45286876/105487831-62ba1700-5cb9-11eb-8ece-cc34b741c401.png)

also see #2418 

Should only include:

Micro-endemic level 2 
Micro-endemic level 1
Regional endemic level 2
Regional endemic level 1
National endemic
Widespread
Unknown

**Comment by dimasciput** [comment]
@helendallas yes this is because it the master list you have `Widespread (more than one Freshwater Ecoregion)` for odonata adults, but for other species it's just `Widespread`. Both of them are stored in the database, I will fix in the backend for now, but please in the future just use Widespread.

**Comment by helendallas** [comment]
@dimasciput I will fix in the Master list

**Comment by helendallas** [comment]
@dimasciput Categories correct but need order revised:

![image](https://user-images.githubusercontent.com/45286876/106274055-56dfcf00-623c-11eb-9f26-4fb698c71a44.png)

Should be :
Micro-endemic level 2
Micro-endemic level 1
Regional endemic level 2
Regional endemic level 1
National endemic
Widespread
Unknown

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/108301754-3bca0480-71d5-11eb-8754-b672e3ee5b01.png)

Fixed in production
