### ISSUE TITLE
Sampling method should be added for all VM OdonataMap records

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2485]
At the moment Sampling Method is blank, please can you change this to 

Sampling method | Photographic record

I have added Photographic record to Sampling methods in Admin

**Comment by helendallas** [comment]
@dimasciput 



![image](https://user-images.githubusercontent.com/45286876/106274553-20ef1a80-623d-11eb-8a25-524e2bed6388.png)

Please add space between Photographic Record - not PhotographicRecord (also there are two in the backend)
![image](https://user-images.githubusercontent.com/45286876/106274636-3bc18f00-623d-11eb-8ca1-295172a3f4e6.png)


Where does HumanObservation come from - should be Visual Observation

**Comment by dimasciput** [comment]
> Where does HumanObservation come from - should be Visual Observation

It's coming from the odonate database, should I rename it?

**Comment by helendallas** [comment]
@dimasciput Its fine to leave, just please add a space Human Observation if possible

Thanks

**Comment by dimasciput** [comment]
@helendallas added Human Observation, also duplicates has been cleaned up

**Comment by helendallas** [comment]
@dimasciput  please see ticket #2487

**Comment by helendallas** [comment]
@dimasciput Sampling method now visible in CSV, thanks, but still missing from:

https://freshwaterbiodiversity.org/site-visit/detail/63443/

![image](https://user-images.githubusercontent.com/45286876/108346314-e9deaa00-71e7-11eb-8ad6-6d9f864b3e45.png)


Is it possible to show here as well?

**Comment by dimasciput** [comment]
@helendallas that's weird, I'll check it tomorrow morning

**Comment by dimasciput** [comment]
@helendallas this is fixed

**Comment by dimasciput** [comment]
@helendallas this is fixed
