### ISSUE TITLE
why are there so many duplicate sampling methods in admin?

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2487]
Can we get rid of duplicate records, 

![image](https://user-images.githubusercontent.com/45286876/105491365-d7438480-5cbe-11eb-90f8-02bb3cbb24b6.png)

**Comment by helendallas** [comment]
@dimasciput Some duplicates removed but there were others that had lowercase first letter, which I have now made into uppercase. Please can you do another run to remove duplicates.

![image](https://user-images.githubusercontent.com/45286876/108321750-41bbe780-71cd-11eb-9219-4cc65e873893.png)

**Comment by dimasciput** [comment]
@helendallas I cleaned up the duplicates

**Comment by helendallas** [comment]
@dimasciput Thanks closing
