### ISSUE TITLE
CSV file for Odonata Map data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2488]
![image](https://user-images.githubusercontent.com/45286876/105493179-b4669f80-5cc1-11eb-9db6-c80ef3159397.png)

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Chlorolestes%20fasciatus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=33&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Some issues:**

basisOfRecord =  Sampling method = Photographic record (please add space between words)

RecordedBy in VM needs to become Collector/Owner in FBIS (so in this case Diedericks G)
In a way the Owner needs to be OdonataMap Virtual Museum and Collector needs to be Diedericks G
as 
![image](https://user-images.githubusercontent.com/45286876/105495131-7323bf00-5cc4-11eb-9628-11ed2eec8e99.png)

locality - there are extra letters e.g. b'farm Berlyn 506; 16.6 km N of Graskop'

Authors - should be Underhill L
Year - 2021 - this should be updated automatically depending on the date of the update
Source -  should be OdonataMap Virtual Museum, FitzPatrick Institute of African Ornithology, University of Cape Town (See ticket #2478 )

**Comment by dimasciput** [comment]
@helendallas author and year are not available for source reference database, I can add it but it will take half a day to a full day.

**Comment by helendallas** [comment]
@dimasciput Okay, no problem just include Source, as per ticket #2478 Dont worry to add it for now, just focus on correcting other issues highlighted above, thanks

**Comment by helendallas** [comment]
@dimasciput Still need to fix 

RecordedBy in VM needs to become Collector/Owner in FBIS (so in this case Diedericks G)
In a way the Owner needs to be OdonataMap Virtual Museum and Collector needs to be Diedericks G

At the moment Collector/owner are all given as OdonataMAP VM

**Comment by dimasciput** [comment]
@helendallas yes i haven't done this yet, it's still in progress. Please only test the review column.

**Comment by helendallas** [comment]
@dimasciput Sorry I misunderstood. I thought this would be fixed with ingestion into the live site, especially since this will be a regular ingestion of the same data

**Comment by dimasciput** [comment]
@helendallas I encountered some issues here with the collector name, it seems they don't have same format : 
- Sometimes it's firstname then last name : K.D.B, Dijkstra
- last name then first name : W&M Tarboton
- multiple names with no separator : Tarboton W&M Griesel, J&R
- multiple names with + as separator : Tarboton W. + Dijkstra, K.-D.B.
- multipel names with & as separator : Tarboton W&M & A Manson

So it's very hard for me to parse this string into correct user object. I can just make them as one user regardless of the format.
What do you think?

**Comment by helendallas** [comment]
@dimasciput Okay, tricky.

Do you mean bring in as they are regardless of format. That would be fine I think. Since the filter now is Owner only, and not collector, it wont make it messy

**Comment by dimasciput** [comment]
@helendallas okay cool, I'll update it right away

**Comment by dimasciput** [comment]
Hi @helendallas , regarding this request for csv

> @dimasciput Still need to fix
> 
> RecordedBy in VM needs to become Collector/Owner in FBIS (so in this case Diedericks G)
> In a way the Owner needs to be OdonataMap Virtual Museum and Collector needs to be Diedericks G
> 
> At the moment Collector/owner are all given as OdonataMAP VM

Should I put collector name in the collector/owner field? And where should I put the owner? Keep in mind that this will affect other modules download.

**Comment by helendallas** [comment]
@dimasciput If there is only one field Collector/Owner, then because of the messiness of the data, I suggest we just make it OdonataMAP VM, rather than each collector name.  

The user then needs to go to the VM record to see who collected the data......

If these were separate we could include both. 

Lets keep it simple for now. 

Does that makes sense.

**Comment by dimasciput** [comment]
@helendallas fixed in the site visit form 
![image](https://user-images.githubusercontent.com/1979569/108797235-4ca3bd00-75bd-11eb-8bb3-62285054ad93.png)

**Comment by helendallas** [comment]
@dimasciput Thanks, looks fine
