### ISSUE TITLE
Please change hover over text from Odonata to Odonate Adults

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2490]
![image](https://user-images.githubusercontent.com/45286876/105496646-6dc77400-5cc6-11eb-8662-dc20ef5baa2c.png)

Please revise hover text to read "Odonate Adults"

**Comment by dimasciput** [comment]
@helendallas updated in testing, will also applied on live when the import is done

**Comment by helendallas** [comment]
@dimasciput Sorry just checked and this is Ädults Odonata"- should be "**Odonate Adults**"
