### ISSUE TITLE
PLease add hover text to Overview dashboard module icons

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2491]
Please add hover text to all module icons. Same as Module

![image](https://user-images.githubusercontent.com/45286876/105496842-b0894c00-5cc6-11eb-8cf7-da67bbac415e.png)

Same as for 
![image](https://user-images.githubusercontent.com/45286876/105496901-c8f96680-5cc6-11eb-84d4-fff3673eccb2.png)

**Comment by dimasciput** [comment]
@helendallas added on testing
