### ISSUE TITLE
Enable Multiple module selection

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2492]
At the moment one can choose to see data by selecting a module (fish, invert, algae or odonata). And then you can click abiotic to only show sites with abiotic data.

It would be useful to be able to select more than one module to select sites that have, fish + inverts, or fish + algae, or indeed all modules.

Thought will need to be given to how to deal with sites that are very close to one another. 

![image](https://user-images.githubusercontent.com/45286876/105497564-b4699e00-5cc7-11eb-90fe-4694cbc63089.png)

**Comment by helendallas** [comment]
@dimasciput This does not appear to be working.  It is adding records rather than selecting sites that include fish + inverts + algae , so 

So if 10 sites had fish data, and of these 10 sites only 4 site also had Invert data , then only the 4 sites that had both fish and SASS data should be shown.

At the moment it is adding the 10 fish sites to the 4 invert sites and returning 14 sites (less if some are the same site), but I am sure you understand the issue). Please shout if unclear.

**Comment by dimasciput** [comment]
@helendallas this has been deployed to live site, please test there.

**Comment by helendallas** [comment]
Thanks @dimasciput Working nicely now
