### ISSUE TITLE
Adjust colour and position of dragonfly icon in search bar

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2494]
@dimasciput please add some space between dragonfly and fish icons. 
Also, please make sure it matches the colour scheme, and size, of the other icons.

<img width="384" alt="Screenshot 2021-01-25 at 12 13 07" src="https://user-images.githubusercontent.com/44292029/105692358-fe8c9280-5f06-11eb-84ef-988f589e0127.png">

**Comment by helendallas** [comment]
Please also see #2486

**Comment by dimasciput** [comment]
@jeremyshelton fixed on testing

**Comment by jeremyshelton** [comment]
Looks good. Thanks @dimasciput
