### ISSUE TITLE
I cannot edit the dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2498]
When I try to edit dashboard I get:
![image](https://user-images.githubusercontent.com/45286876/105853085-fa877000-5fed-11eb-8b51-68633d87ea0a.png)

![image](https://user-images.githubusercontent.com/45286876/105852950-cca22b80-5fed-11eb-9f03-442f712cb6e9.png)

**Comment by dimasciput** [comment]
@helendallas because you're not an admin anymore, I changed your role since you don't want to receive download requests from RBIS anymore.

**Comment by helendallas** [comment]
@dimasciput Okay, then please give me admin rights as I need this. I will set email to file RBIS requests in a folder. thanks

**Comment by dimasciput** [comment]
@helendallas ok done, please try again
