### ISSUE TITLE
GBIF data no longer clipped to SA boundary?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2503]
<img width="1439" alt="Screenshot 2021-02-01 at 12 35 37" src="https://user-images.githubusercontent.com/44292029/106447460-3016d800-648a-11eb-8259-7120139b88fb.png">

**Comment by dimasciput** [comment]
@jeremyshelton this is odonata data, I will remove all the records outside SA after the import is done

**Comment by jeremyshelton** [comment]
@dimasciput OK cool - no problem
