### ISSUE TITLE
Link to SASS dashboard not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2504]
https://freshwaterbiodiversity.org/sass/dashboard/undefined/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[18.042297363281246,-34.31848685867646],[18.657531738281246,-34.77997173591062],[18.915710449218746,-33.33282302850357],[17.948913574218746,-33.497888166852064],[18.042297363281246,-34.31848685867646]]

**Comment by helendallas** [comment]
Closing as no longer an issue
