### ISSUE TITLE
Cleaning up databases (reference category)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2511]
@dimasciput what is the easiest way to clean up the list of Databases (Reference category) on FBIS. There are some databases, like 'housing development' that need to be removed, and others need some format adjusting.

<img width="1232" alt="Screenshot 2021-02-11 at 10 38 42" src="https://user-images.githubusercontent.com/44292029/107616569-04001180-6c57-11eb-8076-4053ab2b514b.png">

@helendallas

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput Its is still messy and there are some strange options as well which are not in the Source Reference Database

![image](https://user-images.githubusercontent.com/45286876/114887059-623ca280-9e08-11eb-85ea-2ac418914b9d.png)

**Here are the databases in Source References**

![image](https://user-images.githubusercontent.com/45286876/114887234-8bf5c980-9e08-11eb-86ee-51e68463f43d.png)

**Comment by dimasciput** [comment]
Fixed, @helendallas please try again

**Comment by helendallas** [comment]
Thanks
