### ISSUE TITLE
Validating records

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2512]
@dimasciput a few issues in the record validation process. 

1. Filtering by owner not working
2. Is it possible to show more (or all?) records needing validation on the same screen, rather than having them on lots of different pages?

<img width="1166" alt="Screenshot 2021-02-11 at 10 46 46" src="https://user-images.githubusercontent.com/44292029/107616960-afa96180-6c57-11eb-969f-7160d116fb88.png">

**Comment by helendallas** [comment]
@dimasciput Where is this deployed and where can I test this ?
