### ISSUE TITLE
Odonata icon- colour still not correct

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2513]
@dimasciput 
Dragonfly icon is a different shade of grey to the other icons. 
It needs to be the same.

<img width="283" alt="Screenshot 2021-02-11 at 10 40 31" src="https://user-images.githubusercontent.com/44292029/107617495-b1bff000-6c58-11eb-99e0-05d264d419ef.png">

**Comment by dimasciput** [comment]
@jeremyshelton can you provide the icon with the same color? actually I edited it manually with photo editor.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas where is that icon from? If someone sends me an image file then I can edit it 👍

**Comment by helendallas** [comment]
@jeremyshelton This was from Rene (Les's team member). Here is the image. 

![Odonata Logo](https://user-images.githubusercontent.com/45286876/107643153-72a49580-6c7e-11eb-8f14-886e90abed1f.png)

**Comment by jeremyshelton** [comment]
@helendallas OK thanks
I'll get on it...

**Comment by jeremyshelton** [comment]
Ok @dimasciput , I have tried to match the colour with the others. 
Try these:

![dragonfly_light](https://user-images.githubusercontent.com/44292029/109921232-333cf800-7cc4-11eb-9100-5dac1bfe09b0.png)
![dragonfly_dark](https://user-images.githubusercontent.com/44292029/109921240-3637e880-7cc4-11eb-8920-917dffb840c0.png)

**Comment by dimasciput** [comment]
Updated
