### ISSUE TITLE
Graph spacing in fish detailed dashboard

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2515]
Native / Non-native species graph looks squashed. Should fill the entire panel?

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=["value,sa_provinces,Western%20Cape"]&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

<img width="913" alt="Screenshot 2021-02-12 at 08 59 05" src="https://user-images.githubusercontent.com/44292029/107739096-cc55a000-6d10-11eb-8573-86436facf5cf.png">

**Comment by dimasciput** [comment]
@jeremyshelton looks fine from my side, I tested with Chrome and Firefox. Try hard refresh.

**Comment by jeremyshelton** [comment]
@dimasciput 
OK, hard refresh sorted it out on Safari 👍
