### ISSUE TITLE
Reference duplicate in metadata table

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2516]
@dimasciput @helendallas 
FRC monitoring database should appear only once in metadata table?
Maybe it is showing twice because one has notes & one does not?

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[%22CR%22,%22EN%22]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

<img width="1283" alt="Screenshot 2021-02-12 at 09 34 19" src="https://user-images.githubusercontent.com/44292029/107741827-93202e80-6d16-11eb-9b1b-e9deb127acd4.png">

**Comment by helendallas** [comment]
Checked and not duplicated any more - closing ticket

![image](https://user-images.githubusercontent.com/45286876/114886473-d6c31180-9e07-11eb-9272-52a26e2632fb.png)
