### ISSUE TITLE
Please delete incorrect fish data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2523]
As we chatted about there are four studies that need to be removed data from FBIS production so that we can re-ingest the correct data.

Please can you delete the associated fish data for these study references:

Snaddon KD, Shelton JM, Frenzel P & Paxton BR | 2019 | The Freshwater Research Centre: Baseline Assessment   Report 1. | A Baseline Assessment for Freshwater   Biodiversity Conservation in the Riviersonderend Catchment, South Africa.   Report 1. River Health. | Published report

Nussey G, Van Vuren JHJ & Du Preez HH | 2000 | Water SA | Quantifying the annual fish harvest from   South Africa’s largest freshwater reservoir | Peer-reviewed scientific article

Reizenberg J | 2017 | University of Cape Town MSc Thesis | The thermal tolerances and preferences   of native fish in the Cape Floristic Region: towards understanding the effect   of climate change on native fish species. | Thesis

Reizenberg J, Bloy LE, Weyl OLF, Shelton JM &   Dallas HF | 2019 |   | Variation in thermal tolerances of   native freshwater fishes in South Africa’s Cape Fold ecoregion: examining the   east–west gradient in species’ sensitivity to climate warming | Peer-reviewed scientific article

The full excel file is attached 

@Aneri16 @jeremyshelton 
 Does the UUID in this deletion file match the UUID of the data on FBIS Production?

[SA fish data for FBIS v3__For deletion_17 Feb 2021.xlsx](https://github.com/kartoza/django-bims/files/6000953/SA.fish.data.for.FBIS.v3__For.deletion_17.Feb.2021.xlsx)

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 
Yes, the UUIDs match those for the records on production.

**Comment by jeremyshelton** [comment]
@helendallas should we make another ticket to request record deletion functionality from @dimasciput ?

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 

Yes, ultimately we need functionality to delete a record and or Site Visit. We can already delete a site.

But I am sure this is quite a task and will require significant time from Dimas,.

Thoughts DImas? 
Basically you would need to create the functionality that would have allowed FBIS Admin to delete the records specificed in this ticket.

**Comment by helendallas** [comment]
@dimasciput For now Dimas please can you manually delete these: Spreadsheet earlier in ticket.

Please can you delete the associated fish data for these study references:

Snaddon KD, Shelton JM, Frenzel P & Paxton BR | 2019 | The Freshwater Research Centre: Baseline Assessment Report 1. | A Baseline Assessment for Freshwater Biodiversity Conservation in the Riviersonderend Catchment, South Africa. Report 1. River Health. | Published report

Nussey G, Van Vuren JHJ & Du Preez HH | 2000 | Water SA | Quantifying the annual fish harvest from South Africa’s largest freshwater reservoir | Peer-reviewed scientific article

Reizenberg J | 2017 | University of Cape Town MSc Thesis | The thermal tolerances and preferences of native fish in the Cape Floristic Region: towards understanding the effect of climate change on native fish species. | Thesis

Reizenberg J, Bloy LE, Weyl OLF, Shelton JM & Dallas HF | 2019 |   | Variation in thermal tolerances of native freshwater fishes in South Africa’s Cape Fold ecoregion: examining the east–west gradient in species’ sensitivity to climate warming | Peer-reviewed scientific article.

The @jeremyshelton We can ingest the new data, happy to assist.

@dimasciput I am going to create a new ticket for the enhancement to delete a record and/or study reference

**Comment by jeremyshelton** [comment]
@dimasciput 
Let us know when you have deleted these records so that we can upload the correct versions.
Thank you

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton can you confirm that you want all records associated with these references to be deleted?

![image](https://user-images.githubusercontent.com/1979569/116502946-13e6d380-a8df-11eb-91e5-3cfcc2a9588d.png)

![image](https://user-images.githubusercontent.com/1979569/116502981-2bbe5780-a8df-11eb-98b4-e284bac32913.png)

![image](https://user-images.githubusercontent.com/1979569/116502996-37aa1980-a8df-11eb-9549-d8b29e69d428.png)

![image](https://user-images.githubusercontent.com/1979569/116503015-42fd4500-a8df-11eb-8ffd-117b5fea8d32.png)

**Comment by jeremyshelton** [comment]
@dimasciput yes that's correct.
We will then be uploading corrected data sets associated with some of these references.
Thanks

**Comment by dimasciput** [comment]
@jeremyshelton 
Removed : 

https://freshwaterbiodiversity.org/source-references/?&q=The%20Freshwater%20Research%20Centre%3A%20Baseline%20Assessment%20Report%201

https://freshwaterbiodiversity.org/source-references/?&q=Quantifying%20the%20annual%20fish%20harvest%20from%20South%20Africa%E2%80%99s%20largest

https://freshwaterbiodiversity.org/source-references/?&q=The%20thermal%20tolerances%20and%20preferences%20of%20native%20fish

https://freshwaterbiodiversity.org/source-references/?&q=Variation%20in%20thermal%20tolerances%20of%20native%20freshwater%20fishes

**Comment by jeremyshelton** [comment]
@dimasciput perfect. Thanks.
Is there an easy way for us to remove other incorrect data ourselves, or not?

**Comment by helendallas** [comment]
@jeremyshelton Is this sorted, if so please close the ticket

**Comment by jeremyshelton** [comment]
@helendallas yes the records have been deleted, but still wanted touch continue the conversation with @dimasciput to check the feasibility of adding a delete button so that we don't have to go through Kartoza every time. can start a new ticket for that if you prefer?

**Comment by helendallas** [comment]
@jeremyshelton 
I suggest a new ticket as this is a feature enhancement, thanks
