### ISSUE TITLE
Selected Adult odonate module returns invertebrate data as well

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2524]
If I select Adult Odonate module, I anticipate that only adult odonate data will be returned. At the moment other odonate invertebrate data is also returned.

![image](https://user-images.githubusercontent.com/45286876/108322565-48972a00-71ce-11eb-83c0-027c5bb8a0b7.png)

See metadata table below:

![image](https://user-images.githubusercontent.com/45286876/108322443-22718a00-71ce-11eb-8db5-4073fb50057a.png)

**Comment by dimasciput** [comment]
Updated in the live site
