### ISSUE TITLE
Please can you check Sort By Site Visit: and Sort by Occurrences

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2527]
The Site VIsit numbers are not working - numbers are occurrences; also please check occurrences.

![image](https://user-images.githubusercontent.com/45286876/108504825-2e894480-72bf-11eb-983e-85f73606748c.png)

![image](https://user-images.githubusercontent.com/45286876/108504942-5bd5f280-72bf-11eb-8221-f90f536ea85a.png)

![image](https://user-images.githubusercontent.com/45286876/108504984-6a240e80-72bf-11eb-8570-5232d52622db.png)

**Comment by dimasciput** [comment]
@helendallas which module is this?

**Comment by dimasciput** [comment]
@helendallas ok found it, only fish and invert. This is because the site visit is kind of new feature, so it hasn't been applied to old modules yet. Should be easy fix.

**Comment by dimasciput** [comment]
@helendallas currently updating the site visit from the background, it should be finished by tomorrow.

**Comment by helendallas** [comment]
@dimasciput still not sure this is working. Several occurrences = site visits, when data are SASS data, no module selected. PLease can you check

![image](https://user-images.githubusercontent.com/45286876/109814730-8452da80-7c37-11eb-83b5-89df0a144cd7.png)

**Comment by helendallas** [comment]
A site visit = Site Code + Sampling Date - it has always been this. There cannot be different visit with the same site and date. Unless they were done by different people. we need to clear this up.

@helendallas  agreed.

To me these are all the same site visit (because they have the same site code and date), but are served as 74 different site visits: https://freshwaterbiodiversity.org/site-visit/list/?taxon=&search=&siteId=33521&collector=&category=&yearFrom=2000&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,sa_provinces,Western%20Cape%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=21&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33521&orderBy=-total_survey&polygon=

So something has gone wrong, or am I missing something here?

Issue duplicated in ticket#2545

**Comment by dimasciput** [comment]
@helendallas I have fixed this, can you please check?

**Comment by helendallas** [comment]
Checked for all modules. Working fine now.
