### ISSUE TITLE
Deleting a SASS record - not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2533]
I tried to delete a SASS record - 

https://freshwaterbiodiversity.org/sass/view/4197/

![image](https://user-images.githubusercontent.com/45286876/109127955-a6d88580-7757-11eb-92fb-c0db1e4a0ce7.png)

But got an error message after hitting delete

![image](https://user-images.githubusercontent.com/45286876/109127785-78f34100-7757-11eb-91d0-ed5a52892ce4.png)

**Comment by helendallas** [comment]
@dim So I checked and this record was deleted, so the delete functionality is working, but one gets this message, so perhaps worth checking.

**Comment by dimasciput** [comment]
@helendallas will do.

**Comment by dimasciput** [comment]
error : http://sentry.kartoza.com/sentry/freshwaterbiodiversity/issues/2743/

**Comment by helendallas** [comment]
@dimasciput Tried again, working so closing ticket.

**Comment by dimasciput** [comment]
@helendallas please don't the error is reported from the system, I still need to check it.

**Comment by dimasciput** [comment]
Fixed
