### ISSUE TITLE
SASS dashboard label not visible

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2534]
![image](https://user-images.githubusercontent.com/45286876/109130987-01bfac00-775b-11eb-9f12-9fcee055d908.png)

![image](https://user-images.githubusercontent.com/45286876/109131128-303d8700-775b-11eb-9ae1-0710c0ad2594.png)

Please can you fix the SASS dashboard in Single Site and Multi-Site Overview panel

**Comment by dimasciput** [comment]
@helendallas sorry! should be fixed now
