### ISSUE TITLE
Report not available in dropdown list when adding SASS data

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2537]
When trying to complete the Source Reference info for SASS data that I have added, the Report that I want to reference is not available on the dropdown list even though it has been uploaded in Source References

![Source ref error](https://user-images.githubusercontent.com/55532903/110293994-f2145300-7ff7-11eb-84aa-6deacf2cc7eb.png)

**Comment by Aneri16** [comment]
@dimasciput have you had a chance to have a look yet?

**Comment by helendallas** [comment]
Closing ticket as resolved with updates to Source References
