### ISSUE TITLE
document orchestration and restore

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#254]
Configuration, deployment and restore of a BIMS instance needs to be documented. The restore part is especially important for disaster recovery.

Please point to where this is or if it's not in place yet, add it to https://docs.google.com/document/d/10al06N9yJaY6GcovCVhtHhzVQI0KQYQ6QEGaW0stfiQ/edit#

**Comment by dimasciput** [comment]
New document is here : https://docs.google.com/document/d/16_fvd602MjIWm_zIw_ta7pkSKcS6dRYVT8w9j9Td-L4

**Comment by dimasciput** [comment]
must check the document

**Comment by timlinux** [comment]
@dominicschaff could you take this one on since deploying ORBIS is fresh in your head?

**Comment by helendallas** [comment]
@dominicschaff @dimasciput @timlinux 

Has this been finalised? If so can we close the ticket?

**Comment by helendallas** [comment]
Closing ticket. Docs on new system.
