### ISSUE TITLE
Dashboard - endemism should only be category not description

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2542]
At the moment the overview shows the full description. We had a similar issue in FBIS and I recall it was because the master list had different descriptions. Only a problem on the overview dashboard

![image](https://user-images.githubusercontent.com/45286876/111147428-27d6b000-8593-11eb-8452-6dca03bccbfe.png)

I have edited them in Admin - Endemism, but changes not made

![image](https://user-images.githubusercontent.com/45286876/111147169-db8b7000-8592-11eb-980e-2bfd0f90ecb2.png)

Really NB that these get linked to taxon as discussed in our meeting of the 8 March. For FBIS and RBIS. 

I dont know how to fix this?

**Comment by helendallas** [comment]
@dimasciput Fixed by reingesting Amphibian Master list with correct endemism categories. Closing ticket

**Comment by helendallas** [comment]
@dimasciput I am reopening, as although it is fixed on the ovevrview for site and multisite, it is still wrong for Taxon. I am reingested master files with short endemism categories, so not sure why this is still there, or why still in BIMS admin-endemism

![image](https://user-images.githubusercontent.com/45286876/115386419-a4cff780-a1d9-11eb-9eb6-130ccd1d5db6.png)

**Comment by helendallas** [comment]
I edited the endemism categories and this has been corrected now. Closing ticket

**Comment by helendallas** [comment]
This is has come back :(
Please can you fix again

![image](https://user-images.githubusercontent.com/45286876/171813912-21344895-b0d9-4a99-9840-e235cf28fcf8.png)

**Comment by helendallas** [comment]
@dimasciput I have asked the RBIS team to upload the master lists again with the correct endemism names. I think the problem has come in that they used the description as well.

![image](https://user-images.githubusercontent.com/45286876/171822849-6aab3756-3b62-4296-a30b-fab0f8ff0fd3.png)

**Comment by helendallas** [comment]
@mmindje @Thacien1 

I think the endemism categories uploaded for the master lists are still being done incorrectly in terms of the endemism categories. You are meant to include the Endemism only not the description.

**Endemism**
Micro-endemic level 2
Micro-endemic level 1
Regional endemic level 2
Regional endemic level 1
National endemic
Subregional endemic
Widespread
Unknown

Please see here in the master list dropdown
[RBIS Master List of Taxa Template.xlsx](https://github.com/kartoza/django-bims/files/9274741/RBIS.Master.List.of.Taxa.Template.xlsx)

If you keep including the description as well then there are duplicates and it does not display correctly.
See here on the side panel

![image](https://user-images.githubusercontent.com/45286876/183242548-4388a15c-bca4-418f-bb7c-185f4dd5a55d.png)

**Comment by mmindje** [comment]
issue fixed with Dimas. TICKET TO BE CLOSED
