### ISSUE TITLE
Please add Odonate adults icon and summary to the home page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2543]
@dimasciput I think this can be inserted in between invertebrates and algae. 
I think a breakdown by endemism will be most informative for this module?
Also, I think 'Invertebrate' should be changed to 'Invertebrates'
Also see ticket #2513 

![Screenshot 2021-03-15 at 16 08 24](https://user-images.githubusercontent.com/44292029/111167161-7bec8f00-85a9-11eb-9beb-267d0325948e.png)

**Comment by dimasciput** [comment]
@jeremyshelton sure I'll add it, please don't mention "dimas", it should be "dimasciput" :) ( I've edited your ticket ). We don't want to notify other user.

**Comment by dimasciput** [comment]
Added @jeremyshelton

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - looks great!
