### ISSUE TITLE
CBAs not showing for Western Cape and Eastern Cape?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2544]
@NyakudyaA
@dimasciput 

The National CBA layer is not showing in the Western Cape and Eastern Cape Provinces. 
Any idea why that might be and if we can get them back up and running, as we are demonstrating the FBIS this week. 
Thanks

![National CBAs](https://user-images.githubusercontent.com/44292029/111176385-f6b9a800-85b1-11eb-82b3-c6315407c6ce.png)

@helendallas 
@timlinux

**Comment by NyakudyaA** [comment]
I will take a look in the morning

**Comment by NyakudyaA** [comment]
This has been fixed
![fixes](https://user-images.githubusercontent.com/2510900/111274706-02eb4700-863e-11eb-97a3-edb2b0ebd48f.png)

**Comment by jeremyshelton** [comment]
Good stuff - thanks @NyakudyaA
