### ISSUE TITLE
Site visits and site occurrences 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2545]
@dimasciput 
When filtering sites and sorting by site visits, sometimes the number of visits shown in the search result does not match that in the dashboard.

![Screenshot 2021-03-15 at 19 25 31](https://user-images.githubusercontent.com/44292029/111195697-3342cf00-85c5-11eb-9516-f4b2f2ca7a83.png)

In the case of the green site, FBIS says 74 visits, but the dashboard shows that the data are actually all from the same visit: https://freshwaterbiodiversity.org/site-visit/list/?taxon=&search=&siteId=33521&collector=&category=&yearFrom=2000&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33521&orderBy=-total_survey&polygon=

However, this is not the case for the second entry (site shown in green), where there are genuinely multiple site visits: https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=9909&collector=&category=&yearFrom=2001&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=-total_survey&polygon=

@helendallas @timlinux

**Comment by dimasciput** [comment]
@jeremyshelton 

In the case of the green site, FBIS says 74 visits, but the dashboard shows that the data are actually all from the same visit: https://freshwaterbiodiversity.org/site-visit/list/?taxon=&search=&siteId=33521&collector=&category=&yearFrom=2000&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33521&orderBy=-total_survey&polygon=

They are different visits with same date and site, I can combine them if you want.

**Comment by jeremyshelton** [comment]
OK @dimasciput maybe we need to re-look at our definition of site visit @helendallas ?
I think don't change anything for now & we can chat about this at our new catchup 👍

**Comment by helendallas** [comment]
A site visit = Site Code + Sampling Date - it has always been this. There cannot be different visit with the same site and date. Unless they were done by different people.  we need to clear this up.

**Comment by jeremyshelton** [comment]
@helendallas  agreed.

To me these are all the same site visit (because they have the same site code and date), but are served as 74 different site visits: https://freshwaterbiodiversity.org/site-visit/list/?taxon=&search=&siteId=33521&collector=&category=&yearFrom=2000&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,sa_provinces,Western%20Cape%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=21&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33521&orderBy=-total_survey&polygon=

So something has gone wrong, or am I missing something here?

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 
This is issue has already been ticketed in #2527 

So closing ticket. Please refer to #2527

**Comment by jeremyshelton** [comment]
OK thanks @helendallas
