### ISSUE TITLE
Common names not showing for fish

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2548]
@dimasciput 

Something has gone wrong with the common names again. 

Common names for fish are either absent of listed incorrectly as scientific names in both overview and detailed dashboard.

![Screenshot 2021-03-17 at 09 16 21](https://user-images.githubusercontent.com/44292029/111429693-021be900-8702-11eb-97f9-12539198ec07.png)
![Screenshot 2021-03-17 at 09 19 54](https://user-images.githubusercontent.com/44292029/111429694-021be900-8702-11eb-8d7c-3e6ba42a824e.png)

![Screenshot 2021-03-17 at 09 15 29](https://user-images.githubusercontent.com/44292029/111429683-fdefcb80-8701-11eb-83c2-5ae79717beed.png)

**Comment by dimasciput** [comment]
@jeremyshelton currently if there's no common name for the species, the dashboard displays canonical name instead. I just checked the site, and this species never has a common name.

**Comment by dimasciput** [comment]
@jeremyshelton but this will be fixed when we reingest the master fish data

**Comment by dimasciput** [comment]
Let's close this one since it's the same with https://github.com/kartoza/django-bims/issues/2280
