### ISSUE TITLE
Sign-up error

### ISSUE THREAD

**Issue by brendadaly3098** [kartoza/django-bims#2549]
**Describe the bug**
When signing up on the website https://freshwaterbiodiversity.org/ I get the following error: 500 - SERVER ERROR
We're unable to fulfill your request. Rest assured we have been notified and are looking into the issue. If the error continues, please file an issue in Github's issue tracker.

**To Reproduce**
1. Go to sign up button
2. Complete the form

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 86.0.1 (64-bit)
 - Device: laptop

**Comment by dimasciput** [comment]
Hi @brendadaly3098, thanks for the report.

We have fixed this issue, please try it again.

**Comment by brendadaly3098** [comment]
![image](https://user-images.githubusercontent.com/31683220/111443765-5dee6e00-8712-11eb-84f8-a7252fb1f229.png)

Now getting a 502 Bad Gateway error

**Comment by dimasciput** [comment]
@brendadaly3098 is this after you sign up?

**Comment by brendadaly3098** [comment]
That is correct

**Comment by brendadaly3098** [comment]
I tried again and the system said that this username was in use and I was then able to log into the website, thank you

**Comment by dimasciput** [comment]
@brendadaly3098 thanks, I have fixed this issue, but I think you have successfully signed up, so please just login instead. Or you can try signing up again if you want to test.
