### ISSUE TITLE
upload functionality in different apps?

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#255]
why do different BIMS upload functionalities appear to be in different apps? 

- BIMS has 'shapefile upload session' and 'shapefiles'
- Upload has 'upload files and uploads'

...clean up

**Comment by dimasciput** [comment]
The upload app is from geonode, I hid them in this PR : https://github.com/kartoza/django-bims/pull/509

**Comment by gubuntu** [comment]
We don't want to hide GeoNode upload functionality - LEDET GIS staff will be using it to upload GIS layers.
