### ISSUE TITLE
Some sites have the same FBIS Site Code

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2555]
Several sites have the same FBIS Site code  -this should be a unique code. The following have been picked up:

H6AMAN-00028
H6AMAN-00025
H6RIVI-00137
H6RIVI-00136
H6RIVI-00138
H6RIVI-00139

https://freshwaterbiodiversity.org/map/#search/H6AMAN-00028/taxon=&search=H6AMAN-00028&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

and 
https://freshwaterbiodiversity.org/map/#search/H6RIVI-00139/taxon=&search=H6RIVI-00139&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33514&polygon=

I suspect the duplicates are coming in with the OdonataMAP data, and a duplicate FBIS Site Code is being allocated.  

@dimasciput Please can you check this and set it that FBIS Site Codes are always unique

**Comment by helendallas** [comment]
@dimasciput Has this been deployed yet as there are still duplicates.

![image](https://user-images.githubusercontent.com/45286876/122345285-fbdb1a00-cf47-11eb-83e4-b01a44ed2bdb.png)

Have you ensured that when OdonataMap data is harvested that duplicate site codes are not created?

**Comment by dimasciput** [comment]
@helendallas please try it again

**Comment by helendallas** [comment]
@dimasciput Looks fine now thanks. 

Have you ensured that when OdonataMap data is harvested that duplicate site codes are not created?

Can I close?

**Comment by dimasciput** [comment]
@helendallas For odonata, the system will create a new site with a unique site code.

**Comment by dimasciput** [comment]
@helendallas yes I think we can close this.
