### ISSUE TITLE
SASS Number of Taxa is always 1 less on Overview dashboard, compared to SASS record

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2556]
@dimasciput Please can you check the following:

The number of Invert taxa is always one less on the overview dashboard (22):

![image](https://user-images.githubusercontent.com/45286876/111610863-7929ae00-87e4-11eb-9357-f9e4306a5644.png)

 https://freshwaterbiodiversity.org/map/#search/h6rivi-00137/taxon=&search=h6rivi-00137&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33511&polygon=

Correct in the detailed dashboard (23) and SASS record (23):
![image](https://user-images.githubusercontent.com/45286876/111610935-9199c880-87e4-11eb-8349-3e579ed8fca8.png)

![image](https://user-images.githubusercontent.com/45286876/111611006-a6765c00-87e4-11eb-86a3-0d871fca8b35.png)

https://freshwaterbiodiversity.org/sass/dashboard/33511/?taxon=&search=h6rivi-00137&siteId=33511&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33511&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@helendallas this is fixed, but I think the site code has been changed so you can't use the old url.
