### ISSUE TITLE
Austroglanididae in Invertebrates - check on taxon uploads

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2558]
A fish family 

Chordata | Actinopterygii | Siluriformes | **Austroglanididae**

is in the Invertebrate Taxon Management????  This is a fish species.

![image](https://user-images.githubusercontent.com/45286876/111621840-1e4a8380-87f1-11eb-8ebd-a5706e4d5509.png)

![image](https://user-images.githubusercontent.com/45286876/111621682-f1966c00-87f0-11eb-9fa7-436459ab4e67.png)

**Comment by helendallas** [comment]
@dimasciput So I found two records where the data have been incorrectly assigned to a taxon. Austroglanididae is actually not even an invert taxon.  They were ingested as Data Combined Completed 2020_02_21.
Here is the data:

![image](https://user-images.githubusercontent.com/45286876/114859007-770a3d80-9dea-11eb-9e28-e78c32179e71.png)

Here is the xls  file with UUID for each record.

[Austroglanididae records FBIS.xlsx](https://github.com/kartoza/django-bims/files/6317420/Austroglanididae.records.FBIS.xlsx)

The original data file ingested had the following UUIDs and Taxon names.  I used the UUID from the CSV to find in the original ingestion file  SA Invertebrate Data for FBISv3_11 May 2020.xlsx:

61e262e1-c662-4b9f-b326-7962751e8234 as Diptera | Tipulidae
6d719d30-cf56-4974-9f4c-0d61a3ffa7d4 as Trichoptera | Leptoceridae

It seems so strange I would appreciate you seeing why this has happened? and how it can be fixed.

**Comment by helendallas** [comment]
@dimasciput Please can you investigate why these taxa were incorrectly assigned when ingested.  It is easy to fix, but better to work out why it happened in the first place. as it many be more widespread, which will be a concern.

**Comment by helendallas** [comment]
@dimasciput Please can you update me on this ticket

**Comment by dimasciput** [comment]
@helendallas I updated all occurrences to correct species for Austroglanididae. I'm not really sure the cause of this, but probably it was old bug that has been fixed.
