### ISSUE TITLE
Taxon Management - add filter functionality for rank

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2559]
At the moment it is not easy to filter taxa, which when one has > 3000 becomes very difficult.

Are you able to add the filter option above the sort for the columns now in the Taxon Management?

Especially for Taxon (already there), but add for Rank

![image](https://user-images.githubusercontent.com/45286876/111623114-a2513b00-87f2-11eb-8e94-7f100575694e.png)

**Comment by helendallas** [comment]
Essentially it would be good to be able to see taxa hierarchically, so when one needs to see Hydropsychidae, one would then select:

Rank: filter for Order = Trichoptera, then one sees all the families in the order Trichoptera.
RanK: filter for Family = Hydropsychidae, then one sees all the genera and species in the family Trichoptera.

Similar to the backend Taxa:

![image](https://user-images.githubusercontent.com/45286876/113278521-4f8f7d00-92e2-11eb-8c76-fb4139e0d4f6.png)

Is this an option?

**Comment by dimasciput** [comment]
Hi @helendallas I have added rank and other filters to taxa management view, please test it. 
![image](https://user-images.githubusercontent.com/1979569/115683231-6f194300-a380-11eb-85ca-122eb4752ac6.png)

**Comment by dimasciput** [comment]
It's only on freshwaterbiodiversity.org for now

**Comment by helendallas** [comment]
@dimasciput Thanks. These are good, but what I really need is a way to hierarchically select taxa so that they can be checked.
So if I applied a filter Order: I would then see a drop down list of orders available, and then I could select one, and then see all the taxa underneath that order. 

Select Filter = Ephemeroptera: Then see all families,, genera and species in Order Ephemeroptera.

Not sure if this is possible?

**Comment by dimasciput** [comment]
@helendallas It is possible, but much more complicated than what I have added. Will come back to this ticket again later.

**Comment by helendallas** [comment]
@dimasciput No problem, lets leave for now.

**Comment by dimasciput** [comment]
Hi @helendallas , what do you think of this?

https://user-images.githubusercontent.com/1979569/121300864-9670a300-c921-11eb-84fd-2ad361d722d8.mp4

**Comment by helendallas** [comment]
@dimasciput 
Fantastic, just what we need, thanks SO much!

**Comment by dimasciput** [comment]
@helendallas ok I will try to deploy it today, still in testing phase.

**Comment by helendallas** [comment]
@dimasciput Not sure if this is working for Order level...spinning:
https://freshwaterbiodiversity.org/taxa-management/?&ranks=&origins=&endemism=&cons_status=&parent=2431

and family
https://freshwaterbiodiversity.org/taxa-management/?&ranks=&origins=&endemism=&cons_status=&parent=599

Also we need a "Clear"

**Comment by dimasciput** [comment]
@helendallas you need to select the module first, I will hide the filter when the module is not selected.

**Comment by helendallas** [comment]
@dimasciput Got it thanks, working now :)
