### ISSUE TITLE
Source references  - managing duplicates

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2560]
@dimasciput At the moment it is possible to update unpublished data when duplicates are present, and then give it the same name, and then delete the reference with no records.

Please clarify how one does this for databases and published reports, theses

see duplicates below which each have records.
![image](https://user-images.githubusercontent.com/45286876/111748637-7210a780-8899-11eb-87d7-b1327d49b6a2.png)

Also Databases does not work at the moment
![image](https://user-images.githubusercontent.com/45286876/111748918-bef47e00-8899-11eb-85bd-e9e7da5343ac.png)

And author filter not working

**Comment by dimasciput** [comment]
@helendallas 
It's working but there is a bug that I haven't fixed it yet. The workaround for now:
- go to the source reference page from the menu: https://freshwaterbiodiversity.org/source-references/
- then click database.

**Comment by dimasciput** [comment]
@helendallas 
> And author filter not working

Same with above sorry.

**Comment by dimasciput** [comment]
> Please clarify how one does this for databases and published reports, theses

Yes it's much complicated for these cases, because they have some data/document attached to them. 
Can you create a feature request ticket for this? Thanks

**Comment by helendallas** [comment]
Issue for reports and database created in separate ticket #2562 . So closing ticket.
