### ISSUE TITLE
Upload Taxonomic data Issues experienced on RBIS Production

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2568]
The following issues were experienced when I tried to upload taxonomic data to RBIS Production:

So I added master list – three taxa did not get uploaded, even though two are existing families on GBIF **(Elmidae and Scirtidae)** – I have added url in the error file. 

_Error message is: 'SUPERFAMILY' is not in list_

[Invert master error file 2021_03_24.xlsx](https://github.com/kartoza/django-bims/files/6197259/Invert.master.error.file.2021_03_24.xlsx)

The third taxon Ampullariidae were left out completely, and not given in error file either.

I tried to add Ampullariidae, Scirtidae and Elmidae, so I can import data file.  But when I tried to add Scirtidae, it finds it on GBIF

![image](https://user-images.githubusercontent.com/45286876/112312378-6bc26700-8caf-11eb-817f-bc918508d812.png)

But then when I click ADD, it doesn’t add it……

Is the reason that I cant add Scirtidae because the taxon is already included with Helodidae - correct scientific name for Helodidae is Scirtidae.

In FBIS both Helodidae and Scirtidae are included.

Scirtidae is the accepted names, Helodidae in the synonym.

![image](https://user-images.githubusercontent.com/45286876/112312421-77ae2900-8caf-11eb-9d84-cf8db4547aa2.png)

also: Please can you also check why extra incorrect common names are being added:

![image](https://user-images.githubusercontent.com/45286876/112312498-88f73580-8caf-11eb-958b-576c260ce4d5.png)
![image](https://user-images.githubusercontent.com/45286876/112312508-8bf22600-8caf-11eb-8620-dc6d1fa721c6.png)

Or incorrect ones:
![image](https://user-images.githubusercontent.com/45286876/112312543-944a6100-8caf-11eb-961d-aa5517fcf8a4.png)

**Comment by dimasciput** [comment]
@helendallas I have removed all the taxa, and then reupload it, and it looks good now. Please test it.

**Comment by helendallas** [comment]
@dimasciput Thanks, all looks fine now.
