### ISSUE TITLE
Upload Occurrence Data - experiences on RBIS production

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2569]
I tried to upload the occurrence data file but nothing uploaded and I got the following error message:

**column bims_biologicalcollectionrecord.category does not exist**

Error file attached:
[Error file Upload occurrence data Invertebrates 02021_03_24.xlsx](https://github.com/kartoza/django-bims/files/6197324/Error.file.Upload.occurrence.data.Invertebrates.02021_03_24.xlsx)

Here is the original data file that I tried to upload:

[RBIS_Macroinvertebrate.final.Data.file.24March.2021.xlsx](https://github.com/kartoza/django-bims/files/6197330/RBIS_Macroinvertebrate.final.Data.file.24March.2021.xlsx)

**Comment by dimasciput** [comment]
@helendallas this is fixed, please try again.

**Comment by helendallas** [comment]
@dimasciput Success, thanks!
