### ISSUE TITLE
Source References - peer-reviewed scientific article without a DOI

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2570]
Sometimes a Peer-reviewed scientific article does not have a DOI, but rather a URL, or is a PDF. 

At the moment one cannot add a url or pdf to this reference category.

![image](https://user-images.githubusercontent.com/45286876/112315922-49cae380-8cb3-11eb-9db4-058e61150135.png)

Here is the url:
https://www.salamandra-journal.com/index.php/home/contents/2020-vol-56/1958-mindje-m-l-tumushimire-u-sinsch

I tried adding this to DOI or Source,, but they don't work, and now I cant delete from DOI

![image](https://user-images.githubusercontent.com/45286876/112317467-c0b4ac00-8cb4-11eb-9a8f-3384dcfd112d.png)

**Comment by helendallas** [comment]
@dimasciput Working on testing, thanks. Please roll out to live on **FBIS and RBIS**

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
This is looking good on live now, @helendallas 
Closing ticket.

**Comment by helendallas** [comment]
@dimasciput This needs to be rolled out to RBIS please
