### ISSUE TITLE
Source References - we need to be able to change the Reference Category

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2571]
At the moment it is not possible to change the reference category on the Source References. This is an enhancement that would be very useful, for e.g. the thesis below has been incorrectly classified as a peer-reviewed scientific article.

![image](https://user-images.githubusercontent.com/45286876/112320718-f3ac6f00-8cb7-11eb-82ec-164c15bc3e0c.png)

Another case is where data are added as unpublished data, and then they a consolidated in a published report.

**Comment by timlinux** [comment]
Only applies for cases where unpublished becomes published (don't need to deal with the reverse case or e.g. database ->  publication). Will need to copy the unpublished data over to a new published data model and then update all references.

**Comment by helendallas** [comment]
@dimasciput I am going to close this as I dont expect it will come up much, especially for FBIS
