### ISSUE TITLE
Fish taxon with incorrect species linked via GBIF and IUCN

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2574]
@dimasciput 
Cheilobarbus capensis has the wrong species linked via GBIF and IUCN.
Please add the correct species link to these two platforms.

**Comment by helendallas** [comment]
See ticket #2541 as well

**Comment by dimasciput** [comment]
@jeremyshelton I updated the iucn link with data from https://www.fishbase.se/summary/Pseudobarbus-capensis.html, but I couldn't find the gbif link for this species.

**Comment by dimasciput** [comment]
@jeremyshelton is this the correct link https://www.gbif.org/species/9561740 ?

**Comment by helendallas** [comment]
@jeremyshelton Cheilobarbus capensis is not in GBIF.  Does this seem right? has the name changed???
Can you go through the fish species and check the GBIF links for all.

![image](https://user-images.githubusercontent.com/45286876/114855434-41fbec00-9de6-11eb-8bdf-ee7363621cb2.png)

I have deleted the GBIF key in the Taxon management:
![image](https://user-images.githubusercontent.com/45286876/114855759-9606d080-9de6-11eb-8e14-7f8e994822f9.png)

**Comment by jeremyshelton** [comment]
@helendallas yes the Berg Breede Whitefish is a particularly confusing one. 
On the IUCN Red list and GBIF it is Pseudobarbus capensis.
Paul Skelton pointed out that the most recent paper allocates to to the name Cheilobarbus capensis, hence what is currently on FBIS. 
However, perhaps we should revert to P. capensis on FBIS so that we can link with the GBIF data? Tricky one, but that's my feeling for now...

**Comment by jeremyshelton** [comment]
@helendallas here is the paper redescrbiing C. capensis FYI: https://www.researchgate.net/publication/323524940_The_identity_of_Barbus_capensis_Smith_1841_and_the_generic_status_of_southern_African_tetraploid_cyprinids_Teleostei_Cyprinidae

**Comment by jeremyshelton** [comment]
Same goes for the Sawfin, which is Pseudobarbus Serra on GBIF and IUCN, but latest correct name is actually Cheilobarbus Serra. 
Both Cheilobarbus names exist on Fishbase.
Hard to know which names to give them on FBIS...

**Comment by jeremyshelton** [comment]
Finally, another problem child is Pseudobarbus burchelli - the former name of the widespread Breede redfin, but now allocated to the CR Barrydale redfin. The widespread one is temporarily called Pseudobarbus sp. nov. 'breede' but doesn't exist on GBIF/IUCN. 
So, at present, lots of the data on FBIS that are meant to be assigned to Pseudobarbus sp. nov. 'breede' currently fall under Pseudobarbus burchelli which is incorrect. 
@helendallas I think we need to have a session to decide the best way forward with these problems cases.

**Comment by helendallas** [comment]
@jeremyshelton Agreed, a session is needed. Perhaps in preparation for that chat, can you find out from Willem Coetzer or Albert Chakona how SAIAB deal with data published to GBIF whose taxonomy has changed. And how correct taxonomy can be promoted to GBIF.

**Comment by jeremyshelton** [comment]
@Helen Dallas ***@***.***> agreed. Will do.

[image: best sig.png]
www.frcsa.org.za

**Comment by helendallas** [comment]
@jeremyshelton I am going to close this ticket as you have reassigned GBIF ids. The discussion above is larger than this ticket.
