### ISSUE TITLE
Fish taxon on FBIS but not present in fish module in taxon management? 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2575]
Schilbe depressirostris - present in FBIS searches on the map, but not present in fish module in taxon management? 
It is supposed to be in the master list.
I tried to add it as a new taxon, but it didn't seem to work - please explain how to add a new taxon via taxon management?

**Comment by helendallas** [comment]
@jeremyshelton 
I have created a instructional video to show how to do this. I will share this with you via we transfer. Please add it to our youtube.

I will also be creating documentation for this through the RBIS project but am waiting on finalisation of the Taxon Management module.

**Comment by helendallas** [comment]
Closing ticket

**Comment by helendallas** [comment]
@dimasciput Can you please check that the species created is linked to the records that were on FBIS before I added the taxon.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton https://freshwaterbiodiversity.org/taxa-management/?&selected=1&taxon=Schilbe%20depressirostris%20

You can see the total records now

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - yes, I can now see the taxon and its records. 
I see that in taxon management it says there are 219 records, but when searched on the map there are only 52 records (FBIS + GBIF). 
Any idea why there is a mismatch?
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton I fixed it, can you try it again? You need to select both fbis and gbif or you can click the search icon from the taxon management page :
![image](https://user-images.githubusercontent.com/1979569/114814651-cf3b4280-9dde-11eb-9725-2317e14a9e22.png)

**Comment by jeremyshelton** [comment]
@dimasciput 
OK - looks good.
Thanks.
