### ISSUE TITLE
Upload and manage taxon images

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2580]
Add ability to upload and manage our own taxon images

**Comment by helendallas** [comment]
@dimasciput I have tested this and it works, closing ticket

**Comment by dimasciput** [comment]
@helendallas this is still in progress, not deployed yet.

**Comment by helendallas** [comment]
@dimasciput okay. I think I am getting confused with logos

![image](https://user-images.githubusercontent.com/45286876/115522022-06509e80-a28c-11eb-82f6-d21b8fd8fa2d.png)
 Is this adding images of taxa to RBIS or FBIS? Where will they sit?

**Comment by dimasciput** [comment]
@helendallas these are images for specific taxon/species, it will show up in the taxon side panel/dashboard
![image](https://user-images.githubusercontent.com/1979569/115529579-382e2900-a2bd-11eb-9fcf-894bf53ae7ae.png)

So they (RBIS), wanted the ability for users to upload their own species images. Currently all images are from gbif.

**Comment by helendallas** [comment]
This works well to add an image, but after deleting the image using the clear button, it got stuck on "fetching". Please check if this is working correctly before we close the ticket.

![image](https://user-images.githubusercontent.com/45286876/144019359-6a85904a-61ac-4ba4-813c-012729fc3f5e.png)
