### ISSUE TITLE
Site Ownership is not working properly

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2587]
It seems that whoever is logged in is the site owner.

Janette is owner when she is logged in, 
![image](https://user-images.githubusercontent.com/45286876/114365503-ce09db80-9b7a-11eb-8217-d629733729ee.png)

and I am site owner when I am logged in.
![image](https://user-images.githubusercontent.com/45286876/114365546-deba5180-9b7a-11eb-8616-deb97874e72f.png)

Same with Aneri

Please can you investigate what is happening.

**Comment by helendallas** [comment]
@dimasciput Both Janette and I checked the same site but the Owner is now blank:


https://freshwaterbiodiversity.org/location-site-form/update/?id=27750


![image](https://user-images.githubusercontent.com/45286876/114849540-268de280-9de0-11eb-8ca1-5101e829c987.png)

**Comment by dimasciput** [comment]
@helendallas I just checked, and this site doesn't have an owner. Should I just set the owner to FBIS admin?

**Comment by helendallas** [comment]
@dimasciput I am the owner, I can change my side. Is this not a more widespread issue?

**Comment by helendallas** [comment]
@dimasciput I will get Janette and Aneri to check a few others. Hopefully it is an isolated case.

**Comment by helendallas** [comment]
@dimasciput Ok, seems to be working for all sites now, checked by my colleagues, so closing ticket, thanks
