### ISSUE TITLE
Site code generator error

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2588]
>  When trying to add Kates new sites to BIMS and click on generate site code it comes up without the first 4 letters of the river name and won’t let us add it or move forward.

![image](https://user-images.githubusercontent.com/1979569/114805711-aa8a9f00-9dcd-11eb-9320-7e67c988589a.png)

**Comment by helendallas** [comment]
@dimasciput Closing ticket as this seems to be working fine
