### ISSUE TITLE
We need functionality to delete a record, site visit and or study reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2592]
At the moment we are reliant on Dimas to delete data from FBIS. This is not sustainable.

The administrators need to be able to delete data - ideally at several levels, namely:

an individual occurrence record
all occurrence records associated with a SiteVisit
All occurrence records and associated data for a Study Reference

Happy to discuss further @dimasciput @jeremyshelton to see what is feasible. Not urget, but should be built into admin fucntionality for long term sustainability

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas please try it on testing. For now only staff or admin user can delete the records.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput  

I think it is fine for this functionality to be restricted to staff and admin for now.

I was able to successfully delete a record on testing. I deleted am erroneous P. phlegethon record from site N4WITR-00041.

I did however notice a few issues when doing so:

<img width="1193" alt="Screenshot 2021-07-09 at 06 34 07" src="https://user-images.githubusercontent.com/44292029/125028624-a8607580-e088-11eb-9743-6834f27f8833.png">

1. Deleting one record from a site seemed to change the other record at that site from 'validated' to 'unvalidated'
2. After deleting a record, the work flow then leads through the rest of the data upload steps, which is not necessary. Can we please rather end the date a record work flow on deletion of the record confirmation?
3. Something has gone wrong with site owner: on testing the owner for this site is showing as 'Dimas Ciputra, Jim Cambray' but on live it is correctly showing as showing as 'E.R. Swartz'. Also, the Collector/owner institution is incorrectly showing as 'CapeNature' on live. The correct institution is 'South African Institute for Aquatic Biodiversity' as per the ingested data sheet. 


Perhaps point 3 is a separate issue and should be addressed in a separate ticket @helendallas ?

**Comment by dimasciput** [comment]
> Something has gone wrong with site owner: on testing the owner for this site is showing as 'Dimas Ciputra, Jim Cambray' but on live it is correctly showing as showing as 'E.R. Swartz'. Also, the Collector/owner institution is incorrectly showing as 'CapeNature' on live. The correct institution is 'South African Institute for Aquatic Biodiversity' as per the ingested data sheet.

Those are site visit's owner not site's owner, and don't worry about that since it's not mirror to live site. Probably I changed it when I did some testing.

**Comment by dimasciput** [comment]
> After deleting a record, the work flow then leads through the rest of the data upload steps, which is not necessary. Can we please rather end the date a record work flow on deletion of the record confirmation?

Yes because it's basically updating a site visit, that's why you still need to go to other pages. I can come up with better solution, but also I need more time. So probably for now hopefully this is an acceptable solution?

**Comment by dimasciput** [comment]
> Deleting one record from a site seemed to change the other record at that site from 'validated' to 'unvalidated'

Let me fix this one

**Comment by jeremyshelton** [comment]
**Yes because it's basically updating a site visit, that's why you still need to go to other pages. I can come up with better solution, but also I need more time. So probably for now hopefully this is an acceptable solution?**

@dimasciput OK that's fine.

**Comment by jeremyshelton** [comment]
@dimasciput OK that sounds good. We can streamline the process later if it needs more time. 
-------
Still not sure why collector/owner institution is incorrectly showing as 'CapeNature' on live site for these records. The correct institution is 'South African Institute for Aquatic Biodiversity' as per the ingested data spreadsheet - do you think we need to correct this manually for this study, or perhaps indicative of a broader issue? @helendallas ?

**Comment by dimasciput** [comment]
@jeremyshelton I fixed issue number 1, please test again

About issue number 3, maybe we can open another ticket since it's not related to this issue.

**Comment by jeremyshelton** [comment]
@dimasciput issue 1 fix is working fine now. Ready to deploy to live site. 

Will create a new ticket for issue 3.

Thank you.

**Comment by jeremyshelton** [comment]
@dimas let us know when this is ready for testing in live.

**Comment by jeremyshelton** [comment]
@dimasciput please roll this out to Live site as soon as possible.
Thank you.

**Comment by jeremyshelton** [comment]
Part 2 and 3 of this ticket have been transferred to new ticket: #2710
