### ISSUE TITLE
Is it possible to delete old user names in Author  - Source Reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2593]
At the moment there are a lot of names that are not still Authors in the Source Reference:

![image](https://user-images.githubusercontent.com/45286876/114885165-b21a6a00-9e06-11eb-9099-363a8debdd30.png)

These users are on the People/Users in BIMS, but they must be from old ingestions of data where authors formating from incorrect or it was changed.
![image](https://user-images.githubusercontent.com/45286876/114884673-3ddfc680-9e06-11eb-906c-7a6d99c7f5e3.png)

**Comment by dimasciput** [comment]
Hi @helendallas , so what do you want me to do here? Delete old authors?

**Comment by helendallas** [comment]
@dimasciput Not to worry, I will check and fix using merg users. Safe this way.
