### ISSUE TITLE
Geocontext data not being generated for new sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2598]
A colleague added this SASS data 4 weeks ago.

No geocontex data yet
![image](https://user-images.githubusercontent.com/45286876/114990333-b42d0900-9e98-11eb-99cc-352886041fdd.png)

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/116495377-fad52700-a8cc-11eb-8d79-4e973390c958.png)

it shows up now

**Comment by helendallas** [comment]
@dimasciput Province still not showing
![image](https://user-images.githubusercontent.com/45286876/118090187-7fde3700-b3c9-11eb-85d2-5500ce38431d.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Please can you follow up with Dimas and check why the geocontext data is not all coming in for this site. e.g province

**Comment by helendallas** [comment]
@Fanevanjanahary please can you check River Management Unit. These should be available for the Western Cape

https://freshwaterbiodiversity.org/sass/dashboard/33518/?taxon=&search=&siteId=33518&collector=%5B%22Kate%20Snaddon%22%5D&category=&yearFrom=2020&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33518&orderBy=name&polygon=

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Still not working on SASS dashboard.

![image](https://user-images.githubusercontent.com/45286876/123099295-584fa500-d432-11eb-85df-a0cc316648e1.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Please respond to this ticket. The River Management unit is still not being populated for this example site.
@dimasciput please can you also check and revert.

**Comment by Fanevanjanahary** [comment]
Hi @helendallas we have already fixed This ticket 

https://testing.healthyrivers.kartoza.com/sass/dashboard/27291/?taxon=&search=&siteId=27291&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&page=21

![image](https://user-images.githubusercontent.com/12623986/126440088-6df7c75a-8ea1-43f3-b486-0d2f315c4c46.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Thanks but has it been rolled out to FBIS live yet?????  Its hard to keep track of what has been fixed on testing and when it is rolled out.  Please can you check and revert. @dimasciput

**Comment by dimasciput** [comment]
@helendallas not yet, but please test on testing first. I will try to deploy to live site tomorrow.
