### ISSUE TITLE
Site generator not working correctly

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2599]
There is still an issue with this.  Several sites have been misallocated the Secondary catchment. Should be H6 not G1

![image](https://user-images.githubusercontent.com/45286876/114991008-695fc100-9e99-11eb-94b2-7ff298143678.png)

**Comment by dimasciput** [comment]
@helendallas I have fixed this, please try it again

**Comment by helendallas** [comment]
Seems to be fine, closing
