### ISSUE TITLE
Logos on Taxon Management not looking good

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2601]
Please can you correct the logos on the taxon management, so they do not have a white border.

![image](https://user-images.githubusercontent.com/45286876/115358684-329de980-a1be-11eb-817b-b21c4cb21c1d.png)

Please can you then share all the FBIS and RBIS logos with this ticket so that we can have a place to keep them for future instances. 

It would also be nice to have a solid bird, so that it works with the others.

**Comment by helendallas** [comment]
@dimasciput I have asked Jeremy if he can edit them to have a transparent background, then I can re-upload log for each module. He is going to see what he can do.
@jeremyshelton

**Comment by dimasciput** [comment]
Awesome thanks!

**Comment by helendallas** [comment]
@jeremyshelton Thanks for sending new logos through. Closing ticket
