### ISSUE TITLE
There is no way to add a Site in RBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2603]
At the moment the only way to add a new site and or data is by the admin - upload Occurrence data.

We need to discuss with the RBIS team if they want users to be able to add Sites and or data themselves, and if yes, then we need to make this functionality visible.

@timlinux  Please can you make a note to discuss at our next session.

**Comment by timlinux** [comment]
On FBIS:

![image](https://user-images.githubusercontent.com/178003/124098889-dfb19f80-da54-11eb-95a5-c338e27bf7fa.png)

**Comment by helendallas** [comment]
Closing this ticket as duplicated in #2978
