### ISSUE TITLE
Delete a record button?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2612]
@dimasciput what would it take to add a record delete button so that we don't have to go through Kartoza every time we need to delete an incorrect record?

@helendallas

**Comment by helendallas** [comment]
Closing this ticket as it is already captured in #2592

**Comment by helendallas** [comment]
@dimasciput As per our chat today, please can you add the functionality to delete a record for now, so that we can do this ourselves for our rogue records.

**Comment by dimasciput** [comment]
this is done in testing

**Comment by jeremyshelton** [comment]
@dimasciput from what I can tell this has been done in testing, but not yet rolled out to live? Or am I missing something?

Testing:
<img width="1242" alt="Screenshot 2021-07-16 at 15 53 00" src="https://user-images.githubusercontent.com/44292029/125959023-f6cda0fb-acf1-450b-9b0a-6f2007b29842.png">

Live:
<img width="1164" alt="Screenshot 2021-07-16 at 15 53 07" src="https://user-images.githubusercontent.com/44292029/125959068-474ee76c-ab4f-4ce8-8859-78d2029b9021.png">

**Comment by jeremyshelton** [comment]
Then
