### ISSUE TITLE
Create upload form for water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2614]
@timlinux @dimasciput Here is an outline of first point of discussion for today.

FBIS Phase 2 includes the development of a thermal module. A priority for this module is the development of upload forms for adding water temperature data. These data may be recorded at variable logging intervals, including 0.5, 1, 2 or 3 hours. 

We need to be able to **Add water temperature data** for both an existing site, and for a new site.

![image](https://user-images.githubusercontent.com/45286876/118768953-e529a080-b87f-11eb-9b70-55c5a664b75e.png)

### **Steps:**

- Select an existing site or add a new site (exactly as before)
- Click “Add water temperature data”
- Select dates of water temperature logging period: **Start date**, **End data** (If this can be automatically picked up from the data then that would also be fine). **Tim: Lets parse the file rather**
- Is your data for a one year period? Yes/No (If this can be automatically picked up from the data then that would also be fine) - **Tim: We use the start date to initiate the annual period and in the thermagraph we only consider the 12 month period following the start date. We will not discard any date that exceeds the user data.**
- For sub-daily water temperature data: Select Logging interval: Dropdown comprising: 0.5h, 1h, 2h, 3h, where h = hours (If this can be automatically picked up from the data then that would also be fine) **Tim: Lets let the user define it.**
- Please also include option to add daily data (minimum, mean and maximum) - given the neat graphs Dimas showed us. **Tim: Can be implemented in bullet above as a 24hr interval**
- Browse to csv? or excel? file of water temperature data and upload data **Tim: CSV for v1**

Then following the uploading of water temperature data, the user also needs to be given the option to **upload air temperature data** for the same site.  The same process for uploading water temperature data can be followed. **Tim: Note that we should do upserts so that new imports overwrite existing data if timestamps match.**

**Issues for consideration and discussion:**

**1. Quality control** - it would be good to check the quality of data as follows:

- gaps in the data
- very high temperatures which may be air temp measurements - perhaps show mean, minimum and maximum values and if the max is higher than??? the user is notified. 
- date format time stamp is correct
- correct number of records per logging interval, 48 for 0.5h, 24 for 1h, 12 for 2h, 8 for 3 h
- Start and end times need to be fixed: start : 00:00; end: 23:00 (or 23:30 for 0.5h interval) - this is necessary for calculation of metrics and can be automated.

**Tim: Validation should happen on upload and prevent the whole dataset being uploaded if there are any issues in it.**

The user should receive an error file similar to in Taxon Management uploads, with the error indicated and then they need to go and check.  Data should only be uploaded once all errors are corrected (unlike taxa where only the records with errors are excluded). The data is time series.

**2. Duration of the logging period.**
The standard period, and one required to generate Indicators of Thermal Alteration (ITA)  and a Thermograph (see ticket) is 1 year of data. However sometimes users have data for shorter (6 months) or longer (5 years) time periods.  

It would be good to allow these data to be uploaded as well. I have added the question:
Is your data for a one year period? Yes/No
This will allow one to divert to the ITA and thermograph metrics calculations.

How do we show the other data?

**Further comment:** It would be good to allow water temperature data of any duration to be uploaded and then for sites where there is more than one year of data, allow the user to select the start date for generating Indicators of Thermal Alteration (ITA)  and a Thermograph.

Note: I will write a user guide to assist users in how to prepare and upload water temperature data.

**Comment by helendallas** [comment]
Here is a file of hourly water temperature data for more than one year.

[WT_G2EERS-JONKE_10_11_2008 to 13_02_2011.xlsx](https://github.com/kartoza/django-bims/files/6724780/WT_G2EERS-JONKE_10_11_2008.to.13_02_2011.xlsx)

Here is a file of 30 minute water temperature data for more than one year.

[DuToits Feb 2021 WT Data.xlsx](https://github.com/kartoza/django-bims/files/6724897/DuToits.Feb.2021.WT.Data.xlsx)

Here is a file of 3-hourly water temperature data for one year.

[EC_Cata River 01_08_2013 to 31_07_2014 3 hourly.xlsx](https://github.com/kartoza/django-bims/files/6724923/EC_Cata.River.01_08_2013.to.31_07_2014.3.hourly.xlsx)


Here is a file of daily (minimum, mean and maximum) water temperature data

[Mutale Bridge Daily data.xlsx](https://github.com/kartoza/django-bims/files/6724866/Mutale.Bridge.Daily.data.xlsx)

**Comment by dimasciput** [comment]
@helendallas it means there is a bug, can you share your file please?

**Comment by dimasciput** [comment]
nevermind, I got it

**Comment by dimasciput** [comment]
@helendallas I managed to upload all the data : 
![image](https://user-images.githubusercontent.com/1979569/139518442-dbd24f96-edb7-4e6a-b02c-77e42642387d.png)

**Comment by helendallas** [comment]
@dimasciput I checked another upload data set

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=8110&thermalModule=True

But get error message when viewing the dashboard??

![image](https://user-images.githubusercontent.com/45286876/144577046-772f6848-c6ac-4340-9012-d3274452645c.png)
 On testing

**Comment by dimasciput** [comment]
@helendallas thanks

@Fanevanjanahary can you check the issue https://testing.healthyrivers.kartoza.com/water-temperature/8110/?taxon=&search=&siteId=8110&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=8110&orderBy=name&polygon=&thermalModule=True

**Comment by dimasciput** [comment]
@helendallas should be fixed now

**Comment by helendallas** [comment]
Thanks, not all values added? maybe needs more time?
https://testing.healthyrivers.kartoza.com/water-temperature/8110/?taxon=&search=&siteId=8110&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=8110&orderBy=name&polygon=&thermalModule=True

**Comment by dimasciput** [comment]
@helendallas everything has been added from the file, so this dashboard is actually per year, you can select the year in the header.

**Comment by dimasciput** [comment]
@helendallas hmm maybe instead of year, we can add start time and end time in the dashboard. But that's different issue.

**Comment by helendallas** [comment]
ok so at the moment I can add data of any length time series, and it will just show what has been added? I will do some more checking if your answer is yes.

Really excited to see this visualised!

Lets leave as is for now re year/start time etc.

**Comment by dimasciput** [comment]
> ok so at the moment I can add data of any length time series, and it will just show what has been added? I will do some more checking if your answer is yes.


@helendallas yes, the dashboard will only show data annually for now, from January to December. Then you can change the year here : 
![image](https://user-images.githubusercontent.com/1979569/144585414-c281e7a2-57b0-40ec-9e1a-d324857fa459.png)

**Comment by helendallas** [comment]
Trying to upload longer time series data....but still processing....guess it may take a while

https://testing.healthyrivers.kartoza.com/water-temperature-form/?siteId=8110

**Comment by helendallas** [comment]
@dimasciput Please can you check through this ticket and see if the Validation issues have been addressed adequately or if we need to create a new ticket for developing later.

**Comment by helendallas** [comment]
@dimasciput I am battling to upload data to testing. Says "processing Data" > 10 minutes, think there is a bug

![image](https://user-images.githubusercontent.com/45286876/145177351-3f203108-b885-4acf-aec4-107432952aa2.png)

Here is the excel file
[WT_G1BERG-DRIEH_03_03_2010 to 04_02_2011.xlsx](https://github.com/kartoza/django-bims/files/7674649/WT_G1BERG-DRIEH_03_03_2010.to.04_02_2011.xlsx)

**Comment by dimasciput** [comment]
@helendallas it's because you have the header incorrect, it should be "Water temperature" not "Temp". I added error message for that here https://github.com/kartoza/django-bims/pull/2923. Will deploy it later to testing.

**Comment by dimasciput** [comment]
updated in testing

**Comment by helendallas** [comment]
Thanks, noted
