### ISSUE TITLE
Automate calculation of Indicators of Thermal Alteration (ITA) and thermograph

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2615]
@timlinux @dimasciput 

Here is an outline of the requirements for the automation of the ITAs = thermal metrics. Nick has created an excel spreadsheet that runs using several macros sequentially to transform the sub-daily water temperature data to Metrics and a Thermograph.

**Steps:**
The sub-daily water temperature data is converted to daily data -**Metrics_calcs** tab
Generate thermal metrics data - **Output metrics** tab
Generate thermograph - **Thermograph** tab

**Example of presentation of thermal metric (ITA) data** 
 
![image](https://user-images.githubusercontent.com/45286876/118780671-933b4780-b88c-11eb-89e4-536af170102f.png)

Additional: Timing - Julian day

**Comment by helendallas** [comment]
The procedure is described in the word document and the excel file for the thermal metrics and thermograph will be emailed as Github do not support macro enabled xls files.

[Metrics spreadsheet notes.docx](https://github.com/kartoza/django-bims/files/6725386/Metrics.spreadsheet.notes.docx)

**Comment by helendallas** [comment]
The Metrics spreadsheet Blank, with macros, and the example with hourly data are shared via the dropbox folder.
FRC_Kartoza Thermal Module/ Thermal metrics and thermograph

**Comment by dimasciput** [comment]
Hi @helendallas , regarding the threshold, are they calculated based on geomorphological zone value? 
![image](https://user-images.githubusercontent.com/1979569/144000068-57e5c3dc-d210-4a39-9397-7b42f982c8a0.png)

What if the site doesn't have geomorphological zone value? Which one should we use?

**Comment by helendallas** [comment]
@dimasciput The zones Upper and lower are based on the spatial layer: Thermal framework - Thermal Zone: Upper, Lower; see ticket #2835 

We dont use geomorpohological zone. The user needs to be able to update it they have. Shout if unclear

**Comment by dimasciput** [comment]
> The user needs to be able to update it they have.

@helendallas to update the default threshold or threshold for specific site? 

If the site doesn't have Thermal Zone value, should it display blank for this table?

**Comment by helendallas** [comment]
There should be no blank thermal zones as far as I can tell looking at the dbf file.
![image](https://user-images.githubusercontent.com/45286876/144006333-fb4fe011-67a8-4864-9434-bafd73f86f98.png)

**Comment by dimasciput** [comment]
@helendallas and who can update this threshold? the owner of the site? or the owner of the temperature data?
Because it's pretty confusing in the user interface side. 
Can we just focus on the threshold from the thermal zone for now?

**Comment by helendallas** [comment]
The owner of the temperature data needs to be able to update if possible. We can leave for now and use the threshold from the thermal zone for now, and then when I am adding data if it becomes a problem then we will need to add functionality for the owner of the temp data to change. This could happen at the time of uploading the temp data?

**Comment by dimasciput** [comment]
@helendallas ok cool, let's do that. I'll create a ticket for the functionality to update the threshold data.

**Comment by helendallas** [comment]
@dimasciput Sounds like a plan, thanks

**Comment by dimasciput** [comment]
@helendallas I have added this calculation, and deployed to testing. Sorry it took a while, because I have to make sure the calculation is correct, I have tested with the data from example, and it looks good. 
For now you can access this dashboard from admin page in the location site section, and search the site that has water temperature data. :
https://testing.healthyrivers.kartoza.com/admin/bims/locationsite/?q=G2EERS-JONKE
![image](https://user-images.githubusercontent.com/1979569/144037362-c5992f2e-4c2c-4c51-972c-dba2fcbf481f.png)

And just click the open dashboard link.

**Comment by helendallas** [comment]
Thanks @dimasciput That's awesome! I can imagine all the challengin calculations behind the scenes!

**Comment by helendallas** [comment]
@dimasciput Please let me know when this is rolled out to live. Then I can close the ticket.
