### ISSUE TITLE
Align Admin function tools and dropdowns for RBIS and FBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2621]
At the moment FBIS and RBIS have some shared admin functionality, but these are not served uniformly across the sites, and some are missing:

FBIS
![image](https://user-images.githubusercontent.com/45286876/119120038-19da5b00-ba2c-11eb-8d0a-b7191668d9ca.png)

RBIS
![image](https://user-images.githubusercontent.com/45286876/119120088-2a8ad100-ba2c-11eb-9bf4-c5379d408d80.png)

Please can you add / move the following in FBIS to the drop-down admin functionality:

- Download requests
- Validate records (remove from top menu bar and include as a dropdown)
- Update records (remove from top menu bar and include as a dropdown) - not sure if this is also for a non-admin user, if it is then add to User section

![image](https://user-images.githubusercontent.com/45286876/119120518-a9800980-ba2c-11eb-8b35-dee390e8556c.png)

- Summary report

**Comment by dimasciput** [comment]
@helendallas please check on testing

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary 

Looking good, thanks. A few questions or comments:

- Please can you move **Download requests** below **Validate records**
- **Update records** has disappeared - I think this should be added to **User - below Profile and Site Visits**  @dimasciput ? does this make sense. Is this to allow a user quick access to their records? Not sure how it works or if still needed.
- Backups don't work but I am assuming this is because it is testing site

Also where is it sensible to add a Docs to FBIS - as in RBIS - perhaps best left for when we create the mothership with shared wagtail resources.

**Comment by dimasciput** [comment]
@helendallas we don't need `Update records` anymore, since user can update their record from site visit page.

**Comment by helendallas** [comment]
@dimasciput Thanks, that is what I suspected :)

**Comment by helendallas** [comment]
@Fanevanjanahary 

Please confirm when the order has been revised as follows:

- Please can you move Download requests below Validate records

And rolled out to production site on FBIS, thanks

**Comment by helendallas** [comment]
closing ticket, fine in FBIS
