### ISSUE TITLE
Allow sharing of wagtail documents across BIMS instances

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2624]
At the moment one has to write separate admin documentation in FBIS and RBIS.

It would be good to allow sharing of documents (which need to be selected) so that admin docs are created once and are shared and or transferable to other instances.  

We chatted about this before @timlinux  and @dimasciput but I couldn't find a ticket, so have created this one.

All of these in RBIS, and more to come, ideally need to be available in FBIS.

![image](https://user-images.githubusercontent.com/45286876/119647658-d4010680-be20-11eb-9ccb-b7d4d2349778.png)

**Comment by timlinux** [comment]
We will create the 'mothership site' for this rather.

@amyburness can you plan some time for this. We will do this pro-bono so please do not log against FRC. Please give an estimate of how many days and then work with Dimas to get your design deployed. Looking for wagtail theme galleries would be great.

**Comment by timlinux** [comment]
Incorporate in #2627 please

**Comment by amyburness** [comment]
@timlinux 

I will have a look I have seen some nice clean and simple themes that could work for this. 
I will assign some time to this and #2627 next week.

**Comment by helendallas** [comment]
@timlinux @dimasciput 

This has now been created but I do not have access to edit docs. We need this actioned via a chat session please

**Comment by helendallas** [comment]
Notes from TIM re BIMS mothership notes etc.

So I add write permissions for you and Jeremy.

Just accept here:

https://github.com/kartoza/bims-website/invitations

Then go to the folders with the content:

https://github.com/kartoza/bims-website/tree/main/docs/src


Click on any of the files with .md extension then click the pencil to edit:

 

Editing the content uses exactly the same system as editing a ticket so you should hopefully feel at home there. You can use the preview option to see how your changes look:


 

Once you are done editing, scroll down the page and write a short message explaining your changes (1) then choose commit directly to the main branch (2) the commit (3)
 

Normally we would actually ask you to make a branch and a pull request, but use option (2) for  now to keep things simple.

Your changes should appear on the live site within a minute or so.

I do plan to make the site pretty etc. and we are going to add all our training materials for developers there. Do you mind if we also migrate all the content from the user manual there? I have a way that does a fairly decent job of making PDF's from the site so we can have a single point of truth for all the docs then.

I added the same notes above on the README on the landing page in case you need them again in the future:

https://github.com/kartoza/bims-website/

**Comment by helendallas** [comment]
@timlinux Please can you update us on the progress of the documentation portal for the BIMS instances

**Comment by helendallas** [comment]
Closing ticket as wagtail no longer being used. Link here:

https://kartoza.github.io/bims-website/
