### ISSUE TITLE
Common names not being included when Taxon Master list is uploaded

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2625]
@dimasciput Please can you check why common names are not always added to the taxon. For e.g. Amphibian module in RBIS, included common names, but they are not in Taxon management.

I just reran the uplaoding of amphibians master list csv, and no common names are being added.

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 

I am a bit unclear how common names are being dealt with across all the taxa.

We know that for some, eg fish in FBIS, that GBIF names are not always correct and so it is better to use our master list, or update in taxon management. This is easy since there are < 140 species.

However for other taxa, e.g. invertebrates, which have so many more taxa it will be easier to rely on GBIF.

Is the workflow - use GBIF common names, but allow admin to update in taxon management? @dimasciput Please cna you clarify and check that it is working for FBIS and RBIS. thanks

**Comment by jeremyshelton** [comment]
@helendallas 
The workflow that you have outlines is the way that I understand it. 
Like you say, for fish we have manually adjusted all common names to overwrite the incorrect GBIF ones. 
@dimasciput

**Comment by dimasciput** [comment]
Hi @helendallas @jeremyshelton it should work now in the testing, here's how to test it : 
- Download taxa file in taxon management 
- Change or add new name in common name column
- Upload the file in taxa uploader

**Comment by helendallas** [comment]
@dimasciput I did this but the new name is added, and does not replace the old one - I changed the following common names in the Fish module

Taxon | Scientific name and authority | Common Name
Actinopterygii | Actinopterygii | Unknown
Ambassis natalensis | Ambassis natalensis Gilchrist & Thompson, 1908 | **Helen One**
Amphilius uranoscopus | Amphilius uranoscopus (Pfeffer, 1889) | **Jeremy one**

They are all retained

![image](https://user-images.githubusercontent.com/45286876/123092639-fd667f80-d42a-11eb-821e-a536c5f371bd.png)

**Comment by dimasciput** [comment]
@helendallas please try again in testing, should be fixed now. I also fixed the utf-8 csv.

**Comment by dimasciput** [comment]
@jeremyshelton please test this in testing, thanks

**Comment by jeremyshelton** [comment]
@dimasciput do I first need to delete the taxon before uploading the corrected taxon?
Is the Taxa uploader the same thing as using the 'Add a Taxon' button?

<img width="1159" alt="Screenshot 2021-07-16 at 16 32 27" src="https://user-images.githubusercontent.com/44292029/125964426-8cfa83ef-3f13-4725-a089-34899bed1760.png">

Perhaps it's best for @helendallas and I to work through this when she's back next week....

**Comment by helendallas** [comment]
@jeremyshelton This is on the testing site right?
 
We really need the testing to be a mirror image of live site @dimasciput Is it possible to action this please? Soonest.

@jeremyshelton I will have a session with you on the work flow for managing taxa. Have you read my notes? Its written for Rwanda but applicable to FBIS as well.

[Managing taxa in Taxon Management.pdf](https://github.com/kartoza/django-bims/files/6847657/Managing.taxa.in.Taxon.Management.pdf)

**Comment by jeremyshelton** [comment]
@helendallas **This is on the testing site right?** yes - in testing

**We really need the testing to be a mirror image of live site @dimasciput Is it possible to action this please? Soonest.**
@helendallas please see ticket #2679 

**@jeremyshelton I will have a session with you on the work flow for managing taxa. Have you read my notes? Its written for Rwanda but applicable to FBIS as well.**
That will be good. Will also look through the PDF 👍

**Comment by helendallas** [comment]
@dimasciput CSV download in taxon management is now not working on testing.

**Comment by dimasciput** [comment]
@helendallas this is fixed and deployed to live.

**Comment by helendallas** [comment]
@dimasciput PLease can you deploy to RBIS as well - that goes for all the recent fixes please

**Comment by helendallas** [comment]
@dimasciput Has this been rolled out to RBIS. I uploaded amphibian master list again that includes common names and they are not visible in Taxon Management. Please check and revert.

**Comment by dimasciput** [comment]
@helendallas not yet unfortunately, I'll deploy it tomorrow morning

**Comment by helendallas** [comment]
@dimasciput ok thanks

**Comment by helendallas** [comment]
@dimasciput Checking if this has been deployed yet to RBIS? From August.

**Comment by helendallas** [comment]
@dimasciput This is not working, common names are not uploading even though they are in the csv file

**Comment by helendallas** [comment]
@mmindje Have you checked if this is working, i.e. are common names being added when they are uploaded. I see that noe have been added for the amphibians. Were they included in the csv file you uploaded?

![image](https://user-images.githubusercontent.com/45286876/158595855-32293e5b-abcd-4e10-b20f-3d031061a415.png)

**Comment by helendallas** [comment]
Helen emailed @mmindje and thacien to get latest master lists, so that I can check if this has been resolved.

**Comment by mmindje** [comment]
Hello @helendallas Yes, see attached the masterlists uploaded
[Newly-Cleaned_Master-list-data-file-_-Plants-xlsx 22Feb2022.xls](https://github.com/kartoza/django-bims/files/8541989/Newly-Cleaned_Master-list-data-file-_-Plants-xlsx.22Feb2022.xls)

[Cleaned- Master-list-NewPlandata-file-_-Plants-xlsx-28Feb2022-xlsx.xlsx](https://github.com/kartoza/django-bims/files/8541999/Cleaned-.Master-list-NewPlandata-file-_-Plants-xlsx-28Feb2022-xlsx.xlsx)



[Amphibians- Masterlist-final_Feb 2022.xlsx](https://github.com/kartoza/django-bims/files/8542015/Amphibians-.Masterlist-final_Feb.2022.xlsx)

[Final RBIS Master List of Taxa Template 30032022.xlsx](https://github.com/kartoza/django-bims/files/8542018/Final.RBIS.Master.List.of.Taxa.Template.30032022.xlsx)


[RBIS-Master-List-of-WaterBirds-Template-Refined-xlsx.xls](https://github.com/kartoza/django-bims/files/8542032/RBIS-Master-List-of-WaterBirds-Template-Refined-xlsx.xls)


[New macroinvertebrate MasterList 2022.xlsx](https://github.com/kartoza/django-bims/files/8542037/New.macroinvertebrate.
MasterList.2022.xlsx)

[RBIS.Master.List.of.Taxa_Odonates_updated_BDMT_21._Feb 2022.csv](https://github.com/kartoza/django-bims/files/8542039/RBIS.Master.List.of.Taxa_Odonates_updated_BDMT_21._Feb.2022.csv)

**Comment by helendallas** [comment]
I am closing this ticket as I have checked the uploading on testing site and it works. **Common Name** needs to have a capital N
