### ISSUE TITLE
We need a website for the upstream BIMS project

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2627]
![BIMS Home Page Wireframe](https://user-images.githubusercontent.com/178003/119803520-6f54b300-bed7-11eb-8886-e7dd85f1d825.png)

We could build the site using wagtail and then centralise all the general docs in one place

**Comment by timlinux** [comment]
See also #2624 @amyburness and include that in your planning

**Comment by amyburness** [comment]
This has evolved into a documentation site for BIMS made by @Jeremy-Prior

**Comment by Jeremy-Prior** [comment]
Documentation site available here: https://kartoza.github.io/bims-website/
