### ISSUE TITLE
Add extra features to BIMS Admin Page People Users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2634]
**### Please can you do the following to allow users to be better managed:**

**New columns:**
- Add new column "Organization Name" to show the organization of the user
- Add new column "Role" to show the role of the user
- Add new column "Date joined"  to show the date the user signed up to FBIS
- Add new column "Last login"  to show the date the user last logged into FBIS

**New filters:**
- Add "Signed Up" as a filter
- Add "Organization Name" as a filter
- Add "Role" as a filter

**New sorting:**

- Add sort functionality to "Organization Name", "Role", "Signed Up", "Date joined", "Last login" and "Sass accredited status"" 

**CSV download:**

- Can you also allow all users to be downloaded as a csv file.

![image](https://user-images.githubusercontent.com/45286876/121149075-a2d1fe80-c842-11eb-8d62-5d13a5da1163.png)

**Comment by dimasciput** [comment]
@helendallas the sorting for 'Signed up' and 'Sass accredited status' is also going to take time to implement.

**Comment by helendallas** [comment]
@dimasciput **Signed up** is really what I need as I need to do some stats and graphs for the FBIS paper. Its the only way to know who signed up and when.

**Comment by dimasciput** [comment]
@helendallas the filter for "Signed up" is pretty easy, but the sorting is little bit complicated, let me deploy what I have been working on for this ticket.

**Comment by helendallas** [comment]
@dimasciput actually signed up = date joined right, so is it easier to just include date joined?

**Comment by helendallas** [comment]
@dimasciput sorry misread, sorting can also wait for now.

**Comment by dimasciput** [comment]
@helendallas please test it here https://freshwaterbiodiversity.org/admin/people/profile/?

**Comment by helendallas** [comment]
@dimasciput That's working nicely Dimas. I reckon thats fine for now. The stuff that the other functionality can wait. Thanks !

I have managed to copy and paste into excel so I can do the analyses

**Comment by helendallas** [comment]
If you create a filter for Signed Up then I wont need to be able to sort, so happy for you to exclude that.
