### ISSUE TITLE
 Add CSV download to BIMS Admin Page People Users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2639]
Please can you created the ability to download all users in a csv file, with columns expressed as:

- Username
- Email
- First name
- Surname
- Organization name
- Role
- Active
- Date joined
- Last login
- Sass accredited status
- Staff status

Ticket linked to #2634

**Comment by dimasciput** [comment]
Hi @helendallas I managed to write a function to download the users, I have deployed it to live site, please test it.


https://user-images.githubusercontent.com/1979569/121485828-c6d84000-c9fa-11eb-9586-be774a75f662.mov

**Comment by helendallas** [comment]
@dimasciput Thanks will check now. just a heads up, I am finding a number of duplicates

e.g.






<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/Helen%20Dallas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/Helen%20Dallas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>





Ruth-Mary_Fisher | Ruth-Mary_Fisher | rc.fisher20@gmail.com | Ruth-Mary | Fisher | South African National Parks | Researcher | May     20, 2021, 8:43 a.m. | May     20, 2021, 8:43 a.m.

Ruth-Mary_Fisher
May     20, 2021, 8:43 a.m.
Ruth-Mary_Fisher | rc.fisher20@gmail.com | Ruth-Mary | Fisher | South African National Parks | Researcher | May 20, 2021, 8:43 a.m.

**Comment by helendallas** [comment]
@dimasciput Works fine, I assume one has to do it page by page?

**Comment by dimasciput** [comment]
@helendallas check the video I shared, to download all of them click `Select all ... users`

**Comment by helendallas** [comment]
@dimasciput Got thanks, works well., also cant see duplicates anymore...
