### ISSUE TITLE
Incorrect occurrence data upload template

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2644]
The downloadable template for uploading occurrence data in the administration tab is incorrect for all modules. 
This also seems to prevent occurrence data uploads when using the correct template.

https://freshwaterbiodiversity.org/upload-collections/ 

@helendallas

**Comment by helendallas** [comment]
@jeremyshelton I will check these. One issue is they are slightly different for each module. I will create a new folder on our new project file to use for now

**Comment by helendallas** [comment]
@dimasciput Please can you show us where we have to put these templates in the backend , 

There will be one for each module

![image](https://user-images.githubusercontent.com/45286876/122158422-ed6c0000-ce6c-11eb-8eb8-f10979f53318.png)

**Comment by helendallas** [comment]
Fixed closing
