### ISSUE TITLE
Algal Taxon Master list

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2645]
The CSV file downloaded for algae has a **number of duplicate taxa** and does not have **Family** included in the taxonomic hierarchy.

We cannot validate the uploaded master list without being able to download the data.

Please see attached xls showing duplicates as extracted using the downlaod CSV button on FBIS Taxon Management

[FBIS extracted Algal master list 2021_06_15.xlsx](https://github.com/kartoza/django-bims/files/6655048/FBIS.extracted.Algal.master.list.2021_06_15.xlsx)

**Comment by helendallas** [comment]
And as per #2381 

Specifically:

    Family is missing
    Division is missing
    Growth form is missing

**Comment by helendallas** [comment]
In Taxon Management there are duplicates??????  Not sure why"?

Can I safely delete the ones with no records?
![image](https://user-images.githubusercontent.com/45286876/122051913-69bb0080-cde5-11eb-8eff-e61e0e774c6a.png)

I suspect duplicate records were added when I re-uploaded the new algal master list, but I understood the original taxon would be overwritten.  See dates

@dimasciput Please can you investigate what is happening.

**Comment by dimasciput** [comment]
I think this is because they have slightly different name, you can always merge the duplicates in the admin page. Can we close this one @helendallas ?
