### ISSUE TITLE
We need to be able to add new publications and reports in Source references

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2650]
Before we upload new occurrence data we need to be able to add reports as pdf in the Source Reference admin.

![image](https://user-images.githubusercontent.com/45286876/122359536-ec62cd80-cf55-11eb-9245-da80b68460a3.png)

I suspect this only applies to published reports that require a pdf to be uploaded. Then we insert the document link into the upload file in the column:

Document Upload Link
e.g http://freshwaterbiodiversity.org/documents/93

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary This is actually quite an urgent task as we cannot upload new data upload files until this has been added.

**Comment by helendallas** [comment]
As a work around @dimasciput We added documents using the link you provided.

Use this link:
https://freshwaterbiodiversity.org/documents/?limit=5&offset=0

I did notice that these documents are not yet in the Source References though, so not sure if you still need to pull them in. I just wanted to give you a heads up before you tackle this ticket. Thanks

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton hi, currently I'm busy working on this feature.
