### ISSUE TITLE
River names disappear when zoomed in

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2651]
When zooming in on the map, all river names disappear completely when zoomed in close to the finest river scale:

![Screenshot 2021-06-17 at 10 41 33](https://user-images.githubusercontent.com/44292029/122362796-b83cdc00-cf58-11eb-9dd5-a004e82aa1cb.png)

**Comment by timlinux** [comment]
Actually there are two scale zones that don't have names and then the labels come back on:

![fbis-river-blindspot](https://user-images.githubusercontent.com/178003/123243221-b768f480-d4da-11eb-83b3-d7cf86ea6db4.gif)

**Comment by NyakudyaA** [comment]
I will check them and fix

**Comment by NyakudyaA** [comment]
The layer name in question is `sa_rivers` coming from kartoza geoserver

**Comment by jeremyshelton** [comment]
@NyakudyaA @dimasciput 
From what I can tell there are no river names showing between the 2km and 5km zoom levels. 
This makes it confusing when navigating the map.
Is there an easy way to get the river names showing at this scale?

**Comment by NyakudyaA** [comment]
> @NyakudyaA @dimasciput
> From what I can tell there are no river names showing between the 2km and 5km zoom levels.
> This makes it confusing when navigating the map.
> Is there an easy way to get the river names showing at this scale?

@jeremyshelton I have assigned one of our interns to fix this.

**Comment by jeremyshelton** [comment]
Great.
Thanks @NyakudyaA

**Comment by dimasciput** [comment]
any updates on this @amyburness @NyakudyaA ?

**Comment by helendallas** [comment]
@amyburness Any ideas on this on?

**Comment by timlinux** [comment]
@amyburness can you try to make an updated version of the 1:50k rivers where you assign the closed 1:500k river name to each river segment if the 1:50k river name is missing?

**Comment by timlinux** [comment]
@amyburness can we set a time cap of four hours for you to resolve this? If you haven't come up with a workable solution by the end of that, leave a note here and I think we will abandon this task and wait for a decent national dataset.

**Comment by helendallas** [comment]
So for now we do not have a better rivers coverage or dataset. Until SANBI/DWS improve this layer we will need to live with this. I will label On hold until SANBI revert

**Comment by helendallas** [comment]
Closing as no action from SANBI
