### ISSUE TITLE
Conversion of air temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2665]
We need air temperature data from 973 stations to be converted from ASCII file format to spreadsheet format.
Then these are used to calculate an “average” mean temperature for each day of the year.

The details of the process and associated files are provided in the word document:

[Thermal Module_Notes on air temperature data.docx](https://github.com/kartoza/django-bims/files/6739159/Thermal.Module_Notes.on.air.temperature.data.docx)

The relevant file is in our shared folder:
FRC_Kartoza Thermal Module/Air temperature data

@timlinux @dimasciput  Please can you go through these and revert to Nick if you have any questions.

**Comment by timlinux** [comment]
@amyburness I am assigning this to you. I think it would be good to do it in QGIS using a model. Please review the requirements and the data and chat to me if you need inputs on how to approach this. Keep the project with the model around in case we want to tweak the process.

**Comment by Fanevanjanahary** [comment]
Hi, @helendallas please can you check if this data in step one is correct so I can continue the next step? 

the txt file: [0812567_W.txt](https://github.com/kartoza/django-bims/files/8122207/0812567_W.txt)

and the step one: [0812567_W.csv](https://github.com/kartoza/django-bims/files/8122205/0812567_W.csv)

**Comment by dimasciput** [comment]
@helendallas can you check the files from Faneva?

**Comment by helendallas** [comment]
@dimasciput @NickRivers-Moore already responded by email. He is not yet comfortable with github

Hi Faneva,

Just responding to the mail below from Helen.

I downloaded the text and csv files from the links below.

From my understanding:
•	The text file is the raw data;
•	The csv file is the first step in the conversion.  I confirm that this look correct (the example in 0008782.xlsx – third tab = data to use – is how it should look).  This all seems to be in order.

Next step, as per the thermal notes, it to take what is in the csv file and convert into a three column file (attached – AT_example), with a fourth column added as a calculation.

Please let me know if you need any more help.

[Thermal Module_Notes on air temperature data.docx](https://github.com/kartoza/django-bims/files/8131376/Thermal.Module_Notes.on.air.temperature.data.docx)
[0008782_W.xlsx](https://github.com/kartoza/django-bims/files/8131377/0008782_W.xlsx)
[AT_example.xlsx](https://github.com/kartoza/django-bims/files/8131378/AT_example.xlsx)

@Fanevanjanahary Please contact @NickRivers-Moore  if you have issues. Also on email please

**Comment by helendallas** [comment]
@Fanevanjanahary Please update me on progress. Has this been completed????

**Comment by Fanevanjanahary** [comment]
@helendallas, Nick said in his last email that the last step is correct, I will convert all the station's files and will send them to you. I've written a script on QGIS to convert the data here https://gist.github.com/Fanevanjanahary/5d6c7faf26d99174846d574e3fc32a2b if you maybe need it

**Comment by Fanevanjanahary** [comment]
@helendallas I've emailed you and Nick the link to download the data converted. Please let me know if you have any problems. Thank you

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput We have gone through this data and it is looking good. I will close the ticket.
