### ISSUE TITLE
RBIS Forest Cover

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2669]
@dimasciput can you check why the forest cover layer does not show up in the spatial filter group.

![image](https://user-images.githubusercontent.com/178003/124094276-8a738f00-da50-11eb-858d-4bf238a46742.png)

**Comment by dimasciput** [comment]
It is showing up now 
![image](https://user-images.githubusercontent.com/1979569/159878867-aea38143-5b32-44f1-9723-bbef12542dc7.png)
