### ISSUE TITLE
We need to review CHIRPS data for rainfall data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2670]
https://www.chc.ucsb.edu/data/chirps

Can we review this dataset in terms of its suitability (over Worldclim - https://www.worldclim.org/) and if you are happy to use it, we can deploy for RBIS.

**Comment by dimasciput** [comment]
Hi @bimeobed, any updates on this?

**Comment by bimeobed** [comment]
Hi @timlinux  we are still waiting the data from Rwanda Mereological agency and we are happy to use that data from worldclim  unfortunately me and Admire we try to download it but is too big difficult to clip by using my computer

**Comment by NyakudyaA** [comment]
> Hi @timlinux we are still waiting the data from Rwanda Mereological agency and we are happy to use that data from worldclim unfortunately me and Admire we try to download it but is too big difficult to clip by using my computer

Do you need help for us to download this for you and clip it to the country extent ?

**Comment by bimeobed** [comment]
Yes it will  be great. May  be it is an issues of my computer when I try to clip out Rwanda  it takes  long time at the end fairs  that why we decide to wait data from meteo but when we get these data from worldclim we can prefer to use it
thank you for your help.

**Comment by NyakudyaA** [comment]
We need to do the following

- [ ] Download data from https://www.worldclim.org/
- [ ] Source the Rwanda boundary preferably from RBIS
- [ ] Buffer the boundary slightly so that when you clip you prevent the staircase effect for rasters
- [ ] clip all the rasters you have downloader
- [ ] Create a model/script to automate this process

**Comment by bimeobed** [comment]
Thank you very much @Jeremy-Prior  now the precipitation data has been successful uploaded in Geonode  I think we can schedule a session with admire to see the way we can display these data on the graph bcse I am not able to do that
![Image](https://user-images.githubusercontent.com/73634159/160445418-59920fee-4af2-403f-861a-ee8267309be4.png)

**Comment by Jeremy-Prior** [comment]
I've updated the names and descriptions of the GeoTiff layers to include the years from which the data was averaged.

**Comment by bimeobed** [comment]
Hello, @NyakudyaA  Already climate data for 10 m resolution has been registered in service registry but  I try to make group interact fair. Could you help me to fix this issues?
![image](https://user-images.githubusercontent.com/73634159/167846002-49d85cdf-8497-4222-a906-9731e3b83b3d.png)


Now to register the layer in service registry work well
![image](https://user-images.githubusercontent.com/73634159/167846260-71c97076-a6f2-4221-b5e1-016d5e56207f.png)

**Comment by bimeobed** [comment]
@NyakudyaA  when  I sent this the message  how may I fix this?
![image](https://user-images.githubusercontent.com/73634159/167847781-f0744167-24e7-49d7-a88a-9e7805afce1a.png)

**Comment by bimeobed** [comment]
Hello @NyakudyaA  Could you help me to fix this issues because group interact does not work or may I continue to upload precipitation data for 5m we will update group interact after

**Comment by NyakudyaA** [comment]
> Hello @NyakudyaA Could you help me to fix this issues because group interact does not work or may I continue to upload precipitation data for 5m we will update group interact after

Hi @bimeobed I will take a look shortly and revert

**Comment by bimeobed** [comment]
Thank  you very much @NyakudyaA

**Comment by NyakudyaA** [comment]
@bimeobed This is fixed now.
![rwanda-geocontext](https://user-images.githubusercontent.com/2510900/168244296-ad0a4422-94a4-4e8a-840e-5164b891c114.png)

All the layers being used in geocontext need to be publicly visible unless you add credentials when registering the service in geocontext

![2022-05-13_10-35](https://user-images.githubusercontent.com/2510900/168244712-e535b32d-32e9-4c31-a701-ac2c4f78c925.png)

**Comment by bimeobed** [comment]
Thank you very much @NyakudyaA  Now it is working well let register the remaining layers for 5m

**Comment by bimeobed** [comment]
Hi @NyakudyaA  I hope you are doing well now all precipitation data ( 5m prec and 2.5M Prec )has been registered  the remaining task is to reload into the graph and also to make group read does not work on my side could you help me to check this issues? I try to flow the guidance you sent to me but it can't work
![image](https://user-images.githubusercontent.com/73634159/170215420-d472c789-0d2d-4f56-9e2b-0d6e826f5deb.png)
![image](https://user-images.githubusercontent.com/73634159/170215752-bca32021-5146-4b9f-a4fd-3f4a37fbfdaa.png)

**Comment by NyakudyaA** [comment]
I will check them and revert after testing

**Comment by NyakudyaA** [comment]
@bimeobed This is now fixed
![2 5m](https://user-images.githubusercontent.com/2510900/170943914-e3fb43ab-bcae-42c5-9f87-fcb9b77eb200.png)
![5m-prec](https://user-images.githubusercontent.com/2510900/170943923-308faa1e-3381-4895-8a58-abb640a2c76b.png)

@dimasciput Can you take over to show the graphs

**Comment by bimeobed** [comment]
Thank you very much @NyakudyaA

**Comment by bimeobed** [comment]
Hello @dimasciput   Could you help us  to show precipitation data on graph . I and Admire already we registered in service registry and in GeoNode.

**Comment by helendallas** [comment]
RBIS project finished, closing ticket
