### ISSUE TITLE
CSV files not correct again

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2673]
I assisted a user to download data for the species

![image](https://user-images.githubusercontent.com/45286876/124108803-c9144400-da66-11eb-8e5f-9ed51df63961.png)

The CSV file downloaded does not appear to have the correct Source Reference Data for GBIF data -  the Source and Reference Category should be included and owner should not be Kartoza_Admin etc. 

here is the file
[Wynand Malherbe Biomphalaria pfeifferi.xlsx](https://github.com/kartoza/django-bims/files/6747454/Wynand.Malherbe.Biomphalaria.pfeifferi.xlsx)
the file:

**Comment by dimasciput** [comment]
@helendallas please test, I have changed all the owner to GBIF.

**Comment by helendallas** [comment]
@dimasciput Thanks thats sorted. Closing ticket
