### ISSUE TITLE
Spatial layers and filters for thermal module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2674]
For the thermal module, five new spatial layers need to be added, with four of these to be included as filters as well.

All layers have been shared in our dropbox folder:
FRC_Kartoza Thermal Module/Spatial Layers and filters

**Spatial layers and filters**

- Köppen Climate  Zones - spatial layer and filter  - in spatial filter
- Flow regions - spatial layer and filter (Similar layout to SA ecoregion level 1) - put in same drawer as Flow regime types, drawer labelled **Flow regions**   - in spatial filter
- Flow regime types - spatial layer and filter (Similar layout to SA ecoregion level 2)   - in spatial filter
- Thermal framework - spatial layer and filter    - in spatial filter

Metadata to add to the **Layer selector i button** are provided as word docs for each.

**Comment by timlinux** [comment]
@amyburness can you set up a call with Helen and Nick so that you can get the layers from the dropbox and understand the requirements, then chat with  @NyakudyaA to understand how to set up the filters.

**Comment by helendallas** [comment]
Closing ticket as separate tickets created for each layer and filter
