### ISSUE TITLE
Incorrect collector/owner institution for fish data

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2678]
1. **Owner issue**: There are still a lot of records with Owner incorrectly listed as FBIS Admin: for example 533 fish records and 17 invert records. This must be an error on the FBIS end, because these the Owner information in the ingested spreadsheets is correct. 

2. **Collector/owner institution issue**:  Collector/owner institution is incorrectly showing as 'CapeNature' on live site for records from the following study: 
**E.R. Swartz, Paul Skelton & Paulette Bloomer. 2007. Sea-level changes, river capture and the evolution of populations of the Eastern Cape and fiery redfins (Pseudobarbus afer and Pseudobarbus phlegethon, Cyprinidae) across multiple river systems in South Africa**
The correct institution is 'South African Institute for Aquatic Biodiversity' as per the ingested data spreadsheet.

@dimasciput @helendallas do you think we need to correct this manually for this study, or perhaps indicative of a broader issue?

**Comment by jeremyshelton** [comment]
@Janette-Lumley @aneriswanepoel

**Comment by helendallas** [comment]
@jeremyshelton Agreed their are issues with owner. I picked up a lot of Rivers database data that dont have owner and which dont have rivers databse 2015 as the source reefrence :(

**Comment by aneriswanepoel** [comment]
I recently downloaded a CSV for fish data and experienced a similar issue... CSV download not the same as what was ingested:

Upload CSV:
![image](https://user-images.githubusercontent.com/55532903/133407402-a800f3c6-26dd-49ef-8640-79bdda18f29a.png)

Download CSV:
![image](https://user-images.githubusercontent.com/55532903/133407491-b832514d-315c-4f86-8e71-d8ffa3fa1685.png)

@jeremyshelton @helendallas @dimasciput

**Comment by dimasciput** [comment]
@aneriswanepoel @jeremyshelton @helendallas 

Different `collector/owner insitute` is a problem, will check that. 
But reference category database can't have author and year. These two fields will be ignored.

**Comment by dimasciput** [comment]
![2021-09-15_16-41](https://user-images.githubusercontent.com/1979569/133410338-cf8a08d2-b42f-4198-a203-2c6c8bad9fd7.png)

As you can see here, Andrew Deacon has changed their organisation to 'Clean Stream Biological Services', that's why it's different when you download the data.

@aneriswanepoel @jeremyshelton @helendallas

**Comment by helendallas** [comment]
Checked and seems to be fine, closing
