### ISSUE TITLE
Testing site must mirror live site

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2679]
@dimasciput 
It is difficult to use testing site to test data and functionality unless it is an exact mirror of the live site.
Is it possible to schedule a weekly reset of testing to match live site?
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas there is currently no automated process to do this, it's possible I think but it's not that easy. Do you want us to spend some time to add this? Probably need half a day to one day.

**Comment by jeremyshelton** [comment]
@dimasciput thanks for the update. 
Understood. 
This is definitely a priority, so please go ahead and allocate the required time.
Perhaps a weekly synchronization with the live site (running over the weekend) might be best?
@helendallas ?

**Comment by helendallas** [comment]
Agreed, this is important, especially when we come to training data providers. They will need to work on the testing site only during the training so this needs to mirror the live site 100%.

**Comment by helendallas** [comment]
@dimasciput This needs to include a complete mirror including source references so that new data can be added to testing before live

**Comment by dimasciput** [comment]
Testing site now will be updated automatically every Sunday.
