### ISSUE TITLE
Adding new freshwater Ecosystem Types

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2681]
Up until now we have only been focussing on biodiversity data from rivers.
However, moving forward we will nee to add some additional freshwater ecosystem types.

These will probably include: wetlands, dams, lakes. 
This field will need to be included in:
- data upload template
- csv downloads
- filters
- dashboards

This will require a discussion to figure out the details. 
@helendallas

**Comment by helendallas** [comment]
@jeremyshelton I recall we spoke about this and came up with ecosystem types? Please can you add here is we have

**Comment by jeremyshelton** [comment]
@helendallas for the frogs, what they want is: River, Wetland, Terrestrial. We could also add Dam, but don't think it needs to get more complicated than this?

**Comment by helendallas** [comment]
We have had a rethink at this approach. It will be simpler to be able to filter using existing or new layers including :

- National Rivers Map
- National Wetlands Map
- National Dams Map

We will park this for now until the layers are ready.

**Comment by helendallas** [comment]
On hold until SANBI layers are ready

**Comment by helendallas** [comment]
Closing ticket as no longer relevant as filters will be created once the layers are ready and uploaded.
