### ISSUE TITLE
Landuse / land cover / forestry layer not working

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2683]
![image](https://user-images.githubusercontent.com/178003/125757713-eb285293-035d-4f8c-9952-60655cf225e4.png)

@dimasciput can you please investigate why and also review the wagtail docs to ensure the process is properly described based on the current platform.

**Comment by dimasciput** [comment]
Update : 
- the forest cover filter is now working properly

**Comment by helendallas** [comment]
RBIS project finished, closing ticket
