### ISSUE TITLE
Incorrect base layer whe adding fish data

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2690]
Base layer default when adding new data to a sits should be same as for map and 'add a site' workflow': Bing Satellite Hybrid.
At the moment it is a different layer. 
https://freshwaterbiodiversity.org/fish-form/?siteId=65892
![Screenshot 2021-07-20 at 06 59 35](https://user-images.githubusercontent.com/44292029/126264538-556f1e12-499d-47df-b23e-74e360e24a64.png)

**Comment by helendallas** [comment]
@Fanevanjanahary This should apply for adding all new data: fish, invertebrates, algae, SASS

**Comment by Fanevanjanahary** [comment]
- Fish

![image](https://user-images.githubusercontent.com/12623986/129149740-e5d58acc-76d0-4017-a316-43b0850bb120.png)


- Invertebrates
![image](https://user-images.githubusercontent.com/12623986/129149451-28b55c6f-c22c-4631-acd8-3d8c277a3a7a.png)

- Algae
![image](https://user-images.githubusercontent.com/12623986/129149541-a430df1c-408f-4e39-a7f8-f0dd8ea173e2.png)

- SASS
![image](https://user-images.githubusercontent.com/12623986/129149630-29d430fd-e352-4662-9576-936609eff346.png)

**Comment by jeremyshelton** [comment]
@Fanevanjanahary thank you.
Looks good.
Closing ticket.
