### ISSUE TITLE
Occurrence data upload: taxon error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2691]
@dimasciput 
When uploading fish occurrence data csv file, error file returns for certain records: 'Taxonomy does not exist for this group'. However, the taxonomy data are correct in the upload file. Therefore, there should not be an error message for these data.
This has happened in the past as well.
In the error file, the **Taxon** and **Taxon rank** and other columns appear erroneous - it looks like column contents or headers have shifted in the error file??
@helendallas @aneriswanepoel 
![data upload error](https://user-images.githubusercontent.com/44292029/126318128-36edef2b-94d2-4e95-8fb0-3d6695c81bbb.png)

**Comment by dimasciput** [comment]
@jeremyshelton have you upload the fish data to the correct module?

**Comment by jeremyshelton** [comment]
@dimasciput yes, as far as I know this was uploaded to the fish module.
@aneriswanepoel can you confirm that this is correct?

**Comment by jeremyshelton** [comment]
@dimasciput yes - definitely the fish module 👍

**Comment by jeremyshelton** [comment]
Majority or records do not return an error. Only a subset of them.

**Comment by jeremyshelton** [comment]
@dimasciput OK we have found the issue - the error taxa seem to have a space after taxon name.
Will fix this and hopefully that sorts out the problem.

**Comment by dimasciput** [comment]
okay cool
