### ISSUE TITLE
Data upload: adding a geocontext timer?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2692]
Since it is not possible to upload new data until the geocontext from the previous upload is complete, is it possible to add something that shows us 'geocontext % progress' for each upload, so that we know when to start the next one?
@helendallas @timlinux

**Comment by dimasciput** [comment]
I have a different solution, the geocontext is done by different worker ( processor ), so this won't an issue again if you want to reupload the data.

**Comment by jeremyshelton** [comment]
@dimasciput OK, but we are currently unable to upload fish occurrence data to testing site, presumably because it is still fetching goecontext from a previous upload? If that is the case, how do we know when we can start uploading the next spreadsheet?

**Comment by dimasciput** [comment]
@jeremyshelton one sec, let me fix it quickly.

**Comment by jeremyshelton** [comment]
@dimasciput OK

**Comment by dimasciput** [comment]
@jeremyshelton please try it again

**Comment by jeremyshelton** [comment]
@dimasciput we have tested it again (on testing site) with two data sets that definitely do match the upload template, but on both occasions it returns this error:

<img width="1029" alt="Screenshot 2021-07-22 at 09 19 50" src="https://user-images.githubusercontent.com/44292029/126602812-809da9d0-2bb8-4547-b6d7-a227b5b167ac.png">

**Comment by dimasciput** [comment]
@jeremyshelton it seems you saved the csv with different format, you need to save csv with comma instead of semicolon
![image](https://user-images.githubusercontent.com/1979569/126603227-17520e6a-2117-4a13-a1d3-3a52a793090a.png)

**Comment by jeremyshelton** [comment]
@dimasciput OK which .CSV format must I use on Mac?

**Comment by dimasciput** [comment]
@jeremyshelton which editor you use on mac?

**Comment by helendallas** [comment]
@dimasciput This is the same problem I have experienced on testing for ages.

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton My issue was also related to the wrong csv choice. I gues it is working now, although I havent checked for a while

**Comment by jeremyshelton** [comment]
> @jeremyshelton which editor you use on mac?

@dimasciput OK I have fixed my .CSV format from ; to ,

However, even with that fixed, spreadsheet upload on testing is still getting stuck.

**Comment by dimasciput** [comment]
@jeremyshelton is it still stuck now?

**Comment by jeremyshelton** [comment]
@dimasciput OK upload worked.
There were some errors. 
Fixed errors from error file.
Now not able to upload corrected file, maybe because it is fetching geocontext info?

<img width="1067" alt="Screenshot 2021-07-22 at 10 25 05 AM" src="https://user-images.githubusercontent.com/44292029/126610095-95407af7-b2f6-4d06-b670-2c5cd9988cac.png">

**Comment by dimasciput** [comment]
@jeremyshelton one moment, I actually forgot to deploy the fixes to testing.

**Comment by jeremyshelton** [comment]
@dimasciput OK :)

**Comment by dimasciput** [comment]
@jeremyshelton should be fine now

**Comment by jeremyshelton** [comment]
@dimasciput so far, so good:

<img width="1175" alt="Screen Shot 2021-07-22 at 10 48 11 AM" src="https://user-images.githubusercontent.com/44292029/126612698-eadf21ee-eeb2-4141-86b6-ac38ee9c125e.png">

**Comment by jeremyshelton** [comment]
@dimasciput 🥳

<img width="1091" alt="Screen Shot 2021-07-22 at 10 54 02 AM" src="https://user-images.githubusercontent.com/44292029/126613435-90767e34-e877-4dae-bec9-acd50d0e67fb.png">

**Comment by jeremyshelton** [comment]
@dimasciput just uploaded another and it went through smoothly. Looks like its working well now.
Are we now ready to deploy this upload functionality to live site?

**Comment by dimasciput** [comment]
I'm deploying to live site now

**Comment by jeremyshelton** [comment]
Excellent.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas @aneriswanepoel 

Occurrence data upload to live working perfectly.
No FBIS having following upload.

Thank you @dimasciput 
Closing ticket.
