### ISSUE TITLE
Source References: add a document upload link button

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2694]
We need a button for uploading a new PDF in the source reference module, that leads to the links below:
https://freshwaterbiodiversity.org/documents/
https://testing.healthyrivers.kartoza.com/documents/

<img width="1142" alt="Screenshot 2021-07-22 at 06 23 55" src="https://user-images.githubusercontent.com/44292029/126589932-2274ea62-a2b4-4dce-9b9b-7a4bcaa5c076.png">

@aneriswanepoel 
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton in the next version we don't want user to upload from document page, we will create a new page to do this instead. See this ticket https://github.com/kartoza/django-bims/issues/2650

**Comment by jeremyshelton** [comment]
OK thanks thanks @dimasciput
