### ISSUE TITLE
Delete a site button

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2698]
We need to be able to delete a site.
Currently it is not possible to delete a record if it is the only record at a site, but we need to be able to do this:

<img width="1183" alt="Screen Shot 2021-07-23 at 7 56 44 AM" src="https://user-images.githubusercontent.com/44292029/126742604-1d3c5e71-b7bd-4f95-8d7f-8c56e40cf431.png">

@helendallas @timlinux

**Comment by helendallas** [comment]
@jeremyshelton We can already do this on the Site edit form, see screenshot. I am closing ticket.

![image](https://user-images.githubusercontent.com/45286876/127992067-f4e83db1-e690-4798-88be-76faf0662d85.png)
