### ISSUE TITLE
GBIF harvesting  - not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2699]
GBIF fish data harvesting is not working.
Gets stuck on the first taxon.

@Janette-Lumley @helendallas

**Comment by helendallas** [comment]
@dimasciput Please can you check this our soonest

**Comment by dimasciput** [comment]
@jeremyshelton did you test it on testing or live?

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/128124794-50857f83-7096-4178-bd57-c772a1ceb4f8.png)
Looks fine on testing

**Comment by helendallas** [comment]
@dimasciput This is on live. We wanted to reharvest fish using the updated taxon list.

**Comment by dimasciput** [comment]
@helendallas ok checking...

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton it should works now :slightly_smiling_face:

**Comment by helendallas** [comment]
@thanks

**Comment by helendallas** [comment]
Working now, closing

**Comment by jeremyshelton** [comment]
@dimasciput @Fanevanjanahary 
We urgently need to use this tool. 
It was fixed before and is no longer working?
Let us know when it is up and running again and we will test 👍

**Comment by dimasciput** [comment]
@jeremyshelton what was the issue? I just checked and it's working

**Comment by jeremyshelton** [comment]
@dimasciput sorry I see that the comment I added to this ticket this morning is not here (maybe it disappeared when I reopened the ticket).

Anyway, the issue is that the GBIF harvester is getting stuck on species 14:

![unnamed](https://user-images.githubusercontent.com/44292029/130039534-aad974d4-1160-4fa2-b8e2-16b01a1024ff.png)

Is it working for you beyond species number 14?

**Comment by jeremyshelton** [comment]
We were running it for all of the fish species...

**Comment by dimasciput** [comment]
can you run it again, I will check the error logs

**Comment by jeremyshelton** [comment]
OK will do 👍
Running it now & will report back 👍

**Comment by jeremyshelton** [comment]
@dimasciput we did another run and it's working fine now.
Maybe it was a break in internet connection that stopped the previous harvest.
Thank you.
Closing ticket.
