### ISSUE TITLE
Fish data upload taxonomy error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2700]
@dimasciput we continuously get the "Taxonomy does not exist for this group" even after I've double checked everything is correct (no spaces, matches the master list etc). The other spreadsheets that also contain these "erroneous" taxa have all uploaded successfully so the taxa aren't the problem...

Upload file: 
[1. KNP fish data 2009 for uploading.csv](https://github.com/kartoza/django-bims/files/6885257/1.KNP.fish.data.2009.for.uploading.csv)

Error file: 
[error_1._KNP_fish_data_2009_for_uploading_8IREjU5 (1).csv](https://github.com/kartoza/django-bims/files/6885255/error_1._KNP_fish_data_2009_for_uploading_8IREjU5.1.csv)

@aneriswanepoel

**Comment by dimasciput** [comment]
@jeremyshelton @aneriswanepoel I found a hidden space. It's between Enteromius and viviparus
![image](https://user-images.githubusercontent.com/1979569/127263844-7c19a97e-77ba-466b-b491-f680b5a75eea.png)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Missed that. Most extra spaces have occurred at the end of the name 🧐
Will update and upload - sure that will work now. 
@aneriswanepoel

**Comment by helendallas** [comment]
Closing ticket.
