### ISSUE TITLE
We need to replace the charts with highcharts

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2707]
Our charting lib is old and has some limitations, we should refactor it, replacing it with highcharts.

See also https://github.com/kartoza/django-bims/issues/2444

**Comment by helendallas** [comment]
Closing ticket as graphs working fine

**Comment by helendallas** [comment]
Noted some issues e.g.
![image](https://user-images.githubusercontent.com/45286876/196627501-c0859ef2-3bcc-490a-9ac7-b1d833c84af5.png)
 We need to revisit this please

**Comment by dimasciput** [comment]
@helendallas I have tested this, and the chart has been updated and improved, I couldn't find any issues anymore, please let me know if you found one.

**Comment by dimasciput** [comment]
@helendallas I have tested this, and the chart has been updated and improved, I couldn't find any issues anymore, please let me know if you found one.

**Comment by helendallas** [comment]
The chart that I get when I download the ecological category chart is still problematic

This is what is looks like on the dashboard
![image](https://github.com/kartoza/django-bims/assets/45286876/8ec5ab08-e4ad-4fc4-ae6a-3637fa74ea63)


https://freshwaterbiodiversity.org/sass/dashboard/11056/?taxon=&search=&siteId=11056&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=11056&orderBy=name&polygon=&dst=

it looks like this when it is downloaded as a svg

![Ecological category(1)](https://github.com/kartoza/django-bims/assets/45286876/370937ed-8415-4fc6-b051-f9677ac6050c)

**Comment by dimasciput** [comment]
![Ecological category-3](https://github.com/kartoza/django-bims/assets/1979569/d4cf30cf-d32a-4b01-8718-ba42fe4edf49)

I have fixed this, please test on testing site.

**Comment by helendallas** [comment]
Thanks @dimasciput All looking fine now, please deploy to production
