### ISSUE TITLE
Delete data from a site visit and a study reference

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2710]
We need to functionality to delete data from:

1. all occurrence records associated with a Site Visit
2. all occurrence records and associated data for a Study Reference

This request is carried over from ticket #2592 which I have now closed.

@helendallas @aneriswanepoel

**Comment by helendallas** [comment]
What we dont yet have is to be able to delete a Site Visit for a Non-SASS site, as per this screenshot and link
https://freshwaterbiodiversity.org/sass/view/11029/

![image](https://user-images.githubusercontent.com/45286876/128981415-7c568ce8-8afe-48cf-a312-7cf27241679a.png)


We need to same for the algae, invert and fish dashboards, and all others going forward.
https://freshwaterbiodiversity.org/site-visit/detail/4720/

![image](https://user-images.githubusercontent.com/45286876/128981632-08390095-ebe3-4c73-bc8d-917daab639c0.png)


So we need a DELETE button next to EDIT button for all of these Site Visit forms

**Comment by dimasciput** [comment]
@Fanevanjanahary I sized this ticket to 5, please let me know if you need more or less time.
