### ISSUE TITLE
Please remove abiotic data from Site Location form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2711]
At the moment the associated abiotic data is shown for each site, if it exists. This does not make sense as the abiotic data is linked to a site visit -  I suggest we remove it here as it is shown with Site visit data
@jeremyshelton What do you think?

https://freshwaterbiodiversity.org/location-site-form/update/?id=9949

![image](https://user-images.githubusercontent.com/45286876/128488204-c7ddf91b-2298-40ba-88d2-555818fc90c5.png)

**Comment by jeremyshelton** [comment]
@helendallas agreed.
