### ISSUE TITLE
Error message after updating geomorpohologial zone

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2712]
When I edit Site Location form, and run the 

Fetch data for Geomorphological zone, and the hit Save

I get an error message and the new zone is not save.
![image](https://user-images.githubusercontent.com/45286876/128500649-c784ac6e-9c0e-4f03-b883-20a239abcf58.png)

Here is the site:
https://freshwaterbiodiversity.org/location-site-form/update/?id=9906

**Comment by dimasciput** [comment]
@Fanevanjanahary can you check this bug?

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Not sure if you have fixed this or not as no one responded to my ticket! It seems to be working now, so will close ticket for now. Please always feedback to me via the ticket when something is fixed.
