### ISSUE TITLE
SASS taxa from SASS v 4, alwasy missing if I edit SASS data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2713]
This is a recurring issue - please can you try and fix it.

When I edit old SASS data, that included Trichoptera (cased caddis 1 ) etc., then after editing and saving, it is always left out, so score etc are wrong.

Here is the original data before I edited it.  I did not edit the SASS data at all.
![image](https://user-images.githubusercontent.com/45286876/128520925-dc24296c-3517-40de-9289-3a5fb4597c25.png)

Then I opened it to edit as I wanted to update biotopes and correct Source Reference, but when it is saved, and I check, these taxa have been left out.

![image](https://user-images.githubusercontent.com/45286876/128521054-4864f301-ae04-4aab-b650-c99cc8e9f308.png)

https://freshwaterbiodiversity.org/sass/view/2205/

**Comment by helendallas** [comment]
@dimasciput Any chance you can see what the issue is here. We need to check through a lot of SASS data and are unable to do this until this is resolved. Because in going to edit the data errors are introduced.

**Comment by dimasciput** [comment]
@helendallas not yet, will look into it later.

**Comment by dimasciput** [comment]
@helendallas this is fixed in live site

**Comment by helendallas** [comment]
Thanks @dimasciput Seems to be correct now, closing ticket
