### ISSUE TITLE
CSV download file errors

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2716]
CSV download file has some errors, such as records without co-ordinates

@dimasciput @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput here is the erroneous .csv file:

[7ea51120cdaf2cb5485001be6789889a168d1d1fa6a71fdf76975a878d79df21.csv](https://github.com/kartoza/django-bims/files/6965749/7ea51120cdaf2cb5485001be6789889a168d1d1fa6a71fdf76975a878d79df21.csv)

**Comment by dimasciput** [comment]
I didn't see the error in the csv, can you point out which record? @jeremyshelton @aneriswanepoel

**Comment by aneriswanepoel** [comment]
> I didn't see the error in the csv, can you point out which record? @jeremyshelton @aneriswanepoel

So we think the errors are from GBIF - think we can close this ticket now?

**Comment by helendallas** [comment]
Closing ticket
