### ISSUE TITLE
Data clipping to SA boundary not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2717]
We still have data points falling outside of SA boundary:
<img width="641" alt="Screen Shot 2021-08-11 at 5 28 17 AM" src="https://user-images.githubusercontent.com/44292029/128965412-42ee7ac1-54e2-4b68-820d-85e3c3f8a41b.png">

**Comment by dimasciput** [comment]
@jeremyshelton please don't create a new ticket when the old ticket is still up. https://github.com/kartoza/django-bims/issues/2462

**Comment by jeremyshelton** [comment]
@dimasciput sorry, but it's not always easy to know if there is already an existing ticket for the issue. 
Particularly if not created by FRC (in this case it was Tim).
I always check first, but there will be occasions when we miss an old ticket for the same issue.
