### ISSUE TITLE
Delete a site

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2718]
It would be great to have the ability for us to delete a site.
At present, we are able to delete occurrence records, but not all of them because there needs to be at least one record associated with an existing site. 
@helendallas @timlinux

**Comment by helendallas** [comment]
@jeremyshelton We already have the functionality to delete a site: see link and screen shot

https://freshwaterbiodiversity.org/location-site-form/update/?id=30701

![image](https://user-images.githubusercontent.com/45286876/128981203-ddfe0e5c-87a9-4d3d-9bfa-e649cfbdb7b5.png)

What we dont yet have is to be able to delete a Site Visit for a Non-SASS site, as per this screenshot and link
https://freshwaterbiodiversity.org/sass/view/11029/

![image](https://user-images.githubusercontent.com/45286876/128981415-7c568ce8-8afe-48cf-a312-7cf27241679a.png)


We need to same for the algae, invert and fish dashboards, and all others going forward.
https://freshwaterbiodiversity.org/site-visit/detail/4720/

![image](https://user-images.githubusercontent.com/45286876/128981632-08390095-ebe3-4c73-bc8d-917daab639c0.png)


So we need a DELETE button next to EDIT button for all of these Site Visit forms

@jeremyshelton Is this what you are after Jem?

**Comment by jeremyshelton** [comment]
@helendallas OK got it. 
Yes, what you say makes sense. 
I think this request is covered in #2710  ?
If so I will close this ticket (#2718)

**Comment by helendallas** [comment]
@jeremyshelton Sure but maybe just copy the screenshot and link to the @2710

**Comment by helendallas** [comment]
Added to #2710. closing ticket
