### ISSUE TITLE
Delete a  reference (and all sites and data associated with it)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2719]
Please delete all data and sites from the below reference:

Peer-reviewed scientific article. Jeremy Shelton, Olaf Weyl, Karen Esler & Bruce Paxton	2018. Temperature mediates the impact of non-native rainbow trout on native freshwater fishes in South Africa’s Cape Fold Ecoregion. Biological Invasions.

http://dx.doi.org/10.1007/s10530-018-1747-7

**Comment by dimasciput** [comment]
@jeremyshelton the reference and all records and site associated with it has been removed from the site.

**Comment by dimasciput** [comment]
*live site

**Comment by jeremyshelton** [comment]
@dimasciput 
But I can still see the reference there:
<img width="335" alt="Screen Shot 2021-08-12 at 6 49 36 AM" src="https://user-images.githubusercontent.com/44292029/129140234-e4da8bdf-2192-477b-9274-12938c4b4285.png">


And the sites and data are still there too:
Here is an example - https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=9129&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9129&orderBy=name&polygon=

**Comment by dimasciput** [comment]
> But I can still see the reference there:

Yes I think it's still stored in memory, should be fine as they no longer exist in the system anymore.

> And the sites and data are still there too:

they are not associated with the source reference.

**Comment by jeremyshelton** [comment]
@dimasciput OK, then can you also please delete all date from this reference also:
<img width="250" alt="Screen Shot 2021-08-12 at 8 10 20 AM" src="https://user-images.githubusercontent.com/44292029/129146771-ef2fc3a6-2974-4cf1-9e10-aca1315233f8.png">

**Comment by dimasciput** [comment]
@jeremyshelton do you want to delete all 113 records associated with that reference?

**Comment by jeremyshelton** [comment]
@dimasciput yes please.
Thank you

**Comment by dimasciput** [comment]
@jeremyshelton ok done

**Comment by jeremyshelton** [comment]
@dimasciput 
Checked.
Looks good.
Thank you.
Closing ticket.
