### ISSUE TITLE
Site corrections not reflecting on map when merging sites

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2721]
When editing the co-ordinates of a site that is incorrect (eg a site in the ocean or a site outside of South Africa) and merging it with an existing site, the corrected site is not reflected on the map. The incorrect site still shows. It is the same when deleting a site - the site still shows on the map.

eg: TYOL-00001 (I have tried to correct this site twice but it is still shown in the ocean)

And here is an example of a site that I deleted but is still showing on the map:
![image](https://user-images.githubusercontent.com/55532903/128992481-b89d312e-c4ef-4dd8-9d65-b34a875167a6.png)

      

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
@aneriswanepoel you just need to refresh the browser, because the old data is still stored in browser.

**Comment by aneriswanepoel** [comment]
@dimasciput I have tried refreshing (Ctrl + F5) and still not working...

**Comment by dimasciput** [comment]
@aneriswanepoel which site did you update?

**Comment by aneriswanepoel** [comment]
@dimasciput one of the sites is TYOL-00001

**Comment by dimasciput** [comment]
Are you trying to remove it or change the coordinate?

**Comment by aneriswanepoel** [comment]
@dimasciput I am trying to change co-ordinates and merge it with an existing site

**Comment by dimasciput** [comment]
@aneriswanepoel can you give me the steps you have done?

**Comment by aneriswanepoel** [comment]
1. Clicked "Edit" on dashboard
![image](https://user-images.githubusercontent.com/55532903/129150260-e9643415-c666-4f6b-9d51-23fffa8f68ab.png)

2. Entered the correct co-ordinates and clicked "Update"
![image](https://user-images.githubusercontent.com/55532903/129150542-9d4a9fa2-ee7b-48e8-acf1-8a8fe7b7f6d2.png)

3. Clicked "Use the existing site"
![image](https://user-images.githubusercontent.com/55532903/129150646-3f856fb4-73bc-4c29-aa5e-7250acf008c3.png)

4. Site was then updated to correct code:
![image](https://user-images.githubusercontent.com/55532903/129150774-5b5ea8ca-27b0-42f7-b9bf-1d02c9dcd5a9.png)

5. Then clicked "Save" and got this message:
![image](https://user-images.githubusercontent.com/55532903/129150891-2451726a-556f-4274-a345-49bbf78910b2.png)

**Comment by dimasciput** [comment]
> Clicked "Use the existing site"

When you clicked this, you actually change to different site. You can't merge sites from this page, you can only merge sites with the lasso tool. Maybe just update the lat and lon manually, and then click save.

**Comment by aneriswanepoel** [comment]
> > Clicked "Use the existing site"
> 
> When you clicked this, you actually change to different site. You can't merge sites from this page, you can only merge sites with the lasso tool. Maybe just update the lat and lon manually, and then click save.

Okay then maybe I should update the co-ordinates, and then go to the sites and merge the, with the lasso tool

**Comment by dimasciput** [comment]
Ok thanks, please close when it's done
