### ISSUE TITLE
Bug in csv downloader for SASS Summary data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2725]
Something strange happening in CSV, see sampling date: 19-02-1998

![image](https://user-images.githubusercontent.com/45286876/129169913-7860c527-97ae-41df-be0b-55a503b77905.png)

![image](https://user-images.githubusercontent.com/45286876/129169934-f9446d19-3b64-4be3-aa7f-7817c2ef8306.png)

**Comment by dimasciput** [comment]
@helendallas can you copy the filter list in the csv here please

**Comment by helendallas** [comment]
url:
https://freshwaterbiodiversity.org/sass/dashboard/9859/?taxon=&search=G2DIEP-ABBOT&siteId=9859&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20G%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9859&orderBy=name&polygon=
