### ISSUE TITLE
Dallas 1995 etc issues

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2727]
[Dallas 1995 etc issues.docx](https://github.com/kartoza/django-bims/files/6979738/Dallas.1995.etc.issues.docx)

- [ ] Delete Dallas 1995 data from first source reference as this is the data imported from the Biobase and does not show as SASS data.
- [ ] Check why the links to the other source references are not working
- [ ] Check why some Sites and SASS data imported from Rivers Database are not in FBIS
- [ ] When I edit SASS data that is not version 5, the cased caddis get left out and I have to go in again to add an abundance. see original data below.

cc @helendallas

**Comment by helendallas** [comment]
@dimasciput These are not all sorted? e.g. some riversdbase sites still missing. This is worrying as I only happen to know these sites because they are mine.....what if other river dbase sites didnt get imported? 

e.g. J2FONT-SWART
