### ISSUE TITLE
Sampling date is wrong on Site Visit validation form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2728]
As per ticket #2439 The Sampling date shown on the dashboard, is not correct.

Please see these examples, where dates are all different.  
![image](https://user-images.githubusercontent.com/45286876/129326476-7a6a2cbd-c634-414e-9d4d-84f436407e3a.png)

https://freshwaterbiodiversity.org/sass/view/12983/

https://freshwaterbiodiversity.org/sass/view/3198/

https://freshwaterbiodiversity.org/sass/view/2911/

**Comment by helendallas** [comment]
I think the date been shown on the Site Visit form is the date the data were entered or edited, not the sampling date.

**Comment by helendallas** [comment]
But also another issue???
![image](https://user-images.githubusercontent.com/45286876/129348504-a097f082-d168-48dc-b8a7-2623edf352e9.png)

On form: July 17, 2021
On data sheet: 07/31/2017
![image](https://user-images.githubusercontent.com/45286876/129348598-6e642b88-ee1b-43a9-be6a-ab16cc40f868.png)

https://freshwaterbiodiversity.org/sass/view/12894/

**Comment by dimasciput** [comment]
@helendallas this should be fixed now, please check it again
