### ISSUE TITLE
Please check why quite a lot of Rivers Database 2015 data is now showing as unvalidated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2730]
This ticket is linked to #2439 but I didn't want it to get lost. These sites also don' t show Owner

e.g.
![image](https://user-images.githubusercontent.com/45286876/129361109-4b657c45-b7d2-4571-85bf-75522d82c85e.png)

![image](https://user-images.githubusercontent.com/45286876/129361137-60f2bc35-2ca4-4d6d-8778-d122ef59ff31.png)

https://freshwaterbiodiversity.org/sass/view/1776/

**Comment by dimasciput** [comment]
@helendallas should be fixed now

**Comment by helendallas** [comment]
Closing ticket, seems ok
