### ISSUE TITLE
Dont make edited data become unvalidated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2731]
This tikcet relates to ticket #2439 

At the moment, any data Site or SASS that I go into to check or edit, then becomes unvalidated.

Is there a way to ensure that going forward only data that are added by a user end up in the validation queue. This applies across all data types, SASS, algae, invert, fish etc.

If you have already actioned this please close ticket. I didnt want this getting lost.

**Comment by dimasciput** [comment]
Hi @Fanevanjanahary , can you handle this one. Thanks

**Comment by Fanevanjanahary** [comment]
I think this is already fixed @helendallas 

![validated](https://user-images.githubusercontent.com/12623986/130166243-32f5d1af-3519-427a-bc1c-31bf5ed83dcb.gif)

**Comment by dimasciput** [comment]
Hi @Fanevanjanahary maybe check the data that is "In review" mode. When the admin/staff updates the data, it should still be in review mode.

**Comment by Fanevanjanahary** [comment]
Alright

**Comment by Fanevanjanahary** [comment]
@dimasciput it works as well for the data "In review"
![in-review](https://user-images.githubusercontent.com/12623986/130235872-3c34574d-2083-4214-bc92-6d183c576a39.gif)
