### ISSUE TITLE
Remove data capturer in Site Visit form for Validation

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2732]
Ticket is linked to #2439 

Data Capturer is still showing - not necessary: e.g. Aneri captured the data but James/Jeremy is the Owner, only need James shown

![image](https://user-images.githubusercontent.com/45286876/129316074-29c1b1ad-6601-44df-bf8b-a30432c72ffb.png)

other examples:
![image](https://user-images.githubusercontent.com/45286876/129316209-ffca0b60-9e53-49ac-b679-1e36f479a865.png)

**Comment by dimasciput** [comment]
@Fanevanjanahary just show owner, no need to display the collector

**Comment by helendallas** [comment]
Thanks, fixed.
