### ISSUE TITLE
Provide access to national SASS auditor to update SASS accreditation of users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2733]
Please can  you show me how to create a group of users that get access t being able to update the SASS accreditation status of users on a regular basis.

![image](https://user-images.githubusercontent.com/45286876/129367748-3c1173ab-ff57-4f48-89de-ed5d2ffbb659.png)

**Comment by helendallas** [comment]
@dimasciput Not sure what to check here?

**Comment by dimasciput** [comment]
@helendallas sorry I didn't add any description. Basically, users with the SASS manager role can now update the SASS accreditation status of other users.

<img width="1201" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/26131747-2d5e-4241-be2d-da47f21a5bfd">

**Comment by helendallas** [comment]
So when Christa logs in will she be able to access the Administration / Admin Page from top menu.

Then navigates to People/Users. 
And use the filter to select a user
Clicks on name
Scroll to bottom and update
 
Is this correct?

**Comment by helendallas** [comment]
@dimasciput PLease see questions above.

**Comment by helendallas** [comment]
@dimasciput Please respond to this

**Comment by helendallas** [comment]
@dim Either a conversation needed or a more detailed explanation or video of how this works please.

**Comment by helendallas** [comment]
@dimasciput To fix and deploy to live soonest please. as discussed on 19 sep 2023

**Comment by dimasciput** [comment]
@helendallas this is deployed to live.

**Comment by helendallas** [comment]
@dimasciput Did you change it as per our discussion. I need some guidance here please,. It is not obvious what one does, thanks

**Comment by helendallas** [comment]
@dimasciput This is not working as needed. I created a second profile and added SASS Manager . But when I login I don't see Admin option on menu and cannot get to users.

Please check and revert

**Comment by helendallas** [comment]
Why do I login as SASS Manager? I thought I assigned SASS Manager to a user and then that user has rights to modify accreditation

**Comment by dimasciput** [comment]
@helendallas yes that's correct, I mean user need to login as a SASS manager.

**Comment by dimasciput** [comment]
@helendallas let me check

**Comment by helendallas** [comment]
Okay so I created a second profile hfdallas@gmail.com and made me a SASS Managers

https://freshwaterbiodiversity.org/admin/people/profile/4428/change/?_changelist_filters=q%3DHelen

But when I login I don't see Profile Admin

<img width="473" alt="Screenshot 2023-10-19 at 08 40 32" src="https://github.com/kartoza/django-bims/assets/45286876/0209728f-063c-49cd-a69f-41d85d8746d8">

**Comment by dimasciput** [comment]
@helendallas you need to set the user as staff as well, so they can login to admin page.

![Screenshot 2023-10-19 at 1 41 43 PM](https://github.com/kartoza/django-bims/assets/1979569/6d388927-9fdd-45a2-a1cc-0a216817ed48)

**Comment by helendallas** [comment]
DOne, but now I see whole admin page...is it meant to be like that?

<img width="583" alt="Screenshot 2023-10-19 at 08 54 32" src="https://github.com/kartoza/django-bims/assets/45286876/1bd0323c-d462-4ba4-9f30-49dca680b85c">

**Comment by dimasciput** [comment]
@helendallas Ah, I probably need to restrict staff users from seeing all the menus. However, when user click one of them, it will lead to a forbidden page. I'll create a new ticket and address it there.

**Comment by helendallas** [comment]
Ok thanks, yes, sounds like a plan

**Comment by helendallas** [comment]
Thanks closing ticket
