### ISSUE TITLE
Please check why quite a lot of Rivers Database 2015 data does not have an Owner

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2734]
Linked to ticket #2439 

A lot of data migrated from the Rivers Database 2015, does not have an Owner associated with it. 

In addition to individuals, including Helen Dallas, Liz Day, Jeanne Gouws, there are some where the owner was an organisation, including 

- Umgeni Water 
- DWAF WC

**Comment by dimasciput** [comment]
@helendallas I found the name in collector section, should I move the collector name to owner for data that doesn't have owner and organization as the owner?

**Comment by helendallas** [comment]
Yes, that should be fine, thanks

**Comment by dimasciput** [comment]
@helendallas can you check it again? should be fixed now

**Comment by helendallas** [comment]
@dimasciput Some still seem to be missing but I am going to close the ticket and get Janette to manually update fro the original database.
