### ISSUE TITLE
Delete a reference - bug

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2736]
Study reference persists after (1) all data were deleted and (2) the reference was deleted in the Source References tab?
I would think that once these have been done the reference should no longer be on FBIS?

<img width="606" alt="Screen Shot 2021-08-17 at 7 45 21 AM" src="https://user-images.githubusercontent.com/44292029/129670352-6500db75-10c0-4ce8-9b05-91f2be901b5d.png">

**Comment by dimasciput** [comment]
@jeremyshelton it takes some time to update as the data is being cached in the system to improve performance.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput for letting me know 👍
