### ISSUE TITLE
Problem when deleting occurrence record via site visit tab

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2742]
Site N4DENS-00003 has two occurrence records. I want to delete one of them. However, when I do so then both records, as well as the site dissappear?

![Screen Shot 2021-08-20 at 7 47 15 AM](https://user-images.githubusercontent.com/44292029/130185786-e6ffe8ff-2a23-4925-9d88-e24eb073f431.png)
im

https://testing.healthyrivers.kartoza.com/site-visit/update/7383/

@aneriswanepoel @helendallas

**Comment by Fanevanjanahary** [comment]
@jeremyshelton  This is already fixed 

![Peek 2021-10-04 00-01](https://user-images.githubusercontent.com/12623986/135771552-b2cdb875-49fc-4c40-8fa2-841ded17f2d4.gif)

**Comment by jeremyshelton** [comment]
OK looks good.
Thanks @Fanevanjanahary 
Closing ticket now.
