### ISSUE TITLE
Site code generator not working

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2745]
When creating a new site, the site code generator gets stuck on "Generating"

![image](https://user-images.githubusercontent.com/55532903/130227901-b98139a9-ba90-477f-9d60-475609423bd8.png)

@dimasciput @jeremyshelton

**Comment by dimasciput** [comment]
Hi @aneriswanepoel can you check again on testing?

**Comment by helendallas** [comment]
@dimasciput I checked this now on testing, generator working for rivername, site code and geomorphological zone.

**Comment by helendallas** [comment]
Not sure if you already rolled the fix to live but it is also working on live site but seems to take longer.

**Comment by helendallas** [comment]
Working as of 20 September 2021. Closing ticket
