### ISSUE TITLE
We need a detailed Thermal Dashboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2748]
We need to be able to see the details of the graphs and tables generated in tickets #2615 as well as the normal site information as shown below
![Thermal dashboard overview shot](https://user-images.githubusercontent.com/45286876/134522589-0ed4c061-a422-4f21-85b8-6750bbfd29fb.png)

Thermograph example:
![Thermograph](https://user-images.githubusercontent.com/45286876/134523347-55cf2643-b039-43f8-8afe-2da1ebb5566d.png)

Example of table with thermal metrics:

![Table Thermal metrics](https://user-images.githubusercontent.com/45286876/134523850-999d4b22-e2f5-49dd-a729-cfdc2041196f.png)

**Comment by helendallas** [comment]
There is also a whole screening process and dashboard but I am not sure if we should be tackling this yet as I am concerned that it will use to much of our budget. see below

[Figure 7 Screening process.pdf](https://github.com/kartoza/django-bims/files/7218417/Figure.7.Screening.process.pdf)

**Comment by helendallas** [comment]
It would be good to also include the existing visualisations that you have for time series data that you showed us.

**Comment by helendallas** [comment]
Here is the original dashboard I created for the thermal data. I think we could chat through this and discuss what it is feasible to include.
[Appendix 4 FBIS report template_Thermal Single Site_Final 31 Aug 2020.pptx](https://github.com/kartoza/django-bims/files/7562740/Appendix.4.FBIS.report.template_Thermal.Single.Site_Final.31.Aug.2020.pptx)

**Comment by dimasciput** [comment]
@helendallas the ticket for screening https://github.com/kartoza/django-bims/issues/2873, I think it won't be on current sprint (sprint 3).

**Comment by helendallas** [comment]
ok @dimasciput understood. thanks

**Comment by dimasciput** [comment]
@helendallas 
![image](https://user-images.githubusercontent.com/1979569/144186271-8b072425-26f8-4177-b7a5-abf25eb1db53.png)

how do you get these data? 95%_low, 95%_up, etc. I couldn't find it on the spreadsheet.

**Comment by helendallas** [comment]
@dimasciput Its on the Calcs_thermograph tab of the spreadsheet. see Example Metrics_master code5_Eerste River-ITA.xlsm

I have asked if Nick is available if you dont come right...this is his brain power :)

![image](https://user-images.githubusercontent.com/45286876/144186892-395a7b40-8e61-4357-a207-966635eb19ce.png)

**Comment by dimasciput** [comment]
@helendallas ah okay, I missed it, I think it's self explanatory, let me try to tackle it first. Thanks.

**Comment by helendallas** [comment]
Great thanks. Nick is actually not available today so if you have questions this will have to wait until tomorrow.

**Comment by dimasciput** [comment]
@helendallas this is deployed to testing, please test it there

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Looking great, thanks!!!!

**A few comments:**

- Can we have the full overview section as per other dashboards for consistency and additional information.
- Can you include a photograph on top right as per other dashboards
- Can you style Monthly magnitudes with shaded headed as others and add extra space between header and Jan

- Thermal metrics table - please rename the following to match the graph:
Mean7 -  **Mean_7**
Min7 -  **Min_7**
Max7 - **Max_7**

Same with 
![image](https://user-images.githubusercontent.com/45286876/144562108-3a46e72b-2715-497a-9bec-cd39a6e42421.png)

Mean_7cnt
Min_7cnt
Max_7cnt
Mean_7dur
Min_7dur
Max_7dur

Would it be possible to have a pdf that can be clicked that gives an explanation of all of these metrics? 
Perhaps next to the download button
![image](https://user-images.githubusercontent.com/45286876/144562869-22b1a716-b9a6-47ad-a6a7-ad436315e4be.png)

We have an **?** which when clicked open a pdf???? Would be very useful for user.

[Help PDF for Thermal Metrics table in dashboard.pdf](https://github.com/kartoza/django-bims/files/7647664/Help.PDF.for.Thermal.Metrics.table.in.dashboard.pdf)

We need to include a Metadata Table at the bottom as per other dashboards -  please see #2888 

It would be good to have a site image as well - please see ticket #2889 

Any chance these two tickets could be included in this sprint????

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Please confirm when these changes can be done, thanks

**Comment by dimasciput** [comment]
updated in testing

**Comment by helendallas** [comment]
Thanks @dimasciput @Fanevanjanahary This looks great. Please roll out to live on thursday.

**Comment by helendallas** [comment]
Still not rolled out to live @dimasciput ? I thought this was meant to happen a week ago?

**Comment by helendallas** [comment]
Thanks Looks great, closing ticket
