### ISSUE TITLE
Please can you standardise the date format - it is confusing 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2752]
Please see this example, where dd and mm get confused and potentially mixed.

In FBIS, this date is shown as 10-03-2011

![image](https://user-images.githubusercontent.com/45286876/131085347-e68e3c02-f802-498e-89c7-34c89aa25979.png)

https://freshwaterbiodiversity.org/sass/view/12053/

However in the CSV file downloaded it is shown as 03-10-2011, which is the same as in the original Rivers Data
E1BOON-R303B 10/3/2011

It need to be consistent from one form to another, another example, on the SASS Site dashboard, and Site form and other dashboards

See another example:

![image](https://user-images.githubusercontent.com/45286876/131088830-83c31b55-b562-442f-aef0-dc588b1f4aea.png)

![image](https://user-images.githubusercontent.com/45286876/131088883-5c0cec41-a9b9-4ea6-9b3d-9741c684d212.png)

And then on the fish, invert and algae dashboard, it is different again:
![image](https://user-images.githubusercontent.com/45286876/131089468-979f5314-1fa0-4ef6-b9d0-b2782d7a70ea.png)

and again different on the Site Visit dashboard
![image](https://user-images.githubusercontent.com/45286876/131089537-1d6cce93-b768-4cbb-9d9e-dd3d5ed78cdd.png)

The dates are inconsistent  -please can you standardise; I suggest the dates as per fish.invert.algae, odonate dashboard:
yyyy-mm-dd

**Comment by timlinux** [comment]
@dimasciput to confirm if deployed on testing or live and to add a label that we can mark issues as 'testing' or 'live'.

**Comment by helendallas** [comment]
@Fanevanjanahary Have you fixed this last issue yet? Please respond on github so I can check and close ticket, thanks

**Comment by helendallas** [comment]
@Fanevanjanahary dates seemed to be problematic again, see here

![image](https://user-images.githubusercontent.com/45286876/150788002-ecb072ea-90fc-482d-80f4-544d812137b2.png)

https://freshwaterbiodiversity.org/site-visit/detail/189664/

Please can you check

**Comment by Fanevanjanahary** [comment]
@helendallas I will check on it.

**Comment by helendallas** [comment]
@Fanevanjanahary Please update me on this ticket.

**Comment by Fanevanjanahary** [comment]
@helendallas  I tested and got this

![image](https://user-images.githubusercontent.com/12623986/160554053-bd08468c-f43f-40ac-bb03-eea701b6cf0b.png)

**Comment by helendallas** [comment]
Okay, seems okay again I will close for now. Thanks @Fanevanjanahary
