### ISSUE TITLE
Issue with displaying of Site Visit data sampled in different biotopes

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2756]
I noticed that in the Site Visit form, data are not displayed correctly as biotopes are not included in the hierarchy:
**Site + Sampling date (= SiteVisit),  - Broad biotope - Specific biotope - substratum**:

### For example: this site:
https://freshwaterbiodiversity.org/site-visit/detail/134542/
![image](https://user-images.githubusercontent.com/45286876/132195391-67915132-6849-45ed-b78c-7d6eb1c013cb.png)

Two sets of biotope level data were uploaded, the first in the **broad biotope = Stones in current**; and the second in the **broad biotope =  Marginal vegetation**. 

However in the Site Visit form the biotopes are mixed up, and sampling method, which doesn't make ecological sense, and because of this some taxa are recorded twice. 

We need this form to differentiate between biotope level data Broad biotope, Specific biotope, Substratum.

Please can we discuss how best to do this and what will be required in the backend. One option is to show Broad Biotope and allow the user to select from dropdown list; or to include Broad, specific and substrate in the list as columns? 

The CSV downloaded has the data correctly, so the underlying data are correct. see below:

[SIte Visit Data extracted from FBIS showing biotope issues.xlsx](https://github.com/kartoza/django-bims/files/7114988/SIte.Visit.Data.extracted.from.FBIS.showing.biotope.issues.xlsx)

**Comment by dimasciput** [comment]
Hi @helendallas I just realized this is little bit complicated when user want to edit their site visit data with multiple biotope data. Should we just split the data into two site visits? Even they are the same data and location, but they have different biotope.

**Comment by helendallas** [comment]
@dimasciput If you split it into two site visits, with different biotopes, how would the user then see the data and edit the data?

**Comment by helendallas** [comment]
@dimasciput Happy to chat or perhaps you can describe solution better before implementing.  Coult one not include a dropdown for Broad biotope here
![image](https://user-images.githubusercontent.com/45286876/135217437-e82758bc-cd65-4d9f-bd31-2d07d511a15b.png)

**Comment by dimasciput** [comment]
@helendallas yes I could add a dropdown there, it's easy to implement in detail page. 
But when you go to edit page for this specific site visit, things will get complicated from the user interface side and also backend implementation, how will user update the biotope if there are two different biotopes and different collection records associated with them? And what if they want to add new biotope?

**Comment by helendallas** [comment]
mmm okay, I understand. So if you split it into two site visits, with each one having a biotope, then the user would go to for example the Site- sampling date - biotope, to see and edit data. That could work
