### ISSUE TITLE
Source references not downloadable in metadata table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2759]
When I try to download this report i get an error message:

https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%22862%22%5D&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/132299696-40853006-4fc4-4046-8495-50e704fb7c54.png)

Error message:

https://freshwaterbiodiversity.org/uploaded/documents/document/Ch7IQF0TRMCU8-l3RJauuA.pdf
![image](https://user-images.githubusercontent.com/45286876/132299745-e86ee787-ee11-47c9-bed0-54a54f3c866b.png)

It could be because you haven't finished the source reference updates yet

**Comment by dimasciput** [comment]
@helendallas Fixed, it was an issue in the server

**Comment by helendallas** [comment]
@dimasciput Thanks so much ! Working
