### ISSUE TITLE
CSV of abiotic data not downloading correct data for some sites

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2760]
We have tried to download csv of abiotic data for sites of the Source Reference =  
![image](https://user-images.githubusercontent.com/45286876/132300716-c554a013-0b16-4a2b-beed-036f2740300b.png)

For 33 of the sites, the data returned is for the incorrect and is always for the site: H4HOUT-DEHOE. These are also the sites that were only assessed once in Nov 1995.  The sites assessed more than once return the correct data.

For example, we tried to download abiotic csv for H2SAND-SANDD

https://freshwaterbiodiversity.org/sass/dashboard/9981/?taxon=&search=H2SAND-SANDD&siteId=9981&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%22862%22%5D&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9981&orderBy=name&polygon=

But the csv returned the data for the wrong site, always H4HOUT-DEHOE

[Abiotic data H2SAND-SANDD.xlsx](https://github.com/kartoza/django-bims/files/7119679/Abiotic.data.H2SAND-SANDD.xlsx)

Another example: 
H2ROOI-WORCE

**Comment by Janette-Lumley** [comment]
@helendallas and @dimasciput I have checked and the data is downloading correctly. Thanks

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 
CLosing ticket
