### ISSUE TITLE
We need to be able to add a new Unpublished data"set

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2761]
At the moment you are forced to select from the list of existing unpublished datasets. However, if a user needs to create a new dataset it is not possible.

Please can you allow for the ability to "**Add New**" in the same way as for the Database:
![image](https://user-images.githubusercontent.com/45286876/132332716-cf06222c-7d9c-4958-b8d7-5c861be48e9e.png)

![image](https://user-images.githubusercontent.com/45286876/132332510-7874ef40-a1bb-4411-9b02-a65a3d2925f7.png)

**Comment by dimasciput** [comment]
Please test on testing site

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput  This is working well on testing. Please roll out to live

**Comment by jeremyshelton** [comment]
Thanks @dimasciput @Fanevanjanahary 
This is working nicely on live site now.
Closing ticket.
@helendallas
