### ISSUE TITLE
Please fix type of reference category

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2762]
I have found some instances where the reference is a PhD thesis, but it is included as a peer-reviewed scientific paper:
![image](https://user-images.githubusercontent.com/45286876/132334225-569ff61c-2400-4b46-949d-f8e2bf8dfa21.png)

https://freshwaterbiodiversity.org/edit-source-reference/121/?next=/source-references/%3Ftype%3D%26collectors%3D2416%252C1550%26page%3D%26q%3D

This example needs to change to type =  Published report or thesis

If this functionality is going to take some time to action, then we can instead provide a list of incorrect - I have asked Janette to check how many instances there are where we need to change the Type. If it is only a few, then it might be best for you to just do it in the back end.

**Comment by helendallas** [comment]
@dimasciput 
These need to change to Published report or thesis: only 5 references, so please change in the backend.

![image](https://user-images.githubusercontent.com/45286876/134490094-99542fd6-9458-4293-b818-3374b5b48b5c.png)

![image](https://user-images.githubusercontent.com/45286876/134490157-c8c37d7b-631a-40f1-b9d6-49b95d2f56ec.png)

**Comment by dimasciput** [comment]
@helendallas this is fixed in live site

**Comment by helendallas** [comment]
Thanks @dimasciput closing ticket

**Comment by helendallas** [comment]
Sorry @dimasciput I found one more -  it needs to be changed ro report/thesis

![image](https://user-images.githubusercontent.com/45286876/135610057-21bcd2b8-196a-43bc-bf0f-f980edf4e9e2.png)

**Comment by helendallas** [comment]
@dimasciput please can you fix this last one so I can close this ticket. 
![image](https://user-images.githubusercontent.com/45286876/140888338-dbc5df2c-7893-44db-8b33-0e80df0130bf.png)

**Comment by dimasciput** [comment]
@helendallas updated https://freshwaterbiodiversity.org/source-references/?&q=an%20evaluation%20of%20sass

**Comment by helendallas** [comment]
@dimasciput PLease can you check why this is not making it to the filter? and the records link in source reference doesnt work

![image](https://user-images.githubusercontent.com/45286876/142587900-623dd885-fd94-4a8d-a02c-a4453dc513b0.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22622%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

![image](https://user-images.githubusercontent.com/45286876/142587873-2016982a-5138-499c-8d39-27d4b1cc9f9e.png)

**Comment by dimasciput** [comment]
@helendallas can you try it again?

**Comment by helendallas** [comment]
Thanks @dimasciput Working now :)
