### ISSUE TITLE
PLease add a confirm or select button to Find GBIF in Change Taxonomy

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2767]
At the moment when you click Find GBIF, the closest match is added, and this is sometimes incorrect. 

![image](https://user-images.githubusercontent.com/45286876/132704086-b1d3cafc-89a4-45a2-83e8-b6d5dc14f723.png)

Is it possible to include an option screen as below, where the GBIF options are listed, to ensure that mistakes are not made by adding the incorrect taxon.

![image](https://user-images.githubusercontent.com/45286876/132704289-81a83165-29eb-4f17-a568-f9068d5b5275.png)

**Comment by dimasciput** [comment]
@helendallas rolled out to testing and live site, please test

**Comment by helendallas** [comment]
Thanks @dimasciput This works well Please roll out to live.
