### ISSUE TITLE
GBIF data not coming through to FBIS

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2772]
@dimasciput @Fanevanjanahary GBIF data are not coming through properly on FBIS.

For example, a query for the fish taxon Pseudobarbus afer on FBIS (with GBIF turned on in source) produces 230 records, of which 6 are labelled GBIF.

However, there are 353 records for this taxon on GBIF, most of which have coordinates, and so should be displayed on FBIS.

There are also multiple issues with missing information and jumbled columns in the csv download from FBIS for this taxon: 
- Titles are appearing in the source column
- Sources appearing in the title column
- Lots of incorrect or missing data (blank cells) from multiple columns: Collector/owner, Collector/owner institute, Authors, Source, Reference category, title, DOI/URL

As far as I know these issues were fixed in a previous ticket, but there are now lots of errors again.

P. afer csv downloads from FBIS and GBIF attached.

[p afer - fbis download.csv](https://github.com/kartoza/django-bims/files/7151800/p.afer.-.fbis.download.csv)
[p afer - gbif download.csv](https://github.com/kartoza/django-bims/files/7151801/p.afer.-.gbif.download.csv)

@helendallas @aneriswanepoel @timlinux

**Comment by dimasciput** [comment]
Hi @jeremyshelton , can you give us example for these cases : 

- Titles are appearing in the source column
- Sources appearing in the title column
- Lots of incorrect or missing data (blank cells) from multiple columns: Collector/owner, Collector/owner institute, Authors, Source, Reference category, title, DOI/URL

**Comment by dimasciput** [comment]
> However, there are 353 records for this taxon on GBIF, most of which have coordinates, and so should be displayed on FBIS.

Have you checked that they are within the SA border? We received thousands of data from GBIF, but had to delete it because it was out of bounds.

**Comment by jeremyshelton** [comment]
@dimasciput 

Titles are appearing in the source column **- row 117**
Sources appearing in the title column **- row 96**
Lots of incorrect or missing data (blank cells) from multiple columns: Collector/owner, Collector/owner institute, Authors, Source, Reference category, title, DOI/URL - Row 1 has no source, institute, author, year, ref category, title, url/doi

All GBIF records appear to be from inside the SA border:

![Screen Shot 2021-09-13 at 8 21 03 AM](https://user-images.githubusercontent.com/44292029/133034357-f69bb598-ca55-48b4-ab04-3c7707bf791f.png)

**Comment by jeremyshelton** [comment]
@dimasciput this is quite strange because when we downloaded the data csv for P afer from FBIS (GBIF turned on) a couple weeks ago there were 389 records, but now there are only 230?

**Comment by jeremyshelton** [comment]
@dimasciput there are two separate issues here:

1. FBIS not showing the correct number of records for a taxon (for P. afer we should have 209 records uploaded to FBIS + 343 records from GBIF with coords = 552 total records)
2. Jumbled/missing data in .csv download (this seems to be a recurring issue?)

@helendallas

**Comment by dimasciput** [comment]
> Lots of incorrect or missing data (blank cells) from multiple columns: Collector/owner, Collector/owner institute, Authors, Source, Reference category, title, DOI/URL - Row 1 has no source, institute, author, year, ref category, title, url/doi

I just checked and it's an old data from May that doesn't have reference anymore, maybe just remove this 

> Sources appearing in the title column - row 96

I don't see this problem in the csv, GBIF is database record that's why it appears as a title -> https://freshwaterbiodiversity.org/edit-source-reference/689/?next=/source-references/%3F%26q%3DGBIF

> Titles are appearing in the source column

It appears both in source and title, because this entry doesn't have source. 
https://freshwaterbiodiversity.org/edit-source-reference/903/?next=/source-references/%3F%26q%3DSea-level%2520changes%252C%2520river%2520capture%2520and%2520the%2520evolution%2520of%2520populations%2520of%2520the%2520Eastern%2520Cape%2520and%2520fiery%2520redfins%2520%28Pseudobarbus%2520afer%2520and%2520Pseudobarbus%2520phlegethon%252C%2520Cyprinidae%29%2520across%2520multiple%2520river%2520systems%2520in%2520South%2520Africa

**Comment by dimasciput** [comment]
> @dimasciput this is quite strange because when we downloaded the data csv for P afer from FBIS (GBIF turned on) a couple weeks ago there were 389 records, but now there are only 230?

@jeremyshelton I just removed a lot of gbif data that located outside SA

**Comment by jeremyshelton** [comment]
@dimasciput but all the GBIF data for P. afer fall inside SA boundary, so surely non of those would have been removed?
https://www.gbif.org/species/2359874

**Comment by helendallas** [comment]
@jeremyshelton Why dont you extrarct data from GBIF and then DImas can check what is going on. I am also battling to get my head around the fact that so few data are being returned. Doesnt make sense

**Comment by dimasciput** [comment]
Hi @jeremyshelton @helendallas , will you harvest gbif data again for Fish and Invert? 
Let me investigate the issue tomorrow morning.

**Comment by jeremyshelton** [comment]
> @jeremyshelton Why dont you extrarct data from GBIF and then DImas can check what is going on. I am also battling to get my head around the fact that so few data are being returned. Doesnt make sense

@helendallas I have already done this - see above attached csv called 'p afer - gbif download.csv'

**Comment by jeremyshelton** [comment]
> Hi @jeremyshelton @helendallas , will you harvest gbif data again for Fish and Invert?
> Let me investigate the issue tomorrow morning.

OK @dimasciput - we are harvesting fish and inverts from GBIF again.

**Comment by jeremyshelton** [comment]
@dimasciput 

Restoring FBIS to Saturday's version seems to have resolved **issue 1** - the incorrect number of records.

Then for **issue 2**: 
- What do you mean by an old data set from May? What data are these? How/why must they be removed?
- Sources appearing in the title column - see below screenshot from FBIS csv download.
![Screen Shot 2021-09-13 at 2 28 16 PM](https://user-images.githubusercontent.com/44292029/133084002-a27c89b4-a304-4711-9183-235688ba35ed.png)
- Is it correct that GBIF shows blank for year and source? Surely the source (rather than the title) should be GBIF, and the year of that record should show? Or am I missing something?
![Screen Shot 2021-09-13 at 2 29 02 PM](https://user-images.githubusercontent.com/44292029/133084188-0b3edab7-eefe-47cd-92a2-f30f3340fc9f.png)

**Comment by dimasciput** [comment]
> @jeremyshelton Is it correct that GBIF shows blank for year and source? Surely the source (rather than the title) should be GBIF, and the year of that record should show? Or am I missing something?

For database record, we didn't include year and source, database only have title. If we add year, then it will have multiple source references with the same database name.

**Comment by helendallas** [comment]
@dimasciput Agree, we dont want to add year as this creates multiple data sets. I added Global Biodiversity Information Facility (GBIF) as the source for GBIS data, so this will show up now in the csv.

![image](https://user-images.githubusercontent.com/45286876/134468759-7ca5a64e-ddc8-4945-abb0-7ec19bda2cd1.png)

I am going to close this ticket
