### ISSUE TITLE
We need to be able to add site to Lesotho and eSwatini

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2774]
As discussed previously we need to  be able to add site to Lesotho and eSwatini  -at the moment I get an error message when I try and correct a site in Lesotho. I thought this had been sorted a while back?

![image](https://user-images.githubusercontent.com/45286876/133217667-3a64a711-6105-4f35-9a86-3ef8464afc78.png)

https://freshwaterbiodiversity.org/location-site-form/update/?id=10881

**Comment by dimasciput** [comment]
this is deployed in testing and production site.

**Comment by helendallas** [comment]
@dimasciput Working on testing but I get error message on live. I tried to add a new site in Lesotho. this site: D1TSET-00002

![image](https://user-images.githubusercontent.com/45286876/135584737-c5626dae-14e1-448b-ab0f-f5f3ad6e39bc.png)

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 
I have now checked this on the live site and it is working fine now - able to add new sites in Lesotho & Swaziland.
Closing ticket.
