### ISSUE TITLE
Check data harvested from GBIF

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2775]
We are not sure that all the available data is coming down from GBIF and or is being removed when the South African border is filtered.

@dimasciput Please can you check. 
Example file: 

[GBIF Ephemeroptera.xlsx](https://github.com/kartoza/django-bims/files/7161118/GBIF.Ephemeroptera.xlsx)

So I went onto GBIF and ran an extraction query for Ephemeroptera, there are 10,000 + records, just for that order alone, so I am really confused why the invert master list only brings down < 2,000 records in total. Please see what I selected.
 
https://www.gbif.org/occurrence/map?basis_of_record=HUMAN_OBSERVATION&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=MATERIAL_SAMPLE&country=ZA&has_coordinate=true&has_geospatial_issue=false&publishing_org=c5f7ef70-e233-11d9-a4d6-b8a03c50a862&publishing_org=28eb1a3f-1c15-4a95-931a-4af90ecb574d&publishing_org=b3bf3a83-1f68-4541-a03f-330d30d567f5&publishing_org=66522820-055c-11d8-b84e-b8a03c50a862&publishing_org=0c163d39-b67e-4bd9-a2f4-6344b67247f9&publishing_org=149b9411-e994-4416-a218-f2ef21173e44&publishing_org=b4640710-8e03-11d8-b956-b8a03c50a862&publishing_org=5ffa575c-fcd4-4583-9611-545f67b04316&publishing_org=37e82b90-1e21-11de-ab90-f72009d2669b&publishing_org=bc092ff0-02e4-11dc-991f-b8a03c50a862&taxon_key=1225&occurrence_status=present

**Comment by helendallas** [comment]
see also ticket #2772

**Comment by dimasciput** [comment]
@helendallas please can you check if this is fixed?

**Comment by helendallas** [comment]
@dimasciput For Ephemeroptera: When I add GBIF data to the records, I get an extra 9,078 records, which is more in agreement with direct download from GBIF. and an extra 79,193 for all inverts.

FBIS only 44,129, and for all invertebrates 255,840
FBIS + GBIF 52,307, and for all invertebrates 335,033

I will close this ticket, thanks


![image](https://user-images.githubusercontent.com/45286876/134467917-a87ab31b-773d-4a30-942f-6f8c2ef494c9.png)

![image](https://user-images.githubusercontent.com/45286876/134467998-c4efb5d3-ca77-4b7a-95c1-6140715e9b1a.png)
