### ISSUE TITLE
Incorrect (old) fish names appearing in fish data download (csv)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2777]
Several fish taxa including Cheilobarbius capensis and serra, Amatolacypris trevelyani, Sedercypris calidus and erubescensare present in the fish .csv data downloads. However, these names are not present in the fish master list, and so should not appear in the csv data downloads.

**Comment by dimasciput** [comment]
@jeremyshelton Can you send us the downloaded file? It will easier to figure out the issue if we have the data.

**Comment by jeremyshelton** [comment]
@dimasciput I have emailed you the fish file that was downloaded on Monday...

**Comment by dimasciput** [comment]
Hi @jeremyshelton I found some old data that was imported on 20 May, should we delete them?

**Comment by dimasciput** [comment]
I'm not really sure if it's 20 May this year or last year.

**Comment by helendallas** [comment]
@jeremyshelton Please check if this is still an issue and either add to current sprint or close ticket. thanks

**Comment by jeremyshelton** [comment]
@helendallas OK - I am doing another fish data dump & will feed back once that's ready...

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

OK, I have done a new data download & unfortunately this issue persists. 

The incorrect names are names that I recently changed in taxon management:
Cheilobarbius capensis > Pseudobarbus capensis
Cheilobarbus serra > Pseudobarbus serra
Amatolacypris trevelyani > Pseudobarbus trevelyani
Sedercypris calidus > Pseudobarbus calidus
Sedercypris erubescens > Pseudobarbus erubescens
Namaquacypris hopes > Barbus hospes
Schilbe depressirostris > Schilbe intermedius

The old names (the ones on the left) are not present in taxon management, nor do they appear in the taxon search dropdown. 

However, in the data download both names feature for each taxon, which is not correct. The names on the left should not appear in the fish data download at all. 

@dimasciput I do not know what you mean by 'May data' - this is a taxon management issue. Not a data issue?

**Comment by helendallas** [comment]
@dimasciput Please can you prioritise this in this sprint , thanks

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton will do

**Comment by dimasciput** [comment]
@jeremyshelton this is fixed only on production, will be mirrored to testing on Sunday automatically.

**Comment by jeremyshelton** [comment]
Good stuff - thanks @dimasciput
