### ISSUE TITLE
Missing data in fish and invert csv downloads

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2778]
@dimasciput 
We have noticed (looking as fish and invert csv downloads) that there are fairly large numbers of data points with missing data in certain fields like Water Management area and province. This information should be present for all records? An example is the screenshot below which shows that for fish 4000+ records have no WMA info. 

<img width="271" alt="Screen Shot 2021-09-15 at 1 42 07 PM" src="https://user-images.githubusercontent.com/44292029/133427487-36098ea3-8b4a-4bd6-85e1-db87bfa14099.png">

Do you think this is perhaps something linked to Geocontext updating?
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton yes it's geocontext issue, will need to fetch it again.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Checked. All looks good.
Closing ticket.
