### ISSUE TITLE
Exclude GBIF sites from Site Validation

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2779]
No, we can't validate GBIF sites, as we know they are often wrong, but we can also not fix them in FBIS. We need to exclude from Site Validation, can you include the filter as for records?

_Originally posted by @helendallas in https://github.com/kartoza/django-bims/issues/2460#issuecomment-915044200_

**Comment by helendallas** [comment]
@dimasciput Many sites have no owners? not sure why if the GBIF sites have been excluded. 
![image](https://user-images.githubusercontent.com/45286876/135589910-dc1c4342-ccb1-4b28-ba60-3ba285b6cdf1.png)

**Comment by timlinux** [comment]
@Fanevanjanahary can you please update your tickets at the end of each sprint to indicate where we are with the ticket?

**Comment by Fanevanjanahary** [comment]
@helendallas @jeremyshelton the sites don't have an owner since they aren't linked to biological collection records. Should we exclude them also from validation?

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 

I am not sure I understand how data is harvested from GBIF when there is no biological collection record????
Our workflow is such that GBIF data should only be harvested using our taxon master lists.

Is this perhaps old sites which were harvested using earlier master lists that included species no longer on our list? such as fish?

Regardless we don't want to include sites which do not have biological collection records. @jeremyshelton do you agree?

**Comment by jeremyshelton** [comment]
@Fanevanjanahary @dimasciput @helendallas 
_Regardless we don't want to include sites which do not have biological collection records. @jeremyshelton do you agree?_
Agreed.

**Comment by helendallas** [comment]
@dimasciput Some of these data are from OdonataMAP. Either way if there is not biological data associated with it, then the sites should be removed.

![image](https://user-images.githubusercontent.com/45286876/145179073-3efb5048-05c7-4dc6-a2e0-1efceb36511f.png)

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 

Please get back to us on this ticket. The only sites for validation should be the ones added by users, not GBIF or VM, or uploaded as bulk upload by FBIS Admin.

**Comment by timlinux** [comment]
@dimasciput to do one last check here before we are done

**Comment by helendallas** [comment]
@dimasciput Please check this as there are still VM sites that shouldnt be there

![image](https://user-images.githubusercontent.com/45286876/171012104-97619236-4bc1-4da3-b373-2213bb04428d.png)

**Comment by helendallas** [comment]
@dim @Fanevanjanahary Any progress on resolving this ticket?

**Comment by dim** [comment]
sorry, i'm the wrong person to ask :)

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Any prgress on this ticket?
