### ISSUE TITLE
Remove date when uploading unpublished datasets

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2780]
Please remove date when uploading unpublished data and database.

It is creating extra work for us having to go and combine unpublished datasets

I fixed all of these source reference a few weeks ago and now they are all wrong again :(

**Comment by helendallas** [comment]
Also the merge doesnt seem to be working

![image](https://user-images.githubusercontent.com/45286876/133588394-4978dc50-a3a0-4507-bddb-881de75c7213.png)

**Comment by helendallas** [comment]
@dimasciput Is this fixed in testing?  @aneriswanepoel Please can you check on testing once Dimas responds

**Comment by dimasciput** [comment]
Yes sorry, please test on testing first.

**Comment by aneriswanepoel** [comment]
@helendallas checked on testing now and most dates have been removed but some still remaining:
![image](https://user-images.githubusercontent.com/55532903/135582698-d874bc3d-9e99-4027-be52-43572fc00d33.png)

**Comment by helendallas** [comment]
@aneriswanepoel did you upload a new set of data, you cna add data to testing as it gets reset every sunday. PLease add some of the unpublished data that created multiple sets before, maybe just change the name, and then also please test with database, and different dates, thanks

**Comment by aneriswanepoel** [comment]
@helendallas Oh okay I see what you mean. Okay will do

**Comment by aneriswanepoel** [comment]
@dimasciput I am trying to upload data to test the fixes, but get the error message "Taxonomy does not exist for this group" so can't upload. 
[error_Fish_testing_-_1_October_2021_1.csv](https://github.com/kartoza/django-bims/files/7265312/error_Fish_testing_-_1_October_2021_1.csv)

**Comment by helendallas** [comment]
@aneriswanepoel Please check there are no blank spaces - this issue has come up before

**Comment by helendallas** [comment]
I checked and species are on testing and csv looks correct
![image](https://user-images.githubusercontent.com/45286876/135606834-85f39b3f-d311-4870-a9ff-da50dbf979c7.png)

**Comment by timlinux** [comment]
Waiting for Dimas to fix uploader on testing so that this can be checked.
