### ISSUE TITLE
FBIS data boundary

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2786]
@dimasciput 
We need to serve data from neighboring countries outside of SA.
Specifically, the data for the rivers shown on (or clipped for) FBIS - as indicated by the blue lines.

<img width="1010" alt="Screen Shot 2021-09-22 at 3 47 49 PM" src="https://user-images.githubusercontent.com/44292029/134356346-e37d0093-a1f6-40c7-98ef-c9e4e0843593.png">

We will need country as a filter, and as an attribute (new column) in .csv downloads.

We suggest this be included by adding a new sub-drawer underneath 'province' with dropdown for neighboring countries. The drawer name can be changed from 'Province' to 'Province and Neighboring Country'

<img width="283" alt="Screen Shot 2021-09-22 at 3 53 20 PM" src="https://user-images.githubusercontent.com/44292029/134357358-3b7a0e57-92c4-43a3-a097-a59883ae4a9d.png">

The default is: user gets everything if filter not active.
If you add a filter, you only get a subset (data from selected countries)

Please also see related tickets: #2784 and #2774 

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas this is pretty big ticket, because we need to update the boundary, filter and how gbif fetch the data. For now I sized this to 20, we need 2-3 days to implement this.

**Comment by jeremyshelton** [comment]
@dimasciput  SA neighboring countries include: Mozambique, Botswana, Zimbabwe, Namibia, Eswatini, Lesotho

**Comment by amyburness** [comment]
@dimasciput I have made the layer for sadac countries published it to Geoserver and a geojson if needed. Is this all you need from my side to update? 

![sadac](https://user-images.githubusercontent.com/77841514/138275323-0e717953-c627-4f0c-81c1-1b5f2164d8c9.png)

**Comment by amyburness** [comment]
@timlinux @dimasciput The boundaries layer is on Geocontext the staging one. 
![geocontext](https://user-images.githubusercontent.com/77841514/140069525-13fc4c21-5c53-43f5-bf60-e4c71a0a8e26.png)

**Comment by helendallas** [comment]
Thanks @amyburness 

@dimasciput Please let us know when this is rolled out to FBIS testing, thanks

**Comment by timlinux** [comment]
@dimasciput can you pull the GEOJSON from GeoServer and finish the  last steps.

**Comment by timlinux** [comment]
For the layer in the filter change from "Province" to "Province or Country"

**Comment by dimasciput** [comment]
the geojson :
[combination_saprovince_buffered.zip](https://github.com/kartoza/django-bims/files/7615505/combination_saprovince_buffered.zip)

@Fanevanjanahary can you create a script that will check whether the site is inside the geojson or not?

**Comment by dimasciput** [comment]
@Fanevanjanahary you can update the code here https://github.com/kartoza/django-bims/blob/main/bims/api_views/site_in_country.py

**Comment by dimasciput** [comment]
Hi @Fanevanjanahary any updates on this?

**Comment by Fanevanjanahary** [comment]
@dimasciput I'm working on it now

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 
Any progress on this? Please let me know when it is done and whether I must check on testing or live.

**Comment by jeremyshelton** [comment]
@Fanevanjanahary @dimasciput let us know when this is ready for testing on live?

**Comment by Fanevanjanahary** [comment]
@jeremyshelton @helendallas this is already done. You can review it please

**Comment by jeremyshelton** [comment]
Hi @Fanevanjanahary I don't see the requested filter options anywhere in the search bar yet? Do we need to re-harvest data sets from GBIF in order to get the data for the SA neighboring countries including Mozambique, Botswana, Zimbabwe, Namibia, Eswatini, Lesotho? It looks like there are still data gaps in these countries?
@dimasciput @helendallas @timlinux

**Comment by jeremyshelton** [comment]
@Fanevanjanahary @dimasciput please give an update on the status of this ticket?

**Comment by helendallas** [comment]
So @dimasciput @Fanevanjanahary We dont know what is happening with this ticket. Please see @jeremysheltons question above, copied here again.

Requested filter not visible, do we need to reharvest GBIS data for this to show?

**Comment by jeremyshelton** [comment]
@helendallas we are working through this ticket on slack.
I have advised @dimasciput that if this is going to be too complex or time consuming then we must just leave the data clip at the SA boundary....

**Comment by jeremyshelton** [comment]
@dimasciput please provide an update on this ticket. 
Looks like data boundaries on testing and production are both clipped to SA border. 
If this is going to be a time-suck, then lets rather park it for now and leave the data clipped to SA Boundary, which is actually fine. 
Please advise.

**Comment by dimasciput** [comment]
@jeremyshelton we haven't had a chance to address this last sprint, if you want we could prioritize this ticket for the next one. What do you think?

**Comment by timlinux** [comment]
Conclusion from our sprint planning call: Let's finish this up if it is in the order of ~1/2 days work.

**Comment by dimasciput** [comment]
@jeremyshelton this has been added to live site, please test it.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
This seems to be working fine. 
A few small adjustments needed. 
1. Please group the province and country filters into separate drawers called 'South African Province' and 'Neighboring Country' (as per the image below).
2. Please remove red lines from filter selections for neighboring countries (but please do not remove these for provinces)
3. Default selection should be all data within SA boundary only.

Thanks
![IMG_4969](https://user-images.githubusercontent.com/44292029/165061758-4e3b4219-ee9e-4053-9879-52194a6c5637.jpg)

**Comment by dimasciput** [comment]
@jeremyshelton 
The first requirement stated this :
```
We suggest this be included by adding a new sub-drawer underneath 'province' with dropdown for neighboring countries. The drawer name can be changed from 'Province' to 'Province and Neighboring Country'
```
So the few adjustment you proposed may take more time than we planned and are also not included in this ticket. So perhaps could you create another ticket?

**Comment by jeremyshelton** [comment]
@dimasciput 
**We suggest this be included by adding a new sub-drawer underneath 'province' with dropdown for neighboring countries. The drawer name can be changed from 'Province' to 'Province and Neighboring Country'**

👆But this original request corresponds to requirement 1 (shown in the picture), so I think it should remain a part of this ticket? ...or perhaps my original request was not clear enough? @helendallas @timlinux 
Also, note the difference between 'drawer' and 'sub-drawer'.

**Comment by helendallas** [comment]
I cant check as I cant see any spatial filters....I have tried HArd refresh but still nothing

![image](https://user-images.githubusercontent.com/45286876/165066841-2671ee35-a3b5-4fde-a6ce-da247e09b74d.png)

**Comment by dimasciput** [comment]
@helendallas it's only available on the live site because it's a data issue

**Comment by dimasciput** [comment]
> point_up_2But this original request corresponds to requirement 1 (shown in the picture), so I think it should remain a part of this ticket? ...or perhaps my original request was not clear enough? @helendallas @timlinux
Also, note the difference between 'drawer' and 'sub-drawer'.

I thought from the meeting we're going to merge this under one drawer and call it **Province and Neighboring country**. These requests are more difficult than we planned, basically we have to change again the layer that produces the boundary (separate the layers), change the logic on how to check whether the site is inside the correct boundary or not, change the spatial scale filter, change the GBIF harvester logic. It might take 2-3 days. 

@helendallas @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput the original request was for a **new sub-drawer** underneath 'province' with dropdown for neighboring countries. The **drawer** name can be changed from 'Province' to 'Province and Neighboring Country'

...in other words, to have the SA Provinces and Neighboring Countries grouped into **separate sub-drawers** within the overarching drawer called 'Province and Neighboring Country'.

My apologies if this was not clear enough in the original ticket. 

As it stands, for me it is confusing having SA Provinces and Neighboring Countries all under the same dropdown.

If this is going to suck up 3-5 days of time, I suggest we revert back to what we had prior to adding neighboring countries....but this should be a group decision - @helendallas @timlinux your thoughts?

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 

What is there now is what I understood from the ticket and our discussions.

It will be easy to unclick neighbouring countries if one only wants data in SA.

I am happy with it as it is

**Comment by helendallas** [comment]
sorry I didnt mean to close the ticket

**Comment by jeremyshelton** [comment]
OK thanks @helendallas 
I'm happy to go with the group vote on this 👍

**Comment by helendallas** [comment]
@jeremyshelton I reckon as long as we indicate to users - especially SANBI who will use data for the NBA - that we have included sites on transboundary rivers of neighbouring countries then it will be fine. 

Can I close the ticket?

**Comment by jeremyshelton** [comment]
@helendallas 👍
