### ISSUE TITLE
Water Quality

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2787]
This is a placeholder for the upcoming water quality module.

We expect to have an API access that lets us pull data from  https://waterportal.rwb.rw/location_info/WQ51

The process for developing the module will be:

@Deborahcyu and RBIS team to have a follow up meeting with the Rwandan Water Board to confirm data access via API details and any restrictions in how we may use the data.

RBIS Team to have an internal meeting to plan out the requirements.

RBIS team to then meet with @timlinux and @helendallas to present their requirements and we will help to mock up the user experience in RBIS.

Kartoza and FRC will then go and plan developer time and a timeline for implementation.

**Comment by timlinux** [comment]
Point data are enumerated as a long json object in the source of the page:

![image](https://user-images.githubusercontent.com/178003/134477282-f53cb770-ac01-4ac4-b87a-008253ffe9a6.png)

**Comment by helendallas** [comment]
RBIS project finished, closing ticket
