### ISSUE TITLE
Plan how to include thermal and wetland water quality data in drawers

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2788]
At the moment we have the following:

![image](https://user-images.githubusercontent.com/45286876/134498923-4fb79d51-e669-4b0a-9a9a-5099a39a7aae.png)

We need to make provision for non-biodiversity data, including 

- water temperature data - and associated components of the thermal module
- water quality data for wetlands

I would like to propose that we change to label for Module to **Biodiversity Module**, 
and then add in a new Module - potentially called Abiotic Module or Thermal Module and or  Water Quality Module?

I am finding out if the wetlands wq data is always associated with biodiversity data, in which case it will be treated exactly as in the current FBIS, where abiotic data are served as companion data and can be selected by ticking **Abiotic** in the **Module** drawer
![image](https://user-images.githubusercontent.com/45286876/134499968-05f9ec2f-e89a-4059-8d35-675ffaa19ce7.png)

However I suspect this data is independent, which then makes sense to have in is own drawer or grouped with water temp?

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/138254200-ebc9703e-c553-4e83-a3c1-03a1dc7379a3.png)

We can prioritise water temperature and water quality as new modules for now and then Helen and FRC team will figure out which other criteria to all filtering on.

Helen to share informative text to use on tooltips when you hover over them.

For the items we should use nice icons like we do in the biodiversity module.

Filtering will subselect sites and site visits so you will only see site visits on a site that match the criteria.

**Comment by helendallas** [comment]
Thanks Dimas - I will close this ticket for now although we might need to revise text at some stage but it needs a discussion with the FRC team

**Comment by helendallas** [comment]
@dimasciput 

Please rename Drawer: **Abiotic Module**
Please rename Temperature: **Water Temperature**
Please rename Abiotic: **Physico-chemistry**

Then we can close

**Comment by helendallas** [comment]
@dimasciput  Please can you also rename Abiotic data: **Physico-chemical data** in the detailed dashboards.

![image](https://user-images.githubusercontent.com/45286876/142407161-2657e67a-51d0-48bf-b76b-0d6605148512.png)

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput This looks fine on testing. Please roll out to live, than I can close the ticket.

**Comment by helendallas** [comment]
Thanks looks good on live, closing ticket
