### ISSUE TITLE
GBIF records mismatch

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2798]
1. If I select Reference category: Database and search FBIS Data only I get 259,943 records.
Then If I turn on GBIF in data sources this increases to 314,250 records. **Difference = 54,307** suggesting that there are only 54,307 records on available from GBIF? Surely this in incorrect?

2. However, if I then unselect the reference category filter I get 398,626 records for FBIS and 500,662 records for FBIS+GBIF. **Difference = 102,036**

I would expect the difference in 1 to be greater than the difference in 2 because that should take into account data from GBIF + other databases (Like CapeNature State of Biodiversity etc), but this is not the case. 

Any thoughts on what might be happening here @helendallas @dimasciput ?

**Comment by helendallas** [comment]
@jeremyshelton Please check if this is still an issue
