### ISSUE TITLE
Site code generator bug

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2808]
![image](https://user-images.githubusercontent.com/1979569/135237365-8c4a54e8-3909-4603-95d5-f12ce12707e8.png)

The whitespace from the river name should be removed when generating the site code.

**Comment by dimasciput** [comment]
fixed on testing

**Comment by helendallas** [comment]
@dimasciput I am checking on testing but white space is still there...

![image](https://user-images.githubusercontent.com/45286876/135580799-6ebb7484-51a6-4507-b9f1-315557fa9540.png)

**Comment by dimasciput** [comment]
Hi @helendallas I only fixed the site code generator in the site edit page, I haven't fixed the existing site codes error. Will do that in the live site.

**Comment by helendallas** [comment]
Ji @dimasciput Okay thanks, then it seems to be working fine. You can roll to live

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton this is fixed in live site

**Comment by helendallas** [comment]
Closing

**Comment by aneriswanepoel** [comment]
Site code not in the correct format (live site):
![image](https://user-images.githubusercontent.com/55532903/170934076-53825e11-d58c-4a6c-8cd0-ddf6dd5f7aec.png)
 @helendallas @dimasciput
