### ISSUE TITLE
Incorrect country error

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2818]
When I update the Geomorphological Zone of a site and click Save, I get the message "Site is not in the correct country" even though the site is in South Africa:

![image](https://user-images.githubusercontent.com/55532903/137289326-90fdfa75-28f9-4b84-b915-891c5e6125ab.png)

![image](https://user-images.githubusercontent.com/55532903/137289404-5d595998-ae1a-4fa9-bda0-a66aef33fb21.png)

@dimasciput

**Comment by helendallas** [comment]
Fixed, closing
