### ISSUE TITLE
Fish data download issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2819]
Hi @dimasciput 

I have just done a full fish data download, and the following issues have been noted:

- No Origin data are coming through.
- Large amounts of data have missing Endemism information.

This must be an error, because all fish taxa on our master list do have origin and endemism categories assigned?

There is also no 'Source' for records for 'Published report or thesis' or 'Peer-reviewed scientific article'.

Here is the full FBIS fish data download from today (GBIF data included) for you to look at.

Excel file: https://docs.google.com/spreadsheets/d/117T1ewlnSAbpGZd027ibB6Z6YBu4z84h/edit?usp=sharing&ouid=110481595245278648642&rtpof=true&sd=true

Csv file: https://drive.google.com/file/d/1FsamS2HhUO_bMDP0uXpDN3t2L7Jmgjfm/view?usp=sharing

@helendallas @timlinux

**Comment by jeremyshelton** [comment]
@dimasciput have you managed to change the source for Peer-reviewed scientific articles?

**Comment by jeremyshelton** [comment]
@dimasciput I see that the Source for Peer-reviewed scientific articles is still blank. 
Attached is a download of forth from the Western Cape Province from this morning.
Please advise on the easiest way to populate the source field. 
Thanks
[86f1f405b357c9fbc709120c0748d0bd3930ee41def7c33d0060a5ae3908f28c.xlsx](https://github.com/kartoza/django-bims/files/7473005/86f1f405b357c9fbc709120c0748d0bd3930ee41def7c33d0060a5ae3908f28c.xlsx)
[86f1f405b357c9fbc709120c0748d0bd3930ee41def7c33d0060a5ae3908f28c.csv](https://github.com/kartoza/django-bims/files/7473006/86f1f405b357c9fbc709120c0748d0bd3930ee41def7c33d0060a5ae3908f28c.csv)

**Comment by jeremyshelton** [comment]
@dimasciput any update on this ticket?

**Comment by dimasciput** [comment]
@jeremyshelton checking it now

**Comment by helendallas** [comment]
@dimasciput The source is correct in the Source References, but is not being pulled down in the csv files. I am checking csv again.

![image](https://user-images.githubusercontent.com/45286876/145179640-ffb5ed40-0a1b-43f6-97f9-9c6b65745b56.png)

**Comment by dimasciput** [comment]
this is deployed to **testing**.

**Comment by helendallas** [comment]
@jeremyshelton please can you check this

**Comment by jeremyshelton** [comment]
@helendallas I am literally busy testing this tight now 😅

**Comment by jeremyshelton** [comment]
Looking good.
Thanks @dimasciput 
Closing ticket.
