### ISSUE TITLE
Water temperature data uploader

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2828]
From https://github.com/kartoza/django-bims/issues/2614

Steps:

- Select an existing site or add a new site (exactly as before)
- Click “Add water temperature data”
- Select dates of water temperature logging period: Start date, End data (If this can be automatically picked up from the data then that would also be fine). Tim: Lets parse the file rather
- Is your data for a one year period? Yes/No (If this can be automatically picked up from the data then that would also be fine) - Tim: We use the start date to initiate the annual period and in the thermagraph we only consider the 12 month period following the start date. We will not discard any date that exceeds the user data.
- For sub-daily water temperature data: Select Logging interval: Dropdown comprising: 0.5h, 1h, 2h, 3h, where h = hours.
- Please also include option to add daily data (minimum, mean and maximum) - given the neat graphs Dimas showed us. Tim: Can be implemented in bullet above as a 24hr interval
- Browse to csv

See the sample files here https://github.com/kartoza/django-bims/issues/2614#issuecomment-869508338

**Comment by helendallas** [comment]
@dimasciput I added data for one year to the site: G2EERS-JONKE. It appears to have uploaded successfully as I can see it when I click on Temperature -  although I cant check it as the data are not visualised yet.

![image](https://user-images.githubusercontent.com/45286876/140083026-66e8aa29-10b3-4574-9de7-519d2838f183.png)


The testing site no longer has the option to upload water temperature data? 



@Fanevanjanahary @dimasciput Have you tested the upload for all the logging intervals and for different start and end times? on testing? 

Please can also change the Word: Temperature to **Water temperature**

**Comment by timlinux** [comment]
See https://github.com/kartoza/django-bims/issues/2779

**Comment by helendallas** [comment]
@dimasciput for this:
Please also include option to add daily data (minimum, mean and maximum) - given the neat graphs Dimas showed us. Tim: Can be implemented in bullet above as a 24hr interval

Can I only add Mean, or is the functionality to upload Min and max as well. as per the file in dropbox
Daily_Mutale Bridge Daily data.xlsx

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary I am trying to upload more data
https://testing.healthyrivers.kartoza.com/water-temperature-form/?siteId=9885

But it seems to be "processing"for a long time

**Comment by helendallas** [comment]
Closing this ticket as issues captured in #2614
