### ISSUE TITLE
Replace Water Management Areas with correct WMAs 2016

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2832]
The WMAs included in FBIS are the old ones. These were replaced in 2016 with a consolidated version of 9 WMAs. 

![image](https://user-images.githubusercontent.com/45286876/138689843-ae83bf50-826f-4606-a0ba-fc00adbd94ea.png)

The shape file etc have been added to the Thermal folder and shared with Amy. The metadata can stay the same. 
https://www.dropbox.com/sh/86u5maad4zau6bs/AAB4eKyuW8LgDNgLo6TohyqVa?dl=0

**Comment by timlinux** [comment]
@amyburness we will pass this along to SANBI to work on once they have been trained up.

**Comment by helendallas** [comment]
On hold for SANBI to do once training has been completed

**Comment by helendallas** [comment]
This will be actioned by Kate Snaddon FRC, so closing ticket on this repository

**Comment by KSnaddon** [comment]
@dimasciput and @amyburness This has been done and the spatial layer and filter are both correct.

**Comment by helendallas** [comment]
Thanks closing ticket
