### ISSUE TITLE
Spatial layer - Thermal framework

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2835]
We need a new layer and filter added, named "**Thermal Framework**". This is part of the Thermal module, see ticket #2674 

**First** @NickRivers-Moore needs to add two columns to the Thermal framework.dbf file to include categories for:

- **System Resilience**: Very high Resilience, High Resilience, Medium Resilience, Low Resilience, Very low Resilience(using the categories in Dallas and Rivers-Moore 2019, manual)
- **Model Accuracy**: Very high Accuracy, High Accuracy, Medium Accuracy, Low Accuracy, Very low Accuracy(using the categories in Dallas and Rivers-Moore 2019, manual)

**Nick** - please also rename columns to Thermal Zone, System Resilience, System Resilience Category, Model Accuracy, Model Accuracy Category.

**Next:** Amy needs bring in layer to FBIS. When the user clicks on the map, the full set of attributes should be shown, except for area and perimeter.
Metadata for this layer "i" is provided in the word doc file.

**Next**: Amy needs to add these as filters in the Spatial filter drawer:
Drawer label should be : **Thermal Framework**
Then there should be 3 sub-categories in this drawer:

- Thermal Zone: Upper, Lower
- System Resilience: Very high Resilience, High Resilience, Medium Resilience, Low Resilience, Very low Resilience
- Model Accuracy: Very high Accuracy, High Accuracy, Medium Accuracy, Low Accuracy, Very low Accuracy

The user can then click the box to return a subset of the data/sites.

Please note use uppercase for first letter of each word.

Files are in the shared dropbox folder:
FRC_Kartoza Thermal Module/Spatial Layers and filters/Thermal framework

**Comment by amyburness** [comment]
@dimasciput I have uploaded the thermal layer to maps.kartoza.com. Please let me know if there are any issues or fixes needed.
![thermal geo](https://user-images.githubusercontent.com/77841514/139814534-ece52c41-a72c-4189-9a6e-0163ecfbfd8f.png)

**Comment by amyburness** [comment]
@dimasciput there may be an issue with the data of this one I am looking at it now i'll let you know when it is solved.

**Comment by amyburness** [comment]
@helendallas @NickRivers-Moore There is the same quin_id issue with this layer where the same quin_id is assigned for 2 different places. 
![thermal quin issue](https://user-images.githubusercontent.com/77841514/140028601-7ab0ceac-ae67-4961-9831-cfaae138bc05.png)

![thermal quin issue 2](https://user-images.githubusercontent.com/77841514/140028593-e3af95cc-31fd-4552-9672-563cbfce3fff.png)

**Comment by NyakudyaA** [comment]
> @helendallas @NickRivers-Moore There is the same quin_id issue with this layer where the same quin_id is assigned for 2 different places. ![thermal quin issue](https://user-images.githubusercontent.com/77841514/140028601-7ab0ceac-ae67-4961-9831-cfaae138bc05.png)
> 
> ![thermal quin issue 2](https://user-images.githubusercontent.com/77841514/140028593-e3af95cc-31fd-4552-9672-563cbfce3fff.png)

Maybe you need to merge them if it is really meant to be like that

**Comment by helendallas** [comment]
@amyburness Glad you picked this up – there is not a mistake here, but it has to do with how the quinary catchments (a fifth level of catchments) were defined.  Each fourth-level (quaternary) catchment was broken down into three categories of landscape heterogeneity [see Subquinary field which lists these as a 1, 2 or 3].  This means that each quaternary catchment consists of AT LEAST three quinary polygons, BUT sometimes there may be more than one instance of a type 1 or 2 or 3, so that there may be two or more quinary polygons for with the same ID as they represent the same type within the same quaternary catchment. i.e. there are more polygons in the shapefile than there are record Ids.

**Comment by helendallas** [comment]
From Amy:

Do I then assign the same flow type metric subset values to both of the records with the same quin id?
 
From Nick: YES

**Comment by amyburness** [comment]
@helendallas @NickRivers-Moore 
Thanks I will do that.

**Comment by timlinux** [comment]
Can you give a status update on this please @amyburness ?

**Comment by amyburness** [comment]
@timlinux this has been published to Geoserver. I will publish it to geocontext and FBIS with the other today.

**Comment by amyburness** [comment]
@timlinux @helendallas
Update:
Current - Thermal Framework is up as layer in the Layer selector.
Today - Adding as a filter to the spatial filters.
![image](https://user-images.githubusercontent.com/77841514/142371231-195ea782-c22a-40e3-a6e7-32790beba79a.png)

**Comment by amyburness** [comment]
@helendallas @timlinux 
Update:
*the thermal layers are ready to go published on all the platforms and grouped etc.  They too are affected by the Geocontext memory/ cores issue  but it should all be up and running tomorrow.

**Comment by helendallas** [comment]
thanks @amyburness Please can you reorder the legend:
Very high Resilience, High Resilience, Medium Resilience, Low Resilience, Very low Resilience

Not

![image](https://user-images.githubusercontent.com/45286876/144014204-a6c6dcb6-3de4-41f2-816d-2ad7ed1b35f3.png)

I am also just waiting confirmation from Nick that he wants resilience to be shown, thanks

**Comment by amyburness** [comment]
@helen 
done, we can use any of the data in the legend I'll wait for Nick's input. 
![image](https://user-images.githubusercontent.com/77841514/144018967-5be28ebc-fb18-463b-bd54-35fc96622f70.png)

**Comment by helendallas** [comment]
Brilliant thanks @amyburness Ok, when Nick responds I will hop on again

**Comment by helendallas** [comment]
Hi @amyburness Nick would prefer legend to use Thermal zones. 
Thermal Zone: Upper, Lower

The resilience and model accuracy can be extracted by clicking on a quinary. Thanks

**Comment by amyburness** [comment]
hi @helendallas 
I have updated the legend to be by zone do you want the name of the layer to be thermal Zone or can it remail Thermal framework as above. 
The Filters are also working and show as above.
Drawer label: Thermal Framework
Then there 3 sub-categories in this drawer:
Thermal Zone: Upper, Lower
System Resilience: Very high Resilience, High Resilience, Medium Resilience, Low Resilience, Very low Resilience
Model Accuracy: Very high Accuracy, High Accuracy, Medium Accuracy, Low Accuracy, Very low Accuracy

![image](https://user-images.githubusercontent.com/77841514/144194837-d32d4f18-7da3-4f88-926a-a95b9459e4a4.png)

I have not updated all of the location sites yet just a few as as a test.

**Comment by helendallas** [comment]
Thanks @amyburness My comments

The drawer name should remain Thermal framework.

I noticed some issues with filters.

![image](https://user-images.githubusercontent.com/45286876/144198241-fed62cb1-7571-489c-9f87-9a06d8e81e24.png)

Please order Upland before Lowland

![image](https://user-images.githubusercontent.com/45286876/144198326-55e16514-3927-418a-b8ab-8987f6e3e55c.png)
 Some categories missing and order

All resilience categories are in the file :

![image](https://user-images.githubusercontent.com/45286876/144198645-70531dcc-e848-41e0-b431-f51bbb48e7aa.png)

Thermal framework_categories.xlsx

![image](https://user-images.githubusercontent.com/45286876/144198777-c4b41a16-0cd7-40bc-9700-8e4b0226c563.png)

Again categories missing -  also when all are in please always order as discussed perviously, thanks

**Comment by helendallas** [comment]
Can you also please change the colours to light green for upland and dark green for lowland...it will be easier then to see the sites

Also filters not working, see

![image](https://user-images.githubusercontent.com/45286876/144199689-5979ec44-53d2-4045-9c09-8c0c5280f3ef.png)

**Comment by amyburness** [comment]
@helendallas 
* colours for upland and lowland Updated
* Draw name corrected and all subcategories present, @dimasciput is there a way to get the categories to not show alphabetically but rather in order of class? eg. Very High, High, Meduim, Low and Very Low and Upland Before Lowland
![image](https://user-images.githubusercontent.com/77841514/144553961-feab4be3-9241-47b4-8ceb-b34e0972c771.png)

**Comment by dimasciput** [comment]
> Draw name corrected and all subcategories present, @dimasciput is there a way to get the categories to not show alphabetically but rather in order of class? eg. Very High, High, Meduim, Low and Very Low and Upland Before Lowland in the filters?

Unfortunately, it's not possible at the moment.

**Comment by helendallas** [comment]
@amyburness Filters need checking, don't think they are working as they should. see hydrological region ticket

**Comment by helendallas** [comment]
So @amyburness @dimasciput 
There are 23,113 sites on FBIS

![image](https://user-images.githubusercontent.com/45286876/152933907-7b77ef30-f3c3-4d64-aa69-b8b3a9e7056e.png)

However if I apply the System Resilience filter, only 177 sites are returned

![image](https://user-images.githubusercontent.com/45286876/152934042-751fae52-12f2-4c5f-89d8-2dc0af6bda42.png)

Please investigate why this is happening, thanks

**Comment by amyburness** [comment]
@dimasciput 

For the filter red lines for the thermal framework we need to updated they are not referencing the right layer (thermal_framework).
![image](https://user-images.githubusercontent.com/77841514/154153786-bf88c9aa-cfa6-4bd4-a8ca-8b040997f77d.png)

Can you change the requests for each too something like the below:

For Thermal framework Filter
https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfsSERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=**thermal_framework**&TILED=true&STYLES=red_outline&CQL_FILTER=zone%20in%20(%27Lowland%27)&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=3757032.814272985%2C-5009377.085697312%2C5009377.085697313%2C-3757032.814272984

For System Resilience
https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfs?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=**thermal_framework**&TILED=true&STYLES=red_outline&CQL_FILTER=thermal_resilience_category%20in%20(%27Low%20Resilience%27)&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=3130860.6785608195%2C-3130860.6785608195%2C3757032.8142729835%2C-2504688.5428486555

For Model Accuracy
https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfs?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=**thermal_framework**&TILED=true&STYLES=red_outline&CQL_FILTER=model_accuracy_category%20in%20(%27High%20Accuracy%27)&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=3130860.6785608195%2C-2504688.542848654%2C3757032.8142729835%2C-1878516.40713649

**Comment by helendallas** [comment]
@dimasciput @amyburness 

Thermal framework layers looks good but filters not working:

Upland and lowland does not return all the relevant sites

Resilience: 405,108 sites (FBIS) but with all filters clicked only 5,612 sites

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22group,thermal_resilience%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

Model accuracy - same issue as for resilience.

PLease check and revert soonest, thanks

**Comment by dimasciput** [comment]
![2022-02-24_16-44](https://user-images.githubusercontent.com/1979569/155499554-1ce28ffc-d12f-4bfd-96f0-6b232160c890.png)
![2022-02-24_16-43](https://user-images.githubusercontent.com/1979569/155499564-c45902f5-778c-442d-8927-1588cdf7ed7e.png)

The red line is now showing up.

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/155500420-7422ae5f-3ff1-4251-9cb7-8cfa2319865a.png)

@helendallas currently fetching thermal data for all sites

**Comment by helendallas** [comment]
Thanks @dimasciput . Still only 144,385 sites showing when all resilience categories are clicked.

![image](https://user-images.githubusercontent.com/45286876/155945928-968cac87-fc17-454c-a419-0eca413884d6.png)

Is data still being fetched?

**Comment by helendallas** [comment]
@amyburness Please cna you also speak to this ticket. Why are there relatively few sites , about 1/4 being returned. Please read ticket, thanks

**Comment by amyburness** [comment]
@dimasciput 

Hey Hey I am having a look at the Location sites on FBIS for the Thermal Framework data an I have found that not all of the points have the location context for the thermal framework data.
Thermal Framework
System Resilience
Model Accuracy
I don't think all of the points are harvesting data from Geocontext.
I think there may be a similar issue for
Hydrological regions
Hydrological region flow type

![image](https://user-images.githubusercontent.com/77841514/158576883-a225db1b-abd6-46d7-bcbb-58108abc984a.png)
![image](https://user-images.githubusercontent.com/77841514/158576919-442dd304-1caa-4c82-ba44-404985905da7.png)

**Comment by helendallas** [comment]
So why is all data not been harvested?  I suspect there is an issue with geocontext.

**Comment by helendallas** [comment]
Anything more on this @dimasciput @timlinux ? 
I recall that at our last meeting you spoke about the geocontext issues that were being experienced. It would be good to resolve this.

**Comment by helendallas** [comment]
Most sites now have thermal framework geocontext data, so closing ticket
