### ISSUE TITLE
Spatial layers - Hydrological Region 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2836]
We need a new layer and filter added, named "**Hydrological Region**". This is part of the Thermal module, see ticket #2674

First @NickRivers-Moore needs to revise the hydrological_regions_dd.dbf file to the correct WMAs as in the edited file:
Edited hydrological_regions_dd.xlsx

Nick also needs to provide a descriptive name (if possible) for each hydrological region that will be included in the filter

Next: Amy needs bring in layer to FBIS. When the user clicks on the map, the full set of attributes should be shown, including 
**Hydrological Region, Name, Rainfall Region, Primary Catchments, WMAs**

Metadata for this layer "i" is provided in the word doc file.

**Next:** Amy needs to add these as a filter in the Spatial filter drawer:
Drawer label should be : **Hydrological Region**
Then there should be 2 sub-categories in this drawer:

- Hydrological Region: Number and name (if possible)
- Flow Regime Type: number (see ticket #2837 )

The user can then click the box to return a subset of the data/sites.

Please note use uppercase for first letter of each word.

Files are in the shared dropbox folder:
FRC_Kartoza Thermal Module/Spatial Layers and filters/Hydrological regions

**Comment by dimasciput** [comment]
@amyburness let me know if you have published it to maps.kartoza.com.

**Comment by amyburness** [comment]
@dimasciput the layer is published and styled on maps.kartoza.com. Please let me know if there are any issues or fixes needed
![hydrological region](https://user-images.githubusercontent.com/77841514/139814028-91e49fd4-fe8c-4fee-8c7d-f8fc01cfca21.png)

**Comment by timlinux** [comment]
@amyburness can you please publish this in geocontext and then into FBIS? Please ask @NyakudyaA and @Fanevanjanahary for help if you need to know how the process works (and update our docs in the process if they are not clear / complete).

**Comment by amyburness** [comment]
@Tim yes I will do so today

**Comment by amyburness** [comment]
@timlinux @helendallas 
Update: 
Current - Horological regions up as layer in the Layer selector (made it slightly see through by default so that the flow regime types can be seen below as discussed @helendallas) .

Today - Adding as a filter to the spatial filters. 

![image](https://user-images.githubusercontent.com/77841514/142370181-a0a25616-f7a7-41f3-a20a-0380cd3a5a5c.png)

**Comment by amyburness** [comment]
@helendallas @timlinux 
Update: 
* The Hydrological Regions have been uploaded and also made a filter. 
* @dimasciput can you do the location sites background update for all of the points?
![image](https://user-images.githubusercontent.com/77841514/143878369-816d4801-0a91-424e-b339-b87cee86a432.png)

**Comment by amyburness** [comment]
@helendallas 
I have update the layers and filters and you should be able to view them all now. 
as per above I have made:
Drawer label : Hydrological Region
Then 2 sub-categories in this drawer:
 * Hydrological Region: Number and name (if possible) (Currently by Name)
 * Flow RegimeType: Number (see ticket Spatial layers - Flow Regime Type #2837 )

@dimasciput I have updated a few of the location sites as a test can you do the rest from the back-end? 

![image](https://user-images.githubusercontent.com/77841514/144191382-98cc2bd8-3839-41e4-9997-76862e7c4be2.png)

We also rounded the values and made for example area and perimeter more human friendly.

**Comment by helendallas** [comment]
Ok thanks @amyburness I cant see this yet so assume it is still being rolled out

![image](https://user-images.githubusercontent.com/45286876/144200592-fca49887-904c-4e7f-819d-af61f4d244f2.png)

**Comment by helendallas** [comment]
So @amyburness @dimasciput 
For all existing filters, when they are selected, the area is outlined in red. Then all sites within that Red outline area get returned. See ecoregion below:
![image](https://user-images.githubusercontent.com/45286876/144578379-bcde537a-3d0a-4e3a-bd29-5476b205b514.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,3%20LOWVELD%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=


The red border is missing for all the new thermal layers, and not all sites are returned.....

see hydrological regions

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,hydrological_regions,Western%20Cape%20(winter)%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

![image](https://user-images.githubusercontent.com/45286876/144578727-021e6566-f7d9-4d4c-aab3-7244fa3671be.png)

But only 41 sites

Without the filter applied, you can see there should be many more sites...
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

![image](https://user-images.githubusercontent.com/45286876/144578923-4dd40ed3-cf29-4031-98fc-ed133eebf09f.png)

**Comment by amyburness** [comment]
@helendallas taking a look

**Comment by amyburness** [comment]
@dimasciput 
I think that not all the points have been harvested from the following Geocontext location contexts/groups. Can you Harvest them all in the background? 

![image](https://user-images.githubusercontent.com/77841514/150536820-86ed05dc-283f-4ea5-8168-fa5eb6e75559.png)

![image](https://user-images.githubusercontent.com/77841514/150536483-86128b3e-3d01-490e-854b-4c0ba5c33c66.png)

**Comment by amyburness** [comment]
Hi there @dimasciput 

1. Issue not all the points are showing: I don't think that not all the points have harvested the information from the geocontext services I added.

2. No red line around the filter area: So I had a look at the requests and there is something weird going on the request should reference the name of the layer in GeoServer for example (hydrological_regions_dd). the request needs to be changed  to reference the proper name in Geoserver. 

I think the request should be something like this  https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfs?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=kartoza:hydrological_regions_dd&TILED=true&STYLES=red_outline&CQL_FILTER=hydrological_name in ('Western Cape (winter)')&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&BBOX=2504688.542848654,-3757032.814272985,3757032.814272982,-2504688.542848657

The same problem is true for the other filters for the geoserver layers I added following the RBIS documentation.
They come from the geoserver layers
kartoza:mv_flow_regime_type_full
kartoza:thermal_framework

**Comment by helendallas** [comment]
@dimasciput @amyburness Any solutions here yet?

**Comment by dimasciput** [comment]
@helendallas will look into it Thursday, I think the solution is just to refetch the geocontext data.

**Comment by dimasciput** [comment]
@helendallas @amyburness the red line is showing up now, and I have started the script to fetch the geocontext data. It will take a while.

**Comment by amyburness** [comment]
@dimasciput the red line is showing for the Hydrological region filter but not for:
*Hydrological Region Flow Type
* Thermal Framework
* System Resilience
* Model Accuracy

I'll have a look at the requests and see the issues and layers they need to pull from and give you the information.

**Comment by amyburness** [comment]
@dimasciput 
can you update the red outline for the filter Hydrological Region Flow Type. 
![image](https://user-images.githubusercontent.com/77841514/154148702-386fd6c5-ce96-4d5d-8c77-99d841d26a94.png)

The request is not referencing the correct layer (mv_flow_regime_type_full) and filter (flow_region_type) I think for example the requests need to look something like this:

https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfsSERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=mv_flow_regime_type_full&TILED=true&STYLES=red_outline&CQL_FILTER=flow_region_type%20in%20(%271.01%27)&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=2504688.542848654%2C-5009377.085697312%2C3757032.814272982%2C-3757032.814272984

**Comment by helendallas** [comment]
Thanks this seems to be working now, closing ticket
