### ISSUE TITLE
Validate record and add delete site visit button

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2839]
There are 3 sites/records that have been validated but which are still showing as unvalidated, but they Validate button is not visible

![image](https://user-images.githubusercontent.com/45286876/139050285-766489be-371d-4a90-a615-4a21bca2959b.png)

**Comment by helendallas** [comment]
https://freshwaterbiodiversity.org/site-visit/list/?validated=[%22non%20validated%22]&o=date

**Comment by dimasciput** [comment]
add delete site visit functionality

**Comment by helendallas** [comment]
Thanks Dimas that great, still an issue with these 3 site/sampling dates.

They should be validated but still showing as unvalidated;  I am not sure why? 

Please can you change them in the backend, or show me how to change them

![image](https://user-images.githubusercontent.com/45286876/165249131-5746b8b9-6f28-4938-a4b8-8a756b0f4ecf.png)

https://freshwaterbiodiversity.org/site-visit/list/?validated=[%22non%20validated%22]&o=date&modules=21#

**Comment by helendallas** [comment]
Also seems to be the same issue with some for the fish data, shows as unvalidated, but the the Validate button has disappeared...

![image](https://user-images.githubusercontent.com/45286876/165250197-9451cf71-93f2-4678-83a3-14c19fca6ab3.png)

**Comment by helendallas** [comment]
@dimasciput Please check this a revert in the next sprint

**Comment by helendallas** [comment]
@dimasciput I am still not able to validate this record.

https://testing.healthyrivers.kartoza.com/site-visit/list/?validated=[%22non%20validated%22]&o=date&collectors=%5B562%5D  The validate button is missing.

**Comment by helendallas** [comment]
@dimasciput Please can you check what the issue is here. It is still an issue that these records are unvalidated, I think it may occur if the data are edited?????

The validate option has dissapeared

Here are some more examples:
![image](https://user-images.githubusercontent.com/45286876/172786450-b74552b9-676f-4b6a-afa2-38390032cf6f.png)

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket now.
