### ISSUE TITLE
"westdene pan nature reserve" should be called korsman bird sanctuary

### ISSUE THREAD

**Issue by FBIS-issues** [kartoza/django-bims#2850]
The site named as westdene pan nature reserve is commonly known and marked on maps as korsman bird sanctuary, please would you change it. 

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/3044">User information </a>
Browser: Chrome
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/#search/westdene%20pan%20nature%20reserve/taxon=&search=westdene%20pan%20nature%20reserve&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=
Screen resolution: 2560 x 1440

**Comment by helendallas** [comment]
This comes from GBIF, cannot be fixed in FBIS
