### ISSUE TITLE
Data sources should all be on by default: FBIS, GBIF and Virtual Museum

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2853]
@dimasciput we have two requests for the Data Sources functionality:
1. Please can we change the Data Sources default to GBIF data turned on.
2. Please can we add, within the Data Sources drawer, the option to turn FBIS data on and off.
@helendallas @timlinux 
<img width="419" alt="Screen Shot 2021-11-09 at 2 18 32 PM" src="https://user-images.githubusercontent.com/44292029/140923006-91376836-6f37-4db1-862a-d31a207d9e81.png">

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 
The default should be FBIS and GBIF turned on please, i.e. so that when a user first lands on the page, FBIS data is visible, and GBIF data is visible. 

![image](https://user-images.githubusercontent.com/45286876/145174897-e8e6f889-abaa-473b-aeda-0fd55e18b01b.png)

**Comment by helendallas** [comment]
Please can we also add Virtual Museum to be automatically clicked on
see #2946

**Comment by helendallas** [comment]
So to confirm, 
all Data Sources should be on by default, FBIS, GBIF and Virtual Museum
The user should be able to turn off all of these as needed
