### ISSUE TITLE
Data with no site visit

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2854]
@dimasciput  Aneri and I were checking the data in unpublished, and there are 8 records assigned to 3 different sites that have data but no sampling date , so there is no site visit.

I cannot find how to fix/check this in the back end.

Here are the details:
@aneriswanepoel  So none of these sites have site visits (sampling dates), although they have data

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22673%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

![image](https://user-images.githubusercontent.com/45286876/141420211-d245607f-9828-4a8a-a51b-c6fa4b5b7385.png)

B2KLIP-00011 Michiel Jonker
https://freshwaterbiodiversity.org/admin/bims/locationsite/27232/change/?_changelist_filters=q%3DB2KLIP-00011

B2UNSP-DWAAL Rob Palmer
https://freshwaterbiodiversity.org/admin/bims/locationsite/11111/change/?_changelist_filters=q%3DB2UNSP-DWAAL

C9KLEI-00002 OdonataMap
https://freshwaterbiodiversity.org/admin/bims/locationsite/48445/change/?_changelist_filters=q%3DC9KLEI-00002

Any ideas? why this happened and how to fix it?

**Comment by dimasciput** [comment]
This is fixed on live site
