### ISSUE TITLE
Issues when users sign up to testing site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2855]
We receive this email 

-----Original Message-----
From: Mail Delivery System <MAILER-DAEMON@kartoza.com> 
Sent: Wednesday, November 10, 2021 10:24 AM
To: fbis@frcsa.org.za
Subject: Undelivered Mail Returned to Sender

This is the mail system at host kartoza.com.

I'm sorry to have to inform you that your message could not be delivered to
one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own
text from the attached returned message.

                   The mail system

<gbif@kartoza.com>: host aspmx.l.google.com[108.177.15.27] said: 550-5.1.1
The
    email account that you tried to reach does not exist. Please try
550-5.1.1
    double-checking the recipient's email address for typos or 550-5.1.1
    unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser o2si49720412wry.513 -
gsmtp
    (in reply to RCPT TO command)

-- 
Dimas Ciputra - Software Developer
Email : dimas@kartoza.com
Tel : +62 812 1679 2585
Visit https://kartoza.com to find out about open source :
 •  Desktop GIS programming services
 •  Geospatial web development
 •  GIS Training
 •  Consulting Services

**Comment by dimasciput** [comment]
this shouldn't be an issue anymore

**Comment by helendallas** [comment]
Closing ticket, will reopen if issue persists once new user signs on to testing site
