### ISSUE TITLE
Layer description: Water Source Areas

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2856]
@dimasciput or @amy

please remove the text in blue highlight from the water source areas: ground water layer description: 
<img width="458" alt="Screen Shot 2021-11-15 at 1 26 33 PM" src="https://user-images.githubusercontent.com/44292029/141774446-7b0dbd96-75b2-412c-b0b2-675ac2cddbbe.png">

**Comment by NyakudyaA** [comment]
![swas-area](https://user-images.githubusercontent.com/2510900/141776291-b0883bf4-005a-4898-bff6-d7f06126e4cd.png)

Done @jeremyshelton

**Comment by jeremyshelton** [comment]
@NyakudyaA @dimasciput @amyburness 
The labels for the ground and surface water source areas are incorrect.
The groundwater layer has the surface water description and vice versa. 
Please swop them around.
Thanks

**Comment by amyburness** [comment]
@jeremyshelton can you send a screenshot

**Comment by amyburness** [comment]
@jeremyshelton  I have corrected it 
![image](https://user-images.githubusercontent.com/77841514/144233159-8b808ce7-9113-40ec-bf41-412cabcc1344.png)

**Comment by jeremyshelton** [comment]
Thanks @amyburness
