### ISSUE TITLE
Change to Conservation Status column in Master list

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2858]
@dimasciput we need to add in a new column to the taxon master list upload templates:

Conservation status  -> Conservation status (Global)
New column = Conservation status (National)

These changes need to be coded into the search bar/filtering, and added into CSV downloads. The existing CVS formats need to be used, just change the Conservation status to become 2 columns, called Conservation status (Global) and Conservation status (National)

@jeremyshelton I removed the csv examples as they were not all correct, especially algae, and we dont upload odonates, these are harvested from OdonataMap.

@dimasciput please ask if unclear

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux 

From Brenda Daly at SANBI:

We, unfortunately, did not budget for API development in this phase of the NBIS Project.
 
The information will be accessible from the website via a GUID, however, we are still in UAT as we migrate from BRAHMS version 7 to 8 and currently are unable to provide stable GUIDs.
 
We hope to finalise the migration before the end of February.

**Comment by jeremyshelton** [comment]
Not sure where that leaves us, but I'll touch base with Brenda on this again in March.

**Comment by helendallas** [comment]
On hold until SANBI revrerts

**Comment by jeremyshelton** [comment]
@helendallas I've followed up with SANBI on this, so lets see what they come back with...

**Comment by jeremyshelton** [comment]
@dimasciput is it possible to add 'National Conservation Status' as a field in taxon management + CSV downloads?
We can add this to the master list as a new column next to Conservation Status (global).
Then we can do the linking with the SANBI species pages when they provide us with links for the species pages.

**Comment by helendallas** [comment]
@dimasciput Please can you tackle this soon so that we can upload the both - to revise

@dimasciput we need to add in a new column to the taxon master list upload templates:

Conservation status -> Conservation status (Global)
New column = Conservation status (National)

These changes need to be coded into the search bar/filtering, and added into CSV downloads. The existing CVS formats need to be used, just change the Conservation status to become 2 columns, called Conservation status (Global) and Conservation status (National)

This ticket links to 
https://github.com/kartoza/django-bims/issues/2857

So best to do both at the same time.

**Comment by dimasciput** [comment]
@helendallas the csv has been updated with the new column. Regarding the filter, do you want to add a new filter sub panel called Conservation status (National) ?

**Comment by helendallas** [comment]
Will it be a problem if National categories differ from Global categories?

I suspect this will be the case. So We will need a tick button to show which to include for Global versus National.

Maybe 
https://freshwaterbiodiversity.org/admin/bims/iucnstatus/

should be renamed Conservation status. or else we have two separate tables in BIMS, one for Global ?IUCN and one for National?

**Comment by helendallas** [comment]
@dimasciput Has this been rolled to testing?  

**Can you confirm the  column headers:** which of the ones below?
Conservation status (Global) or Global Conservation status
Conservation status (National) or National Conservation status

Thanks

**Comment by dimasciput** [comment]
@helendallas yes this has been deployed to testing. 

Here's the updated headers : 
- Conservation status / Conservation status global ( you can use either one )
- Conservation status national

**Comment by helendallas** [comment]
Thanks @dimasciput

**Comment by helendallas** [comment]
Closing ticket as deployed to live
