### ISSUE TITLE
Endemism tool tips not updating

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2859]
Tool tips in the endemism categories in the search/filter bar on the left of the map are not consistent with the descriptions in the Bims. If possible can these update automatically when changes are made in the Bims descriptions/

![image](https://user-images.githubusercontent.com/45286876/141929402-5c817d77-bb6f-4815-a070-177b65b2e098.png)

![image](https://user-images.githubusercontent.com/45286876/141929287-e7c309a1-3b8f-410a-90ad-3d6e0492e742.png)

**Comment by dimasciput** [comment]
@jeremyshelton please test on testing site

**Comment by jeremyshelton** [comment]
@dimasciput this looks good 👍
Please deploy to production site.

**Comment by jeremyshelton** [comment]
I see this now on production site. 
Closing ticket.
