### ISSUE TITLE
Functionality to update threshold for temperature data

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#2872]
From https://github.com/kartoza/django-bims/issues/2615

> The owner of the temperature data needs to be able to update if possible. We can leave for now and use the threshold from the thermal zone for now, and then when I am adding data if it becomes a problem then we will need to add functionality for the owner of the temp data to change. This could happen at the time of uploading the temp data?

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, please deploy to production
