### ISSUE TITLE
We need to add sentry support

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2885]

**Comment by dimasciput** [comment]
we already did for fbis http://sentry.kartoza.com/sentry/freshwaterbiodiversity/ @timlinux

**Comment by timlinux** [comment]
Ah that is the old man in me forgetting that we have it. It would be good to take some technical debt time (maybe in the coming devops sprint) to address all the issues listed there so that we have a good signal to noise ratio.

**Comment by dimasciput** [comment]
this is added now
