### ISSUE TITLE
Testing site issues when creating new frog module

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2887]
@dimasciput I am trying to harvest GBIF data for the taxa in a new frog module created on testing site. However, it keeps getting stuck on species 25 or 28 of 134. I tried to leave the harvest running overnight last night, but that did not solve the issue. Any suggestions?
@helendallas @timlinux

**Comment by jeremyshelton** [comment]
@dimasciput OK after a few tries the harvest did work: 23661 records for 122 amphibian taxa. 

However, the multi-site overview and multi-site detaileddashboards don't seem to be working (they are not loading), so can't test if the endemism, origin, conservation status, water dependence etc are coming through. 

The taxon dashboards seem to be working OK though.

Spatial filters have disappeared from the testing site: none are available, making it difficult to test further: 
![Screen Shot 2021-12-04 at 1 29 32 PM](https://user-images.githubusercontent.com/44292029/144707813-c61c53e6-bbcb-4774-a2d2-964312a5cb79.png)

**Comment by jeremyshelton** [comment]
@dimasciput just a quick update that the testing site is still not working when I try to look at the recently-uploaded frog data. It gets stuck on 'Loading' the I try to do a frog data search from multiple sites: https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=2009&yearTo=2021&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=37&validated=&sourceCollection=[%22fbis%22,%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=
![Screen Shot 2022-01-10 at 3 08 16 PM](https://user-images.githubusercontent.com/44292029/148771213-49cc158a-e5fd-4734-a2bb-6e93404c2c2e.png)

Also, the site is not refreshing weekly to mirror the live site, but it should be.

@helendallas

**Comment by jeremyshelton** [comment]
**Update 18 Jan 2022**

@dimasciput testing site still getting stock on 'Loading' when I try to load the dashboard for amphibian data:
![Screen Shot 2022-01-18 at 2 50 51 PM](https://user-images.githubusercontent.com/44292029/149940755-01eee64b-d00f-4ed7-a390-0c17983d344b.png)

We need to try to resolve this before we add the new amphibian to the live site, so that we can test that the data on Endemism, Conservation Status...etc is all coming through correctly

@helendallas

**Comment by dimasciput** [comment]
most of the issues should be fixed now @jeremyshelton , but the site name is still an issue.

**Comment by jeremyshelton** [comment]
This has been fixed.
Thanks @dimasciput
