### ISSUE TITLE
We need to include the form to add Source Reference for water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2888]
Please can you include the "Source reference for records"form after adding water temperature data so that the metadata can be added. 
This then also needs to be shown in the Metadata Table in the Detailed dashboard. see #2748 

![image](https://user-images.githubusercontent.com/45286876/144567234-ad61f0d8-8358-4f5a-b969-2e4d11c1ddb6.png)

**Comment by dimasciput** [comment]
this is deployed  to testing

**Comment by helendallas** [comment]
Please can you include option to filter by author as well. This will make it easier to find an existing source reference.

**Comment by dimasciput** [comment]
![Uploading image.png…]()

@helendallas added in testing

**Comment by helendallas** [comment]
@dimasciput please confirm when author(s) filter has been added and this is deployed to live

**Comment by helendallas** [comment]
Thanks for adding Author(s) as a filter. 

Is it possible to be able to add a button. The work around is the add the Source reference first but this is more complex for the user.
![image](https://user-images.githubusercontent.com/45286876/154429992-9a24bb8c-02b2-4242-9cf3-62cb40712e8f.png)

So that if the report etc is not showing then the author can ask to add a new Source reference.

**Comment by helendallas** [comment]
Let me close this for now. I will add via Source References
