### ISSUE TITLE
Please add ability to add photo to the water temperature upload form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2889]
Please can you include the option to add a site image 

![image](https://user-images.githubusercontent.com/45286876/144567714-dfdb83ae-37ce-4cb9-b5d8-ef404aa1507b.png)

Add water temperature form:

![image](https://user-images.githubusercontent.com/45286876/144567810-f921cb3d-efa0-47ce-8f00-2eef0a32bbc5.png)

**Comment by helendallas** [comment]
Thanks, this is working fine, except for the date issue, please see ticket #2927 , repeated here

I uploaded 2009 water temperature data, and added a photograph, but today's date was added instead. I realise the water temperature is time series, so cannot select an actual date, but it is incorrect to give it today's date. It should rather be the year? 

![image](https://user-images.githubusercontent.com/45286876/151758589-cacd4508-1741-4b4d-ae0c-e061a72a6a7d.png)

https://testing.healthyrivers.kartoza.com/water-temperature/9980/?taxon=&search=H2ROOI-WORCE&siteId=9980&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9980&orderBy=name&polygon=&thermalModule=

**Comment by helendallas** [comment]
I will rather close new ticket I created.

**Comment by helendallas** [comment]
@Fanevanjanahary Any progress on fixing this?

**Comment by helendallas** [comment]
Not fixed yet @dimasciput @Fanevanjanahary 
This photo was added to water temperature for 2009 but has been given today's date.

**Comment by dimasciput** [comment]
@helendallas did you test in on testing? Unfortunately you have to reupload the image so it can get the correct date.

**Comment by helendallas** [comment]
I tested on testing, a while ago and noted the issue. then tried again on live today but still showing todays date

**Comment by helendallas** [comment]
Okay seems fine now, once photo is uploaded again, thanks

**Comment by helendallas** [comment]
@Fanevanjanahary PLease can you check this. I uploaded some photos to a site, but then they were not there later, and others were added to a different site.
Thanks

**Comment by helendallas** [comment]
@dimasciput 

Here is one example site - I added a photo to this site, but its not there, then I added a photo to a different site (G1WOLW-ABDAM) and that photo is now visible for E1ROND-KEURB

https://freshwaterbiodiversity.org/water-temperature/10358/2009/?taxon=&search=E1ROND-KEURB&siteId=10358&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=10358&orderBy=name&polygon=&thermalModule=&dst=&startDate=2009-01-01&endDate=2009-12-31


https://freshwaterbiodiversity.org/water-temperature-form/edit/?siteId=10358&year=2009
So not photograph, and then when I click on edit, I get a photo I uploaded for a different site: G1WOLW-ABDAM

**Comment by helendallas** [comment]
I have created a new ticket #2979 , closing this one now
