### ISSUE TITLE
Source reference issue

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2891]
I have tried to update the source reference for these but it just keeps creating new references. Please can you check what is going on.

![image](https://user-images.githubusercontent.com/45286876/145198924-644f46c4-d6a4-4586-a2ff-6b859181b7ab.png)

https://freshwaterbiodiversity.org/source-references/?&collectors=2729

It should all be the same source reference

**Comment by dimasciput** [comment]
https://freshwaterbiodiversity.org/source-references/?&collectors=2729 fixed now
