### ISSUE TITLE
Blyde river: opsaridium peringueyi not extinct

### ISSUE THREAD

**Issue by FBIS-issues** [kartoza/django-bims#2894]
In the blyde river (and i think the klaserie) opsaridium peringueyi is indicated as extinct (despite records of it). i have confirmed with dr francois roux of mtpa - it is not an extinct species.

thanks for a great product.

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/3076">User information </a>
Browser: Chrome
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/#search/BLYDERIVIER/taxon=&search=BLYDERIVIER&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=
Screen resolution: 1366 x 768

**Comment by dimasciput** [comment]
Resolved
