### ISSUE TITLE
RBIS testing site cannot test data more than once

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2896]
@dimasciput the RBIS TESTING SITE cannot allow us to test data more than once after we have got an error file corrected. We need to wait for the next day to retest the data. It keeps processing endlessly

![image](https://user-images.githubusercontent.com/64961274/149352029-cea36c25-68c1-4a0e-b3a9-8066e1636ad5.png)

**Comment by dimasciput** [comment]
@mmindje can you test again on testing please?

**Comment by mmindje** [comment]
Is it an issue in the system @dimasciput

**Comment by helendallas** [comment]
This is working now, closing ticket
