### ISSUE TITLE
Issue with GBIF harvest on Testing site

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2911]
@dimasciput I am having trouble harvesting data for 7 frog taxa in the testing site. The taxa do exist on GBIF and the taxon names in the master list match those on GBIF. Any idea why these are returning zeros from the harvest?

https://testing.healthyrivers.kartoza.com/uploaded/harvest-session-log/25-1643099094_YhPAMLQ.txt

Here is the csv I uploaded to a module called 'FrogTest'
[Error taxa tests - 25 Jan.csv](https://github.com/kartoza/django-bims/files/7932012/Error.taxa.tests.-.25.Jan.csv)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput for fixing this on Testing site. 
Please let us know as soon as it is deployed to live site so we can begin creating the new frog module.
Thanks

**Comment by dimasciput** [comment]
This is also deployed to live site

**Comment by jeremyshelton** [comment]
Thanks @dimasciput
