### ISSUE TITLE
We need a feature to add a call/song/ for species 

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2913]
We need a feature to add a call/song/ for species like frogs or birds on the individual species dashboard the way we can now add image to the species?

That is to help us add more birds songs for instance that were are soon receiving  from the Planet Bird song project

![image](https://user-images.githubusercontent.com/64961274/150953718-bd209508-83b7-4294-b3c6-a7025d503828.png)

**Comment by dimasciput** [comment]
@mmindje before we start implementing this feature please give us the sample data first.
