### ISSUE TITLE
Source references - need to be able to upload pdfs > 3mb

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2926]
At the moment, and pdf that is about 3mb or greater does no upload. small docs work fine.

Here is a problem doc that wont upload
[Uploading Dallas & Rivers-Moore 2012 WRC Water Temperature 1799-1-12.pdf…]()
c

**Comment by helendallas** [comment]
sorry not working
![image](https://user-images.githubusercontent.com/45286876/156130818-432407b2-d68d-486b-b5a9-20b9f7faf619.png)

**Comment by dimasciput** [comment]
@helendallas can you send me the pdf again, the above link is not working

**Comment by dimasciput** [comment]
@helendallas https://testing.healthyrivers.kartoza.com/source-references/?&q=test%20large%20data it's working fine for me the uploader. Can you screenshot your form before uploading, and share it here?

**Comment by helendallas** [comment]
here we go @dimasciput 

![image](https://user-images.githubusercontent.com/45286876/156135817-9cd078b5-2e49-42e6-a1af-96999bd1927e.png)

**Comment by dimasciput** [comment]
@helendallas for the authors, did you write it yourself or choose from the dropdown?

**Comment by helendallas** [comment]
I chose from the dropdown

**Comment by dimasciput** [comment]
@helendallas I couldn't replicate this issue in testing site, I uploaded the source reference here with the same details : https://testing.healthyrivers.kartoza.com/source-references/?&q=Water%20temperature%20and%20the%20ecological%20reserve.

What browser did you use?

**Comment by helendallas** [comment]
firefox

**Comment by helendallas** [comment]
Thanks @dimasciput I can use the one you added since a lot of the data are linked to that study reference. Then I will check again using google, maybe its a browzer issue?

**Comment by dimasciput** [comment]
But it's still on the test site, did you test it on the live site?

**Comment by helendallas** [comment]
Going to do now, will revert

**Comment by helendallas** [comment]
Still getting the error message????? even on google chrome
 I type in the date , is that correct
2012

And notes in blank.

**Comment by dimasciput** [comment]
@helendallas one second, I think I found the issue.

**Comment by dimasciput** [comment]
@helendallas please can you try it again on testing.

**Comment by helendallas** [comment]
Success 
![image](https://user-images.githubusercontent.com/45286876/156147255-5e4408fc-8df7-4a01-a1cc-9409e63e9718.png)
