### ISSUE TITLE
GBIF harvest - site code bug

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2928]
Site names are erroneously being generated from site descriptions and/or coordinates when harvesting frog data from GBIF. 
![unnamed](https://user-images.githubusercontent.com/44292029/151912256-3b0f78bd-4e2b-47b3-b451-b22c7045aeb9.png)

**Comment by jeremyshelton** [comment]
@dimasciput do you have a feel for how big a fix this is?
I know it is no longer a FBIS sprint, but we really don't want to have all of these wrong site codes up on the production site.
Please advise

**Comment by dimasciput** [comment]
@jeremyshelton the fix itself is pretty easy, but the time to fetch and generate all the missing site codes will take 2-3 days. Because there are about 11k new sites. I will start working on the fix tomorrow.

**Comment by jeremyshelton** [comment]
Thanks for fixing @dimasciput
