### ISSUE TITLE
GBIF harvest not working for some taxa

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2929]
The GBIF harvest from the frog master list resulted in six taxa returning zero data. However, these taxa are on GBIF and do have data associated with them. Looks like the same kind of issue that you had to fix on the testing site last week. 

Here are the taxa:
Fetching : Amietia delalandii
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=9311531&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)---------------------------------------------------
Fetching : Afrixalus spinifrons
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=2426562&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)---------------------------------------------------
Fetching : Afrixalus knysnae
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=2426576&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)---------------------------------------------------
Fetching : Afrixalus fornasini
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=2426566&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)---------------------------------------------------
Fetching : Afrixalus delicatus
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=2426573&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)---------------------------------------------------
Fetching : Afrixalus aureus
URL : http://api.gbif.org/v1/occurrence/search?taxonKey=2426558&offset=0&hasCoordinate=true&hasGeospatialIssue=false&country=ZA&country=LS&country=SZ
Expecting value: line 1 column 1 (char 0)

**Comment by dimasciput** [comment]
@jeremyshelton I can see the data in fbis : 
https://freshwaterbiodiversity.org/map/#search/Amietia%20delalandii/taxon=&search=Amietia%20delalandii&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=36&validated=&sourceCollection=[%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

https://freshwaterbiodiversity.org/map/#search/Afrixalus%20spinifrons/taxon=&search=Afrixalus%20spinifrons&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=36&validated=&sourceCollection=[%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=

**Comment by jeremyshelton** [comment]
@dimasciput ok - a ran a second GBIF harvest last night and that seems to have now added the data for these (that were missed in the first harvest).
Closing ticket.
