### ISSUE TITLE
Master list upload issues

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2930]
When uploading the Anuran master list to the production site, there were two taxa that were duplicated by FBIS when the master list was uploaded (Tomopterna adiastola, Vandijkophrynus nubicola), and two other taxa that were on the master list but did not show up on FBIS (Xenopus laevis, Xenopus muelleri). I manually fixed this via the admin page, but there is nowhere for me to manually update the attribute 'Water Dependence' for the Xenopus taxa: both should be classified as 'Obligate freshwater breeder'.

**Comment by dimasciput** [comment]
@jeremyshelton what do you mean by 'Water Dependence' attribute? Can we do that before? Or is this new feature?

**Comment by jeremyshelton** [comment]
@dimasciput it is a column in the Anuran master list that was added in taxon management. The same kind of thing as origin or endemism, but specific to frogs...

<img width="500" alt="Screen Shot 2022-02-01 at 7 22 15 AM" src="https://user-images.githubusercontent.com/44292029/151916893-e225ad3a-88e3-4be2-9bed-1f1606957a5e.png">

It is a column in the csv download, and we will request that this becomes a new filter in the next sprint.

**Comment by dimasciput** [comment]
@jeremyshelton you can add it here 
![image](https://user-images.githubusercontent.com/1979569/151917645-e93aa754-7303-4eea-9cb8-80f8d2d42d7b.png)

You can copy the data from other taxon in the same module.

**Comment by jeremyshelton** [comment]
@dimasciput OK cool - let me try that 👍

**Comment by jeremyshelton** [comment]
@dimasciput 

Order of columns in the .csv download: we need the water dependence column to be the next one after conservation status:

<img width="894" alt="Screen Shot 2022-02-01 at 8 26 21 AM" src="https://user-images.githubusercontent.com/44292029/151922317-db25298d-5296-4f5a-b388-8a613fc45f5b.png">

**Comment by jeremyshelton** [comment]
> @dimasciput OK cool - let me try that 👍

Done ✅

**Comment by dimasciput** [comment]
> @jeremyshelton Order of columns in the .csv download: we need the water dependence column to be the next one after conservation status

We couldn't do that at the moment, new attribute will always be the last header.

**Comment by jeremyshelton** [comment]
@dimasciput OK then. This is not urgent. 
We can look at it again at a later stage.
Closing ticket.
