### ISSUE TITLE
Landing page module summaries

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2931]
@dimasciput please add Anura.
Also please change the breakdown category for Fish and Anura to Conservation Status.
Thanks
<img width="1308" alt="Screen Shot 2022-02-01 at 8 58 50 AM" src="https://user-images.githubusercontent.com/44292029/151927971-3c8e1d4f-caa6-4360-82e6-5870e91471ac.png">
imas

**Comment by helendallas** [comment]
When a new Taxon Group is added, it should automatically be added to the headline dashboard.

**Comment by helendallas** [comment]
Thanks @dimasciput 

Please can you use the same colour palette that is FBIS

NOT
![image](https://user-images.githubusercontent.com/45286876/156528775-7d296826-ee51-4049-88ea-de867309c266.png)

RATHER
![image](https://user-images.githubusercontent.com/45286876/156529630-092ee861-f3d3-499b-94da-88a2b5ca56a5.png)

**Comment by jeremyshelton** [comment]
@dimasciput can you also please adjust the Algae breakdown to reflect division?
Thanks
<img width="702" alt="Screen Shot 2022-03-10 at 9 58 37 AM" src="https://user-images.githubusercontent.com/44292029/157615291-f7e9a712-91d3-4322-a633-cfce401df1cb.png">

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 
I just noticed that the invertebrates have a different look to the others when you scroll over, 

![image](https://user-images.githubusercontent.com/45286876/165302711-f6f29925-bb06-452c-a69a-3015e3789619.png)

Is it possible to change this to be like the others where you get the Ecological Category shown as the arrow hovers over it

**Comment by dimasciput** [comment]
I will take over this.

**Comment by dimasciput** [comment]
Fixed on testing

**Comment by helendallas** [comment]
Thanks @dimasciput Looks fine on testing, please roll out to live

**Comment by helendallas** [comment]
@dimasciput Is this deployed to production?

**Comment by dimasciput** [comment]
@helendallas yes, I have deployed everything to production
