### ISSUE TITLE
Discrepancies in Data

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2937]
Just an example, IN INVERTEBRATES

![image](https://user-images.githubusercontent.com/64961274/152347897-2d811957-2248-4ecf-b071-b46f3dc232d4.png)

As you see above from the Taxon management- the numbers of total taxonomy is different from the ones filtered from GBIF and RBIS.

![image](https://user-images.githubusercontent.com/64961274/152348165-ef2866ff-f400-421c-927a-7906d841ebd3.png)

**Comment by helendallas** [comment]
@mmindje The number of taxa in Taxon Management is based on your Master list. In this case there are 66 taxa.
The Number of taxa in the map, including GBIF and RBIS data, is dependent on which taxa have occurrence records. If you have a taxon in the master list, but it does not have any occurrence records, then it will not come up on the map.

That is why the taxa do not always match. I suggest you check which taxa are missing from the map, and then check if there are records in GBIF - directly via GBIF.
