### ISSUE TITLE
Training in data upload forms on how to add sites and occurrences to sites.

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2938]
@Helendallas to include training in data upload forms on how to add sites and occurrences to sites.

**Comment by helendallas** [comment]
I can do training but this can only be done once @dimasciput has added a button to allow a site and data to be added. Please confirm when this has been done on RBIS live and RBIS testing. thanks @dimasciput 

![image](https://user-images.githubusercontent.com/45286876/152748615-dc077e4d-ada0-4877-a11b-34e0ec71bb62.png)
with the site form
![image](https://user-images.githubusercontent.com/45286876/152748721-c0e140ca-8973-4e6b-9f5c-59462abc835f.png)

And ability to add different taxa

![image](https://user-images.githubusercontent.com/45286876/152748826-b5fc7411-c23f-4a02-a90a-c54cdd67fb3b.png)

**Comment by helendallas** [comment]
@dimasciput Please can you set time aside to add the 

Add Site
Add forms

To RBIS.

I need to train the team on how to add single sites and biological data records

**Comment by helendallas** [comment]
Training completed
