### ISSUE TITLE
Third party data downloads not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2941]
CSV data downloads for third party data (inwards, minisass) not working.

**Comment by dimasciput** [comment]
@jeremyshelton I think this is an issue from their side.

**Comment by helendallas** [comment]
So @dimasciput 
I get a security warning on Firefox bu then am able to download csv, Jeremy and Aneri cant download.
![Uploading image.png…]()

**Comment by jeremyshelton** [comment]
@dimasciput this is working now for inwards.
However, the minisass records are not loading, so I can't test those...

**Comment by dimasciput** [comment]
need to  check on minisass website

**Comment by dimasciput** [comment]
it is working now in live and testing

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Looks good. 
Closing.
