### ISSUE TITLE
Duplicate source references being created

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2943]
Some source references are duplicated. @dimasciput needs to investigate why the system changed the permission of the files

Examples:
https://freshwaterbiodiversity.org/source-references/?&collectors=359
![image](https://user-images.githubusercontent.com/45286876/154214640-6dd1465a-a240-41d7-aa83-761022ce3eb4.png)

https://freshwaterbiodiversity.org/source-references/?&collectors=&q=The%20thermal%20tolerances%20and%20preferences%20of%20native%20fishes%20in%20the%20Cape%20Floristic%20Region%3A%20towards%20understanding%20the%20effect%20of%20climate%20change%20on%20native%20fish%20species
![image](https://user-images.githubusercontent.com/45286876/154214613-ce6581aa-480f-493f-b709-a67225ee84d8.png)

https://freshwaterbiodiversity.org/source-references/?&collectors=&q=A%20baseline%20assessment%20for%20freshwater%20biodiversity%20conservation%20in%20the%20Riviersonderend%20catchment%2C%20South%20Africa.%20Report%201
![image](https://user-images.githubusercontent.com/45286876/154214728-449bbec9-e5e2-49ed-838b-f06d52184ed8.png)

**Comment by helendallas** [comment]
@dimasciput This is really impeding our ability to manage the source references - here is another example

![image](https://user-images.githubusercontent.com/45286876/158785085-9336afe8-552b-4b4e-ac70-a2ebcc335c63.png)


Is it not possible to create functionality for us to combined duplicates as you have done for unpublished data

**Comment by helendallas** [comment]
@dimasciput Yes thats fine, as long as you show ,e where and how to do it, thanks

**Comment by helendallas** [comment]
@Fanevanjanahary Please report today on how to fix this in admin, we are battling to work.

Here is another example:
Database: Inkomati-Usuthu Catchment Management Agency Database

Two databases have been created, one for SASS data and one for Fish, but they are called the same.

![image](https://user-images.githubusercontent.com/45286876/166429549-289c15cf-4d21-4719-ab14-2e33cbd9731f.png)

Does @dimasciput still need to check this?

**Comment by Fanevanjanahary** [comment]
Hi @helendallas 

@dimasciput already deployed this on the test, you can merge source references from the admin page. 

- First, you need to change a source reference to verified 
- Then select at least 2 sources references including one verified
- In the action, select _Merge source references_

**Comment by helendallas** [comment]
@Fanevanjanahary Where do I find Source References?

Please send me the url.

If I go into Admin, its not listed in BIMS????

**Comment by Fanevanjanahary** [comment]
@helendallas, sorry for not mentioning it.

https://freshwaterbiodiversity.org/admin/bims/sourcereference/

**Comment by helendallas** [comment]
So I went onto FBIS testing site but then for some reason I got taken to the FBIS production and I didnt realise it. I then merged these three references, and now they have disappeared completely. When I clicked explore it took me to the live site....something strange is going on.

I hope @dimasciput can get these data back

![image](https://user-images.githubusercontent.com/45286876/166681158-53d6034d-44f6-4344-9d94-4e005d481728.png)

**Comment by helendallas** [comment]
So I tested this again on testing this time and after merging, the reference disappears. Clearly not working properly.

I merged these
![image](https://user-images.githubusercontent.com/45286876/166878858-4e615b19-25a6-454d-a0b0-2ff4f7879a57.png)

Now source reference is gone on testing.

**Comment by helendallas** [comment]
@dimasciput Please prioritise fixing this as it is impacting our work. The study reference disappeared after I merged them in the backend.

**Comment by dimasciput** [comment]
@helendallas the issue with this feature has been fixed now, please test on testing.

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/173029684-7dabda2d-da27-40ca-9326-23ee037dca20.png)

Thanks @dimasciput Working now. Please deploy to live

**Comment by helendallas** [comment]
Checking on Live:
![image](https://user-images.githubusercontent.com/45286876/173306472-0706a9f2-fbe4-43bb-9b2c-5518e80d11dc.png)
 and merged

![image](https://user-images.githubusercontent.com/45286876/173306930-1a3e6f22-9abd-4245-b41b-fc574d97a636.png)
