### ISSUE TITLE
Landing page dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2945]
At the moment, Dimas needs to specify what is visualised, i.e. origin, Ecological category, conservation status etc.

Two requests related to this:

Firstly, fish and anurans should both be by Conservation Status, and Algae by Division

Secondly, Is it possible to develop functionality in Admin where we can choose what to display?  Let's chat this through. If an easy task, then action, if it is going to take a long time, then let's leave for now.

**Comment by dimasciput** [comment]
@Fanevanjanahary can you try to tackle this? You only need to focus on the second point. Maybe we can add a new field in taxon_group model to indicate what kind of chart will be displayed in the dashboard. For now the choices are conservation status, division, sass, origin and endemism.

**Comment by dimasciput** [comment]
Please also add tests

**Comment by dimasciput** [comment]
This has been deployed to testing, to update the chart you need to go to admin page : 
https://testing.healthyrivers.kartoza.com/admin/bims/taxongroup/1/change/

Go to the bottom, and you can change how the chart will get the data from. You can also change the display order of the module.

**Comment by helendallas** [comment]
Thanks @dimasciput 
I tested this by changing fish to Endemism, but colours don't come through

![image](https://user-images.githubusercontent.com/45286876/192254654-664ef6ed-d72d-4588-a7b5-dc770f88e934.png)

**Comment by helendallas** [comment]
Working beautifully thanks @dimasciput
