### ISSUE TITLE
Please can we add a new drawer in Data Sources for the Virtual Museum Data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2946]
At the moment Odonata Map is a separate Taxon module - Odonate adults

Since we will be bringing in more Virtual Museum data, we thought it would be better to allow users to select or deselect data from the VM - OdonataMAP and FrogMAP at the moment.

Please can you explore adding the drawer Virtual Museum to our Data Sources

**Comment by jeremyshelton** [comment]
![Screen Shot 2022-02-16 at 2 36 37 PM](https://user-images.githubusercontent.com/44292029/154266548-46de2087-afb7-483c-8108-a2976b0e569e.png)

**Comment by helendallas** [comment]
Please add the following text for the Virtual Museum drawer

The Virtual Museum (https://vmus.adu.org.za/) is a platform for citizen scientists to contribute to biodiversity projects. It is managed by The Biodiversity and Development Institute (http://thebdi.org/) and The FitzPatrick Institute of African Ornithology (http://www.fitzpatrick.uct.ac.za/).

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton please test on testing

**Comment by helendallas** [comment]
@dimasciput Perfect thanks. Please deploy to live
