### ISSUE TITLE
System for flagging records used in decision tools

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2947]
We are keeping track of the UUIDs of all records used in national Decision Support Tools.
We would like to add a tab in the search bar (at the bottom of search bar, under owner) that allows one to filter data based on the 'decision tool label' assigned to a record.

The first step is to build the functionality for us to be able to upload a csv with UUIDs of records that were used in a specific decision tool, and add a name to that filter (e.g. DFFE Screening Tool 2022). There will be several different DSTs added iteratively over time.  

This can also be a separate tab in the Admin panel. To manage in admin have a new dropdown called Decision Support Tools. 

@timlinux @helendallas

**Comment by dimasciput** [comment]
@jeremyshelton I still don't quite understand, please elaborate more at the sprint meeting

**Comment by jeremyshelton** [comment]
@dimasciput OK 👍

**Comment by timlinux** [comment]
![imagem](https://user-images.githubusercontent.com/178003/155105371-64880387-c64f-410e-afa6-71e23e05b5e2.png)

**Comment by dimasciput** [comment]
@jeremyshelton deployed in testing, you can upload the data here https://testing.healthyrivers.kartoza.com/admin/bims/decisionsupporttool/. There's also a button to download the template.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - busy testing this today.

**Comment by jeremyshelton** [comment]
@dimasciput any further progress on this one?

**Comment by dimasciput** [comment]
@jeremyshelton yes I think we have some limitation on how many data can be handled at once because the process is not done in the background like the occurrence uploader. Is it okay to limit like 500 data at once for now?

**Comment by jeremyshelton** [comment]
@dimasciput as discussed, we need to be able to add thousands of records at a time - for example the DFFE Screening Tool comprises 6000+ records that we need to flag. Ideally we would like to do this by uploading a single csv.

**Comment by dimasciput** [comment]
@jeremyshelton can you test it on testing? Thanks

**Comment by jeremyshelton** [comment]
@dimasciput this appears to be working now. 
We had about 80 upload errors that said that this records (uuids) do not exist.
Busy investigating & will revert.

**Comment by jeremyshelton** [comment]
@dimasciput We are not able to check the errors because fish data download requests are not working on FBIS production site. Please let me know when fish data downloads are working again so that we can test.
Thank you.

**Comment by dimasciput** [comment]
@jeremyshelton please try it again, the data is pretty big that's why it might take a long time. You also can try download from testing since it's a mirror of live site.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
My downloads from live sit still not coming through, but that is a separate issue. 
The Decision support tool is working well.
Thank you.
Closing ticket.
