### ISSUE TITLE
Record type - a new column in upload templates and forms

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2948]
New column in all data upload templates and forms called 'Record type' (under sampling effort), with the 5 categories as drop downs.

**Record type**
- Visual observation
- Photographic record
- Specimen collection
- Acoustic record
- DNA sample

This is a binary category, and one or more of the record types can be checked for each occurrence data record.

@helendallas @timlinux

**Comment by dimasciput** [comment]
@jeremyshelton we couldn't add a dropdown to csv only excel file

**Comment by dimasciput** [comment]
@jeremyshelton but I will add the dropdown to the occurrence form

**Comment by jeremyshelton** [comment]
@dimasciput yes - dropdown in the occurrence form, and excel data upload template.
It should also feature as a new column in .csv data downloads.

**Comment by dimasciput** [comment]
@Fanevanjanahary any updates on this?

**Comment by Fanevanjanahary** [comment]
hey @dimasciput, the sample data I've used to test it didn't work. Where can I find sample data for it please?

**Comment by helendallas** [comment]
@jeremyshelton Can you get back to @Fanevanjanahary thanks

**Comment by jeremyshelton** [comment]
@Fanevanjanahary are you testing by uploading data via the form, or by uploading a spreadsheet?

**Comment by Fanevanjanahary** [comment]
@jeremyshelton via the form

**Comment by jeremyshelton** [comment]
@Fanevanjanahary I don't see any option to specify record type in the fish form on the testing site. 
This option should be available under Sampling effort on all taxon upload forms:
<img width="961" alt="Screen Shot 2022-03-29 at 11 36 58 AM" src="https://user-images.githubusercontent.com/44292029/160582237-634ffbe6-f3d1-4229-8044-22881048779b.png">
Does that make sense?

**Comment by dimasciput** [comment]
@Fanevanjanahary can you also make sure record type is included in the csv download?

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
@Fanevanjanahary - let me know if you need more input here, or when you want me to test.
Thanks

**Comment by jeremyshelton** [comment]
@Fanevanjanahary has there been any further progress here?
Anything ready for me to test yet? Or anything you are still stock with that I can help with?
Thanks

**Comment by Fanevanjanahary** [comment]
Hi, @jeremyshelton I think @dimasciput already deployed this on the test.

**Comment by jeremyshelton** [comment]
Thanks @Fanevanjanahary 
Looks good on testing. Happy for you to deploy to production 👍

**Comment by jeremyshelton** [comment]
Thanks @Fanevanjanahary & @dimasciput 
This looks good on the live site 👍
For the bulk data upload templates - can we just add a column to the end called record type?

**Comment by helendallas** [comment]
@dimasciput Please respond re adding a column to the bulk data upload templates. We cna action if yes, as long as the coding is set up to ingest the data correctly.

@jeremyshelton Once we here the response from Dimas, It may be worth testing an bulk data upload with this column included to check that the data is added correctly.

**Comment by helendallas** [comment]
Awaiting response from @dimasciput 

There is a question re has the uploading of the occurrence file been revised so we can include record type as a column. If yes, I can close ticket, if no, I will create a new ticket and close this one

**Comment by jeremyshelton** [comment]
@dimasciput we are still awaiting a response on this ticket? Thanks
