### ISSUE TITLE
Please add a Edit button to Water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2949]
At the moment I cannot go back to the Water temperature upload form and edit the source reference or photo etc.

**Please can you add this in, so that the data can be edited.** 
This would then open up the original Water temperature form: which could then be saved and updated

![image](https://user-images.githubusercontent.com/45286876/154469578-2fbbd83d-b273-48e1-a3c7-e411efc80762.png)

![image](https://user-images.githubusercontent.com/45286876/154469757-a57df018-2b1e-4490-a3eb-c50bb07e9521.png)

**Comment by dimasciput** [comment]
@helendallas and what about the existing water temperature data? Can user edit them?

**Comment by helendallas** [comment]
@dimasciput 

I own all the existing data in FBIS, and yes I will need to be able to edit the associated data, not the water temperature data. So I will need to be able to go to the water temperature form, add source reference, add photo. 

Also I guess if I noticed the data looks strange then I could re-upload the csv and I assume it would be overwritten if the Date Time was the same.

Same rules need to apply as for biodiversity data. Only the owner or the FBIS superuser can edit the data.

**Comment by dimasciput** [comment]
@helendallas deployed in testing

**Comment by helendallas** [comment]
@dimasciput 
Not sure if this is working properly, I edited
https://testing.healthyrivers.kartoza.com/water-temperature-form/edit/?siteId=9980&year=2009

but its stuck on processing

![image](https://user-images.githubusercontent.com/45286876/156128909-a3457c47-b812-4eed-a907-4a6e89355152.png)

**Comment by dimasciput** [comment]
@helendallas what did you update?

**Comment by helendallas** [comment]
I thought I had to update everything ....uploaded csv , added photo and study ref

**Comment by helendallas** [comment]
It would be better to have form show what was already there.....then I could just add the missing bit e.g. change the study ref

**Comment by helendallas** [comment]
Checking each section individually

- Successfully added a photo to an existing site 
- Successfully changed source reference
- Re-uploading CSV file - this seems to be a problem, gets stuck on processing

https://testing.healthyrivers.kartoza.com/water-temperature-form/edit/?siteId=9980&year=2009

![image](https://user-images.githubusercontent.com/45286876/156141696-6ebfd3d9-6fb7-44bc-bdd4-c150b022aeb2.png)

**Comment by dimasciput** [comment]
@helendallas please email me the csv file.

**Comment by dimasciput** [comment]
@helendallas please try it again.
