### ISSUE TITLE
Can we add water temperature time series data that has gaps in it?

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2953]
Some data have gaps in it, for example the attached file:

It would be good to be able to upload these data

Should they be left blank?

![image](https://user-images.githubusercontent.com/45286876/154683386-8255078b-497e-4f0a-a285-2849aff6c77a.png)
[WT_E1OLIF-ABDAM_18_11_2008 to 09_02_2011.xlsx](https://github.com/kartoza/django-bims/files/8097137/WT_E1OLIF-ABDAM_18_11_2008.to.09_02_2011.xlsx)

**Comment by dimasciput** [comment]
@helendallas can you test the chart in testing?

**Comment by helendallas** [comment]
@dimasciput Same issue with gateway timeout, will test again once resolved.

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary 
So when I add the data where the date time is compete but there is missing data, then I get an error message:
![image](https://user-images.githubusercontent.com/45286876/162141564-f8799258-821c-44ad-8ec1-943d8ae43b52.png)

Here is the xls file

[G1BERG-BRBM1 26-Oct-07 TO 21-May-09.xlsx](https://github.com/kartoza/django-bims/files/8440477/G1BERG-BRBM1.26-Oct-07.TO.21-May-09.xlsx)

PLease check why not uploading data with gaps in it.

**Comment by dimasciput** [comment]
@helendallas ah I think we have some misunderstanding, we thought gap means that you don't provide the data for certain dates but instead the date is in still in csv with just empty string. 
Ok let me update it.

**Comment by helendallas** [comment]
Yes, that's correct, thanks

**Comment by helendallas** [comment]
Is it easier to remove the missing date and dates rather than leaving it blank. I can do this easily but then not sure about satrt and end time. Should always be the same ? 00:00-23:00 etc

**Comment by helendallas** [comment]
As in this file:
[G1BERG-00310 26-Oct-07 TO 21-May-09 Missing dates excluded.xlsx](https://github.com/kartoza/django-bims/files/8520639/G1BERG-00310.26-Oct-07.TO.21-May-09.Missing.dates.excluded.xlsx)

Please revert and then deploy to live please

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Please feedback on this ticket following my comments above. Thanks

**Comment by helendallas** [comment]
Okay I retested this on live and it is working fine. Data with missing records added., Closing ticket
