### ISSUE TITLE
Thermal dashboard - allow users to select start and end period for visualising the data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2956]
At the moment, we are only able to visualise data per calendar year, 2009 or 2010 etc, using the dropdown.

Please can you add the option to allow the user to specify the start date and end date for plotting the graph and generating tables, so for example the hydrological year 1 October to 30 September.

**Comment by dimasciput** [comment]
@helendallas deployed in testing

**Comment by helendallas** [comment]
SO the reason for this was to allow users to visualise data for a 1 year period that doesnt follow a calendar year.  

So for example the hydrological year 1 October 2008 to 30 September 2009. 

At the moment it allows us to choose a smaller date range within a year, which is also useful.

![image](https://user-images.githubusercontent.com/45286876/156129581-e7c7f529-b94b-4450-8209-72fb4063767f.png)

Let me know what you think? If its going to be a challenge then lest leave it for now

**Comment by dimasciput** [comment]
@helendallas Unfortunately the current dashboard wasn't built with that in mind, so we're going to be changing many things. I think it's better to leave it for now, we can improve it later.
