### ISSUE TITLE
We need to see sites that only have water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2971]
At the moment, only sites that have occurrence data are visible on the map. 

However, with the addition of the thermal module, this needs to be revised so that sites that have **water temperature data only**, will become visible on the map, when the filter is clicked.

These dont have to be visible always, but need to show when the filter is clicked

Abiotic data - Water Temperature (time series) is clicked

![image](https://user-images.githubusercontent.com/45286876/156532286-60515aac-7938-40b0-8311-e49923dafb50.png)

**Comment by dimasciput** [comment]
@helendallas please test this on testing

**Comment by helendallas** [comment]
Cant test as get error message
![image](https://user-images.githubusercontent.com/45286876/161739420-1e90243d-8ce8-4e20-b0de-f83a0c4e5d86.png)

**Comment by dimasciput** [comment]
@helendallas it seems we keep getting this error when the file is too big, can I spend some time to improve the uploader? I probably need like 3-4 hours.

**Comment by helendallas** [comment]
Yes please do @dimasciput thanks. Sometimes it works, but not always and then its hard to backtrack. Please let me know when it is resolved, thanks

**Comment by dimasciput** [comment]
@helendallas please try uploading it again in testing

**Comment by helendallas** [comment]
Is now uploading 18,000 plus records. Its shows uploaded, but then green block with text at thetop disappears, so if you are running it in the background it then one can miss it. Please can you add it back, thanks

![image](https://user-images.githubusercontent.com/45286876/161961223-7db764d4-4704-4482-b449-5feb84e17c6d.png)

**Comment by helendallas** [comment]
Thanks @dimasciput Looking great now and working well. Is this rolled out to live yet?

**Comment by helendallas** [comment]
Working although there is a delay. Closing ticket
