### ISSUE TITLE
Please check - Water temperature data csv download and graphs not matching time series

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2972]
Please can you check the data uploaded that is only a few months of the year. 

https://freshwaterbiodiversity.org/water-temperature/9980/2011/?taxon=&search=H2ROOI-WORCE&siteId=9980&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9980&orderBy=name&polygon=&thermalModule=&dst=&startDate=2011-01-01&endDate=2011-12-31

The chart is showing a full year, and then when you download the chart as a csv file, the data is there from 1/1/2011  12:00:00 AM to 6/7/2011  12:00:00 AM, but the data uploaded was only 1/1/2011  12:00:00 AM to 2/2/2011  11:00:00 PM

![image](https://user-images.githubusercontent.com/45286876/157248251-cc151b5a-cd0f-4c4a-aa9d-77f284993afc.png)

**Comment by helendallas** [comment]
Here is the xls file I uploaded, 

[H2ROOI-WORCE 01_12_2008 to 03_02_2011.xlsx](https://github.com/kartoza/django-bims/files/8282469/H2ROOI-WORCE.01_12_2008.to.03_02_2011.xlsx)


you can see the 2008 starts on the 12/2/2008  12:00:00 AM, but the graph and csv starts from the 2008-11-11 00:00:00. Not sure why this is.

[H2ROOI-WORCE 2008 csv file.xlsx](https://github.com/kartoza/django-bims/files/8282471/H2ROOI-WORCE.2008.csv.file.xlsx)


Also at the other end, in 2011, the last date is 2/2/2011  11:00:00 PM, but the graphs and CSV go until the 2011-06-07 00:00:00

[H2ROOI-WORCE 2011 csv file.xlsx](https://github.com/kartoza/django-bims/files/8282472/H2ROOI-WORCE.2011.csv.file.xlsx)

**Comment by dimasciput** [comment]
@helendallas @Fanevanjanahary looks fine from the admin page, so probably bug in the chart https://freshwaterbiodiversity.org/admin/bims/watertemperature/?o=2&q=H2ROOI-WORCE

**Comment by dimasciput** [comment]
this should already fixed in testing, please can you test it @helendallas

**Comment by helendallas** [comment]
Thanks @dimasciput @Fanevanjanahary Looks fine now. PLease deploy to live

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput 

There still seems to be an issue with data which is not a full year. Issue is not consistent and sometimes it works fine. Please can you check and revert.

See below:

https://freshwaterbiodiversity.org/water-temperature/9980/2008/?taxon=&search=&siteId=9980&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9980&orderBy=name&polygon=&thermalModule=True&dst=&startDate=2008-01-01&endDate=2008-12-31

Graph shows full year.
![image](https://user-images.githubusercontent.com/45286876/165033265-af46aa7e-90ee-46b4-8ca7-e15233019128.png)

But there is only data for dec

![image](https://user-images.githubusercontent.com/45286876/165033356-aaf6c59e-a7e4-4875-8357-d0401fb99d15.png)

**Comment by helendallas** [comment]
Here is another example: 
https://freshwaterbiodiversity.org/water-temperature/84552/2008/?taxon=&search=&siteId=84552&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%2C%22gbif%22%2C%22virtual_museum%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=84552&orderBy=name&polygon=&thermalModule=True&dst=&startDate=2008-01-01&endDate=2008-12-31

**Comment by dimasciput** [comment]
Hi @helendallas I fixed this just now, but haven't deployed to live yet. Will deploy to test site later today.

**Comment by dimasciput** [comment]
@helendallas this is fixed in testing

**Comment by helendallas** [comment]
Excellent thanks @dimasciput All looking  fine now. Please deploy update to live and I can close the ticket

**Comment by dimasciput** [comment]
@helendallas this has been deployed to live

**Comment by helendallas** [comment]
Thanks @dimasciput Looking great. Closing ticket
