### ISSUE TITLE
Add Site option to RBIS, and add different biodiversity

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2978]
@dimasciput Please add a button to allow a site and data to be added. 

![image](https://user-images.githubusercontent.com/45286876/158599659-b90b2c2f-1e29-4fd3-a852-be1c30d07d85.png)

And ability to add different taxa

![image](https://user-images.githubusercontent.com/45286876/158599753-b8ce42d8-b80e-4cb8-b23e-54fba8b322d2.png)

**Comment by helendallas** [comment]
@dimasciput Please can you set time aside to add the 

Add Site
Add forms

To RBIS.

I need to train the team on how to add single sites and biological data records

**Comment by helendallas** [comment]
For now we have forms ready from FBIS for the following taxonomic groups :

- Fish
- Amphibians - called Anura in FBIS
- Invertebrates

We will need to create new ones for  

- Birds
- Plants

 I suggest you add these already and then I will work with the RBIS team to modify the forms.

The Odonates are pulled in the OdonataMAP so we dont offer functionality to add records to this taxon group.

**Comment by helendallas** [comment]
@dimasciput The Add site needs to show Rwanda, not South Africa.

![image](https://user-images.githubusercontent.com/45286876/173343053-44a8d2eb-c966-4e44-bd6e-56e04a2880cc.png)

![image](https://user-images.githubusercontent.com/45286876/173343149-780e801b-1523-45f3-a2d3-f9c241ac93e4.png)

**Comment by helendallas** [comment]
I then added coordinates in Rwanda but got an error message on submit

![image](https://user-images.githubusercontent.com/45286876/173343424-112543d4-cba4-406c-926b-68c172e4dcd4.png)

Lastly, not all modules visible to add data

![image](https://user-images.githubusercontent.com/45286876/173343526-e2a3cb87-d28f-4f20-82a6-491f59bfb821.png)

**Comment by dimasciput** [comment]
deployed to live
