### ISSUE TITLE
Photograph in water temperature dashboard getting mixed up

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2979]
I added a photo to E1ROND-KEURB 2008 and saved the form.

![image](https://user-images.githubusercontent.com/45286876/158758133-066ada60-7bf1-4511-9173-25472b94ee0e.png)

Then I selected a new site and wanted to add the photo for that site, BUT the photo from the previous site was there.

![image](https://user-images.githubusercontent.com/45286876/158759077-a049d48a-321b-4353-b075-34807a5a9a6b.png)

Then I deleted the incorrect photo and added the correct one for this site: G1BERG-KERSE

![image](https://user-images.githubusercontent.com/45286876/158759602-541e2eba-7d34-4297-aba4-b18c75a9d7cc.png)

But then when I go back to E1ROND-KEURB, the photo I added to G1BERG-KERSE is now there

![image](https://user-images.githubusercontent.com/45286876/158760171-85092f31-0e59-4460-b8a0-f45cd67a284d.png)

**Something is going wrong, please can you check it urgently as it is impacting my ability to add photographs.

The photographs need to be assigned to a SITE and Date (Year in the case of water temperature data)**

**Comment by helendallas** [comment]
Any update on this ticket?

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Please fix this soonest

here all photos are showing up on the edit dashboard

https://freshwaterbiodiversity.org/water-temperature-form/edit/?siteId=10358&year=2008

**Comment by helendallas** [comment]
Further to above, the correct photo comes up when viewing the data but when I open Edit 2008 or Edit 2009 etc, then I see all the photos from multiple sites.  This may become confusing. Can you make it that you only see the photos uploaded for the site/sampling date. Thanks

**Comment by helendallas** [comment]
Is it also possible to show photographs for a site regardless of the year it was associated with.

So for e.g. If I only have a photo for 2008, and I go to 2009, I get the placeholder picture.
Can we instead get the photo from 2008 and whatever other photos are available for the site, with the date shown as it already does.

**Comment by helendallas** [comment]
The same as it does in the SASS dashboard: where you can scroll through photos and dates are shown

https://freshwaterbiodiversity.org/sass/dashboard/9909/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/165068708-37ff8e76-9f0f-4d23-943f-68d4ffc2c6b0.png)
![image](https://user-images.githubusercontent.com/45286876/165068755-4d13df81-9d92-41a7-8e10-3955a2018f4a.png)

**Comment by dimasciput** [comment]
> Is it also possible to show photographs for a site regardless of the year it was associated with.

So for e.g. If I only have a photo for 2008, and I go to 2009, I get the placeholder picture.
Can we instead get the photo from 2008 and whatever other photos are available for the site, with the date shown as it already does.

@helendallas do you want to show all images even if they are not uploaded from water uploader form?

**Comment by helendallas** [comment]
Yes please, that will be most useful, as long as the year and or date is shown with the photo. Is this possible?

**Comment by dimasciput** [comment]
@helendallas yes it's possible, I will deploy it before finishing my day.

**Comment by helendallas** [comment]
Brilliant thanks Dimas !!!

**Comment by dimasciput** [comment]
@helendallas I have deployed the fix to testing, please check it

**Comment by helendallas** [comment]
Some seem to be blank
![image](https://user-images.githubusercontent.com/45286876/165077559-8386ed66-4114-46b9-ae25-c43f7a2bf544.png)

https://testing.healthyrivers.kartoza.com/water-temperature/10358/?taxon=&search=&siteId=10358&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=10358&orderBy=name&polygon=&thermalModule=True&dst=

I added a photo in 2008 and a different one in 2009

**Comment by helendallas** [comment]
Working well on other sites I checked.

**Comment by dimasciput** [comment]
> Some seem to be blank

Yes because the media files have not been brought from live site to testing. I have deployed to live site this morning, can you check it there too? Thanks.

**Comment by helendallas** [comment]
Thanks @dimasciput Look great, working well. Closing ticket
