### ISSUE TITLE
Metadata table not loading (again)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2982]
@dimasciput this is an issue that has happened several times - the metadata table not loading in detailed dashboard, even after hard refresh. 

<img width="1356" alt="Screen Shot 2022-03-22 at 9 48 00 AM" src="https://user-images.githubusercontent.com/44292029/159433677-c09d1898-c6cb-4e1f-bdec-5bc5ded43282.png">

I wonder if there is a way to fix this issue more sustainably?

Thanks

@helendallas @timlinux

**Comment by dimasciput** [comment]
this is a bug from harvesting the data from gbif, I'll fix it in the next sprint

**Comment by jeremyshelton** [comment]
OK cool.
Thanks @dimasciput

**Comment by dimasciput** [comment]
@jeremyshelton this is fixed on live site, since it's a data issue

**Comment by jeremyshelton** [comment]
@dimasciput thanks.
Looks good.
Closing.
