### ISSUE TITLE
We need to be able to track what data users have uploaded to FBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2986]
At the moment we get an email when a user adds SASS or other data. However it is not very easy to summarise the number of data added to FBIS by users.

Please can @timlinux @dimasciput explore options for making it easier to report on the data uploaded to FBIS by the users.

**Comment by timlinux** [comment]
TODO:

- [ ] Dimas to add a link to metabase from FBIS admin menu
- [ ] Tim and Dimas to come up witha standard dashboard that has stats for uploads and downloads

**Comment by timlinux** [comment]
I came up with something like this in Metabase. It can show all the users in aggregate like this:


![image](https://user-images.githubusercontent.com/178003/165723966-92770853-f687-4681-b870-effb03c99515.png)


Or you can filter it based on the user's last name:

![image](https://user-images.githubusercontent.com/178003/165723001-a2722e45-15b2-4d75-ac23-478bf520079f.png)

If this is in line with what you are after, @dimasciput will make a view so that we can filter on full names rather in case there is ambiguity in the surname. You can play with the dashboard here:

https://testing.healthyrivers.kartoza.com:3000/dashboard/3-bims-dashboard

Here is how you apply the filters:
![filters](https://user-images.githubusercontent.com/178003/165726483-f0f8b250-f1ce-4198-a16e-25391b997403.gif)

**Comment by helendallas** [comment]
Perhaps what you wrote in #2598 is what you mean with the tables?

**Comment by helendallas** [comment]
We could keep it simple for now and rely on the **Biological collection records** table in Admin for extracting stats on the number of biological occurrence records added.

If the filters were improved here

![image](https://user-images.githubusercontent.com/45286876/167587132-97f12d37-ad35-4076-aa5f-0082aa3d082b.png)

By adding in these filters: then we could manually extract information at the end of each 6 month period for reporting.

We need to be able to filter by:

- Biodiversity Module
- Data Source
- Temporal (By Collection date)
- Spatial (South African Province, Water Management Area and possibly others)
- Reference Category
- Owner

When a filter was applied we would need to see somewhere the total number of records

The going forward, it would be good to be able to report on Chemical records and Water temperature, using the same set of filters.

@jeremyshelton Thoughts?

**Comment by jeremyshelton** [comment]
@helendallas that makes sense to me. 
It should be quite simple to make our own plots from those filtered data 👍

**Comment by timlinux** [comment]
> We could keep it simple for now and rely on the **Biological collection records** table in Admin for extracting stats on the number of biological occurrence records added.
> 
> If the filters were improved here
> 
> ![image](https://user-images.githubusercontent.com/45286876/167587132-97f12d37-ad35-4076-aa5f-0082aa3d082b.png)
> 
> By adding in these filters: then we could manually extract information at the end of each 6 month period for reporting.
> 
> We need to be able to filter by:
> 
> * Biodiversity Module
> * Data Source
> * Temporal (By Collection date)
> * Spatial (South African Province, Water Management Area and possibly others)
> * Reference Category
> * Owner
> 
> When a filter was applied we would need to see somewhere the total number of records
> 
> The going forward, it would be good to be able to report on Chemical records and Water temperature, using the same set of filters.
> 
> @jeremyshelton Thoughts?

That approach is ok for me, though I think it would be good to chat about it - ultimately I would like to also work to systematise things so that out the box we can provide metrics.

**Comment by helendallas** [comment]
@jeremyshelton We need to schedule time to work through the types of reporting we need.

**Comment by helendallas** [comment]
@timlinux @dimasciput I have lost track of this ticket. Its about tracking what data users have uploaded. What is needed from myself and jeremy?

**Comment by jeremyshelton** [comment]
I suggest we talk through this at the sprint planning call?

**Comment by helendallas** [comment]
Closing this as adequate what we have
