### ISSUE TITLE
Please delete all Dallas 1995 invertebrate data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2987]
We previously tried to resolve this issue but it is still problematic. It arose from bringing in **Dallas 1995** from the Biobase, when the same data (SASS) was already in the River Database.

The easiest solution is for @dimasciput to delete all occurrence records and associated data with the source reference : 1623 records.
I have checked them all and they are all in the FBIS as SASS data.
 
![image](https://user-images.githubusercontent.com/45286876/160104680-9031cee3-dc83-4ecb-8443-adb8162cc40a.png)

The url:
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221110%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

And the xls file with UUIDs

[Dallas 1995 data from FBIS not as SASS data_for deletion.xlsx](https://github.com/kartoza/django-bims/files/8349620/Dallas.1995.data.from.FBIS.not.as.SASS.data_for.deletion.xlsx)

**Comment by dimasciput** [comment]
the occurrence records have been deleted.

**Comment by helendallas** [comment]
Thanks @dimasciput
