### ISSUE TITLE
Issue with SASS ecological category graphs

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2988]
Please can you check why some graphs are now using a combined geom zone. The combined should only be used for those specified and where upper and lower are not available:  Here is the original table I shared with you. These were definately working, but now some are not working.  Plase can you check @dimasciput 

[Table 2_1_Summary Statistics.pdf](https://github.com/kartoza/django-bims/files/8349874/Table.2_1_Summary.Statistics.pdf)

![image](https://user-images.githubusercontent.com/45286876/160110067-04d87fc9-060c-4ae7-8fac-667ab7cac913.png)

**Comment by helendallas** [comment]
Okay so I went into the site and fetch geom zone....and then it started working.

There is clearly a bug in the geocontext geom zone and it is now impacting ecol category interpretation. Please cna you investigate. thanks

**Comment by helendallas** [comment]
here is another example:

https://freshwaterbiodiversity.org/sass/dashboard/9890/?taxon=&search=&siteId=9890&collector=%5B%22Helen%20Dallas%22%5D&category=&yearFrom=1991&yearTo=1994&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Western%20Cape%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9890&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
So when I fetch geom zone, and open site again the ecol category chart is fixed.

**Comment by dimasciput** [comment]
@helendallas I have checked the data in the admin page, it seems it's not getting the geomorphological data from geocontext. That's why it uses **combine** in the chart. 

@amyburness please could you check wether this site has geomorphological data? https://freshwaterbiodiversity.org/admin/bims/locationsite/9890/change/

Geocontext url : https://staging.geocontext.kartoza.com/api/v2/query?registry=group&key=geomorphological_group&x=19.0788674354553&y=-33.9676487093584&outformat=json

**Comment by helendallas** [comment]
@dimasciput Is this fixed on live or testing?

**Comment by helendallas** [comment]
So it seems that even if a site is slightly off the gem zone line, it does now get context data??  We need a work around for this. 

![image](https://user-images.githubusercontent.com/45286876/164618983-35d254c2-386f-413c-94ae-b5a000078d3b.png)


https://freshwaterbiodiversity.org/sass/dashboard/9875/?taxon=&search=&siteId=9875&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9875&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
and the ecoregion is there
![image](https://user-images.githubusercontent.com/45286876/164619287-0a50a457-9d17-4007-a62d-e89b07daf929.png)

https://freshwaterbiodiversity.org/admin/bims/locationsite/9875/change/?_changelist_filters=q%3DG1BERG-FORES

**Comment by timlinux** [comment]
If the user has set a refined geomorphological zone, that should be used in preference over the geocontext one.

**Comment by helendallas** [comment]
@dimasciput These are the geom classes that each geom zone needs to be assigned:

Upper: Mountain headwater stream, Mountain stream, Transitional, Upper foothill
Lower: Lower foothill, Lowland river

![image](https://user-images.githubusercontent.com/45286876/164646432-125bfa28-9831-4869-85d5-91753e37713d.png)

**Comment by helendallas** [comment]
Thanks @dimasciput Grey zones seem to be sorted but not sure if you completed all three issues:

-     If the user has set a refined geomorphological zone, that should be used in preference over the geocontext one.
-     If the site GM zome in set in the model check why it is not reflected in the chart sometimes
-     In some cases it seems that the GM zone lookup from geocontext fails - we need to find some test cases and see why they are failing

 I created a new ticket for this as well #3033

**Comment by dimasciput** [comment]
Yes @helendallas , it should checked all those 3 points.

**Comment by helendallas** [comment]
Ok thanks, I will have another check on testing

**Comment by helendallas** [comment]
Few issues:

Ecological category graph should show have Upper or Lower, at the moment it is Undefined

![image](https://user-images.githubusercontent.com/45286876/165058799-6cc9f243-8a71-4db4-ad70-4369e1b8ff48.png)


Otherwise seems to be working fine thanks @dimasciput

**Comment by dimasciput** [comment]
@helendallas fixed on testing https://testing.healthyrivers.kartoza.com/sass/dashboard/9890/?taxon=&search=&siteId=9890&collector=%5B%22Helen%20Dallas%22%5D&category=&yearFrom=1991&yearTo=1994&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,sa_provinces,Western%20Cape%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22,%22gbif%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=9890&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good except please change

Combine to Combined

![image](https://user-images.githubusercontent.com/45286876/165690726-01eb9440-58bb-421c-9e6b-e212d223b0b4.png)

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary Fixed, closing ticket
