### ISSUE TITLE
Fix Author filter in Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2989]
I created a few Source references, e.g.

![image](https://user-images.githubusercontent.com/45286876/160123715-93ce6c6b-6b74-4179-94d7-d3d61400a345.png)

Now if I search on author =  Helen Dallas, these are returned, even though I ma not the owner

**Comment by dimasciput** [comment]
@helendallas fixed on testing

**Comment by helendallas** [comment]
Look good, please deploy to live
