### ISSUE TITLE
Documenting workflows for metabase analytics

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2992]
# Example workflows with metabase

## Create a base question

Give me a list of every site visit and the taxa collected on those visits, along with the IUCN status:

![image](https://user-images.githubusercontent.com/178003/160371989-bec4d7c3-6c05-46a1-b758-a98e8418b7b3.png)

![image](https://user-images.githubusercontent.com/178003/160372216-3f388c09-5f02-4fa1-bde7-1568fc3568ae.png)

![image](https://user-images.githubusercontent.com/178003/160372268-2eb3f328-60b7-4fca-98ef-230ce2f710bc.png)

![image](https://user-images.githubusercontent.com/178003/160372331-fd95ef1f-65a5-48f1-af5f-afc369118713.png)

![image](https://user-images.githubusercontent.com/178003/160372395-d9a4dd1c-914a-47b6-9ba5-f06968796634.png)

![image](https://user-images.githubusercontent.com/178003/160372611-10bdbd91-52a1-4b49-8a4e-dda6d7e12050.png)

![image](https://user-images.githubusercontent.com/178003/160372736-47912a55-4c90-412e-94dc-9f2830b86db4.png)

![image](https://user-images.githubusercontent.com/178003/160372774-cb8589ed-46ed-42c8-96f5-d278210b91ac.png)

## Add a new component to your dashboard

Start by making a new question

![image](https://user-images.githubusercontent.com/178003/160380500-2c867858-69c0-4598-8d16-5ac7339b31b5.png)

Base it on an existing question

![image](https://user-images.githubusercontent.com/178003/160381764-ee8d7071-07fe-4371-85f4-3584808df335.png)

Choose some interesting columns from your base query:

![image](https://user-images.githubusercontent.com/178003/160459252-b4a6e4d9-e4ec-4f28-b18a-813a8c90bf46.png)

Pick a table to join to your base query:

![image](https://user-images.githubusercontent.com/178003/160458086-f55c5d0b-bff8-4b11-bc2e-f1d247c248d7.png)

![image](https://user-images.githubusercontent.com/178003/160460601-04afb658-967b-42f6-836b-9b89097f8a46.png)

**Comment by helendallas** [comment]
DOnt think we ever took this any further., Suggest closing ticket
