### ISSUE TITLE
The X close button doesnt work on the water temperature form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3008]
When I click X, the form does not close and I cannot get back to the map

![image](https://user-images.githubusercontent.com/45286876/161762093-de523273-4840-431f-be66-19bfe8555176.png)

Instead it takes me to the site form

![image](https://user-images.githubusercontent.com/45286876/161762291-841cd5b4-2ad9-4810-9eac-a1c7f6649dc8.png)

And then back to the water temp form when I try to close that

![image](https://user-images.githubusercontent.com/45286876/161762372-02fa91cf-3c19-4069-8bf7-4e9f08984a7e.png)

https://freshwaterbiodiversity.org/water-temperature-form/?siteId=32392

**Comment by dimasciput** [comment]
Deployed to testing

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput This is working well, please deploy to live

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary This is a problem again, I cant close the water temperature form using the X and get back to the map. Reoponing ticket

**Comment by dimasciput** [comment]
@helendallas Please test this again on the live site.

**Comment by helendallas** [comment]
Checked, its working when one view water temp data, but not after one has added water temp data

**Comment by helendallas** [comment]
BUT

After uploading water temperature data for a site, I get the 
![image](https://user-images.githubusercontent.com/45286876/228772848-2d68161c-3528-456a-abd1-e005167b4111.png)

But then the X button to close the site does not work.

https://freshwaterbiodiversity.org/water-temperature-form/?siteId=115572

**Comment by dimasciput** [comment]
fixed on both production and testing
