### ISSUE TITLE
Please show the notes field in Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3016]
At the moment when we update a Peer-reviewed scientific article, the Notes, field is not visible, although it is there when one first uploads the Peer-reviewed scientific article

Editing Peer-reviewed scientific article
![image](https://user-images.githubusercontent.com/45286876/161995180-cdf975b2-d048-4b6c-baad-f39782b8110d.png)

Adding Peer-reviewed scientific article
![image](https://user-images.githubusercontent.com/45286876/161995433-e7d3f309-8546-4e4a-8e88-c6c446e59a79.png)

**Comment by dimasciput** [comment]
Please test on testing @helendallas

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput This looks fine, please deploy to live
