### ISSUE TITLE
Water quality import module

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#3017]
These will become sites. The extra info can be in the description.

![imagem](https://user-images.githubusercontent.com/178003/162153513-eb2fd551-29ae-46ee-8e5f-c26a4ed6ec9f.png)

Sampling dates need to be consistently entered:

![imagem](https://user-images.githubusercontent.com/178003/162153678-a6604133-579d-4a1e-8b8d-34a2099c56a5.png)

Can the individual readings be left out - I dont think they add any value over bringing in just the mean?

![imagem](https://user-images.githubusercontent.com/178003/162153765-48078d8e-9ebc-4158-9ffe-a28e4eb374d4.png)

All numbers should be represented in scientific notation

![imagem](https://user-images.githubusercontent.com/178003/162154007-9463fee5-bbd7-49f0-8109-b62acc06a433.png)

Numbers should be exact and not indicative:

![imagem](https://user-images.githubusercontent.com/178003/162154191-c0270e81-f360-4510-9d0e-62e4132e3291.png)

Column and row arrangement should be consistent with locations as row and measurement factors as columns

![imagem](https://user-images.githubusercontent.com/178003/162154373-aff1174a-c0d4-460f-a0a8-8f709176165c.png)

Place names need to be resolvable as coordinates (linked to a site) and we need precise dates. In the case we know only the year we could use an indicative date e.g. 1 Jan 2017

![imagem](https://user-images.githubusercontent.com/178003/162154644-40e7c889-4667-4f89-876e-17aed33f5d24.png)

The sheet should contain one long continuous list of readings without being broken into different sections

![imagem](https://user-images.githubusercontent.com/178003/162154823-11b12ed0-29da-45f7-8dad-b1cb1eadf543.png)

Cells for numeric data should not contain words:

![imagem](https://user-images.githubusercontent.com/178003/162155001-dcbfd10f-ce4f-47af-b04c-c1625e8af8e8.png)

Coordinates should be presented as decimal degrees and should use negative (-) to indicate west or north, having no letters in the cell

![imagem](https://user-images.githubusercontent.com/178003/162155260-26b3f157-9013-4795-86dc-b5f7c64b4d39.png)

For not detected, can we just leave it blank:

![imagem](https://user-images.githubusercontent.com/178003/162155528-9102b709-3590-48db-b50f-8e881ea9657d.png)

Every row should have a proper label e.g. district

![imagem](https://user-images.githubusercontent.com/178003/162155717-8b6cabfc-cc7f-4670-9113-af235d6c626c.png)

Dates should be valid

![imagem](https://user-images.githubusercontent.com/178003/162155855-b82c4e3c-13f4-47e8-b1a7-fc78c7e72e1b.png)

Location coordinates are mandatory

![imagem](https://user-images.githubusercontent.com/178003/162156015-e060b685-4466-4054-a20d-1e81c3b618bb.png)

**Comment by timlinux** [comment]
The chem codes should comply with the named vocabulary for BIMS

![imagem](https://user-images.githubusercontent.com/178003/164409751-599f8d5a-1643-43c9-ac62-56628b01af75.png)


Can we get the data structured into a sheet that looks like this.

site code | site description | date | lat | long | chemical code 1 | chemical code 2 | ...|
------------|----------------------|-------|------|------|-----------------------|-------------------------|----|

The following rules can apply:

* the chem code should match one of the named codes in FBIS (more can be added if needed)
* if any cell is blank it will be ignored for chemical codes
* site description is optional
* the imported sites will not be a biological data records (we will update BIMS to include non biological records on the map too) 
![imagem](https://user-images.githubusercontent.com/178003/164411263-d1c9f3d4-77b1-4563-b1e7-abff72105f97.png)
* if the lat lon matches another site with a different site code we will raise an error
*

**Comment by timlinux** [comment]
Can we get the data structured into a sheet that looks like this.

site code | site description | date | lat | long | chemical code 1 | chemical code 2 | ...|
------------|----------------------|-------|------|------|-----------------------|-------------------------|----|

The following rules can apply:

* the chem code should match one of the named codes in FBIS (more can be added if needed)
* if any cell is blank it will be ignored for chemical codes
* site description is optional
* the imported sites will not be a biological data records (we will update BIMS to include non biological records on the map too) 
![imagem](https://user-images.githubusercontent.com/178003/164411263-d1c9f3d4-77b1-4563-b1e7-abff72105f97.png)
* if the lat lon matches another site with a different site code we will raise an error
*

**Comment by timlinux** [comment]
See walkthough here

https://youtu.be/IxnIpSZ7txI

**Comment by helendallas** [comment]
Links to #2993 

WQ template included in this ticket

**Comment by helendallas** [comment]
Closing ticket by way of ticket #3055 and #3054
