### ISSUE TITLE
Please delete all data from Shelton et al. 2018

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3019]
@dimasciput please can you delete all data from this reference, including the reference itself:
![unnamed](https://user-images.githubusercontent.com/44292029/163093657-9d907e04-9cf4-46e2-8a32-87d1c4a0b3a3.png)
Thanks

**Comment by dimasciput** [comment]
@jeremyshelton all the occurrence records with this source reference have been deleted.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput
