### ISSUE TITLE
Admin need to be able to add a new Chem Unit

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3022]
At the moment I am able to edit Chemistry unit table, but I cannot add a new unit.

I can click on Chem Code
But if the Unit is not in the dropdown list, I cannot add it.

![image](https://user-images.githubusercontent.com/45286876/164445891-59722665-8fbb-4260-b4f2-bd176eb06021.png)

In this example I need to be able to add
Cfu/100ml

**Comment by helendallas** [comment]
@dimasciput This is in review, but I am not sure where to test it? FBIS testing?

**Comment by dimasciput** [comment]
@helendallas sorry, rbis testing.

**Comment by helendallas** [comment]
@dimasciput Please can you add this and ticket #3055 to FBIS testing.

RBIS does not yet have any physico-chemical data.
![image](https://user-images.githubusercontent.com/45286876/169537579-cab78f70-f523-4806-859d-6c95c491ce85.png)

Also please can you import the Chemical Unit table from FBIS to RBIS
![image](https://user-images.githubusercontent.com/45286876/169537758-39d71d23-c6f9-4de8-a70d-49d966d80e32.png)


Once done, I can test

**Comment by helendallas** [comment]
Thanks this seems to be working. Please deploy to live (FBIS and RBIS)

**Comment by helendallas** [comment]
Closing as working on FBIS testing and live and RBIS testing
