### ISSUE TITLE
Fix unclassified Geomorphological zones

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3024]
Some sites are listed in the Geomorphological Filter as Unclassified, and yet when I go in to edit the site, they do have  geom zone.

@dimasciput to fix in the backend in the next sprint.

There are 160 such sites, I can manually correct them by going into the site edit and fetching geom zone…but better to find out why this happened.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,geo_class_recoded,Unclassified%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/164652254-1e80a431-529e-4027-a9db-505d3370e540.png)

**Comment by dimasciput** [comment]
@helendallas I have updated this on live site, please can you check it again.

**Comment by helendallas** [comment]
Thanks @dimasciput Many are fixed. I will go through the balance and check. Closing ticket

**Comment by helendallas** [comment]
Please can you check again as several sites are not being correctly classified even though the geom zone is there. for e.g.

![image](https://user-images.githubusercontent.com/45286876/165257954-94bdd93f-ff63-4610-9f5e-53fc43bbdcef.png)

![image](https://user-images.githubusercontent.com/45286876/165258022-a94ea424-303d-41b9-8a39-58dc85f5399c.png)


then when I edit site and click fetch geom zone:

![image](https://user-images.githubusercontent.com/45286876/165258119-59316b44-d30c-4954-99c3-3a7bde06bbaf.png)

**Comment by helendallas** [comment]
Here is the url to sites still unclassified

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,geo_class_recoded,Unclassified%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by dimasciput** [comment]
@helendallas do you want us to re-fetch the geomorphological zone data for all unclassified sites?

**Comment by helendallas** [comment]
Yes please @dimasciput as several should have geom zones, but are shown as unclassified

**Comment by helendallas** [comment]
I will do this manually. Closing ticket
