### ISSUE TITLE
Hide Thermal Metrics if water temperature data is not a full year

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3036]
At the moment, if less than a years data are available, the thermal metrics are shown. This is inaccurate as the thermal metrics should only be calculated when there is a full years data.

Is it possible to hide the Thermal Metric section when data are less than a full years worth, and just give Monthly Magnitudes.

I realise @dimasciput this is extra but thinking about it it can be misleading if thermal metrics are given for a year, when data are only for 3 months.  

Not sure how much effor this will require??

https://freshwaterbiodiversity.org/water-temperature/33349/2007/?taxon=&search=G1BERG-00310&siteId=33349&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%2C%22gbif%22%2C%22virtual_museum%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=33349&orderBy=name&polygon=&thermalModule=&dst=&startDate=2007-01-01&endDate=2007-12-31

![image](https://user-images.githubusercontent.com/45286876/165075170-27787a7e-59cf-452f-8cad-cc050d0309ad.png)

**Comment by helendallas** [comment]
Or perhaps when there is < 10 months data, so that one gets more accurate annual statistics

**Comment by dimasciput** [comment]
@helendallas yes it's possible and it's not too difficult. @Fanevanjanahary can you handle this one? Thanks

**Comment by helendallas** [comment]
Sorry @dimasciput @Fanevanjanahary I am still seeing the Thermal Metric table when the water temperature data in a year is < 10 months.

So to confirm,

If the data from 1 Jan...to 31 Dec is less than 10 months worth, then the Thermal Metric table should be hidden, as the statistics shown for this do not make sense.

See this example, only have data for 2 months

https://testing.healthyrivers.kartoza.com/water-temperature/10358/2008/?taxon=&search=&siteId=10358&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=10358&orderBy=name&polygon=&thermalModule=True&dst=&startDate=2008-01-01&endDate=2008-12-31


so this whole table should be hidden
![image](https://user-images.githubusercontent.com/45286876/165694127-c30fc066-c30b-4f12-92a1-feeb0af34b75.png)

**Comment by dimasciput** [comment]
@helendallas it seems the testing is not updated with this fix yet, let me re-deploy

**Comment by helendallas** [comment]
Ok @dimasciput Let me know when its ready for testing. It woudl be great to have those tickets ready deployed to live before the end of this sprint :)

**Comment by dimasciput** [comment]
@helendallas I have updated the testing site, please check again. I will try to deploy to live site later today.

**Comment by helendallas** [comment]
Working nicely, thanks @dimasciput
