### ISSUE TITLE
Filter search error

### ISSUE THREAD

**Issue by Vries14** [kartoza/django-bims#305]
# Bug report

I did a search on non-native species in the Limpopo administrative area.

# Error
The following was my result
![Screenshot_2018-08-31 Django BIMS Map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc64167f3e7a55e30f7a84ed2fb0025928223c5ed110184d58eeb9cb74fce36f34985619e880685c71973b13a4bbd316bd53ba208a1d82bfed8e1e93fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e44a55ac103063ee7f366e0a.png)

# Expected behaviour

Im expecting to see the boundary of my search. Thus only the non-native species in the Limpopo region/ administrative area

**Comment by dimasciput** [comment]
@Vries14 did you only do category filter? Without other filters?

**Comment by dimasciput** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/1979569/44905612-cdf79d00-ad3c-11e8-8a4c-25c9481e60cf.png">

It works for me, on the testing server.

**Comment by Vries14** [comment]
A category and an administrative filter.

**Comment by dimasciput** [comment]
@Vries14 ah ok, just saw your screenshot

**Comment by dimasciput** [comment]
@Vries14 fixed on testing, please try again

**Comment by dimasciput** [comment]
@Vries14 would it be better to create this ticket on the healthyrivers instead? I think issues on django-bims should be tested on the latest django-bims site, which is testing.limpopobims now.

**Comment by Vries14** [comment]
ok, @dimasciput
