### ISSUE TITLE
Deleting a site with water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3050]
At the moment I cannot delete water temperature or a site where there is water temperature data. 

I get a 

![image](https://user-images.githubusercontent.com/45286876/165941339-d3901845-c00e-40b1-88cb-53e0b3e7b609.png)

when trying to delete the site with the water temperature data -  here is the site

E1OLIF-DUPL

**Comment by dimasciput** [comment]
please test on testing

**Comment by helendallas** [comment]
Thanks. I am now able to delete the site that only has water temperature data. Please deploy to live
