### ISSUE TITLE
Uploading water temp data to a site that already has water temp data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3051]
We need to be able to overwrite existing water temperature data in cases where the incorrect data has been added.

For example: for H1HOLS-STET2 I added data that still had -99, for missing values instead of being blank.

So the stats and graphs dont make sense.

https://freshwaterbiodiversity.org/map/#search/H1HOLS-STET2/taxon=&search=H1HOLS-STET2&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=86253&dst=

![image](https://user-images.githubusercontent.com/45286876/165942143-d14a7efd-f276-4d2e-806c-4f76dcee9a74.png)

I corrected the water temperature data by removing all the -99 values, and tried to add water temperature data again for the whole period 2008-2011, as well as separated for the years 2009 and 2010, by using the 
![image](https://user-images.githubusercontent.com/45286876/165942840-deb10ad7-c519-423e-8e73-509a74c16f44.png)
  
BUT
I kept getting the message - and then the actual water temperature data was not updated.

![image](https://user-images.githubusercontent.com/45286876/165942547-926591d0-40fd-4c51-931e-b7f5f6cd257f.png)

and the graphs etc is the same

![image](https://user-images.githubusercontent.com/45286876/165942960-54da95e1-f04b-477b-8c5b-11e550ac017a.png)

**Comment by dimasciput** [comment]
Ready to test in testing.

**Comment by helendallas** [comment]
@dimasciput I uploaded the corrected data to the 2009 year for H1HOLS-STET2 , but it is just spinning......and I cant do anything else or get out.

![image](https://user-images.githubusercontent.com/45286876/179910790-9078d832-b8b7-41f6-9433-c3e830d30e3f.png)


Please can you check what the issue is, thanks

**Comment by dimasciput** [comment]
@helendallas can you try it again please?

**Comment by helendallas** [comment]
So it is working now thanks @dimasciput but the close button is not working

![image](https://user-images.githubusercontent.com/45286876/179917596-6fcbbebf-9231-4b90-ac20-32c3ae726a49.png)

**Comment by helendallas** [comment]
Thanks this is working now on live, closing ticket
