### ISSUE TITLE
ORBIS - Upload Taxonomic data - error message 'canonicalName'

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3052]
When I Uploaded Taxonomic data into ORBIS, I got an error message I have not received before. I do not know what it means as the species are on GBIF.

For amphibians two taxa (Xenopus laevis and Xenopus muelleri) did not upload. Reason provided in error file: last column was:  'canonicalName'

I also got 27 errors for Birds, same 'canonicalName'

Here is the error file
[error_Botswana_Amphibian_Master_2022_04_20_ubFpWVP.xlsx](https://github.com/kartoza/django-bims/files/8619617/error_Botswana_Amphibian_Master_2022_04_20_ubFpWVP.xlsx)

**Comment by helendallas** [comment]
Strangely they have been pulled down in GBIF, even though they are not in our master list as they didnt upload

![image](https://user-images.githubusercontent.com/45286876/166669476-615f2123-5128-4b04-83d4-5980aa645b22.png)



![image](https://user-images.githubusercontent.com/45286876/166669370-c7b42803-3fc8-49dc-b9d8-32d08744a82f.png)

And then disappear when I select the amphibian module, not sure what is happening here?
![image](https://user-images.githubusercontent.com/45286876/166669673-00503b2d-214c-4c07-adac-0116d0bf75d9.png)

**Comment by dimasciput** [comment]
@helendallas I will check this next week

**Comment by dimasciput** [comment]
@helendallas this should be fixed in orbis, can you test it again please
