### ISSUE TITLE
We need to be able to bulk upload Physico-chemical data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3055]
We need to be able to upload a spreadsheet of physico-chemical data using this template: This needs to available in Admin section.  

The processes should be the same as for the uploading of biological occurrence data. The assumption is the physico-chemical variable must already be in the Chemistry unit table. If it is missing then an error message must alert the admin person that the variable is missing (the same was as a missing taxon is noted in the error file)

**Upload Physico-chemical Data**

[RBIS Water Quality Data Template.xlsx](https://github.com/kartoza/django-bims/files/8630515/RBIS.Water.Quality.Data.Template.xlsx)

![image](https://user-images.githubusercontent.com/45286876/166909051-d9a64ae4-5e21-4a86-89b8-ffc697db0204.png)

**Comment by dimasciput** [comment]
@helendallas this has been added to testing.rbis.kartoza.com, here's the url : https://testing.rbis.kartoza.com/upload-physico-chemical/

**Comment by helendallas** [comment]
@dimasciput getting error message
![image](https://user-images.githubusercontent.com/45286876/169273529-c7c1ad27-261e-46b2-a391-febc8e472ece.png)

**Comment by dimasciput** [comment]
@helendallas please login first

**Comment by helendallas** [comment]
Thanks @dimasciput 

A few tweeks: Please change to Upload Physico-chemical Data in 
Dropdown and Upload form

![image](https://user-images.githubusercontent.com/45286876/169534449-7933aa07-053c-44d9-9785-a0b66fb95970.png)

![image](https://user-images.githubusercontent.com/45286876/169534157-89f60bae-a2e5-4468-a095-85e55f4bef68.png)

**Comment by helendallas** [comment]
Please can you copy the Chemical Unit table fro FBIS to RBIS. I dont want to have to recreate all these variables.  Once this is done then I can test it. Alternatively please roll out to FBIS testing.

**Comment by helendallas** [comment]
@dimasciput I have tried it on FBIS testing and RBIS testing. 

RBIS testing - the uploaded data look fine, however neither the Abiotic / Physcio-chemical or Owner filters do not work, so I had to find site codes in backend.
 
I uploaded dummie data under my name: Helen Dallas as the owner on RBIS.
![image](https://user-images.githubusercontent.com/45286876/173325772-b25ce929-8ac5-47d3-ace6-099719d22162.png)

The dashboard for physico-chemical data in RBIS is also wrong as it has the FBIS overview

https://testing.rbis.kartoza.com/physico-chemical/4822/?taxon=&search=&siteId=4822&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22RBIS%22]&abioticData=True&ecologicalCategory=&rank=&siteIdOpen=4822&orderBy=name&polygon=&thermalModule=&dst=

In FBIS testing I added data under the Owner: Test Tester, but it does not show in the Owner filter. I managed to find the sites, in the backend and then filtered for them on the front end.

Graphs look fine.

**Comment by timlinux** [comment]
Can I suggest along with the menu change We make a group header called upload and then remove the upload prefix from all entriees

**Comment by timlinux** [comment]
Also we should remove this section for RBIS:

![image](https://user-images.githubusercontent.com/178003/174023849-90b54001-1258-4164-8b57-f5a2c727837b.png)

**Comment by dimasciput** [comment]
> @helendallas RBIS testing - the uploaded data look fine, however neither the Abiotic / Physcio-chemical or Owner filters do not work, so I had to find site codes in backend.

Yes currently it's not possible to do this, the search is getting more complicated with a lot of parameters. I think we should discuss this before I try to address this myself.

**Comment by helendallas** [comment]
Okay @dimasciput Lets discuss. I am available now if you want to chat

**Comment by dimasciput** [comment]
@helendallas are you available early next week Helen? I will send you an invite.

**Comment by helendallas** [comment]
Hi sorry no. I am away next week. I can meet the following week, 6th.

**Comment by helendallas** [comment]
> Can I suggest along with the menu change We make a group header called upload and then remove the upload prefix from all entries
> 
> ![image](https://user-images.githubusercontent.com/178003/174023437-84360ce2-2766-4585-8cd8-ff877b64cab6.png)
> 
> This will remove redundancy and prevent the menu becoming overly wide.

@dimasciput This should be UPLOAD not DOWNLOAD

![image](https://user-images.githubusercontent.com/45286876/175516616-b2048a7a-fb41-41af-9df7-5f651ffad654.png)

**Comment by dimasciput** [comment]
@helendallas ah yes sorry! Such a rookie mistake.

**Comment by helendallas** [comment]
:)

**Comment by helendallas** [comment]
Thanks @dimasciput This all seems to be working. closing ticket now
