### ISSUE TITLE
Study References with Water temperature data not visible in filter

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3057]
Studies added that only have water temperature data not biological records, are not visible in the Study Reference filter

![image](https://user-images.githubusercontent.com/45286876/167142919-75796795-c54d-45d9-86bd-77287ac9588c.png)

PLease can you check, as one should be able to search for any study reference

**Comment by helendallas** [comment]
Now study reference is showing up but it is not filtering the data

![image](https://user-images.githubusercontent.com/45286876/173335102-c86fd030-6a40-4ea5-af7d-cbb47346a662.png)

**Comment by dimasciput** [comment]
@helendallas for now if you want to see water temperature data you have to check water temperature data in the abiotic module.

**Comment by helendallas** [comment]
So I dont think this filter is working. We need to be able to find water temperature data using the study reference filter.

So if I click water temperature data in abiotic module, and add the dallas and rivers-moore study reference, then I get all 81 water temperature sites:

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221146%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=True&dst=

![image](https://user-images.githubusercontent.com/45286876/179914036-4e038eb1-1783-439d-ab81-2f3e138b7435.png)

See here as well, where I search for Olsen -  there should only be 10 sites

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22687%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=True&dst=

![image](https://user-images.githubusercontent.com/45286876/179914347-fc26556e-3b00-436f-832e-8ccd023ef472.png)

**Comment by dimasciput** [comment]
@helendallas Let's discuss this in the sprint planning meeting since the query is getting complicated and basically water temperature is not occurrence data.

**Comment by helendallas** [comment]
Okay thanks, happy to chat.

**Comment by helendallas** [comment]
Thanks @dimasciput Your workaround with Radio buttons sounds the way to go

**Comment by helendallas** [comment]
@dimasciput we need to chat re this ticket. Still not able to filter by study reference for the water temperature data.

The drawer should still be called Abiotic module.

Not sure how this all works.

**Comment by helendallas** [comment]
Only problem is sites dont always show, see here
![image](https://user-images.githubusercontent.com/45286876/222436512-0d52816a-7e70-4634-bb10-be6dca8127f5.png)

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22687%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=water_temperature&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by dimasciput** [comment]
deployed to production
