### ISSUE TITLE
Please check two Biological records with Kartoza_admin as owner

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3059]
There are many sites where Kartoza_admin is the owner in the Biological Records table
![image](https://user-images.githubusercontent.com/45286876/167591507-5f005779-1edc-449a-ac69-7320369202a1.png)

https://freshwaterbiodiversity.org/admin/bims/biologicalcollectionrecord/?o=8

Here is an example:
Please check if these are real or fictitious records and delete if the latter.

They are both at the same site:
https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=C9KLEI-00002&siteId=48445&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=48445&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/167590666-ebbec602-344d-4875-bd85-57fc77b9e2d4.png)

https://freshwaterbiodiversity.org/admin/bims/biologicalcollectionrecord/882376/change/?_changelist_filters=o%3D8

![image](https://user-images.githubusercontent.com/45286876/167590039-be2f0558-8778-4680-8f3a-58bdfc1e9e55.png)

https://freshwaterbiodiversity.org/admin/bims/biologicalcollectionrecord/882375/change/?_changelist_filters=o%3D8

![image](https://user-images.githubusercontent.com/45286876/167590109-c67b6116-739c-42f7-86ae-f23eac0a4d71.png)

But in the front end only there are seven records.

![image](https://user-images.githubusercontent.com/45286876/167592146-62b80b5e-7972-4b4d-997a-1e68845aa3e5.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Kartoza_Admin%20%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by dimasciput** [comment]
@helendallas This has been fixed, they are old data that should be removed. Perhaps they come back when we restored the data from old database.

**Comment by helendallas** [comment]
Thanks, closing ticket
