### ISSUE TITLE
We need a mobile app

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#3060]
We need a mobile app with these priorities:

* SASS Capture
* Fish Capture
* Basic physicochemistry (e.g. dissolved O2)
* Location Site Capture + photo(s)

The app needs to work online / offline.

We don't need dashboard or other features from the website.

Focus on Android first then iOS.

The location sites need to be stored on the phone and refreshed regularly when you have connectivity.

We can use a 500m threshold your current location to determine if a site should be shown.

User should be able to add data to an existing site or choose to create a new site.

When adding a new site we use a placeholder id and description and then these are converted to lookup up ID when the data is submitted.

Then uploading data collected in the field the user will have a staging area on the website where they can do any final checks on the data (and automated validation checks can happen) before submitting it for review on the platform.

Basemaps in the future can be cached in future versions but for now, if you have no internet connectivity, the map will show only what has already been fetched in the session and any locally stored data such as location sites.

**Comment by helendallas** [comment]
Closing ticket as has been broken down to several separate tickets
