### ISSUE TITLE
Unable to add new source reference

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#3061]
Unable to add new source references (see screenshot).

![image](https://user-images.githubusercontent.com/55532903/168238098-b000bab8-8828-4c2e-986c-62883d46ef17.png)

**Comment by helendallas** [comment]
@aneriswanepoel Please can you check if this is now working and revert, thanks. On testing site.

**Comment by aneriswanepoel** [comment]
@helendallas okay it's working now

**Comment by aneriswanepoel** [comment]
@helendallas @dimasciput tried to add a document now (on live) and it's not working

**Comment by dimasciput** [comment]
@aneriswanepoel please try it again now

**Comment by dimasciput** [comment]
please do hard refresh first.
