### ISSUE TITLE
Taxon Dashboards not working correctly

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3066]
In ORBIS, the overview and detailed dashboards are not showing up all the links to IUCN, GBIS or origin and endemism.

On the map and in the detailed dashboard, the map shows all records, not just the selected taxon.

![image](https://user-images.githubusercontent.com/45286876/169258071-7a18d73e-d7f6-4d11-bc52-4df7ff075e01.png)

https://orbis.kartoza.com/map/#species-detail/taxon=1323&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=8&validated=&sourceCollection=[%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

This is not consistent, sometimes shows e.g amphibians.

**Comment by timlinux** [comment]
@dimasciput this is probably a side effect of me quickly knocking together a layer in GeoServer for the sites to show up. Could you clone the query / view from FBIS - I suspect without it the CQL filters passed to GeoServer will not work.

**Comment by dimasciput** [comment]
@helendallas this should be fixed now

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, closing ticket.
