### ISSUE TITLE
Reptiles - not showing in Search Result when name is selected, only when occurrences is selected

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3068]
No records visible here:

![image](https://user-images.githubusercontent.com/45286876/169260233-011632d7-b64a-42db-a455-d0371a22c3a2.png)

When we select occurrences, the records are visible

![image](https://user-images.githubusercontent.com/45286876/169260372-70b589f9-520b-4331-b3ab-4d8d21a454dc.png)

**Comment by dimasciput** [comment]
@helendallas this should be fixed now, please check

**Comment by helendallas** [comment]
@dimasciput Thanks fixed, will close ticket
