### ISSUE TITLE
ORBIS - Endemism filter does not have all categories

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3070]
Please can you check why only Widespread is showing. there should also be subregional endemic

![image](https://user-images.githubusercontent.com/45286876/169270651-ddabbbc4-0be1-4b94-9735-923ba28b24a9.png)

![image](https://user-images.githubusercontent.com/45286876/169270900-5d6d9a0b-6ae5-4b50-8d40-087be1c73e46.png)

Endemism also missing in Taxon overview and detailed dashboards

**Comment by timlinux** [comment]
Are there actually occurrence records for these taxa?

**Comment by dimasciput** [comment]
Fixed from the admin.
