### ISSUE TITLE
Info buttons for Data Source text

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3080]
@dimasciput is it possible to 'hide' the text descriptions for Data Sources in a clickable info button? That way we will be able to see all three of the Dara Source options at the same time.

![Screen Shot 2022-05-27 at 1 38 14 PM](https://user-images.githubusercontent.com/44292029/170693629-116dc7d1-480d-4ccf-974c-ecd9e005179e.png)

**Comment by helendallas** [comment]
Similar to the "Metadata" in the layers? Is that what you had in mind @jeremyshelton ?

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 
Yes, exactly like that.

**Comment by dimasciput** [comment]
Please test on testing @jeremyshelton

**Comment by jeremyshelton** [comment]
Perfect.
Thanks @dimasciput 
This can be rolled out to live.
