### ISSUE TITLE
Show new sites even if biological data has not been added - urgent

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3081]
@dimasciput 
Please can you prioritise this ticket please.

A user added 3 sites. But not any biological data as her colleague was going to add the SASS data after she has created all the sites. This is a common work flow.

These are the sites:
![image](https://user-images.githubusercontent.com/45286876/171013928-1a3794d9-5baa-4a79-879c-01ba321516a3.png)

Can you please change it so that a site shows, regardless of if it has data or not.  

Now she cannot find her sites at all on the map or by using filters, even though they have been created.

**Comment by dimasciput** [comment]
@helendallas this should be fixed now, can you test it again.

**Comment by dimasciput** [comment]
@helendallas can you test on testing site? You might need to create a new site.

**Comment by dimasciput** [comment]
@helendallas yes sorry I forgot to update something, please try it again

**Comment by helendallas** [comment]
Thanks @dimasciput Seems to be working now.

**Comment by helendallas** [comment]
Same with the site I created, now appears in dropdown list twice
![image](https://user-images.githubusercontent.com/45286876/171386450-59e06119-ae63-4c9a-b7fd-4439b6c079a3.png)

**Comment by dimasciput** [comment]
@helendallas should be fixed now

**Comment by dimasciput** [comment]
@helendallas this has been deployed to live site.

**Comment by helendallas** [comment]
Great thanks, checked , closing ticket
