### ISSUE TITLE
Check dates for SASS - Historical data earliest and latest record 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3088]
Historical data earliest and latest record flips the dates around? Earliest should be 2020-02-24 but coming as 2024-02-20

![image](https://user-images.githubusercontent.com/45286876/171804376-0878410b-e2e1-4b08-b77e-910cf4d590af.png)

![image](https://user-images.githubusercontent.com/45286876/171804405-6b3c5113-9321-4918-bb3b-2e2dba51a1a7.png)

**Comment by dimasciput** [comment]
This is fixed and deployed to live and testing
@helendallas

**Comment by helendallas** [comment]
Thanks @dimasciput Looking fine now
