### ISSUE TITLE
We need to be able to get the GBIF id for individual points

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3089]
Sometimes a site is in the ocean, or has an incorrect georeference. These are often GBIF data. 

![image](https://user-images.githubusercontent.com/45286876/171811784-f6a78ffe-f37d-4f01-b04c-2cddff24d727.png)

The upstream organisation, e.g. SANBI, would be willing to correct the data point but need the GBIF id to do this.

Can we include a ink to the GBIF record in the Site dashboard - perhaps in the last line of the overview under site description.

If the record is not GBIF, then it is blank, or shows as not GBIF

![image](https://user-images.githubusercontent.com/45286876/171812237-7d7303a1-2e92-47c4-997b-cdf59281a773.png)

**Comment by jeremyshelton** [comment]
....and an equivalent for the Virtual Museum records.
I assume that those records also have some sort of unique identifier?
@helendallas @dimasciput

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton hi, what do you think about this  implementation https://github.com/kartoza/django-bims/pull/3135 ? 
So we show gbif species links, not occurrences, because we can have 100+ records per site and the user interface will look ugly and will also affect performance.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton also you can get these gbif/museum record ids when you download the csv, so I don't think this is necessary?

**Comment by helendallas** [comment]
We can limit this to single site dashboards only?

Users will most use this for single sites, It needs to be in the dashboard if possible, not only the csv as this then requires extra detective work.

**Comment by dimasciput** [comment]
@helendallas we can still have 1000+ gbif occurrences per site, for example : https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=H3KOGM-00001&siteId=25043&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=25043&orderBy=name&polygon=&thermalModule=&dst=

What if we add a new download button to just download gbif ids?

**Comment by helendallas** [comment]
Thanks @dimasciput Yes, its a tricky one when there a lots of records. This came from a user, so keen to implement. Yes, I am happy with a Download button to download GBIF ids.

Thanks

**Comment by dimasciput** [comment]
@Fanevanjanahary can you implement this? Please add the button in the single site dashboard.

**Comment by helendallas** [comment]
Any progreee @Fanevanjanahary

**Comment by Fanevanjanahary** [comment]
@helendallas this is fixed here #3135 but the PR is not merge yet

**Comment by helendallas** [comment]
Hi @Fanevanjanahary I am not sure what you mean by PR is not merge yet?

@dimasciput ?

**Comment by dimasciput** [comment]
@helendallas it means Faneva has made a proposed change, but I haven't approved it yet. But I don't think this is good solution, since we will have a lot gbif ids for one of the site.

**Comment by dimasciput** [comment]
@helendallas ah sorry Faneva has changed the solution to only show the download button that will return gbif ids, I will review it next sprint.

**Comment by dimasciput** [comment]
Please test on testing.

**Comment by jeremyshelton** [comment]
@dimasciput I am getting this error when clicking the button: https://testing.healthyrivers.kartoza.com/uploaded/processed_csv//home/web/media/processed_csv/d12f901573d5bebce9da69128789b6ec6ae7cda880899f4a4fcf2bfe6ecfa0f1.csv
<img width="243" alt="Screenshot 2022-11-28 at 07 33 21" src="https://user-images.githubusercontent.com/44292029/204201552-c1b0e08c-a39e-41fb-8c03-51d9972d96ce.png">
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton please give it another try

**Comment by jeremyshelton** [comment]
@dimasciput OK the download is working now. 

However, the link provided in the download leads to this page (which shows multiple records : https://www.gbif.org/species/9301710
Is it possible to provide the link to the record for that specific site?

Also, the button text should be "GBIF ID"

**Comment by helendallas** [comment]
This still isnt working -  testing or production

![image](https://user-images.githubusercontent.com/45286876/218478425-952d4a39-e3bc-4239-86a6-b83b62832cab.png)

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas The GBIF id button looks out of place?
Can we not just get the GBIF IDs via the normal csv download?
<img width="516" alt="Screenshot 2023-02-22 at 07 14 03" src="https://user-images.githubusercontent.com/44292029/220529086-6160623a-89e6-4464-9683-89b97ba30cb8.png">

**Comment by helendallas** [comment]
This ticket came following a request from Willem Coetzer from SAIAB saying they could only fix erroneous GBIF occurrence data if they had direct access to the GBIF id. So We need to keep as it. He can then select a specific data record and get the id etc.

But at the moment it doesn't seem to be working
![image](https://user-images.githubusercontent.com/45286876/224945764-ee5f34c8-356c-4072-ad25-9549a2f539ec.png)

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[18.399524688720703,-34.3158639256024],[18.411884307861328,-34.35796272885966],[18.42905044555664,-34.354845023671444],[18.42510223388672,-34.33046624049496],[18.408279418945316,-34.31869952533347],[18.403301239013672,-34.31472965888843],[18.399524688720703,-34.3158639256024]]&dst=

**Comment by helendallas** [comment]
I have tried on testing and production.....same issue

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22gbif%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[27.586669921875,-33.346590435898406],[27.696533203124996,-34.17318076114498],[29.9871826171875,-34.37744575857741],[30.668334960937496,-33.20422235093438],[30.1519775390625,-32.280166633565685],[28.6138916015625,-32.91879097277369],[27.586669921875,-33.346590435898406]]&dst=

**Comment by helendallas** [comment]
So @dimasciput the download file arrived but it looks exactly the same as the csv file. What we need here is a link from individual sites to the GBIF id....I dont even know what you use to track down a GBIF record. @jeremyshelton Any idea????

**Comment by helendallas** [comment]
So @dimasciput the download file arrived but it looks exactly the same as the csv file. What we need here is a link from individual sites to the GBIF id....I dont even know what you use to track down a GBIF record. @jeremyshelton Any idea????

**Comment by jeremyshelton** [comment]
@dimasciput OK thanks. Just to confirm, is the GBIF ID the number in the column 'upstream id' in the csv?

<img width="728" alt="Screenshot 2023-03-21 at 06 43 10" src="https://user-images.githubusercontent.com/44292029/226521369-7c8ee84e-25fb-4947-b62a-fd3558f03fb4.png">


I still think it would be nice to include in single site dashboard so that people like Willem at SAIAB can quickly and easily get the GBIF id for an erroneous site......but guess the csv is fine for now.

@helendallas

**Comment by helendallas** [comment]
Yes @jeremyshelton I was envisaging a link from the Single Site dashboard to the GBIF record. That way a user can find the upstream data which can be fixed
