### ISSUE TITLE
Validation of sites and records

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3091]
I dont think that this is working correctly as there are data showing as unvalidated but they were uploaded by the RBIS data team using the occurrence upload templates and should therefore all be automatically validated.

![image](https://user-images.githubusercontent.com/45286876/171825907-bbd651df-b71e-47d8-8a41-e00809f5a51a.png)

Please can you check and make all data in RBIS validated.

Also the Site Validation is showing GBIF sites -  which it should not show.
![image](https://user-images.githubusercontent.com/45286876/171825806-2b985e66-c47a-4b90-bffe-1f6c1567f1f0.png)

**Comment by dimasciput** [comment]
This is fixed in live site

**Comment by helendallas** [comment]
Thanks @dimasciput Looks fine, closing ticket
