### ISSUE TITLE
Check why some records have Source Reference as None

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3099]
![image](https://user-images.githubusercontent.com/45286876/173305502-1d83a70d-732e-48fa-b22d-de4d12f004ca.png)

Please can you fix these records to be Source Reference =  FBIS. I am not sure why they are recorded as None?

**Comment by dimasciput** [comment]
Hi @helendallas , it's because they don't have occurrence records. Source reference is attached to occurrence record/abiotic record/water temperature data. 

It seems these site visits only have abiotic records, the legacy abiotic data doesn't have source reference. Should we assign them to FBIS?

**Comment by helendallas** [comment]
OK thanks @dimasciput I think there are some errors in here for e.g. Toni Olsen data is all linked to fish data.

These records don't come up when I search on Owner =  Toni Olsen. I cant check what abiotic data has been added, but there shouldn't be any that is not linked to fish data?  How can I see what abiotic data are associated with these site visits.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Toni%20Olsen%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by dimasciput** [comment]
@helendallas hmm I can see the site visits from Toni olsen here : https://freshwaterbiodiversity.org/site-visit/list/?&collectors=%5B11%5D&sourceCollection=%5B%5D&modules=1
I'm not sure I understand the question. 

> How can I see what abiotic data are associated with these site visits.

I think when I finished implementing the new search feature, the filter will work bettter on the map.

**Comment by helendallas** [comment]
This seems to be sorted, closing ticket
