### ISSUE TITLE
Metadata not being added to Physco-chemical dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3100]
Once physico-chemical data have been added to as site, the Source Reference of the data shold be listed in the Metadata table.

It is presently missing in both RBIS and FBIS.

https://testing.rbis.kartoza.com/physico-chemical/8429/?taxon=&search=-01206&siteId=8429&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22RBIS%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=8429&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/173342361-54b7088d-4821-494c-9acb-96d4894487c3.png)

**Comment by dimasciput** [comment]
@helendallas I'm going to remove this from fbis project, will address it with RBIS time

**Comment by helendallas** [comment]
Has this been rolled to FBIS testing as well yet?

**Comment by helendallas** [comment]
Looks good on RBIS testing, still needs to be actioned on FBIS

**Comment by dimasciput** [comment]
deployed to live
