### ISSUE TITLE
Spatial layer - Rwanda Forest cover

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3103]
This layer is currently not categorised. It seems that Density is an important categorisation variable, with different densities captured in this column. Perhaps a gradient map of density would work.

@bimeobed Can you discuss with the team 

![image](https://user-images.githubusercontent.com/45286876/173367244-b643ccd0-c1cb-4187-8b21-024440bc17f3.png)

**Comment by bimeobed** [comment]
Thank you @helendallas .We will discuss on this with my team

**Comment by helendallas** [comment]
RBIS project finished, Closing ticket
