### ISSUE TITLE
GBIF ID not showing in CSV data downloads

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3108]
@dimasciput the GBIF ID and other associated columns are blank in CSV downloads for fish and frog data. Also, there is no record identifier information coming through for VM data either.

<img width="1307" alt="Screen Shot 2022-06-15 at 1 30 57 PM" src="https://user-images.githubusercontent.com/44292029/173824512-354f8d82-b47c-4170-85e8-03b2b225df84.png">

@dimasciput @helendallas

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton can I change 'gbif id' to 'upstream id' instead? So we can use it to put gbif id or vm id.

**Comment by helendallas** [comment]
That's fine with me @jeremyshelton ?

**Comment by jeremyshelton** [comment]
👍

**Comment by dimasciput** [comment]
Please test on testing @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput it looks like the the upstream id's are now coming through, but the data are not separated into columns so it's not east to test and check this properly (see below)
<img width="1458" alt="Screenshot 2022-06-21 at 13 57 17" src="https://user-images.githubusercontent.com/44292029/174793948-e5f24484-6dae-4a85-84fe-fd66026db6ae.png">

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas I think it was issue with your excel, you need to set the excel to separate data by comma.

**Comment by jeremyshelton** [comment]
@dimasciput hat is strange, because for my downloads on the live site the data are separated into columns automatically:

<img width="1149" alt="Screenshot 2022-06-22 at 06 59 06" src="https://user-images.githubusercontent.com/44292029/174947177-6a0d03a8-cba9-4d0c-98d2-02add470f001.png">

Is the testing site currently a mirror of live site?

**Comment by dimasciput** [comment]
@jeremyshelton yes it's a mirror, did you download the data in live site from email or download request page?

**Comment by jeremyshelton** [comment]
@dimasciput I downloaded it from the testing site because I did not receive an email download notification following my download request.

**Comment by dimasciput** [comment]
> I downloaded it from the testing site because I did not receive an email download notification following my download request.

You need to check your spam folder, I think testing will always go to spam.

**Comment by helendallas** [comment]
Hi @jeremyshelton and @dimasciput 
I received the file in Spam, so easy to find. And it opened as normal in excel.. Try and revise your default settings in excel Jem.

**Comment by helendallas** [comment]
ID is showing up, please deploy to production

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput - yes, it looks like the upstream identifier is being pulled through for both GBIF and VM data. 

Still a few issues to resolve: 

- I see no information in the 9 columns to the right, which should be populated with data?
**Dataset key | Occurrence id | Basis of record | Institution code | Collection code | Catalog number | Identified by | Rights holder | Recorded by**
If these columns are going to always be blank then perhaps they should be removed from the CSV download?
Is this info not also going to be needed for detailing the data source when users cite data downloaded from FBIS?

- How do we use the upstream ID to get to the original record on GBIF? I have looked but cannot find it...
I see it can be done here for the VM: https://vmus.adu.org.za/vm_search.php?database=safap&prj_acronym=FrogMAP&db=safap&URL=http://adu.org.za/frog_atlas.php&Logo=images/frogmap_logo.png&Headline=Frog%20Atlas%20of%20Southern%20Africa&Use_main_filter=0&User_id=&Full_name=&serve_sp_list=1&drop_down_list=0&assessment=0&message=Search_returned_no_records

- Is there perhaps a way to to provide a url link to the GBIF/VM record so that users can trace the record back to its source?

**Comment by dimasciput** [comment]
> How do we use the upstream ID to get to the original record on GBIF? I have looked but cannot find it...

https://www.gbif.org/occurrence/{upstream_id}

> Is there perhaps a way to to provide a url link to the GBIF/VM record so that users can trace the record back to its source?

It will make the csv significantly bigger. Here's the url for Virtual Museum : https://vmus.adu.org.za/vm_view_record.php?database=safap&prj_acronym=FrogMAP&db=safap&URL=http://adu.org.za/frog_atlas.php&Logo=images/frogmap_logo.png&Headline=Frog%20Atlas%20of%20Southern%20Africa&Use_main_filter=0&User_id=&Full_name=&serve_sp_list=1&drop_down_list=0&assessment=0&query_id=38428&Vm_number=0&recNo=0&numRows=1&Vm_number=12&recNo=1

**Comment by jeremyshelton** [comment]
Yeah, I also found that GBIF page, but it does not seem to be working?
@dimasciput are you able to find a GBIF record using that page + GBIF ID?

Yeah - that's a long url. Maybe not appropriate for csv.

**Comment by dimasciput** [comment]
@jeremyshelton yes it should be, the key is coming from gbif. If you can't open it in gbif, they probably delete the page but still keep the record in database, I'm not sure. Which id is not working?
