### ISSUE TITLE
Dashboard image downloads not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3109]
The downloaded image from this button appears blank.

<img width="431" alt="Screen Shot 2022-06-15 at 1 58 09 PM" src="https://user-images.githubusercontent.com/44292029/173825664-6b66ddcc-17c1-45e2-b755-6ee6be39e7fd.png">
<img width="568" alt="Screen Shot 2022-06-15 at 2 21 01 PM" src="https://user-images.githubusercontent.com/44292029/173825676-30d147b5-0286-47dc-a377-7a23b07fff80.png">

**Comment by dimasciput** [comment]
@jeremyshelton I couldn't replicate this issue, what browser did you use? Can you try it again?

**Comment by dimasciput** [comment]
@jeremyshelton I couldn't replicate this issue, what browser did you use? Can you try it again?

**Comment by jeremyshelton** [comment]
This is what I get when I click on the download. Am I doing something wrong?
<img width="1308" alt="Screenshot 2022-06-21 at 05 50 09" src="https://user-images.githubusercontent.com/44292029/174713116-ec037a63-d507-43f3-9748-391b508e1d9d.png">

**Comment by jeremyshelton** [comment]
https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[17.984619140625,-34.089061315849946],[18.885498046875004,-34.741612498831714],[18.841552734375,-33.651208299204974],[18.270263671875,-33.61461929233378],[17.984619140625,-34.089061315849946]]&thermalModule=&dst=

**Comment by jeremyshelton** [comment]
@dimasciput this seems to be working fine now. 
I previously tested it using both safari + chrome.
Closing ticket.
