### ISSUE TITLE
Harvesting from GBIF not working correctly on FBIS testing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3110]
Please check the GBIF harvesting: Two issues:

It hangs , I ran it for Odonate adults and plants and both stopped early on.
It brings down data for the of Africa, not just SA.

![image](https://user-images.githubusercontent.com/45286876/174244647-91e19348-20f6-4de7-a9dd-38a5b3e58b69.png)

![image](https://user-images.githubusercontent.com/45286876/174244672-782961fb-bc95-4af1-aaf5-6aedd419d27c.png)

Please can you also check if the same issue is on FBIS Production, thanks

**Comment by dimasciput** [comment]
Please test again on testing @helendallas , you need to reupload the taxa list

**Comment by helendallas** [comment]
So I uploaded the wetland plant list and harvested from GBIF overnight. It all appears to be working well now, thanks @dimasciput I will now close the ticket. I will test again for Odonate adults later today as well.
