### ISSUE TITLE
Download request for large dataset did not finish

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3111]
I requested invertebrate data that is 100k+ data, but it stopped processing.
From @dimasciput 
Bad news, it seems the backend stopped processing the data. 

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

@dimasciput to investigate further.

**Comment by dimasciput** [comment]
@helendallas can you test it again in live site please, I have made some improvements in the backend side.

**Comment by helendallas** [comment]
Great that is really useful

**Comment by dimasciput** [comment]
@helendallas apologies, it seems the system won't be able to handle this. I will come up with a better solution.

**Comment by helendallas** [comment]
Has it stopped. Its not often one would do such a large data extraction but in this instance I wanted to check records on mass for inverts, so it would be good to come up with a solution if possible. Thanks @dimasciput

**Comment by helendallas** [comment]
ah okay

**Comment by dimasciput** [comment]
@helendallas I think we also should limit the size of the download for normal users, we can have situation with multiple users requesting 100k+ data at once. What if we add message if the download is too big, they can email the admin directly to get the data?

**Comment by helendallas** [comment]
Agreed, makes sense

**Comment by dimasciput** [comment]
@helendallas I will do that in another ticket

**Comment by dimasciput** [comment]
@helendallas so I managed to resolve this issue in testing, and I found another issue, the csv file size is 22GB, so it's not possible to send it by email. And it takes up a lot of space on the server.  Here's the link if you want to download it : https://testing.healthyrivers.kartoza.com/uploaded/processed_csv/kartoza_admin/6e256a155ff0d49ddcd64bf38d9a2542565bc6e40ca746dee82d5b4ffae56821

Just add .csv at the end of the file once it's finished downloading.

**Comment by helendallas** [comment]
Okay thanks I have started download

**Comment by helendallas** [comment]
@dimasciput Please can you check, this keeps stopping and I need the download file again. thanks

**Comment by dimasciput** [comment]
@helendallas did you test on testing?

**Comment by helendallas** [comment]
@dimasciput  No on live. I tried a few times but it only gets half way then stops. Maybe lets not run it now as our training is starting at 10h00.

**Comment by dimasciput** [comment]
@helendallas okay cool. But I didn't deploy the fix to live I think, since I'm affraid processing large datasets will make the site unstable.

**Comment by helendallas** [comment]
Ok agreed. So then I will try later on testing. I only really need a once off for this large dataset. I will do later

**Comment by dimasciput** [comment]
@helendallas probably do it tomorrow, I'm going to deploy other fixes to testing after training.

**Comment by helendallas** [comment]
Ok, I am headed into the field to dor fieldwork tomorrow so will leave for next week, thanks

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

I am having the same issue with most medium to large downloads that I request. 

I think that there are two issues here: 

1. The long time it takes for a downloads to become available,
2. The fact that some download requests do not finish

The is a very important means of accessing FBIS data and it would be great to find a way to optimise the process...

Thanks

**Comment by dimasciput** [comment]
@jeremyshelton we need to limit the download size, if not then people can abuse the server and make it timeout. 

> 2. The fact that some download requests do not finish

Can you show me which download requests are still not finish?

**Comment by jeremyshelton** [comment]
@dimasciput I requested this one over 5 hours ago...
https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=[%22DFFE%20Screening%20Tool%202022%22]
