### ISSUE TITLE
We need a system to link synonyms to the origin

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3113]
At the moment, we are adding taxa that are synonyms of another taxon, 

e.g Lonchura cucullate (Lonchura cucullata (Swainson, 1837)) is the accepted name on GBIF
Spermestes cucullata Swainson, 1837 is a synonym of Lonchura cucullate 

**Oher examples, even at family level:** 
Melaniidae is a synonym of Thiaridae
Helodidae is a synonym of Scirtidae

![image](https://user-images.githubusercontent.com/45286876/174280278-06d475ce-1b12-4547-ac69-2f464bc987e1.png)

@dimasciput suggested we need to develop a system for linking synonyms and the origin.

Please can we discuss this further as at the moment I am not sure how to name this so that if someone searches on the accepted name e.g. Scirtidae, then data for the synonym are also returned e.g. Helodidae

![image](https://user-images.githubusercontent.com/45286876/174280507-df828e15-e70c-400a-887f-3641aab096e4.png)

![image](https://user-images.githubusercontent.com/45286876/174280844-517e7e98-609f-461e-a514-aaf281c3c06a.png)

![image](https://user-images.githubusercontent.com/45286876/174281003-8b90eb0b-1c4e-4e4e-9b9c-ecb6dd8ec20b.png)

**Comment by dimasciput** [comment]
@helendallas this is still in work in progress : https://github.com/kartoza/django-bims/pull/3124

**Comment by helendallas** [comment]
So I just checked this @dimasciput and I am still getting records for Scirtidae and Helodidae as detailed above.
Can you please explain what you have done?

**Comment by dimasciput** [comment]
@helendallas for existing taxa you need to update it from admin page : https://freshwaterbiodiversity.org/admin/bims/taxonomy/?q=Helodidae. Choose the taxa and then choose update taxa in the dropdown, it should fetch the accepted taxon. 

And then we you search the synonym in the map page, you will receive this result :
![image](https://user-images.githubusercontent.com/1979569/182297040-644e31e7-08e0-4146-8209-b855096952c3.png)

**Comment by helendallas** [comment]
So I updated Helodidae on testing, but when I search on Helodidae
https://testing.healthyrivers.kartoza.com/map/#search/Helodidae/taxon=&search=Helodidae&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

If I search on Scirtidae, I get all.. Is that how it is meant to work?
https://testing.healthyrivers.kartoza.com/map/#search/Scirtidae/taxon=&search=Scirtidae&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

I would really appreciate a chat around this sometime as I ma not to clear now how we deal with synonyms on FBIS.

**Comment by dimasciput** [comment]
> So I updated Helodidae on testing, but when I search on Helodidae
You should see all the taxa. 

It's because you have two Scirtidae on the system : https://testing.healthyrivers.kartoza.com/admin/bims/taxonomy/?q=Scirtidae.
When you merge them you should see the correct result when you searching Helodidae.

**Comment by helendallas** [comment]
Okay so the workflow is click on the taxon I need to update, then update, the search on new name , verify one if there is more than one on the system and click merge.

**Comment by helendallas** [comment]
Closing this ticket as now that FADAtims is happening the workflows will be improved
