### ISSUE TITLE
User not receiving csv download?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3114]
FBIS user Joshua Weeber requested a vac download for anuran data. 
I approved the download, but he did not receive it in his email (including spam).

**Comment by dimasciput** [comment]
@jeremyshelton please ask them to redownload the data again.

**Comment by jeremyshelton** [comment]
@dimasciput I have done so.
Will let you know the outcome.

**Comment by jeremyshelton** [comment]
@dimasciput I get this when trying to approve the download:
<img width="276" alt="Screenshot 2022-06-20 at 13 37 49" src="https://user-images.githubusercontent.com/44292029/174593702-fc00c3f2-5874-4db2-8cb3-9db200e1141f.png">

**Comment by dimasciput** [comment]
@jeremyshelton I think it's because the file is too big, let me fix it tomorrow

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput

**Comment by dimasciput** [comment]
@jeremyshelton please ask the user to check their inbox.

**Comment by jeremyshelton** [comment]
@dimasciput OK will do.
Will revert.

**Comment by jeremyshelton** [comment]
@dimasciput the user did finally receive the download (in his spam folder, after three attempts).
However he picked up multiple issues with the data file that I will detail in a separate ticket.
