### ISSUE TITLE
Reassigning Virtual Museum (and possibly GBIF) records to Record type

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3115]
We need to reassign 'Visual observation' and 'Photographic record' for data coming in from the Virtual Museum (and possible GBIF as well) to record type, instead of sampling method (which it is currently). 
@helendallas @dimasciput @timlinux 
**Conversation needed about this at our next catchup call**

**Comment by helendallas** [comment]
@jeremyshelton I think it should still be kept as sampling method as well. Otherwise nothing will be specified. @dimasciput Please wait on this until we can have a conversation.

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 

I have reassigned the record type to 'photographic record' for records with the sampling method 'photographic record'.

![image](https://github.com/kartoza/django-bims/assets/1979569/3ba264c5-753c-44e4-b966-8d75d1ca7df3)

I also added filters for record type and sampling method in admin page:

![image](https://github.com/kartoza/django-bims/assets/1979569/62ba0089-2e77-46d8-87ee-d71ec89f7001)

I have implemented automatic assignment for records fetched from the virtual museum. If the sampling method is 'photographic record' or 'visual observation', these data will be added to the 'record_type' as well. However, the value of 'sampling_method' will be retained.

**Comment by dimasciput** [comment]
This is added in testing only.

**Comment by jeremyshelton** [comment]
@dimasciput photographic record is still listed under sampling method, but that should be listed under record type. See attached csv downloaded from testing site for virtual museum data.

[fcba6158037b73a61033456bfb6360102ffbaf80b6be5f2e361deb68cf5f24cd.csv](https://github.com/kartoza/django-bims/files/11848483/fcba6158037b73a61033456bfb6360102ffbaf80b6be5f2e361deb68cf5f24cd.csv)

**Comment by dimasciput** [comment]
hi @jeremyshelton, it's because the data was overwritten from production again when you checked. Let me run the script in production

**Comment by dimasciput** [comment]
the production site has been updated, please test it there.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput 
Production looks good.
Closing ticket.
