### ISSUE TITLE
Adding data to a site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3132]
Once a site has been created, a user needs to add their data by selecting the relevant button here:

![image](https://user-images.githubusercontent.com/45286876/175509949-b8bae089-cf89-4bc9-bf37-397a2558530f.png)

**Comments thus far:**

- Some need to be removed: Add SASS data
- Singular/plural mixed up - can admin fix these somewhere and if so where? For e.g. should be Add Amphibian data not Add Amphibians data , etc.
- When I select Add Taxon - nothing comes up after I type 3 letters - how is this meant to work?  This should show the bird master list, etc for each biodiversity module
- Then I selected Add New Taxon, and selected from GBIF list
- after submitting I got an error message

![image](https://user-images.githubusercontent.com/45286876/175511485-eb4a9952-dfbd-447b-885a-d2d722e5d7bd.png)

**Comment by helendallas** [comment]
What is the basis for taxa being included at a new site: e.g Odonates

![image](https://user-images.githubusercontent.com/45286876/175513673-9bf57c1b-e646-48e4-a1db-3f00b387dafe.png)


Add Taxon is not working for - 
Macroinvertebrates
Birds

Others are working in that the names come up when I type 3 letters

**Comment by helendallas** [comment]
Also Add SASS should be hidden
![image](https://user-images.githubusercontent.com/45286876/175514815-eac0d11e-7634-49f6-97f7-47fe787c7f5c.png)

And probably also Add water temperature data
![image](https://user-images.githubusercontent.com/45286876/175514955-10c39745-48f2-4928-b3e5-99d0ffa80659.png)

Are we as admin able to select which ones to include. I can envisage this would be useful with rollout of other instances, so may be worth thinking about now

**Comment by dimasciput** [comment]
@helendallas 

- Some need to be removed: Add SASS data 

You can enable or disable SASS from adming page here : https://testing.rbis.kartoza.com/admin/bims/sitesetting/1/change/

- Singular/plural mixed up - can admin fix these somewhere and if so where? For e.g. should be Add Amphibian data not Add Amphibians data , etc.

Ok, I added singular name field, and admin can update it here : https://testing.rbis.kartoza.com/admin/bims/taxongroup/7/change/. If you provide a singular name, then the form will use that name instead.

- When I select Add Taxon - nothing comes up after I type 3 letters - how is this meant to work? This should show the bird master list, etc for each biodiversity module

I tested and it was working as intended. Please try again.

**Comment by dimasciput** [comment]
> What is the basis for taxa being included at a new site: e.g Odonates

@helendallas 

These are the closest recorded taxa within a 25 km radius.

**Comment by dimasciput** [comment]
@helendallas please give it a test in testing site

**Comment by helendallas** [comment]
@dimasciput I tried to Add Bird data but got an error message

![image](https://user-images.githubusercontent.com/45286876/183102684-8b4947f9-df8a-463d-8637-d0d2b86d278c.png)

Then tried fish and got to end but then
![image](https://user-images.githubusercontent.com/45286876/183103213-fc066640-6f3d-4940-8c4e-a10bef4c90cb.png)

Tried odonates
![image](https://user-images.githubusercontent.com/45286876/183103565-0a0a4113-5ead-44c7-b30c-e43934a59f96.png)

Tried Plants 
![image](https://user-images.githubusercontent.com/45286876/183103783-f8f86679-9131-42cc-8010-3c795fe2b07f.png)

Tried invertebrates - strange list plus 
![image](https://user-images.githubusercontent.com/45286876/183104095-af039326-474a-47ff-a8b8-eaccce77efa2.png)

Tried amphibians
![image](https://user-images.githubusercontent.com/45286876/183104355-e1389c41-058e-4146-91ed-f6866ac6f6db.png)

Tried reptiles
![image](https://user-images.githubusercontent.com/45286876/183104529-25464298-9b87-400e-917e-2c3aaf7c7ea1.png)

Tried mammals
![image](https://user-images.githubusercontent.com/45286876/183104735-ff34099d-9c38-4c74-8bc0-92d484966fbb.png)

Please can you check this coming week if you have time as I need this working to do the training.

Also what spatial unit determines if taxa are listed. catchment?

**Comment by helendallas** [comment]
Testing again now

Birds - working, add taxon is working with correct list

Fish - working, **add taxon is not working as fish master list taxa do not come down, e.g.** 
![image](https://user-images.githubusercontent.com/45286876/185898831-37ff1182-c18a-4d15-85c8-dda2f7a0759a.png)

Odonates - working, add taxon is working with correct list

Plants - working, add taxon is working with correct list

Invertebrates - working, but **add taxon is not working as fish master list taxa do not come down, e.g.** 

![image](https://user-images.githubusercontent.com/45286876/185899773-0eeeffc6-e49b-47fd-87af-fc989bc72e8a.png)

Amphibians - working, add taxon is working with correct list

Reptiles - working, add taxon is working with correct list

Mammals - working, add taxon is working with correct list

@dimasciput Please you check why the master list is not showing when I click Add Taxon for fish and invertebrates.

**Comment by dimasciput** [comment]
Hi @helendallas, I have fixed these issues on testing rbis

**Comment by helendallas** [comment]
Thanks so much @dimasciput - all working now, closing ticket
