### ISSUE TITLE
Revision needed to Add Site form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3158]
Please can you change the text below:

The following standard has been adopted for naming site code:
Catchment + Province ID + District ID + site count

![image](https://user-images.githubusercontent.com/45286876/183097484-7761589e-8af2-40b7-b324-cc9a963c49bf.png)

![image](https://user-images.githubusercontent.com/45286876/183097745-a166ce80-531a-40a2-9315-a5b22d9c4aa3.png)

Can you also please check the site code generator, it is not working correctly on RBIS testing -  this may be because the geocontext data doesnt work on RBIS testing????

**Comment by dimasciput** [comment]
@helendallas the site code generator is working in testing and live, I have checked them.

**Comment by dimasciput** [comment]
@helendallas I will update the description and fixed the existing site codes on the next sprint.

**Comment by helendallas** [comment]
Ok thanks @dimasciput When is the next RBIS sprint?

**Comment by helendallas** [comment]
Thanks, all working closing now
