### ISSUE TITLE
PLease check code for Common Name

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3159]
I thought the workflow for Common Name was also – use the one in the upload master list but if blank use the name on GBIF.

However all the Common Names are blank if they are blank in the upload file?

**Comment by dimasciput** [comment]
@helendallas I have updated the uploader so it will fetch common names from gbif if they are blank in upload file.

**Comment by helendallas** [comment]
Thanks @dimasciput Will this happen automatically or do we need to upload master lists again?

**Comment by helendallas** [comment]
This is working, closing ticket
