### ISSUE TITLE
Adding images to a taxon in Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3163]
At the moment, one either sees GBIF images (if they are available) or one can add an image for a taxon via Taxon Management

![image](https://user-images.githubusercontent.com/45286876/184873063-38bc84e1-6464-479e-9a30-cd9619701cbf.png)

Our admin team have requested the following change if possible:

- Keep all GBIF images that are available - and label that they are from GBIF
- Allow admin to upload taxon image (in addition), and then include an option to specify the Source of the image (e.g. a person's name or a website etc).

Then on the Taxon side panel and Taxon dashboard, all GBIF and other images will be shown, together with the **Source of Image** perhaps immediately below each image on the left hand bottom side

![image](https://user-images.githubusercontent.com/45286876/184873698-cac40060-4fdc-4446-b770-822b536651e5.png)

**Comment by dimasciput** [comment]
@helendallas updated in testing, also show correct attribution if the images are fetched from gbif.

**Comment by helendallas** [comment]
Thanks, working nicely. At this stage it is only admin who can add an image. Going forward it would be good to allow a user to upload an image themselves. This might also need validation. Lets leave as in for now and revisit.  Please deploy to production.
