### ISSUE TITLE
I get a server error when trying to download master list from Upload taxonomic data page

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3165]
I uploaded the revised Taxonomic upload template here:
![image](https://user-images.githubusercontent.com/45286876/184889105-871198aa-c4c9-46a5-b5a6-ac4c4b7fe14b.png)

As an excel file because it has several dropdown lists that need to be used, but it gives an error message when I download it.

https://freshwaterbiodiversity.org/download-taxa-template/?taxon_group=1

![image](https://user-images.githubusercontent.com/45286876/184888769-2ff17ce7-5e16-4512-8ee5-bb26ae1191de.png)

**Comment by dimasciput** [comment]
this should work now

**Comment by helendallas** [comment]
Thanks fixed, closing ticket
