### ISSUE TITLE
Sites and Site Overview Panels not in sync

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#3168]
For recently uploaded invert data - when I click on a Site, the associated overview panel that comes up is not for the same site.
![image](https://user-images.githubusercontent.com/55532903/185883889-1d4e0039-e511-4235-986d-45f1a79c18c4.png)

Works fine on testing.

@dimasciput

**Comment by helendallas** [comment]
@aneriswanepoel Is this still an issue - it seems fine on my side?
![image](https://user-images.githubusercontent.com/45286876/187373192-682fd840-56a9-4760-8318-fee504197f99.png)

**Comment by aneriswanepoel** [comment]
@helendallas it was only for the one invert study that I recently added - but yes looks like its working now.
