### ISSUE TITLE
We need to be able to validate a new species added by a user

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3169]
At the moment a user can **Add New Taxon** in the biodiversity data forms. This links to GBIF and the user selects the taxon.

![image](https://user-images.githubusercontent.com/45286876/185884248-efa73174-0dfd-490d-81b5-a0eeda011ac7.png)

![image](https://user-images.githubusercontent.com/45286876/185884481-98cdb3e0-3180-4e8b-bfe3-b95e08994e06.png)

However, the administrator needs to validate this species, before it is officially part of the system.  We need a workflow to do this.

**Comment by dimasciput** [comment]
There are few questions regarding this :
- If a user captures a site visit with an unvalidated species, can the admin validate the site visit without validating the species first?
- If the validator rejects the species, does that mean the site visit is also rejected?

@helendallas @jeremyshelton

**Comment by dimasciput** [comment]
Hi @helendallas , one more question, if the species got rejected, do you want to remove them from the system and the original collector need to add a different species. Or they can edit the species?
Currently we don't have a system for normal user to edit the taxa, so this make take more time to implement this feature.

**Comment by helendallas** [comment]
Thanks @dimasciput 

I don't think we need a system to allow the user to edit the taxon. 

If a user adds a taxon that is not on our master list, then the admin team should be notified. If we accept the new taxon, we will add it to our taxon management module, and the user's data will be accepted. 

If we reject the taxon, then the admin need to be able to give a reason which is then emailed to the user. We can include something like, if you wish to pursue this then contact us directly etc.

Make sense?

**Comment by dimasciput** [comment]
so if the taxon is rejected, they can do the following:
- add a new site visit with different species
- contact the admin to fix the taxon

@helendallas

**Comment by helendallas** [comment]
> so if the taxon is rejected, they can do the following:
> 
>     * add a new site visit with different species - assuming they added a bunch of taxa to a site visit, and only one taxon was rejected, then they can add the other taxa that are on our master list, but they are notified that the missing taxon is rejected, and we will provide a reason.
> 
>     * contact the admin to fix the taxon -  don't include anything this specified, just give us a reject option for the taxon and a space where we can give a reason.
> 
> 
> @helendallas

**Comment by helendallas** [comment]
Thanks @dimasciput this is working well. Please roll out to FBIS production

**Comment by helendallas** [comment]
Please can you change email message to say:

A new Taxon has been added - not Taxonomy

Otherwise it if fine

![image](https://user-images.githubusercontent.com/45286876/199478275-aaf3ded1-41e0-4ef8-ba17-d0f65670c283.png)


Also when I then search for the taxon the Taxon Dashboard side panel doesnt open

https://testing.healthyrivers.kartoza.com/map/#search/Listrodromus/taxon=&search=Listrodromus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=GENUS&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/199479001-8cab830d-fb0a-4dc0-a092-54a2231b28ed.png)

**Comment by helendallas** [comment]
Ok to leave as is, works fine, please deploy to FBIS, RBIS production

**Comment by helendallas** [comment]
@dimasciput This is not working on FBIS testing like it is on RBIS. I dont get the option to validate the taxon on the Validtae records..Please check and update on testing and production as per RBIS as it was working fine on that.

FBIS testing

![image](https://user-images.githubusercontent.com/45286876/202110174-f1e9e8d4-309e-4b42-a249-7ba3c61b8ae1.png)

RBIS testing

![image](https://user-images.githubusercontent.com/45286876/202110907-be7a3e13-e095-46d3-a88d-0efe4a5da8b3.png)

**Comment by helendallas** [comment]
Working well on FBIS production and testing, closing ticket
