### ISSUE TITLE
Source Reference -  unpublished data not updating in data capture forms

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3171]
I added several unpublished data sources as I was adding new data during testing on RBIS testing

![image](https://user-images.githubusercontent.com/45286876/185901599-af8f3fc5-b860-430b-a29a-33feb6e97d4b.png)

But they do not appear in the source reference dropdown. Please can you check, and also sort this list alphabetically

![image](https://user-images.githubusercontent.com/45286876/185901677-6c646e5e-28a4-4f2f-ad69-28e76cd8720b.png)

I also tested it on FBIS, but when I tried to add a new unpublished data, I got 
session is broken form

https://testing.healthyrivers.kartoza.com/source-reference-form/?session=54c9f81e-88f7-492a-bf9e-7a5e4fef0a43&identifier=fish-form

**Comment by dimasciput** [comment]
@helendallas this is now fixed in rbis testing.

**Comment by helendallas** [comment]
Thanks @dimasciput My source reference is now coming up. Is it possible to have the list sorted alphabetically?

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, please deploy to live

**Comment by helendallas** [comment]
Has this been deployed to live yet?
