### ISSUE TITLE
Location site - update site code not working for > 1 site at a time

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3172]
We need to be able to update the Site code in the Location Site table.

At the moment it only works if you select one site at a time. This will take ages.

Please can you see why it does not work for more -  either 100 at a time, or to be able to select all

![image](https://user-images.githubusercontent.com/45286876/185910002-27a1569a-d8af-4a78-8d3e-70dd1e785588.png)

https://rbis.ur.ac.rw/admin/bims/locationsite/?q=&o=2

This is also an issue in RBIS.

**Comment by dimasciput** [comment]
@Fanevanjanahary, I think it's better to run the task in the background if there are more than 10 sites.

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary Please can you prioritise this. Many sites that are already on FBIS do not have rivername or geomorphological zone. In addition to updating site code in bulk, we need to be able to update

![image](https://user-images.githubusercontent.com/45286876/192501550-84b9ad7a-cf61-4e72-9c5d-e0bd088e5580.png)

I don't think this is working correctly. please can you check.

**Comment by helendallas** [comment]
@Fanevanjanahary Please update me on where I can test this please

**Comment by Fanevanjanahary** [comment]
@helendallas this is fixed by #3205, waiting for @dimasciput to deploy it

**Comment by helendallas** [comment]
@dimasciput Please update me on this ticket?

**Comment by dimasciput** [comment]
@helendallas you can try it in live site

**Comment by dimasciput** [comment]
@helendallas 
> Works for 1 to 5, times out when I select 10

If you select more than 10 sites, they will be processed in the background automatically.

**Comment by helendallas** [comment]
Thanks, this seems to be working now. There are still some sites that don't have the correct code but that is because they are no where near a river? or out of SA

Closing ticket
