### ISSUE TITLE
FIx email for receiving CSV from Taxon MAnagement

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3174]
At the moment, it only send the csv from Taxon management to Dimas. 

Please check.

**Comment by dimasciput** [comment]
@Fanevanjanahary, fix the recipient when user click download csv in taxa management page https://rbis.ur.ac.rw/taxa-management/?&selected=6

**Comment by dimasciput** [comment]
@Fanevanjanahary any updates on this?

**Comment by Fanevanjanahary** [comment]
@dimasciput I've tested this and it sends an email to the logged user
