### ISSUE TITLE
Please add ability to merge sampling methods in Bims -Sampling methods table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3176]
The RBIS team have added occurrence data without using dropdowns, so now they have a whole lot of sampling methods that are the same but which are being recognised as difference because of missing capital or slight differences. See examples below.

Please can you make the functionality for us to select two or more sampling methods, which are then merged. (The same way as you have done for some of the other admin in BIMS).

![image](https://user-images.githubusercontent.com/45286876/187167769-4004b14f-5dd3-422b-a603-26e2afbebfb4.png)

This can also be rolled out to FBIS.

**Comment by helendallas** [comment]
@Fanevanjanahary @dimasciput Where has this been rolled out for testing?
RBIS testing or FBIS testing. Please always make a comment in this ticket rather than just put into review. I would iek to work through this today and some of the other tickets so please advise asap. thanks

**Comment by Fanevanjanahary** [comment]
@helendallas here please https://testing.healthyrivers.kartoza.com/admin/bims/samplingmethod/

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary This is working on FBIS testing. Please deploy to FBIS production and RBIS production.

**Comment by dimasciput** [comment]
deployed to production.
