### ISSUE TITLE
Sampling methods not being updated in the add data form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3177]
Example: Amphibians - I assigned several sampling methods to a Taxon Group

![image](https://user-images.githubusercontent.com/45286876/187168475-efff54f6-492e-409e-91ef-00074b40e071.png)

But even after hard refreshing, these are not showing in the add amphibian data form:

![image](https://user-images.githubusercontent.com/45286876/187168845-b37c91e4-747f-495b-be6c-57ead9c3e8f2.png)

It is not consistent though, as it is NOT working for 

- Birds
- Odonates
- Plants
- Amphibians
- Reptiles
- Mammals

It is working for 

- fish
- invertebrates

**Comment by dimasciput** [comment]
@Fanevanjanahary please add the size for this ticket

**Comment by helendallas** [comment]
@dimasciput @Fanevanjanahary  Is this RBIS testing? or FBIS testing or live???

**Comment by Fanevanjanahary** [comment]
@helendallas this is on FBIS testing

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary This is working now on FBIS testing. Please can you also make sure the list is sorted alphabetically (this should be standard for all dropdown forms).  Please deploy to FBIS live and RBIS live.

![image](https://user-images.githubusercontent.com/45286876/192985609-a3e653d2-224e-4ac5-b447-d59d97d0b8ed.png)

**Comment by dimasciput** [comment]
deployed to production and testing.
