### ISSUE TITLE
Investigate missing records - URGENT

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3179]
We noticed a large amount of study references no longer have any records associated with them.

for example:
![image](https://user-images.githubusercontent.com/45286876/187376028-7fd1ed84-28a2-4fa0-85a7-c275d71107c5.png)

**These include:**

- Unpublished data: 13 source references (1 fish; unsure about the rest)
- Databases: 1 source references (1 fish)
- Published reports/theses: roughly 90 source references (mostly fish; 9 inverts)
- Scientific papers: 230 source references (mostly fish; 1 inverts)

**Comment by dimasciput** [comment]
I'm going to close this, since this has been resolved.
