### ISSUE TITLE
Validate Site does not work as it should - RBIS budget

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3181]
The system in FBIS, RBIS and ORBIS for validating a site is still problematic. I have created tickets about this previously, but to date it has not been satisfactorily resolved.

As administrators we need to be able to view and validate a site that a user has added to the platform. 

The site validation should not apply to sites from GBIF or Virtual Museum sites, as these are impossible to validate. It should also not apply to sites uploaded by administrators using the Upload Occurrence data template.

It should ONLY apply to site created by the user.

This is the Validate Site form at the moment
![image](https://user-images.githubusercontent.com/45286876/187878216-54b31e19-aece-4103-bc21-c093e559074e.png)

It has all records, and there is no way to select Unvalidated Sites.

Please can you make the Validate Site for like the Validate record form, where we can select Unvalidated Sites, and apply the same filters including Owner, Site Code, Source Collection, Module. 

The column headers should be Site code, site description, Source collection, Owner.

![image](https://user-images.githubusercontent.com/45286876/187878505-4e66fdcd-305f-4f54-8f62-794e0ccbe668.png)

Please can we discuss this if my request is impossible. We need this resolved please. Also can you use RBIS budget for this task.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 
This is actually more complicated than the species validation, what do you think if we just remove site validation?
So we keep it simple by just validating the site visit, if there is no visit on the site then the site will be automatically deleted.
Or do we really need to validate the site?

**Comment by helendallas** [comment]
If it is too complicated then I am okay with leaving it out. 

BUT the admin people must be able to go to the site to check it  has been added correctly. Can this be done from the Validate records form?  Is it possible to be able to click the site code on the Validate Records, which then opens up the Site in a separate tab?

![image](https://user-images.githubusercontent.com/45286876/194027356-e2c1d862-900d-48cc-b508-854dd7cf2186.png)

@jeremyshelton ?

**Comment by helendallas** [comment]
Discussed this and the issues/problems around it. Decision taken to remove site from the validation workflow.
@dimasciput Please remove Validate Sites on RBIS and FBIS menu bars
