### ISSUE TITLE
Please check that all aspects of FBIS get mirrored to testing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3182]
At the moment, validation does not get mirrored to testing. The are also some issues with Site settings.

Please can you check that all is mirrored. This is very NB as we are going into a training phase now.

**Comment by helendallas** [comment]
@dimasciput Not fixed. The site setting on Production is different from testing

https://freshwaterbiodiversity.org/admin/bims/sitesetting/1/change/

![image](https://user-images.githubusercontent.com/45286876/218448818-540907f7-be98-4e17-afda-f9ade8aed4f4.png)



https://testing.healthyrivers.kartoza.com/admin/bims/sitesetting/1/change/

![image](https://user-images.githubusercontent.com/45286876/218448518-c16a025f-3b46-4454-84ed-d028ba7c128e.png)


and there is an inbetween step
![image](https://user-images.githubusercontent.com/45286876/218448355-8056a749-ec87-4052-b820-a2bdf728cbc9.png)

**Comment by dimasciput** [comment]
I have fixed the issue and re-enabled the mirrorring script.

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good now, closing ticket
