### ISSUE TITLE
Fetch river name and fetch geomorpholigical zone still not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3184]
Please urgently fix this on live and testing. The Fetch river name is not working
The Fetch data for geomorphological zone is not owrking.

@Fanevanjanahary Any progress on this. I understand @dimasciput asked you to try and fix it.

**Comment by Fanevanjanahary** [comment]
@helendallas this is an issue from geocontext, I already fixed it. I will deploy today.

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary PLease let me know when it has been deployed. In fact please alswasy note in the ticket when something has been fixed as otherwise we dont know????

**Comment by Fanevanjanahary** [comment]
@helendallas please can you check if it works now?

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary Is this on production?

**Comment by Fanevanjanahary** [comment]
@helendallas yes please

**Comment by helendallas** [comment]
The fetche river name seems to work but not always the zone.  Also have you manage to fix the bulk upload in the backend.

https://github.com/kartoza/django-bims/issues/3172

It takes a long time to do each site individually in the front end. It would be better to be able to select all and let it run in the backend.

@dimasciput

**Comment by Fanevanjanahary** [comment]
Thanks @helendallas I'm working on #3172 today

**Comment by dimasciput** [comment]
@helendallas can we close this one?
