### ISSUE TITLE
Bims/Admin/Biotopes - this does not update on the data capture forms and needs sorting

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3185]
At the moment there are several biotopes (broad, specific and substratum) that are incorrect or duplicated in the Biotopes table.

We need to be able to edit and or merge. Issue raised with RBIS as well.

see example here
![image](https://user-images.githubusercontent.com/45286876/188144514-a53930eb-668b-4695-a12f-7a72ff39b18a.png)

There also appear some that are a legacy of SASS or which are used for SASS...not sure which is the case.

![image](https://user-images.githubusercontent.com/45286876/188144868-9af877ae-f522-476d-9460-ffde17d6ef8a.png)

**Comment by helendallas** [comment]
Also this is in the data capture form but is not in the biotopes, 

Not specified and Unspecified are the same and Unspecified is correct -  only in forms not in biotope table so not sure where this is coming from.

**Comment by dimasciput** [comment]
@helendallas I have deployed the fix to testing. You can also see which biotopes are used in SASS.

**Comment by helendallas** [comment]
Thanks @dimasciput  This is an improvement.

So where a biotope is not associated with SASS or a Taxon Group, and does not have a display order, biotope form number  -can these be deleted?

e.g.
![image](https://user-images.githubusercontent.com/45286876/192257060-15b29406-961e-49a3-8275-3038efdc7015.png)

![image](https://user-images.githubusercontent.com/45286876/192257117-2d6e2499-ee5d-4d90-b21c-08929439501e.png)

![image](https://user-images.githubusercontent.com/45286876/192257232-2094a23d-2c24-4fc6-8108-52b8f9e4d357.png)


See here where Slackwater is shown
![image](https://user-images.githubusercontent.com/45286876/192257543-746f9803-436d-4de9-a48b-4e63034d74d9.png)

I assume the one with the Taxon Groups shown and display order is correct, while the other is a legacy name and can be deleted?

**Comment by helendallas** [comment]
Sorry @dimasciput Can you please respond to this and I want to fix today if possible.

So where a biotope is not associated with SASS or a Taxon Group, and does not have a display order, biotope form number -can these be deleted?

**Comment by helendallas** [comment]
I assume I will get a warning if there are biological records associated with it, in which case I then merge with the most appropriate

**Comment by dimasciput** [comment]
@helendallas yes you will get a warning if the biotope is associated with a record.

**Comment by dimasciput** [comment]
@helendallas also careful not to delete the biotope that used in SASS form.

**Comment by helendallas** [comment]
Great thanks. Yes I will make sure not to delete SASS biotopes. I have run a few checks in Testing, and seems to be working great.

**Comment by helendallas** [comment]
I have edited on live , merged and fixed. Closing ticket
