### ISSUE TITLE
Province is not showing in dashboards

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3188]
Please can you check why Province is not showing in the dashboard on production or live. I think it got broken when you changed province to include neighbouring countries

![image](https://user-images.githubusercontent.com/45286876/188371345-1a3d81d9-9fc3-48a9-9fb6-092100c47b97.png)

**Comment by helendallas** [comment]
@Fanevanjanahary Please can you also check this - geocontext issue, thanks

**Comment by dimasciput** [comment]
@helendallas please test on testing site

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary Workign on testing but please adjust spacing on SASS dashboard if possible, the roll out to live soonest please @dimasciput 

![image](https://user-images.githubusercontent.com/45286876/191442666-6787991c-497b-457f-a4d8-759c3ba53e12.png)
