### ISSUE TITLE
Improve the multi site overview request

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3196]
Currently requests for multi site review are quite slow and sometimes cause server timeouts.
We should be able to fix this by processing requests in the background.

**Comment by dimasciput** [comment]
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20X%22,%22value,primary_catchment_area,Region%20A%22,%22value,primary_catchment_area,Region%20B%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by dimasciput** [comment]
Hi @helendallas @jeremyshelton, I have deployed some improvements regarding this issue to testing. Will you give it a test please?

**Comment by helendallas** [comment]
Thanks @dimasciput Definately quicker now, please deploy to live when you can

**Comment by jeremyshelton** [comment]
Also quicker for me.
Thanks @dimasciput
