### ISSUE TITLE
None of the sites are giving the biodiversity data

### ISSUE THREAD

**Issue by FBIS-issues** [kartoza/django-bims#3199]
none of the sites are giving the biodiversity data

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/4156">User information </a>
Browser: Chrome
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/#search/Dorpsriver/taxon=&search=Dorpsriver&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=37367&dst=
Screen resolution: 1366 x 768

**Comment by dimasciput** [comment]
The river name is wrong, should be DORPSRIVIER. And if user want to search river name, they should take advantage of autocomplete feature.
