### ISSUE TITLE
Print map error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3203]
@dimasciput FBIS live site is returning an error when I hit print map o the side bar.
<img width="1156" alt="Screenshot 2022-09-21 at 09 33 39" src="https://user-images.githubusercontent.com/44292029/191443270-ab08c7a3-0959-4ae5-90c8-c3dca3f9be5a.png">
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton can you try it on chrome? What browser did you use? It was working fine for me with chrome.

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton Print map is working now for me. I use Firefox

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas yeah it's working on chrome, but not safari (but I'm fairly certain it did in the past)

**Comment by dimasciput** [comment]
@jeremyshelton this is fixed on testing.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
This is working fine my end & can be delayed to live site 👍

**Comment by jeremyshelton** [comment]
@dimasciput also linked to the map view - can you please adjust the position of the scale bar so that it is not so close to  the bottom of the screen? Thanks
<img width="889" alt="Screenshot 2022-10-07 at 06 53 35" src="https://user-images.githubusercontent.com/44292029/194470601-e56f83b7-0cb2-461b-a15f-62d69a289223.png">
@helendallas
