### ISSUE TITLE
Create a jpg from print map

### ISSUE THREAD

**Issue by FBIS-issues** [kartoza/django-bims#3204]
It would be useful to create a jpg file from the print map option

---

User : <a href="http://freshwaterbiodiversity.org/admin/people/profile/478">User information </a>
Browser: Firefox
Device: Desktop
Referrer: https://freshwaterbiodiversity.org/map/
Screen resolution: 1696 x 954

**Comment by helendallas** [comment]
This request came from a participant at our recent FBIS training session. In addition to being able to print the map as a pdf, they wanted to be able to save the map as a jpg, and possibly other formats as well.

**Comment by dimasciput** [comment]
this is deployed to production and testing.

**Comment by helendallas** [comment]
Works great @dimasciput Thanks, closing ticket
