### ISSUE TITLE
Dashboard - Taxa incorrect

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3206]
All the bar charts in single and multi site dashboards should have the same shape, and then be colour coded based on Origin, Taxa etc.  But the Taxa graph is showing a different pattern. I have checked several sites.  

![image](https://user-images.githubusercontent.com/45286876/192510139-76db7f43-992b-41f6-b4c4-30b7b1c6178f.png)

and another example, invertebrates

![image](https://user-images.githubusercontent.com/45286876/192510609-ae27d371-9336-437a-bf4a-3fe275b2691b.png)

**Comment by helendallas** [comment]
and another
![image](https://user-images.githubusercontent.com/45286876/192511148-36077dce-99eb-400e-988d-6e8c7fa8d8f7.png)

**Comment by helendallas** [comment]
Duplicate ticket in #3212

**Comment by dimasciput** [comment]
Deployed to testing and live site.

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good
