### ISSUE TITLE
Why are there two Unknown categories for origin and Not evaluated for conservation status

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3207]
Please check why there are two unknown categories for origin......there should only be one? How can this be fixed?

![image](https://user-images.githubusercontent.com/45286876/192511603-8ba529ce-4b6e-4fb8-90f5-a35ceb900834.png)

**Comment by helendallas** [comment]
Here are some more examples: origin, also for conservation status - two "not evaluated"
Any chance you can check monday and fix on live as I need dashboards for report
![image](https://user-images.githubusercontent.com/45286876/193458870-812a8d02-3d4e-4d45-adf9-f0d544ffe4e1.png)

![image](https://user-images.githubusercontent.com/45286876/193458908-e61b34a2-b5c1-43f3-804c-58f790e84ec2.png)

**Comment by dimasciput** [comment]
@helendallas can you share the link please? Or what species were you looking for?

**Comment by helendallas** [comment]
Sorry I was out the office. This was for all algae but it is a very broad issue. Not sure why?

Its not easy to find out which taxon my be responsible for this

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by dimasciput** [comment]
deployed to live

**Comment by helendallas** [comment]
Thanks @dimasciput
