### ISSUE TITLE
CSV Downloads - Remove FRC approval?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3210]
@dimasciput

Can we please remove the need for FRC staff to approve a download request.
We still want to keep a log of who downloads what, and when?
We also still want the pop-up to appear that informs the user that there request has been submitted and that it will appear in their email inbox when ready.

@timlinux @helendallas

**Comment by helendallas** [comment]
So @jeremyshelton We do this but uncheck the box in Site Settings. Its easy.

But the issue @dimasciput is when we uncheck this box, the notification to the user disappears.   The user still needs to get the notification please.

**Comment by jeremyshelton** [comment]
@helendallas agreed.

**Comment by Fanevanjanahary** [comment]
@jeremyshelton @helendallas, here is a test I've done. I unchecked  **Enable download request approval** in site settings.

The pop-up:
![Peek 2022-11-22 00-42](https://user-images.githubusercontent.com/12623986/203164094-a13d3a7d-718b-48a9-80da-edaf2c940113.gif)


In the download request:
![image](https://user-images.githubusercontent.com/12623986/203160867-9c8a4247-862c-4ae4-bb73-da50e6aabdd4.png)

The notification mail:
```
Subject: [freshwaterbiodiversity.org] CSV created email notification
From: admin@kartoza.com
To: faneva@kartoza.com
Date: Mon, 21 Nov 2022 21:21:30 -0000
Message-ID: <166906569027.25.4888932203721199044@dev>

--===============6495438286862300388==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit


You have received the following notice from freshwaterbiodiversity.org:


<p>
    Your requested csv file has been compiled and is now ready, please find the attached file.
</p>

--===============6495438286862300388==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="OccurrenceData.zip"
```
