### ISSUE TITLE
Basemaps in dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3211]
@dimasciput how difficult would it be to change baseman's in all dashboards to Bing Satellite?

**Comment by dimasciput** [comment]
@jeremyshelton it's not difficult, but might take some time to update all of them.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput 
Not a top priority, but will be good to do at some point.

**Comment by dimasciput** [comment]
@jeremyshelton deployed in testing

**Comment by helendallas** [comment]
Thanks @dimasciput 

Looks good but please still do for 

- water temperature dashboard
- Physico-chemistry dashboard

**Comment by jeremyshelton** [comment]
Agreed @helendallas 
Thanks @dimasciput

**Comment by helendallas** [comment]
Please also make sure that this is the default basemap for all future dashboards such as pesticides etc.

**Comment by dimasciput** [comment]
The issue has been resolved on the testing site.

**Comment by jeremyshelton** [comment]
@dimasciput the maps in the temperature and physics-chem dashboards differ, but they should be consistent. Physico-chem has no coordinates, grid lines or scale bar. The water temperature format is correct. 
<img width="1173" alt="Screenshot 2023-03-21 at 06 10 00" src="https://user-images.githubusercontent.com/44292029/226516982-236381b1-240c-4bea-8e58-a30850664cdc.png">
<img width="1124" alt="Screenshot 2023-03-21 at 06 19 21" src="https://user-images.githubusercontent.com/44292029/226517010-ebc62d60-6cc1-4f7f-b57a-ac23c2b9d65f.png">

@helendallas

**Comment by jeremyshelton** [comment]
@dimasciput any update on this ticket?

**Comment by dimasciput** [comment]
@jeremyshelton this is fixed in testing

**Comment by jeremyshelton** [comment]
Looks good.
Thanks @dimasciput 
Please deploy to production.

**Comment by dimasciput** [comment]
This has been deployed to production, closing it now.
