### ISSUE TITLE
Multi-site dashboard chart error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3212]
@dimasciput the occurrence data totals should be the same among all charts, but they not. 

![Screenshot 2022-09-28 at 12 56 37](https://user-images.githubusercontent.com/44292029/192763033-1bc38d83-815c-4f52-826c-463c4922b1d7.png)

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[18.4735107421875,-33.17447681421247],[19.4073486328125,-33.9617203252858],[19.4073486328125,-33.15608359237714],[18.4735107421875,-33.17447681421247]]&thermalModule=&dst=

@helendallas

**Comment by dimasciput** [comment]
I'm closing this one, since this is a same issue with https://github.com/kartoza/django-bims/issues/3206
