### ISSUE TITLE
Taxon common name inconsistencies

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3213]
Common name for _Pseudobarbus burgi_ in taxon management differs from that in taxon dashboard.
The taxon dashboard is incorrect (river should be River). Is there a way to easily correct this?

![Screenshot 2022-09-28 at 12 52 07](https://user-images.githubusercontent.com/44292029/192763832-5c24825d-a2b5-446d-aff7-68c0ffdc7596.png)
![Screenshot 2022-09-28 at 12 52 41](https://user-images.githubusercontent.com/44292029/192763848-2be84758-6b65-49f7-9550-90b17ffe6652.png)

**Comment by dimasciput** [comment]
Deployed to testing and live site.

**Comment by helendallas** [comment]
@jeremyshelton Is this corrected? If so please close the ticket
