### ISSUE TITLE
Please add option to merge endemism categories

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3227]
The RBIS team regularly upload slight variations of the endemism categories, and there is currently no way to merge them, or to see data associated with each category.

Please can you add option to Merge endemism categories in the same way that we can merge sampling methods.

**Comment by dimasciput** [comment]
@helendallas added in fbis testing site.

**Comment by helendallas** [comment]
Thanks working fine, please deploy to production

**Comment by dimasciput** [comment]
Deployed to live
