### ISSUE TITLE
Editable list of user sites and records

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3232]
Show list of user sites and records that are not synced yet. 
If it's already synced, they can only edit the data from the site. 

From https://github.com/kartoza/django-bims/issues/3175

@jeremyshelton

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas sorry, I haven't implemented this yet for this sprint. I will need 2-3 days to add this feature.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput - let us know when you are ready 👍
