### ISSUE TITLE
Revision to SASS form needed

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3233]
Please remove TRICHOPTERA (CASE CADDIS 2 TYPES)  from the bottom of the SASS form, it is from SASS Version 4. Please note that when SASS4 calculations are done then all the SASS4 taxa are valid, but they should not be included in SASS5 form

![image](https://user-images.githubusercontent.com/45286876/194290743-7b08ce3d-dd69-4327-9b76-d0eef0dfde87.png)

**Comment by dimasciput** [comment]
please check on production

**Comment by helendallas** [comment]
Closing ticket as working well now
