### ISSUE TITLE
Incorrect metadata showing in taxon dashboard?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3234]
Clean Stream Biological Services Database is showing up in the metadata list for the Pseudobarbus phlegethon taxon dashboard - however Clean Stream do not have any data in the Western Cape Province - the area where P. Phlegethon occurs.

Clean Stream Biological Services Database: https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22892%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

Pseudobarbus phlegethon: https://freshwaterbiodiversity.org/map/#search/Pseudobarbus%20phlegethon/taxon=&search=Pseudobarbus%20phlegethon&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

@dimasciput any ideas about why this metadata is showing?

@helendallas

**Comment by helendallas** [comment]
Hi searched again on Clean stream and this seems to have been resolved. Closing ticket
