### ISSUE TITLE
CVS download on taxon dashboard not working?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3235]
@dimasciput I've tried the CSV download on the taxon dashboard on both testing and production and I'm not getting any emails with download links and it's not in the download queue on either site.

https://freshwaterbiodiversity.org/map/#search/Pseudobarbus%20phlegethon/taxon=&search=Pseudobarbus%20phlegethon&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=
<img width="1663" alt="Screenshot 2022-10-07 at 19 26 47" src="https://user-images.githubusercontent.com/44292029/194615649-5d3a96b8-c592-48cf-94f6-446e8d615aa0.png">

**Comment by dimasciput** [comment]
deployed to testing and prod

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
This is working fine now. 
Closing ticket.
