### ISSUE TITLE
Dashboard images distorted?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3236]
@dimasciput is it possible to maintain the correct proportions of images shown in the taxon dashboards?
I understand that they are being stretched so that the fill the space nicely, but it is important that we maintain the native aspect ratio for these images so that the taxa are shown accurately. Is there perhaps another way to display the images that achieves this, without wasting space?

Distorted images on taxon dashboard: https://freshwaterbiodiversity.org/map/#species-detail/taxon=222&search=Labeo%20seeberi&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

Correctly-proportioned images on iNaturalist: https://www.inaturalist.org/taxa/103819-Labeo-seeberi/browse_photos

**Comment by helendallas** [comment]
Also another suggestion is to make the space for the images smaller and the space for the occurrence graph larger

**Comment by dimasciput** [comment]
This has been deployed to testing and production.
