### ISSUE TITLE
Common name not being pulled down from GBIF correctly

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3244]
The work flow for common name is, first use the one uploaded in the master list, then if this is blank, use the name provided in GBIF.

However for the example below, a whole bunch of names are returned
![image](https://user-images.githubusercontent.com/45286876/199205472-f80d6ea9-bfe7-4575-b689-e3632851153c.png)

However, we should only show the one displayed on the GBIF page below
![image](https://user-images.githubusercontent.com/45286876/199205569-5da5cb6c-8622-4d30-9f83-128517e75e43.png)

https://www.gbif.org/species/2651706

Please can you figure out how to only get the name shown above on the url. 

Here is another example:

![image](https://user-images.githubusercontent.com/45286876/199205841-7baba397-fd99-4fd3-a140-9d4cfe42990e.png)

a synonym
![image](https://user-images.githubusercontent.com/45286876/199205936-010528cd-b0c1-4e13-94c8-4e99229b2df2.png)

of this species so should just be Common medicineplant
![image](https://user-images.githubusercontent.com/45286876/199205985-1fea56fb-aab2-4892-a393-6b3b38282851.png)

**Comment by Fanevanjanahary** [comment]
Hi @dimasciput,
We need vernacular_names in which the language is EN. But for some taxon there are no, vernacular_names, or the EN is missing. Is it Ok if we fetch it from gbif API?

**Comment by Fanevanjanahary** [comment]
@helendallas in this version, we get all of vernacular_names, so that is why **Golden leatherfern** is not the only one shown. We changed it to get only vernacular names in which the language is English, like here https://www.gbif.org/species/2651706

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary 

So to update to only showing English names, do we need to reharvest GBIF data?  or can you get the names all updated in the backend?

@dimasciput ?

**Comment by dimasciput** [comment]
@helendallas Faneva has made some fixes but I haven't deployed it yet to any servers. Let me deploy it to testing today.

**Comment by helendallas** [comment]
All common names have now disappeared on testing including those that were uploaded in the master list. and some species have also disappeared on testing???
PLants Acrostichum aureum

**Comment by dimasciput** [comment]
@helendallas it's on the system, just not showing up in taxa management page, I think it's a bug.

**Comment by helendallas** [comment]
Can you fix it?

**Comment by helendallas** [comment]
there are many examples, where taxa are in the taxa table but dont pull through to taxon management. This is a real issue when we try to upload data as it bombs and comes as an error.

https://testing.healthyrivers.kartoza.com/admin/bims/taxonomy/?q=Pyralidae

I just had an issue with this one now.

**Comment by dimasciput** [comment]
@helendallas sure, it should be an easy fix, but I can only do it next week

**Comment by helendallas** [comment]
@dimasciput PLEASE can you action this asap

**Comment by dimasciput** [comment]
@helendallas hi, will fix this today.

**Comment by helendallas** [comment]
Thanks Fixed, closing ticket
