### ISSUE TITLE
Conservation status global and national

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3254]
**Conservation status global** and **Conservation status national** need to be separate tables as the categories are different and national only applied to south Africa

For e.g. plants have been added and the national categories are now used in side panel dashboard which is incorrect.
![image](https://user-images.githubusercontent.com/45286876/202382995-79dc803d-c240-4e50-9ca1-6a965e00ec4c.png)

One table  IUCN Status is provided, but this is no longer correct as the national categories have been added
![image](https://user-images.githubusercontent.com/45286876/202383544-8e045827-90be-440b-9cf0-e740420f17ad.png)

Please separate tables or make some functonality that we can draw on IUCN categories for global, and a different set for national.

Please make  conservation status in side panel/overview dashboard should be global,
Then in  detailed dashboard please add an extra pie chart to show Conservation Status National, where it is  e.g. for plants. National will not always be available.

**Comment by dimasciput** [comment]
@Fanevanjanahary add a boolean flag in the iucn, to indicate if iucn is global or not.

**Comment by dimasciput** [comment]
@helendallas you can now go to the admin page, and tick which status is national only.
![image](https://user-images.githubusercontent.com/1979569/204185384-5bcdda17-7087-46a7-b360-e4455dc35fd5.png)
https://testing.healthyrivers.kartoza.com/admin/bims/iucnstatus/

**Comment by helendallas** [comment]
Thanks, closing ticket.
