### ISSUE TITLE
We need to rename DFFE Screening Tool 2022 to DFFE Screening Tool Fish 2022

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3255]
@jeremyshelton At the moment the DST specifies:

DFFE Screening Tool 2022

But it is only for fish, so should we rename:

DFFE Screening Tool Fish 2022

@dimasciput We may need functionality for managing the names of the Decision Support Tools in FBIS going forward.

**Comment by dimasciput** [comment]
I will add the functionality for managing the names

**Comment by dimasciput** [comment]
We can now update the name here : 

https://testing.healthyrivers.kartoza.com/admin/bims/decisionsupporttoolname/

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Looks good. 
Can you deploy this to the live site as well?

@helendallas
