### ISSUE TITLE
Update download request workflow

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3262]
- [x] Send admins notification when the download request is added not when it's finished
- [x] Show the progress in the download request page
- [x] Admin can reject the ongoing download request and it automatically cancels the process

**Comment by dimasciput** [comment]
@Fanevanjanahary this is a pretty big ticket, please let me know if you have any questions. We can chat about this tomorrow if you want.

**Comment by dimasciput** [comment]
@helendallas updated in testing

**Comment by helendallas** [comment]
Checked

Email received as download was initiated.

BUT
I did the download on the testing site and then received an email showing link to production site. I then navigated to download page on testing.

On testing
Seems to show in Download request page for csv files, but not for graphs.....just shows as pending
![image](https://user-images.githubusercontent.com/45286876/218456142-371f8fa0-4f65-4b41-bc45-8134f1d3abb5.png)

No email sent to use when the download request was canceled.

**Comment by dimasciput** [comment]
@helendallas please can you test this again on production

**Comment by helendallas** [comment]
Emailed received
Link is now on testing but approve not working
https://testing.healthyrivers.kartoza.com/download-request/?approved_or_rejected=approved&requester=

Just shows as approved
![image](https://user-images.githubusercontent.com/45286876/228765949-190aee73-e820-47cc-89df-b856550fc470.png)

**Comment by dimasciput** [comment]
@helendallas it will be automatically approved if you disabled download request approval in the site setting. 
![image](https://user-images.githubusercontent.com/1979569/228769372-2df16d20-7ebd-4354-9b89-233c5e0b153c.png)

**Comment by helendallas** [comment]
Ok I activated download request in site setting, and received email but request is still not visible in the page

![image](https://user-images.githubusercontent.com/45286876/228775245-cd463c98-ec8c-4f20-9400-8c25529b3dee.png)

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/228778760-f73537c9-8b3d-4e98-9d53-e1d9b71b6878.png)

I can see my download request here. 
Can you try it again with different search?

**Comment by dimasciput** [comment]
@helendallas I probably still need to show the progress even though they have been approved. Let me update that.

**Comment by helendallas** [comment]
Agreed, it shows as pending for quite a long time, and would be good to see progress regardless of whether it has been approved or not especially for large request.

Thanks

**Comment by dimasciput** [comment]
It's also because the system can currently only process one request at a time. Therefore, the download request is pending because the system is still finishing the previous one.

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/228802193-bbddcc9a-4d5f-4139-8dcb-e06f83b9496d.png)

You should be able to see the progress now in approved section.

**Comment by dimasciput** [comment]
this has been deployed to production too

**Comment by helendallas** [comment]
Thanks @dimasciput Closiing ticket this is working well.
