### ISSUE TITLE
Inconsistent site display on map?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3264]
@dimasciput when I look at the map for this area (all data sources and modules turned on) I only see a small number of sites. 
<img width="1321" alt="Screenshot 2022-11-24 at 10 02 31" src="https://user-images.githubusercontent.com/44292029/203727407-1448e15b-8b58-4de1-9561-1184bb1feb3c.png">

However, then when I lasso the area I see many more sites. 
![Uploading Screenshot 2022-11-24 at 09.48.48.png…]()

Any idea why that might be?

Here is a link to the area.

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton please give it another try, I refreshed the map view in the backend.

**Comment by jeremyshelton** [comment]
@dimasciput - OK that fixes the problem. 
Thank you.
Closing ticket.
