### ISSUE TITLE
Functionality to prevent pulling FBIS data back down from GBIF

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3274]
@timlinux @dimasciput 

We are currently in the process of uploading the first tranche of fish data to GBIF. 
This first upload will be done 'manually', and we are registering FRC as a contributor etc. 
We would like to automate in the future as per ticket #3214 

This ticket is a request for functionality to prevent ant FBIS data that are uploaded to GBIF from being pulled back down to FBIS when we harvest GBIF data. i.e. to prevent duplication. 

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton have you managed to push the data to gbif? Can you share  the data.

**Comment by jeremyshelton** [comment]
Yes, the FBIS fish data have been pushed to GBIF.
Here is the link: https://www.gbif.org/dataset/3ea542dc-885d-4c8a-91a3-64d0a5d78301

**Comment by dimasciput** [comment]
Thanks, I will update the script to pull gbif data.

**Comment by jeremyshelton** [comment]
@dimasciput I see that this ticked has been moved to 'For review FRC'
So does this mean you have created and deployed the script? 
To testing and/or production sites?

Can I test this by doing a new fish data harvest from GBIF?

@helendallas

**Comment by jeremyshelton** [comment]
@dimasciput please provide an update on this as per my previous comment.
Thanks

**Comment by helendallas** [comment]
@dimasciput Please revert re this ticket at the start of the next sprint. thanks

**Comment by jeremyshelton** [comment]
@dimasciput please give us the green light when you are ready for us to test this.

**Comment by dimasciput** [comment]
@jeremyshelton, this is ready for testing. Perhaps in testing site, you could create a new taxon group model that includes FBIS species. Then, simply harvest GBIF records for that taxon group and see if you obtain the occurrence record from FBIS

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I will test this afternoon and revert.

**Comment by jeremyshelton** [comment]
@dimasciput I created a new module (called GBIF TEST) with a few fish taxa on the testing site and harvested data for those taxa on GBIF. Taxon management shows that the taxa and records are in the module. However, when I search on this new module via the map the search result returns 0 sites and 0 taxa. Am I doing something wrong?

<img width="513" alt="Screenshot 2023-10-26 at 07 05 33" src="https://github.com/kartoza/django-bims/assets/44292029/d822da70-3ca0-42a3-bcbb-20321eae17b5">
<img width="829" alt="Screenshot 2023-10-26 at 07 26 31" src="https://github.com/kartoza/django-bims/assets/44292029/1ababff2-2e20-480b-a50f-d383a742fd9d">

**Comment by dimasciput** [comment]
Will check this after the mobile app updates.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput

**Comment by helendallas** [comment]
Also @jeremyshelton There is a delay on testing with data cache so not all sites show up immediately

**Comment by jeremyshelton** [comment]
@helendallas copy that

**Comment by helendallas** [comment]
IF you look in the back end table you can see the records have been harvested. But they are not yet showing on the front end due to the delay.

https://testing.healthyrivers.kartoza.com/admin/bims/biologicalcollectionrecord/

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton There is actually another issue. Occurrences that have already been harvested belong to a different group, e.g., Fish. Should we change the taxon group when they are re-harvested under a different group?

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput 
Can we do a quick call to discuss?
It is important that we get this right.

**Comment by jeremyshelton** [comment]
> @jeremyshelton IF you look in the back end table you can see the records have been harvested. But they are not yet showing on the front end due to the delay.
> 
> https://testing.healthyrivers.kartoza.com/admin/bims/biologicalcollectionrecord/

Helen this link is not working - but I will check the back end.

**Comment by dimasciput** [comment]
@jeremyshelton sorry the site is down at the moment, I'm deploying some updates

**Comment by jeremyshelton** [comment]
@dimasciput I have requested a .csv file from the testing site, but I have not received an email with download link. 
Also I don't see it in on the downloads request page either. 
Do you know if the csv download workflow from testing site is working correctly?

**Comment by jeremyshelton** [comment]
Hi @dimasciput the new module I created on testing site is now up and running.
I harvested GBIF data for the four species ("FBIS species" - ie ones that pre-exist in FBIS) included in the new module. 
The harvest returned "non-FBIS data only" - so it looks like this functionality is working from what I can tell ✅

**Details of my testing FYI**
I attach the csv download for the new module that I created on testing: you will se that for Pseudobarbus burgi (a pre-existing FBIS species) that the GBIF harvest returned 54 occurrences, and that in no cases was the source FBIS. Then, if I look at P. burg on production, there are 213 records, of which 45 are GBIF records and the other 168 are FBIS records (ie ones that have been pushed to GBIF, and correctly did not get pulled down when I did the harvest from the new module I created on the testing site). Note the number of GBIF P. burgi records in the testing site is higher than on the production probably because 9 new records have been added to GBID since out last harvest on production. 

[Production.xlsx](https://github.com/kartoza/django-bims/files/13184633/Production.xlsx)
[testing.xlsx](https://github.com/kartoza/django-bims/files/13184635/testing.xlsx)

**Comment by jeremyshelton** [comment]
> @helendallas @jeremyshelton There is actually another issue. Occurrences that have already been harvested belong to a different group, e.g., Fish. Should we change the taxon group when they are re-harvested under a different group?

@dimasciput I am not clear on what this issue is? Can you clarify what these different groups are and how they work?

**Comment by dimasciput** [comment]
@jeremyshelton 

I believe this scenario will be quite rare in our case, but here's the breakdown:

- A user harvests gbif data for _fish_ and obtains occurrence AAA.
- The user creates a new taxon group, _fish2_, which includes a species that also belongs to _fish_.
- When the user harvests gbif data for _fish2_, since it has the same species, they also get occurrence AAA.
- As it stands now, occurrence AAA will be updated to the taxon group _fish2_. Therefore, when you search within the taxon group fish, you won't find AAA, as it has already been migrated to _fish2_.

However, I think this scenario is unlikely, given that currently a species only belongs to one group.

But this is not related to this ticket, if we want to resolve this issue in the future, let's create a new ticket. I'm not sure if this is an issue.

**Comment by jeremyshelton** [comment]
@dimasciput OK understood. 
I agree that this situation will not arise on FBIS, but could possibly come up in the future.
Agreed can you make a "ticket for the future" and put it at the bottom of the todo list so that we have it on record. 

Is for new functionality in this ticket - you can deploy to production.

Thanks

**Comment by dimasciput** [comment]
@jeremyshelton ticket has been created, I also have deployed this to production.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput

**Comment by helendallas** [comment]
Closing this ticket now as completed
