### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3276]
We need to include licence on our landing page somewhere, and as an attachment to the CVD file.

Please can we discuss further and action based on advice of Tim, below: 

Normally the license pertains to the database as a whole, but I think we can have two modalities:

1) When referencing the FBIS database in its entirety, add a generic attribution to the platform e.g.:

Data provided by [freshwaterbiodiversity.org](http://freshwaterbiodiversity.org/) and its contributors.

2) When providing extracts:

Data provided by [freshwaterbiodiversity.org](http://freshwaterbiodiversity.org/) and (enumerated list of data owners).

Both of the above would be accompanied by a copy of the ODBL and layman instructions on how the data may be used, repurposed and must be attributed.

For publishing data, I mentioned in our forum session the other day that I think the ODBL is more appropriate - the Creative Commons is more usually used to written or artistic works. The ODBL license is explained here https://opendatacommons.org/licenses/odbl/. Basically it requires attribution back to the publisher whilst making the data freely distributable under those terms.

**Comment by dimasciput** [comment]
I think we can add this with the new landing page, @jeremyshelton, could you please handle this?

**Comment by jeremyshelton** [comment]
@dimasciput no problem adding it once we have the licence details. 
@helendallas I think the first step is for us to draft it and then bounce it off @timlinux ?

**Comment by helendallas** [comment]
Leaving for now
