### ISSUE TITLE
Add SA province and neighbouring country as a shapefile

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3279]
Not sure why this is not available as a shape file. It is already a filter. Please can you add.

![image](https://user-images.githubusercontent.com/45286876/206420650-250326ce-4c7a-4a4f-a3b7-7ceed1fc48bf.png)

**Comment by dimasciput** [comment]
@helendallas you mean as a visual layer in fbis?

**Comment by helendallas** [comment]
Yes, as a visual layer under spatial layers, here

![image](https://user-images.githubusercontent.com/45286876/218706771-b0b3a925-7943-4a25-8927-d0ec27bbd4e9.png)

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/225804601-12fb531a-39fc-49b2-96f2-ff157250f486.png)

Layer added in the production site

**Comment by dimasciput** [comment]
@amyburness or @NyakudyaA  could you update the style please in geoserver? Thanks

**Comment by amyburness** [comment]
@dimasciput sure I can update the SLD.

**Comment by amyburness** [comment]
![image](https://github.com/kartoza/django-bims/assets/77841514/da8fe549-431f-42d7-9d65-d77a1e673069)
Labels added let me know if this styling needs any updates.

**Comment by dimasciput** [comment]
![Uploading image.png…]()

@helendallas looks fine on my side, thanks @amyburness

**Comment by amyburness** [comment]
@dimasciput Actually yesterday I kept getting a 503 Service Unavailable No server is available to handle this request. error and having to refresh to get the map to show. I think that may be what @helendallas is referencing 
![image](https://github.com/kartoza/django-bims/assets/77841514/f3fdaabd-bffd-458a-8045-38acd749af45)

**Comment by helendallas** [comment]
Thanks @amyburness @dimasciput Looks fine now
