### ISSUE TITLE
Support for SASS5 Data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#328]
We want to add support for SASS5 River health assessments in BIMS.

![screen shot 2018-09-06 at 09 35 24](https://user-images.githubusercontent.com/178003/45142263-5bf9da80-b1b8-11e8-9404-8e71cf085e6d.png)

The aim is to replicate the following field data gathering sheet:

[SASS5_Data_sheet.xlsx](https://github.com/kartoza/django-bims/files/2356005/SASS5_Data_sheet.xlsx)

Some additional notes from our slack discussion of this:

We are going to need to be able to support CRUD (read below for clarification of this) operations on this.

We want to keep things simple hence proposing choices rather than many lookup tables etc to manage domain lists.

Our intention is to support uploading the sass5 sheets and ingest them into the above data models.

We will present them as a nice read only template / view for individual sass5 sheets.

So some clarifications:

1) Note that in CRUD, creation would be in the form of a spreadsheet import, no forms for now and no update support. The workflow would be:

• user uploads a file containing a SASS5 sheet
• we parse it and extract the SASS5 Sheet and Records from it an populate the tables
• User gets a read only representation of that SASS5 sheet
• User can delete that sheet again if they have needed permissions
(so CRD actually, no update except in admin panel)

2) All SASS5 surveys would be related to a site so on the map display there would be no change.

3) We should have a SASS5 accordion in the side panel when you click on a site, in the accordion would reveal a chronological list of SASS5 sheets associated with that site. Clicking on one line item would replace/overlay the map with the report view for that SASS5sheet (maybe with an option to print it too if possible)

4) Sass5order and sass5family has same fields, why not merge them and differentiate them by the type? There is a fk relation between them because one order can have many families. The only reason there is a relation between the record and the order is that in some cases the observations are made at order level not at family.

5) The report should aim to follow a closely as possible the original spreadsheet layout i.e.

<img width="1578" alt="screen shot 2018-09-06 at 09 46 19" src="https://user-images.githubusercontent.com/178003/45142881-f3136200-b1b9-11e8-9d83-ed65a74e545f.png">

<img width="1577" alt="screen shot 2018-09-06 at 09 46 43" src="https://user-images.githubusercontent.com/178003/45142869-ebec5400-b1b9-11e8-99c4-9e2f28359263.png">

But I propose that all the biota scores are placed in a single column i.e.

![screen shot 2018-09-06 at 09 48 46](https://user-images.githubusercontent.com/178003/45142920-15a57b00-b1ba-11e8-9087-59d61ba36c3a.png)

**Comment by timlinux** [comment]
Note that there is a second element to this issue and that is migrating legacy data from the 'old' database from FRC. More info on that to follow.

**Comment by dimasciput** [comment]
Implemented
