### ISSUE TITLE
placeholder ticket for NWM and polygons

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3281]
We need a conversation with Dimas re this. thanks

We need to explore being able to filter data based on selecting a polygon in addition to a point.  Selecting the polygon opens up the overview dashboard for the polygon selected.

NWM6 will be visualized as polygons. 

Filters:
Wetland type
Threat status
Condition (PES)

**Comment by dimasciput** [comment]
@helendallas can you elaborate more about this ticket? Or can you send the polygons?

**Comment by helendallas** [comment]
@dimasciput We need a discussion with the wetland team. Please put this on hold for now.

**Comment by helendallas** [comment]
I am going to delete this ticket as it will be replaced with independent tickets for each issue.
