### ISSUE TITLE
Explore option to generate a spatially defined dashboard that provides summary data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3282]
Several use cases have been requested where a user needs data summarised for a spatial area.

Please can we discuss this further with the full FBIS team and wetland team, and then draw up a dashboard of what we would envisage.

We can then take this to Kartoza for further discussion

**Comment by dimasciput** [comment]
I will investigate this for now, and will come back with some options.

**Comment by helendallas** [comment]
This needs to go on the back burner for now as we need to prioritise the new wetland  module requirements. Also this summary dashboard was a requirement of the SANParks project, so perhaps wet the project comes online we can do it under their funds . @timlinux thoughts?

**Comment by helendallas** [comment]
Closing this ticket as duplicated in #3609
