### ISSUE TITLE
Many taxa in Taxa table are not in Taxon Management or in downloaded CSV

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3285]
Several taxa in the taxon table have not made it to the Taxon Management  and are not downloaded in the csv file. This makes it very challenging to check data.

Please fix urgently.

**Comment by helendallas** [comment]
I tried to test added a new taxon **New Species** but not receiving validation email.

**Comment by dimasciput** [comment]
@helendallas what is the species? 

I just added a species to fish module, and I got this email 
![image](https://user-images.githubusercontent.com/1979569/208053239-79b5b379-8c57-4bbb-bbb7-40dbc37650e0.png)

**Comment by helendallas** [comment]
Yeah I see yours but mine not through, I will add another???

**Comment by dimasciput** [comment]
@helendallas 
Did you try to add Tanytarsini?

Since this is not exist on gbif, you can only add a new data : 
![image](https://user-images.githubusercontent.com/1979569/208057815-e0bff6d8-7553-4ca3-94d3-f254fe0623f2.png)

But we can only add new species or genus from this form.
My suggestion for now is to add it as species, then you change the taxon rank manually.

**Comment by helendallas** [comment]
But is is already in the backend taxa table that is why i didnt want to add it again. testing is very slow.....keeps hanging on my side. might be our fibre...major lightening storms here :(

**Comment by dimasciput** [comment]
@helendallas it's not available on testing https://testing.healthyrivers.kartoza.com/admin/bims/taxonomy/?q=Tanytarsini

**Comment by helendallas** [comment]
ok sorry, adding now....very slow

**Comment by helendallas** [comment]
error file again - Taxonomy does not exist for this group

![image](https://user-images.githubusercontent.com/45286876/208059565-938acb6d-e26b-4dbf-9868-b14c27d8ebaa.png)

**Comment by helendallas** [comment]
added to testing, but not showing in taxon management after adding
![image](https://user-images.githubusercontent.com/45286876/208060328-b6a1d107-9f38-4b90-aac8-4dd83bf29e76.png)


is in taxa table

![image](https://user-images.githubusercontent.com/45286876/208060174-9f6c3893-8fcc-43ac-b729-5cf677126293.png)

**Comment by dimasciput** [comment]
@helendallas you need to change the rank to sub family first

**Comment by helendallas** [comment]
SO SubFamily wont work? does upper and lowercase and space affect uploading. If So

Please send me details of the Taxon rank categories for all levels -  this needs to match our upload file

Trying to upload but system super slow

**Comment by helendallas** [comment]
did again, still get error - used sub family

![image](https://user-images.githubusercontent.com/45286876/208062991-b95f7ac7-f7e7-410d-8126-152bd23cd7e7.png)

**Comment by dimasciput** [comment]
@helendallas 
SO SubFamily wont work? does upper and lowercase and space affect uploading. If So

Letter case will not affect the uploading, but the space does, so you need to put 'Sub Family'

**Comment by helendallas** [comment]
tried sub family, but it didnt work

**Comment by dimasciput** [comment]
https://testing.healthyrivers.kartoza.com/admin/bims/taxonomy/11141/change/ 

You haven't changed it to subfamily.

**Comment by helendallas** [comment]
did again after correcting to sub family

![image](https://user-images.githubusercontent.com/45286876/208068915-f19fa4de-b2b3-4429-aa3c-ddeba83f4148.png)

error message again. kept space

![image](https://user-images.githubusercontent.com/45286876/208069106-eea4b2d5-4ca6-4a45-a358-6ddffa8fc38f.png)


will send csv separately

**Comment by helendallas** [comment]
@dimasciput It is working now on testing. Please can you deploy to production as I need to get these missing data uploaded

**Comment by helendallas** [comment]
mmm I just added a new taxon Salpingidae in testing, manually via the Taxon Management .

But it is not showing in the Taxon Management, only in the Taxa table

![image](https://user-images.githubusercontent.com/45286876/225008911-21112273-dc80-496e-bf96-af2606e97092.png)


![image](https://user-images.githubusercontent.com/45286876/225008756-ec5a2c6b-9588-41ef-b06d-033206bb8515.png)

When a Taxon is added in Taxon Management , it needs to immediately be shown, or it may be added again, with the admin thinking the adding was not successful.

Please @dimasciput Have a proper look at this issue so that it can finally be resolved.

**Comment by dimasciput** [comment]
Deployed to production
