### ISSUE TITLE
Manual styling pesticides 

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/django-bims#3289]
Task:
![image](https://user-images.githubusercontent.com/107027990/208417142-6aa3f574-898e-449f-b36b-cf77d6c5cfbe.png)
Link to shapefiles: https://1drv.ms/u/s!Aonrfv2ZVeCRlOUuTYMPlo3J288HvA?e=MiLVr3
When styling the layer I should create a graduated style with 5 categories. The first being a 0-0 class for no data.
There after it should be 4 equal counts (Quantile) to display the rest of the info with no overlap. 
(Eg. if the maximum value of the pesticide was 10 I would have the following categories: 0-0, 0.1-2.5, 2.6-5, 5.1-7.5, 7.6-10) 

When applying the style we use categorised styling with Equal count (quantile) and 5 classes. If the first value is not 0-0 we change it, this re-calculates the remaining values to the correct values. 
![image](https://user-images.githubusercontent.com/107027990/208419940-6ffc1b88-c6eb-4e67-a6c9-653f0a14be10.png)

We then switch to rule-based styling and save the style as the pesticide name essentially creating a style for the specific pesticide wich can be loaded to display the information in the desired format.
![image](https://user-images.githubusercontent.com/107027990/208420267-933b8f17-45e4-4705-9931-66703ec7a5e0.png)

The issue is with some of the styles the qgis does not calculate correctly as some of the pesticides have more than one 0-0 count:
![image](https://user-images.githubusercontent.com/107027990/208420879-325ddcca-f74f-49a8-aa78-094f9d0ac853.png)
![image](https://user-images.githubusercontent.com/107027990/208421036-d01eff3f-03e1-41e7-9fa4-970436628b84.png)

we can manually calculate the values and overwrite the output in rule-based styling to display the correct values, but this is labour intensive extremely time consuming since there are about 80 incorrect styles. 
![image](https://user-images.githubusercontent.com/107027990/208421692-b5dc666f-57eb-479d-a32a-e7e4c32a8947.png)

My hope is to use a script to speed-up the process in calculating the styles.
I have spent time researching from the pygis developer's cookbook but seem to keep on running into problems since i am not familiar with the code.

**Comment by timlinux** [comment]
Can you share one example file that is not calculating correctly here please @EliVolsch ?

**Comment by EliVolsch** [comment]
It might be best to have a meet tomorrow and then I can demonstrate the problem. The file containing the pesticides can be found in the one drive link above. The file containing the pesticides is called PestApp_Quat_2014. The styles we are applying are from the attribute table. An example of the ones not calculating correctly Ioxynil and Bitertanol.

**Comment by helendallas** [comment]
Not sure if this ticket is resolved or still relevant?
