### ISSUE TITLE
Integration with Encyclopedia of Life

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#329]
For the side panel for a taxon it would add a lot to provide descriptive and illustrative information for a taxon. I suggest that we do this via the encylopedia of life project:

http://eol.org

Here is a sample taxon page from their site:

http://eol.org/pages/584458/overview

They provide a restful API here:

http://eol.org/api

**Comment by timlinux** [comment]
Here is a  python client for the encyclopedia of life API

https://github.com/linbug/eol_python

**Comment by dimasciput** [comment]
we got the EoL from GBIF
