### ISSUE TITLE
Feature needed for Pesticides Layer

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3310]
I need to add multiple styles to one Layer in the FBIS system for non-biodiversity layers. 

I need to have the layer shown in the list for selection and then have a dropdown with each category (e.g. pesticide name) that has its own style attached to it show, and the user can choose which category to visualize on the map. 

![image](https://user-images.githubusercontent.com/77841514/217202341-f4a76b0d-8a34-4ef7-a873-6a4ed5ee30b0.png)

**Comment by NyakudyaA** [comment]
@amyburness Can you confirm if the styles added for this layer are correct?

**Comment by dimasciput** [comment]
Deployed to both production and testing.

**Comment by amyburness** [comment]
@NyakudyaA Yes the styles look correct but James will have to look at them to confirm I will pop him an email.

**Comment by helendallas** [comment]
Thanks @dimasciput The pesticide names need to be sorted alphabetically please.

@amyburness Please add metadata for "i"

Also please confirm with James that all is correct . thanks

**Comment by dimasciput** [comment]
@helendallas the pesticide names is now sorted alphabetically in production.

**Comment by amyburness** [comment]
> @amyburness can you add a metadata for this layer please in geoserver?

@dimasciput I will add this afternoon

**Comment by helendallas** [comment]
@amyburness 

For some pesticide use everything is grey even though there are data??? and metadata still missing

![image](https://github.com/kartoza/django-bims/assets/45286876/36bb1c48-c36c-4506-82a8-db78080e3e0d)

**Comment by NyakudyaA** [comment]
@amyburness remove the default style there and use one of the pesticide as a default.

**Comment by amyburness** [comment]
@NyakudyaA 
removed and updated 
![image](https://github.com/kartoza/django-bims/assets/77841514/4629ed37-00e2-4e0b-b4c3-65f93427ec12)
however, there are still layers showing as grey that are definitely not grey in the style checking the style file now to see if there are any issues
![image](https://github.com/kartoza/django-bims/assets/77841514/ae7e15f4-099d-4aee-9a70-7ea4c04160f0)

**Comment by amyburness** [comment]
I have found the error in the SLD code and have updated them. All of the layers should be good to go @helendallas

**Comment by amyburness** [comment]
@dimasciput I added the metadata/ abstract to this layer and the other risk layers including the source information. James has asked me to add units to the legend which I will do tomorrow on the FBIS day.

**Comment by helendallas** [comment]
Thanks @amyburness and @dimasciput All looks good now, closing ticket
