### ISSUE TITLE
SASS Abundances not correct in dashboard table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3313]
When abundance data is captured per biotope and the revised at Site level, it shows correctly.

But does not come through correctly in the SASS dashboard. e,g, below Libellulidae
https://freshwaterbiodiversity.org/sass/view/13916/
![image](https://user-images.githubusercontent.com/45286876/217860854-3b275e7e-8f0c-4a04-8f61-19ffced21126.png)

Is correct when data is captured but not in dashboard table.

![image](https://user-images.githubusercontent.com/45286876/217860033-031c5adb-ba5b-4501-9dc7-22166451ca23.png)

Also all Baetidae and Hydropsychidae needs to be show in the dashboard table.

![image](https://user-images.githubusercontent.com/45286876/217861428-6f99f0c1-b66e-4de3-83b5-9a7ee2a20f44.png)

**Comment by dimasciput** [comment]
Fixed in testing.

**Comment by helendallas** [comment]
Thanks, issue with missing 1,1 = A is fixed. 
Please deploy to live

**Comment by dimasciput** [comment]
Deployed to production
