### ISSUE TITLE
Site Visit Data incorrect - Getting multiple site visits for same site with same date - duplicate taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3318]
Need to investigate this issue

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=D1ORAN-00021&siteId=86428&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=86428&orderBy=name&polygon=&thermalModule=&dst=

![image](https://user-images.githubusercontent.com/45286876/218477274-b5f79523-e9a2-480d-b120-628331edc812.png)

**Comment by helendallas** [comment]
@dimasciput Please check why duplicate site visit and occurrence records are displayed in the Site Visit Data table, when the data are not there.

![image](https://user-images.githubusercontent.com/45286876/224975236-e302367d-337a-42f9-9e36-64edb0145706.png)

https://freshwaterbiodiversity.org/site-visit/detail/236218/

![image](https://user-images.githubusercontent.com/45286876/224974993-f5321b95-02ab-43a5-a40b-3655d246f827.png)

**Comment by dimasciput** [comment]
@helendallas This has been fixed on testing. The data is mirrored from production, after which I run the script to remove duplicates.
https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=D1ORAN-00021&siteId=86428&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=86428&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
Ok thanks @dimasciput , so you will deploy to production
