### ISSUE TITLE
Pesticide dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3320]
We need a pesticide dashboard that summarises the pesticide data for a site in a quaternary catchment.

This will be visible below the Physico-chemical data dashboard in the side panel.

![image](https://user-images.githubusercontent.com/45286876/218733964-e6146e5a-8055-44e8-b454-bdcf65410baa.png)

When the user clicks on a site, the side panel opens up as always and at the bottom is the **Pesticide data** . The dashboard should include the normal:

**Map** -  as per water temperature and physico-chemical dashboards (but change to Bing satellite map as per ticket #3211 

**Overview** -  as per water temperature and physico-chemical dashboards 

**A colour coded graph showing potential risk to algae, invertebrates and fish** based on the 5 category scale (i.e. Very Low to Very High).

**A table showing the top 10 pesticides** with the highest toxic unit score for algae, invertebrates and fish (expressed as a percentage of the total sum [“sum” in attribute table] of TUs for algae, invertebrates and fish, respectively).

**A downloadable table (csv) of pesticide use** giving estimated crop application rates of each pesticide per quaternary catchment in South Africa (PestApp_Quat_2014.shp attribute table).

**Links to two downloadable spreadsheets:**
Generic Pesticide Risk Indicator
Specific Pesticide Risk Indicator

These are both excel spreadsheets that the user needs to be able to download and use. 

[GenericRI.xlsx](https://github.com/kartoza/django-bims/files/10732310/GenericRI.xlsx)

[SpecificRI.xlsx](https://github.com/kartoza/django-bims/files/10732313/SpecificRI.xlsx)

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 

> A downloadable table (csv) of pesticide use giving estimated crop application rates of each pesticide per quaternary catchment in South Africa (PestApp_Quat_2014.shp attribute table).


How is the estimation calculated?

**Comment by dimasciput** [comment]
this is deployed to testing 

https://testing.healthyrivers.kartoza.com/pesticide-dashboard/66673/?taxon=&search=&siteId=66673&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=66673&orderBy=name&polygon=&dst=

**Comment by helendallas** [comment]
**For the record: Comments from James via email**

In terms of the table showing the top 10 pesticides:
 
This data can derived from the attribute tables of the algae, invertebrates and fish toxic unit layers. Each of these layers are currently displayed in FBIS according to the final ‘Sum’ field in the attribute table.
 
This value in the ‘Sum’ field is the sum of the toxic unit score in each of the preceding fields which gives the toxic unit score for each pesticide. Example:
 
The ‘Sum’ for quaternary A71L (for fish) is 0.031 (see attached Excel Table – Sheet 1 contains the information as contained in the attribute table for A71L showing the toxic unit score per pesticide and the sum of these scores as the last value)
 
The top 10 pesticides are then displayed in bold in Sheet 2 of the table. I’d only want these top 10 pesticides displayed as a table as per Sheet 3 (for Fish) and then also to include a table for Algae and Invertebrates as well.

**Comment by helendallas** [comment]
Please add as i or scroll over text, at PESTICIDE RISK

Pesticide Risk and Use are based on values at the quaternary catchment and do not reflect site specific values.

**Comment by helendallas** [comment]
Thankas @dimasciput This looks good, closing ticket
