### ISSUE TITLE
Show units for water quality variables in csv download

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3323]
CSV downloads currently do not show units for abiotic physic-chemical variables, but this should be included.
 For example, "COND"	should read "Conductivity	(mS/m)" in csv downloads. 

@dimasciput what is the easiest way for us to adjust this?

Here is out abiotic physic-chemical variable spreadsheet: 
[Abiotic_PhysicoChemical Variables Master.xlsx](https://github.com/kartoza/django-bims/files/10800444/Abiotic_PhysicoChemical.Variables.Master.xlsx)

@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton this is updated in testing, please give it a test

**Comment by helendallas** [comment]
Looks good to me. @jeremyshelton ?

**Comment by dimasciput** [comment]
deployed to production
