### ISSUE TITLE
Water temperature data - format for 24 data and missing source reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3329]
@dimasciput Please confirm the format that the water temperature data has to be in when the data are 24h.  Its giving me an error:
Errors :
2 : Missing minimum and maximum data value

Also the option to add a source reference disappears when selecting 24h as the logging interval.

![image](https://user-images.githubusercontent.com/45286876/224013453-4dbb2b50-eb5c-40fd-a330-e34dd7c428d0.png)

**Comment by dimasciput** [comment]
@helendallas 
> Please confirm the format that the water temperature data has to be in when the data are 24h. Its giving me an error:

If the data is daily then you need to provide Mean, Minimum, and Maximum.

> Also the option to add a source reference disappears when selecting 24h as the logging interval.

Ok let me fix this.

**Comment by dimasciput** [comment]
The issue has been resolved on the testing site.

**Comment by helendallas** [comment]
Is it four columns then?
Date and time 
Mean 
Minimum 
Maximum?

**Comment by helendallas** [comment]
@dimasciput Not sure if this is working. I tried to upload the following file.....but it is just spinning.

[Mutale Bridge.csv](https://github.com/kartoza/django-bims/files/11038340/Mutale.Bridge.csv)

**Comment by dimasciput** [comment]
@helendallas have you tested this again? It should be working now

**Comment by helendallas** [comment]
@dimasciput Tested it on testing working now, thanks. Assume already deployed to production, so closing ticket
