### ISSUE TITLE
checking for Data confusion in RBIS

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#3341]
Dear Dimas,

We hope this email finds you well.
We thank you for keeping en eye on the RBIS and the support you continue to provide.

A couple of days, the team has been requested to send data for some catchments here in Rwanda from RBIS. When we pulled the data, we realized that some Taxonomic levels were mixed - e.g: in Birds and Amphibians, you will see for example Afrixalus orophilus (Frog- Kingdom: Animalia, Phylum: Chordata, Class: Amphibia, Order: Anura - but all these will turn to plants such as Plantae, Travheophyta, Magnoliopsida etc.
![image](https://user-images.githubusercontent.com/64961274/226266901-787d4443-4c47-45e5-9c05-92256c787148.png)

check: **https://rbis.ur.ac.rw/map/#species-detail/taxon=3042&search=Afrixalus%20orophilus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22RBIS%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=**

We first though the RBIS input data were wrong but indeed we cannot made the errors as such. We are wondeing whether it is from GBIF data harvest or an error/ Bug in the system. Hence, would you please check if these could be solved? 
Otherwise we shall need to recreate these modules as soon as possible.

Thank you

**Comment by dimasciput** [comment]
Deleted because it was outdated.
