### ISSUE TITLE
Error while uploading taxonomic data

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#3342]
I created the taxon group Trichoptera and tried to upload around 16.000 species, which did not work (I got kind of an overflow issue).

I selected one family and tried the upload as csv and got the message "Header row does not follow the correct format"; I adapted the header according to the template, also added all the columns of the template, but it did not work.

<img width="1025" alt="Bildschirmfoto 2023-03-24 um 12 06 06" src="https://user-images.githubusercontent.com/123731080/227505636-1b2ed25a-28be-4897-acde-20ee617bfbd0.png">

**Comment by dimasciput** [comment]
Hi @helendallas, have you helped her resolve this issue? Can we close this?
