### ISSUE TITLE
Abiotic filter - physico chemical data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3353]
![image](https://user-images.githubusercontent.com/45286876/229121704-dcad6754-d8e9-460e-aba7-8115eb1f47fb.png)

Please check as this does not seem to be working
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=physico_chemistry&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by dimasciput** [comment]
This is fixed, please give it a try

**Comment by helendallas** [comment]
Sites being returned now but not displayed on the map

![image](https://user-images.githubusercontent.com/45286876/231682657-0fe171dd-e303-44d8-8be3-d03ef5568049.png)

**Comment by helendallas** [comment]
Also not showing water temp sites on may. Then if I go back to selecting Occurrences - no sites are returned. Even after hitting reset

![image](https://user-images.githubusercontent.com/45286876/231683360-58eaa995-90bf-44a6-ad8a-a563aa1d192c.png)

**Comment by helendallas** [comment]
Thanks @dimasciput All working now. I will close the ticket
