### ISSUE TITLE
Search result inaccuracy

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3359]
Information in search result tab not consistent with search query and data returned in dashboard. 

<img width="1141" alt="Screenshot 2023-04-17 at 10 47 08" src="https://user-images.githubusercontent.com/44292029/232434209-41a527bc-d29b-4ab5-98b0-5a8214167719.png">

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=physico_chemistry&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[19.02523040771484,-33.82337593116917],[19.04720306396484,-33.83820597734082],[19.084968566894528,-33.81767138227613],[19.08222198486328,-33.80055545273895],[19.062995910644528,-33.79370812225996],[19.038276672363278,-33.79542000623123],[19.02523040771484,-33.82337593116917]]&dst=

**Comment by dimasciput** [comment]
this is fixed on production and testing

**Comment by jeremyshelton** [comment]
Thanks @dimasciput
