### ISSUE TITLE
Taxon management CSV file

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3363]
I downloaded a csv file to test but didnt not receive it by email even though it was only 12 taxa.

Please check where this email has gone and that it is working correctly.

**Comment by dimasciput** [comment]
@helendallas I can download the taxa in production, can you try it again please. If it's still happening please send the link.

**Comment by dimasciput** [comment]
Ah, sorry, I thought it was FBIS.

**Comment by helendallas** [comment]
RBIS project finished, Closing ticket
