### ISSUE TITLE
Allow other service providers when adding Non biodiversity layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#3379]
**Is your feature request related to a problem? Please describe.**

When adding Non-Biodiversity layers in the admin panel the expectation is that we are using wms from OGC protocol. This is a problem when using layers from ArcGIS. i.e the 
URL https://dffeportal.environment.gov.za/hosting/rest/services/PACA/SAPAD/MapServer which would produce the following getmap request
https://dffeportal.environment.gov.za/hosting/rest/services/PACA/SAPAD/MapServer/export?bbox=29.215974,-29.590664,29.489133,-29.404288&size=1237,844&format=PNG32&layers=show:3&transparent=true&f=image

Adding the same layer type in FBIS would produce the following request

https://testing.healthyrivers.kartoza.com/bims_proxy/https://dffeportal.environment.gov.za/hosting/rest/services/PACA/SAPAD/MapServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&name=foo&layers=show:3&format=PNG32&getFeatureFormat=text/plain&STYLES=&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&BBOX=0,-5009377.085697312,626172.1357121639,-4383204.949985148

# Solution

Add an option to choose the service providers i.e 
* OGC Compliant ( MapServer, GeoServer etc)
* ArcGIS ( Rest endpoint, WMS etc)

And in future this could support other types i.e
* Vector tiles URL etc

**Comment by helendallas** [comment]
No relevant since revision of layers visualisation
