### ISSUE TITLE
Harvesting GBIF data for test module Trichoptera freezes

### ISSUE THREAD

**Issue by vanbremer** [kartoza/django-bims#3383]
I have tested harvesting from GBIF for the Trichoptera test module (created from FADA taxonomic list of global trichoptera), but the process fails or freezes after processing a certain number of species. 
After having restarted the harvesting the process freezes again at the same point.

Status message is: 
"Fetching gbif data for Hydropsyche angustipennis (2503/14140)".
Currently still running at https://fip-bio.igb-berlin.de/harvest-collections/. 

<img width="468" alt="2023-05-25_220619" src="https://github.com/kartoza/django-bims/assets/16322488/5274a01a-25e8-475d-a9ff-1fa3f21eef04">

Could you please check why the process fails here?
Thanks a lot!

**Comment by dimasciput** [comment]
this is now fixed, the system will automatically resume the process
