### ISSUE TITLE
Adding data to sites that have water temperature data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3385]
Something strange has happened – all the Site codes have changed even though I included
the correct site codes in the upload file. Here is an example

FBSI Site code | Original Site Code | New site code is now

D3ORAN-00081 | Site 1_Douglas | **D3ORAN-00094**
D7ORAN-00153 | Site 2_Prieska |  
D7ORAN-00154 | Site 3_Gifkloof |  
D7ORAN-00155 | Site 4_Uppington 1 |  
D7ORAN-00156 | Site 5_Uppington 13 |  
D7ORAN-00157 | Site 6_Druiswater |  
D7ORAN-00158 | Site 7_Kanoneiland (Up 6) |  
D7ORAN-00159 | Site 8_Uppington 8 |  
D7ORAN-00160 | Site 9_Uppington 12 |  
D7ORAN-00161 | Site 9_Soverby (Up 2) |  
D7ORAN-00162 | Site 10_Ikaia Lodge (Up 5) |  
D7ORAN-00163 | Site 11_Blouputs |  

And in the location site table; the original site code has been allocated to
Name -&nbsp; please can you check what is up.

**Comment by dimasciput** [comment]
@helendallas I have found and fixed the bug in the uploader script. I also corrected the site code in production.

**Comment by helendallas** [comment]
Thanks, looks like water temp and biological sites are now the same.. closing ticket
