### ISSUE TITLE
Issue with taxa in Taxa table not showing on Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3386]
PLEASE can you sort this out. It has been a recurring issue and you keep asking me to do a quick side fix, but it compromises our workflow when we have to add new occurrence data.
 
So this species Tramea limbate, is in the Taxa table in admin,  https://freshwaterbiodiversity.org/admin/bims/taxonomy/?q=Tramea+limbata
![image](https://github.com/kartoza/django-bims/assets/45286876/73c51e18-df43-4081-9243-4739386e9adc)

but does not show on Taxon Management, and I get an error message when trying to upload occurrence data.
 
“Taxonomy does not exist for this group”
![image](https://github.com/kartoza/django-bims/assets/45286876/669d438d-20dc-4b4e-a918-17d79484dcf6)

**Comment by helendallas** [comment]
Another example
![image](https://github.com/kartoza/django-bims/assets/45286876/cc513c9c-3926-40d8-8c64-62c2dd2eddd6)

This is stored in FBIS, but does not show up in Taxon Management, and does not get downloaded in the csv file.

It would of been added in the taxonomic upload file, not in the SASS taxonomy

**Comment by dimasciput** [comment]
@helendallas, these species are from the virtual museum. I will adjust the harvester script to automatically group species into the correct module and will also fix the existing data.

**Comment by dimasciput** [comment]
@helendallas I have fixed this issue in the testing. Please give it a try.

**Comment by helendallas** [comment]
Ok seems to be fixed for now.. Please deploy to production

**Comment by helendallas** [comment]
@dimasciput Opening ticket as I tried to add a new taxon in taxon management and it is not showing up as before.

**Comment by dimasciput** [comment]
@helendallas is this the one?
https://freshwaterbiodiversity.org/taxa-management/?&selected=21&validated=False

You need to set the validated to false

**Comment by helendallas** [comment]
@dimasciput This is a problem again and I cannot edit get message
<img width="285" alt="Screenshot 2023-10-11 at 14 30 31" src="https://github.com/kartoza/django-bims/assets/45286876/1e12a3d6-b057-4485-81f4-ec9eb60f4057">

**Comment by helendallas** [comment]
Going to create a new ticket rather

**Comment by dimasciput** [comment]
@helendallas https://github.com/kartoza/django-bims/issues/3493#issuecomment-1748324091
