### ISSUE TITLE
Renaming two spatial layers

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3398]
Two quinary layers need to be renamed, as follows 
o	“Quinary catchment” to "Quinary catchments (Schulze et al. 2011)"
o	“NFEPA quinaries” to "Quinary catchments (NFEPA 2011)"

**Comment by helendallas** [comment]
This has been completed on production. Closing ticket

![image](https://github.com/kartoza/django-bims/assets/45286876/8debbdda-4050-4a55-bbd4-e47d5a6169be)

**Comment by helendallas** [comment]
@amyburness Please can you rename as follows:

NFEPA Quinary Catchments

Schulze Quinary Catchments

Also Metadata for Schulze Quinary Catchments needs updating please: as follows

Schulze, R.E., Horan, M.J.C., Kunz, R.P., Lumsden, T.G. and Knoesen, D.M. 2011. The South African Quinary Catchments Database. In: Schulze, R.E. 2011. A 2011 Perspective on Climate Change and the South African Water Sector. Water Research Commission, Pretoria, RSA, WRC Report TT 518/12, Chapter 2.2, 31 - 37. 

It would be really useful if we could easily update the metadata ourselves....Is this possible? and if so how?

**Comment by amyburness** [comment]
@helendallas changes made. 
![image](https://github.com/kartoza/django-bims/assets/77841514/950f0735-784d-4d16-96f9-de6bff465e86)


Old abstract as follows removed: 

From Schulze et al (2011) modelled flow data for quinary catchments in SA.
Use columns A-J from the shapefile “with_ids”.
Column H is the critical one with the quinary IDs (sub_cat).

Note: 
LEVEL_1     equals    “Flow Region” 
REGIME_T   equals     “Flow_Regime_Type”?

These were used to generate Flow Regions and Flow_Regime_Types based on analyses of Indicators of Hydrological Alteration (IHA)

Flow Region (Hydrological Region) and Flow_Regime_Type
Here is the metadata plus metrics, and the shapefile of the eight broad flow regions in SA.

Flow types shapefile on Dropbox

Citation for this would be:

Rivers-Moore, N.A., Schulze, R.E. and Davis, N. (2016) Flow regime types for South African rivers.  WRC Project No. K5/2315, Water Research Commission, Pretoria.

**Comment by amyburness** [comment]
@helendallas I just want to confirm by metadata do you mean the information associated with the layer the user sees when they click on the i button?

If so it is an easy change in GeoServer I will make an SOP we can add to the documentation.

**Comment by amyburness** [comment]
@helendallas ok great let me add a few short notes on how to do the update.

**Comment by amyburness** [comment]
@helendallas here are two simple SOP for how to do the above. Who adds this to the user manual? I see on the documentation site the manual is a PDF. 

[Change display name.docx](https://github.com/kartoza/django-bims/files/12189958/Change.display.name.docx)
[add abstract (1).docx](https://github.com/kartoza/django-bims/files/12189959/add.abstract.1.docx)

**Comment by helendallas** [comment]
@amyburness Kartoza are meant to be keeping the technical side updated. Specific to publishing layers. @timlinux Not sure where this is and how it gets updated.

Please can you share info in ticket

@KSnaddon here are instructions for changing name and metadata abstract from @amyburness

**Comment by amyburness** [comment]
@helendallas I will check with @timlinux and @dimasciput

**Comment by helendallas** [comment]
@amyburness Once these notes have been integrated into the technical doc that Kartoza are maintaining. Also on wagtail
@timlinux Please confirm where the latest technical notes are being added and how they can be accessible to FBIS admin.

**Comment by helendallas** [comment]
Sent email to @amyburness re adding technical notes to document platform, closing ticket
