### ISSUE TITLE
Landing page functionality

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3399]
@dimasciput following on from ticket #3237 we would like to be able to do the following on the FBIS landing page:

**Banner**
- Is it possible to have a single banner image without getting the green dot?
- Is it possible to adjust font size, position and style on the banner?

**Sections**
- How do I change the background colour of different sections on the landing page?
- How do I create text and image inline with each other within the same section? (see RBIS site)
- How do I centre an image in a section (this option is currently greyed out)
- How do I create multiple images horizontally within a section? (see RBIS site)
- I can see an option to add a button - how do I format the colours/shape/border or add a link?
- How do I add a video?

**Partners**
- How do I change the "PARTNERS" font to "Partners"
- How can I add a similar section but under the heading "Funders"

**Comment by dimasciput** [comment]
thanks @jeremyshelton ,

This will take one day to implement and address. I will be working on them during this sprint.

**Comment by jeremyshelton** [comment]
Perfect. Thanks @dimasciput

**Comment by dimasciput** [comment]
Hi @jeremyshelton, could you please check the testing site? 
Is it aligned with what you're looking for? 

Would you like me to create some documentation on how to create sections for the landing page? 
Some aspects may be slightly technical, but I believe they are still manageable for non-tech users.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I am out of office this week but will text and revert on Monday. 
Some basic documentation could be helpful.

**Comment by dimasciput** [comment]
Added docs here : 

- [Adding a Landing Page Section](https://kartoza.github.io/bims-website/admin/adding-landing-page-section/)
- [Embedding Video on the Landing Page](https://kartoza.github.io/bims-website/admin/embed-video-on-landing-page/)
- [Adding Inline Images on the Landing Page](https://kartoza.github.io/bims-website/admin/add-inline-images/)

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I will test this and will revert with feedback 👍

**Comment by jeremyshelton** [comment]
@dimasciput I can provide the icons, but can we please add a section with these high level site metrics as well?

Ideally "Uploads" would be occurrence record uploads and "Downloads" would be occurrence record downloads...but it may be easier to just tally the actual download requests instead?

Please advise on what you think is most feasible?

<img width="776" alt="Screenshot 2023-07-21 at 07 16 58" src="https://github.com/kartoza/django-bims/assets/44292029/bf660798-6da5-4fcd-bc24-759a06f2bd85">

**Comment by dimasciput** [comment]
@jeremyshelton yes please send me the icons.

**Comment by jeremyshelton** [comment]
@dimasciput on great. I will send these through to you later today 👍

**Comment by jeremyshelton** [comment]
@dimasciput here is a link to the icons: https://www.dropbox.com/scl/fo/9f876mtp5hecs5o9d4obq/h?rlkey=dkip1w2rem196hcf68bzhwctc&dl=0

**Comment by dimasciput** [comment]
@jeremyshelton 

![image](https://github.com/kartoza/django-bims/assets/1979569/4b9f3162-94a6-475b-8344-f33aa3a28902)

What do you think?

**Comment by jeremyshelton** [comment]
@dimasciput nice!

1. Make the numbers smaller (they can be in bold font)
2. Make the upload and download icons smaller.
3. These should be above "Biodiversity Records" in a separate section - perhaps white background?

**Comment by dimasciput** [comment]
@jeremyshelton 

![image](https://github.com/kartoza/django-bims/assets/1979569/bcf3cd68-b6a5-43d0-a64d-19b310800ef6)

**Comment by dimasciput** [comment]
![image](https://github.com/kartoza/django-bims/assets/1979569/2ef1875a-4699-4535-bf03-8aa00fe1222a)

Smaller text

**Comment by dimasciput** [comment]
@jeremyshelton 

![image](https://github.com/kartoza/django-bims/assets/1979569/69babd62-3c61-4cd8-804e-49b4477dc6c3)

I resized the download and upload icon

**Comment by jeremyshelton** [comment]
@dimasciput that looks great. Thank you.
By automate, I just man that these numbers will change automatically as the number of records, users, taxa, uploads, downloads change over time?

**Comment by dimasciput** [comment]
> By automate, I just man that these numbers will change automatically as the number of records, users, taxa, uploads, downloads change over time?

Yes, these data are from database.

**Comment by jeremyshelton** [comment]
Excellent 👌

**Comment by jeremyshelton** [comment]
@dimasciput please replaced the upload and download icons with the attached versions.
Please make them nice and small if possible.
Thanks.
![DOWNLOAD](https://github.com/kartoza/django-bims/assets/44292029/cb4cf7a1-0dd4-4b73-9213-9200a14de307)
![UPLOAD](https://github.com/kartoza/django-bims/assets/44292029/fd5a7200-8eaf-437e-a1d4-2fd09a9456ed)

**Comment by helendallas** [comment]
@jeremyshelton Are you happy with landing page? Can we close this ticket?

**Comment by jeremyshelton** [comment]
@helendallas not yet.
Still waiting for @dimasciput to update two icons.

**Comment by helendallas** [comment]
Thanks @jeremyshelton Surely we should be aiming to have functionality that allows us to update the icons? @dimasciput ?

**Comment by jeremyshelton** [comment]
Dimas has given me access to edit icons etc in the landing page sections, but not those icons at the top with the platform summaries and occurrence records.

**Comment by jeremyshelton** [comment]
@dimasciput just a reminder to please update the upload and download icons as per above.
Thanks

**Comment by dimasciput** [comment]
@jeremyshelton, Thanks, I'll address it today. However, could you please move the ticket back to 'ready/todo'? This helps me easily identify which tickets I still need to address.

**Comment by dimasciput** [comment]
@jeremyshelt
<img width="1124" alt="Screenshot 2023-08-24 at 1 07 29 PM" src="https://github.com/kartoza/django-bims/assets/1979569/d6969c6f-c247-4096-aef1-a8f547fa3785">

What do you think?

**Comment by jeremyshelton** [comment]
@dimasciput that looks great.
Please deploy to production.
Thanks

**Comment by dimasciput** [comment]
> Uploads seems low - does this also include all SASS data?

The uploads only count those from the occurrence uploader, not from the site visit/SASS form. Should I also include submissions from the form?

@jeremyshelton @helendallas

**Comment by jeremyshelton** [comment]
@dimasciput yes I think that the SASS uploads should be included in this.

**Comment by helendallas** [comment]
looks Like SASS have been included.Closing ticket
