### ISSUE TITLE
Selecting single or multiple wetlands (i.e. polygons)

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3400]
We need to discuss the feasibility and technical practicality of users selecting (point and select, or using lasso) single or multiple wetlands, that are polygons (not points) on the Wetlands Map.   On selection, the user would receive a single or multi-wetland Overview page with summary information for that whole wetland or wetlands.

The design and contents of the Overview page will be dealt with on a separate ticket.

**Comment by dimasciput** [comment]
Hi @KSnaddon,

I'm trying to understand if the polygon/wetland will serve the same purpose as a current site. Specifically, will it carry the same data, such as occurrences, site visits, site code, and so on? Alternatively, is this polygon intended for a completely different context?

If the polygon is not a site, the implementation would be much simpler since it would behave differently from the existing site.

**Comment by KSnaddon** [comment]
Hi @dimasciput 
If I understand you correctly, the wetland polygon will be like a site, carrying with it information on site visits, occurrences etc.  The polygon will also have several sites (points) within it, as researchers will visit (a point in time and space) a particular wetland (polygon).  So essentially the wetland polygon is like a river line.

**Comment by dimasciput** [comment]
Hi @helendallas @KSnaddon, do you have the layers ready? Or perhaps, do you have a sample of the layer?

**Comment by KSnaddon** [comment]
@dimasciput I am following up with SANBI...

**Comment by KSnaddon** [comment]
@dimasciput Do you have the wetlands layer now?

**Comment by dimasciput** [comment]
@KSnaddon yes I got the layer, I have deployed it to testing site https://testing.healthyrivers.kartoza.com/map/.

I have a question. When a user is creating a site, they simply need to select the layer, correct? Currently, the layer contains polygons of various sizes. Could you provide me with an example of a layer that could potentially serve as a site?

For instance, could this layer

![image](https://github.com/kartoza/django-bims/assets/1979569/f1017610-f89b-4874-a3bb-3f4d0d7a4c02)

be considered a single site?

Also, is there a maximum size for a site? For instance, can users only create sites with smaller layers, like this one?

![image](https://github.com/kartoza/django-bims/assets/1979569/e4016060-90c3-4a69-ac75-0c0035d8e444)

**Comment by KSnaddon** [comment]
@dimasciput  There will be two different workflows - (1) the user will want to add a site (a point) to these polygons, where specific data has been collected, or (2) the user will want to add data that represents the whole wetland (polygon).  So for (1), the workflow would be the same as the existing "add site" process, with some tweaking to make it wetland-specific.  For (2), I'm not sure how it would work - we all discussed being able to select or add a centroid for the whole wetland?

**Comment by KSnaddon** [comment]
@dimasciput 
The boundary lines for the wetlands layer (when I looked at it on the Test Map) are too wide - can we reduce them so that the wetlands don't look so large?  Perhaps the same width as the river lines.

**Comment by helendallas** [comment]
@KSnaddon Is this not the same or similar to ticket #3455 ?

**Comment by KSnaddon** [comment]
@helendallas Yes it can be merged into one

**Comment by helendallas** [comment]
Closing ticket as revised in ticket #3673
