### ISSUE TITLE
Upload of 2 new spatial layers 

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3411]
Two new spatial layers for upload (from SANBI) are:
1. NBA2018 Dams layer (upload spatial layer, create SLD based on two artificial categories, add as a filter)
2. VegMap bioregions (upload spatial layer, create SLD based on biomes colour scheme, add as a filter)

Two documents with information relevant to the upload are as follows:

[Uploading Artificial Wetlands to FBIS.docx](https://github.com/kartoza/django-bims/files/12080786/Uploading.Artificial.Wetlands.to.FBIS.docx)
[Uploading Bioregions to FBIS.docx](https://github.com/kartoza/django-bims/files/12080788/Uploading.Bioregions.to.FBIS.docx)

**Comment by amyburness** [comment]
@KSnaddon I was able to download I will upload these layers to the system and make the documentation on how to do so. They will be up by Friday evening.

**Comment by KSnaddon** [comment]
Thanks Amy!

**Comment by helendallas** [comment]
@amyburness Please update us on this ticket as I dont see either of these layers on FBIS

**Comment by helendallas** [comment]
@amyburness We have another sprint from tomorrow but it doesn't look like these layers have been published yet. PLEASE revert asap as to the status of this please .

We can see the SA Veg map Bioregions but as we can get I don't know if dams layer is correct.

**Comment by amyburness** [comment]
I will look at this today and they will be up this evening. (I think there is an error in the style).

**Comment by amyburness** [comment]
@dimasciput there is an issue I have double-checked the style and it works in GeoServer but does not come through to FBIS 
![image](https://github.com/kartoza/django-bims/assets/77841514/ea712841-bf62-4edd-bde7-e928606851ad)

**Comment by amyburness** [comment]
@helendallas these 2 layers are up in the layers selector and I am working to get the filters done today. Please let me know if the layers look correct.

**Comment by KSnaddon** [comment]
@amyburness They both look good. Perhaps we can make the Veg Bioregions a bit more transparent.  It looks like the similar bioregions are grouped in similar colours, which was the request from SANBI.

I will check with SANBI, but it may make sense to make the title "Artificial waterbodies" with the details of the fact this is from NBA 2018 in the Information.

**Comment by KSnaddon** [comment]
The "i" is not working on any of the layers, so I can't check this.

**Comment by KSnaddon** [comment]
@amyburness 
Did you receive the abstract information for the Dams (artificial wetlands) and Veg Bioregions layers? I'm not sure if Adwoa included this with the layers?

**Comment by helendallas** [comment]
@KSnaddon I think it makes sense to remove the old DWS Dams layer. Can you action, then close ticket. Thanks

**Comment by KSnaddon** [comment]
@amyburness Would you be able to put together the instructions for removing a spatial layer, such as the old DWS Dams Layer mentioned above?

**Comment by helendallas** [comment]
@KSnaddon I am closing this as SA Veg Map Bioregions is up, and Artificial waterbodies are up. I will Crete a new ticket specifically around Kartoza @amyburness improving the documentation so that administrators can more efficiently upload and publish spatial layers, together with metadata etc.

**Comment by KSnaddon** [comment]
@helendallas Thanks Helen.  Yes, a clear work flow and interpretation of the various bits of information that need to be entered when adding a new group and filter would be very useful.
