### ISSUE TITLE
Add NFEPA quinary catchments as a filter

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3412]
Adwoa Awuah (SANBI) successfully added the NFEPA quinaries as a service to GeoContext with the help of Dimas, but she got stuck at adding the quinaries to the existing catchment filter groups on GeoContext.  Although she added the layer to the filter group, she was unable to make this visible on the dashboard and the left menu. 

Can someone assist with these last steps please?

**Comment by helendallas** [comment]
Please can I request that the process gets documented for future....or current documentation checked and clarified so that we can managed the filters independently of Kartoza going forward where possible

**Comment by KSnaddon** [comment]
A short video may help?

**Comment by amyburness** [comment]
@helendallas and @KSnaddon I will make the filtering video this weekend and update the documentation.

**Comment by helendallas** [comment]
@amyburness Please an update on this ticket.

**Comment by KSnaddon** [comment]
@amyburness Is it possible to add the NFEPA quinaries as a filter, but not provide the list of quinary codes as a drop-down list, as for the Schulze quinaries?

i.e. allow the user to enter a quinary number in the Search box, but not break them down like this (which makes an incredible long list!):

![image](https://github.com/kartoza/django-bims/assets/91128958/c5832c51-7d23-4d1f-9229-78ca32a70221)

**Comment by KSnaddon** [comment]
@helendallas @jeremyshelton Can we perhaps shorten the Catchment filter text to "Primary Catchment" and not "Primary Catchment Area"?  This seems unnecessary.  This would apply to all the levels of Catchment.  Also, see my comment above.

**Comment by helendallas** [comment]
@amyburness @KSnaddon I have renamed some of the geo context such as Primary Catchment Area is now Primary Catchment, and have managed to figure out some of the workflows for fixing the overview panels and what is shown and where. What I cannot figure out how to do is to add a new layer to an existing group, such as NFEPA Quinary Catchment

We really do need guidance and documentation on this process please.

**Comment by helendallas** [comment]
As discussed with @dimasciput on the 19 Sep 2023, @dimasciput will add a search function for this NFEPA Quinary Catchment as well as the Schulze Quinary catchment.

Users will then be able to type in the quinary number and select records for the selected quinary.

@KSnaddon This will mean a user cannot select more than one quinary at a time. @dimasciput  Is this correct?

**Comment by helendallas** [comment]
This has been deployed to testing. Awaiting deployment to production. See ticket #3499

Closing ticket
