### ISSUE TITLE
Site icon colour-coding and size

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3414]
@dimasciput can we look at (1) reducing the size of the site icons on FBIS (especially when zoomed out) and (2) colour-coding by Data Source?

We could use the 3 colours from the FBIS logo:

<img width="28" alt="Screenshot 2023-07-21 at 13 12 26" src="https://github.com/kartoza/django-bims/assets/44292029/409a007c-3b87-42e5-b496-50b75586c572">

**Comment by dimasciput** [comment]
> are the data from FBIS, GBIF, VM not distinct on FBIS?

The sites don't have 'data_source' data; they only contain the collection records. A single site could have collection records from FBIS, GBIF, or VM. Also, this is going to make the search query slower, as I need to add a data source to the site.

Perhaps we can revisit this in the next phase, as we plan to enhance the system used for displaying the map, moving from OpenLayers to MapLibre and upgrading to vector layers. This should improve the speed and performance compared to our current approach.

**Comment by dimasciput** [comment]
@jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput ok, understood and agreed 👍

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas do we still need this? Because the color is now from the ecosystem type. We can't have both.

**Comment by jeremyshelton** [comment]
@dimasciput no need to do this anymore.
Closing ticket.
