### ISSUE TITLE
Allow users to flag wetlands that are not / badly mapped

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3425]
It would be extremely useful if FBIS users could flag where:
1. No wetland has been mapped where there should be one, 
2. A mapped wetland is not a wetland, 
3. A wetland has been poorly mapped.

This could be a separate button next to "Add site", perhaps called "Flag wetland map" or something, which would allow the user to add the following information:
1. User name
2. Record the mapping error
3. Comment

This information would then be sent to SANBI and FRC.

**Comment by KSnaddon** [comment]
![Add wetland mapping issue](https://github.com/kartoza/django-bims/assets/91128958/5bfd2afc-1add-435e-ad79-0cdf6a86fef5)

Could add this option up on the main menu bar (shift it to next to "Add site")

**Comment by KSnaddon** [comment]
[Flag mapping issue template.xlsx](https://github.com/kartoza/django-bims/files/12332591/Flag.mapping.issue.template.xlsx)

**Comment by KSnaddon** [comment]
Rather than putting this option up on the menu bar (a bit too prominent?), it could go as a "Feedback" option.  It must have a georeferenced point (coordinates) associated with it though.

**Comment by KSnaddon** [comment]
@dimasciput Is it possible to add another option to the Feedback list - "Flag wetland mapping issue", but connect this to a point on the map?

The email would need to come to the wetland team members.

**Comment by KSnaddon** [comment]
@dimasciput Any thoughts on this?

**Comment by KSnaddon** [comment]
@dimasciput I would appreciate your opinion on whether this is possible?

**Comment by dimasciput** [comment]
Hi, I think it's possible, can you create a mockup for the form?

**Comment by KSnaddon** [comment]
@dimasciput Yes I can do this

**Comment by KSnaddon** [comment]
@dimasciput Something like this:


![image](https://github.com/kartoza/django-bims/assets/91128958/2ea81e1e-c41e-4001-9f19-32cf9851baba)

**Comment by dimasciput** [comment]
@KSnaddon, thank you for the mockup. I've sized this ticket at 5 and will work on it in the next sprint.

**Comment by KSnaddon** [comment]
@dimasciput Thanks!

**Comment by dimasciput** [comment]
![image](https://github.com/kartoza/django-bims/assets/1979569/a2b281e4-56d5-46d2-870a-f59f9bea951d)

@KSnaddon, the menu is too long. We usually want the menu to be a maximum of 2 words. Can we shorten this or move it somewhere else?

**Comment by KSnaddon** [comment]
@dimasciput My suggestion was to put it alongside the Bug Report icon.  Can it fit there?

**Comment by dimasciput** [comment]
@KSnaddon, we need another icon to indicate wetland mapping feedback, so it doesn't confuse users with normal feedback. Do you have a suggestion for an icon? Perhaps Jeremy can help you.

**Comment by dimasciput** [comment]
@KSnaddon this has been added to testing site

![image](https://github.com/kartoza/django-bims/assets/1979569/6efe9f90-5484-4534-a31f-7aeb766ad2dd)

**Comment by KSnaddon** [comment]
@dimasciput This is great!  Is the icon the default "bug" icon?  We will work on that to come up with something more relevant.  

Currently, to these emails come to me only?

**Comment by dimasciput** [comment]
@KSnaddon you can change the recipients here https://testing.healthyrivers.kartoza.com/admin/bims/notification/7/change/

**Comment by KSnaddon** [comment]
@dimasciput @jeremyshelton Can we use the icons available in Office 365? Or are there proprietary issues?

We could use this one? 
![image](https://github.com/kartoza/django-bims/assets/91128958/8dbb8e06-1763-4b9d-845c-df913f3dae38)

**Comment by dimasciput** [comment]
@KSnaddon 
![image](https://github.com/kartoza/django-bims/assets/1979569/b709127b-888e-4fd9-8518-a4c024e17865)

What do you think?

**Comment by jeremyshelton** [comment]
@dimasciput here are two image file options for this if needed. 
Also, is it possible to have text appear when a user hovers over these: "SEND FEEDBACK" and "WETLAND MAP FEEDBACK" - otherwise the user might not know what these are for?

![2](https://github.com/kartoza/django-bims/assets/44292029/dbe88c4a-ac01-4fa3-8722-a26364bf33a8)

![1](https://github.com/kartoza/django-bims/assets/44292029/72118a08-d190-410f-bc0e-46c3723f91a8)

**Comment by dimasciput** [comment]
@KSnaddon @jeremyshelton @helendallas I have updated the icon and added tooltip in testing site.

**Comment by jeremyshelton** [comment]
Yup looks good. 
@dimasciput I see that there is a colour and/or transparency difference between the two.
Please can you standardise?
<img width="43" alt="Screenshot 2023-10-18 at 11 50 36" src="https://github.com/kartoza/django-bims/assets/44292029/10c41cdf-b569-49ec-a967-6b80d1a32303">

**Comment by dimasciput** [comment]
@jeremyshelton updated in testing.

**Comment by KSnaddon** [comment]
@dimasciput Thanks, looks good.

**Comment by dimasciput** [comment]
Deployed to production

**Comment by KSnaddon** [comment]
@dimasciput Looks great, thanks!
