### ISSUE TITLE
Adding Ecosystem Type as a filter

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3429]
We need to add an Ecosystem Type filter - i.e. River, Wetland, or Open Waterbody.  This needs to happen before we upload wetland data, as we are assuming that all FBIS (invert, algae and fish) data currently entered are all from River sites.

**Comment by helendallas** [comment]
@KSnaddon I have added this to the Generic upload template.

@dimasciput This filter should be added above Biodiversity Module please

![image](https://github.com/kartoza/django-bims/assets/45286876/54b513d9-6928-4442-95c2-656dd3e16a0b)

**Comment by helendallas** [comment]
@KSnaddon I unassigned myself as thesis something @dimasciput needs to do, not me, thanks

**Comment by KSnaddon** [comment]
Any chance we can colour the sites according to Ecosystem Type?  River = blue; Wetland = green; Open Waterbody = yellow.  Something like that.

**Comment by dimasciput** [comment]
> Any chance we can colour the sites according to Ecosystem Type? River = blue; Wetland = green; Open Waterbody = yellow. Something like that.

Unfortunately we can't do that at the moment, because sites can have multiple ecosystem types.

**Comment by KSnaddon** [comment]
> > Any chance we can colour the sites according to Ecosystem Type? River = blue; Wetland = green; Open Waterbody = yellow. Something like that.
> 
> Unfortunately we can't do that at the moment, because sites can have multiple ecosystem types.

I thought that each site was assigned an Ecosystem Type.

**Comment by dimasciput** [comment]
@KSnaddon 

For now, we'll assign the ecosystem type to the occurrence records, which will simplify searching, filtering, and uploads. We can revisit this if the implementation proves problematic.

Regarding the color of the sites, let's address that in the future when we modify how sites are rendered on the map. Also, it's not really related to this ticket.

**Comment by KSnaddon** [comment]
@dimasciput 
That's great, thanks.  Just to confirm though - a single site will only ever have one ecosystem type - river, wetland or open waterbody.

**Comment by KSnaddon** [comment]
@dimasciput 
This is done, so we could move this to done
