### ISSUE TITLE
We need all FBIS data to be labelled River as an Ecosystem Type

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3430]
We need to add Ecosystem Type as a new filter (see ticket #3429 ), then include Ecosystem Type as a compulsory column that a user has to populate when uploading data, both as a csv bulk upload file, and in the forms.

**Ecosystem Type should include:**

- River
- Wetland
- Open waterbody

Then all existing FBIS data  (not GBIF or VM) needs to be assigned "**River**" as Ecosystem Type.

With the exception of approx 2000 fish occurrence records which fall within "**Open waterbody"**
s"**

I will provide this xls file shortly after @jeremyshelton has checked it.

**Comment by helendallas** [comment]
@dimasciput Here is the file of occurrence records that need to be labelled Open waterbody""please. 

[FBIS Fish data OPEN WATERBODIES 4 Aug 2023.xlsx](https://github.com/kartoza/django-bims/files/12274155/FBIS.Fish.data.OPEN.WATERBODIES.4.Aug.2023.xlsx)

**Comment by dimasciput** [comment]
Hi @helendallas, this has actually only been updated in testing. I will deploy it to the live this sprint.

**Comment by helendallas** [comment]
Thanks @dimasciput Do I need to check on testing or are you happy it was successful?

**Comment by helendallas** [comment]
@dimasciput The number of record in the file attached in this email was 2014, but the number is the FBIS cdv download when Open waterbodies are selected is 1988.

I will ask Janette to check which are missing and revert

**Comment by helendallas** [comment]
@dimasciput 
Janette checked the data and added the records that were missing from the CSV file when I filtered on Open Waterbodies in the testing site. They are shaded blue below in this file.

Please can you check why these UUIDs were not reallocated to open waterbody. Thanks

[Missing Fish records from FBIS Open waterbodies.xlsx](https://github.com/kartoza/django-bims/files/12584532/Missing.Fish.records.from.FBIS.Open.waterbodies.xlsx)

**Comment by dimasciput** [comment]
@helendallas 
> Please can you check why these UUIDs were not reallocated to open waterbody. Thanks

These data does not exist in the FBIS. Did you get these data from the FBIS, or are these old data? Has it been uploaded to the FBIS?

**Comment by dimasciput** [comment]
Or perhaps this is old data that has been removed from the system. Please send the CSV upload file if this data has been uploaded to the FBIS.

@helendallas @jeremyshelton

**Comment by helendallas** [comment]
@dimasciput I don't think these data have been deleted from FBIS. I have checked some and the data are on the production site. Its is data from 6 sites.

Here is an example:

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=B8LETA-00053&siteId=65860&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=65860&orderBy=name&polygon=&dst=&ecosystemType=


Another one
https://freshwaterbiodiversity.org/site-visit/detail/4199/


Here is the xls fie. The highlighted records on the bottom were missing from the downloaded csv file when I filtered on Open Waterbodies.




[Missing Fish records from FBIS Open waterbodies.xlsx](https://github.com/kartoza/django-bims/files/12725367/Missing.Fish.records.from.FBIS.Open.waterbodies.xlsx)

**Comment by helendallas** [comment]
@dimasciput Please check the missing records

**Comment by helendallas** [comment]
@dimasciput There are now to many Open Waterbody sites. Some for the invertebrates (580 records), which is wrong. I will ask @Janette-Lumley to check fish records but number is correct.

see the map

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=Open%20waterbody

and the dashboard

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=Open%20waterbody


@Janette-Lumley Please download the csv file and check it against the one you created - see earlier in thes ticket - to make sure the missing records have been correctly renamed Open Waterbody

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=Open%20waterbody

**Comment by Janette-Lumley** [comment]
@helendallas the data I highlighted in the spreadsheet doesn't seem to exist in FBIS at all.

**Comment by dimasciput** [comment]
@helendallas @Janette-Lumley perhaps we can reupload the data?

**Comment by helendallas** [comment]
@Janette-Lumley Please check and revert.

**Comment by Janette-Lumley** [comment]
@helendallas see my previous comment, I checked and the data that I highlighted in the spreadsheet isn't in FBIS. As Dimas suggested maybe the data would need to be reuploaded or entered in?

**Comment by helendallas** [comment]
But @dimasciput There are now 580 invertebrate occurrence records that are now incorrect. This needs to be fixed.

Yes I can upload the missing fish data, but you need to sort out the invertebrates please

**Comment by helendallas** [comment]
@dimasciput I don't think re-uploading the data is the solution. I would have assumed that finding the UUID, and then labelling these UUIDs Open Waterbody instead of river would have been straightforward.

Now we have some GBIF records labelled Open Waterbody, which is incorrect
Some invert records labelled open waterbodies, which is incorrect
And not all fish records as the per original spreadsheet labelled Open waterbodies

<img width="495" alt="Screenshot 2023-10-16 at 10 32 09" src="https://github.com/kartoza/django-bims/assets/45286876/11c44b4f-bebf-4077-b53e-aa4a63f7efe2">

We have not yet added any data that is labelled Wetland or Open Waterbody.

So please can you re-assign all Data Source = FBIS to Ecosystem Type = River
Fix all GBIF records to be Ecosystem Type = Unspecified


I am going to ask @KSnaddon To do another intersect of fish data in Open Waterbodies so that we are sure we have the correct data.
Then once I get the new file from Kate, can you use the UUIDs Reassign these records to Ecosystem Type = Open Water body.


Then you need to reassign please @dimasciput

**Comment by KSnaddon** [comment]
@dimasciput @helendallas  Here is the new intersect file as a csv.  Is it best in any other format? NOTE: I did the intersect this time with only dams, reservoirs and weirs (excluding WWTWs and other smaller ponds), which explains the slightly lower number of fish occurrence records compared with last intersect.

[FBIS fish data intersect DAMS 16 Oct 2023.csv](https://github.com/kartoza/django-bims/files/12916323/FBIS.fish.data.intersect.DAMS.16.Oct.2023.csv)

**Comment by helendallas** [comment]
Thanks @KSnaddon 

@dimasciput Please can you action this asap. Please see details above of what needs to be done. And use the UUIDs provided in Kate's file to reassign these occurrence records to open waterbody.

**Comment by dimasciput** [comment]
@helendallas will do, should I test it on testing first?

**Comment by helendallas** [comment]
Not sure? How complicated is it? All GBIF data and VM needs to be unspecified ecosystem type,

All FBIS data - river ecosystem type.

Then once that is resolved, use UUIDs to rename records in xls file to open waterbody.

Happy for you to do it straight onto production, as if it is wrong again, we will just have to redo again until we get it right.

Thanks

**Comment by dimasciput** [comment]
Okay @helendallas , let me do it first thing tomorrow morning my time.

**Comment by dimasciput** [comment]
@helendallas @KSnaddon, it is being updated in production currently. It should be finished in 1 hour.

**Comment by helendallas** [comment]
Thanks @dimasciput

**Comment by dimasciput** [comment]
@helendallas @KSnaddon production has been updated, please test.

**Comment by KSnaddon** [comment]
@helendallas @dimasciput I still get all ecosystem types in the Multi-Site Overview Panel if I have selected (by lasso) only river and open waterbody sites:
![image](https://github.com/kartoza/django-bims/assets/91128958/26a49812-5b48-41e0-ac07-6cd262ef52fc)

**Comment by dimasciput** [comment]
@KSnaddon I didn't see any issues from your screenshot, the unspecified sites are orange.

**Comment by KSnaddon** [comment]
@dimasciput Look at the Filter History at the top of the Panel - all ecosystem types are listed.

**Comment by dimasciput** [comment]
@KSnaddon you also selected open waterbody
![Screenshot 2023-10-19 at 4 25 34 PM](https://github.com/kartoza/django-bims/assets/1979569/bee9e7f8-d68a-47bc-ac81-a1140bbc09a1)

**Comment by KSnaddon** [comment]
@dimasciput Yes I know that - but why does Wetland come up, that is my question.

**Comment by dimasciput** [comment]
@KSnaddon yes, filter history will show all the filters you selected

**Comment by KSnaddon** [comment]
@dimasciput OK thanks. I had always assumed that it returned the selection!
