### ISSUE TITLE
Refined Geomorphological Zone

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3435]
@dimasciput please change 'Refined Geomorphological Zone' to 'User Geomorphological Zone' throughout.

**Comment by helendallas** [comment]
@dimasciput Still needs to be changed here:

<img width="437" alt="Screenshot 2023-10-10 at 13 25 28" src="https://github.com/kartoza/django-bims/assets/45286876/2c927fa5-5c57-413e-97ca-695d18565611">

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas updated in testing

**Comment by jeremyshelton** [comment]
@dimasciput 

I think it still needs updating in the add a site dashboard:
<img width="906" alt="Screenshot 2023-10-20 at 06 41 08" src="https://github.com/kartoza/django-bims/assets/44292029/73f65d5d-dab1-4186-832e-799964e31618">

CSV downloads are not working for me on testing so I can't check it on there...

**Comment by dimasciput** [comment]
@jeremyshelton updated in testing

**Comment by helendallas** [comment]
Thanks @dimasciput 

Not yet updated in detailed dashboard
<img width="288" alt="Screenshot 2023-10-20 at 08 30 00" src="https://github.com/kartoza/django-bims/assets/45286876/67c12070-6b54-45c7-99b2-97c66ff6ca0c">

<img width="443" alt="Screenshot 2023-10-20 at 08 30 36" src="https://github.com/kartoza/django-bims/assets/45286876/5863b5be-900c-4f70-bdfc-8c7344897759">

**Comment by helendallas** [comment]
Ignore above @dimasciput Single site dashboard ticket has fixed these. Please deploy fix to production for Add site on river form, then we can close the ticket
