### ISSUE TITLE
Scale bar falling off map

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3436]
Please adjust scale bar position so that it is more visible.
<img width="228" alt="Screenshot 2023-08-14 at 12 21 31" src="https://github.com/kartoza/django-bims/assets/44292029/cf6254b2-9acf-48fb-a1de-e3c230dce99d">

**Comment by dimasciput** [comment]
Fixed in testing

**Comment by jeremyshelton** [comment]
Looks good.
Please deploy to production.

**Comment by helendallas** [comment]
Deployed, closing ticket
