### ISSUE TITLE
Upload of National Wetland Map 6

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3437]
@dimasciput   NWM6 needs to be uploaded to FBIS. 

The boundary lines for the wetlands layer (when I looked at it on the Test Site) are too wide - can we reduce them so that the wetlands don't look so large? Perhaps the same width as the river lines.

**Comment by helendallas** [comment]
@KSnaddon Where is this layer ? Is it already on geoserver or wherever it needs to be in order for it to be visualised in FBIS. Please provide more details on what still needs to happen.

**Comment by KSnaddon** [comment]
@helendallas The map was already uploaded onto the Test Site by Kartoza, so I have made the assumption that they still have it and that it is loaded on GeoServer.   Adwoa from SANBI was dealing directly with Kartoza on this.  @amyburness and @dimasciput - please let me know if there is anything information that you still require.

**Comment by amyburness** [comment]
@KSnaddon what is the name of the Layer?

**Comment by KSnaddon** [comment]
Title is "National Wetland Map"

**Comment by helendallas** [comment]
@dimasciput The NWM is not on production yet. Please action soonest

**Comment by amyburness** [comment]
Done 
![image](https://github.com/kartoza/django-bims/assets/77841514/4e3ed357-31a2-47cf-b825-f59eb24b5a94)

**Comment by helendallas** [comment]
Thanks @amyburness 
No metadata yet and @KSnaddon please confirm attributes when clicking on the map are correct. Thanks

**Comment by KSnaddon** [comment]
@amyburness The Abstract for the Wetland Map is not showing.  Do you know why this might be?

**Comment by helendallas** [comment]
Closing ticket. Abstract is there now
