### ISSUE TITLE
South African National Land-Cover 2018 (SALC 2018) or similar as a basemap choice

### ISSUE THREAD

**Issue by MikeSilberbauer** [kartoza/django-bims#3439]
Are there any plans to include a Land Cover dataset as a base layer in FBIS? (e.g. from https://egis.environment.gov.za/)
Users find this helpful for identifying catchment activities that may be affecting water quality and aquatic biota.

**Comment by helendallas** [comment]
@KSnaddon Please confirm which land cover layer was decided on by the Wetland team. Please can we action getting it on the FBIS and removing the LADA land use cover. Is this something you and or Adwoa can do?

**Comment by KSnaddon** [comment]
Yes, we are onto this.  The best map is one that SANBI has put together.  We will be able to upload this for publishing probably quite soon.

**Comment by MikeSilberbauer** [comment]
Just for interest, which dataset did you decide to use?

**Comment by KSnaddon** [comment]
It's based on the NLC 2020, but with some classes amalgamated to match the classes used in Wet-Health assessments. I can get you more details.

**Comment by MikeSilberbauer** [comment]
Thank you, I have spent the last week or so working with the NLC 2020 and the suggested amalgamating palettes from https://egis.environment.gov.za/gis_data_downloads for simplifying the data when zoomed out. After a bit of a learning curve getting it to plot using standard colour schemes in R it looks very useful. I would be interested in seeing the class groupings that you will be using.

**Comment by KSnaddon** [comment]
@dimasciput or @amyburness How do I load a raster layer to the SANBI schema?  I want to publish the NLC 2020 land cover dataset.

**Comment by MikeSilberbauer** [comment]
Please see https://egis.environment.gov.za/sa_national_land_cover_datasets and https://egis.environment.gov.za/gis_data_downloads

**Comment by KSnaddon** [comment]
@dimasciput I just sent you a Dropbox link for the Land cover dataset.

**Comment by dimasciput** [comment]
this has been added thanks to @amyburness 
![image](https://github.com/kartoza/django-bims/assets/1979569/7c574e0f-fce3-4306-a2eb-d6d408f1675f)

**Comment by MikeSilberbauer** [comment]
1. The latest available land cover is now SANLC 2020 (https://egis.environment.gov.za/sa_national_land_cover_datasets). Apparently CSIR, GeoTerraImage and the government departments of forestry fisheries & environment, and agriculture, land reform & rural development plan to update the land cover data more frequently, so a standard process for updating the base layer on FBIS might be necessary. [SA_NLC_2020_Technical_Presentation_Mark_Thompson.pdf](https://github.com/kartoza/django-bims/files/14647117/SA_NLC_2020_Technical_Presentation_Mark_Thompson.pdf)

3. I support the suggestion of displaying the landcover (or "land-use") class name when you click on the map.
4. The colours used should be those in the colour table provided with the image file.

![image](https://github.com/kartoza/django-bims/assets/9193968/aaa70882-c3ec-40e2-8741-99738d0f7a01)

**Comment by helendallas** [comment]
Thanks @MikeSilberbauer 

@amyburness Please can you pursue and update as suggested by Mike. And explore option to automate going forward. Thanks

**Comment by KSnaddon** [comment]
@amyburness and @dimasciput It should have been the NLC 2020, which I shared with Dimas. 

@amyburness I have just shared the same link with you.

**Comment by KSnaddon** [comment]
I agree that the Class should come up on the map, and get rid of the legend.  I had assumed that the palette / style is associated with the layer.

**Comment by dimasciput** [comment]
Ah, I just used the title of this ticket for the layer name, we can change that from admin page.

**Comment by KSnaddon** [comment]
Thanks Dimas - that's a relief!  Will you make that change?

**Comment by MikeSilberbauer** [comment]
[The 73 land-use classes available in the 2020 dataset with SALCC_1 SALCC_2.xlsx](https://github.com/kartoza/django-bims/files/14648873/The.73.land-use.classes.available.in.the.2020.dataset.with.SALCC_1.SALCC_2.xlsx)
Sorry about the confusion with the original title of the ticket: At that stage I had not started working with the 2020 data.
In case you need to verify the colours and classes embedded in the raster file, I have made my own lookup table of class names with hex and RGB colours. The table includes the level 1 and 2 aggregated classes, which are useful if you want to generalise the view at different scales.

**Comment by KSnaddon** [comment]
Thanks Mike, that's useful to have!

**Comment by helendallas** [comment]
@KSnaddon Please check and close ticket if this is all sorted, thanks

**Comment by KSnaddon** [comment]
@dimasciput I have changed the title of the layer to SANLC 2020, and added an abstract in GeoServer.  

@amyburness Please can you let me know which style file you used for the layer that you published?  I don't have access to the Kartoza workspace to figure this out.

**Comment by dimasciput** [comment]
@KSnaddon @helendallas I have updated this on production, could you check it again please
![image](https://github.com/kartoza/django-bims/assets/1979569/8284b018-9343-4712-b6d3-78f03028d3d5)

**Comment by KSnaddon** [comment]
@dimasciput This looks correct, thanks.

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket

**Comment by MikeSilberbauer** [comment]
Looks good, thank you!
