### ISSUE TITLE
The spatial layer I button is not opening up the metadata

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3440]
The clicking of the I no longer opens up the metadata for any of the layers.

Please investigate urgently

<img width="332" alt="Screenshot 2023-08-16 at 09 15 43" src="https://github.com/kartoza/django-bims/assets/45286876/c2d47b62-5e52-429a-847a-1ac4c173609a">

**Comment by dimasciput** [comment]
Fixed in testing site

**Comment by helendallas** [comment]
Fixed in production as well, closing ticket
