### ISSUE TITLE
We need to add a new way to name a site in a wetland

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3441]
@dimasciput Please read below and advise if it possible to have two ways of naming a site, thanks. This is quite an important issue so hopefully it is possible.

At the moment we have automated the naming process for sites on rivers:

<img width="552" alt="Screenshot 2023-08-16 at 09 21 58" src="https://github.com/kartoza/django-bims/assets/45286876/daeaac31-ce23-47ff-8ee7-866300f901fc">

Now that were are including other ecosystem types, we need to introduce a second way of naming sites in wetlands.

**This needs to be as follows:**

Site code = quaternary catchment + 1st four letters of the User wetland name, e.g. U22GRiet-000005 (6 digit number) 
 - @KSnaddon Please confirm if the quaternary catchment is derived from quaternary catchment spatial layer or a column in the NWM6.

Then @dimasciput - going forward, all incoming occurrence data needs to be assigned one of three ecosystem types (as per ticket #3430 )

- If data are River: then the Site Code generated is as per river (current one)
- If the data are Wetland: then the site code generated is as per the new one above
- If the data are Open waterbody: @KSnaddon We need to decide which to use? river or wetland

**Comment by KSnaddon** [comment]
The quaternary catchment is provided as an attribute in the Wetland Map.  It has been assigned according to the dominant quaternary in which the wetland lies.

@dimasciput - we can probably use only a 5 digit number after the 4 letters of the wetland name.  We are unlikely to have more than 100 000 sites in one wetland.

I am consulting on the Open Waterbodies site code issue, and will report back.

**Comment by KSnaddon** [comment]
@dimasciput We would like to propose a slightly altered Site Code protocol for Wetlands: Quat Catch - User Wetland Name or Wetland Map name (if no User name) (4 letters) - 4 digit number, such as U22G-Riet-0001.

For Open Waterbodies, we suggest using the same method as above, as generally, waterbodies will have a name used by the User, or even in the Wetland Map.

It should be noted that there are Open Waterbodies included in the Wetland Map. So a user might add an Open Waterbody site to a mapped Wetland.  This is not a problem.

**Comment by helendallas** [comment]
Thanks @KSnaddon Please can you confirm exactly where each of these must be derived.....NWM? and which columns

**Comment by KSnaddon** [comment]
Quat catchment = derived from NWM6 = attribute is called "Quaternary" (NOTE: there are 226 wetlands without a quaternary - I need to check why this is with SANBI, but may be where a decision still needs to be made where a wetland crosses more than one quat)

User name = input by the user (use the name from NWM6 if no name entered by User = attribute is called "Name")

Number = generated by FBIS

**Comment by dimasciput** [comment]
@KSnaddon 

> User name = input by the user (use the name from NWM6 if no name entered by User = attribute is called "Name")


What if the name of the layer is also empty? There are some geometries that don't have a 'name' : 

<img width="829" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/4ecba962-1d65-4d7c-8961-352afc6da861">

**Comment by KSnaddon** [comment]
@dimasciput 
Ideally the user must put in a name - perhaps that needs to be made explicit, i.e. add the words (something like)  "User must specify a wetland name if one is not provided by the Wetland Map"

**Comment by helendallas** [comment]
Some comments re the Add Wetland form: @dimasciput Please make sure it is as similar to Add river as possible, so we need:

Add: Fetch Wetland Name
G21F-**kate**-00001. _ please make name uppercase KATE
Add: Fetch data next to hydrogeomorphic zone



<img width="1130" alt="Screenshot 2023-09-08 at 11 28 41" src="https://github.com/kartoza/django-bims/assets/45286876/421e552a-c3c8-41f8-9247-7f39de4ce4b4">
<img width="1136" alt="Screenshot 2023-09-08 at 11 28 54" src="https://github.com/kartoza/django-bims/assets/45286876/60b023a2-de5a-4580-a027-7aaf0654373d">

**Comment by dimasciput** [comment]
@helendallas yes I haven't deployed it to production yet, all the wetland features

**Comment by helendallas** [comment]
Thanks closing ticket
