### ISSUE TITLE
Managing who receives emails from FBIS site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3444]
At the moment, multiple users receive an email when 

- Site visit is ready to be validated
- Download request notification
- Account created email notification
- SASS created email notification

and an email is sent to the following emails. 
 
[fbis@frcsa.org.za](mailto:fbis@frcsa.org.za); [dimas@kartoza.com](mailto:dimas@kartoza.com); [amyburnessenviro@gmail.com](mailto:amyburnessenviro@gmail.com); [jeremy@frcsa.org.za](mailto:jeremy@frcsa.org.za); [janette@frcsa.org.za](mailto:janette@frcsa.org.za); [katesnaddon@telkomsa.net](mailto:katesnaddon@telkomsa.net); [helen@frcsa.org.za](mailto:helen@frcsa.org.za); [janette@frcsa.org.za](mailto:janette@frcsa.org.za); [aneri@frcsa.org.za](mailto:aneri@frcsa.org.za); [addloe@gmail.com](mailto:addloe@gmail.com); [helen@frcsa.org.za](mailto:helen@frcsa.org.za); [dimas.ciputra@hotmail.com](mailto:dimas.ciputra@hotmail.com); [jeremy@frcsa.org.za](mailto:jeremy@frcsa.org.za)
 
Not sure why some are duplicated? or why everyone above needs to receive them.
 
We need a way to manage who receives one or many of these email notifications. For e.g. Aneri has left so shouldn’t receive an email.

In the future, a specific admin person may be the validator of new plant occurrence records, and we need to be able to assign this person.

**Comment by dimasciput** [comment]
You can manage this here https://testing.healthyrivers.kartoza.com/admin/bims/notification/

**Comment by helendallas** [comment]
Thanks @dimasciput I see this is deployed to live. I will close ticket
