### ISSUE TITLE
Wetland dashboards

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3448]
I have put together a pdf (link to the Word doc also provided here) with the work flow for tailoring the existing dashboards and panels for entry of wetland data.  I have moved through all the various panels, from "adding a site" through to the Pesticide Dashboard, making notes on what will remain the same and what should change.

text in green = where text is changed or tailored for wetlands
text in orange = suggested changes for ALL ecosystem types
text in purple = questions and issues for discussion

@jeremyshelton, @helendallas  - Please check that this makes sense.  
@dimasciput - Please let me know if anything doesn't make sense.  There are some issues / questions that may need some discussion.  I know this is a lot of information, which may be best split into different tickets, but we can work that out as we go.

[FBIS Work Flow for Wetland Dashboards 22 August 2023.docx](https://github.com/kartoza/django-bims/files/12409780/FBIS.Work.Flow.for.Wetland.Dashboards.22.August.2023.docx)
[FBIS Work Flow for Wetland Dashboards 22 August 2023.pdf](https://github.com/kartoza/django-bims/files/12409782/FBIS.Work.Flow.for.Wetland.Dashboards.22.August.2023.pdf)

**Comment by dimasciput** [comment]
hanks, @KSnaddon,

There will be many changes to the current site, so I've sized this ticket at 40. This means it will take at least 4 days to complete on the development side.

<img width="364" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/831a7cb8-0b7a-4b63-a053-eedcec25674e">

Please ensure that this data is available in both geocontext and geoserver.

Perhaps it would be better to split the tickets for more effective tracking of progress.

@jeremyshelton @helendallas

**Comment by jeremyshelton** [comment]
**Please ensure that this data is available in both geocontext and geoserver.**
@KSnaddon maybe it will be helpful to create another ticket with a matrix of all of the new wetland-linked layers and filters to help track their progress? We can update it as Amy and Admire work through them. This will help @dimasciput know which are ready and available on geocontext and geoserver?

**Perhaps it would be better to split the tickets for more effective tracking of progress.**
This will equate to approx 10 tickets, which is quite a lot to keep track of. What if we leave it as 1 ticket for now (as. means of keeping everything in one place), and set up a matrix (similar to the above) to help us keep track of the progress on the different facets? @timlinux thoughts?

**Comment by KSnaddon** [comment]
I will also put together a table showing the link to the relevant layer.

We can generate tickets as issues come up, and keep this main one as the "mother of all tickets"??

**Comment by KSnaddon** [comment]
Please ensure that this data is available in both geocontext and geoserver. - please see ticket #3453

**Comment by helendallas** [comment]
Closing ticket as some aspects have been completed and others have been ticketed separately
