### ISSUE TITLE
Upload of 3 layers for wetland attributes

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3453]
3 new layers need to be uploaded in order to be able to provide data for the single and multi-site dashboards.

1. Rainfall intensity zones (sanbi:Rainfall_Intensity) - is on GeoServer, not GeoContext yet
2. Mean Annual Precipitation zones (sanbi:MAP_zones) - on GeoServer, not on GeoContext yet
3. Inherent Runoff Potential - not properly on GeoServer yet, I think the layer is too big, and only half of it loads onto GeoServer (sanbi:Soil_runoff_potential_SCS).

@dimasciput  I will let you know when they are all up on GeoContext.

**Comment by NyakudyaA** [comment]
@KSnaddon Can you share the big layer and I will upload it for you

**Comment by KSnaddon** [comment]
@NyakudyaA 
Thanks Admire!  I have shared the Dropbox link with you via your email address.

**Comment by KSnaddon** [comment]
@NyakudyaA  can you please check on GeoServer and GeoContext to see if I've added the 2 layers (Rainfall Intensity Zones and MAP zones) correctly? The group is called Rainfall Zones (on GeoCOntext), and they are both on the sanbi store.

**Comment by KSnaddon** [comment]
Thanks!

**Comment by dimasciput** [comment]
@KSnaddon I'm going to add these data to geocontext, and then harvest them in production site. So in the next sprint I will have the data ready for the dashboard.

**Comment by KSnaddon** [comment]
@dimasciput Thanks.  I got this far with all 3 layers in GeoContext:

![image](https://github.com/kartoza/django-bims/assets/91128958/ee8c0832-3bd9-4fb2-9811-940ea39bf021)

Can you check that I loaded them onto GeoContext correctly?

**Comment by KSnaddon** [comment]
@dimasciput Did you manage to locate these 3 layers on GeoContext / GeoServer?

**Comment by KSnaddon** [comment]
@dimasciput These layers don't need to be visual layers, but just context layers for adding data for wetlands in the panels and dashboards.

**Comment by KSnaddon** [comment]
@dimasciput Please can you check these 3 layers that are on GeoContext.  Location sites need to be updated to include these 3.

**Comment by helendallas** [comment]
@dimasciput to check that layers are available in BIMS

**Comment by dimasciput** [comment]
@helendallas @KSnaddon only rainfall layer is broken in geoserver.

**Comment by helendallas** [comment]
Lest close this ticket now as everything is sorted except rainfall intensity which @KSnaddon has created another ticket for.

See #3549
