### ISSUE TITLE
Add biodiversity data - wetland

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3454]
<img width="768" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/6df32131-af30-4012-950d-70f3ab2a9d1a">

@KSnaddon what are the options for these fields?
- Hydrogeomorphic Type (User?)
- Broad Biotope / Habitat
- Hydroperiod

**Comment by dimasciput** [comment]
child of #3448

**Comment by KSnaddon** [comment]
@dimasciput The dropdown options for this are in the upload template below:

[Revised Generic Data Upload Template with latest dropdowns 2023_08_15.xlsx](https://github.com/kartoza/django-bims/files/12426096/Revised.Generic.Data.Upload.Template.with.latest.dropdowns.2023_08_15.xlsx)

Would you like me to show which ones were added specifically for wetlands?

**Comment by KSnaddon** [comment]
For clarity, the relevant columns in the Excel template are:

- Hydrogeomorphic Type (User?) = User hydrogeomorphic type 
- Broad Biotope / Habitat = Broad biotope (I would like to see this changed to Broad biotope / habitat in the template - @helendallas)
- Hydroperiod = Hydroperiod

**Comment by dimasciput** [comment]
Thanks, so only two new fields for the add occcurrence data : 
- User hydrogeomorphic type
- Hydroperiod

And should we update 'Broad Biotope' to 'Biotope / Habitat' for all ecosystem types?

@KSnaddon

**Comment by dimasciput** [comment]
@KSnaddon, don't you think the `User hydrogeomorphic type` should be assigned to the site, rather than on this form? Or could a site have multiple hydrogeomorphic types?

**Comment by KSnaddon** [comment]
> @KSnaddon, don't you think the `User hydrogeomorphic type` should be assigned to the site, rather than on this form? Or could a site have multiple hydrogeomorphic types?

@dimasciput That's a good point.  It should be assigned to a site when a user adds a wetland site, yes.  I added this to the upload template, as for RIvers, there is a column for "Refined Geomorphological Zone", so I assumed we needed this here too.

**Comment by KSnaddon** [comment]
> Thanks, so only two new fields for the add occcurrence data :
> 
> * User hydrogeomorphic type
> * Hydroperiod
Yes, that seems  right.

> And should we update 'Broad Biotope' to 'Biotope / Habitat' for all ecosystem types?


I would like that, as wetlanders don't often use the word biotope.  @helendallas Are you ok with that?  I think we did discuss it.
>

**Comment by dimasciput** [comment]
> @dimasciput That's a good point. It should be assigned to a site when a user adds a wetland site, yes. I added this to the upload template, as for RIvers, there is a column for "Refined Geomorphological Zone", so I assumed we needed this here too.

No, these data are for site visit. That's why there's no geomorphological zone included either. Okay, I won't add this field here.

**Comment by KSnaddon** [comment]
Agreed

**Comment by KSnaddon** [comment]
[Single site overview - wetlands - attributes.docx](https://github.com/kartoza/django-bims/files/12426986/Single.site.overview.-.wetlands.-.attributes.docx)

@dimasciput I have provided the relevant spatial layers and attribute name (in bold) for the various details that would appear on the single site biodiversity data panels for wetland data.  

![image](https://github.com/kartoza/django-bims/assets/91128958/561327ec-49ac-4a27-b079-790ee67a8a6c)

**Comment by dimasciput** [comment]
@KSnaddon, as discussed in our last meeting, the spatial filter will be added from the admin page. Both the wetland and other sites will have the same information. This isn't related to this ticket. Can you please review if we can now add biodiversity data to the site?

**Comment by KSnaddon** [comment]
> Can you please review if we can now add biodiversity data to the site?

@dimasciput I'm not sure what you are asking here?

**Comment by helendallas** [comment]
@KSnaddon There is quite a lot of different issues in this ticket. I suggest we close this one and capture specifics in separate tickets. Some you and I will be able to do ourselves. Others we may need @dimasciput to action.

@dimasciput  Kate and I will meet to discuss and revert.

**Comment by helendallas** [comment]
Closing this ticket and creating a new one that is more focused on single site dashboard. Please see ticket #3518
