### ISSUE TITLE
Multiple site dashboard - wetland

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3455]
@KSnaddon @jeremyshelton @helendallas 

<img width="726" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/c35a7a44-ec5e-4f67-91f6-8e7a07d1dc56">

I believe we can accomplish this by adding a wetland to the spatial filter and then simply including the ecosystem type in the site visit data. What are your thoughts?

**Comment by dimasciput** [comment]
child of #3448

**Comment by KSnaddon** [comment]
@dimasciput Yes, I am suggesting that users specify "Ecosystem Type" when a site is added. 

So you are saying that a user would search for a wetland (through lasso or the wetland name / code) then the multi-site dashboard would provide all sites (in the list of "Site Visit Data"), with Ecosystem Type specified as an attribute? Or are you saying that only the wetland sites would be provided?

**Comment by KSnaddon** [comment]
@dimasciput Is it possible to select a wetland by clicking on it on the map?

**Comment by dimasciput** [comment]
> So you are saying that a user would search for a wetland (through lasso or the wetland name / code) then the multi-site dashboard would provide all sites (in the list of "Site Visit Data"), with Ecosystem Type specified as an attribute? Or are you saying that only the wetland sites would be provided?

Yes the ecosystem type will be added in the new column here 

<img width="462" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/33f46740-d48f-4b96-915a-63a1562bedba">

**Comment by KSnaddon** [comment]
> > So you are saying that a user would search for a wetland (through lasso or the wetland name / code) then the multi-site dashboard would provide all sites (in the list of "Site Visit Data"), with Ecosystem Type specified as an attribute? Or are you saying that only the wetland sites would be provided?
> 
> Yes the ecosystem type will be added in the new column here
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/1979569/262914765-33f46740-d48f-4b96-915a-63a1562bedba.png">

Perfect, thanks

**Comment by KSnaddon** [comment]
> > @dimasciput Is it possible to select a wetland by clicking on it on the map?
> 
> It's not possible at the moment. This will be a new feature that will probably take 1-2 days to implement. What do you think?

@dimasciput I will check with Helen and get back to you on this.  It would be very useful I think.  But may just need to go on the backburner for now.

**Comment by dimasciput** [comment]
Great thanks, 

I wanted to update you regarding the "add site" functionality. 
Currently, when adding a wetland site, you need to select the wetland layer. It's not like other ecosystems where you can simply place a point on the map. I've implemented this method, but I can modify it if you prefer a different approach.

Here's the example : 

https://github.com/kartoza/django-bims/assets/1979569/797a1fbe-d7e3-4537-bb79-87ef62cc1028

**Comment by KSnaddon** [comment]
@dimasciput  This looks great, however, users will still want to add a point (site) within the wetland.  How will this be done?

**Comment by KSnaddon** [comment]
@dimasciput Ideally, users can add information for the whole wetland (as you have it in the example) but also for a site within a wetland.  The site code that we suggested (quat catch - name - number) is for a site, and not for the whole wetland.

**Comment by dimasciput** [comment]
> @dimasciput Ideally, users can add information for the whole wetland (as you have it in the example) but also for a site within a wetland. The site code that we suggested (quat catch - name - number) is for a site, and not for the whole wetland. Helen suggested that we concentrate on being able to add a site within a wetland first, then look at adding the functionality of adding data for a whole wetland.

So not site codes for the whole wetland data? 
Okay let me save this for later, and just use the point for now.

**Comment by KSnaddon** [comment]
Yes, for now users will add a site as a point to a wetland polygon.  The single site overview panel for that site will provide summary information for the whole wetland polygon. Hope that makes sense.

But please keep this for later, as we will pick this up.

**Comment by helendallas** [comment]
@ks Further discussion is needed on this and we need to asses best use of Dimas remaining time. I am not clear what is required here.

**Comment by helendallas** [comment]
Closing ticket as revised in tickets #3673
