### ISSUE TITLE
Download occurrence data not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3464]
When I tried to download a civ file I got this message

<img width="629" alt="Screenshot 2023-09-08 at 11 56 52" src="https://github.com/kartoza/django-bims/assets/45286876/952a7b2b-c0b5-4332-ab88-1c7eb59a09c1">

**Comment by dimasciput** [comment]
This is fixed

**Comment by helendallas** [comment]
Thanks @dimasciput
