### ISSUE TITLE
We need to be able to colour code sites 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3466]
By for e.g

by ecosystem type

Se #3414

**Comment by dimasciput** [comment]
<img width="180" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/e64df8d5-7108-4c55-88e6-44e479bc3f6f">

Updated in production

**Comment by helendallas** [comment]
Thanks @dimasciput but the sites don't filter by ecosystem site - they are all still visible even when only one is selected.
I also think the colours should be more distinguishable

<img width="1234" alt="Screenshot 2023-09-18 at 09 27 35" src="https://github.com/kartoza/django-bims/assets/45286876/2dbb0a51-e628-4e2a-b1f8-734ebbf72d46">

<img width="1191" alt="Screenshot 2023-09-18 at 09 30 02" src="https://github.com/kartoza/django-bims/assets/45286876/849d5bb5-f5e1-44c0-834b-54170f225850">

**Comment by dimasciput** [comment]
@helendallas please try it again.

**Comment by helendallas** [comment]
Ok filters working but colours not great.

Please make 
River: Yellow with black outline (as before)
Wetland: green with black outline (as it is in the testing site)
Open waterbody: Dark green with white outline???  these disappear when I zoom in

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

- Site filtering not working for me - when I uncheck wetland ecosystem type, no sites disappear?
- I think that we should keep to the FBIS colour palette. 
- I agree with Helen's suggestion: Yellow = river, Blue = wetland, Green = open waterbody, Red/orange = unspecified (GBIF/VM)
- Maybe we use FBA618 for unspecified (GBIF/VM)?

![FBIS_Colours](https://github.com/kartoza/django-bims/assets/44292029/ffb210b5-0838-48e9-844c-ae3337e846ff)

**Comment by KSnaddon** [comment]
I'd like to suggest we stick with green for wetland and blue for open waterbody, as that makes more sense?  Rivers stay yellow.

**Comment by helendallas** [comment]
@KSnaddon @dimasciput Happy with suggestions, river yellow, wetland green, blue open waterbody and FBA618 for unspecified (GBIF/VM)

**Comment by KSnaddon** [comment]
@dimasciput @helendallas   If we haven't actually added any wetland occurrence data yet, how are there so many wetland sites? I don't think that all sites that happen to land in a wetland should be called wetland sites?  We have to acknowledge that the wetland map is not 100% accurate, and neither is the river map.  So users will themselves know if it's a wetland or river, and FBIS doesn't get to decide which.  Same for Open Waterbodies.

**Comment by helendallas** [comment]
@KSnaddon Dimas hasn't changed the colour coding yet. There are no wetland sites and only the open waterbodies. Apply the filter

**Comment by helendallas** [comment]
@dimasciput Just a note fyi. The coding is wrong and misleading and really we should have got it correct on testing before rolling out to production.

Colours are not correct, but also the filter doesn't not work for wetlands which has zero sites, but the dots are still showing.

For future please let's stick to checking it is working on testing before deploying to live. Thanks


Same applies to ticket #3430 . Phase see ticket as some sites have not been correctly assigned. We need to know why.

**Comment by dimasciput** [comment]
@helendallas Hi, I have reverted back the color in production site. Will update the testing site instead.

**Comment by jeremyshelton** [comment]
OK @dimasciput - let us know when you are ready for us to test it on the testing site.

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton can we add "unspecified" to the ecosystem type options? This is for gbif and museum data.

**Comment by jeremyshelton** [comment]
@dimasciput yes.

**Comment by helendallas** [comment]
Agreed

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton @KSnaddon please test it again on testing site

**Comment by helendallas** [comment]
Open water body and Unspecified are very hard to see on the map

**Comment by KSnaddon** [comment]
@dimas This looks good.  Zoomed out, the yellow and orange are a bit close in colour.  But I assume it will look different on the Pblic Site?

Agree with @helendallas . Can the colours be made a bit brighter?

**Comment by KSnaddon** [comment]
@dimasciput Also, the Multi sites overview for Open waterbodies after a filter for this has a glitch in the Ecosystem Type:

![image](https://github.com/kartoza/django-bims/assets/91128958/01b1846a-60e8-4ecc-aef1-06b7e859ad69)

**Comment by KSnaddon** [comment]
@helendallas Good idea

**Comment by helendallas** [comment]
Also a different issue but related: We need to be able to update Ecosystem Type on the Site form for existing sites.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas @KSnaddon 

I think it looks a bit strange having different colour outlines for the different categories. 
For me the black outline (as per the production site at present) is clearest. 
How about this colour scheme?
These should be easy enough to distinguish on the map.... 

<img width="398" alt="Screenshot 2023-09-28 at 12 44 17" src="https://github.com/kartoza/django-bims/assets/44292029/b5ac8cc8-e7d4-41be-8c1b-c248d3e96986">

**Comment by helendallas** [comment]
Works for me

**Comment by KSnaddon** [comment]
Looks good

**Comment by dimasciput** [comment]
Updated @jeremyshelton @helendallas @KSnaddon 

<img width="1284" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/680445e4-f4df-4726-9600-e4e9fb6e2748">

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Seeing it on the map, I think that the red is a little jarring. 
Can we please adjust as per below?

Also, do you control the order of the layers? If so can we have rivers at the front, then wetlands, then open water, then unspecified in that order. Thanks

<img width="371" alt="Screenshot 2023-09-29 at 06 33 16" src="https://github.com/kartoza/django-bims/assets/44292029/c0497960-0b0c-492e-8809-15a8dae2ceee">

**Comment by KSnaddon** [comment]
@jeremyshelton The rivers may obscure the (fewer) wetland and open waterbody sites if they are on top?

**Comment by jeremyshelton** [comment]
@KSnaddon @dimasciput agreed. 
So then the order should be: Wetland, Open water, River, Unspecified.
Thanks

**Comment by dimasciput** [comment]
@jeremyshelton @KSnaddon I have updated the styles based on the feedback.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
However sites are not loading on testing site anymore?

**Comment by jeremyshelton** [comment]
@dimasciput I'm thinking we should replace the river  legend with the sites legend.
The current river legend is not useful because all river lines look the same. 
However it would be very useful for the viewer to see the site legend when they arrive at the site.
Thoughts @helendallas @KSnaddon ?

**Comment by KSnaddon** [comment]
Completely agree!  Good idea.

**Comment by helendallas** [comment]
@dimasciput Agreed, thanks

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas @helendallas I've added the legend in testing

**Comment by helendallas** [comment]
@dimasciput Sites not showing again

**Comment by dimasciput** [comment]
@helendallas can you try it again, also the sites are little bit slow

**Comment by jeremyshelton** [comment]
@dimasciput the legend looks great, but the sites on the map are not loading for me.

**Comment by dimasciput** [comment]
@jeremyshelton it's loading fine for me, try hard refresh and then wait for 10-15 seconds

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton 

<img width="1174" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/e9e6cd6e-bf1e-48b5-99f5-bf835f16742d">

**Comment by helendallas** [comment]
Nope @dimasciput Nothing working for me. Tried hard refresh several times.still no sites

**Comment by dimasciput** [comment]
@helendallas, make sure the site is selected. Did you wait for 15 seconds on the map?

<img width="1370" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/73fbf153-9d39-4b62-ae57-b4b4ae0a8dad">


What browser are you using?

**Comment by jeremyshelton** [comment]
> @helendallas @jeremyshelton
> 
> <img alt="image" width="1174" src="https://user-images.githubusercontent.com/1979569/273128144-e9e6cd6e-bf1e-48b5-99f5-bf835f16742d.png">

Copy that 👍

**Comment by dimasciput** [comment]
@helendallas, @jeremyshelton, let me restart the geoserver to see if it works for you

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput

**Comment by KSnaddon** [comment]
@dimasciput Sites loading OK for me now.  Legend visible on Test Site.

**Comment by dimasciput** [comment]
@KSnaddon, @jeremyshelton, @helendallas, I've made some updates to improve the loading of the sites. It's still slow, but it should be more stable. Please wait for 30 minutes.

**Comment by KSnaddon** [comment]
@dimasciput Test site or Production?

**Comment by KSnaddon** [comment]
@dimasciput The Test site works perfectly for me, with colour coding and legend.

IF I select (lasso) multiple sites, the Ecosystem Type list all four of the types (i.e. River, Wetland, Open waterbody and Unspecified).  Are you still working on that?

**Comment by KSnaddon** [comment]
Sorry, wrong ticket for that comment.

**Comment by helendallas** [comment]
Closing ticket - deployed to production

**Comment by jeremyshelton** [comment]
@dimasciput can you please deploy the site colour code legend to the production site?
Thanks
<img width="1526" alt="Screenshot 2023-10-13 at 10 05 24" src="https://github.com/kartoza/django-bims/assets/44292029/3a7a3b2f-4447-4812-90e2-0252d2e545da">

**Comment by dimasciput** [comment]
@jeremyshelton already did, just hard refresh your browser

**Comment by jeremyshelton** [comment]
@dimasciput OK got it.
Can you make it so that the default is that the legend is displayed when a user arrives on the map?

**Comment by dimasciput** [comment]
@JeremyShelton, by default, the legend is open when you access the site for the first time. If you hide it, the setting will be saved. Try opening it in a new browser to see.

**Comment by dimasciput** [comment]
@jeremyshelton, can we close this ticket? If you have any new feature requests, we can create a new one.

**Comment by jeremyshelton** [comment]
@dimasciput OK got it.
Yes, closing ticket (again :)
