### ISSUE TITLE
A user needs to be able to upload a photo of an occurrence record

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3469]
At the moment, only photos of the site can be uploaded to FBIS, as well as photos of a taxon - via admin.

Users need to be able to add a photo of an occurrence record, as recorded in the field - this needs to be for on the App and well as the FBIS platform.

So for the App, one adds an Observed Taxon, click the box, then can there be an option next to this to say: "Add Photo" 

Similarly in the FBIS platform, can you add an option to Add Photo on the right of the "Abundance" etc.

<img width="1219" alt="Screenshot 2023-09-11 at 12 27 38" src="https://github.com/kartoza/django-bims/assets/45286876/7a21d01b-ee8c-46c1-8223-6e4200c3ff97">

@jeremyshelton fyi

**Comment by jeremyshelton** [comment]
@dimasciput Ideally the user would be able to add up to 3 images per record if possible.
