### ISSUE TITLE
Problem with Validate records

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3470]
When I click Validate, it does not then confirm validation and go back to Validate records page
 Gets stuck here

<img width="704" alt="Screenshot 2023-09-11 at 15 26 59" src="https://github.com/kartoza/django-bims/assets/45286876/c1cc836d-b8a9-4091-848f-c9eaff8574c1">

**Comment by dimasciput** [comment]
updated in testing

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good. I appreciate the extra notification on the top of the form. Please deploy to production
