### ISSUE TITLE
Veg bioregions layer has been deleted from GeoServer

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3475]
@amyburness SA Veg Bioregions layer is no longer on GeoServer.  I would like to edit the Abstract but can't find it

**Comment by amyburness** [comment]
It could be permissions are you happy to meet some time tomorrow and discuss the few issues further?

**Comment by KSnaddon** [comment]
Yes, I did reply to your email. I can meet at 2pm?

Thanks for sorting out the Bioregions!! I was going a bit crazy ...
