### ISSUE TITLE
Metadata abstracts missing from these layers

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3485]
Several layers in FBIS do not have associated abstract metadata information when clicking the " i "

- Geomorphological Zones
- Sub Water Management Areas
- Strategic Water Source Area - Surface (it was there but now disappeared)
- SA Provinces and SADC  boundaries
- Pesticide Use (kg/ha)
- National Wetland Map 6 beta

NFEPA river FEPAs 2011 - this is extremely long and doesn't fit within area - suggest reducing and providing link

**Comment by helendallas** [comment]
Here is the one to be added for 

**Geomorphological Zones**

Geomorphological zones for all rivers were generated using Digital Elevation Model (DEM): 90m x 90m resolution Shuttle Radar Topography Mission (SRTM). This is a preliminary classification where slope has been used to classify the rivers using slope classes based on Rowntree and Wadeson (1999).

Moolman J, Kleynhans CJ and Thirion C (2002) Channel Slopes in the Olifants, Crocodile and Sabie River Catchments. Department of Water Affairs and Forestry, Institute For Water Quality Studies, Internal Report No.N/0000/00REH/0102. 41pp 

Rowntree KM and Wadeson RA (1999) A hierarchical geomorphological model for the classification of selected South African Rivers. Water Research Commission Report No. 497/1/99, Water Research Commission, Pretoria. 334pp.

**Comment by KSnaddon** [comment]
@helendallas We have added the Wetlands Map abstract, but @amyburness for some reason it isn't showing.  I added it in GeoServer - should I also do something in BIMS admin to make it visible?

**Comment by amyburness** [comment]
@KSnaddon @helendallas can you provide me with the abstracts for these layers? I will check them and test why they are not Showing and update them.

**Comment by KSnaddon** [comment]
@amyburness Here is the one for NWM 6 Beta (copied off GeoServer):
"The National Wetland Map 6 Beta is an unpublished version (not public) update of the National Wetland Map. National Wetland Map 6 Beta includes inland wetlands, artificial wetlands (dams), and estuaries. This dataset includes an update of wetland extent in selected catchments, and an update of wetland attributes across the dataset. The National Wetland Map 6 Beta contains the condition, ecosystem threat status, and protection level of the NBA 2018. These will be re-assessed, updated, and released to the public after the completion of the NBA 2024."

**Comment by helendallas** [comment]
Metadat for :
Pesticide Use map:

Map of estimated pesticide application rates (kg/ha) for more than 200 active ingredients for all quaternary catchments in South Africa, based on pesticide use data from 2014. [Source: Dabrowski, J.M. (2022). An Integrated Approach to Managing and Mitigating the Risk of Agricultural Nonpoint Source Pesticide Pollution to the Aquatic Environment. Volume 2: Development of Risk Maps and a Risk Indicator for Identifying Hotspots and Prioritising Risks of Pesticide use to Aquatic Ecosystem Health. WRC Report No. TT 885/22. Water Research Commission, Pretoria].

**Comment by helendallas** [comment]
Strategic Water Source Area - Surface (it was there but now disappeared) - can you check the Kartoza site???? They have been up for years, not sure why they now disappeared

Otherwise use this which I have revised from GW:
The Strategic Water Source Areas for surface water (SWSA-sf) reflect areas that have high surface water availability and where the surface water forms a nationally important resource. The areas are delineated for the purposes of research, and the outcomes are useful to national level planners and decision-makers as an indication of the location of strategic surface sources and resources. The framework for the management of the SWSAs promotes various best-practice groundwater management measures, such as the delineation of wellfield capture zones, and the incorporation of these in spatial planning processes. It is recommended that DWS prioritizes the SWSA-sw, along with other criteria (areas of sole supply, presence of stressed resources), for various management measures allowed for in the NWA, but not yet implemented.

**Comment by helendallas** [comment]
Sub Water Management Areas - these are now back??

**Comment by helendallas** [comment]
SA Provinces and SADC boundaries

I suggest:

Map of the nine provinces in South Africa, together with neighbouring countries with in the SADC region.

**Comment by amyburness** [comment]
I found the problem in the non biodiversity layers some of these layers were not referencing the layer correctly i.e. nwm6_beta_v3_20230714 instead of kartoza:nwm6_beta_v3_20230714

Once I updated them the abstract showed. 

Do you still want me to update the abstracts to the ones provided above currently I left them as the originals.

**Comment by KSnaddon** [comment]
@amyburness The abstract for the sub Water Management Areas is the wrong one - the one appearing now is actually for the Surface Water SWSAs.

**Comment by KSnaddon** [comment]
@helendallas If you give me the correct abstract for the sub-WMAs I can correct this one. Or are we dropping sub-WMAs as a visual layer?

**Comment by KSnaddon** [comment]
@helendallas See above - are we still providing the sub-WMAs as a layer, and if so, can you send me the abstract so that I can load it? At the moment, the wrong abstract is provided.

**Comment by helendallas** [comment]
@KSnaddon I actually haven't been able to find the metadata for sub WMAs. I did email Nancy a while back but she has not responded. Perhaps you can try. I thought these had the metadata on an old version of FBIS but cannot find it anywhere???

**Comment by helendallas** [comment]
Closing ticket - all metadata added
