### ISSUE TITLE
Admin need to be able to add new and manage existing sampling effort measure

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3486]
In BIMS we need to be able to edit existing and add new sampling effort measures.

Current ones are:

- Time (min)
- Area (m2)
- Replicates

**Comment by helendallas** [comment]
@dimasciput This is sampling effort measure; Currently only these

<img width="566" alt="Screenshot 2023-10-24 at 08 58 48" src="https://github.com/kartoza/django-bims/assets/45286876/19503660-f74e-443a-bb9e-534eb7c5993c">

Where do I add new ones if needed? Is it just in the Change sampling method form? There is no Bims Table Sampling effort measure

<img width="1069" alt="Screenshot 2023-10-24 at 09 00 24" src="https://github.com/kartoza/django-bims/assets/45286876/c847e837-d37a-43c2-ac8d-47d186189436">

**Comment by dimasciput** [comment]
@helendallas I'm still working on it, that's why I put it on the 'in progress' column.

**Comment by dimasciput** [comment]
@helendallas this has been added to testing.

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, Is it possible to allow one to select one or more specific module (like with biotopes?). If yes - please action, if not, then leave. Thanks

**Comment by dimasciput** [comment]
@helendallas, yes, currently it can only select one. In the future, I can improve it to allow multiple selections, but I think this should suffice for now? I have deployed it to production.

**Comment by helendallas** [comment]
Agreed @dimasciput Thanks, fine for now, closing ticket
