### ISSUE TITLE
Admin need to manage new wetland components

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3488]
In BIMS we need to be able to manage (edit and add new) wetland components including:

- Wetland Indicator Status
- Hydroperiod
Can these please be added to BIMS as tables

Also please confirm that Hydrogeomorphic Type is derived from the National Wetlands Map 6

**Comment by KSnaddon** [comment]
@helendallas Hydrogeomorphic type is derived from NWM6 by default, and refined by the user ("User hydrogeomorphic type").

**Comment by dimasciput** [comment]
@KSnaddon @helendallas can you give me example values for Wetland Indicator Status and Hydroperiod? And these are attached to location site right?

**Comment by KSnaddon** [comment]
@dimasciput Yes both of these can be entered when a user adds biodiversity occurrence data to a wetland site.   Wetland Indicator Status is linked to plant occurrence data.  @helendallas I've realised I made this "All" and not "Plants only" in the upload template. This should be changed.

Hydroperiod is also for biodiversity occurrence data, but is an option for all biodiversity modules.

**Comment by dimasciput** [comment]
@KSnaddon, are both of these fixed options or free text?

**Comment by KSnaddon** [comment]
@dimasciput They are fixed drop-down options

**Comment by helendallas** [comment]
@dimasciput Please see below

**Wetland Indicator Status**

- Obligate wetland
- Facultative wetland
- Facultative
- Facultative dryland
- Dryland

For Hydroperiod

- Inundated
- Saturated at surface
- Dry at surface

**Comment by dimasciput** [comment]
@KSnaddon @helendallas please test on testing site

**Comment by helendallas** [comment]
Works fine on testing. Please deploy to production

**Comment by dimasciput** [comment]
Deployed to production

**Comment by KSnaddon** [comment]
@dimasciput Thanks!
