### ISSUE TITLE
Admin need to be able to add new and manage existing Record Type

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3489]
At the moment we cannot edit existing or add new record types.

Current record types include:

- Visual observation
- Photographic record
- Specimen collection
- Acoustic record
- DNA sample

Please add labels in BIMS for managing Record Type

**Comment by dimasciput** [comment]
added in testing https://testing.healthyrivers.kartoza.com/admin/bims/recordtype/

**Comment by helendallas** [comment]
Thanks @dimasciput Is it possible to be able to specify order as for other admin table. This is useful especially when new record types are adding in future.

**Comment by dimasciput** [comment]
@helendallas yep it's possible, I will add it.

**Comment by dimasciput** [comment]
@helendallas, the display order has been added. You can change the order simply by clicking the up and down icons.

<img width="636" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/2b9d592a-1d87-4c14-81c6-e6250c2f08fc">

**Comment by helendallas** [comment]
Working closing ticket
