### ISSUE TITLE
Ecosystem type filter - add "Apply" and "Clear"

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3490]
@dimasciput  Can you perhaps add the options "Apply" and "Clear" to the Ecosystem type filter, as it is set up for the other filters?

![image](https://github.com/kartoza/django-bims/assets/91128958/c38c56bf-a6fd-48ad-8ee4-efb8fd40ebe6)

**Comment by dimasciput** [comment]
Added in testing site

**Comment by KSnaddon** [comment]
Thanks @dimasciput that's great.
