### ISSUE TITLE
Data from multiple taxa groups showing in one form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3491]
We are seeing invertebrates, algae and fish for the same site and site visit when all are added together. This is in the validation section and FBIS. Even though I applied the algae filter.

Why is this??

X2ELAN-00174

https://freshwaterbiodiversity.org/site-visit/detail/332016/

<img width="1125" alt="Screenshot 2023-09-21 at 10 52 14" src="https://github.com/kartoza/django-bims/assets/45286876/4fc3f614-413d-4eb3-a501-60c3e6dd9b16">

All data are visible on all modules

here is one from the fish filter

https://freshwaterbiodiversity.org/site-visit/detail/332016/

**Comment by dimasciput** [comment]
@helendallas it's because sometimes in site visit data you can have multiple modules. Should we break this apart? I mean, should we create separate site visits for different modules?

I think this only happens for existing data, or data that is uploaded via the CSV uploader.

**Comment by helendallas** [comment]
@dimasciput Yes, I think we need to break up by module. So then if you select fish data and drill down to the fish dashboard and to the site visit on the fish dashboard, you only get the fish data returned.

Thanks

**Comment by dimasciput** [comment]
This is fixed in testing.

**Comment by helendallas** [comment]
Thanks @dimasciput Looks great. Please deploy to production after training.

**Comment by dimasciput** [comment]
Deployed to production
