### ISSUE TITLE
Unable to go to a taxon to validate

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3493]
@dimasciput @timlinux I get an Error - 502 Bad Gateway - when I click on a taxon name in the Bims Admin Page ("Taxa") in order to validate.

**Comment by dimasciput** [comment]
This is fixed on testing

**Comment by KSnaddon** [comment]
@dimasciput thanks I can go in on the testing site.  Please can you fix this on the Public site too?

**Comment by helendallas** [comment]
@dimasciput Please reply to production soonest

**Comment by KSnaddon** [comment]
@dimasciput That's OK, I will wait. I will put these edits on hold, so just let me know when it's fixed? Thanks!

**Comment by helendallas** [comment]
@KSnaddon This seems to be working but please can you check. You need to validate in Taxon Management. Click filter - Validate = False to see all unvalidated taxa.

<img width="1208" alt="Screenshot 2023-10-13 at 08 19 11" src="https://github.com/kartoza/django-bims/assets/45286876/7f7f09f5-ae0c-463a-98e3-dbbc1239a27b">

**Comment by KSnaddon** [comment]
This is working for me now
