### ISSUE TITLE
We need to add an embargo period option for keeping some data private for a period of time

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3498]
At the moment all data added to FBIS, via the platform or app, are immediately available for all FBIS users.

Several users have said that they don't want to use FBIS because they need to keep their data private for a period of time to allow them to publish the data.  They said that if there was a way to select an "Embargo Period" , then they would add their data to FBIS, knowing that the data would be released after the embargo period was over.  We suggest a 12 month embargo period as standard, after which the data are visible on FBIS.  The owner of the data should be able to view there data. 

Please can you add this to both the app and platform, perhaps below Owner, on the data entry forms, as a check box, with an explanation:
"**Please select if you need the data to have a 12 month time embargo**" 

@timlinux Please can you check that this is the correct wording - I am sure you have had this issue before.

This was one of the requirements for SANParks, so perhaps the functionality can be created under the SANParks project.

<img width="1138" alt="Screenshot 2023-09-26 at 14 08 09" src="https://github.com/kartoza/django-bims/assets/45286876/fa8b98a6-6d52-49b5-9343-c229957b969a">

**Comment by dimasciput** [comment]
Hi @helendallas , I have sized this ticket to 8.

**Comment by helendallas** [comment]
Thanks @dimasciput @jeremyshelton @KSnaddon Is this something we want to do now, or hold over to the next app iteration.

It was something that SANParks needed so I had hoped to do it using their funds, but their project is not yet online yet.

My feeling is we release the app as is, and that this can come at a later stage.

Thoughts?

**Comment by jeremyshelton** [comment]
@dimasciput how long does a size 8 ticket take?

**Comment by dimasciput** [comment]
Hi @jeremyshelton , 8 is a full day. Or 7 hours.

**Comment by jeremyshelton** [comment]
@helendallas I vote we do it now, but also happy for you to overrule I favour of using Dimas' time elsewhere.
Guess the first priority is to get the other issues identified in the mobile app #3175 sorted out first...

**Comment by helendallas** [comment]
@dimasciput Are you still scheduled to work on FBIS on the 8 and 9 Nov? If yes, then please implement. It will need another round of testing before we then release the app.

**Comment by KSnaddon** [comment]
@helendallas I think we can release the App - if the people who want the embargo don't use it initially, then that's not a huge loss?  We can even put a little pop up somewhere on the App that mentions upcoming features such as this?

**Comment by helendallas** [comment]
Thanks @KSnaddon @jeremyshelton 

@dimasciput I agree with Kate, lets roll this app version out once you have checked the issues I was experiencing. 

We can park the embargo ticket and rather do that development with SANParks funds when they come online.

**Comment by dimasciput** [comment]
This feature has been added to testing site.

**Comment by KSnaddon** [comment]
Thanks Dimas.  Are the embargoed records completely invisible to other users (i.e. no dot on the map, if it’s added to a new site), or is the site visible and the data not?

 

Kate

**Comment by dimasciput** [comment]
@KSnaddon, the embargo data will not be visible to anyone, including the owner. This is because we do not check the owner in the backend, doing so would impact the performance of the query. Additionally, if the site contains only the embargo data, then it will also remain invisible.

**Comment by helendallas** [comment]
Thanks @dimasciput I added a site and a fish record. The intention of the embargo period was to allow the owner to be able to use FBIS and see their data from when they first add it, but that this data would be hidden from everyone else until the embargo period had ended. 

At the moment I can see the site, but not the occurrence data. This needs to apply for all data including SASS and abiotic.

**Comment by dimasciput** [comment]
helendallas Ah, okay, then this will be more complicated than I thought because we also need to query records by owner, and it's probably going to impact performance. Can we park this for now? I think there are other tasks in Sanpark that are more urgent.

**Comment by helendallas** [comment]
Sure, but it was a requirement from them so will need to tackle it. 
You should work through the tickets as per the task table I shared with you. Certain tasks are linked to certain milestones.

I will email it again. Also for this project you can just get me to review it, thanks.

**Comment by helendallas** [comment]
@dimasciput Please confirm if you have updated this functionality so that the owner of the data has access to their data during the embargo period. This should also be applied to SASS data, not only biodiversity occurrence records.

**Comment by helendallas** [comment]
@dimasciput Please can you check and finish this ticket so I can test, thanks

**Comment by dimasciput** [comment]
@helendallas yes I have implemented this on biodiversity records and SASS records, please test it on staging site.

**Comment by helendallas** [comment]
FBIS or SANParks?

**Comment by dimasciput** [comment]
sanparks site

**Comment by helendallas** [comment]
@dimasciput I have checked this. It seems to be working fine now. Please deploy to production. SANParks and FBIS
