### ISSUE TITLE
Improve spatial filter

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3499]
If the spatial filter has many values, it might be more efficient to use text input rather than checkboxes.

**Comment by dimasciput** [comment]
@KSnaddon @helendallas 

Hi, this feature is now available on the testing site.

From the admin page at: https://testing.healthyrivers.kartoza.com/admin/bims/locationcontextfiltergrouporder/

Select the ID of the spatial filter you wish to change to a text input, then check the option "use autocomplete in filter". As an example, I modified 'NFEPA Fish Sanctuaries All Species'.

<img width="893" alt="Screenshot 2023-09-29 at 4 18 32 PM" src="https://github.com/kartoza/django-bims/assets/1979569/03825073-6c47-466e-9f2f-42026006516c">

The spatial filter will be updated into this : 

<img width="476" alt="Screenshot 2023-09-29 at 4 53 52 PM" src="https://github.com/kartoza/django-bims/assets/1979569/1bd15085-5854-40a4-a643-b4d337b464f0">

**Comment by helendallas** [comment]
Thanks @dimasciput Works well, please deploy to production

**Comment by helendallas** [comment]
@dimasciput I checked this again, the filter no longer filters the records. E.g. I clicked Schulz quinary catchment box, and selected two using the free text, but it does not filter to the correct records.

<img width="959" alt="Screenshot 2023-10-04 at 12 20 15" src="https://github.com/kartoza/django-bims/assets/45286876/a6c34e5f-891c-4f2b-92a7-18c60069c311">



https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22group,quinary_catchment_area%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
@helendallas, if you check the parent name, it will filter using all the values of the parent filter. In this case, it will use all filters from "Schulze Quinary Catchment". This follows the previous behavior: if you check the parent, it will select all children.

**Comment by dimasciput** [comment]
@helendallas perhaps I should remove the textbox when user select the parent filter?

**Comment by helendallas** [comment]
Ok thanks. Then happy for you to deploy to production.

**Comment by helendallas** [comment]
All working, closing ticket
