### ISSUE TITLE
Add option to hide geocontext data in spatial filter

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3501]
Add a checkbox to indicate whether the geocontext data is hidden from the spatial filter. When checked, it will only be displayed in the dashboard or side panel.

**Comment by dimasciput** [comment]
added in testing 
<img width="1053" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/f00dc7e9-7293-401e-8f87-57fc96dcb2da">

**Comment by helendallas** [comment]
Great @dimasciput Please deploy to production

**Comment by helendallas** [comment]
Working, closing ticket
