### ISSUE TITLE
Taxon Management not finding Genus on GBIF

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3511]
@helendallas I have tried to add a genus to Taxon Management, and FBIS doesn't find it on GBIF, when I know it's there.  Then if I add the Family in, as requested, I get this message:

![image](https://github.com/kartoza/django-bims/assets/91128958/fa67353b-dd69-47ff-9962-73bba2f10313)

Can you give it a try too?

**Comment by dimasciput** [comment]
<img width="298" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/c6618dff-434d-44b3-832c-73b03485885a">

@KSnaddon make sure to select the dropdown here

**Comment by KSnaddon** [comment]
@dimasciput Thanks - I didn't realise that you can't type the Family in, but have to select it from the Dropdown.  A bit confusing!
