### ISSUE TITLE
Add "Wetland type" and "Artificial waterbody type" as filters

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3517]
@dimasciput I have added (on Test Site) these 2 filters: "Wetland type" and "Artificial waterbody type"

They should be a filter "drawer" on their own really, and not a spatial filter.  Not sure yet what to call it.  

Please can you check whether I have added these two filters correctly?  If so, can you update the sites to include these geocontext layers?

![image](https://github.com/kartoza/django-bims/assets/91128958/5167062b-4710-4848-92f9-e1a50e78e35e)

**Comment by KSnaddon** [comment]
@dimasciput Please hold on harvesting for these filters /layers for now.  We are working on the order of filters and groups on the panels etc, so will let you know when they are ready for harvesting. Thanks

**Comment by helendallas** [comment]
@KSnaddon Closing ticket as I think it may confuse Dimas.
