### ISSUE TITLE
Single site dashboard updates

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3518]
This is a follow-on from #3454 , which has now been closed.

Revision to site specific dashboard so that relevant information is available in the overview table. See below
Green - already actioned on production
Red - need Dimas to action
Yellow - needs to be brought into BIMS and then I can add (Kate)

<img width="581" alt="Screenshot 2023-10-10 at 11 51 03" src="https://github.com/kartoza/django-bims/assets/45286876/2a0bced0-2b89-4145-8190-bb0d8c9b0a56">

**Comment by helendallas** [comment]
After discussion with @KSnaddon some changes made:

Filters
<img width="494" alt="Screenshot 2023-10-10 at 14 19 25" src="https://github.com/kartoza/django-bims/assets/45286876/aa005ed2-5a61-48de-b7ce-1d2cc17c52c1">

And the overview dashboard

<img width="539" alt="Screenshot 2023-10-10 at 14 22 38" src="https://github.com/kartoza/django-bims/assets/45286876/75f9ab5c-79ee-4447-ace7-0d6b2bb5223f">

**Comment by KSnaddon** [comment]
@helendallas  I have done the following in BIMS admin (but none of these are showing on the search list!)
1. I have added Wetland Hydrogeomorphic Type as a group under the filter "River zones and wetland types"
2. I have added Wetland Present Ecological State 2018, Wetland Ecosystem Threat Status 2018 and Wetland Ecosystem Protection Level 2018 as groups under the filter "Ecosystem Condition and Threat Status

I must be doing something wrong as they are not appearing (don't think it's just taking time to load).  It would be great if you can check this, or ask Dimas to check.

**Comment by helendallas** [comment]
@KSnaddon The tick box for "Show in dashboard" needs to be ticked for it to be visible in the overview dashboard and as a filter. Also @dimasciput still needs to update functionality for not showing as a filter etc.

<img width="645" alt="Screenshot 2023-10-10 at 19 11 32" src="https://github.com/kartoza/django-bims/assets/45286876/acce7598-93dd-40c8-b204-7c01b48fe78d">

**Comment by KSnaddon** [comment]
@helendallas Aha thanks.  I wasn't sure (tired brain) which dashboard this referred to.

**Comment by KSnaddon** [comment]
@helendallas I have also added 4 groups to "Climate, vegetation and soils" filter.

**Comment by helendallas** [comment]
@KSnaddon Still not working properly though. I will take another look in the morning

**Comment by helendallas** [comment]
@dimasciput Please prioritise getting this sorted. Kate and I have done a lot of getting the dashboards and filters sorted as we want them. You may want to deploy updates to filters etc before doing this? Outstanding issues:


1. @KSnaddon to bring in SA VegMap Bioregion and add to Climate, Vegetation and Soils, and also add it as a filter



2. @dimasciput to generate top part of overview dashboard

<img width="538" alt="Screenshot 2023-10-11 at 10 29 45" src="https://github.com/kartoza/django-bims/assets/45286876/762c1687-9ea7-4382-94e9-42c301ed5dc4">



3. @dimasciput to check why order of filters is not working -  e.g. catchment is meant to be after Management Areas

<img width="385" alt="Screenshot 2023-10-11 at 10 40 34" src="https://github.com/kartoza/django-bims/assets/45286876/1bdfdd02-6c6d-4dc5-8fb7-48c76702b5c3">



4. @dimasciput to check why geo context not populating for the new layers, or renamed layers - see below


<img width="431" alt="Screenshot 2023-10-11 at 10 33 20" src="https://github.com/kartoza/django-bims/assets/45286876/8e84420e-e245-4392-8e0d-288b981c9c3a">



5. @dimasciput to check filters as some are not visible including:

- Wetland Hydrogeomorphic Type as a group under the filter "River zones and wetland types"
- Wetland Present Ecological State 2018, Wetland Ecosystem Threat Status 2018 and Wetland Ecosystem Protection Level 2018 as groups under the filter "Ecosystem Condition and Threat Status


<img width="274" alt="Screenshot 2023-10-11 at 10 54 43" src="https://github.com/kartoza/django-bims/assets/45286876/ce22fa49-5f0e-46a0-80a1-3bef4ca7446a">

**Comment by helendallas** [comment]
@dimasciput Wetland Ecosystem Threat Status has not appeared as a filter

<img width="270" alt="Screenshot 2023-10-13 at 08 25 56" src="https://github.com/kartoza/django-bims/assets/45286876/084f1100-d835-4535-b32e-a4ea65f20233">


Even though it is there. please can you check

<img width="724" alt="Screenshot 2023-10-13 at 08 28 34" src="https://github.com/kartoza/django-bims/assets/45286876/5113a755-004d-4b0f-981b-1ebf9ac10780">

**Comment by dimasciput** [comment]
@helendallas, it should be there now. Currently, the system is still harvesting wetland context data for all sites, so you might not see all the data today.

**Comment by helendallas** [comment]
Thanks it just popped up :)

**Comment by KSnaddon** [comment]
@dimasciput I would really like to know what I was doing wrong or not doing, which meant that the filters / groups that I set up in BIMS admin didn't appear?

**Comment by helendallas** [comment]
@dimasciput Please confirm what the reason was why the various layers did not appear. Was everything done correctly on our side? or not.

Did you have to do an extra step on your side. Kate and I would like tot know that we are doing things correctly, so that we can do this going forward.

Please comment in this ticket.

**Comment by KSnaddon** [comment]
@dimasciput @helendallas For all single site overview or detailed biodiversity view panels, it would be useful to have the "Ecosystem Type" at the top under "Overview", so you know what kind of site you're looking at:

![image](https://github.com/kartoza/django-bims/assets/91128958/0a969f4e-a238-4fea-951b-af7d51ddc9bf)

**Comment by KSnaddon** [comment]
@dimasciput @helendallas The "River and Geomorphological Zone" Filter is visible on the panels as well as the "River and Wetland Type".  We only need the latter, but then the River name needs to go somewhere.

Where are we with adding the wetland information to the panels?

**Comment by KSnaddon** [comment]
@helendallas I have added SA Veg Bioregion to the Filter "Climate, Vegetation and Soils"

**Comment by helendallas** [comment]
> @helendallas I have added SA Veg Bioregion to the Filter "Climate, Vegetation and Soils"

@KSnaddon This is not showing as a filter???? Nothing under this drawer is showing. Does @dimasciput still need to do something?????

<img width="329" alt="Screenshot 2023-10-19 at 15 55 19" src="https://github.com/kartoza/django-bims/assets/45286876/6e2b663f-d72c-47e6-a638-b93600728abf">

**Comment by KSnaddon** [comment]
@helendallas I have asked @dimasciput to tell me what still needs to be done to get these to be operational.  I am not sure yet.

**Comment by dimasciput** [comment]
@KSnaddon @helendallas you can see the filter now. 

> @dimasciput Please confirm what the reason was why the various layers did not appear. Was everything done correctly on our side? or not

@KSnaddon @helendallas 
There was an incorrect configuration in geocontext. You switched "layer typename" with "layer name" and vice versa. It should be configured as shown in the image below:
![image](https://github.com/kartoza/django-bims/assets/1979569/df661d8b-aedf-4bce-bfd6-7cc76fae3547)

**Comment by dimasciput** [comment]
@KSnaddon, it's better to group the services in GeoContext to avoid making multiple requests. You can see an example here:
https://geocontext.kartoza.com/admin/geocontext/group/71/change/?_changelist_filters=q%3Dwetland_group_v3

I've grouped the wetland services, for which you previously created a separate group for each service. I won't update the group now, as we've already harvested some of the data.

**Comment by dimasciput** [comment]
@KSnaddon @helendallas rainfall intensity zone layer is broken in geoserver, that's why you didn't get any value.

**Comment by dimasciput** [comment]
> @KSnaddon @dimasciput This still needs to be done by Dimas. We need to replace the River and Geomorphological Zone with this. VERY NB that it is done before Monday @dimasciput

@helendallas updated in production and testing, since it's not a big change I also deployed it to production.

**Comment by KSnaddon** [comment]
> @KSnaddon @helendallas rainfall intensity zone layer is broken in geoserver, that's why you didn't get any value.

@dimasciput How do I fix it?

**Comment by KSnaddon** [comment]
> @KSnaddon, it's better to group the services in GeoContext to avoid making multiple requests. You can see an example here: https://geocontext.kartoza.com/admin/geocontext/group/71/change/?_changelist_filters=q%3Dwetland_group_v3
> 
> I've grouped the wetland services, for which you previously created a separate group for each service. I won't update the group now, as we've already harvested some of the data.

@dimasciput Thanks for that.  As you can see, it would be super useful to have these steps explained better in the manual.

**Comment by KSnaddon** [comment]
> There was an incorrect configuration in geocontext. You switched "layer typename" with "layer name" and vice versa. It should be configured as shown in the image below:

@dimasciput Thanks - it is confusing and I always copy one that works, but obviously errors occur!

**Comment by dimasciput** [comment]
@KSnaddon @helendallas We are currently harvesting for all new spatial filters except the wetland. We finished fetching the wetland data a week ago.

**Comment by dimasciput** [comment]
@KSnaddon please work with @NyakudyaA or @amyburness to fix the layer.

**Comment by KSnaddon** [comment]
@dimasciput Thanks! Will do.

**Comment by helendallas** [comment]
Closing ticket and this is completed. One linked ticket #3547 which @dimasciput is working on
