### ISSUE TITLE
Base map - terrain tiles missing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3521]
The base map needs updating

<img width="1423" alt="Screenshot 2023-10-11 at 10 15 34" src="https://github.com/kartoza/django-bims/assets/45286876/bb2cd92d-769a-4d14-875a-fefdcf8c5517">

**Comment by dimasciput** [comment]
@helendallas ah thanks for the report, will check this

**Comment by dimasciput** [comment]
@helendallas ok it seems stamen is not free anymore, I think I'm going to replace it with other service.

**Comment by dimasciput** [comment]
This is fixed in testing

**Comment by dimasciput** [comment]
Deployed to production
