### ISSUE TITLE
Revise metadata for NFEPA river FEPAs 2011 - to long

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3522]
@KSnaddon Please can you try and reduce the words in this metadata and add a link.

**Comment by KSnaddon** [comment]
@helendallas I will get to this later today after field trip.

**Comment by KSnaddon** [comment]
@helendallas I have reduced the text somewhat, but it's a complicated one with several categories to describe.  Have a look and let me know what you think?  I'm not sure what you mean by "adding a link"?

**Comment by KSnaddon** [comment]
@helendallas Do you mean the reference?

**Comment by helendallas** [comment]
Thanks @KSnaddon That looks fine, fits now. Lets leave as is
