### ISSUE TITLE
Taxon Management Edit Taxon is not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3523]
I cannot open a taxon to edit. Something is not working

<img width="1143" alt="Screenshot 2023-10-11 at 14 59 24" src="https://github.com/kartoza/django-bims/assets/45286876/66a3ff8f-7e21-4240-9f89-b17c53186f64">

I get an error message when I click on Edit
<img width="285" alt="Screenshot 2023-10-11 at 14 30 31" src="https://github.com/kartoza/django-bims/assets/45286876/3b08d0ba-b91c-4e11-89df-b7cf2543890b">

**Comment by KSnaddon** [comment]
@dimasciput I am also unable to edit a taxon.  @helendallas I am unable to add the last few KNP taxa as a result, as they need to be added manually.

**Comment by helendallas** [comment]
@KSnaddon @dimasciput This seems to be working now.

@dimasciput An issue I noticed is that not all GBIF taxa are returned to choose from when selecting Add Taxon. Often the varian is given as an option to add but not the species.
Please can you check.

**Comment by dimasciput** [comment]
@helendallas can you give me example of the species name?

**Comment by dimasciput** [comment]
@helendallas @KSnaddon I'm going to close this one, since we can now edit the taxa. Please create a new ticket for the gbif issue.
