### ISSUE TITLE
Add New Taxon - GBIF does not return all options

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3528]
When there is a variant, the Add New Taxon - GBIF. -does not return the species as well as variant, so the admin person cannot select the correct GBIF Taxon

**Comment by dimasciput** [comment]
@helendallas this is a same ticket with https://github.com/kartoza/django-bims/issues/3526 right?

**Comment by helendallas** [comment]
Sorry, I didn't see @KSnaddon had already created one. I will delete this one
