### ISSUE TITLE
Taxon list on Algae dashboard needs to be refreshed to include recent additions to Master List

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3531]
@dimasciput @helendallas I'm not sure who needs to do this?  Recent additions to the Algae Master List are not available on the Algae dashboard.

**Comment by helendallas** [comment]
@KSnaddon Not sure what you mean??

**Comment by KSnaddon** [comment]
@helendallas Never mind, it's sorted.  We didn't "Add Taxon"!
