### ISSUE TITLE
River names not showing at some scales

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3544]
@dimasciput 

We need rived names to be visible to the user at all scales. 
However, at certain scales (while zooming into the map) there are no river names available. 

<img width="854" alt="Screenshot 2023-10-20 at 06 39 00" src="https://github.com/kartoza/django-bims/assets/44292029/13711515-f3f4-4790-adb2-ce02586d2e8b">

**Comment by dimasciput** [comment]
@jeremyshelton, this is a layer issue. I can't fix this. @amyburness or @NyakudyaA would be better suited to work on it.

**Comment by jeremyshelton** [comment]
@dimasciput yes I thought so. 

@amyburness or @NyakudyaA - is it possible to show river names at all scales when zooming in and out of the map?

**Comment by NyakudyaA** [comment]
@jeremyshelton The rivers should render at a scale <100. If they are not rendering below we can take a look. Also remember that when rendering labels,they are done per tile in order to reduce clutter

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas @NyakudyaA 
The absence of river names being displayed at most scales is still a usability issue. 
@dimasciput I know you said that this is a layer issue - but on Cape Farm Mapper river names are displayed at all scales (see attached recording). This is for the DWS Rivers layer - the same layer we are using. 
Is there no way to achieve a similar river name display approach on the FBIS?

https://github.com/kartoza/django-bims/assets/44292029/80a94349-2e86-426a-9f91-b955b361bc82

**Comment by helendallas** [comment]
@NyakudyaA Any comments on this?

**Comment by NyakudyaA** [comment]
> @NyakudyaA Any comments on this?

We are using 2 river layers, the NGI rivers and the DWA rivers. First option would be to 
* Update the NGI rivers with the latest one and switch to that. This is only visible at large scales
* Update DWA rivers layer if there is a new one.

for the labelling issue, I suggest @amyburness looks at the SLD that is used to label the rivers. You can remove the SLD labelling Vendor options i.e Grouping Features. Also check if the issue is happening for the cached layer vs. the WMS layer. If the issue occurs for the cache, I suggest you fix the metatile size

**Comment by Jeremy-Prior** [comment]
Adjustments were made to the SLDs for the two layers and this is the current effect:

https://github.com/user-attachments/assets/72605708-7c00-4e1e-b014-1f9c26feee44

Please review. There are some adjustments that can be made to the scales and font sizes if necessary.

**Comment by helendallas** [comment]
Thanks @Jeremy-Prior 

@jeremyshelton please review and comment

**Comment by helendallas** [comment]
@jeremyshelton Please check if this is an improvement

**Comment by helendallas** [comment]
Thanks @Jeremy-Prior Looks fine from my side except where you have different names for the rivers....see here. I am not sure which is correct or when one switches from DWA 1:500 000 to NGI layer for river names?

![Image](https://github.com/user-attachments/assets/b161541f-a156-4500-b8b8-528ed796ce21)

**Comment by Jeremy-Prior** [comment]
Hi @helendallas, 

The names from the DWA and NGI layers are consistent with each other and are correct. The secondary name, Hopies, appears to be coming from the Bing Satellite basemap layer:
![image](https://github.com/user-attachments/assets/e40adb4e-80b2-43d0-b90d-e7abf4f1ebd8)

Switching to the Terrain basemap shows the same river name:
![image](https://github.com/user-attachments/assets/8fdd3faf-ad0b-4f48-96b3-3e5fb4943080)

**Comment by helendallas** [comment]
aha, gosh that is confusing but ok, at least DWA and NGI match.

**Comment by helendallas** [comment]
Then I am happy to sign off on this one. The s @dimasciput and @Jeremy-Prior
