### ISSUE TITLE
Taxon dashboards not loading on testing and production sites.

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3545]
@dimasciput 
<img width="449" alt="Screenshot 2023-10-20 at 06 58 42" src="https://github.com/kartoza/django-bims/assets/44292029/220070fc-a6d0-4241-bc0a-e5ac8fd32065">

**Comment by dimasciput** [comment]
@jeremyshelton for which species? It would be helpful if you also share the link.

**Comment by jeremyshelton** [comment]
Sure: Lestagella penicillia

https://testing.healthyrivers.kartoza.com/map/#species-detail/taxon=1921&search=Lestagella%20penicillata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
@jeremyshelton fixed on testing. I will update to production later today.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput

**Comment by dimasciput** [comment]
Deployed to production

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Working fine now.
Closing ticket.
