### ISSUE TITLE
Side panel dash and detailed dashboard update

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3547]
@dimasciput Two small requests please for today.

**Side panel dashboard**

Please add Ecosystem Type at the top above Site Code on the side panel dashboard

<img width="506" alt="Screenshot 2023-10-20 at 08 53 25" src="https://github.com/kartoza/django-bims/assets/45286876/c9dea86e-3e59-4715-a906-9bcb8ef7823d">

Remove River (name) at the bottom

So we only have:

- Ecosystem Type
- Site Code
- Site Description
- Site coordinates

Then we can manage the other info we need such as Ecoregion level 1.

**Detailed dashboard**

Please rename River/Wetland/Open Waterbody/Unspecified to Ecosystem Type

<img width="429" alt="Screenshot 2023-10-20 at 08 55 11" src="https://github.com/kartoza/django-bims/assets/45286876/6ea5986d-5572-4b78-9304-f0f118f7c266">

**Comment by dimasciput** [comment]
@helendallas something like this : 

![image](https://github.com/kartoza/django-bims/assets/1979569/198e231a-a900-46c9-b665-4accd55a3991)

**Comment by helendallas** [comment]
Yes, but remove geomorphological zone

**Comment by dimasciput** [comment]
No, you can remove location context in side panel from admin page. I will deploy it to testing.

**Comment by helendallas** [comment]
Thanks.

**Comment by dimasciput** [comment]
Please test on testing

**Comment by helendallas** [comment]
This looks fine except for the strange site codes for open waterbodies and unspecified. As per email.

**Comment by dimasciput** [comment]
Deployed to production

**Comment by helendallas** [comment]
great thanks. Looks good.
