### ISSUE TITLE
River and Wetland Threat status

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3548]
In the filters threat status for rivers in in full, but for wetlands it is abbreviated.

Amy - is there an easy fix to make the weltand threat status categories show in full? LC is Least Concerned

<img width="278" alt="Screenshot 2023-10-20 at 09 15 40" src="https://github.com/kartoza/django-bims/assets/45286876/08de9224-eca9-4b7d-a463-f63efdebfa1e">

This does not need to be done in this sprint. I this is something Kate can learn please can you show and document. thanks

**Comment by helendallas** [comment]
@dimasciput Please re-harvest data

**Comment by dimasciput** [comment]
this is fixed

![image](https://github.com/kartoza/django-bims/assets/1979569/9ac8fb48-a1a4-456d-9d73-2daa5926c2c9)

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket
