### ISSUE TITLE
Unable to publish Rainfall Intensity Zones layer on GeoServer

### ISSUE THREAD

**Issue by KSnaddon** [kartoza/django-bims#3549]
I am struggling to publish the Rainfall Intensity zones layer in Geoserver.  I changed the attribute Zone to zone in QGIS and re-uploaded to SANBI (this is why it's v3), but now the co-ord system and bounding boxes are wrong.  Can you help please?

This layer is only for filtering and panels, and not for visual.

![image](https://github.com/kartoza/django-bims/assets/91128958/27bee66a-746f-40d7-a25d-779e62c26705)

**Comment by KSnaddon** [comment]
@amyburness @NyakudyaA Are you able to help with this today please?

**Comment by NyakudyaA** [comment]
@KSnaddon Please check the published layer `Rainfall_Intensity_v3`. Ideally, we would like to keep one copy in the DB and in GeoServer. Can we cleanup  the layers to only keep the most wanted unless there is good reason to keep the older versions

**Comment by KSnaddon** [comment]
@NyakudyaA Thanks for fixing the layer. Please tell me what you did?

I will delete the old one.

**Comment by KSnaddon** [comment]
@NyakudyaA I was under the impression that the "Name" on GeoServer had to be all lower case? So, like this - sanbi:rainfall_intensity_v3  I've changed it to that.

**Comment by KSnaddon** [comment]
@dimasciput The Rainfall Intensity Zones layer is fixed in GeoServer, and I have updated the service and the group etc in BIMS admin to refer to the corrected layer.  

Can you harvest for this layer?

**Comment by NyakudyaA** [comment]
> @NyakudyaA I was under the impression that the "Name" on GeoServer had to be all lower case? So, like this - sanbi:rainfall_intensity_v3 I've changed it to that.

You can name it anything you want, Do you still need the `sanbi:rainfall_intensity` inside GeoServer? I would suggest that if you do not need that one please remove it and rename `rainfall_intensity_v3` to `rainfall_intensity`

**Comment by KSnaddon** [comment]
@NyakudyaA Please check that this is now all correct, Admire?  I deleted the old one.

**Comment by dimasciput** [comment]
@KSnaddon I'm going to close this one, since we can harvest the layer now.

**Comment by KSnaddon** [comment]
Thanks @dimasciput
