### ISSUE TITLE
River and Wetland Present Ecological State

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3551]
In the filters present ecological state for rivers in in full, but for wetlands it is abbreviated.

Ideally we need In full with abbreviation in parenthesis

<img width="272" alt="Screenshot 2023-10-20 at 09 18 38" src="https://github.com/kartoza/django-bims/assets/45286876/318cc81b-229d-4056-acbe-d6f9b8da6e42">

**Categories for River PES**
- Unmodified Natural (A)
- Largely Natural with few modification (B)
- Moderately Modified (C)
- Largely Modified (D)
- Seriously Modified (E)
- Critical/Extremely Modified (E)

**Extra river categories**
- Data Deficient
- Estuary
- Foreign

**Then combined ones for wetland PES**
- Unmodified Natural/Largely Natural with few modification (A/B)
- Moderately Modified (C)
- Largely/Seriously/Critically/Extermely modified (C/D/E)

@KSnaddon 

This is not needed for this sprint.

**Comment by amyburness** [comment]
@KSnaddon I have emailed this to you.

@dimasciput will you need to resample the data as we have made updates?

**Comment by KSnaddon** [comment]
@dimasciput Please let me know when you resample these data?

@amyburness I am checking why there are blank entries for the wetland PES.

**Comment by dimasciput** [comment]
@KSnaddon I will do this on the next sprint.

**Comment by helendallas** [comment]
@dimasciput Please re-harvest data

**Comment by dimasciput** [comment]
This is fixed

**Comment by helendallas** [comment]
Not correct yet:  Duplicates for Wetland PES:


<img width="237" alt="Screenshot 2024-03-19 at 09 45 45" src="https://github.com/kartoza/django-bims/assets/45286876/b6870d61-2bbd-47af-8cf6-e4de03550fc9">

**Comment by KSnaddon** [comment]
@dimasciput Please change as follows:
Unmodified natural/Largely natural with few modifications (A/B) **PLEASE NOTE change to modifications (not modification)**
Moderately modified (C)
Largely/Seriously/Critically modified (C/D/E) **PLEASE NOTE to take out extremely**
Seriously/Critically/Extremely modified (D/E/F) **THIS IS A NEW ONE to cater for the F category  -extremely modified**

**Comment by helendallas** [comment]
SO @KSnaddon Are these then the correct categories - sorry I was confused by above, where you have some categories in more than one place.  Please confirm

- Unmodified natural/Largely natural with few modifications (A/B)
- Moderately modified (C)
- Largely/Seriously/Critically modified (D/E)
- Extremely modified (F)

**Comment by KSnaddon** [comment]
@helendallas No, due to the fact that the Wetland Map combines C/D/E, and also D/E/F.  However, I am just checking exactly how many combinations we need to include for the filter, so none are missing.

@dimasciput I assume we can't just provide a list of A to F, right? We actually need to include only the categories as they are written in that attribute column (i.e. in this case, "nba2018pes").

**Comment by helendallas** [comment]
@dimasciput From above - if not clear please ask @KSnaddon for clarification

@dimasciput Please change as follows:
Unmodified natural/Largely natural with few modifications (A/B) PLEASE NOTE change to modifications (not modification)
Moderately modified (C)
Largely/Seriously/Critically modified (C/D/E) PLEASE NOTE to take out extremely
Seriously/Critically/Extremely modified (D/E/F) THIS IS A NEW ONE to cater for the F category -extremely modified

**Comment by helendallas** [comment]
@KSnaddon Please can we finalise this ticket. I am not sure if Dimas is the one who needs to do this or if you can?

Please revert asap. FBIS sprint on 28 and 29 May. We only have a few days left of Dimas's time.

**Comment by KSnaddon** [comment]
@dimasciput Please let me know how I can do this?  I understand that I need to make the changes to the attributes in the original shapefile, but is there a different way to do it?

**Comment by dimasciput** [comment]
@KSnaddon, I can update it from the database, but I need more information on how to get the extremely modified category.

here's current categories in database:

![image](https://github.com/kartoza/django-bims/assets/1979569/54783426-ffb9-45a8-97c6-b975f4432dd1)

I need to know how to separate the D/E/F category into C/D/E and D/E/F. Basically, I need more information from other columns.

**Comment by KSnaddon** [comment]
@dimasciput Apologies, there isn't a C/D/E category in the wetland map.  Categories are as above:
Unmodified natural (A)
Unmodified natural / Largely natural with few modifications (A/B)
Moderately modified (C)
Largely / Seriously / Critically modified (D/E/F)

**Comment by dimasciput** [comment]
@KSnaddon I have updated the data on the layer and also spatial filter.

**Comment by KSnaddon** [comment]
@dimasciput Thank you!

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket
