### ISSUE TITLE
Water temperature sites should all be Ecosystem Type = River

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3553]
I noticed that the sites that have water temperature data are a mixture of River sites and Unspecified sites in terms of Ecosystem Type.

Please can you reassign all these sites as River sites. I uploaded all the data so know that this is correct.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=water_temperature&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
@helendallas I'm going to update the sites on the production.

**Comment by dimasciput** [comment]
Updated in production

**Comment by helendallas** [comment]
Thanks, closing ticket
