### ISSUE TITLE
Be able to see Ecosystem Type drawer as filter when viewing water temp or physico-chem data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3554]
Is it possible to be able to see and filter on ecosystem type when we select water temp or physic-them data.

At the moment it disappears when either is selected.

<img width="654" alt="Screenshot 2023-10-20 at 11 57 03" src="https://github.com/kartoza/django-bims/assets/45286876/51149a3c-9410-4578-9301-439bdceb326b">

**Comment by dimasciput** [comment]
@helendallas, this has been fixed in testing. Bonus improvement, the water temperature and physico-chemistry filter now operate faster than before.

**Comment by helendallas** [comment]
Looks good @dimasciput Thanks, Please deploy to production

**Comment by dimasciput** [comment]
@helendallas deployed to production

**Comment by helendallas** [comment]
Looks great, thanks closing ticket
