### ISSUE TITLE
Site code duplication again when uploading taxa to existing sites - urgent

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3561]
We have the same issue again when I want to add data to an existing site code.

I added algae data to 8 existing invertebrate sites for the study reference: On production….top shot now, and on testing below before uploading algae data.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221114%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

Then I Uploaded algae data to the same 8 sites, but new sites have been created even though the site codes are the same. On testing.

<img width="816" alt="Screenshot 2023-10-25 at 08 44 47" src="https://github.com/kartoza/django-bims/assets/45286876/22eae383-bdb9-431c-a5d5-99238c0fb9ad">

<img width="635" alt="Screenshot 2023-10-25 at 08 35 46" src="https://github.com/kartoza/django-bims/assets/45286876/059d4463-575a-4b7c-88a3-6394ce49ee42">

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221114%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified
 

This has been a recurring issue and one that has significant consequences!!!!

PLEASE can you see what is happening and fix again urgently.

<img width="1445" alt="Screenshot 2023-10-25 at 08 48 10" src="https://github.com/kartoza/django-bims/assets/45286876/b4349521-6961-460f-b264-aad6eff80c7c">

**Comment by helendallas** [comment]
Transcribed email comms:

From Dimas: Ah, okay. I found the issue. You used 'Ecosystem Type' instead of 'Ecosystem type' in the CSV file, which is why the sites are categorized as unspecified. I will update the uploader to also recognize 'Ecosystem Type'.

From Helen: I redid after changing type to lowercase, and one site still made a new one even though the code was the same. New one created – code in upload field was H5BREE-00013
<img width="422" alt="image" src="https://github.com/kartoza/django-bims/assets/45286876/3c2662df-31a6-4352-acd6-ad054b3ea245">

From Dimas: This is fixed in testing.

@dimasciput Have these fixes been deployed to production yet?

**Comment by dimasciput** [comment]
@helendallas I think so, but let me check again tomorrow morning.

**Comment by dimasciput** [comment]
@helendallas it has been deployed to production
