### ISSUE TITLE
Not specified and Unspecified in several BIMS tables

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3563]
We currently on the site and app have dropdown options that include both Not specified and Unspecified.  It is confusing to the user to have both options which mean the same.

These are the relevant BIMS tables:

- Sampling method
- Broad Biotope / Habitat
- Specific Biotope / Habitat
- Substratum

Some data in FBIS are linked to Unspecified.

So either we need to remove Not specified for all and have Unspecified as the default

OR 

We need to rename all Unspecified as Not specified, and then delete Unspecified in these BIMS tables.

@dimasciput Please advise what is the easiest and then please action. Thanks

**Comment by helendallas** [comment]
@dimasciput Thanks I see you have fixed this in the App. Can you please do the same in the FBIS Production, and both are still available

**Comment by dimasciput** [comment]
@helendallas easiest is to use Unspecified instead, I have updated the mobile app to use 'unspecified' instead of 'not specified'.

**Comment by dimasciput** [comment]
Updated in testing.

**Comment by helendallas** [comment]
Thanks looks fine, please deploy to production
