### ISSUE TITLE
Harvesting of GBIF Records for Specific Taxon Groups

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3565]
From this ticket https://github.com/kartoza/django-bims/issues/3274

https://github.com/kartoza/django-bims/issues/3274#issuecomment-1782232324

- A user harvests gbif data for fish and obtains occurrence AAA.
- The user creates a new taxon group, fish2, which includes a species that also belongs to fish.
- When the user harvests gbif data for fish2, since it has the same species, they also get occurrence AAA.
- As it stands now, occurrence AAA will be updated to the taxon group fish2. Therefore, when you search within the taxon group fish, you won't find AAA, as it has already been migrated to fish2.

**Comment by helendallas** [comment]
Think this has been dealt with, closing
