### ISSUE TITLE
Problem with downloading algal data on production

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3566]
Last week I tried to download a small csv file of 268 records for study reference 

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221185%22]&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

<img width="1315" alt="Screenshot 2023-10-30 at 12 16 45" src="https://github.com/kartoza/django-bims/assets/45286876/34791a1a-8199-4ede-9d96-2d7dca0953d9">

It has not worked, and I tried again today, still didn't work.
<img width="993" alt="Screenshot 2023-10-30 at 12 18 53" src="https://github.com/kartoza/django-bims/assets/45286876/9e4c3e96-9597-4c1f-8ef1-d7b5bb52473c">

Trying again.

@dimasciput Please can you check again in the morning to see if there is na issue

**Comment by helendallas** [comment]
As per email comms on the 31st October, @dimasciput has found a bug and will fix on 1 Nov and deploy to testing and production.

**Comment by dimasciput** [comment]
@helendallas I have fixed this, and it has been deployed to production and testing.

**Comment by helendallas** [comment]
Thanks @dimasciput Downloading now, closing ticket
