### ISSUE TITLE
Ecological Category Graph Issue

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3570]
Just wanted to let you know that there seems to be an FBIS issue with the ecological cat data.
 
[https://freshwaterbiodiversity.org/sass/dashboard/86301/?taxon=&search=&siteId=86301&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%221149%22%5D&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=86301&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified](https://freshwaterbiodiversity.org/sass/dashboard/86301/?taxon=&search=&siteId=86301&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%221149%22%5D&endemic=&conservationStatus=%5b%5d&modules=&validated=&sourceCollection=%5b%22fbis%22,%22gbif%22,%22virtual_museum%22%5d&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=86301&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified)
 
This is one of our sites…the graph with ecological cat is not showing. However, if I go to the site and reload the Geomorphological zone and refresh the site then it appears. Do we need to do this for all our sites or is this something that you can change on your side?

**Comment by dimasciput** [comment]
this is fixed, the issue is because the site is missing ecoregion data.

**Comment by helendallas** [comment]
@dimasciput Please confirm that this has been resolved subsequent to the last email from user Aileen
