### ISSUE TITLE
Add Fetch Wetland Name and Fetch data for Hydrogeomorphic type in Add Wetland Site form

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3573]
Plase can you update the Add Wetland Site form so that a user can click on a:

**Fetch Wetland Name**. (Same as for Fetch River Name in River Site Form)

**Fetch data** - for Hydrogeomorphic Type  (Same as for Fetch data for Geomorphological Name in the River Site Form)

<img width="841" alt="Screenshot 2023-11-08 at 16 39 03" src="https://github.com/kartoza/django-bims/assets/45286876/b0c96906-1175-4a8e-bb99-ace9df0649e4">

**### Needs to be the same as the current Add River Site form**

<img width="844" alt="Screenshot 2023-11-08 at 16 39 19" src="https://github.com/kartoza/django-bims/assets/45286876/7f758314-0962-49f4-b402-3098795aa902">

**Comment by dimasciput** [comment]
@helendallas, the data for the wetland is actually fetched automatically when the user changes the coordinates. Therefore, if it's empty, that means there's no wetland layer. However, I understand for consistency with other forms. Should I disable this automatic feature and implement a button instead?

https://github.com/kartoza/django-bims/assets/1979569/e2ccfe57-1daa-4371-bb2a-59a6339cff32

**Comment by helendallas** [comment]
I assumed the geomorphological zone was also fetched automatically? Is It not?

Either way for consistency please add. Sometime the user does not know the hydro zone is blank.  If there is no hydro type fetched then the user may be prompted to add a user Hydro type.

**Comment by dimasciput** [comment]
@helendallas geomorphological zone is fetched automatically in the backend when the site is added. Do you want to show the geomorphological zone field as well in the form?

**Comment by helendallas** [comment]
Not sure I understand your question. At the moment Geomorphological Zone is fetched automatically in the backend when the site is created.  BUT this does not always work and so we have the option for a user to also Fetch data - next to geomorphological Zone.

We are asking for the same for Hydro regional, its gets fetched automatically in the backend, but the a user can click fetch data, to make sure there is no type specified, and then this will prompt them to add a type if they know it. 

Make sense?

**Comment by dimasciput** [comment]
@helendallas ah, that makes sense. I thought your question, "I assumed the geomorphological zone was also fetched automatically. Is it not?" referred to the wetland site. Because currently there's no geomorphological zone field in the wetland site.

**Comment by dimasciput** [comment]
Implemented in testing site

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good. please reply to production

**Comment by dimasciput** [comment]
Deployed to production
