### ISSUE TITLE
Remove Wetland Indicator Status in Add data for a Wetland Site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3574]
@dimasciput I asked for this in error. Please can you remove from all the  **Add data form** for all sites that are Wetland sites

<img width="838" alt="Screenshot 2023-11-08 at 16 44 14" src="https://github.com/kartoza/django-bims/assets/45286876/1113ea15-959f-464a-9ba5-371335dd21c2">

This is actually an attribute specific to a plant taxon and is only in the plant master list

**Comment by dimasciput** [comment]
Updated in testing

**Comment by helendallas** [comment]
THanks, Looks fie, please deploy to production.
