### ISSUE TITLE
Rename Module - Abiotic Module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3575]
Please rename " Module" to Abiotic Module - as it was before

<img width="282" alt="Screenshot 2023-11-08 at 16 51 48" src="https://github.com/kartoza/django-bims/assets/45286876/2c9ff2e1-06fe-4ba7-a13a-055c3c96c86f">

**Comment by dimasciput** [comment]
Updated in testing

**Comment by helendallas** [comment]
Please deploy to production
