### ISSUE TITLE
Physico-chemical dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3581]
Graphs fall over photos if taken in portrait mode.  

<img width="846" alt="Screenshot 2023-11-14 at 10 32 59" src="https://github.com/kartoza/django-bims/assets/45286876/50813153-1f5e-44e2-996b-fb955c9110bf">

https://testing.healthyrivers.kartoza.com/physico-chemical/116594/?taxon=&search=G22A-Schu-00001&siteId=116594&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=116594&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
Fixed in testing

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, please deploy to production

**Comment by dimasciput** [comment]
deployed to production
