### ISSUE TITLE
Add functionality to delete data associated with a specific source reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3584]
At the moment it is not possible to select a source reference and delete all associated data. Sometime this is necessary when data are not correct and it is easier to delete the entire source reference.

For the Source Reference, can you please allow one to delete records.

An issue to make sure of is that if there are other data at the site sampled as a different source reference, then this does not get deleted

**Comment by helendallas** [comment]
Thanks @dimasciput I have checked this and it looks great. Please deploy to production

**Comment by dimasciput** [comment]
Deployed to production
