### ISSUE TITLE
Delete Site Visit does sometimes gives an error message

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3585]
I needed to delete site visit data. Example here

<img width="1180" alt="Screenshot 2023-11-24 at 12 08 01" src="https://github.com/kartoza/django-bims/assets/45286876/49416fa6-75e0-4ce7-98c2-6a749dd3eeaa">

But 3 times out of 4 I get an error message

<img width="1180" alt="Screenshot 2023-11-24 at 12 08 07" src="https://github.com/kartoza/django-bims/assets/45286876/2e01632f-a6f6-4fa3-8a70-88f514f09126">

Even though the site visit data is actually deleted.

1 if 4 times it deletes and returns this page

<img width="1237" alt="Screenshot 2023-11-24 at 12 13 36" src="https://github.com/kartoza/django-bims/assets/45286876/19138854-5e55-4a4a-af50-0cc29b062cfb">

**Comment by helendallas** [comment]
Thanks @dimasciput Not getting error message anymore. Please deploy to production.

**Comment by dimasciput** [comment]
Deployed to production
