### ISSUE TITLE
Rainfall intensity zones

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3586]
At the moment only abbreviations are given

Please @KSnaddon Expand these to include full names with abbreviation in parenthesis  (high, medium, low) 

@KSnaddon There are 4 categories so you need to check what each is as your text categories are only 3.

<img width="265" alt="Screenshot 2023-11-24 at 12 24 13" src="https://github.com/kartoza/django-bims/assets/45286876/e7d94939-9b49-41f0-a0a8-c8e682278038">

**Comment by KSnaddon** [comment]
@amyburness Is there an easy way to edit the attributes in a spatial layer, other than making the changes in QGIS and then re-publishing the layer?  

In the example above, I want to change "1" to "High intensity", "2" to "Moderate intensity", etc

**Comment by amyburness** [comment]
@kate I can update this for you and send a vid on how to do it what are the 4 categories. ?

**Comment by KSnaddon** [comment]
@amyburness Thanks, please do send a vid of the process?

The categories are:
1 = Zone 1 (low)
2 = Zone 2 (medium)
3 = Zone 3 (high)
4 = Zone 4 (very high)

**Comment by KSnaddon** [comment]
@amyburness Can you please send me the video of how to make the changes above?  This pertains to a few tickets.

**Comment by amyburness** [comment]
@KSnaddon I have emailed this to you. 

@dimasciput will you need to resample the data as we have made updates?

**Comment by KSnaddon** [comment]
@dimasciput Can you please just let me know when you resample the data for Rainfall Intensity Zones?

**Comment by helendallas** [comment]
@dimasciput Please resample data

**Comment by dimasciput** [comment]
@amyburness the rainfall intensity zone is empty https://maps.kartoza.com/geoserver/sanbi/wms?service=WMS&version=1.1.0&request=GetMap&layers=sanbi%3Arainfall_intensity_v3&bbox=16.387104034423828%2C-34.89776611328125%2C32.97265625%2C-22.060932159423828&width=768&height=594&srs=EPSG%3A4326&styles=&format=application/openlayers

I will manually update the filter from the backend now, but when we fetch new data, it will not receive any data since the layer is empty. Could you please fix it?

**Comment by dimasciput** [comment]
![image](https://github.com/kartoza/django-bims/assets/1979569/f9c3db20-a991-4aac-a4f5-2ceb2d74bfd5)

**Comment by KSnaddon** [comment]
Thanks @dimasciput  Has this been fixed so that the data are returned? Or must this still be done?

**Comment by helendallas** [comment]
@KSnaddon This seems to be filtering data. Please check and close ticket if you are happy, thanks

**Comment by KSnaddon** [comment]
Agreed. I will close ticket.
