### ISSUE TITLE
Revise Form - ADD AN OPEN WATERBODY SITE

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3587]
At the moment the **Add an open waterbody site** is based on the Add a river site.

Please update as follows:

Replace **River Name** with **Open Waterbody Name**
Replace **User River Name** with **User Open Waterbody Name**
Add "F**etch Open Waterbody Name**" (As per F**etch Wetland Name** as in ticket https://github.com/kartoza/django-bims/issues/3573)

This should be retrieved from Open Waterbody name in the NWM6 beta, if there is no name then the user should be prompted to **Add a User Waterbody Name**
This prompt should also apply to Add Wetland Name.

<img width="858" alt="Screenshot 2023-11-24 at 12 40 17" src="https://github.com/kartoza/django-bims/assets/45286876/962cd5a3-157e-4c08-a3b0-60942ed57584">

This should also be carried over to the mobile app. as per ticket https://github.com/kartoza/django-bims/issues/3175

As with User River Name taking precedence for naming a site, the same should apply for the User Wetland Name and User Open Waterbody Name

**Comment by helendallas** [comment]
On further checking with @KSnaddon We have decided that this should be put on hold for now as SANBI have removed open waterbody name from the NW6 map. We will see Add Open Waterbody Site as it is. On hold for now

**Comment by KSnaddon** [comment]
@helendallas I have discussed this with the wetland team.  It seems that open waterbodies won't ever be part of the National Wetland Map.  They will be classified as "depressions".  And there isn't a separate map of Open Waterbodies.  However, "Open Waterbody" continues to be a useful tag, as an ecosystem type of its own in FBIS.  

What we would like to see is that the FBIS codes for Open Waterbody records be generated in the same way as for wetlands, but allow for users to enter a User Name for the Waterbody, AND/OR fetch the River Name.  @dimasciput - does this make sense?  The User Waterbody Name would then be used to generate the FBIS site code (as for Wetland sites).

We don't need to add "Fetch Open Waterbody Name" as there won't ever be one (i.e. no spatial layer to provide this)

![Waterbody name](https://github.com/kartoza/django-bims/assets/91128958/555b0b3d-7bec-49b5-9489-6c1f2cd0519a)

**Comment by helendallas** [comment]
Checked and working, closing
