### ISSUE TITLE
Remove blank SA Veg Bioregion from Filter drop-down options

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3588]
The blank category needs to be removed in the SA Veg Bioregion

<img width="271" alt="Screenshot 2023-11-24 at 12 50 48" src="https://github.com/kartoza/django-bims/assets/45286876/7b026087-5834-4131-8f84-5f62a3713c88">

**Comment by KSnaddon** [comment]
@amyburness Please advise me on how to do this? The veg bioregion spatial layer is stored in the Kartoza workspace - can I access it to edit?  I don't want to publish a whole new layer, as that will impact on the filters.

**Comment by amyburness** [comment]
@KSnaddon 
1. the vegbiomoap is in SANBI schema so you should have access. 
2. the empty values come from this data that has no bioregion but is non-terrestrial vegetation. 
![image](https://github.com/kartoza/django-bims/assets/77841514/55555684-3a3e-450d-a8a7-08acf7048244)
What would you like to do assign it a bioregion of Non-terrestrial vegetation. Removing it would not be ideal.

**Comment by KSnaddon** [comment]
@amyburness  We can make this a "bioregion" called "Non-terrestrial: aquatic or estuarine"

**Comment by KSnaddon** [comment]
@amyburness Any news on this? Please make the blank bioregion "Non-terrestrial: aquatic or estuarine".

Or tell me how to do this?

**Comment by amyburness** [comment]
@KSnaddon I have emailed this to you.

@dimasciput will you need to resample the data as we have made updates?

**Comment by KSnaddon** [comment]
@dimasciput Update on this please?

**Comment by helendallas** [comment]
@dimasciput Please action in next sprint. I need this closed.

**Comment by dimasciput** [comment]
Updated

**Comment by KSnaddon** [comment]
Thaks @dimas - Checked and all good
