### ISSUE TITLE
Add Mean Annual Precipitation zones as a spatial layer

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3589]
@ks I think it would be useful to be able to visualise this layer. Please can you add it.

**Comment by KSnaddon** [comment]
@helendallas This is done on the Test Site.  Please check. I am also wanting to add the units to the legend for the map, and write these out for the filter, as for the other few layers that need more text (Rainfall Intensity Zones, etc).  I am hoping for some guidance on this from Amy (have put this on the ticket #3586 ).

**Comment by helendallas** [comment]
thanks @KSnaddon They are quite hard to see. Can you make the colour more intense and visible

Also no I information yet


<img width="1391" alt="Screenshot 2023-11-28 at 10 08 47" src="https://github.com/kartoza/django-bims/assets/45286876/25fd4b9e-ea30-44ae-a45f-888479856863">

**Comment by KSnaddon** [comment]
@helendallas Please also check the "i", as it is opening for me.

**Comment by helendallas** [comment]
Great thanks @KSnaddon Looks good

**Comment by helendallas** [comment]
Great working now

**Comment by KSnaddon** [comment]
@helendallas Can I publish to Production?

**Comment by helendallas** [comment]
yebo, then close the ticket. Thanks a mill;
