### ISSUE TITLE
Wetland site codes incorrect when uploaded as occurrence data csv file

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3591]
We uploaded wetland data using the csv occurrence data upload file.

These were coded as per a river site, which is incorrect. It should be a wetland site code. 

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=Wetland

**Comment by helendallas** [comment]
These codes are still incorrect. Have the ones that were uploaded been fixed? Testing or production?

**Comment by helendallas** [comment]
These have been fixed in production. I haven't tested upload again, will close ticket for now.

**Comment by helendallas** [comment]
@dimasciput 

Kate uploaded a csv file of wetland site and Site Codes did not update to use the User Wetland Name in the Code.  It updates when I edit the site and click Generate Site Code, but doe not do automatically when uploading the CSV file. 

@KSnaddon fyi

**Comment by helendallas** [comment]
@KSnaddon Have you checked lately if the csv upload is generating correct wetland site codes? Please revert soonest

**Comment by KSnaddon** [comment]
@helendallas Yes, I did this recently with the TMG wetland inverts, and it was working.

**Comment by helendallas** [comment]
Great thanks @KSnaddon Closing ticket then
