### ISSUE TITLE
Ecosystem type filter - issue when searching for using a site code

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3592]
If I select Ecosystem type = Wetland, and then add a site code, all ecosystem site types are returned. Is it possible to have the site code search work with the ecosystem type filter?

https://freshwaterbiodiversity.org/map/#search/g1drak/taxon=&search=g1drak&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=Wetland

<img width="1442" alt="Screenshot 2023-11-28 at 11 24 12" src="https://github.com/kartoza/django-bims/assets/45286876/aacf8936-5e53-4e88-8c79-9e14c1c9117b">

**Comment by helendallas** [comment]
Thanks @dimasciput Looks ok. Please deploy to production

**Comment by dimasciput** [comment]
Deployed to production
