### ISSUE TITLE
Uploading SANParks spatial layers to platform and creating filters

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3597]
Uploading SANParks spatial layers to platform and creating filters, metadata etc.

**Comment by helendallas** [comment]
Closing as actioned.

**Comment by helendallas** [comment]
I have reopened this ticket as the filtering has not been imp[lemented.
@amyburness @dimasciput Please action this on Monday for all existing layers that need filters

**Comment by helendallas** [comment]
Missing MPAs, 

<img width="240" alt="Screenshot 2024-05-12 at 16 29 11" src="https://github.com/kartoza/django-bims/assets/45286876/abf4301f-d44a-451e-97ce-5eba16ba1be2">

**Comment by helendallas** [comment]
@amyburness I have fixed these based on discussions with Dian and Judith. They only want the SANPars filters visible not protected areas.

Please see #3880 and add the MP as a group and filter.

@dimasciput Not sure if you need to do this?

**Comment by helendallas** [comment]
Revised 
![Screenshot 2024-05-16 at 09 47 23](https://github.com/kartoza/django-bims/assets/45286876/2ce74b4c-84c1-46ed-9cbf-12cc4d32d28f)

![Screenshot 2024-05-16 at 09 48 36](https://github.com/kartoza/django-bims/assets/45286876/fd196791-e433-4d06-a657-8b1c6a86d411)

Closing this ticket but please do #3880 soonest
