### ISSUE TITLE
Tsk 9. Implement user roles

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3598]
Develop a system that allows system administrators to grant different levels of access to different users, including SANParks staff

**Comment by helendallas** [comment]
@dimasciput Some clarity re this ticket:

This needs to allow SANParks administrators the ability to control which users get access to data:

There are essentially:

- Public (anyone on web)
- Private (SANParks only; maybe additional designated people)
- Sensitive (specific people only)

In the upload template we have included a field about Data Type, which is the above.

**Comment by helendallas** [comment]
From #4135 

When this is deployed, the filter will now also check the data type:

Public or empty data type:
All users will be able to see the data.

Private:
All the staff of the tenant site will be able to see the data. For example, Sanparks staff will be able to see Sanparks occurrence data with the data type set to private.
Additionally, I have added a new group called SensitiveDataGroup. If a regular user is added to this group, they will also be able to see private data.

Sensitive:
I have added a new group called SensitiveDataGroup. If a user is added to this group, they will be able to see sensitive data.

The new groups :

**Comment by dimasciput** [comment]
@helendallas I have deployed to staging.

**Comment by helendallas** [comment]
@dimasciput I discussed with client. They are happy to just work with the Data Type and not the Taxon (see #3605  https://github.com/kartoza/django-bims/issues/3605)
I need to test further

**Comment by helendallas** [comment]
@dimasciput This is half working: I added three datasets, Public, private and sensitive - as separate source references



![Image](https://github.com/user-attachments/assets/0d1c4b1a-735b-4576-9fd3-44f6bd578e2e)



Public data - fine

Private data - I can see this data even though I am not part of the PrivateDataGroup - not working

Sensitive data - I cannot see this data. - working



![Image](https://github.com/user-attachments/assets/64e4d3b7-6467-4ead-8a52-60a02ec44437)



![Image](https://github.com/user-attachments/assets/2d3a99b1-217f-4156-b21e-a4122dc96e17)

Very strange that other sites are visible though...bug????

**Comment by helendallas** [comment]
Question:

Can a dataset contain a mix of Public, Private and Sensitive data types? This is the most practical for SANParks, so that a dataset can be uploaded in one go, with sensitive data labelled Sensitive.

**Comment by dimasciput** [comment]
@helendallas Private data - I can see this data even though I am not part of the PrivateDataGroup - not working

Currently if you are staff or superuser, you will be able to see this even if you are not part of this group. Should I disable this?

**Comment by helendallas** [comment]
> Currently if you are staff or superuser, you will be able to see this even if you are not part of this group. Should I disable this?

Yes please @dimasciput I am sure SANParks would want this

**Comment by helendallas** [comment]
Separate ticket created for this #4212 

Rest is working thanks

**Comment by helendallas** [comment]
Cant test until private and sensitive data are uploaded, assuming it is working.
