### ISSUE TITLE
Tsk 15. Expand the ability to export to various file formats

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3604]
Expand the ability to export to various file formats. Further input needed from SANParks

**Comment by helendallas** [comment]
@dimasciput This isn't yet working. I see option to download as xls and csv, but I don't get email, and I get 4040 forbidden message when trying to access via link

**Comment by dimasciput** [comment]
@helendallas this should be fixed now

**Comment by helendallas** [comment]
Thanks @dimasciput Receiving notifications and emails. Closing ticket
