### ISSUE TITLE
Tsk 18. Develop functionality to add a confidence level associated with data

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3607]
Develop functionality to add a confidence level associated with data, including accuracy of identification, accuracy of locality, and reliability of sources (SANParks to explain further). It needs to include functionality to score the reliability of data points.

**Comment by helendallas** [comment]
This is covered by including confidence levels in the upload template including accuracy of identification, accuracy of locality. Reliability of sources will rather link to checklist.
