### ISSUE TITLE
Tsk 19. Develop functionality to allow a user to generate checklists

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3608]
Develop functionality to allow a user to generate checklists (csv and Pdf report) for selected parks and/or taxonomic groups with relevant information such as conservation status,endemism, etc. Possibly including a standard branded pdf report.

**Comment by helendallas** [comment]
Here is the template for the checklist.  

There are two parts 1) the csv/xls file as detailed below and 20 a summary report as a csv/xls or pdf?
A checklist would be done for a Park or Management Unit (essentially the user would select using the filter). 

I think the Checklist  should be available on the Side Panel below the individual biodiversity modules.

I was hoping to have enough funds to do a Summary Dashboard, which in my mind should come before the checklist, but Dian is worried we may run out of funds. Then we would navigate to Summary Dashboard and then select Download Checklist on this dashboard. Please give it some thought and perhaps an estimate of time for each.

So of 1)
The checklist would need to be a csv/xls file that is downloaded. 
@helendallas To add template once she has received feedback from Dian and Judith

**Comment by helendallas** [comment]
@dimasciput Here is the template for the checklist.

Normally the checklist would be created per National Park per Biodiversity Group. So a separate checklist for Birds, a separate chemist for Mammals etc.  It is very seldom that more than one biodiversity group would be included in the checklist.

Happy to discuss Summary Dashboard and Checklist with you before you start to work on this. It would be good to know the practicality of creating the Summary Dashboard First, and then from the dashboard you download the relevant checklist(s).

I may be able to provide extra funds on FBIS for this if need be as we would really like it as well. 
Here is the template

[Checklist template 2024_05_22.xlsx](https://github.com/user-attachments/files/15815645/Checklist.template.2024_05_22.xlsx)


Here is an example checklist xls file
[Example Checklist as xls file 2024_05_22.xlsx](https://github.com/user-attachments/files/15815776/Example.Checklist.as.xls.file.2024_05_22.xlsx)

**Comment by helendallas** [comment]
Please also see #3609

**Comment by dimasciput** [comment]
@helendallas can you give me example of the pdf report?

**Comment by dimasciput** [comment]
I have estimated this ticket to be 8, but this does not include the PDF due to its different layout and complexity.

@helendallas

**Comment by helendallas** [comment]
@dim ok, I have prepared one but just getting input from Dian before I attach here.

**Comment by helendallas** [comment]
For the pdf version - it depends a bit on what you are able to do.

Here is the general layout (Table ) but with look of the attached pdf if possible. The text in red below provides an explanation of the details.

Some checklists may have more attribute information such as NEMBA which are derived from the attribute of taxa. Problem is if we have a lot of attributes then it will not fit on a page.

![Screenshot 2024-06-13 at 13 43 20](https://github.com/kartoza/django-bims/assets/45286876/b8605109-0dd9-4ba3-81bc-066fcf0dcf4e)

[Camdeboo NP Bird checklist - example pdf.pdf](https://github.com/user-attachments/files/15818617/Camdeboo.NP.Bird.checklist.-.example.pdf.pdf)

**Comment by dimasciput** [comment]
@helendallas So currently, all the sources will be from GBIF, right? Because they are harvested from GBIF.

**Comment by helendallas** [comment]
Correct although they would like differentiation between iNaturalist records on GBIF and others if possible. When they start adding their data there will be more data sources

**Comment by helendallas** [comment]
@dimasciput Getting there thanks. Some points after discussion with Dian.

**Please include two additional columns** 

- Column 1: Park or MPA Name
- Column 2: Creation Date (Date when the checklist was created)

For GBIF data, it is very NB to include the specific Dataset that the GFIF data originates from. The dataset can be extracted using the Dataset Key, which is a unique key linked to a specific dataset.  I am not sure if this is already pulled down from GBFI, but if not it needs to be added please. 

See here for examples of datasets.
![Screenshot 2024-06-18 at 11 57 30](https://github.com/kartoza/django-bims/assets/45286876/89c9d0a2-2f59-403f-b42b-c4b2d1e69ac6)

**Comment by dimasciput** [comment]
Hi @helendallas 

I have added : 'Park or MPA Name', 'Creation date', and 'Dataset' to checklist.

I will add more items from the remaining list.

**Comment by helendallas** [comment]
Looking good. Can you name the xls/csv file with better name, at the moment it is blank.

Possibly Park Name/MPU and Module Checklist.xls

**Comment by dimasciput** [comment]
@helendallas I have added the functionality to generate the pdf. I will update the naming later, should be quick one.

**Comment by helendallas** [comment]
@dimasciput Something is not working here. I tested the download checklist which was working before for csv and xls, but now it's not.

Here is what I go sent.

[Checklist.csv](https://github.com/user-attachments/files/16143576/Checklist.csv)

**Comment by helendallas** [comment]
**Issues from when I could down the checklist:**
First column header should be: Accepted Scientific name and authority (including synonyms)
Only English common name should be pulled from GBIF - here there are multiple names so something is wrong

![Image](https://github.com/user-attachments/assets/e741b0c5-9da4-4a3b-9d73-97fa608dee27)

**Comment by dimasciput** [comment]
@helendallas, there are actually multiple English common names returned from GBIF for some species, e.g., Arctocephalus pusillus (Schreber, 1775) : 

![image](https://github.com/user-attachments/assets/6c5e2d77-53ee-4391-8b43-3e255c78914c)

There is no indication in the data which common name is the 'official' one.

**Comment by dimasciput** [comment]
@helendallas I have updated the title. Currently, the common names are still showing all of them. We can show just the first common name, as it is done on the taxon management page.

**Comment by helendallas** [comment]
Issues:

CSV file for checklist not being email from staging.  Request falls into a black hole :(

![Image](https://github.com/user-attachments/assets/97f3fbd5-14ac-42a0-a98b-9d99c7299601)



Cannot download from production - spins

**Comment by helendallas** [comment]
Managed download of csv, xls and pdf on staging. Waiting for feedback from SANParks

**Comment by helendallas** [comment]
Some comments thus far:


Please include Taxon Rank in the csv and xls as an additional Column.

Only include Species and Subspecies in the pdf.  (Exclude all higher taxonomic levels including Genus, Family etc.) 

-  if this will take long to implement, then please put on back burner as #3598  and #3605 should receive TOP Priority with the remaining budget

**Comment by helendallas** [comment]
@dimasciput Have you done anything further on the checklist ticket yet?

**Comment by dimasciput** [comment]
@helendallas updated on staging, please give it a try

**Comment by helendallas** [comment]
Thanks @dimasciput I will review with the client today

**Comment by helendallas** [comment]
Some feedback:

Please include Family in csv and xls as well.
We still need to check if all sources are making it into the PDF

**Comment by helendallas** [comment]
Also @dimasciput For the pdf, please make the display order alphabetical based on Accepted Scientific Name and Authority

**Comment by helendallas** [comment]
Sorry @dimasciput the issues with the pdf are sorted yet:

**PDF**

- [ ] Only include Species and Subspecies in the pdf. (Exclude all higher taxonomic levels including Genus, Family etc.)
- [ ] Sorted alphabetically based on scientific name in pdf.



![Image](https://github.com/user-attachments/assets/f5523c74-c660-483f-af7d-ada5f4b08333)




**XLS and CSV**
I cant check if family has been included as most checklists that have species and genera -  I added a new family but the staging is very slow so think you may be doing updates? I will try again tomorrow

**Comment by helendallas** [comment]
Okay, thanks @dimasciput I did another check - and it is working now.



![Image](https://github.com/user-attachments/assets/fad4767f-c6da-4c1c-9a5f-8edd2a292ee8)

Please deploy to production when ready

**Comment by helendallas** [comment]
Closing this now, Checklist issues will be created as new tickets
