### ISSUE TITLE
a BIMS instance should be able to access GeoNode layers from multiple nodes

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#361]
# Problem

Some national pubblic data sets are on LEDET GeoNode but are also needed in Healthyrivers. 

# Proposed solutions
1. duplicate the layers on healthyrivers GeoNode OR
1. put all common layers on maps.kartoza.com
  a. then the apps will need to be aware of multiple layer sources. 
  a.  and apply permissions for local layers but assume all remote layers are public
1. Access remote layers from wherever they are. e.g. Healthyrivers fetches some national layers from maps.kartoza.com and some from LEDET

**Comment by dimasciput** [comment]
implemented with different approach
