### ISSUE TITLE
Develop functionality to show occurrence data per month or per month sampled

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3610]
Develop functionality to show occurrence data per month or per month sampled (at the moment data are only shown per year in dashboards). User must be able to select  "Show by month" or " Show by year". Also See SASS dashboard which has data per sampling date

**Comment by helendallas** [comment]
Thanks @dimasciput That looks good. A user will just need to use the temporal filter to be able to see individual months.

<img width="910" alt="Screenshot 2024-05-07 at 11 31 38" src="https://github.com/kartoza/django-bims/assets/45286876/7cbddad2-810f-4923-9b9d-20ed64395695">

Closing ticket
