### ISSUE TITLE
Uploading occurrence data creating duplicate records

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3621]
I uploaded an edited dataset that had extra data, but instead of overwriting the old UUID, it created a new record.

 

Instead of 332 records w

e now have the original 194 + 322 = 526.

 

See highlighted site and records.

 
[Koen FBIS Testing Download 2.xlsx](https://github.com/kartoza/django-bims/files/13521005/Koen.FBIS.Testing.Download.2.xlsx)

https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=[%22Ruan%20Koen%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
This has been fixed in testing site

**Comment by helendallas** [comment]
@Janette-Lumley Please can you check these data are now correct with no duplicates. Please see ticket for details

**Comment by Janette-Lumley** [comment]
@helendallas there are no duplicates. There are 194 records instead of 332 so this must be the original data only?

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 
@dimasciput Please deploy fixes to production

**Comment by dimasciput** [comment]
deployed to production
