### ISSUE TITLE
Integrate Odonates (adults) into Invertebrates module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3624]
At the moment we have Invertebrates and Odonates (adult) as separate biodiversity modules.
 
We kept the latter separate so that we could separate out the Virtual Museum records, which are adults only.
 
Since then, we added the Data Source = Virtual Museum.
 
@dimasciput Is it possible to integrate the occurrence records Odonates (adult) into Invertebrates, but keeping them discoverable by tagging them Virtual Museum (in the same way we do with the Anurans).

Then the Invertebrate Odonate data tagged as VM taxa , can be harvested monthly from the VM website using the same API.

@dimasciput Please confirm if this is possible. Thanks

**Comment by dimasciput** [comment]
I have integrated the odonate to invertebrate in testing, please test it.

**Comment by helendallas** [comment]
@dimasciput I checked this when it was on testing, and made comments, but somehow these have been lost/not saved. Can you roll out to testing again so that I can check.

**Comment by dimasciput** [comment]
I have merged the invert and odonates in the testing, please give it a try. But the latest virtual museum data will only be available on production.

**Comment by helendallas** [comment]
Thanks, some points

Please restore the BDI Link that used to be associated with Odonate Adults as per Anuran Dashboard

<img width="375" alt="Screenshot 2024-04-08 at 10 13 36" src="https://github.com/kartoza/django-bims/assets/45286876/49a4a4f1-c951-4d7f-bce6-aa1fd26e0c67">


We are getting dulpicate Source References - this could be because of the harvesting of new data. I can merge them, but it would be better to make sure that all new data is added to the existing database.

<img width="666" alt="Screenshot 2024-04-08 at 10 07 47" src="https://github.com/kartoza/django-bims/assets/45286876/587a5307-5f2a-41bb-b4fa-6f3e65173759">

<img width="1370" alt="Screenshot 2024-04-08 at 10 21 29" src="https://github.com/kartoza/django-bims/assets/45286876/d8025245-4f3f-4203-8871-5265fcacc2c2">

**Comment by helendallas** [comment]
@dimasciput Any chance you can finalise this ticket and deploy to live today or tomorrow.  I am waiting to take a screenshot of the landing page dashboard for an article and I would prefer to have these integrated.

Its been a long time......

**Comment by dimasciput** [comment]
@helendallas 
> Please restore the BDI Link that used to be associated with Odonate Adults as per Anuran Dashboard

After investigating by checking the database, I found that the BDI link was overwritten when you uploaded the invertebrate taxa on December 5, 2023, with an empty BDI link. Here is the master file: https://freshwaterbiodiversity.org/uploaded/taxa-file/FBIS_Master_List_FBIS_Invertebrates_2023_12_05_Revised_with_odonates.csv.

To fix this, I will need to restore the database for all the invertebrates before the upload and only restore the BDI link.

I will do this on the next sprint, since it will take some time.

**Comment by helendallas** [comment]
Oh dear @dimasciput Can I not just add the BDI link to the taxon page? And if so where? I can get Janette to do this.

**Comment by dimasciput** [comment]
@helendallas I think it's better you add it to the csv, and then we can upload it on testing first.

**Comment by helendallas** [comment]
@dimasciput Would it work if I uploaded the odonata adult master list to the invertebrate module? Would it then overwrite only this taxa that were integrated into inverts?

I could test on testing site?

**Comment by helendallas** [comment]
@helendallas to revise and upload

**Comment by helendallas** [comment]
I have uploaded the invertebrates again with the BDI links added. All looks fine, Closing ticket
