### ISSUE TITLE
Check GBIF Harvesting

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3626]
The GBIF harvesting for Invertebrates stopped at record Trithemis stictica (2009/3564). I then cancelled it and started again.

Please keep an eye on it.

Question; there are 3875 invertebrate taxa in Taxon Management but only 3584 were shown on the harvest page.

Why is there this discrepancy?

<img width="1197" alt="Screenshot 2023-12-05 at 19 47 33" src="https://github.com/kartoza/django-bims/assets/45286876/b319e78d-8901-4026-a0c6-f2e6b7b194db">

**Comment by dimasciput** [comment]
@helendallas, the issue likely arises from species names containing unusual characters, probably from the CSV file.

![image](https://github.com/kartoza/django-bims/assets/1979569/7f7c12ba-e7e1-4ec7-874f-4ef23c5ca255)

**Comment by dimasciput** [comment]
@helendallas 

I have fixed the name manually.

> Question; there are 3875 invertebrate taxa in Taxon Management but only 3584 were shown on the harvest page.

The GBIF harvester only fetches species with taxa ranks of species, subspecies, and genus.
Here is the taxa management with that filter applied:

https://freshwaterbiodiversity.org/taxa-management/?selected=21&ranks=SUBSPECIES%2CSPECIES%2CGENUS&origins=&endemism=&cons_status=&parent=&validated=True

**Comment by dimasciput** [comment]
@helendallas, I actually found a lot of species names with this weird character. Could you fix them from the admin page?

![image](https://github.com/kartoza/django-bims/assets/1979569/45123e29-c565-4cd2-aa1f-076ac963df35)

**Comment by helendallas** [comment]
I can but why are they importing strangely. on the exes and csv file they are fine
<img width="417" alt="Screenshot 2023-12-06 at 07 39 57" src="https://github.com/kartoza/django-bims/assets/45286876/0f83d1ba-4327-4d2d-b4bc-584fb1f4d307">

**Comment by dimasciput** [comment]
![Screenshot 2023-12-06 at 9 19 33 AM](https://github.com/kartoza/django-bims/assets/1979569/fcb61e16-4ca0-4897-8718-49342ea28f45)

What application did you use to open the csv? Here's your csv I opened with 'Easy csv editor' https://apps.apple.com/us/app/easy-csv-editor-mobile/id1634410417

**Comment by dimasciput** [comment]
@helendallas

**Comment by helendallas** [comment]
I created the csv in xls on my apple Mac

**Comment by dimasciput** [comment]
@helendallas, did you use Excel? I just tried Excel on a Mac, converted the XLS to CSV, and it worked fine.

**Comment by helendallas** [comment]
Yes

**Comment by helendallas** [comment]
My csv file also looks fine, so something went wrong in the uploading of taxonomic data which I did yesterday

**Comment by helendallas** [comment]
For some reason the harvest I started a few days ago and the one I started yesterday have both stalled on Trithemis stictica

**Comment by helendallas** [comment]
I have cancelled the second upload session. I don't think the issue can be the strange characters. My csv file looks fine and the block come on the species Trithemis stictica. Please can you check and revert. I am out for most of the day but would be keen to get this done. 

Let me know if I must upload the csv file again

**Comment by helendallas** [comment]
@dimasciput This finished successfully. Closing this ticket now
