### ISSUE TITLE
3. Customised FADAtims Taxon Management website

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3633]
Customised FADAtims Taxon Management website with branding and logo as per the current FADA webpage (http://fada.biodiversity.be). It needs a landing page hosting main information about the system. (The customisation will be undertaken by Astrid with guidance from Dimas).

**Comment by helendallas** [comment]
@dimasciput This will require training of Astrid. Has @amyburness written documentation for this at all for other projects? If so, @amyburness please can you share here or point me to where they are.

**Comment by dimasciput** [comment]
@helendallas, the document for customization is here: https://kartoza.github.io/bims-website/administrator/customisation/

I think we can add more guides here. Let me ask someone else to help with this.

**Comment by helendallas** [comment]
As discussed 22 Aug 2024, @dimasciput is going to spin up revised menus, that @schmikloi  can then edit. 


Landing Page = Home . The landing page editing guidelines documents are available here: https://kartoza.github.io/bims-website/administrator/customisation/
These may need more work to from Kartoza side, but lets see how Astrid finds them.


On the Landing Page - the user/expert will Sign up and Login

![Image](https://github.com/user-attachments/assets/39185171-f629-4c03-8e7b-199b0f04ab90)


After logging in they will be taken to Taxon Management  (= FADA Database) - The main engine of FADA

![Image](https://github.com/user-attachments/assets/23f7a578-8060-4dbf-8e9a-a79aa454ba4d)



Details of logo and colour have been provided by Astrid

![Image](https://github.com/user-attachments/assets/7537d353-26a7-4f26-9aab-b0373d279e09)






The current FBIS **About** Page - Becomes the **FADA History** page - Dimas to revise wording - Astrid to add content. This is done here: **Admin-Flat Pages**

The current FBIS **Citation** Page - becomes the **FADA Experts and Groups** page. **Admin-Flat Pages**


![Image](https://github.com/user-attachments/assets/dba06ee3-da41-4369-88cf-5d848146a876)

There is also a Help Page to provide manuals, tutorials, etc. This is done here: **Admin-Flat Pages**

Astrid to provide and add content to these pages.

@dimasciput Should @schmikloi wait until the FADA production is ready?


This ticket supersedes #3886 which I will now close

**Comment by helendallas** [comment]
Thanks @dimasciput Looking good.

Should these non-FADA flat pages be deleted here?  however if the admin can turn on or off then not necessary, as may e useful to have extra options?


![Image](https://github.com/user-attachments/assets/7833ff1c-3d0d-4d5c-b97e-e36707e69310)


Also can you explain functionality we can use display in navbar. - I assume you are making this something admin can manage in the future. So if Astrid wanted to add /citation-guidelines/

I cant see in Change flat page where to do this

**Comment by helendallas** [comment]
@schmikloi Can you check staging and confirm when you are happy. then once @dimasciput deploys to production, you can add text etc.

**Comment by schmikloi** [comment]
looks good and I think I can handle the text editing etc within the flat pages!

still the menu bar needs a bit of editing
- the tiny logo on the left should be the one without "infra" 
- the current "About" could be deleted
- "Database" should be renamed into "FADA Database"
let me know if I can change this on my own?

please also let me know where I can edit the landing page? thanks!

**Comment by dimasciput** [comment]
@schmikloi 

> - the tiny logo on the left should be the one without "infra"
> - the current "About" could be deleted
> - "Database" should be renamed into "FADA Database"
> - let me know if I can change this on my own?

I have updated these

here's the admin page for the landing page

https://fada.sta.do.kartoza.com/admin/bims_theme/

Perhaps I can create the initial landing page design, and then you can edit it? However, please remember that the landing page is static, so there won't be any real-time data, except for the module summary, which I've disabled for FADA because it contains occurrence records data.

**Comment by schmikloi** [comment]
Thanks a lot!!!
Can I already start putting content on the flat sites?

**Comment by dimasciput** [comment]
@schmikloi yes you can do it now.

**Comment by schmikloi** [comment]
update: I have started to add content, but still need to figure out why for example different font types are displayed on the two sites;
the landing page seems to be a bit more complicated though... still need to look into this.

**Comment by dimasciput** [comment]
@schmikloi I can clean up the font later to improve it.

For the landing page, could you provide an idea of the content for each section? I will add the initial content based on that.

You can check out SANParks here: https://sanparks.do.kartoza.com/

**Comment by schmikloi** [comment]
I have made a quick page preview; please check if this is feasible; maybe the second text section will not be needed need after all...

[landing page.pdf](https://github.com/user-attachments/files/16909388/landing.page.pdf)

**Comment by dimasciput** [comment]
@schmikloi I have updated the landing page

**Comment by schmikloi** [comment]
Perfect, looks very cool already ! Will try if I can edit it now on my own. Thanks a lot!

**Comment by dimasciput** [comment]
@schmikloi you can edit the contents here https://fada.sta.do.kartoza.com/admin/bims_theme/landingpagesectioncontent/

**Comment by dimasciput** [comment]
You can update the partners logo, name and link here https://fada.sta.do.kartoza.com/admin/bims_theme/partner/

I have updated the [FADA Experts & Groups](https://fada.sta.do.kartoza.com/pages/fada-expert-groups/) & [FADA History](https://fada.sta.do.kartoza.com/pages/fada-history/) page as well.

**Comment by helendallas** [comment]
I am assuming you are happy with this @schmikloi and that you have managed to update the website as required - with the exception of spacing between Freshwater Animal and Diversity Assessment. which @dimasciput will fix.

**Comment by helendallas** [comment]
Closing by way of #4376
