### ISSUE TITLE
5. Develop functionality to allow general users (non-experts) to use the Taxon Management System

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3635]
Develop functionality to allow general users (non-experts) to use the Taxon Management System. 
General users should not be able to edit anything – so read only. 
Users (including those not signed up) need to be able to query and browse through the FADAtims, and search for specific species, taxon groups or taxon related information.

**Comment by schmikloi** [comment]
the public website (not logged in) should see all the taxagroups, so that the public can choose where to look at (read only); once an expert logs in, he see only their taxagroup, which they can then also edit.
do you agree @helendallas?

**Comment by helendallas** [comment]
I agree that public can see all taxagroups, but when an expert logs in they should also be able to see all taxagroups. 
However, they should only be able to edit their own group.

**Comment by schmikloi** [comment]
Ok, I agree with Helen, but maybe they could then see their taxagroup (which they can edit) on the top of the list (or marked in a color)

**Comment by helendallas** [comment]
@schmikloi That makes sense. So the experts group is at the top and clear, but they still have access to other groups.

@dimasciput Is this possible?

**Comment by dimasciput** [comment]
@helendallas Can you test again? This week, the staging might be unstable because I am currently working on it.

**Comment by helendallas** [comment]
@dimasciput Still not working. Not to worry I am just working on tickets while I have the time. FADA scheduled for 20-24 June sprint. Astrid and I want you to have comments etc ready.

**Comment by dimasciput** [comment]
@helendallas can you test it again please

**Comment by helendallas** [comment]
Thanks @dimasciput This wis working now. closing ticket
