### ISSUE TITLE
Mobile app final fixes

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3637]
FBIS Mobile App testing 13 December 2023 on iPhone

1. Add site
When typing in user site code the text box becomes hidden by the keyboard making it difficult for the user to see what they are typing. 

https://github.com/kartoza/django-bims/assets/44292029/4629bce5-e27d-4c32-8cba-58ea6f3c2a7a

2. Add record
It would be helpful to have a ‘close’ or ‘back’ option for this panel.
(Tapping the map causes this panel to disappear when it’s for an existing site, but not for a site that a user has just created).

Helen’s comment (android): Mine got stuck and I go back at all. 

 
![Picture 1](https://github.com/kartoza/django-bims/assets/44292029/d24f9fad-600c-4cf2-9886-6c513dd2a5b8)

3. Add record
Grey text in the ‘Observed taxa’ and ‘Add abiotic data’ is too light for the user to see.
Please make it a little darker.

 
![Picture 2](https://github.com/kartoza/django-bims/assets/44292029/49c54936-1956-4c07-8984-79563203dd9c)

4. Add record
Please remove the word ‘Add’ from the text ‘Add Abiotic data’.

5. Add record
Can you add ‘Unspecified’ to the list of source references. If a user taps to add a source reference, but then decides not to, there is currently no way to get back to ‘unspecified’

Helen’s comment (android): I tapped the source reference again and could select unspecified.

6. Add record
Why can I only add SASS data to a new site that I create, but not to a site that already exists?
Users should be able to add SASS data to existing sites.

Helen’s comment (android): I can add SASS to an existing site

 
<img width="657" alt="Screenshot 2023-12-14 at 11 39 46" src="https://github.com/kartoza/django-bims/assets/44292029/8650612b-8cae-40a2-bf3b-9963da7578fb">

7. Add SASS button
I think it would be cleaner if the ‘Add SASS’ button could be moved up to be in the same row as plants. Also I think the formatting (button size, font style and size) of this button should match that of the other buttons, but I do think it’s good to have it a different colour to the fish, anurans and plants

**Comment by dimasciput** [comment]
@jeremyshelton 

> Add record
> Why can I only add SASS data to a new site that I create, but not to a site that already exists?
> Users should be able to add SASS data to existing sites.
> 

You can only add SASS to a river site, make sure you select the river site.

**Comment by jeremyshelton** [comment]
@dimasciput you are correct: I was indeed trying to add to a site not on a river.
My mistake. Please ignore this one.

**Comment by dimasciput** [comment]
@jeremyshelton I have deployed the fixes to testingflight, please update your app.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Will test and revert asap.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I have tested this and ammonia happy that all of the issues have been fixed.
Closing ticket and happy for this to be the final version (unless @KSnaddon detects any other issues on the android version)
