### ISSUE TITLE
6. Develop FADA expert validation functionality and workflows

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3644]
Experts (and users) need to be able to add a new Taxon to FADAtims, using a form on the website (including name, evidence, contact details, Reference, photographs), which is then passed on to (level 3), level 2 and level 1. 
If level 1 agrees the taxon is validated/accepted and added to FADA. An expert/user needs to be able to upload supporting evidence when proposing a new taxon be added. This needs to include the uploading of source references, including pdfs. (modify existing Source Reference system). The source reference system needs to include keywords such as species name, that allows for future querying.

**Comment by helendallas** [comment]
This has been shown to us in the meeting. It will require testing. @schmikloi I will start setting up some mock levels and experts on the FADA staging

**Comment by helendallas** [comment]
From #3884 

For example, there are three taxon groups: Taxon Group A, B, and C. Taxon Group A is the parent of B, and B is the parent of C.

Workflow Steps:

A new taxon is added to Taxon Group C where it is initially validated by the corresponding experts.

Once initially validated, the taxon appears in Taxon Group A for final validation by the experts there.

After final approval in Taxon Group A, the taxon is considered fully validated.

[New Taxon] --> [Taxon Group C (Initial Validation)] --> [Taxon Group A (Final Validation)] --> [Validated]

I am closing the other ticket as repetitive #3884

**Comment by helendallas** [comment]
Closing ticket as @helendallas to show @schmikloi workflows. Can be done outside github
