### ISSUE TITLE
Existing wetland site codes need to be updated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3662]
at the moment because of #3591 the wetland sites codes on FBIS are incorrect.

Can these be fixed in the backend?

**Comment by dimasciput** [comment]
@helendallas yes let me create a script to fix this

**Comment by dimasciput** [comment]
I have updated the existing site codes

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, closing ticket
