### ISSUE TITLE
Please rename Occurrence in Abiotic Module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3667]
Please rename "Occurrence" to (Occurrence - Biodiversity module)

<img width="239" alt="Screenshot 2024-01-29 at 09 30 39" src="https://github.com/kartoza/django-bims/assets/45286876/8e579498-ce66-4a30-812a-2935f3333089">

**Comment by dimasciput** [comment]
Updated in testing and production

**Comment by helendallas** [comment]
It might be better to delete Occurrence - Biodiversity module in the drawer header and just leave as Abiotic Module. Then when the user opens the drawer they then see the Occurrence - Biodiversity module, which by default is selected

<img width="302" alt="Screenshot 2024-01-30 at 10 46 34" src="https://github.com/kartoza/django-bims/assets/45286876/9a0398a5-60cf-444a-b984-4d1929ca72ef">

**Comment by dimasciput** [comment]
@helendallas I have deployed this to production

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket
