### ISSUE TITLE
Revise label (and attribute) for river in Wetland Hydrogeomorphic Type

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3668]
This needs to be revised

River needs to be " **Under revision**"

<img width="244" alt="Screenshot 2024-01-29 at 09 34 09" src="https://github.com/kartoza/django-bims/assets/45286876/0606846e-bd93-4f14-a15b-993ea3d3ba44">

**Comment by KSnaddon** [comment]
@dimasciput or @amyburness - Can you let me know when this will be done please?  Instead of "River", we need to have the type "Under revision".

**Comment by amyburness** [comment]
@dimasciput 
The layer data has been updated can you update the BIMS side 
![image](https://github.com/kartoza/django-bims/assets/77841514/72384782-c7a5-4cd3-b8c0-6c1b47c33d6f)

**Comment by dimasciput** [comment]
thanks @amyburness ,

@KSnaddon I have updated the label in the fbis as well

![image](https://github.com/kartoza/django-bims/assets/1979569/9d381e3b-f0f6-4bad-8bef-48b25015217e)

**Comment by KSnaddon** [comment]
Thank you @dimasciput and @amyburness !
