### ISSUE TITLE
revise header etc in Overview table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3671]
At the moment there is repetition in all single site dashboards, please revise

Keep top Overview, 

delete " Overview Site details"

Rename Overview in grey to Site details

<img width="451" alt="Screenshot 2024-01-29 at 09 41 22" src="https://github.com/kartoza/django-bims/assets/45286876/bf27b64b-5d51-4922-bb1b-c64e364597fb">

**Comment by helendallas** [comment]
Thanks, please also Rename Overview in grey to Site details (as detailed above), It still reads Overview

<img width="440" alt="Screenshot 2024-04-08 at 10 50 51" src="https://github.com/kartoza/django-bims/assets/45286876/16953e68-94b2-4712-b4e5-8823d22939b8">

**Comment by dimasciput** [comment]
@helendallas

**Comment by helendallas** [comment]
Thanks @dimasciput Look good, please deploy to production

**Comment by dimasciput** [comment]
Deployed to production, will check the other dashboard later

**Comment by helendallas** [comment]
Checking all dashboard sin production:

Single site Fish - fine
Single site Invertebrate - fine
Single site Algae - fine
Single site Anurans - fine
Single site Plants - fine

Single site SASS - fine
Single site Water temperature - fine
