### ISSUE TITLE
Create new Wetland Characteristics dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3672]
We need a new dashboard that would be above the SASS dashboard in the Side Panel Dashboard, that would provide data for a Wetland Polygon that a user has selected (see #3673 ) - this should resemble the look of a single site dashboard on the side panel dashboard.

<img width="496" alt="Screenshot 2024-01-29 at 10 18 59" src="https://github.com/kartoza/django-bims/assets/45286876/4464546e-198d-478e-8a69-aee9ea0edf8e">

**For now it would just be the Map and the information Overview Table.**

<img width="452" alt="Screenshot 2024-01-29 at 10 13 14" src="https://github.com/kartoza/django-bims/assets/45286876/6003750a-9a45-4fce-9f65-a86152a89695">

**The geocontext data would be derived by using the centroid point of the wetland polygon.**

If possible it would be good to remove river specific details from the overview table, as follows:

<img width="235" alt="Screenshot 2024-01-29 at 10 14 12" src="https://github.com/kartoza/django-bims/assets/45286876/98108d11-c248-4f05-b00f-4d0e82d23fe1">

<img width="172" alt="Screenshot 2024-01-29 at 10 14 24" src="https://github.com/kartoza/django-bims/assets/45286876/40a64687-3f64-4170-bf85-7c1b67c5d471">

**Later we would add in summary statistics once this functionality has been developed in the SANparks project**

@KSnaddon

**Comment by dimasciput** [comment]
@helendallas @KSnaddon 

I've implemented this on testing, but there are some caveats because we don't know where the wetland layers are located. So, when users click on the wetland layer, a dashboard button will appear. Clicking on it will open a side panel to display the geocontext data. However, since the data is fetched in real-time, it may take some time to display everything. Nonetheless, the data is stored in the database, which means if someone clicks on the same layer again, it will load faster.

https://github.com/kartoza/django-bims/assets/1979569/d29b3093-81b5-4818-9519-85ef120e69c6

**Comment by KSnaddon** [comment]
@dimasciput This is looking good.  The wetland layers are mostly on the SANBI workspace.

**Comment by dimasciput** [comment]
@KSnaddon, what I mean is the location of the wetland on the map. So, I think it's better for users to just click on the wetland data, and then the system will fetch the geocontext data. This way, the data will grow organically, instead of us pre-fetching all geocontext data for all the wetlands.

**Comment by helendallas** [comment]
@KSnaddon Please confirm that you are happy with this? If yes, I will close the ticket. Thanks

**Comment by KSnaddon** [comment]
@dimasciput and @helendallas I am happy with the dashboard as it stands.  It would be great to build on this at some stage, and to place it with the other dashboards, so it doesn't stand on its own.  I am keen to see what is developed for the SANParks reserves, as it will probably look similar.

**Comment by helendallas** [comment]
Thanks @KSnaddon . I see it is already deployed to production, so closing ticket
