### ISSUE TITLE
We need to be able to select and display data based on a wetland polygon

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3673]
We need to be able to select a wetland polygon on the NWM layer, to return geocontext data as per ticket #3672 , even if there is no occurrence data , and all return data if there is occurrence data.

The Wetland Characteristic dashboard need to be visible, even if there is no occurrence data.

<img width="218" alt="Screenshot 2024-01-29 at 10 03 18" src="https://github.com/kartoza/django-bims/assets/45286876/ddc950a9-9f43-4ecf-bd35-9e9d52710767">

**Comment by dimasciput** [comment]
@helendallas this has deployed to testing, see how it works here https://github.com/kartoza/django-bims/issues/3672#issuecomment-2041072436

**Comment by helendallas** [comment]
Is there a way to open a detailed dashboard that resembles the existing dashboards rather than have a pop up one as the side panel.

Also if I choose click on a site in the wetland polygon, it starts to open the site but is then overridden by the. wetland dashboard.

**Comment by dimasciput** [comment]
@helendallas 


Yes, it's possible, though a bit confusing. Could you confirm the workflow, please?

- The user first needs to display the wetland layer.
- When the user clicks on the wetland layer, a popup will appear with the layer's information, similar to other layers. Should we also automatically display the side panel, or should we add a button in the popup to show the side panel?
- If the user clicks on an existing site that is a wetland site, should the wetland dashboard button appear? If the site is not a wetland, even though it is on the wetland layer, should the wetland dashboard button not appear?

**Comment by helendallas** [comment]
Thanks @dimasciput Agreed, it is a bit confusing. Let me chat to @KSnaddon and figure out the best workflow.  

My feeling is the following:
If a user has the Wetland Map spatial layer visible, and they click on a wetland polygon, tthen the Side Panel would open and the Wetland Dashboard would be an option for them to select, as well as all the other dashboards.
If a user has the Wetland Map spatial layer visible, and they click on a site in wetland polygon, then the Side Panel would open and the Wetland Dashboard would be an option for them to select, as well as all the other dashboards.
If a user has the Wetland Map spatial had not been selected and the layer was not visible, then the Wetland dashboard would be greyed out? Not sure of this one?

@KSnaddon what are you thoughts on this.

**Comment by helendallas** [comment]
Please see ticket #3672 

@KSnaddon Please see my comments above. We have limited budget to do much here, but please revert if you are happy to leave as is for now.

**Comment by helendallas** [comment]
Closing by way of other ticket. Deployed
