### ISSUE TITLE
MiniSASS link is broken

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3674]
Link is not working 

<img width="566" alt="Screenshot 2024-01-29 at 11 42 48" src="https://github.com/kartoza/django-bims/assets/45286876/1f1a5e37-ab8d-4e56-8931-da16ecc52be3">

Please see ticket #3322

**Comment by dimasciput** [comment]
@helendallas, we have updated this on the staging site. MiniSASS has changed how they display the layers, we had to update the code on the FBIS to accommodate these changes.

**Comment by helendallas** [comment]
The icons need to be the crabs as per mini SASS so that we an differentiate from our sites. Is this possible as it was before.

![Image](https://github.com/user-attachments/assets/31cf6369-9683-4ff9-912e-36d4969e5cb6)

**Comment by dimasciput** [comment]
@helendallas This is fixed, I also added a legend
![image](https://github.com/user-attachments/assets/2a55d340-a730-44e1-b138-99415aeaa259)

**Comment by helendallas** [comment]
Thanks @dimasciput The overview dashboard does not look great. Please can you aim to tackle #3322 

If the FBIS funds run out I will find alternative. thanks

**Comment by dimasciput** [comment]
@helendallas It might take a couple of days to implement that. Let's discuss it there. But I think we can deploy and close this issue, right?

**Comment by helendallas** [comment]
Yes, deploy now is fine. No rush on the other, I just think it would be nice to do.
