### ISSUE TITLE
Add a page to facilitate boundary uploads

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3681]
For #3653

**Comment by helendallas** [comment]
@dimasciput Has this been implemented? Is it SANParks or FADA?

**Comment by dimasciput** [comment]
@helendallas Yes, it has been implemented for all. This boundary is used for fetching species, so it will not be used a lot, probably only once in the beginning, and only by admin.

To go to the page, first go here: https://sanparks.do.kartoza.com/harvest-species/, and click on the layer uploader.
