### ISSUE TITLE
Implement a user interface to allow species to be designated as the parent point for retrieving species data from GBIF

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3682]
For #3653

**Comment by helendallas** [comment]
@dimasciput Is this not the FADA project? Please change if it is, thanks

**Comment by dimasciput** [comment]
@helendallas It was initially used by sanparks to fetch GBIF species. I have implemented this and will now close it.

**Comment by helendallas** [comment]
Implemented by Dimas. Closing ticket
