### ISSUE TITLE
replace django db password with something secure

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#369]
the current username and password are really insecure

they shoud not be stored in plain text anywhere

**Comment by dimasciput** [comment]
What do you suggest for username and the password? We can easily change those in rancher, and rancher is pretty secure

**Comment by timlinux** [comment]
We can do this in the rancher orchestration….for LEDET we will need to manually go and add the user too since the database is persistent.

**Comment by timlinux** [comment]
@dimasciput just pick a user and password and share it back to @gavin and Rancher orchestration.

**Comment by dimasciput** [comment]
also should be documented in https://github.com/kartoza/django-bims/issues/254
