### ISSUE TITLE
Master List: add variety and form in addition to subspecies

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3691]
At the moment we have subspecies.

We also need to be able to upload variety and forma.

@helendallas to update dropdown in master list upload template

@dimasciput to update on the Upload Taxonomic data side

**Comment by helendallas** [comment]
Variety has been added.

Form still needs to be added.

Not in Taxon Management filter so I assume not in 

<img width="548" alt="Screenshot 2024-05-07 at 12 28 10" src="https://github.com/kartoza/django-bims/assets/45286876/e29a007d-ae0e-40cf-b4ce-f34595069ba3">


Where do I access Taxonomic Rank in BIMS? Some like Life and Cultivar Group are not needed. 

<img width="278" alt="Screenshot 2024-05-07 at 12 29 27" src="https://github.com/kartoza/django-bims/assets/45286876/3c56aa0e-21d2-4d75-9291-dc074ff8526a">

**Comment by dimasciput** [comment]
@helendallas The list is currently hard-coded because it does not change often, simplifying the implementation. I have removed the cultivar and life categories. You should see the variety and form in the taxa management filter and taxa page now.

This is only deployed on staging for now.

**Comment by helendallas** [comment]
Thanks @dimasciput Please deploy to production
