### ISSUE TITLE
Implementation of Feedback Mechanism for Taxon Data Management

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3696]
Ideally Level 2 and 3 experts feed updates to the Level 1 global FADA expert, with supporting evidence. This is then evaluated and either accepted or rejected (with reasons) to the global FADAtims.

**Comment by helendallas** [comment]
@dimasciput I assume this will be revised since there is only Level 1 (Global) and Level 2 (Country/region)

**Comment by dimasciput** [comment]
@helendallas yes this ticket is not relevant anymore, I will close this ticket
