### ISSUE TITLE
Landing page icons

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3698]
@dimasciput 
Would you mind replacing the current black icons on the landing page with these blue ones?
Thanks
![7](https://github.com/kartoza/django-bims/assets/44292029/2b8cccb9-86bb-4836-88fa-742659e64d51)
![8](https://github.com/kartoza/django-bims/assets/44292029/947a165d-8b36-43e6-8d00-9deb7ee49ed7)
![9](https://github.com/kartoza/django-bims/assets/44292029/b95634f6-44fc-47f4-95b5-1582c42d5fc4)
![10](https://github.com/kartoza/django-bims/assets/44292029/0090b3e9-3dec-467b-9e51-acd63c03aca2)
![11](https://github.com/kartoza/django-bims/assets/44292029/bc43e889-fec7-4bbb-817a-fbaffdb462d3)

**Comment by dimasciput** [comment]
@jeremyshelton, it will look like this; see the first two icons.

![Screenshot 2024-02-09 at 11 16 03 AM](https://github.com/kartoza/django-bims/assets/1979569/212ce09f-8e19-4685-967a-b1ab18c2dfb4)

If you don't want the icons to look smaller, please remove the padding from the icons.

**Comment by jeremyshelton** [comment]
@dimasciput does this work better?

![7](https://github.com/kartoza/django-bims/assets/44292029/99a80e53-61db-4ccc-97c6-35b4deaa92c1)
![8](https://github.com/kartoza/django-bims/assets/44292029/e0ba7724-6466-4683-9bb6-e9d14acd7186)
![9](https://github.com/kartoza/django-bims/assets/44292029/bd7d74c4-1fbf-4f04-a929-26f4f31d0197)
![10](https://github.com/kartoza/django-bims/assets/44292029/f0f67763-b43c-4cfb-83b0-58333c420290)
![11](https://github.com/kartoza/django-bims/assets/44292029/4ce900ec-7d51-4b9c-a0cc-4ec27e3d1f85)
