### ISSUE TITLE
Upload tab in Admin not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3704]
The upload tab in the admin menu is not clickable for me.
<img width="357" alt="Screenshot 2024-02-13 at 07 15 44" src="https://github.com/kartoza/django-bims/assets/44292029/233c5835-424c-4f70-93d3-ae3c28fb37b9">

**Comment by dimasciput** [comment]
@jeremyshelton, that's not a link, it's a header section, which means those sections are for upload only.

**Comment by jeremyshelton** [comment]
OK. thanks for the clarification.
