### ISSUE TITLE
After editing biodiversity data - I am not taken to abiotic and then source reference pages. gets stuck

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3721]
I tried to UPDATE INVERTEBRATES DATA FOR SITE G4OUDE-DSCAB

https://freshwaterbiodiversity.org/site-visit/update/422907/

I needed to change percentage to number.

I clicked Submit, but it didn't work and I got stuck on the screen unable to edit data.

**Comment by dimasciput** [comment]
@helendallas this is fixed in production and testing
