### ISSUE TITLE
Can you increase the size of the sites - very hard to see at most zoom levels

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3732]
Please see how hard it is to see a site.

<img width="1190" alt="Screenshot 2024-03-05 at 16 02 19" src="https://github.com/kartoza/django-bims/assets/45286876/17ac52ed-3034-4772-9880-018d694dd823">

**Comment by dimasciput** [comment]
@helendallas I have updated the size, please try it again

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good closing ticket
