### ISSUE TITLE
Deleting site occurrence data is not being updated in dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3761]
I deleted data for 2013-10-16. but it still shows on the dashboard. even though when you click one it, it is not there and I get the 
404 - PAGE NOT FOUND

I think this is a repeat offender.

![Screenshot 2024-03-18 at 09 23 48](https://github.com/kartoza/django-bims/assets/45286876/ccee7a96-980c-4024-b14c-39e634328fcf)

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=H1MOLE-DETOI&siteId=9907&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=9907&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
deployed in testing

**Comment by helendallas** [comment]
Thanks @dimasciput Looking. good, please deploy to production after training

**Comment by dimasciput** [comment]
Deployed to production
