### ISSUE TITLE
Mobile app data sync issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3772]
Syncing records using the hamburger (top right) > List unsynced data > sync records does not seem to be working? In other words data synced with this workflow are not making it onto the FBIS main site?

**Comment by helendallas** [comment]
@jeremyshelton Is this working now? If so please comment and close the ticket. I assume it is iOS

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 
Yup. This is working now (on apple).
Closing ticket.
