### ISSUE TITLE
We need defined permissions and roles

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#3775]
Potentially have these permissions:
	- per taxon or
	- per dataset or
	- per source or
	- pre/post embargo period
	- other permission / role based restraints
	- or organisation based

And these roles:

- Super admin (can do anything on any organisation)
- Admin (can do anything within an organisation)
- Editor (can change existing records)
- Taxon Expert
- Taxon Editor
- GIS Manager
- Organisation User
- Public User

**Comment by helendallas** [comment]
No longer relevant
