### ISSUE TITLE
FBIS speed issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3777]
FBIS is very slow to load and navigate.

**Comment by helendallas** [comment]
Thanks @dimasciput Seems better now, closing ticket

**Comment by jeremyshelton** [comment]
@dimasciput I am finding that data queries and dashboards are loading noticeably more slowly than they did in the past.
This has a big impact on the user experience. Is there any way to speed this up? Thanks

**Comment by dimasciput** [comment]
@jeremyshelton Hi, you might have hit the cache in the past, which is why it was faster. If you open your URL again, it should be faster. Other than that, there hasn't been much change in the query. I tested it, and it seems to have the same speed as before. The speed also depends on the size of the data.

**Comment by jeremyshelton** [comment]
OK copy that. Will try it after refreshing the cache.
Thanks Dimas

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 
Data searches are still going much more slowly than in the past, even after hard refresh. 
If we can't speed this up then maybe we can add a 'timer wheel' to the 'search result tab' to reassure the user that their query is being processed? (at present, it says 'loading' next to sites and taxa, but a timer wheel would be clearer).

**Comment by helendallas** [comment]
@jeremyshelton When FBIS is migrated to the multi-tenant system the speed for reading will improve.

Perhaps we can park this for now as we intend migrating to staging in the next FBIS sprint 0 then we check that everything looks good and works, then Dimas will migrate production as well.

Comments @jeremyshelton

**Comment by jeremyshelton** [comment]
@helendallas OK cool. Agreed.
