### ISSUE TITLE
Water temperature data listed as available when actually not uploaded

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3782]
For some sites, water temperature data have been uploaded for 2008-2013, then nothing for 2014, 2015, 2016, 2017, and then uploaded for 2018 and 2019.

In the selection drop-down, all years are shown even when there is no water temperature data. 

![Screenshot 2024-03-27 at 10 23 56](https://github.com/kartoza/django-bims/assets/45286876/33d0fae4-4b74-44b6-b59d-6d05db716d29)

If these "phantom" dates are selected the graph spins as it cannot produce the stats etc as no data have been uploaded. Here is an example.

https://freshwaterbiodiversity.org/water-temperature/9909/2016/?taxon=&search=G2EERS-JONKE&siteId=9909&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%2C%22gbif%22%2C%22virtual_museum%22%5D&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=9909&orderBy=name&polygon=&dst=&ecosystemType=River%2CWetland%2COpen+waterbody%2CUnspecified&startDate=2016-01-01&endDate=2016-12-31

Please fix to make only years where water temperature data have been uploaded shown on the selection drop-down.

**Comment by dimasciput** [comment]
Deployed in testing

**Comment by helendallas** [comment]
Thanks @dimasciput Looks great, please deploy to production after training

**Comment by dimasciput** [comment]
Deployed to production
