### ISSUE TITLE
Make Source Reference Available to ordinary Users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3783]
At the moment only FBIS Administrators can see Source References.

It would be useful for a user to be able to navigate the Source References and to be able to add a Published Report (pdf). When a user uploads data using the Occurrence Upload template, the link to the document needs to be added to FBIS prior to upload.  

In the longer term we would like users to be able to prepare occurrence data files and be able to upload reports as pdfs.

Can you make it possible for a user to view/filter Source References, and upload a Report/pdf only.

Happy to discuss.

**Comment by dimasciput** [comment]
this is deployed in testing, non staff user should be able to upload a Report/pdf only.

**Comment by helendallas** [comment]
I logged in as an ordinary user and could add a report successfully, BUT I also had the option to add a peer-reviewed scientific article.


<img width="935" alt="Screenshot 2024-04-08 at 10 33 03" src="https://github.com/kartoza/django-bims/assets/45286876/84e9fca0-c765-4a1d-9dfc-7e06e2189840">

For now let's restrict to report. 

Thanks

**Comment by helendallas** [comment]
@dimasciput I am getting an error message now. Please action to restrict upload to Repor or thesis only. Then deploy to production and I can close ticket.

**Comment by helendallas** [comment]
@dimasciput This is fixed on Multi-tenant staging, but not FBIS staging. Happy to leave for now as we will be migrating FBIS over to multi-tenant soon, I hope.

Please deploy to multi-staging production.
