### ISSUE TITLE
Change "Site" to "Location"

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3794]
Change the word Site to Location throughout the site. 

![image](https://github.com/kartoza/django-bims/assets/77841514/6d72e19c-2595-430b-bf07-5dbde35ea029)

**Comment by dimasciput** [comment]
@helendallas I have removed the site visit

**Comment by helendallas** [comment]
@dimasciput Correct on staging, please deploy to production

**Comment by helendallas** [comment]
After explaining issue of site versus locality, SANParks are happy to continue with Site. Closing ticket
