### ISSUE TITLE
Add the marine protected areas

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3796]
Add the marine protected areas the sanparks ones _check in the boundaries from the GIS person.

**Comment by helendallas** [comment]
@amyburness These have been added as layers, 

<img width="1138" alt="Screenshot 2024-05-07 at 12 17 11" src="https://github.com/kartoza/django-bims/assets/45286876/8910a974-f395-4561-950a-336c34147098">

@dimasciput - have they been included in the harvester?

**Comment by helendallas** [comment]
@dimasciput Please confirm that these MPAs ar included in the harvester.

**Comment by dimasciput** [comment]
<img width="767" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/5d0d3ef6-7054-4788-975c-11d106351fff">

@helendallas yep

**Comment by helendallas** [comment]
Great thanks @dimasciput . Closing ticket.
