### ISSUE TITLE
the legend and layer selector overlap each other

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#380]
element ordering needs to be cleaned up. If you are busy with the layer selector it's OK if it draws over the legend (though they should ideally be completely out of the way of each other). atm the legend draws over the layer selector

**Comment by NyakudyaA** [comment]
One can't escape or close the legend easily as it covers the context layer panel. Please ensure this is possible. Alternatively, reposition where the legend opens so that it doesn't restrict the user from unticking the layer. Maybe there could be a hover option for the legend?
