### ISSUE TITLE
When I edit a SASS record from the validation form, submit, and close I am kicked out FBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3810]
During validation, the Source Reference is sometimes omitted. I then need to go in and add it and submit the data

<img width="1084" alt="Screenshot 2024-04-09 at 09 43 40" src="https://github.com/kartoza/django-bims/assets/45286876/57ed7fd4-de9a-47ea-8274-ae333f763f44">

Then when I click X, I get this

<img width="1156" alt="Screenshot 2024-04-09 at 09 43 53" src="https://github.com/kartoza/django-bims/assets/45286876/50593497-75cc-4119-b406-e7fcdd2ec6f9">

**Comment by helendallas** [comment]
I tested this and it seems to be working now, so closing ticket

**Comment by helendallas** [comment]
@dimasciput Which staging? I am getting a bit confused where changes are being made.

Is it

https://fbis.sta.do.kartoza.com

or https://testing.healthyrivers.kartoza.com

**Comment by helendallas** [comment]
I testing on new FBIS staging. When I click the last Submit button (After adding the source reference) I get taken back to the "Update SASS record" page. If I click the X then I go back to the View Record, and no matter what cant get back to Validate Records.

<img width="1221" alt="Screenshot 2024-06-12 at 11 34 41" src="https://github.com/kartoza/django-bims/assets/45286876/9d55bd39-ca37-4924-a79f-35e71d3438c8">


After Submitting, I should get a note saying SASS record updated, then get taken back to the validate Records, so that I can then validate record and proceed to review the next one.

**Comment by dimasciput** [comment]
I have updated this on fbis.sta.do.kartoza.com

**Comment by helendallas** [comment]
Thanks @dimasciput Working well now. Closing ticket.
