### ISSUE TITLE
Change 'add taxon' default settings 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3814]
@dimasciput can we change the default for **add taxon** from 'percentage' to 'number', unless @helendallas objects?
The reason being that most people entering a taxon record will be reporting a number, not a percentage as far as I know.

<img width="885" alt="Screenshot 2024-04-09 at 17 27 05" src="https://github.com/kartoza/django-bims/assets/44292029/e83fc1fb-9ec7-45a6-97f2-f590fdd121cb">

https://testing.healthyrivers.kartoza.com/fish-form/?siteId=122587

**Comment by helendallas** [comment]
@jeremyshelton I agree and am am happy with the suggestion

**Comment by helendallas** [comment]
It might be better to add functionality to allow the user to choose the default in the Abundance table.

<img width="787" alt="Screenshot 2024-05-07 at 10 49 36" src="https://github.com/kartoza/django-bims/assets/45286876/be110805-cdcb-487a-96ef-e956dbeb529e">


@dimasciput Can this be done? Thoughts?

**Comment by dimasciput** [comment]
Hi all, the current default is the top one. You can change the order of the abundance types by clicking the move icon in the admin : 

<img width="471" alt="Screenshot 2024-05-07 at 09 53 57" src="https://github.com/kartoza/django-bims/assets/1979569/cb833718-c9c5-4ad0-b342-f8cbe4f09b6b">

**Comment by helendallas** [comment]
I noticed that by changing the display order, I can move number to the top, which is then the default.

**Comment by helendallas** [comment]
I have done this by changing the sort order. Closing ticket

**Comment by jeremyshelton** [comment]
@helendallas OK great!
