### ISSUE TITLE
Remove Legacy sites with no occurrence, wt or wq data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3816]
Please create a script to check how many sites exist without any associated occurrence, water temperature, or chemical records data. 

Then,  delete them, if it's safe.

**Comment by dimasciput** [comment]
@helendallas I have deleted the legacy sites in testing site, will delete them on production

**Comment by dimasciput** [comment]
I have deleted them on production

**Comment by helendallas** [comment]
Thanks @dimasciput It is hard for me to check this, so I am trusting it is all fine and closing ticket
