### ISSUE TITLE
We need to make sure that data are added to the same Site Type (river, wetland, open waterbody)

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3826]
When a user adds a new Site, they Select Add Site, and have to choose whether to add a River Site, a Wetland Site or an Open Waterbody site.  If there is an existing site within 500 metres, they are given the option to add their data to this site, or create a new site.

We need to make sure that only sites that are the same Type are given as options, and then we need to be able to see these sites on the map to make the choice (see ticket #3803 )

SO if A user adds a River Site, only other River sites should pop up for them to add their data.

Similarly with Wetland sites, and Open waterbody sites.

If we don't do this we may get data collected in a river added to a wetland if the co-ordinates are a bit out.

**Comment by dimasciput** [comment]
@helendallas this has been added to staging site

**Comment by helendallas** [comment]
@dimasciput This looks great, thanks.

PLease deploy to production
