### ISSUE TITLE
chage the background on the sign up and login pages to SANParks green

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3827]
#005E30

![sanpbg](https://github.com/kartoza/django-bims/assets/77841514/c545999f-7e48-4233-a920-2c7a299479ef)

**Comment by dimasciput** [comment]
@helendallas the background has been updated

**Comment by helendallas** [comment]
@dimasciput Correct on staging, deploy to production

**Comment by helendallas** [comment]
@amyburness Still not right on login / signup page. Please update soonest

<img width="457" alt="Screenshot 2024-05-07 at 11 17 43" src="https://github.com/kartoza/django-bims/assets/45286876/c47c14a4-0bd9-4a25-92fc-ef14d3ecbe41">

**Comment by dimasciput** [comment]
![image](https://github.com/kartoza/django-bims/assets/1979569/7bb6226c-e06a-4ea6-9646-1116cd34a9fe)

Fixed on staging and production

**Comment by helendallas** [comment]
Thanks @dimasciput Looks fine, closing ticket
