### ISSUE TITLE
Remove FBIS specific information.

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3828]
resources let's remove /hide the fbis resources
![image](https://github.com/kartoza/django-bims/assets/77841514/4bad0d59-ccc8-4c0e-a310-f022e5be6db5)
remove FBIS site visits We don't need for SANParks
![image](https://github.com/kartoza/django-bims/assets/77841514/e1d43c77-5fa6-43da-8e12-ee399be624fc)

We can keep the functionality but just remove the fbis relevant data.

**Comment by helendallas** [comment]
@dimasciput Re above requests:

Agree Source references are from FBIS so should be removed. Not the functionality just the data. 


Going forward each tenant should only see their own source references. How will this be managed?  Can I go and delete these source references in Sanparks but they will still be in FBIS?

Re the Site Visits - this is SANParks not FBIS @amyburness Data pulled in from GBIF

**Comment by helendallas** [comment]
@dimasciput 

**First re Source References:**

I am only see SANparks source references now but when I added one of each category, they did not show in the Source Reference. Is there a delay?

<img width="1249" alt="Screenshot 2024-04-18 at 11 25 08" src="https://github.com/kartoza/django-bims/assets/45286876/bfcefd09-b696-4d6d-9bff-4a5970276276">

<img width="923" alt="Screenshot 2024-04-18 at 11 24 35" src="https://github.com/kartoza/django-bims/assets/45286876/0928dec3-3237-4f13-b0ed-278778f39577">

Second Re Site Visits:

These look ok.

**Comment by helendallas** [comment]
When I added a source reference from the Source Reference Manager, they are all now visible


SOme issues:

**FBIS Source references are still populated in the dropdowns**

- Unpublished data
- Published Reports
- Databases

These should all only include SANparks source references

<img width="1112" alt="Screenshot 2024-04-18 at 14 49 23" src="https://github.com/kartoza/django-bims/assets/45286876/e7d5b342-9e6d-48bb-ab2d-9a807715cf53">


Second:
When I add a source reference at the end of adding an occurrence record, then the source reference does not show in the Source Reference Manager.

For all categories as well

**Comment by dimasciput** [comment]
this has been done on staging and production

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, closing ticket
