### ISSUE TITLE
Data Source: All data added to SANParks BIMS must be labeled SANParks

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3838]
Data uploaded by SANparks to their platform must please be labelled 
SANParks in the Data Source drawer

SO 

**Data Source**

- SANParks
- GBIF

**Comment by dimasciput** [comment]
@helendallas The data source should automatically appear if there is data uploaded from SanPark; if not, it might be because of the cache.

**Comment by helendallas** [comment]
@dimasciput Please see #3876 as data added is not showing in the filter

**Comment by dimasciput** [comment]
Fixed on staging

**Comment by helendallas** [comment]
Thanks @dimasciput Closing this as comments made on #3876
