### ISSUE TITLE
We need to make Add the Source Reference Compulsory

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3846]
At the moment, users are able to add data that has no Source Reference.

This is problematic as the data is of less value if we don't know what the source reference is.

Please can you make it compulsory to select an existing source reference or add a new one on the thirds page when a user uploads data.

If the user tries to submit the data and they have not selected a source reference, then should be promoted to add it, before data can be submitted.

This should also apply to the Mobile app - although for now this can wait. The FBIS is NB to implement sooner please.

**Comment by dimasciput** [comment]
@helendallas I have moved the source reference selection to the main form for the occurrence form and SASS form. And make the source reference compulsory, so users can't submit if they haven't select a source reference. 

![image](https://github.com/kartoza/django-bims/assets/1979569/b07e0827-0aeb-4d0e-b4e8-73c469cfd848)

**Comment by dimasciput** [comment]
I have deployed it to http://fbis.sta.do.kartoza.com

**Comment by helendallas** [comment]
Thanks @dimasciput That is much better. I have checked, all working, so closing ticket.
