### ISSUE TITLE
Biotope colours incorrect again

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3854]
We need the biotope categories to be colour coded as follows:

SIC
SOOC
Bedrock

All different shades of blue

AQV
MVIC
MVOC

All different shades of green

G
S
M

All shades of browns and beiges

**Comment by dimasciput** [comment]
@helendallas I have updated the color here https://fbis.sta.do.kartoza.com/sass/dashboard/10369/?taxon=&search=&siteId=10369&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=%5B%2522sass%2520accredited%2522%5D&sourceCollection=%5B%2522fbis%2522,%2522gbif%2522,%2522virtual_museum%2522%5D&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=10369&orderBy=name&polygon=&dst=&ecosystemType=

**Comment by helendallas** [comment]
Thanks please deploy to production
