### ISSUE TITLE
12?. Handle synonym in taxa uploader

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3860]

**Comment by helendallas** [comment]
@dimasciput Please provide some guidance on how this works and how we can test it please. 

Does this cover task 12?

**Comment by dimasciput** [comment]
@helendallas I will copy my email to Astrid 

Hi Astrid, 

I've attached a sample of the updated template. There are now two new columns for synonyms : "Taxonomic status," and "Accepted Taxon."

![image](https://github.com/kartoza/django-bims/assets/1979569/58f7247b-0a30-45d5-a21a-763562511dbb)

To add a synonym, you first need to add an accepted taxon. In the example above, the accepted taxon is "Ecnomidae." 
You can then add the synonym as a normal record, but ensure you set its taxonomic status to "Synonym" and specify "Ecnomidae" as the accepted taxon. 
If there's no accepted taxo
n, the record won't be added, and you'll receive some error messages.

Regards,

[taxa_test.csv](https://github.com/user-attachments/files/15574528/taxa_test.csv)

**Comment by helendallas** [comment]
@schmikloi @dimasciput The template here for uploading excludes some columns currently in the BIMS, including:

- On GBIF
- GBIF URL

And then ones like below - should presumably not be included at a global scale? as these may vary depending on country/region. I had thought these would be additional tags.

- Origin
- Endemism
- Conservation status global
- Conservation status national

**Comment by helendallas** [comment]
Pleas see #3888 with details of input fields from @schmikloi

**Comment by helendallas** [comment]
Oka so @dimasciput has added ability to filter on synonyms
