### ISSUE TITLE
Site Code generation not working in SANParks

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3874]
The site naming indicates that the name is based on:

<img width="836" alt="Screenshot 2024-05-07 at 10 30 31" src="https://github.com/kartoza/django-bims/assets/45286876/16ce045d-59f1-46af-aa25-d442205115e5">

But it does not seem to be working.  There is no Site name???? field in Add Site form. 

<img width="581" alt="Screenshot 2024-05-07 at 10 29 02" src="https://github.com/kartoza/django-bims/assets/45286876/484b9ccd-3b83-418d-bfe2-31c0a365dae4">

Please investigate

**Comment by dimasciput** [comment]
This is fixed on staging.

**Comment by helendallas** [comment]
Sorry @dimasciput After discussion with Dian and Judith yesterday they now don't want Site Name or Site description. 

What should we use instead? Perhaps Park or MPA Name as this is a compulsory filed in their new upload form. Also all data will form in a Park or MPA.

1st four letter of Park or MPA Name + site count

Thoughts?

The we just change Site Name to **Park or MPA Name**

![Screenshot 2024-05-16 at 08 53 55](https://github.com/kartoza/django-bims/assets/45286876/cdc088ce-0171-435f-8771-4d33092fd3a8)

**Comment by helendallas** [comment]
@dimasciput Unless you have already done this, I suggest we just change Site Name to Park Name, 

and leave Site description in (it can be blank) in the form.

That way less  to change.

**Comment by dimasciput** [comment]
@helendallas ok will do

**Comment by dimasciput** [comment]
@helendallas this has been updated in the staging site

**Comment by helendallas** [comment]
Thanks @dimasciput . 

So for now the user needs to add the Park Name, and then the site code is generated from this?

Is it possible to add the Fetch option / or automatically fetch the Park Name if available.  How long will this take to implement?

If not, then the user needs to be prompted to add the Park Name or the site code is wrong.

Also the text needs to be updated - remove description

<img width="410" alt="Screenshot 2024-06-12 at 13 00 37" src="https://github.com/kartoza/django-bims/assets/45286876/3f9d84df-c895-4a0f-8f14-1b5ea271816f">

**Comment by dimasciput** [comment]
@helendallas 

> Is it possible to add the Fetch option / or automatically fetch the Park Name if available. How long will this take to implement?

It's possible, it will probably take 2-3 hours. And I need to know which layer I can use to get the park name.

**Comment by helendallas** [comment]
Thanks @dimasciput Since we are still waiting for an updated spatial layer, I suggest we hold off retrieving from the layer for now. I will create a separate for this and put on back burner pending receiving and publishing the new layer.

SO once you have updated the text re name, I can close the ticket.

**Comment by helendallas** [comment]
@dimasciput Please can you change this to the **first 3 letters** of the Parks so that they are unique. Two won't work as some parks are both MA etc.

Also then revise the text below. Then we can close ticket.

<img width="410" alt="338939672-3f9d84df-c895-4a0f-8f14-1b5ea271816f" src="https://github.com/kartoza/django-bims/assets/45286876/eb0a2f87-5f8f-453c-9c50-28107329bf02">

**Comment by helendallas** [comment]
@dimasciput Please can you finalise this one, thanx

**Comment by helendallas** [comment]
ok 3 letters working, just need to update text. and then when spatial layers have been updated, automate the retrieval of the park name.

1st three park name + site count

<img width="447" alt="Screenshot 2024-07-03 at 16 52 56" src="https://github.com/kartoza/django-bims/assets/45286876/5dd068d6-c68a-4c8f-a89f-fb5e109da560">

**Comment by helendallas** [comment]
This has been sorted, so going to close the ticket.

I will create a new one to remind us to link to new spatial layers for fetching Park/MPU Name.
