### ISSUE TITLE
A site and data I added on SANParks does not show in the Data source = SANPark filter

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3876]
I added data to -0TEST-00001

https://sanparks.sta.do.kartoza.com/map/#search/-0TEST-00001/taxon=&search=-0TEST-00001&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=221&ecosystemType=

However if I apply the Data source = SANParks filter, it disappears.

<img width="533" alt="Screenshot 2024-05-07 at 11 58 30" src="https://github.com/kartoza/django-bims/assets/45286876/c88a6a33-353c-40b5-86af-f2f662f30404">

**Comment by helendallas** [comment]
But they data are there in surveys

<img width="469" alt="Screenshot 2024-05-07 at 12 08 35" src="https://github.com/kartoza/django-bims/assets/45286876/4f18c13c-31c6-49e3-a8ac-f52141032900">

**Comment by dimasciput** [comment]
Fixed on staging sanparks

**Comment by helendallas** [comment]
Thanks @dimasciput . There is still a lag time, Is this the chance. I. site added does not show immediately. This may be a problem. Can you add in that the cache is refreshed after new sites or data are added?

**Comment by dimasciput** [comment]
@helendallas ok, now the caches are deleted when user added new record.

**Comment by helendallas** [comment]
Thanks @dimasciput This is great. See ing the site and data immediately is a big plus for users.  Please deploy to production then we can close ticket.
