### ISSUE TITLE
Check that Meerkat National Park is included in the GBIF harvester

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3877]
No occurrence data are in the Meerkat National Park.

Please check

<img width="409" alt="Screenshot 2024-05-07 at 12 47 35" src="https://github.com/kartoza/django-bims/assets/45286876/7dde7b7c-a767-4bfd-95e0-a1b456e58c7c">

**Comment by dimasciput** [comment]
@helendallas, I checked, and there is a boundary for Meerkat. However, let me create a new boundary that only includes Meerkat and check if it's running correctly.

**Comment by helendallas** [comment]
@dimasciput Data have been pulled down so I am closing this ticket as a YES>

![Screenshot 2024-05-15 at 08 18 32](https://github.com/kartoza/django-bims/assets/45286876/630bb802-8889-4f8d-baef-9c294f67ce64)

**Comment by helendallas** [comment]
Okay thanks @dimasciput
