### ISSUE TITLE
Add metadata for all spatial layers

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3881]
The new layers added for SANParks do not have any metadata.

Please add these.

![Screenshot 2024-05-08 at 09 14 33](https://github.com/kartoza/django-bims/assets/45286876/40656407-266f-4e4a-b932-170100b0ffe5)

![Screenshot 2024-05-08 at 09 14 44](https://github.com/kartoza/django-bims/assets/45286876/fda6945b-82eb-4b1f-a221-9ae089ccd90d)

**Comment by helendallas** [comment]
Waiting for text from Di and Judith

**Comment by Jeremy-Prior** [comment]
hi @helendallas, 

> Waiting for text from Di and Judith

Have you received the necessary metadata text (abstracts)?

**Comment by helendallas** [comment]
@Jeremy-Prior No I am still waiting on this

**Comment by helendallas** [comment]
@Jeremy-Prior 

Here is the metadata for the two layers:

SANParks Boundaries metadata
The SANParks boundaries spatial layer represents the SANParks terrestrial conservation estate and designated marine protected areas managed by SANParks in 2024. The layer does not necessarily represent the fence lines or proclaimed extents of national parks and is based on the boundaries of land parcels that are managed by SANParks. The layer was created by Scientific Services of SANParks with input from SANParks Park Planning. The boundaries of marine protected areas are based on the South African Protected Areas Database layer from the Department of Forestry, Fisheries and the Environment. This dataset is intended for visualisation and planning purposes.
 
SANParks Sections metadata
The SANParks sections spatial layer represents section boundaries used for operational and planning purposes by SANParks in 2024. The layer was created by Scientific Services of SANParks. The marine sections are based on the national Marine Protected Area Zonations spatial layer from the Department of Forestry, Fisheries and the Environment. The terrestrial sections include ranger sections and planning units for different national parks. This dataset is intended for visualisation and planning purposes. There are no designated sections currently included for some of the parks where ranger sections are not used.

**Comment by helendallas** [comment]
Thanks @Jeremy-Prior 

Just missing SANParks Buffer Zones - I have emailed the client and will revert as soon as received.

**Comment by Jeremy-Prior** [comment]
Okay, perfect, thank you @helendallas

**Comment by helendallas** [comment]
The SANParks team can add metadata now using Visualisation layers form, so closing this ticket
