### ISSUE TITLE
Simplify the homepage

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3886]
Taxonomic experts are mostly not so experienced in complex interface systems; therefore I would suggest that we have a very simple "homepage" with just a login and the logo; this page should then direct the expert

![image](https://github.com/kartoza/django-bims/assets/1979569/83b6aafd-f251-4102-85c6-63461f3e1281)

**Comment by dimasciput** [comment]
@schmikloi 

After logging in, what page should we show the user?

**Comment by schmikloi** [comment]
we have to talk about the homepage again once we have the other functionality in place;
can I see the feature above anywhere?

**Comment by helendallas** [comment]
It would be good for @schmikloi to provide a graphic backdrop for the FADA Landing Page, with branding.
Then after logging in or signing in one goes to Taxon Management

**Comment by schmikloi** [comment]
> [@schmikloi](https://github.com/schmikloi) Do you envisage a homepage that only comprises the Taxon Management sections of BIMS? With the other functionality (maps, layers, filters etc) hidden.
> 
> So the FADAtims become s a subset of the BIMS, with key functionality on the Taxon Management.
> 
> This was what I envisaged but want to check we are on the same page.

Hello both :) 
yes this is what I had in mind.

**Comment by schmikloi** [comment]
> [@dimasciput](https://github.com/dimasciput) Astrid and I have spoken and we agree it needs to be simplified.
> 
> **From Astrid via email** Generally, I think we are not there yet in terms of something that a non-technical expert can easily use. My vision would be that the expert clicks on a species, and then a form opens where they can edit all entries, add synonyms etc.
> 
> Both general users (read only) and experts go to simplified landing page and Taxon Management only.
> 
> [@schmikloi](https://github.com/schmikloi) to provide text for landing page.

I have now compiled a document on how I think the website should basically look like; it should consist of four pages (see attached document):
•	Home
•	FADA Database
•	FADA Experts & Groups
•	FADA History

To my mind we have two options now:
- you build only the Database page and I build the rest; on the Experts & Groups page however, we would need an automated link to the pdfs of the released checklists
- all four pages are implemented at your end

everything can still be discussed!

[FADA_website.docx](https://github.com/user-attachments/files/16599851/FADA_website.docx)



[infraFADA_CI_Manual.pdf](https://github.com/user-attachments/files/16599857/infraFADA_CI_Manual.pdf)

**Comment by helendallas** [comment]
Thanks @schmikloi 

From my perspective I think it would be good if you built the website and Kartoza focused on the Database page with necessary links.
@dimasciput - your thoughts?

**Comment by helendallas** [comment]
@dimasciput to implement initial changes.
@schmikloi to add text etc.

**Comment by helendallas** [comment]
Closing ticket by way of #3633
