### ISSUE TITLE
Implement Taxa Group Specific Views for Experts

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3887]
@schmikloi 
> I would then suggest to have all the taxagroups on the left (like I have added now the Trichoptera); each expert will be allocated to a specific taxa group and when they login, they should only see their taxagroup.

So, experts can only see their taxon group, but what about non-experts? 
There is a ticket suggesting that public users should be able to see all taxon groups : 
https://github.com/kartoza/django-bims/issues/3635

@helendallas

**Comment by schmikloi** [comment]
See my comment at #3635

**Comment by dimasciput** [comment]
> Ok, I agree with Helen, but maybe they could then see their taxagroup (which they can edit) on the top of the list (or marked in a color)

**Comment by dimasciput** [comment]
The color of the taxon group appears blue if you are an expert in that taxon group.

**Comment by helendallas** [comment]
Mine is orange but it does allow me to see my group. Reckon this is fine.

**Comment by schmikloi** [comment]
> Mine is orange but it does allow me to see my group. Reckon this is fine.

I also do not see the taxon groups I added in blue any more... one is grey, the other one orange...

**Comment by dimasciput** [comment]
@helendallas @schmikloi sorry it's not blue, but orange and it has an icon

**Comment by dimasciput** [comment]
I can change the color if you want

**Comment by helendallas** [comment]
Happy with orange -  as long as it stands out :)

**Comment by schmikloi** [comment]
fine with me as well; and I think the icon is a good idea!
