### ISSUE TITLE
Update taxa management page to show more fields

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3888]
@schmikloi 

![image](https://github.com/kartoza/django-bims/assets/1979569/801ddd8e-ca1d-4fdc-8416-1b7fd6c7aa5b)

> The overview list of species on the right looks nice, but it should probably also contain families to filter etc.

Yes, we can add more fields, but it will result in horizontal scrolling. Could you let us know which fields you would like to display?
I will add the ticket size (time to implement), which depends on the number of fields added and their complexity.

**Comment by schmikloi** [comment]
it would be best if most of/all the fields that we have in the expert template would be available and then the user can choose which ones they might want to display (and the others are then hidden); not sure if this is feasible...?
if not I will provide you a list of "must have" columns

**Comment by dimasciput** [comment]
Hi @schmikloi,

It is possible, but most of those fields will not be filterable and sortable like the current ones because we store the data differently. Additionally, I think it will take a long time to implement, probably around three days. We can implement the must-have columns first, and then improve it in the future.

**Comment by schmikloi** [comment]
ok.., but I seem not to get it right:
we collect more/other info (columns) than what is visible currently; if we put them all in the table then we will have to scroll horizontally, correct; but if we do not put them into the table, how can they then be seen by users or edited by experts?

**Comment by helendallas** [comment]
@schmikloi To provide details of what needs to be visible in the taxon management overview table

![Screenshot 2024-06-05 at 09 45 55](https://github.com/kartoza/django-bims/assets/45286876/fb3d1d9a-794d-4997-ac42-a3011c2e77af)



And in the Edit detail table


![Screenshot 2024-06-05 at 09 46 55](https://github.com/kartoza/django-bims/assets/45286876/eb278bd5-3009-4ece-bdf2-9794d44253cd)

**Comment by dimasciput** [comment]
@schmikloi @helendallas 

Hi, I've updated the taxon management page to display more fields. The action button is now fixed on the right, so as we add more fields, the table will be scrollable while the button remains in place.

You can also click the arrow icon on the left to reveal additional data for each taxonomy:

<img width="1091" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/3408cfb4-d62a-4989-b4e4-7662dd3fb031">

Not all the data is there yet, but the base structure is set up, making it easy to add more. I had to rewrite the taxon management page since we were using a simple table view before, but now we can add more advanced features.

**Comment by schmikloi** [comment]
Hi @dimasciput,
This looks very nice already, thanks a lot!!
I suppose all the main fields will be in the filters-table and all fields will be editable in the end, correct?

**Comment by dimasciput** [comment]
![image](https://github.com/user-attachments/assets/ba220908-0635-4c9b-b69b-822630a3947b)

@helendallas @schmikloi 

I have also updated the filter.

**Comment by helendallas** [comment]
Thanks @dimasciput Closing ticket
