### ISSUE TITLE
Enable Addition of Higher Taxonomic Ranks via UI

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3890]
@schmikloi 

> I wanted to add a new species, but the family was missing (can’t believe that Polycentropodidae are missing in GBIF 🤔???); where can the expert add a family (or any other higher systematic units)?

Currently, we can only upload taxa of higher rank than species or genus. Would you like the ability to add these from the UI?

**Comment by schmikloi** [comment]
once all the data are uploaded, experts might want to edit everything in the system, so I think it might be necessary to add everything from family downwards

**Comment by dimasciput** [comment]
@helendallas Deployed to staging. Users can now add new taxa with a higher rank than species.

If additional attributes or fields are needed for this form, please add a new ticket for that.

**Comment by helendallas** [comment]
Thanks @dimasciput . This is working. Closing ticket. No budget remaining for extra fields in this phase
