### ISSUE TITLE
Add Author When Adding New Taxon

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3891]
@schmikloi 

> I added a new species that was not in GBIF; I could not enter the author before it was validated; in the process it would make sense that the expert who enters the species can also add the author, so that this author is already visible to the taxagroup expert admin (highest level) who finally approves the species

Yes, we can add this feature. I will size this ticket as a 5, meaning it will take between half a day to a full day to implement.

**Comment by schmikloi** [comment]
thanks, this works now

**Comment by schmikloi** [comment]
just noticed that the author was not saved... i.e. I could add it to the taxon, but back in the overview table it was not there any more...

**Comment by helendallas** [comment]
The author is saved after adding. Closing ticket
