### ISSUE TITLE
Spatial filter error

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3905]
When using spatial filters like Water Source Areas (and others), Searches are returning data from outside the filter boundary.

![Screenshot 2024-05-17 at 06 39 18](https://github.com/kartoza/django-bims/assets/44292029/118fb988-7c6a-4729-a49c-ac3a71cfaef3)

**Comment by dimasciput** [comment]
@jeremyshelton I checked, and it seems that the site or the context data has been updated. We need to re-harvest the geocontext data. I suggest harvesting when we move to the new architecture. What do you think? 
cc @helendallas

**Comment by helendallas** [comment]
@dimasciput I agree. Let's leave for now as we are moving towards bringing FBIS onto the multi-tenant platform. Then we can re harvest.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas agreed, happy with that approach.

**Comment by helendallas** [comment]
Closing ticket - we will reharvesta nd check in multi-tenant environment
