### ISSUE TITLE
Consider removing redundant tabs on search bar?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3906]
@helendallas @dimasciput based on my own use of the platform, I never use the lower three tabs on the search bar and have never seen anyone using them - so maybe we should remove those features - do you agree or disagree?

<img width="330" alt="Screenshot 2024-05-17 at 06 49 43" src="https://github.com/kartoza/django-bims/assets/44292029/d3823542-cc54-4acb-8a02-9bf60e32b729">

**Comment by helendallas** [comment]
@jeremyshelton Please don't make any more suggestions for changing on the tickets until we speak about this. Budget is up and we need to finish remaining tasks please, not add new ones.

I often change base map, and print map

**Comment by jeremyshelton** [comment]
Thanks @helendallas 
That answers the question.
Closing ticket.
