### ISSUE TITLE
Revise text in the 'About' tab?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3907]
The 'About' page feels redundant, since all of that info now appears on the home page? 
Should we update it to be more useful, or just remove it?
We could consider replacing that tab with citation guidelines, which feel a bit hidden but are quite important?

**Comment by helendallas** [comment]
@jeremyshelton Please let's not delete, rather add different content Such as:

The FBIS team
News etc

and agree citation.

Lets chat further at a later stage.

**Comment by jeremyshelton** [comment]
Thanks for the input @helendallas 
That seems sensible. 
I will re-assign the ticket to myself to action this.
