### ISSUE TITLE
Reduce size of upload and download icons

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3908]
- @dimasciput you please swop the top two sections on the landing page, so that Biodiversity records is at the top?
- Is it possible to give us access to edit this section?
- Can you also please Reduce size of upload and download icons a bit?

Thanks
<img width="395" alt="Screenshot 2024-05-17 at 06 56 42" src="https://github.com/kartoza/django-bims/assets/44292029/a032866b-74e1-46e6-a4b9-e6303b2475e5">

**Comment by helendallas** [comment]
Thanks @dimasciput 

@jeremyshelton Are you happy with new size. Assume its on production?

**Comment by jeremyshelton** [comment]
Yes looks good. 
Thanks @dimasciput 
Closing ticket.
