### ISSUE TITLE
Update Download data CSV file to only include columns in SANParks upload template

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3910]
At the moment when I download SANparks data, I get all the data from the FBIS csv.

This needs to be updated to include just the SANParks data as per the upload template. see #3909 

Additional columns of the layers included on the SANparks platform can also be included.

**Comment by helendallas** [comment]
Revision to above:

Can you remove the following from the csv download:
![Image](https://github.com/user-attachments/assets/b893a89e-ab40-4410-80c6-1f18373a87de)

And then Include all Master list attributes such as Conservation Status (global and national), Origin, Endemism, Cites listing, Sensitive, TOPS, and any others added to as an attribute in the Taxon Management

And then add in the extra columns and attributes that are included in the Upload Occurrence template for a Biodiversity Module.

**Comment by dimasciput** [comment]
@helendallas please test on staging

**Comment by helendallas** [comment]
Cant test as SANParks data not showing in side panel.

**Comment by helendallas** [comment]
@dimasciput There are some strange and unnecessary columns pulling down. Ecoregions and provinces are getting mixed up with monthly rainfall.

province and ecoregion and Nfepa fish. suggest we remove yellow for now

xls attached.



[New For demonstration Occurrence Data.xlsx](https://github.com/user-attachments/files/16608778/New.For.demonstration.Occurrence.Data.xlsx)




![Image](https://github.com/user-attachments/assets/c0d2b0e1-6a65-406c-a0ee-1f13b0acc524)

**Comment by helendallas** [comment]
Thanks @dimasciput **CITES listing** is still not coming down.

See here for xls



[Occurrence Data 8.xlsx](https://github.com/user-attachments/files/16844708/Occurrence.Data.8.xlsx)

**Comment by helendallas** [comment]
Soory I am blind CIets listig gis there. All goo then @dimasciput except for #4213 which is a separate ticket

**Comment by helendallas** [comment]
There may still be an issue with extra columns downloading, I need too still check this.

**Comment by helendallas** [comment]
completed by way of #4216
