### ISSUE TITLE
Rename Ranger sections layer in LAYER SELECTOR

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3911]
Please rename this layer as follows:

Ranger Sections. -should become **Management Units**

<img width="292" alt="Screenshot 2024-05-17 at 10 14 45" src="https://github.com/kartoza/django-bims/assets/45286876/3d1a9b74-2302-47f1-8a84-07e75c79fec5">

**Comment by helendallas** [comment]
@amyburness Please can you action this so we can close this ticket, thanks

**Comment by amyburness** [comment]
@helendallas done
![image](https://github.com/kartoza/django-bims/assets/77841514/e7ab0a74-1824-4784-9b29-7e6c55db6d12)

**Comment by helendallas** [comment]
Thanks @amyburness Closing ticket
