### ISSUE TITLE
Email not being received when I download a csv

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3912]
After I download a csv file of occurrence data, I receive the download request email but not the email with the data, even though it is completed.

**Comment by dimasciput** [comment]
@helendallas 
![image](https://github.com/kartoza/django-bims/assets/1979569/4478eb61-611a-465b-8de1-4b04f57b14d6)

I can see here that the email has been sent, could you check your spam folder please?

**Comment by helendallas** [comment]
shucks I realised I was logged in with my gmail not frc...So sorry !
