### ISSUE TITLE
Common names not being harvested from GBIF in Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3924]
In an earlier version the common names were being pulled into GBOF.

This is no longer happening.

Please can you check.

Will I need to reharvest all the group to bring down the common names?

**Comment by dimasciput** [comment]
@helendallas I have fixed this. Please test on the production. You should still see the common names now.

**Comment by helendallas** [comment]
Thanks @dimasciput Do I need to harvest taxa again?

**Comment by helendallas** [comment]
Not working correctly, many missing common names when I harvested Amphibians in Staging. e.g. they have a common name on gbif

Also please check paleo database records are not coming through, I noticed one

<img width="642" alt="Screenshot 2024-05-24 at 09 40 07" src="https://github.com/kartoza/django-bims/assets/45286876/76335a15-bc28-4861-a5d4-feeb782092f0">
<img width="859" alt="Screenshot 2024-05-24 at 09 40 30" src="https://github.com/kartoza/django-bims/assets/45286876/08539040-cf75-45c3-9f9d-bb7f1c731186">
<img width="571" alt="Screenshot 2024-05-24 at 09 41 30" src="https://github.com/kartoza/django-bims/assets/45286876/81ce1bcf-d8c5-44bb-a187-e615702fd372">

**Comment by dimasciput** [comment]
@helendallas it was data issue so I only fixed in production. Could you check in production later?

**Comment by helendallas** [comment]
Sure will do

**Comment by helendallas** [comment]
Checked and looking good, closing ticket
