### ISSUE TITLE
Plant data uploaded in March 2023 come up as no records even though Present = 1

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3927]
Not sure what the issue is.

In March I uploaded >9000 plant records. They uploaded successfully.

<img width="1011" alt="Screenshot 2024-05-23 at 12 09 52" src="https://github.com/kartoza/django-bims/assets/45286876/626afadf-2882-48b6-bdc3-875124a67183">

However on the Validate records form, all of these sites show Unvalidated (even though uploaded data should become validated automatically on upload), plus the occurrences are zero.

https://freshwaterbiodiversity.org/site-visit/list/?validated=[%22unvalidated%22]&o=date

<img width="1382" alt="Screenshot 2024-05-23 at 12 14 09" src="https://github.com/kartoza/django-bims/assets/45286876/4e61dc19-8d21-4226-ba6b-f47766ad3d52">

If I go to one of these sites via the search on Map, then the record is there and the data. see example here.  SO must be an issue with validation form?

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=G22B--00088&siteId=143847&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=37&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=143847&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by helendallas** [comment]
It's not only this dataset. there are others. that were uploaded and which are unvalidated, and have zero records. Is the zero records perhaps because there is no abundance, only Present = 1

**Comment by dimasciput** [comment]
Hi @helendallas,

I have checked this, and the data is not related to what you uploaded. It's an empty site visit, probably legacy data. I will remove it safely.

Here's some proof:

Data you uploaded in CSV, the first row:
![image](https://github.com/kartoza/django-bims/assets/1979569/002a00a7-c5f6-49e5-8079-832d99c5f1d3)

And this is the actual validated data:
https://freshwaterbiodiversity.org/site-visit/detail/454276/

**Comment by dimasciput** [comment]
@helendallas I cleaned up the site visits in the fbis staging.

**Comment by helendallas** [comment]
Thanks @dimasciput I assume this is on https://fbis.sta.do.kartoza.com

Please action on production: https://freshwaterbiodiversity.org
