### ISSUE TITLE
Make Water temperature data visible in Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3941]
At the moment only Records and Physio-chemcial data are visible in Source References.

We need to include Water Temperature data here as well if possible. Otherwise it looks like there are no data associated with this Source Reference.

Also Records need to be rename **Occurrence Records**

<img width="834" alt="Screenshot 2024-06-04 at 12 36 20" src="https://github.com/kartoza/django-bims/assets/45286876/a614e134-5f28-4c58-a069-f189c11584b4">

**Comment by dimasciput** [comment]
added in staging site

**Comment by helendallas** [comment]
Brilliant, thanks @dimasciput Please deploy to production
