### ISSUE TITLE
New Taxonomy email notification

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3944]
@dimasciput 
We need clarity on how the validation emails work - and need to test that they are working.

- A User adds a new taxon (in FBIS this can be any user) - @schmikloi Your may not want to allow general users to be able to do this in FADAtims. Please confirm.

- If above is allowed, then Level 3 (country) SA expert gets an email saying a new taxon has been created - just like it is in FBIS at the moment.  This expert then checks and accepts or rejects the new taxon.

- Level 1 Global expert - do they also get an email? Do they also need to validate the taxon or is it automatic as it was validated by Level 2.

@schmikloi Please check my logic here and correct if wrong.

**Comment by dimasciput** [comment]
@helendallas currently the level 1 still needs to validate the taxon. I think I forgot to add email notifications to the level 1.  Will add it on the next fada sprint.

**Comment by helendallas** [comment]
When I added a taxon to Level 3 (South Africa) Plecoptera - I received a notification email.

**Comment by dimasciput** [comment]
@helendallas, I mean the notification that level 3 has approved the taxonomy and level 1 needs to approve for the taxon to be validated.

**Comment by helendallas** [comment]
Ok thanks

**Comment by schmikloi** [comment]
@helendallas 
to clarify the points above:
a "normal user" (the one without login; level 0 I suppose) should NOT be able to add a species; but they should be able to send a notification to the regional and/or global expert that they have found a new species (this could be done through normal email as this will rarely happen).
region or sub-group experts (level 2) should be able to add a species and also to validate a species they get from level 3 (whoever this might be in our case) and this should always finally be validated/accepted by the global level 1 expert.
if level 3 adds a taxon, then level 2 and 1 should get an email
if level 2 adds a taxon, then level 1 should get an email

hope this makes sense 🥴...

**Comment by dimasciput** [comment]
Thanks for the explanation, @schmikloi.

So for a normal user, they can just use the "contact us" here: https://fada.do.kartoza.com/contact/ if they found a species.

> region or sub-group experts (level 2) should be able to add a species and also to validate a species they get from level 3 (whoever this might be in our case) and this should always finally be validated/accepted by the global level 1 expert.
if level 3 adds a taxon, then level 2 and 1 should get an email
if level 2 adds a taxon, then level 1 should get an email

I will review the current functionality again. It should have been doing this.

**Comment by helendallas** [comment]
I think this is working fine. Let' s deploy to production and start getting real data in for final checks.
