### ISSUE TITLE
10. Develop functionality to ensure all changes are time stamped and logged

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3948]
@dimasciput You note this as completed but we do not see where this is tracked and available for testing.

Please provide an explanation

**Comment by dimasciput** [comment]
@helendallas this has been added in the backend. Every time a new taxon is edited, it creates a clone of that taxon called a taxon proposal. If the taxon is rejected, the proposal's status is changed to rejected. If accepted, the taxon proposal will override the existing taxon.

In addition to this, we also have audit logs for most of the data.



![Image](https://github.com/user-attachments/assets/4d2412c7-11da-410c-baeb-053b122561a6)

**Comment by helendallas** [comment]
@schmikloi Please can you confirm this is ok for this round as budget is running out.

**Comment by schmikloi** [comment]
Basically this is fine, but I do not think that the taxonomic experts will ever be that experienced so that they will work their way through the BIMS administration pages.
I wonder if the "created at" timestamp could simply be shown somewhere here; so that the expert sees the timestamp of the last change, even though they cannot see what the last change actually was...

![Image](https://github.com/user-attachments/assets/8d0cb309-b27e-4e50-98f7-a0503bc8bbd4)

If the money runs out we have to schedule a call very soon as these are the base functionalities we need (and I thought we had agreed upon). I could try to allocate some of my money to you.

**Comment by helendallas** [comment]
Thanks @schmikloi Let's see what @dimasciput says. I agree navigating the BIMS backend is not ideal. It would be useful to have it on this form.

@dimasciput in relation. At the moment all BIMS platforms have the same taxonomic management based on the updates implemented through FADA. Obviously editing will be restricted to FADA experts but the normal user will be able to see the table, and at the moment administrators of for e.g FBIS, can also edit fields on the Edit table.

I think we perhaps need a clearer understanding of this @dimasciput . Thanks

**Comment by dimasciput** [comment]
@helendallas @schmikloi yes that's very easy to add

**Comment by dimasciput** [comment]
@helendallas added in staging

**Comment by helendallas** [comment]
Thank @dimasciput Looks good from my side:

Visible here: Created at - can be sorted

<img width="1216" alt="Screenshot 2024-08-26 at 11 05 44" src="https://github.com/user-attachments/assets/1157a0ca-ddd3-493f-9d7e-54f1547fcd98">

And here: Last modified

<img width="858" alt="Screenshot 2024-08-26 at 11 06 23" src="https://github.com/user-attachments/assets/ab45a805-3c72-44df-aea3-b7a130eaa52b">

@schmikloi Please cna you check and confirm this is adequate.

**Comment by dimasciput** [comment]
@schmikloi 

We can do that for the last edited entry, but when staff upload data through the uploader, it is currently logged only as 'Admin' who added the data. Is that okay with you?

**Comment by schmikloi** [comment]
@dimas that is perfectly fine! just want to make sure if more than one expert works on the group that the others can see who was the last to make a change; thanks!

**Comment by dimasciput** [comment]
@schmikloi added 'last_modified_by' to edit form on the staging.

**Comment by helendallas** [comment]
Looks okay to me. Now have when modified and by whom

![Image](https://github.com/user-attachments/assets/8d3d9c08-88a6-4604-af27-c30a1fb9288d)
