### ISSUE TITLE
12. Check and develop functionality to handle synonymns and link to accepted name

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3949]
A ticket for the uploading of synonyms has been created and work started. see #3860 

However we need functionality for an expert to add a synonym in Taxon Management. 

Does this follow the normal procedure that is currently in place, where you Add A Taxon, then select from GBIF (if it is on GBIF), or add a new genus or species.

However I don't see where one then connects this synonym to the accepted name.

@dimasciput Please explain and revert.

**Comment by helendallas** [comment]
Comment from Astrid via email:
I cannot see where I can do this once a species is in the system and I want to add a synonym or change anything

**Comment by schmikloi** [comment]
I added a comment on the synonyms also on the template of the fields:
I think we have to talk about the synonyms at some stage: if we keep them in one list together with the valid species, then we need an additonal column that tells as "valid" or "synonym"; or we have them in a speparate table and make link from the species to it;
in any case, they must be searchable for the users: i.e. user enters a species name and all the synonyms are displayed

**Comment by dimasciput** [comment]
@schmikloi thanks, yes I think we can add the column and update the search functionality.

**Comment by dimasciput** [comment]
@helendallas @schmikloi deployed in staging.

**Comment by helendallas** [comment]
SO now we can filter on Taxonomic Status

![Image](https://github.com/user-attachments/assets/5caef533-f369-40a6-86e7-c519a1519f17)

And sort

![Image](https://github.com/user-attachments/assets/2763f97f-a26f-4eaa-a6b1-388f67dbcddb)

@schmikloi Have you tested this? It would be good to add the accepted name and its synonym and see if both are returned when a user filters on one or the other.

**Comment by schmikloi** [comment]
that works pretty well (there are synonyms in the Ostracoda list), thanks for including this!

**Comment by helendallas** [comment]
Closing
