### ISSUE TITLE
Search is too slow

### ISSUE THREAD

**Issue by cchristelis** [kartoza/django-bims#396]
# Problem

With all the fish data loaded, the search takes way too long.

# Proposed solution

- Send information to page as soon as possible. If we already know the number of sites, before serializing all the data, then we need to give the user this number as soon as possible.
- Clear the map and add a throbber informing the user that the search is "busy happening".
- Evaluate alternative searching methods and propose a better solution.

**Comment by Vries14** [comment]
- [x] Information gets sent to page, we knows number of sites
- [x] user gets informed that search is busy happening
