### ISSUE TITLE
Only show Add Sass to river sites

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3969]

**Comment by helendallas** [comment]
@dimasciput I checked this on both.

I am still seeing Add SASS data when I add a wetland site

<img width="974" alt="Screenshot 2024-06-12 at 08 44 23" src="https://github.com/kartoza/django-bims/assets/45286876/4f401fc2-6748-4b75-b8d9-a94f8c98db06">

**Comment by helendallas** [comment]
Thanks @dimasciput This is sorted now. Please deploy to production
