### ISSUE TITLE
Add functionality to update Roles - in People/Users

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3972]
At the moment the Roles a person selects when they **Sign in**  are fixed.

Is it possible to add functionality to allow admin to manage these **Roles**, especially add new ones.

I suspect this is important for going forward for the mulit-tenant version as not all organisations/instances will want the same set of roles.

<img width="1021" alt="Screenshot 2024-06-12 at 10 15 05" src="https://github.com/kartoza/django-bims/assets/45286876/030f3b0a-2c0a-4ab9-88a5-7c85bdbc99ed">

<img width="463" alt="Screenshot 2024-06-12 at 10 16 47" src="https://github.com/kartoza/django-bims/assets/45286876/cdcfc287-59f3-42ed-b29e-733a1fc9f487">

**Comment by dimasciput** [comment]
@helendallas this has been added to staging

**Comment by helendallas** [comment]
Deployed and tested on production. Closing ticket
