### ISSUE TITLE
CSV file downloaded from Taxon Management needs to include tags and attributes

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3979]
I tested the csv download for FADAtims but it didn't include any tags. These need to be included in the download column as separate columns please.

@dimasciput Also please clarify what the difference is between a tag and an attribute.

**Comment by dimasciput** [comment]
@helendallas I have updated the download taxa list to include tags and attributes. Please test it on staging. Each tag will become a new column : 
![Screenshot 2024-07-25 at 16 53 19](https://github.com/user-attachments/assets/9eeac822-49d3-4140-8b17-973afef8872f)
