### ISSUE TITLE
Add new BIMS table - Invasions for Non-native species

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3984]
At the moment any changes to Origin categories need to be done by @dimasciput 

As we onboard new tenants in the Multi-tenant model, it has become evident that this is not longer working.
Administrators of each platform need to be able to manage there categories in Origin, in a similar way to endemism.

So @dimasciput please confirm if it is possible to pull out Origin as a BIMS table which can be managed by admin for each platform.

For e.g. SANParks have requested these categories:

- Native
- Non-native
- Unknown
- Non-native- Invasive
- Non-native - Category 1a invasive
- Non-native - Category 1b invasive
- Non-native - Category 2 invasive
- Non-native- Category 3 invasive.

### However, I believe the following is a better solution:

Rename Filter drawer:
**ORIGIN, ENDEMISM AND INVASION**

Then add, option under Non-Native to include (in the same way as Native has Endemism as sub-categories):

All invasives
- Non-native - Category 1a invasive
- Non-native - Category 1b invasive
- Non-native - Category 2 invasive
- Non-native- Category 3 invasive

This would mean adding a new BIMS table called **Invasions** which admin can manage in the same way as Endemism.

I am confirming with Dian if this is an acceptable solution. 

@dimasciput Please can you size this ticket so I can revert to them.

**Comment by dimasciput** [comment]
Hi @helendallas 

Currently, the origin values are hard-coded. Changing them to a table might take a day or more because many things need to be updated, such as the uploader, the download function, and migrating the existing taxonomy table to use the new origin table.

If we just add the categories in the code for now, it might take 2-3 hours.

**Comment by helendallas** [comment]
@dimasciput I don't want to change the Origin categories. I want to add a new BIMS table called Invasions. So Original will still just be:

Native
Non-native

But then there will be a new table
INVASIONS. - with the categories below.

SO changing to a table would be a day or two? If so, then leave for now until uploader and checklists are completed.

**Comment by dimasciput** [comment]
@helendallas Ah, if we just want to add a new table invasion, it will probably take less than a day. However, will this affect the filter and the upload? If yes, then it will probably take 5-6 hours.

**Comment by helendallas** [comment]
See details here as above

<img width="638" alt="Screenshot 2024-07-03 at 10 42 52" src="https://github.com/kartoza/django-bims/assets/45286876/8ef6db7f-8334-4810-a5df-6606418aed59">

**Comment by dimasciput** [comment]
@helendallas I have added this. You can manage the data here: https://sanparks.sta.do.kartoza.com/admin/bims/invasion/

I have also handled the uploader to accommodate this. If you upload taxa with 'Origin = Category 1a invasive,' it will automatically use the invasive data. If it does not exist, it will create one automatically.

**Comment by helendallas** [comment]
@dimasciput Not sure I understand your logic here. Please clarify.

Some uploaded data will just have Origin = Non-native, without an invasive category and we still need to accommodate these in FBIS, SANParks etc.

Some of the data.e e.g. plants will have an invasion category but not all. I think the uploader should have a column Origin - as it does already, and then a new column Invasion, with the categories below.  I think the default should be Unknown. I have added categories to invasions table.

<img width="165" alt="Screenshot 2024-08-08 at 09 42 21" src="https://github.com/user-attachments/assets/05295064-2fe8-4675-a707-95a804b1546d">

**Comment by helendallas** [comment]
This is something that can be deployed to all instances as it is useful for `fibs and other `bims platforms

**Comment by dimasciput** [comment]
@helendallas thanks that makes sense, yes I will add unknown to the logic.

**Comment by helendallas** [comment]
I uploaded a test reptile master list that had 5 species.

One did not upload

Success file


[success_Invasions_Test_BIMS_reptiles_test_upload_19Aug2024.csv](https://github.com/user-attachments/files/16659780/success_Invasions_Test_BIMS_reptiles_test_upload_19Aug2024.csv)



error file



[error_Invasions_Test_BIMS_reptiles_test_upload_19Aug2024.csv](https://github.com/user-attachments/files/16659776/error_Invasions_Test_BIMS_reptiles_test_upload_19Aug2024.csv)


All categories have been added

![Image](https://github.com/user-attachments/assets/c3e3e0fd-85fd-46e8-9c25-bd5b3f3b8ec1)

**Comment by helendallas** [comment]
Assuming fine as cant check - don't want to add dummy data
