### ISSUE TITLE
Add FBIS_SA boundary for harvesting GBIF species/taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3998]
Please can you add the functionality to bring down GBIF species using the harvester. Please add the existing FBIS boundary as per the map that includes related river catchments.

**Comment by helendallas** [comment]
Duplicate ticket #4021 

Going to close other ticket and add map here

![Image](https://github.com/user-attachments/assets/59f5cf9d-d26c-4ec3-aba8-87c617d38f90)

**Comment by dimasciput** [comment]
Hi @helendallas , Jeremy is going to process the layer and then I will upload it later.

**Comment by helendallas** [comment]
I tried to download for a new group I created to test it, but it didn't work. Here is part of the csv


![Image](https://github.com/user-attachments/assets/3bd1b098-e9f0-40f0-b5e2-9fae5f4f3494)



![Image](https://github.com/user-attachments/assets/90c86eaf-73c7-48a4-83ea-777fd549f6e1)

**Comment by dimasciput** [comment]
@helendallas you forgot to add this
![image](https://github.com/user-attachments/assets/7f4eb13c-9b19-4c35-aac1-1cf46e7f53a3)

I have added it, can you try it again?

**Comment by helendallas** [comment]
Ah of course sorry. still getting use to new workflows :)

**Comment by helendallas** [comment]
Thanks @dimasciput This seems to be working, please deploy to production

**Comment by dimasciput** [comment]
Uploaded to production

**Comment by helendallas** [comment]
Thanks
