### ISSUE TITLE
Add Taxon - dropdown not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4009]
I tried to test adding a new taxon but family dropdown not working

<img width="994" alt="Screenshot 2024-06-21 at 12 56 50" src="https://github.com/kartoza/django-bims/assets/45286876/90bbc40d-736a-4b26-a201-35cc21749c52">

Please can you check

**Comment by helendallas** [comment]
Still not working

**Comment by dimasciput** [comment]
@helendallas the taxon need to be added first to the taxon group.

**Comment by dimasciput** [comment]
![image](https://github.com/user-attachments/assets/7fc6cfea-1480-436d-9071-330ef4a00636)

**Comment by helendallas** [comment]
This is working as long as the Taxon exists in the Taxa file. Closing
