### ISSUE TITLE
Ecological Category (SASS) filter missing even though it is ticked ion the Site Settings

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4019]
This is an urgent one as without this we cannot move across to multi-tenant for FBIS

**Comment by dimasciput** [comment]
this is fixed

**Comment by helendallas** [comment]
Thanks @dimasciput filter is there but there is no SASS dashboard, when I apply the filter.

https://fbis.sta.do.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified



<img width="1452" alt="Screenshot 2024-07-03 at 12 29 55" src="https://github.com/kartoza/django-bims/assets/45286876/b79a1aab-d722-4303-8de6-e1d064124caa">

**Comment by helendallas** [comment]
Thanks @dimasciput This is working now. closing ticket
