### ISSUE TITLE
Map UI and site papercuts

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#402]
testing via VPN on http://bims.ledet.gov.za

- [x]  map controls need hover tip to say what they are
- [x] Change site html title from Django BIMS to Limpopo BIMS
- [ ] implement SSL
- [x] locate by farm id form is titled 'locate by coordinate'?? - fix
    - [x] confirm that it will work with any portion of the string
- [x] base map control is still not integrated with the main layer control
- [x] in 'locate options' change 'Locate by Farm Portion/Farm Portion Code Page' to  'Locate by Farm Portion Code'

**Comment by dimasciput** [comment]
@gubuntu I'm not sure how to install the ssl for private site, would it be possible for them to make it public?

**Comment by gubuntu** [comment]
I asked Errol on the WhatsApp group just before I added you - keep up the pressure there.

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
