### ISSUE TITLE
Placeholder ticket of remaining issues from #3940

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4020]
Validation status filter not working - this is also a problem of current production

SASS accreditation status - number on new staging differ from production

Third party layers - Inwards wq sites/data not working

Validate records - Many unvalidated taxa, See unvalidated data gives me the 404-error message, not working. Filter default should be FBIS, as this is the only data that can be validated

**Comment by dimasciput** [comment]
> Validation status filter not working - this is also a problem of current production

This should be fixed now

**Comment by helendallas** [comment]
Thanks @dimasciput 

Third party Inwards wq fixed.

Validation filter working now.

Re Validate records - I see you have removed Source Collection - I assume then that only FBIS data are shown ,  which is correct. thanks.

So as you mentioned cant check numbers, so I reckon these are all sorted on the new staging.
