### ISSUE TITLE
Harvest species - should have SA boundary first, not sure what the whole list is, but not needed, only existing spatial boundary we use for FBIS production.

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4021]
When FBIS is on multi-tenant, please add current FBIS SA boundary, so that we can harvest species for new modules from GBIF

**Comment by dimasciput** [comment]
@helendallas should we use this boundary?
![image](https://github.com/kartoza/django-bims/assets/1979569/8c7371e7-16ef-4d25-b241-38d2435c24ca)

**Comment by helendallas** [comment]
Yes, that includes transboundary river right

**Comment by helendallas** [comment]
Duplicate of #3998 Closing this ticket
