### ISSUE TITLE
Wheel chart of Biodiversity Records not working correctly

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4039]
You developed functionality to allow admin to select the type of wheel chart: Options include: Global Conservation Status, Origin, Endemism, Division (Algae only), SASS Ecological Category (Invertebrates only).

<img width="524" alt="image" src="https://github.com/kartoza/django-bims/assets/45286876/19493451-0758-406c-9bb0-4698b098dde1">

I cant get this to work on SANParks, and also if I change chart from conservation to origin, I cannot change it back again. 

Please check why it is not working.

**Comment by helendallas** [comment]
Please check colour coding all strange now on FBIS

**Comment by dimasciput** [comment]
@helendallas yes, you can set the colors from the admin page. Let me do that tomorrow. 
https://fbis.sta.do.kartoza.com/admin/bims/iucnstatus/

**Comment by helendallas** [comment]
Thanks @dimasciput Good to know. Do we have the number codes for FBIS, if so I can update. Or we cna leave until FBIS is moved to multi-tenant.

**Comment by dimasciput** [comment]
@helendallas 

Yes, here's the color codes : 

```
colors = [
            '#D7CD47',
            '#39B2A3',
            '#17766B',
            '#2C495A',
            '#525351',
            '#8D2641',
            '#641f30',
        ];
```

But you were right. Let's do this on the production multi-tenant environment, because staging will be overwritten anyway.

**Comment by helendallas** [comment]
Thanks @dimasciput Agreed. I will action on production when implemented

**Comment by helendallas** [comment]
<img width="834" alt="Screenshot 2024-07-09 at 13 36 44" src="https://github.com/kartoza/django-bims/assets/45286876/9575febc-7eba-46a4-b3a2-be258070262e">

**Comment by helendallas** [comment]
Thanks @dimasciput This is working and I have updated on SANParks. I will do on FBSI production when on multi-tenant. I assume I need to do for each tenant, or can it be universal?

**Comment by helendallas** [comment]
Reallocating ticket to @helendallas The IUCN colour coding needs to be added to FBIS when deployed on multi-tenant

**Comment by helendallas** [comment]
I have updated this on the new multi-tenant production. Closing ticket
