### ISSUE TITLE
Fix remove module functionality in taxa management

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4040]
The remove module should remove the module group and all occurrences that are recorded in this group.

**Comment by dimasciput** [comment]
@helendallas I have deployed the fix and improvement to the staging site. Please test it. It might take a while to delete records if there is a lot of data, but you can close the page because the process will be done in the background.

**Comment by helendallas** [comment]
Thanks @dimasciput This is working great. Please deploy to  production

**Comment by dimasciput** [comment]
deployed
