### ISSUE TITLE
I need to merge a database with unpublished data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4053]
@dimasciput This has been discussed previously by email.

I need to merge these data sources - one is Unpublished data and one is Database.

![Screenshot 2024-07-10 at 13 06 51](https://github.com/kartoza/django-bims/assets/45286876/0e634bde-9a92-43a2-b920-4d8209fc841c)

**Comment by dimasciput** [comment]
@helendallas I have added this in staging and production

**Comment by helendallas** [comment]
Great thanks
