### ISSUE TITLE
'Find GBIF' button bug - taxon management

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#4061]
@dimasciput I get a server error when clicking add GBIF earn editing the fish taxon Gilchristella aestuaria in taxon management. 

<img width="970" alt="Screenshot 2024-07-12 at 06 06 04" src="https://github.com/user-attachments/assets/5e977fad-811d-447e-ab33-90e15de6963f">

**Comment by dimasciput** [comment]
@jeremyshelton This should be fixed in the new multi-tenant setup. I will update you again once I have deployed it to the new server. Or you can test on the staging site here fbis.sta.do.kartoza.com

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas this is fixed

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
I see in the new taxon management there is no find GBIF button?
Has this been moved elsewhere? How do I test this fix?

**Comment by helendallas** [comment]
@jeremyshelton You can still access it by Admin/Taxa

https://freshwaterbiodiversity.org/admin/bims/taxonomy/

Then search for the relevant taxon and find GBIF


![Image](https://github.com/user-attachments/assets/9b84cd31-7d85-498c-86fe-76942a678b7e)

https://freshwaterbiodiversity.org/admin/bims/taxonomy/7446/change/?_changelist_filters=q%3Dpseudobarbus

**Comment by jeremyshelton** [comment]
OK thanks @helendallas 
Looks good now - thanks @dimasciput 
Closing ticket.
