### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#4081]
@dimasciput when I go to freshwaterbiodiversity.org I see kartoza favicon, and then when I log in I see FBIS favicon - is this correct?
<img width="835" alt="Screenshot 2024-07-19 at 07 53 59" src="https://github.com/user-attachments/assets/0c3d4741-7b77-4c2d-af34-b57b747da32e">

**Comment by dimasciput** [comment]
@jeremyshelton probably because of cache, can you check it again now? Try hard refresh and then open new tab.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Sordet.
