### ISSUE TITLE
Add link to Taxa Admin in FBIS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4082]
The FBIS Admin team need to be able to edit certain fields that are not in the new Taxon Management System requested by FADA

Please can you add a link it the Taxon Management to allow FBIS admin to go to the Admin Table so that they cna continue to update the Origin, Endemism, National Conservation Status etc.

This should only be visible in the FBIS.
@jeremyshelton @KSnaddon Please note that Dimas is aware of this issue and has proposed a fix so that we see our previous table in the FBIS only.

**Comment by helendallas** [comment]
@dimasciput and @jeremyshelton Further to this ticket and linked to #4061 

For FBIS and SANParks, and in fact any tenant who needs to manage their own Origin, Endemism, Invasions, GBIF Link, Taxon photos etc - i.e. all the details that we could modify in the original Edit Taxon form, will be needed going forward.

With the revision to accommodate the FADA, these were no longer available unless one dived into Admin/Bims/Taxa

@dimasciput you mentioned adding a second link to allow us to edit/view the edit table attributes as before.  

Please give some thought as to how this should be, I reckon it should be a link on the Taxon Management only accessible to admin of a specific platform.
The alternative is to expand the new Edit front-end developed for FADA

**Comment by dimasciput** [comment]
@helendallas, I have added a link to edit the taxonomy on the admin page popup for now. It will only appear in the FBIS and if the user is a superuser. Please test it out.

**Comment by dimasciput** [comment]
Only deployed to staging

**Comment by helendallas** [comment]
Thanks @dimasciput That is useful. I suspect it may be needed for SANParks and Kafue as well at some stage as this is the only way for superusers to update origin, endemism, Invasion etc.

**Comment by helendallas** [comment]
In the version on staging there was a close button. Sometimes one wants to go to edit a taxon but then one doesn't actually do anything. One could just save but a close button included would be better if possible

**Comment by dimasciput** [comment]
![image](https://github.com/user-attachments/assets/5c348a18-a91b-41cf-8e52-6731cefc3808)

@helendallas close button added in staging

**Comment by helendallas** [comment]
Perfect thanks

**Comment by helendallas** [comment]
Please deploy this to SANParks as well. It should probably be standard for all superusers to be able to get into the Taxa table via this edit link.

**Comment by helendallas** [comment]
I don't think so, just FBIS, SANparks, Kafue, for now. thanks

FADA has most of what they need in the current edit

**Comment by dimasciput** [comment]
@helendallas 
![image](https://github.com/user-attachments/assets/57c6a9f7-e6b0-4af9-9906-86380d058207)

I have added setting here in the admin page : https://sanparks.sta.do.kartoza.com/admin/bims/sitesetting/37/change/
If you check this, it will show the edit button.

**Comment by helendallas** [comment]
Thanks @dimasciput That's awesome
