### ISSUE TITLE
GBIS Species Harvest should be the SA country border

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4086]
When we harvested species from GBIF we used the SA border .

But now when I tried to do a new group, it looks like it is the SANParks boundary.

The SANParks boundary is what is used for harvesting GBIF occurrence records.

see below -  please update GBIF Species to SA boundary as before and leave GBIF occurrence as SANPArks boundary

<img width="918" alt="Screenshot 2024-07-19 at 15 11 53" src="https://github.com/user-attachments/assets/78c1a4f4-a4f6-4f60-ba04-98380b0e45a7">

**Comment by dimasciput** [comment]
Hi @helendallas, I think we have SA border before but I removed it and changed to only sanpark boundary. I can reupload the SA border later.

**Comment by helendallas** [comment]
Ok thanks. Yes we need what we had before SA border for harvesting species, but SANParks border for harvesting occurrence records. Please let me know when the correct one is back. Thanks

**Comment by dimasciput** [comment]
![Screenshot 2024-07-29 at 10 16 10](https://github.com/user-attachments/assets/d7af67af-4dd6-430d-940a-d0d4b1f310da)

@helendallas can I use this boundary from FBIS?

**Comment by helendallas** [comment]
No Dimas -  we don't want the transboundary rivers. Tim or you created the sanparks boundary that we used initially. Do you still have it. Just use the SA country boundary, plus with the MPAs.

I will see if I cna find an email train of this or an old ticket.

**Comment by helendallas** [comment]
SA boundary with a small buffer along the cost so the marine protected areas are included please.

**Comment by dimasciput** [comment]
@helendallas got it, I will check first and also ask Tim. Thanks.

**Comment by helendallas** [comment]
Ok, please make sure you use the SA land boundary and then extend the layer area to include the Marine Protected areas. Not huge mid Atlantic areas in the southern ocean, as we don't want deep sea pelagic species included.  see here:

<img width="970" alt="Screenshot 2024-07-30 at 10 49 12" src="https://github.com/user-attachments/assets/3d2da7c6-e8ae-4c3f-a6a2-bee1abfc0c7c">

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good. Closing ticket
