### ISSUE TITLE
Change data confidence fields to char field

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4088]
> We were unable to test this because the tow fields were set as numerical instead of categorical. Field are :
> 
> Certainty of identification
> Accuracy of coordinates
> 
> Please update and then we can test again. 

 _Originally posted by @helendallas in [#3909](https://github.com/kartoza/django-bims/issues/3909#issuecomment-2238487134)_

**Comment by helendallas** [comment]
@dimasciput I noticed these have been added to Bims Taxa. Not sure they have been included in Taxa -  as they are linked to occurrence - like Record type in FBIS. And ultimately probably need to be a BIMS table that can be edited.

Perhaps there was some misunderstanding around this?



![Image](https://github.com/user-attachments/assets/155db6e7-3e8c-4b06-9f98-669819185454)


Also what is Reliability of Sources?

**Comment by dimasciput** [comment]
@helendallas these added to occurrence, location site, and also taxonomy. Just in case in the future if we want to do something similar to taxonomy, I can remove this on the taxonomy if you want. 

> Also what is Reliability of Sources?

I think this is added based on old requirements, I need to check the document again.

**Comment by helendallas** [comment]
ah okay thanks. Happy to leave in. May need in future?

**Comment by helendallas** [comment]
fixed, closing
