### ISSUE TITLE
Abiotic filters cause side panel to disappear when clicking on a site

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4098]
So there is a bug here.

I open up to see sites, and the side panel opens. but when I click on a site to see the temp data the side panel disappears.

Also an issue with physico-chem

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22,%22gbif%22,%22virtual_museum%22%5D&module=water_temperature&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by dimasciput** [comment]
@helendallas I have created the ticket here https://github.com/kartoza/django-bims/issues/4095. Can you test on staging?

**Comment by helendallas** [comment]
Thanks @dimasciput Working now on staging

**Comment by helendallas** [comment]
thanks fixed. closing ticket
