### ISSUE TITLE
User Upload stats

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4108]
Please confirm what is included in these upload stats.  i.e. where are the stats derived from.

60474 seems very high.

![Screenshot 2024-07-25 at 10 32 35](https://github.com/user-attachments/assets/4e3ef6a9-3771-4253-8ebb-08b181873687)

**Comment by dimasciput** [comment]
@helendallas, these are data added by users, excluding GBIF and the Virtual Museum. For example:

- Users add SASS records.
- Users add site visits using the form.
- Staff upload occurrences through the uploader, with every successful row counted as one.

**Comment by helendallas** [comment]
Ok that's why it's high, I didn't anticipate staff uploads being included. Happy to leave as is. thanks
