### ISSUE TITLE
Allow Admin to change Landing Page image and text

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4114]
At the moment all new tenant systems onboarded, have to have the landing page image and text created and edited by Dimas.

If we intend moving in the direction of a more independent deployment of BIMS, then it would be good to develop functionality to allow a new user to add the landing page image and associated text.

Example here for Kafue:

![Screenshot 2024-07-26 at 13 41 26](https://github.com/user-attachments/assets/5395a486-e810-4bcb-b1dd-f317859b9c7b)

@timlinux I am not sure how we can fund these general improvements to the BIMS as we attempt to are it more automonous. I cannot use existing project funds as they are all already stretched.

Perhaps you have an intern that would like to tackle this which Dimas then checks.

**Comment by helendallas** [comment]
Can this be done on Kafue project?

**Comment by helendallas** [comment]
For now, here are the images set by Kafue team. One for landing page, one for sign up.

Landing page

![Image](https://github.com/user-attachments/assets/84ee4770-fbae-40f7-a4a1-4dd7caea9efd)


Sign up page

![Image](https://github.com/user-attachments/assets/0d44041b-4d63-452d-8f9c-a4f7bde39ef3)


Alternative 

![Image](https://github.com/user-attachments/assets/27ea7f5c-3a2b-4575-9c07-336ae6cc4334)

**Comment by dimasciput** [comment]
Updated in staging and production

**Comment by helendallas** [comment]
Thanks fine for now
