### ISSUE TITLE
Occurrence records are not visible unless a biodiversity module is filtered

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4117]
When no filters re applied and one clicks the search arrow, all records should be shown. This should be the default.

On the Kafue Flats system, no records are shown in the search result, although they are visible on the map.  They are only shown if  a biodiversity module filter is selected.

https://kafue.do.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

![Screenshot 2024-07-29 at 09 52 39](https://github.com/user-attachments/assets/332283f2-6622-41bc-88cf-2c212d309528)

![Screenshot 2024-07-29 at 09 53 43](https://github.com/user-attachments/assets/e0997df0-3c49-46cf-930f-3047d83d4b03)

**Comment by dimasciput** [comment]
@helendallas this is fixed, try again from the map view

**Comment by helendallas** [comment]
Thanks @dimasciput Sorted. Closing ticket

**Comment by helendallas** [comment]
@dimasciput Please can you fix this on staging as well. I am training team at 10h00 and it's not working.

**Comment by dimasciput** [comment]
@helendallas fixed

**Comment by helendallas** [comment]
Thanks
