### ISSUE TITLE
Is Username needed for Sign In

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4118]
In BIMS at the moment, when you sign in the user is asked to add a Username.

However future login is based on email and password.

The username seems redundant.  I am not sure if it used anywhere in the backend?

![Screenshot 2024-07-29 at 09 58 46](https://github.com/user-attachments/assets/25c1f8d9-0dc8-4089-b11f-dcdee2236ee6)

**Comment by dimasciput** [comment]
I have fixed this @helendallas

**Comment by helendallas** [comment]
Great thanks
