### ISSUE TITLE
download requests not working again 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4119]
I tried to download on staging, never received email.

I tried to download on production - just spins.

**Comment by dimasciput** [comment]
@helendallas is this the download request?
![image](https://github.com/user-attachments/assets/d5837a18-dfaa-4cc5-b53d-cb4bfa2d7c71)

**Comment by helendallas** [comment]
This is the only one I received. checklist pdf from staging. Nothing for csv or xls on staging, and on production I cannot open dashboard...just spinning

**Comment by helendallas** [comment]
Closing ticket as these are working, thanks
