### ISSUE TITLE
Uploading occurrence data that does not have a latitude and longitude

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4123]
We discussed previously that SANParks needed to be able to upload data that does not have a geo reference.

Dian has subsequently generated centroid lat and longs for each National park and MPA.  She needed to do this as sometime the artificial lat/long fell outside the park.

For data with no geo reference but which have a park name, then these generated centroids should be used.

what is the best way to facilitate this?

Also can an occurrence data file have a mix of data that has a geo reference and data without a georeference?

For now the team are adding the centroid to their datasets before uploading as we are worried that the budget may run out.

**Comment by helendallas** [comment]
Here are the centroids for the SANparks.



[park centroids_July2024.xlsx](https://github.com/user-attachments/files/16444434/park.centroids_July2024.xlsx)

**Comment by dimasciput** [comment]
@helendallas 

Currently, the system uses the park name to get the centroid from the park layer. If they have an updated layer, I can upload it to our server and then use it to fetch the centroid. However, I can also update the uploader to check from the CSV you provided.

**Comment by helendallas** [comment]
So @dimasciput The issue is the centroid sometimes sits outside the park because of the shape of the Park. They do not yet have a new park and management unit layer, so I think it is best to use the centroid provided in the csv.

**Comment by dimasciput** [comment]
@helendallas I have added the csv to the staging, so now it will check the park name from the csv

**Comment by helendallas** [comment]
Sorry @dimasciput Please clarify workflow.

If the user has not added lat and long for an occurrence record, but has added a Park Name, then the lat/long included in the csv will be used to upload the occurrence record.

**Comment by dimasciput** [comment]
@helendallas that's correct

**Comment by helendallas** [comment]
@dimasciput This is not working. Only the longitude is uploading. Latitude is a repeat of Longitude.

Should be:


![Image](https://github.com/user-attachments/assets/4682cedb-4187-4354-8dd8-50d827c8b807)
![Image](https://github.com/user-attachments/assets/d9e886d0-c632-4311-b541-dac77cdeb4c5)

But here is the uploaded site and data
https://sanparks.sta.do.kartoza.com/location-site-form/update/?id=216549


![Image](https://github.com/user-attachments/assets/32b43fdf-132a-4bd7-8f18-d1680cac8a2f)


I see also SANParks mixed up x and Y (lat and long), so I corrected and made headers Latitude and Longitude and then uploaded new csv to Site Settings



![Image](https://github.com/user-attachments/assets/d8df8f3a-3d4e-4946-9b37-5c4836305183)

**Comment by dimasciput** [comment]
Hi @helendallas, please use lowercase "x" and "y" for now. If you change to "lat" and "lon," I will have to update the code. Also this is only applies to the uploader, not when creating a site from the form, as I thought the ticket was only for the uploader.

**Comment by dimasciput** [comment]
x = latitude
y = longitude

**Comment by dimasciput** [comment]
@helendallas The site will be automatically created in the background. For example, in this case:

- A user adds a new occurrence with the site "Park A."
- The system checks for an existing "Park A."
- If "Park A" does not exist, a new site will be created using the latitude and longitude provided in the CSV occurrences master.
- If latitude and longitude are not provided and the data refers to a park, the system will check with the park name in the CSV.
- If a match is found, a new site will be created using the latitude and longitude from the park CSV.
- If no match is found, an error message will be displayed.

**Comment by helendallas** [comment]
Thanks @dimasciput This sounds logical and good.

**Comment by helendallas** [comment]
Thanks working great

**Comment by helendallas** [comment]
Assuming fine as cant check - don't want to add dummy data
