### ISSUE TITLE
Rejected taxa get added to Taxon group

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4129]
I added a taxon and then rejected it.

I did not receive an email and then when I checked the taxon was added to the group.

Please check.

**Comment by dimasciput** [comment]
@helendallas can you tell the taxon name? And the taxon group?

**Comment by helendallas** [comment]
I deleted them, but will create a new one, then reject and share

**Comment by dimasciput** [comment]
@helendallas this is fixed on staging

**Comment by helendallas** [comment]
Thanks @dimasciput This is now working as the rejected taxon is not added to the taxon list. 
However, I did not receive an email saying that the taxon was rejected with a reason.

**Comment by dimasciput** [comment]
@helendallas thanks, I will check this

**Comment by dimasciput** [comment]
@helendallas I have fixed this.

**Comment by helendallas** [comment]
All working now thanks @dimasciput
