### ISSUE TITLE
There are some issues with the Sanpark boundary layer

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4134]
400 Client Error: Bad Request for url: http://api.gbif.org/v1/occurrence/search?taxonKey=5249287&offset=0&hasCoordinate=true&hasGeospatialIssue=false&basisOfRecord=HUMAN_OBSERVATION&limit=300&geometry=POLYGON%20((20.7573%20-25.8053,20.7519%20-25.8131,20.7543%20-25.807,20.7573%20-25.8053))

**Comment by helendallas** [comment]
@dimasciput I am not sure what these issues are?

But please can you check that the GBIF species boundary (SA +MPUS +coastal buffer) is working correctly.

SANParks have noted that only 6 birds taxa are present in the MPAs. It may well be that there are only 6 taxa with occurrences. I am re harvesting from GBIF now to check

**Comment by helendallas** [comment]
Not sure what was done here @dimasciput ?

**Comment by dimasciput** [comment]
@helendallas I have updated the boundary for staging, you won't see this error again.
