### ISSUE TITLE
FBIS errors-data dissapearring

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4146]
Please can you check this asap. A user is saying they added data, but the latest record is not showing. An example Site is

H7HUIS-BWINE

April 2024 data has been added, and I see it in the biological collection records table, but it is not pulling through to the graphs.

https://freshwaterbiodiversity.org/admin/bims/biologicalcollectionrecord/?q=H7HUIS-BWINE

In another example, SASS data were added to H7HUIS-COLER but no SASS data is shown in the side panel, although the data are there

https://freshwaterbiodiversity.org/admin/bims/biologicalcollectionrecord/?q=H7HUIS-COLER

**Comment by dimasciput** [comment]
@helendallas this is fixed on staging.

**Comment by helendallas** [comment]
Great thanks @dimasciput . Looks good. pLease cna you deploy soonest as the user is needing to use for reporting. She is an FBIS Hero So want to keep her onboard!
