### ISSUE TITLE
Citation page

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#4149]
@dimasciput the citation page is hidden away and difficult to find at the bottom of the landing page. 
Can we add this to the top menu bar?

**Comment by dimasciput** [comment]
@jeremyshelton sure I can add a new menu, where should I put it?

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 
Far right will be good.

**Comment by helendallas** [comment]
Thanks @dimasciput I am happy with it next to help.



![Image](https://github.com/user-attachments/assets/b8268eb6-08d6-4bf9-92fd-372ad7982d76)
