### ISSUE TITLE
Common names need to be provided in Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4153]
Common names are no longer provided in Taxon Management. This was useful.

Please can you reinstate for all tenants.

I think we agreed that the common name in the uploaded/edited master list would be used, but if there was no name uploaded then we would use the first GBIF English name as often shown on the species page on gbif.

At the moment in the Bims Taxa table multiple names have been pulled down from GBIF. e.g. 

![image](https://github.com/user-attachments/assets/26e352b4-9981-42c3-b6e9-8df082a219cb)

**Comment by dimasciput** [comment]
Common names have been added to taxon management, but currently, sorting by them is not possible due to its complexity. If this feature is needed, we can create a new ticket.
