### ISSUE TITLE
We need to improve the speed of data uploads

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4154]
At the moment, since moving to the multi-tenant, data uploads are very slow. 

For example I started to upload a dataset of 4195 records at 10h43 on 14 Aug, when I checked today at 11h00 only 1338 had been uploaded.

We need improved speed for uploading large datasets as this is critical for the success of all BIMS projects and future onboarding of tenants.

**Comment by dimasciput** [comment]
This has been fixed in the production

**Comment by helendallas** [comment]
Thanks Closing
