### ISSUE TITLE
Taxonomic upload error for Bird Module Master list

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4161]
We tried to upload edited Brod master list.

attached

[Birds_master upload_19August_HD.xlsx](https://github.com/user-attachments/files/16659272/Birds_master.upload_19August_HD.xlsx)

got this error

![image](https://github.com/user-attachments/assets/81a64719-75fa-4453-ba36-09131e94ed9d)

**Comment by helendallas** [comment]
Success file attached

[success_Birds_master_upload_19August_HD.csv](https://github.com/user-attachments/files/16659330/success_Birds_master_upload_19August_HD.csv)

Error file attached

[error_Birds_master_upload_19August_HD.csv](https://github.com/user-attachments/files/16659333/error_Birds_master_upload_19August_HD.csv)

**Comment by dimasciput** [comment]
@helendallas this is fixed on staging

**Comment by helendallas** [comment]
@dimasciput appears to be stuck...

<img width="904" alt="Screenshot 2024-08-20 at 13 06 53" src="https://github.com/user-attachments/assets/179f4000-a424-473f-9b24-d58903913db0">

**Comment by dimasciput** [comment]
@helendallas Sorry I think it was stuck because I have a deployment on the staging site. Will let you know when you can test it again.

**Comment by helendallas** [comment]
@dimasciput Can I go ahead and test this yet?

**Comment by dimasciput** [comment]
@helendallas yes you can try it now.

**Comment by helendallas** [comment]
Thanks @dimasciput It wis working. Please deploy to production
