### ISSUE TITLE
Dashboard - Private and Sensitive data are not visible on the dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4162]
I have permission to view public, private and sensitive data.

However when I open the dashboard with private or sensitive data, I don't see all the information. Download data is missing.

![Screenshot 2024-08-19 at 13 18 54](https://github.com/user-attachments/assets/3067b71a-0757-44ad-a075-4a99503e5eb2)

https://sanparks.sta.do.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%2213%22]&endemic=&invasions=&conservationStatus=[]&modules=42&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

Same issue with Sensitive data

https://sanparks.sta.do.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%2214%22]&endemic=&invasions=&conservationStatus=[]&modules=42&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

**Comment by dimasciput** [comment]
@helendallas fixed on staging

**Comment by helendallas** [comment]
Still an issue on dashboard - csv of private data not downloading and Site visits not accessible.

**Comment by helendallas** [comment]
All private and sensitive data now visible on dashboards, when permissions have been granted

**Comment by helendallas** [comment]
Cant test until private and sensitive data are uploaded. Assuming it is working
