### ISSUE TITLE
Option to change date format for uploading occurrence data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4167]
SANParks have all dates to DD/MM/YYYY instead of YYYY/MM/DD.

There systems automatically use DD/MM/YYYY and even if they set the date to YYYY/MM/DD it gets changed back to DD/MM/YYYY when we save the csv file.

Please can you size this and discuss other repercussion. I am not adverse to it changing for all BIMS. I would need to update documentation and upload templates.

**Comment by dimasciput** [comment]
@helendallas now you can use both in the staging

**Comment by helendallas** [comment]
I created a file with both date formats. It uploaded successfully, but I cant retrieve the data via aa csv download, it doesn't show processing on download requests, and the site visits doesn't work from the dashboard.

Not sure what the issue is

https://sanparks.sta.do.kartoza.com/admin/bims/downloadrequest/132/change/

https://sanparks.sta.do.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22563%22]&endemic=&invasions=&conservationStatus=[]&modules=47&validated=&sourceCollection=[%22SANPARKS%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

Here is the upload file.



[Test Primary WC SSC plants_HD.csv](https://github.com/user-attachments/files/16707208/Test.Primary.WC.SSC.plants_HD.csv)

**Comment by dimasciput** [comment]
Ah probably because of the private data type, let me check it again.

**Comment by dimasciput** [comment]
@helendallas I'm going to remove the download requests

**Comment by helendallas** [comment]
Thanks @dimasciput This is working,. I did another test with public data and it is uploading and downloading fine. Deploy to production.
