### ISSUE TITLE
add option to merge record type in BIMS Record type table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4168]
SANParks admin are adding data that creates supplicates when they should be the same.

Please add functionality to select and merge record types as you have with other bits tables.

<img width="416" alt="Screenshot 2024-08-20 at 09 13 28" src="https://github.com/user-attachments/assets/b48cf6f9-bd45-4238-bb36-7738d362c162">

https://sanparks.sta.do.kartoza.com/admin/bims/recordtype/

**Comment by dimasciput** [comment]
@helendallas added in the staging

**Comment by helendallas** [comment]
THANKS LOOK GOOD.
