### ISSUE TITLE
Source References - Private or Sensitive data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4192]
If admin upload private or sensitive data type, will the related source reference also then be private or public?

What happens if the dataset includes a mix of public and private data?

Do we need functionality to indicate if a data source is public, private or sensitive?

**Comment by dimasciput** [comment]
> If admin upload private or sensitive data type, will the related source reference also then be private or public?

No unfortunately, it will be public. 

> Do we need functionality to indicate if a data source is public, private or sensitive?

Yes, we can probably add this. Should I go ahead and do it? It will likely take about half a day.
Perhaps you can discuss with them first?

@helendallas

**Comment by helendallas** [comment]
Let me discuss it with them and once we see what budget is left.

Thye can also just choose to upload title only.

**Comment by helendallas** [comment]
SANParkas are happy with my suggestion:

Second issue is functionality to keep certain Source References private for private and sensitive data. This becomes complicated when the source dataset is a mix of public private and sensitive data.  The work around is you only upload the title page, and in that include an email the user can email to request the full document. Then it is at your discretion whether or not they are sent the full report.

Closing ticket
