### ISSUE TITLE
Checklist - more than one name for the same taxon

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4193]
An issue that SANParks have found in the past with creating species checklists is that different sources use different scientific names (species and subspecies) for the same taxon (same entity with same common name). 

This is not a problem when one is a synonym of the other as it will be sorted out through the process of using the Accepted name. It is a problem when both the subspecies and species names are accepted but they are being used for the same taxon (same common name).  See examples below:

![Screenshot 2024-08-28 at 11 29 52](https://github.com/user-attachments/assets/c19f2762-e386-4ff8-8e27-724d1d41e954)

For the xls/csv file:
To include both taxa as well as  a count of occurrence records for each in the xls/csv file.  The admin can select which is the correct one.

For the pdf: 
Suggestion is to include the name that has the most occurrence records.

Another **PREFERRED option for the PDF** is for SANParks to provide a xls file of First Taxon name, Second taxon name, Correct Taxon name, as below, and then only the correct taxon name gets included in the checklist.

![Screenshot 2024-08-28 at 11 39 32](https://github.com/user-attachments/assets/48e4e62e-a420-4994-bd3b-1b730d223e9b)

**Comment by dimasciput** [comment]
@helendallas 

I will add the count for now. The preferred method is difficult to implement because we need to ensure that they belong together.

Also, regarding the current data on staging, I couldn't replicate this issue. For example, Suricata suricatta—the subspecies and the species don't share the same common names from GBIF.

However, I will display the count instead.

**Comment by helendallas** [comment]
Please make sort order alphabetical in xls/csv using Accepted Scientific name and authority



![Image](https://github.com/user-attachments/assets/63179095-c23a-43b1-b6c9-73ff675002e5)

**Comment by helendallas** [comment]
Thanks looks good

**Comment by helendallas** [comment]
From Dian:

We will have to write some explanatory text on the website to explain the issue of the subspecies and species names coming through for the same taxa and how to interpret the information.

Could we add some text about this issue to the pdf download – i.e. a disclaimer?

I have asked Dian to provide text.

Perhaps it can be an extra sheet in xls, and at the bottom of the pdf.

**Comment by helendallas** [comment]
Di to provide wording for disclaimer

**Comment by helendallas** [comment]
After discussion SANParks will rather add disclaimer to the About page or in the new Help tab. Closing ticket
