### ISSUE TITLE
Xls and CSV not including extra customised columns for a taxon group

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4216]
As per See #3688 , SANParks needed to be able to upload custom files for certain taxon/biodiversity modules.

You added functionality for this by including option to upload occurrence template for a specific module.

However when I upload occurrence data, and then download the csv , these extra columns are no downloaded.  This was a very NB requirement from SANParks so please cna you try and make it happen this sprint. Essentially the upload template columns need to be included in the download, plus the normal extra columns as per a csv download. Thanks

For e.g.

Here is the Mammal upload template

[Mammals_upload_template_30Aug_KdNaPQt.csv](https://github.com/user-attachments/files/16847357/Mammals_upload_template_30Aug_KdNaPQt.csv)

Here is the data file I uploaded, with some of the filed filled in

[Helen Camdeboo test wildebeest hyena caracal.xlsx](https://github.com/user-attachments/files/16847370/Helen.Camdeboo.test.wildebeest.hyena.caracal.xlsx)

Here is the success file after the upload

[success_Helen_Camdeboo_test_wildebeest_hyena_caracal.csv](https://github.com/user-attachments/files/16847380/success_Helen_Camdeboo_test_wildebeest_hyena_caracal.csv)

BUT the downloaded XLS and CSV do not include these extra columns.

[Occurrence Data 2.xlsx](https://github.com/user-attachments/files/16847414/Occurrence.Data.2.xlsx)

**Comment by dimasciput** [comment]
@helendallas, could you test this first before I deploy it to production? If I deploy it to production, it will include this feature as well.

**Comment by helendallas** [comment]
Hi Dimas

Testing now

**Comment by helendallas** [comment]
Upload stuck. Testing with plants template. Lots of columns..... I am checking with SANParks if this is the final one

Here is template

[plant-template.xlsx](https://github.com/user-attachments/files/16885431/plant-template.xlsx)

Here is upload file

[WC SSC plants_HD.xlsx](https://github.com/user-attachments/files/16885432/WC.SSC.plants_HD.xlsx)

**Comment by dimasciput** [comment]
Hi Helen,

Could you try it again? The server is restarted this morning.

Regards,
Dimas Ciputra

**Comment by helendallas** [comment]
Ok @dimasciput I updated the plant template in the Plant module and added dummy data to a test data set. Attached here.

The plant upload file has a lot of columns and is quite complex



Template uploaded to Plant module:

[CSV BIMS_Plant occurrence data upload template_August 2024.xlsx](https://github.com/user-attachments/files/16886096/CSV.BIMS_Plant.occurrence.data.upload.template_August.2024.xlsx)

Test data:

[Test data upload BIMS_Plant occurrence data upload template_August 2024.xlsx](https://github.com/user-attachments/files/16886098/Test.data.upload.BIMS_Plant.occurrence.data.upload.template_August.2024.xlsx)

Tried again now....stuck on 1/10


<img width="882" alt="Screenshot 2024-09-05 at 10 13 40" src="https://github.com/user-attachments/assets/71001b00-627b-4b79-8da5-bdee2e8f68fe">

**Comment by dimasciput** [comment]
Let me test it later. Could you test the download?

**Comment by helendallas** [comment]
I dowloaded the csv and xls file from yesterdays dataset and it was fine, thanks

**Comment by dimasciput** [comment]
@helendallas I have fixed this, could you try it again?

**Comment by helendallas** [comment]
morning @dimasciput I just uploaded new plant data set and downloaded csv and xls and all looking good. thanks

**Comment by helendallas** [comment]
Assuming fine as cant check - don't want to add dummy data
