### ISSUE TITLE
SubSpecies should not be full taxon name in csv download

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4220]
@dimasciput I just noticed that the csv download SubSpecies has the full taxon name instead of just Subspecies

![Screenshot 2024-09-04 at 08 35 29](https://github.com/user-attachments/assets/19bf1298-979c-4763-8841-a8cc850deadf)

So here it should be **grimmia** only.

I am sure this is in agreement with FADA and should be universal across all BIMS.

**Comment by helendallas** [comment]
@dimasciput I cnat check this as csv download not working. Might be because of deployment.

**Comment by dimasciput** [comment]
@helendallas can you try it again now?

**Comment by helendallas** [comment]
Download keeps getting stuck at 400/668

**Comment by helendallas** [comment]
This is not working yet

https://sanparks.sta.do.kartoza.com/admin/bims/downloadrequest/227/change/

**Comment by helendallas** [comment]
Thanks @dimasciput This looks fine now.
