### ISSUE TITLE
GBIF Link

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4228]
It is important for FADAtims that the FADA taxonomy is used, not GBIF. In some cases this will match but not always.

@schmikloi asked if it is possible to include the GBIF link on the FADA Taxon Management only when:

Genus + species /subspecies + Author (Authority) are an exact match.

Then, when there is not an exact match include functionality for the Expert to be able to manually add the appropriate GBIF Key.  It is best if this is included in the Edit Page -  Perhaps After Author and Status

<img width="1135" alt="Screenshot 2024-09-06 at 11 32 06" src="https://github.com/user-attachments/assets/04a15c3f-250f-42fd-8f0a-30d752f40ef9">

<img width="465" alt="Screenshot 2024-09-06 at 11 31 14" src="https://github.com/user-attachments/assets/a4c1bbf4-0923-4bd6-9b47-5e581fb099da">

Importantly, for now, other BIMS e.g. FBIS and SANParks, need to retain the old system of GBIF as the taxonomic backbone.

Happy to chat further @dimasciput 
If this will take a lot of time to implement, then Astrid said Geraldine can do it manually.

**Comment by schmikloi** [comment]
Hi @dimasciput and @helendallas,
just tested the GBIF linking page and this works quite smoothly; so if the linking cannot happen on your side (or takes too much time for now), I will ask Géraldine to do it before we upload the species. We then would just need the GBIF key field to manually edit the keys.

**Comment by dimasciput** [comment]
Hi @helendallas, @schmikloi, I'll add the GBIF key field for now. Do you also want to add a GBIF link button like on the admin page, or is it just a field to enter the GBIF key?

**Comment by helendallas** [comment]
I think just a field to enter the GBIF key.

**Comment by dimasciput** [comment]
@helendallas @schmikloi the gbif key field has been added in the form.

**Comment by helendallas** [comment]
Thanks @dimasciput That looks good to me.

<img width="473" alt="Screenshot 2024-09-10 at 09 54 12" src="https://github.com/user-attachments/assets/f83c4c21-4741-45f6-958c-a84f8cee0874">

<img width="175" alt="Screenshot 2024-09-10 at 09 54 33" src="https://github.com/user-attachments/assets/e2b5b6ce-3840-435c-b078-9e8db11d60ec">

**Comment by schmikloi** [comment]
@dimasciput looks good to me too! I also appreciate the link to GBIF when you click on it.
The "Check in GBIF" link in the editing page should just link to the GBIF website, correct? (or should it already search for the elected species?)

**Comment by dimasciput** [comment]
@schmikloi, it will just redirect you to the GBIF site with the GBIF key you entered in the text box.

**Comment by schmikloi** [comment]
ok thanks!

**Comment by dimasciput** [comment]
@helendallas can we close this?

**Comment by helendallas** [comment]
Yes, Works great
