### ISSUE TITLE
Add GBIF Dataset Table for Manual Key and Name Input

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4229]
As GBIF sometimes returns only dataset keys without names, and validating keys through their service may not always provide results, we propose adding a GBIF dataset table. This table will allow users to manually input both the UUID (key) and the corresponding dataset name. The table will use the provided name when a dataset occurrence only has a key.

**Comment by dimasciput** [comment]
@helendallas, this is the admin page for the extracted dataset from GBIF occurrences that have been recorded in the system:

https://sanparks.sta.do.kartoza.com/admin/bims/dataset/

Currently, this is done manually using a script in the backend. Users can also add abbreviations for the dataset, and the checklist will use that abbreviation.

**Comment by helendallas** [comment]
I added an abbreviation to iNat RG

but got this error when I tried to save it

![Screenshot 2024-09-09 at 09 29 23](https://github.com/user-attachments/assets/e5a5936a-3c51-48c4-9215-6db93b3e9d44)

**Comment by dimasciput** [comment]
> Is the UUID in the table = datasetKey?

Yes

> but got this error when I tried to save it

Ah ok, there is a bug with the url field. Can you remove the url for now? Just make sure it's empty. 
I will add the fix later today.

**Comment by helendallas** [comment]
Ok thanks

**Comment by helendallas** [comment]
I added abbreviation but pdf checklist still bringing through full name.


![Image](https://github.com/user-attachments/assets/dad28d9d-9825-4e5b-8acc-25d5669c8212)



![Image](https://github.com/user-attachments/assets/1501d82a-163e-4f4a-a48a-72844453fa6b)


I am still waiting for xls checklist download

**Comment by dimasciput** [comment]
@helendallas is this on staging? Because I can't find your download request for the pdf.

> I am still waiting for xls checklist download

I just deployed the fix for the url, can you try download it again.

**Comment by helendallas** [comment]
Ok, abbreviation coming through now, I re did xls, 

Question - there is a new dataset that came down
Nature data from around the World

I added it to the table , but how do I get the other information?

**Comment by dimasciput** [comment]
@helendallas, for now, I have to run the script to check the dataset key in GBIF and fill in the other information. But the extra details aren't really needed right now, I just added them in case we need them in the future.

I can add a button on the admin page to update the dataset key and fetch all the missing information from GBIF. But do you think this is enough for now?

**Comment by helendallas** [comment]
Ok so If I add in a New Dataset Name, then I can click a key to update?

**Comment by helendallas** [comment]
When does the script run?

This dataset came down with the GBIf data but wasn't in the table.
I then added it. Not sure I am clear re above?

![Screenshot 2024-09-09 at 11 34 13](https://github.com/user-attachments/assets/d2d9d68c-d2ef-4ea3-9994-351bc1e4d498)

**Comment by dimasciput** [comment]
@helendallas 
You need to make sure to use the same dataset key from GBIF, as we're searching by the key instead of the name.

In the future, I’ll add a button to extract keys from existing occurrences and add them to the tables.

For now, if you download a checklist and there are keys the user hasn’t registered in the dataset table, the key will appear as-is in the checklist file. This way, the user can take that key, check it on GBIF, and add it themselves to the table.

For example, if there are occurrences with a dataset key like 1aaec653-c71c-4695-9b6e-0e26214dd817 and it’s not in the dataset table, when the user downloads a checklist that includes this dataset, it will show the key “1aaec653-c71c-4695-9b6e-0e26214dd817.”

Then, staff or a superuser can add it to the dataset table by checking it on GBIF with this URL: https://www.gbif.org/dataset/1aaec653-c71c-4695-9b6e-0e26214dd817. They just need to add the key and name. The next time the user downloads the checklist, it will display the updated name instead of the key.

**Comment by helendallas** [comment]
ok thanks

**Comment by helendallas** [comment]
For @dim to do when he comes back. 

In the future, I’ll add a button to extract keys from existing occurrences and add them to the tables.

**Comment by helendallas** [comment]
Closing . Lats action in #4237
