### ISSUE TITLE
Auto retrieve GBIF dataset when new occurrence records added

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4237]
From #4229 

@dimasciput to add a button to extract DatasetKeys from existing occurrences and add them to the tables.

Ideally when new GBIF occurrence records are harvested and there is a new dataset, can it be automated to be added to the dataset table.

**From previous ticket:**
For now, if you download a checklist and there are keys the user hasn’t registered in the dataset table, the key will appear as-is in the checklist file. This way, the user can take that key, check it on GBIF, and add it themselves to the table.

For example, if there are occurrences with a dataset key like 1aaec653-c71c-4695-9b6e-0e26214dd817 and it’s not in the dataset table, when the user downloads a checklist that includes this dataset, it will show the key “1aaec653-c71c-4695-9b6e-0e26214dd817.”

Then, staff or a superuser can add it to the dataset table by checking it on GBIF with this URL: https://www.gbif.org/dataset/1aaec653-c71c-4695-9b6e-0e26214dd817. They just need to add the key and name. The next time the user downloads the checklist, it will display the updated name instead of the key.

**Comment by helendallas** [comment]
@dimasciput Please can you also bring the GBIF dataset details into the datasets table for FBIS. Very useful.

**Comment by dimasciput** [comment]
@helendallas I have added a button to fetch datasets in the admin page : https://fbis.sta.do.kartoza.com/admin/bims/dataset/

Also now when the system harvesting occurrences data from gbif, it will automatically update the dataset.

**Comment by helendallas** [comment]
Very weird

It's correct when I follow link in email and download. But the email I am getting sent has the incorrect one and the name is different, just checklist.

![Image](https://github.com/user-attachments/assets/89814bf3-0fc7-4902-b2c0-03c37aa944ef)

I will foreward to you

**Comment by dimasciput** [comment]
@helendallas is this comment for different ticket?

**Comment by helendallas** [comment]
oops sorry yes. ignore its working
