### ISSUE TITLE
Clean up Flat Pages across tenants

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4239]
At the moment one can see flat pages for other tenants . Please can you clean this up or show me how to. I didn't want to just delete e.g. SANParks About on the FADA in case this had repercussions.

It would also be good to have the 

- About
- Help
- Citation

As standard with all BIMS tenants. And then how does one tick the Sow in NavBar option?

On SANparks Production
![Screenshot 2024-09-11 at 12 28 00](https://github.com/user-attachments/assets/83ea18ba-c308-482d-9b7e-b99b8052c14a)

On FADA Staging

![Screenshot 2024-09-11 at 12 29 18](https://github.com/user-attachments/assets/a3e248ee-ad07-4d45-a457-6a7ac473a167)

Also please confirm how this works. Not clear -  e.g. FADA history only works when sanparks.sta.do.kartoza.com is elected and not when fada.sta.do. kartoza.com

![Screenshot 2024-09-11 at 12 38 00](https://github.com/user-attachments/assets/35cf4721-f518-4e3a-b706-00112e6e6354)

**Comment by dimasciput** [comment]
@helendallas I have updated the flat page for sanparks production https://sanparks.do.kartoza.com/admin/flatpages/flatpage/

![image](https://github.com/user-attachments/assets/b7e6fa90-8fb3-4584-a52b-028c04253368)

The help and citation are now in navbar.

**Comment by helendallas** [comment]
@dimasciput Still incorrect on sanparks staging

<img width="488" alt="Screenshot 2024-11-11 at 10 00 33" src="https://github.com/user-attachments/assets/8a6ea8e5-b631-44ac-b594-094e3c203591">

**Comment by dimasciput** [comment]
@helendallas, this will be fixed when I mirror the data from production to staging again. I plan to do that next week.

**Comment by helendallas** [comment]
Great thanks @dimasciput

**Comment by helendallas** [comment]
I will close this ticket then
