### ISSUE TITLE
I get a 404 -Page not found message when opening site visit from SASS dashboard

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4243]
I cannot go to a site visit from this dashboard

![Screenshot 2024-09-16 at 12 22 47](https://github.com/user-attachments/assets/d1bdffcb-0298-4bd7-9137-cb9454be10fe)

https://freshwaterbiodiversity.org/sass/dashboard/115589/?taxon=&search=H9KORI-MIDDL&siteId=115589&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&invasions=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=115589&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by helendallas** [comment]
This was also picked up by a user. Please @dimasciput can you fix asap.

**Comment by dimasciput** [comment]
@helendallas fixed on production

**Comment by helendallas** [comment]
Great thanks @dimasciput
