### ISSUE TITLE
Checklist - Sources not being correctly populated -  Citation column in occurrence upload file

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4247]
In both the csv/xls and pdf, the column **Sources** needs to be populated from the **Citation** column in the Occurrence Upload template. 

Sanparks needed an abbreviation and the best way for them to manage this is to include a column **Citation** - which provides an abbreviation of a scientific article, data et, unpublished data or report.  

-	Upload files contained populated Citation field which should be used to pull through sources to checklist for uploaded SANParks occurrence data. 
- PDF checklist is bringing through the entire citation for uploaded occurrence data and no GBIF sources. For example, the “Masubelele M L, Foxcroft L C, and Milton SJ | 2009 | "Alien plant species list and distribution for Camdeboo National Park, Eastern Cape Province, South Africa" |Koedoe” should be Masubelele et al. 2009 as seen in under Citation in the upload. 
- 
![Screenshot 2024-09-18 at 09 37 26](https://github.com/user-attachments/assets/4ed7def4-cf72-4ca9-8bb4-458ef8524f4e)

For all data uploaded to SANParks, the checklist MUST use the text provided in this **CITATION** column in the checklist Source. Examples below.

![Screenshot 2024-09-18 at 09 00 00](https://github.com/user-attachments/assets/d02a1652-d6c4-4af7-99b8-fb4b63b75e56)

![Screenshot 2024-09-18 at 09 01 25](https://github.com/user-attachments/assets/e5ea44be-8564-43dc-bcc1-326bc3dc49eb)

**Comment by dimasciput** [comment]
@helendallas I have deployed this feature to the staging site

**Comment by helendallas** [comment]
@dimasciput This looks fine on staging. Has it been deployed to production?
