### ISSUE TITLE
Checklist - Sources not being correctly populated with abbreviations for GBIF datasets

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4248]
Where datesets are pulled down from GBIF, you added functionality for the SANParks team to add the abbreviation to be used in the Sources for checklist csv/xls and pdf.

The team have added the abbreviations in the Dataset table, but they are still not being pulled through to the checklist, for either the xls or pdf.

![Screenshot 2024-09-18 at 09 08 12](https://github.com/user-attachments/assets/9bc9b2ae-e559-4a82-8c48-625e9b1adc69)

BUT in the checklists

-	Relevant GBIF datasets had Abbreviations filled in, which should be the field that is used to pull sources into the checklist 
-

![Screenshot 2024-09-18 at 09 09 15](https://github.com/user-attachments/assets/621baf92-d978-4900-b1fc-5b4514ca3e58)

![Screenshot 2024-09-18 at 09 09 32](https://github.com/user-attachments/assets/e9e1650f-e495-450e-a9c4-b9d3cee4c576)

![Screenshot 2024-09-18 at 09 13 32](https://github.com/user-attachments/assets/00cd6bc1-9798-40d6-9633-3b6841c17b1f)

**Comment by dimasciput** [comment]
![image](https://github.com/user-attachments/assets/52e27d09-714b-40c3-a948-9b8fc01481ff)

Please test it again on staging.

**Comment by helendallas** [comment]
Thanks @dimasciput This seems to be pulling through now

**Comment by helendallas** [comment]
Seems to be fine now. has this been deployed to production?

**Comment by helendallas** [comment]
Checked. Good
