### ISSUE TITLE
Checklist - csv/xls and pdf not bringing down all taxa

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4249]
The checklist csv/xls or pdf are not bringing in all the taxa it should. For example Camdedoo Mammals

https://sanparks.sta.do.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value%2Csanparks%2CCamdeboo%20National%20Park%22]&reference=&endemic=&invasions=&conservationStatus=[]&modules=42&validated=&sourceCollection=[%22SANPARKS%22,%22gbif%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

There are 72 mammal taxa when the filter mammal and camdeboo are applied.

![Screenshot 2024-09-18 at 09 21 07](https://github.com/user-attachments/assets/ac8b7eec-256e-4a35-820b-c096e613c6e3)

But the checklist is only bringing down the following9 taxa and they are no longer sorted alphabetically as per earlier ticket.

![Screenshot 2024-09-18 at 09 32 01](https://github.com/user-attachments/assets/7ac5be7e-526f-4e1f-8b73-e41d895809e6)

**Comment by dimasciput** [comment]
@helendallas, that’s weird. I tested this and it shows 70 taxa. And when I download it, I get the correct data. Can you try again?

**Comment by helendallas** [comment]
@dimasciput pdf only bringing down this

<img width="1016" alt="Screenshot 2024-09-25 at 15 59 30" src="https://github.com/user-attachments/assets/be566a60-9dea-495b-af1e-eb5567dbb39b">

Here is pdf received and xls. More taxa in xls but something strange happening at top of file.

[Checklist.pdf](https://github.com/user-attachments/files/17132173/Checklist.pdf)

[Mammals Checklist.xlsx](https://github.com/user-attachments/files/17132174/Mammals.Checklist.xlsx)

**Comment by helendallas** [comment]
Pdf still not bringing down all taxa - still as above

**Comment by dimasciput** [comment]
@helendallas hmm I got this file,

[sanparks.sta.do.kartoza.com_checklist_Mammals_326.pdf](https://github.com/user-attachments/files/17275145/sanparks.sta.do.kartoza.com_checklist_Mammals_326.pdf)

**Comment by dimasciput** [comment]
@helendallas can you try it again? Try download the file from download request page

**Comment by helendallas** [comment]
Reckon this is fine now. Has it been deployed to production?

**Comment by helendallas** [comment]
FIne, closing
