### ISSUE TITLE
Add spatial layer and filter - Zam_Catchments

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4250]
Please add this spatial layer to KFWIS.

The **layer** should be renamed:
Catchments

The **filter** should be on River_Sub but renamed River subcatchments

[Zam_Catchments.zip](https://github.com/user-attachments/files/17043083/Zam_Catchments.zip)

Please also check other column headers and rename as necessary

**Comment by Jeremy-Prior** [comment]
The Catchments layer is up and initially styled on the site:

![image](https://github.com/user-attachments/assets/6ec22eba-1a1c-4b61-a4fe-9253e9a8ba7a)

The spatial filters will still be worked on.

**Comment by Jeremy-Prior** [comment]
Some of the Catchments polygons are layered on top of each other with the same RIVER_SUB. This means they were recorded with the same geometry but with varying information in the other columns and this will affect styling and may affect other functionalities.

Example of 3 geometries overlain on one another:
![image](https://github.com/user-attachments/assets/50a3335c-2122-48d4-bb5e-fc19dfa37dd3)

12 catchments have multiple geometries overlapping and this is from 28 features sharing RIVER_SUB features but having differing information in the other columns. 

@helendallas, is it possible to check with the Kafue team how they would like to proceed? Would they like the data cleaned or left as is?

**Comment by helendallas** [comment]
Layer fine for now, no filter yet. Hope to be able to train Kafue staff to do this.
