### ISSUE TITLE
Add spatial layer and filter - Zam_districts

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4251]
Please add this spatial layer to KFWIS.

The **layer** should be renamed:
Districts

The **filter** should be on Name1_ but renamed Name

[Zam_districts.zip](https://github.com/user-attachments/files/17043110/Zam_districts.zip)

**Comment by Jeremy-Prior** [comment]
The Catchments layer is up and initially styled on the site:

![image](https://github.com/user-attachments/assets/d5c69d08-a7b7-4d88-87ba-19af905ac4d5)

The spatial filters will still be worked on.

**Comment by helendallas** [comment]
Layer Fine, closing. No filter yet, Will hopefully be able to show Kafue team how to do this themselves
