### ISSUE TITLE
Add spatial layer and filter - Zam_freshwater

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4252]
Please add this spatial layer to KFWIS.

The **layer** should be renamed:
For now please call this layer River Catchments

The **filter** should be on Name

[zam_freshwater.zip](https://github.com/user-attachments/files/17043178/zam_freshwater.zip)

**Comment by Jeremy-Prior** [comment]
The Catchments layer is up and initially styled on the site:

![image](https://github.com/user-attachments/assets/5d05a9c3-5f50-46f0-b12d-3d5701244ba0)

The spatial filters will still be worked on.

**Comment by helendallas** [comment]
Layer fine for now, no filter yet. Hope to be able to train Kafue staff to do this.
