### ISSUE TITLE
Add spatial layer and filter - Zam_Wetlands

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4255]
Please add this spatial layer to KFWIS.

The **layer** should be renamed:
Wetlands

The **filter** should be on Name

[Zam_wetlands.zip](https://github.com/user-attachments/files/17043282/Zam_wetlands.zip)

**Comment by Jeremy-Prior** [comment]
The Catchments layer is up and initially styled on the site:

![image](https://github.com/user-attachments/assets/778f5a97-c45c-473a-90d8-824f149f0bf7)

The spatial filters will still be worked on.

**Comment by helendallas** [comment]
Layer fine for now, no filter yet. Hope to be able to train Kafue staff to do this. Issue with Kafue area, but need Kafue team to fix
