### ISSUE TITLE
Invasions missing from CSV download in Taxon Management

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4273]
Invasion categories were added to SANParks - see e.g. Birds success upload file.

But when we download the CSV from the Bird Module in Taxa Management, no Invasions column is downloaded.

<img width="1218" alt="Screenshot 2024-10-01 at 10 11 52" src="https://github.com/user-attachments/assets/25ad0082-28ab-49c7-9d6a-a2b8de0cdc67">

See example here with no Invasions column in the csv.

<img width="1422" alt="Screenshot 2024-10-01 at 10 13 53" src="https://github.com/user-attachments/assets/1708efed-d149-4164-b655-0d02a43b20ea">

**Comment by dimasciput** [comment]
Hi @helendallas 

The invasion value needs to be added to the origin column. So, it should be origin => Category 2a invasive, and it will automatically add the species as non-native.

So, this is not a bug, but I can add this feature. It will take 2-3 hours, but I'm not sure if this is part of the sanpark requirements.

**Comment by dimasciput** [comment]
@helendallas https://github.com/kartoza/django-bims/issues/3984#issuecomment-2296402785

**Comment by helendallas** [comment]
Ah okay. Let me discuss with SANParks. I also misunderstood. I will revert

**Comment by helendallas** [comment]
@dimasciput I did not understand the workflow here. Can we have it working the same way as endemism please.

Origin - native - then fill in endemism field for endemism category
 
Origin - non-native - then fill in invasion field for invasion category


 
The Origin field should only be used to indicate if the origin of the species is SA (native) or not SA (non-native), not endemism or invasion status

**Comment by dimasciput** [comment]
@helendallas I have added this functionality, so please try to upload it again.

**Comment by helendallas** [comment]
@dimasciput I don't think I get what you have done here.

The team uploaded the invasions as a separate column for reptiles, but it is still not coming down in csv.

[reptiles_invasion testing upload_04-10.csv](https://github.com/user-attachments/files/17256804/reptiles_invasion.testing.upload_04-10.csv)

[success_reptiles_invasion_testing_04-10.csv](https://github.com/user-attachments/files/17256806/success_reptiles_invasion_testing_04-10.csv)

[Reptiles-2024-10-4_master list download after testing.csv](https://github.com/user-attachments/files/17256807/Reptiles-2024-10-4_master.list.download.after.testing.csv)

**Comment by dimasciput** [comment]
@helendallas ah I haven't updated the master list download. Let me fix it quickly.

**Comment by helendallas** [comment]
@dimasciput Please confirm when this is done.

**Comment by dimasciput** [comment]
@helendallas this has been added to production and staging

**Comment by helendallas** [comment]
Not seeing it in download?

**Comment by helendallas** [comment]
<img width="1167" alt="Screenshot 2024-10-07 at 09 49 29" src="https://github.com/user-attachments/assets/6531dc87-0812-4d78-b5d2-e514b83b1b32">


Ok I am but please put it with the other attributes etc. not in taxonomy

**Comment by helendallas** [comment]
Checked and now in Production csv download, closing ticket
