### ISSUE TITLE
New South African National parks layer

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4280]
@dimasciput 

The SANParks team have updated the spatial layer as discussed. 

Please replace Park Boundaries with SANParks Boundaries. zip

<img width="232" alt="Screenshot 2024-10-03 at 13 29 30" src="https://github.com/user-attachments/assets/4c38d28f-213b-456a-ae74-772e3061492b">

And then use this to filter:

 
<img width="240" alt="Screenshot 2024-10-03 at 13 31 15" src="https://github.com/user-attachments/assets/28a529e1-1eef-4d1c-94ee-55d5fb2db609">

.Zip files to be sent via Wetransfer

**Comment by helendallas** [comment]
@dimasciput Update on this please

**Comment by dimasciput** [comment]
@helendallas, this has been updated in staging. The spatial filter will be run on production instead. Could you please test if the layer is correct?

**Comment by helendallas** [comment]
Not seeing Park boundaries layer, only Sections.

<img width="1174" alt="Screenshot 2024-10-21 at 12 02 30" src="https://github.com/user-attachments/assets/0b98d633-0dc9-4793-9177-dd443569f6d6">

**Comment by Jeremy-Prior** [comment]
Hi @helendallas please refresh the page, the layer order should have been adjusted on staging so that the Park Boundaries layer is just below the Sections layer and is not further down the list:
![image](https://github.com/user-attachments/assets/387c6acd-fb6c-41d5-96fa-223b2aed5bf3)

**Comment by helendallas** [comment]
Thanks @Jeremy-Prior Looks good and positive feedback from client.

Can you please make the default that Park Boundaries is above Section.

The deploy to production please.

**Comment by Jeremy-Prior** [comment]
Layer order done on staging:
![image](https://github.com/user-attachments/assets/07e4c0b5-a836-4f08-bb2d-230a0bcb783f)

**Comment by helendallas** [comment]
Great. Just need to update filter , see ticket #4241

**Comment by helendallas** [comment]
@Jeremy-Prior @dimasciput 

We picked up an issue with Golden Gate Highlands and Golden Gate Highlands National park - these should be the same.

Also can these be sorted alphabetically 
first MPAs (Blue ones) , then Park names (Green ones)

**Comment by Jeremy-Prior** [comment]
Adjusted on staging:

![image](https://github.com/user-attachments/assets/7146cf33-3222-4d40-b37b-4c11c5e535fd)

@helendallas please review.

**Comment by helendallas** [comment]
Great thanks
