### ISSUE TITLE
Layer SANParks Sections for replacing current Management Units

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4282]
@dimasciput

The SANParks team have updated the spatial layer as discussed.

Please replace Park Boundaries with SANParks Sections. zip

Note Management units =. Sections. As per ticket #4241 The correct name is Section

<img width="238" alt="Screenshot 2024-10-03 at 13 33 17" src="https://github.com/user-attachments/assets/be70d2fa-e64d-4f77-87fe-76202e04c3c3">

And then include this layer for the filter

<img width="243" alt="Screenshot 2024-10-03 at 13 37 24" src="https://github.com/user-attachments/assets/f9eec985-d320-4ecd-af7f-5c21f4071244">

.zip file to be sent via Wetransfer

**Comment by dimasciput** [comment]
The layer has been updated and name has been changed in the staging. 

Spatial filter will be done in production.

**Comment by helendallas** [comment]
Waiting on feedback from SANParks team.

**Comment by helendallas** [comment]
Thnumbs up from client, please deploy to production

**Comment by helendallas** [comment]
thanks
