### ISSUE TITLE
FADA website footer

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4295]
tried to edit the webpage; the footer figure (the row of animals) is still blurry; could you provide me with the best resolution this banner should have please?

same is true for the logos?

and where are the pictures stored? I uploaded many to test how I could get it less blurry; I need to delete the old ones now... 
Thanks!

**Comment by helendallas** [comment]
@schmikloi As mentioned, new images overwrite old images, once you have saved

Do this here:

https://fada.sta.do.kartoza.com/admin/bims_theme/customtheme/34/change/

![Image](https://github.com/user-attachments/assets/6d064055-b64e-436d-a4a3-c6ddea960605)
