### ISSUE TITLE
We need to store the full taxonomy for a taxon

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#43]
Please extend the Taxon model to also include these properties:

```
from pygbif import species as sp

species = sp.name_usage(3329049)
print 'Kingdom:', species['kingdom']
print 'Phylum:', species['phylum']
print 'Class:', species['class']
print 'Order:', species['order']
print 'Family:', species['family']
print 'Genus:', species['genus']
print 'Species:', species['species']
print 'Taxon ID:', species['taxonID']
print 'Accepted Name:', species['accepted']
print 'Canonical Name:', species['canonicalName']
print 'Accepted Key', species['acceptedKey']
```
Note that we already have scientific_name which is the same as the canonicalName in my list above.

I am not proposing to normalise these fields so just store them as a flat table in Taxon.

We will use these later to do the searching and reporting 'how many records do we have from Kingdom: Plantae' and we can also use these to generate numbers for our infographic on the landing page.

Additionally if there are subsepecies and variety details for the taxon these should be stored.

**Comment by ismailsunni** [comment]
Done in #48
