### ISSUE TITLE
GBIF Occurrence harvesting - 2024-10-14 07:36:45,638 - ERROR - 400 Client Error: Bad Request for url: http://api.gbif.org/v1/occurrence/search?

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4305]
I harvested Brachipoda on SANParks production and got some errors

Please cna you check what the issue is and if this has occurred previously for the taxon groups

2024-10-14 07:36:45,638 - ERROR - 400 Client Error: Bad Request for url: http://api.gbif.org/v1/occurrence/search?

File txt.

[Brachiopoda 204-1728891404_k75pl9H.txt](https://github.com/user-attachments/files/17360598/Brachiopoda.204-1728891404_k75pl9H.txt)

**Comment by dimasciput** [comment]
This error is fixed on staging, I will deploy updated boundary to production

**Comment by helendallas** [comment]
Thanks
