### ISSUE TITLE
Centroids ready for sections

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4311]
Just as you did with Park centroids, please cna you integrate section centroids for occurrence records that only have the section name and no lat long.

Here is the csv file

[Section centroids_08102024.csv](https://github.com/user-attachments/files/17391096/Section.centroids_08102024.csv)

see 

https://github.com/orgs/kartoza/projects/80/views/1?pane=issue&itemId=72882111&issue=kartoza%7Cdjango-bims%7C4123

**Comment by dimasciput** [comment]
@helendallas added in staging

**Comment by helendallas** [comment]
Works well, thanks, Please deploy to production

**Comment by dimasciput** [comment]
Deployed to live
