### ISSUE TITLE
expert level test

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4313]

**Comment by schmikloi** [comment]
hi @dimasciput 

I just tested the expert level for FADAtims; what I did:

- I signed up with another email to simulate an expert
- I logged in as FADA admin and granted this expert access to be Plecoptera-global expert

what I recognized:

- when I log in as expert, I get the map as very first view --> this should be hidden for all FADAtims
- the taxagroup I was signed up to (Plecoptera global) is not marked in any different color
- I cannot edit anything

Did I do something wrong while registering this expert?

**Comment by dimasciput** [comment]
@schmikloi 

There are only three experts for Plecoptera global

![image](https://github.com/user-attachments/assets/1d769145-efbc-4e56-bfc1-fad4e0d36a5a)

Did you click save?

> when I log in as expert, I get the map as very first view --> this should be hidden for all FADAtims

Yes, I can fix this easily.

**Comment by helendallas** [comment]
Closing this now as explanation provided
