### ISSUE TITLE
Filters for new spatial layers needs updating

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4322]
Please update the spatial filters based on the new layers. New should include:

SANParks and MPUs
SANParks sections
SANParks buffer zones

**Comment by helendallas** [comment]
@dimasciput Please update on staging as well, or mirror staging site with production.

The team are doing training next week and the sites need to be the same if possible.

**Comment by dimasciput** [comment]
@helendallas it's a public holiday today, I will address this over the weekend. It shouldn't take a long time.

**Comment by helendallas** [comment]
Thanks, closing ticket now
