### ISSUE TITLE
online publication of organism groups

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4324]

**Comment by schmikloi** [comment]
@dimasciput @helendallas 

The workflow of implementing organism groups will be as follows: 

- I upload a new organism group from the template that I get from the expert
- then I ask the expert to check it
- s/he edits the organisms group where necessary
- once s/he is ready, we can release this organism group online, visible for the public

So we need a feature to actually release an organism group online; how it this done in the BIMS? Is any new species automatically online?

comment from @dimasciput: I understand this is an important and very useful feature, but there wasn’t any requirement for it, so I didn’t think to implement it. I can definitely add this, and it will probably take me a day to implement and test, or maybe even less.

**Comment by helendallas** [comment]
As per our discussion @dimasciput to implement system whereby unvalidated taxa are not visible to public until expert publishes them.

**Comment by dimasciput** [comment]
The unvalidated taxa now hidden to public or non expert users.

**Comment by schmikloi** [comment]
Thanks @dimasciput, but I am not sure where I can see this and where as an expert I can actually change this?
@helendallas maybe you can help me with that?

**Comment by helendallas** [comment]
@dimasciput Please can you provide a better explanation.

**Comment by dimasciput** [comment]
@schmikloi @helendallas 
For example, in mammals, there is a new unvalidated taxon—one that is still under review. When you log in as a non-expert or regular user, you will no longer see this taxon on the taxa management page.

**Comment by helendallas** [comment]
Ok thanks Dimas

So @schmikloi Here I logged in as helen@frcsa.org.za - admin. -added a taxon - unvalidated
<img width="237" alt="Screenshot 2024-11-26 at 12 01 02" src="https://github.com/user-attachments/assets/07c6d8b9-103d-4946-8fe4-aecb7b36f62d">

Then I logged in elsewhere as hfdallas@gmail.com - normal user -  didn't see the invalidated taxon
<img width="236" alt="Screenshot 2024-11-26 at 12 01 26" src="https://github.com/user-attachments/assets/b880c726-9d26-4e4a-af18-6a5559f26be3">

Then on editing a taxon - there are now 2 unvalidated taxa

<img width="1460" alt="Screenshot 2024-11-26 at 12 03 06" src="https://github.com/user-attachments/assets/16ca8901-e0e3-468a-9492-4fefde465f16">

Then as a normal user, I now no longer see the edited, unvalidated taxon either.

<img width="239" alt="Screenshot 2024-11-26 at 12 04 14" src="https://github.com/user-attachments/assets/284c45ae-9ccd-4607-96fa-730f462689f0">

Makes sense @schmikloi

**Comment by schmikloi** [comment]
Makes super sense! Thanks!

A few issues though:
- the second taxon in your unvalidated-list does not have the 3-points-button on the right; where can I validate this one?
- can we set all the species as invalidated once uploaded, so that the experts can check them first before they go online?
- can we validate all unvalidated species in one go?

**Comment by helendallas** [comment]
Thanks @schmikloi I have created 2 new tickets to capture these issues. Closing this ticket now.
