### ISSUE TITLE
GBIF harvested taxa not showing in dashboards 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4335]
I harvested insects and there are 50 records but these are not showing in side panel dashboard or on the landing page.

<img width="1455" alt="Screenshot 2024-10-30 at 09 37 25" src="https://github.com/user-attachments/assets/c2b2f1b5-2e97-475d-b038-e25c32112616">

They only show if I have selected Insects filter in the Biodiversity module filter. I think this holds for other taxa as well.

<img width="1444" alt="Screenshot 2024-10-30 at 10 47 20" src="https://github.com/user-attachments/assets/2a0a0c36-e3d6-4a08-b5d2-578ab3b18ca0">

I don't think the biodiversity filter is working properly.

**Comment by dimasciput** [comment]
@helendallas, it’s because the landing page is cached for faster performance. I’ll add a button to clear the cache for the landing page.

**Comment by helendallas** [comment]
Thanks Clear chase works, closing
