### ISSUE TITLE
New User login not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4336]
When new user follow the link in the confirmation email they receive a 404 error. They can still sign into the site manually, but the link isn’t working.
 
“Your account has been approved and is now active. (NAME) You can use the login form at: http://sanparks.do.kartoza.com/login”

**Comment by dimasciput** [comment]
this is fixed on production and staging. The url will automatically redirect to the correct location.

**Comment by helendallas** [comment]
![Image](https://github.com/user-attachments/assets/26f7c408-274b-49cb-8540-be3d6c2b9f56)

@dimasciput The email is from FADA, not SANParks.

Login account email is working, just need to update original signs email to SANParks

**Comment by helendallas** [comment]
@dimasciput Please can you fix email notice - this will confuse new signups. Then I can close the ticket

**Comment by dimasciput** [comment]
This is fixed, I have tested it

**Comment by helendallas** [comment]
Thanks
