### ISSUE TITLE
Upload duplicates issue

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4338]
When uploading occurrences to SANPARKS, they received this message.
[error_Roxanne_upload_duplicates.csv](https://github.com/user-attachments/files/17677061/error_Roxanne_upload_duplicates.csv)

**Comment by dimasciput** [comment]
@helendallas this is fixed, there was issue with the database

**Comment by helendallas** [comment]
I haven't checked but closing ticket and will ask Naz to check
