### ISSUE TITLE
DNS Record for SANParks

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/django-bims#4340]
Good day Kartoza Support Team

We need to setup a DNS record for BIMS.sanparks.org.

We kindly ask for your assistance in getting the IP address to which BIMS must point in order for us to link it to [https://sanparks.do.kartoza.com/.](https://sanparks.do.kartoza.com/)

Your assistance will be highly appreciated

Regards
Walter

**Comment by MarinaKartoza** [comment]
This issue was logged as a Lead on the portal.
The request was submitted to myself and Dimas.
Dimas resolved the issue by providing the information as required by the client.
