### ISSUE TITLE
GBIF occurrence data not pulling through to pdf checklist

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4342]
Kruger Park checklist - mammals

Loxodontia missing - there are records but not coming into pdf

<img width="447" alt="Screenshot 2024-11-15 at 07 46 20" src="https://github.com/user-attachments/assets/24c3d3af-7047-4d8d-9298-12ff38919224">

pdf 

<img width="1016" alt="Screenshot 2024-11-15 at 07 46 50" src="https://github.com/user-attachments/assets/406b2a10-2996-498e-ac25-f7fa9d8781e8">

**Comment by helendallas** [comment]
Okay, I see the reason is it was genus records. Let me chat to Dian about this. Please hold off ticket for now

**Comment by dimasciput** [comment]
@helendallas I'm going to move this to "Client to test"

**Comment by helendallas** [comment]
I am going to close this as SANPrks only wanted species included, not genus in pdf.  If ticket #4345 is resolved then all the species should be pulled through here.
