### ISSUE TITLE
GBIF occurrences not pulling through to csv occurrence file

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4343]
I downloaded csv file for Kruger Mammals.

Only 100 records came down in csv, instead of all 20496

<img width="417" alt="Screenshot 2024-11-15 at 08 11 13" src="https://github.com/user-attachments/assets/00bc1dcb-5ea4-4d53-9c39-bfc6701cefef">

Here is the csv file

[test.csv](https://github.com/user-attachments/files/17770952/test.csv)

**Comment by dimasciput** [comment]
@helendallas this is fixed in staging

**Comment by helendallas** [comment]
SO do I need to re harvest all mammals?

**Comment by dimasciput** [comment]
@helendallas No, this is a different bug. You should see the same number of occurrences in both the dashboard and the csv.

**Comment by helendallas** [comment]
Ok thanks

**Comment by helendallas** [comment]
@dimasciput Did you check this out? Any idea what the cause is?

**Comment by dimasciput** [comment]
@helendallas, some of the records from GBIF are not generating UUIDs correctly. I will add them manually for now and investigate the root cause

**Comment by helendallas** [comment]
Ok thanks @dimasciput

**Comment by helendallas** [comment]
I am closing this ticket as GBIF records on dashboard match csv. Created new ticket on UUID issue
