### ISSUE TITLE
GBIF ID not being save when adding taxon to a taxon group

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4344]
Please check why the GBIF id is not being saved - on Kafue production, but may be on others. haven't checked.

It has happened multiple times and I am forced to edit, find GBIF

<img width="1198" alt="Screenshot 2024-11-15 at 09 19 41" src="https://github.com/user-attachments/assets/7b404563-1fcf-4097-8e39-d5917ac6cbc8">

**Comment by dimasciput** [comment]
I have fixed this issue on staging and production
