### ISSUE TITLE
 Checklist Confidence Field Issue

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4350]
Is it possible to populate the Confidence field in the csv checklist download with the highest Certainty field information across all source templates? This field is currently blank.
For example, if Papio ursinus has High, Medium and Low Certainty across three different occurrence uploads respectively, that the Confidence field in the checklist download is High. Or if only Medium and Potential Distribution, the Confidence would be Medium etc. 
 
Hierarchy of Certainty (and Confidence) dropdowns: 
High
Medium
Low
Potential Distribution
Outdated Distribution
Unknown
 
I am unsure how this would work when there are only GBIF sources though. Please let us know what you advise.

**Comment by dimasciput** [comment]
@helendallas this is feasible, but I will need 3-4 hours to implement it. Should I go ahead?

**Comment by helendallas** [comment]
@dimasciput Maybe finish off the other remaining tickets first as there are only about 25 hours remaining.

**Comment by helendallas** [comment]
Please action this as SANParks need it.

**Comment by dimasciput** [comment]
@helendallas, the issue with the blank certainty field is because they uploaded occurrence data with 'Certainty' as the column name, instead of 'Certainty of Identification.' I believe I already provided the correct template for this. I think it would be better for them to re-upload the data with the correct format rather than me fixing it on the backend.

I will add the hierarchy today.

**Comment by helendallas** [comment]
Agreed @dimasciput I have emailed them

**Comment by helendallas** [comment]
@dimasciput From Dian

Our current certainty field contains the following Certainty

High
Medium
Low
Unknown
Potential Distribution
Outdated Distribution

i.e. it is not just about identification. I think the field may have originally been focused on identification only (confidence/certainty of identification, maybe) but then we later changed it to certainty. Or we considered confidence and kept certainty or changed confidence to certainty. I can’t remember but the field is not only around identification now it is also around whether it is likely that species occurs in that place. i.e. if a species was somewhere fifty years ago, then we might not know whether it is there now and if a species is only known to be within a distribution range, then you don’t know if it is actually in the park.

@dimasciput I suggest you update to Certainty, is this a BIMS table for managing or is is hard coded? if latter then please add those listed above.

Thanks

**Comment by dimasciput** [comment]
I have updated this on production

**Comment by helendallas** [comment]
Thanks @dimasciput Downloaded fine, closing ticket.
