### ISSUE TITLE
mistake in the detailed view

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4360]
![Image](https://github.com/user-attachments/assets/790f758e-6a68-4dad-989a-2f95d31c9e35)

If I look on the detailed view of a synonym, then in the third column on the right I see the Valid/Accepted Names, but not the genus and the species name of the synonym; 
I think this third column should be named "Species Information" and always display the information of the species no matter if accepted or synonym AND it should have two additional lines, one for the Author(s) and one for the Status (i.e accepted or synonym)

@helendallas what do you think?

**Comment by helendallas** [comment]
Not sure I follow. For me the NB issue is if the Taxon is a synonym, then I need to see the accepted name.

We are also going to drop Genus and Species columns if I recall from our previous meeting.

Taxon, Family, Status, Author, Accepted Taxon. - would be my suggestion for order

**Comment by schmikloi** [comment]
Ok, we can drop this; I see that it makes sense the way you describe it..
Still, in the Species field it should be only the species name WITHOUT the genus (in this case only "virens").
And you are right, we wanted to drop Genus and Species from the overview table.

**Comment by helendallas** [comment]
Closing as updated in #4380
