### ISSUE TITLE
CSV Master list download not including TOPS

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4365]
TOPS attributes have been added for several. groups. However these are not always brought down in the csv master list download.

The following groups are missing the TOPS after uploading a populated field: Arachnids, Reptiles and Mammals. Strange that it works for some and not others.  Several files- upload success, and download csv.

[success_Reptile_masterlist_30Sept (1).csv](https://github.com/user-attachments/files/17918220/success_Reptile_masterlist_30Sept.1.csv)

[success_Arachnids_masterlist_upload_30Sep_aywSCUG.csv](https://github.com/user-attachments/files/17918221/success_Arachnids_masterlist_upload_30Sep_aywSCUG.csv)

[Downloaded_Arachnids_26Nov.csv](https://github.com/user-attachments/files/17918222/Downloaded_Arachnids_26Nov.csv)

[Mammals-2024-11-26-8-8407990387458285227.csv](https://github.com/user-attachments/files/17918216/Mammals-2024-11-26-8-8407990387458285227.csv)
[success_Mammals_Masterlist_26_Nov_FINAL1-1.csv](https://github.com/user-attachments/files/17918218/success_Mammals_Masterlist_26_Nov_FINAL1-1.csv)
[Downloaded_Reptiles_25Nov.csv](https://github.com/user-attachments/files/17918219/Downloaded_Reptiles_25Nov.csv)

**Comment by helendallas** [comment]
It seems it was a field case issue for those groups. TOPS is coming through in the downloads now. Closing ticket

**Comment by dimasciput** [comment]
@helendallas this is fixed in staging

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good. Please deploy to production

**Comment by dimasciput** [comment]
deployed
