### ISSUE TITLE
Website: Partner Logos

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4369]
@dimasciput : on the landing page, I have copied all logos into one png to guarantee the appearance that the RBINS people wished for; still I struggle to make it bigger (no matter with how many pixels I uploaded the pic) ....
can you please let me know where I could change the size?
Would be good to have the logos correctly until next week when I show the website to the RBINS team

**Comment by dimasciput** [comment]
@schmikloi can you check the landing page again now?

**Comment by schmikloi** [comment]
> @schmikloi can you check the landing page again now?

Looks good now!
Thanks a million and sorry for bothering with that kind of stuff...
