### ISSUE TITLE
Update Summary view

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4380]
Please revise tot he following:

<img width="1202" alt="Screenshot 2024-11-29 at 08 22 46" src="https://github.com/user-attachments/assets/5bde8d59-e211-4465-8ed3-c85b39fc8869">

Taxon, Family, Status, Author, Accepted Taxon

 So Drop genus and species from summary view

Replaces #4360

**Comment by schmikloi** [comment]
@helendallas & @dimasciput 
Please this order:
Taxon, Author, Family, Status, Accepted Taxon
as the author is part of the taxon name and therefore should be close to it
thanks!

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, closing ticket
