### ISSUE TITLE
UUIDS not being created for all GBIF data that is harvested.

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4381]
There is an issue with downloading GBIF data - not all occurrence records ar getting a UUID.  I am sure this is an issue across all BIMS.

Please see here

<img width="892" alt="Screenshot 2024-11-29 at 10 08 03" src="https://github.com/user-attachments/assets/079df0d1-1614-45cb-9098-794e67b96e0c">

**Comment by helendallas** [comment]
temporary fix

https://github.com/kartoza/django-bims/pull/4373

**Comment by dimasciput** [comment]
@helendallas this has been fixed, but I will add another check to make sure the uuid will be generated automatically.

**Comment by helendallas** [comment]
Thanks @ prioductiona and staging?  SANParksk and all other BIMS?

**Comment by dimasciput** [comment]
@helendallas this is fixed on staging

**Comment by dimasciput** [comment]
fixed on production

**Comment by helendallas** [comment]
THanks
