### ISSUE TITLE
Add contextual legends

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#469]
_From @NyakudyaA on October 31, 2018 8:57_

# Problem

Some of the legends we have for our layers are very long. Although we have a scrollbar to navigate the legend it will be nice to have contextual legends.

# Solution

Contextual legends are based on the bounding box of the layer visible
ie
http://maps.kartoza.com/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=kartoza:lada_land_use&styles=&bbox=1822825.125,-4147822.75,3667056.0,-2744173.5&srs=EPSG:3857

_Copied from original issue: kartoza/healthyrivers#286_

**Comment by NyakudyaA** [comment]
_From @gubuntu on October 31, 2018 9:48_

@NyakudyaA please rather put this and other general bims issues in django-bims. Only very instance-specific issues should go in healthyrivers or ledet.

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
