### ISSUE TITLE
UI not consistent

### ISSUE THREAD

**Issue by carina1000** [kartoza/django-bims#472]

**Comment by carina1000** [comment]
#Problem
UI is not consistent, for example, there are at least 3 different cross/close symbols.

![Screen Shot 2018-11-01 at 11.49.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f26b7191a379ee0c2f58415c48be5d4a1f06a3a3dc78e2a436628f0e0abbd73e5b26c13813adb0871fbf00e9298a4f8dbfb49850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f64de74c53a3163f60f43b.png)

# Solution
Please see Icons here to use https://drive.google.com/drive/u/3/folders/1fgljBJo-w47N-dnXZqqsIrcKcjVgKwoy

Let me know if you need more icons!

**Comment by Vries14** [comment]
They are still different, some have black background and some dont.
![screenshot from 2018-11-09 15-37-53](https://user-images.githubusercontent.com/42169058/48266199-57aba100-e437-11e8-93ab-075b9f979265.png)

**Comment by Vries14** [comment]
Icons fixed
