### ISSUE TITLE
Locate by Farm Portion Code does not working

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#494]
## Problem

1. Put `T0KT00000000024100355` in the Locate by Farm Portion Code input field
2. Click Go
3. Nothing happened

**Comment by dimasciput** [comment]
@NyakudyaA I tried to request `http://maps.kartoza.com/geoserver/wfs?COUNT=1&CQL_FILTER=id+%3D+%27T0KT00000000024100355%27&SERVICE=WFS&PROPERTYNAME=id&REQUEST=GETFEATURE&TYPENAME=kartoza%3Afarm_portion&VERSION=2.0.0`, and I didn't get any coordinates data. What did I do wrong?

**Comment by gubuntu** [comment]
that request returned a valid response (though with a strange MIME-type?) though I imagine you are expecting the whole record including the geometry? 

```<wfs:FeatureCollection numberMatched="1" numberReturned="1" timeStamp="2018-11-14T05:30:41.112Z" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://maps.kartoza.com/geoserver/schemas/wfs/2.0/wfs.xsd http://kartoza http://maps.kartoza.com/geoserver/wfs?service=WFS&version=2.0.0&request=DescribeFeatureType&typeName=kartoza%3Afarm_portion http://www.opengis.net/gml/3.2 http://maps.kartoza.com/geoserver/schemas/gml/3.2.1/gml.xsd"><wfs:member><kartoza:farm_portion gml:id="farm_portion.250034"><kartoza:id>T0KT00000000024100355</kartoza:id></kartoza:farm_portion></wfs:member></wfs:FeatureCollection>
```

**Comment by dimasciput** [comment]
@gubuntu yes, without geometry the data will be not useful.

**Comment by NyakudyaA** [comment]
@dimasciput here is a request that returns the json `http://maps.kartoza.com/geoserver/kartoza/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=kartoza:farm_portion&&CQL_FILTER=id ='T0KT00000000024100355'&outputFormat=application/json`

**Comment by gubuntu** [comment]
the search should be fuzzy, i.e. allow a search on part of a farm ID, like so
http://maps.kartoza.com/geoserver/kartoza/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=kartoza:farm_portion&&CQL_FILTER=id%20like%20'T0KT000000000241003%'&outputFormat=application/json

**Comment by dimasciput** [comment]
> @gubuntu 
the search should be fuzzy, i.e. allow a search on part of a farm ID, like so
http://maps.kartoza.com/geoserver/kartoza/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=kartoza:farm_portion&&CQL_FILTER=id%20like%20'T0KT000000000241003%'&outputFormat=application/json

Will do on another PR.

**Comment by Vries14** [comment]
@dimasciput , Locate by farm portion code not working in healthyrivers

**Comment by timlinux** [comment]
@Vries14 Please test when deployed to testing. @dimasciput to update this ticket when ready for testing.

**Comment by Vries14** [comment]
Locate by farm portion code now working
