### ISSUE TITLE
Locate by farm id should be able to search with portion of the string

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#499]
Child of https://github.com/kartoza/django-bims/issues/402

>http://maps.kartoza.com/geoserver/kartoza/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=kartoza:farm_portion&&CQL_FILTER=id%20like%20'T0KT000000000241003%'&outputFormat=application/json

>Ideally the search should first return a list of full matching ids (without geometries, like it currecntly does) and then fetch the geometry (or bounding box) of the single one the user selects, then zoom there.

>but if that response times out or has errors, BIMS will need to handle those and ask the use for a more specific id (or say that the one they searched for is not in the db)

**Comment by Vries14** [comment]
When entering portion of string, return list of matching ids
