### ISSUE TITLE
Add species name and authority to the distribution map

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#514]
Add species name and authority to the distribution map on the detailed dashboard

Appended (Regarding center table title):
> s/records overtime/records over time/

**Comment by Christiaanvdm** [comment]
I am unsure where this information is meant to go? There is no distribution map on the detailed dashboard.

**Comment by Christiaanvdm** [comment]
Should I move the species name up and/or add it prominently at the top - it appears this field is already on the page?

Showing the authority on map is likely possible I'm just worried for instances (such as bellow) where the number of records could make that data hard to read.

<img width="1190" alt="screenshot 2018-12-11 at 15 45 00" src="https://user-images.githubusercontent.com/34506346/49804890-7796f300-fd5c-11e8-9a94-aebf64ecc0a7.png">

**Comment by gubuntu** [comment]
s/records overtime/records over time/

**Comment by Christiaanvdm** [comment]
> s/records overtime/records over time/

Fixed my side in this branch.

**Comment by philipfrenzel** [comment]
I’ve cc’ed Toni to please assist as I’m out in the field this week.

Thanks!

**Comment by toniolsen** [comment]
@Christiaanvdm please remove the species name from the top of the page.
For now lets just leave species name and authority in the table (taxon row), like you have it already.

**Comment by Christiaanvdm** [comment]
@toniolsen ok great, thanks for your feedback. What is it you would like to see about the authority or did you mean you are happy with things as they are and we can close this ticket?

**Comment by toniolsen** [comment]
@Christiaanvdm regarding the authority, we should include it behind the species name (like you have done). Basically just remove "Galaxias zebratus" at the top of the page and leave it as is. Thanks!

**Comment by Christiaanvdm** [comment]
<img width="1369" alt="screenshot 2018-12-13 at 07 01 32" src="https://user-images.githubusercontent.com/34506346/49916763-0dd63080-fea5-11e8-9014-afd3fd814aba.png">
