### ISSUE TITLE
Build in the list of literature at the bottom of the detailed dashboard with links to knowledge database (PDFs/URLs).

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#516]
![screen shot 2018-11-23 at 12 59 46 pm](https://user-images.githubusercontent.com/43198125/48940400-18de1680-ef20-11e8-93e5-b2d41ed62b1c.png)

**Comment by timlinux** [comment]
@dimasciput has done the model updates - we need to add this to the detailed dashboard as a literature list. The literature list should be shown for 

* taxon dashboard
* site dashboard
* multisite dashboard (see #559)

For references that are string based they will simply be listed
For references that are modelled in our citations or geonode docs CMS there should be a hyperlink to the doc.

It might be nice to have an image gallery for cases where the doc is an image.

**Comment by timlinux** [comment]
@dimasciput to do the backed data models 
@Christiaanvdm to do the front end view in the dashboards

**Comment by Christiaanvdm** [comment]
This data is coming as the GeoNode document type.

**Comment by toniolsen** [comment]
Only non-copyright sources PDFs can be provided, otherwise links to where they can  find the PDFs can be provided. @timlinux  @Christiaanvdm

**Comment by helendallas** [comment]
Super-seeded by  #1478
