### ISSUE TITLE
Move spatial filtering into filter drop-down tab

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#517]
Spatial filtering should not be a separate tab on the left menu, but should rather be moved to the 'filtering tab' at the top. 

<img width="871" alt="screenshot 2018-11-23 at 12 55 16" src="https://user-images.githubusercontent.com/44292029/48940504-90ac4100-ef20-11e8-8a20-ffcbf8b3836b.png">

**Comment by toniolsen** [comment]
This is a replicate

**Comment by dimasciput** [comment]
Duplicate https://github.com/kartoza/django-bims/issues/510
