### ISSUE TITLE
We need a form for adding fish data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#518]
From our workshop on 23 November we discussed the development of new forms for FBIS. The link to open a form should be incorporated into the Site details dashboard 'Add fish records'.

![screenshot 2018-11-23 at 13 17 07](https://user-images.githubusercontent.com/178003/48940958-357b4e00-ef22-11e8-9a36-76d249082d1d.png)

Once opened the fish form should look something like this:

![screenshot 2018-11-23 at 13 10 13](https://user-images.githubusercontent.com/178003/48940652-2051ef80-ef21-11e8-9b49-a282bf13f096.png)

To support this we will need to add some new models:

![screenshot 2018-11-23 at 13 12 14](https://user-images.githubusercontent.com/178003/48940795-8d658500-ef21-11e8-9f82-08bc7ff4dbbf.png)

**Comment by timlinux** [comment]
CC @jeremyshelton

**Comment by dimasciput** [comment]
Redundant https://github.com/kartoza/django-bims/issues/749
