### ISSUE TITLE
We need to allocate site codes

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#519]
Every site added to the system:

* First two letters are Secondary Catchment code e.g. G3
* Next four letters of the river name e.g. BERG
* Hyphen
* Five letters describing location e.g. 00001 - legacy data may use alphnumeric strings for the five letter location  which we should continue to support.

**Comment by timlinux** [comment]
We need to display the site id in the dashboard too please

**Comment by timlinux** [comment]
We should add this to the model and update the existing data to comply with this. The Site id catchment part will need to come from geocontenxt. For the river name we will need to add the nearest river name lookup to geocontext. @Christiaanvdm will need to work on that

**Comment by Christiaanvdm** [comment]
requires Issue https://github.com/kartoza/geocontext/issues/64

**Comment by Christiaanvdm** [comment]
@dimasciput Could you please advise on how I should implement this? Am I mistaken in thinking all the work needed is DB side?

**Comment by Christiaanvdm** [comment]
Ok thanks, great. I looked at your code and thought as much but just wanted to make sure.

**Comment by timlinux** [comment]
We are missing the Secondary catchment code at the start of the site code.

Also @dimasciput we need to preserve exisitng codes that already existed and only allocated codes for new sites. Can you go back and fist them out please?
