### ISSUE TITLE
We need to implement the SASS online form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#520]
For the header section of the original sass form we only need the biotope scores.

![screenshot 2018-11-23 at 13 46 12](https://user-images.githubusercontent.com/178003/48941963-3dd58800-ef26-11e8-9cbd-cd3e0025cf3f.png)

![image](https://user-images.githubusercontent.com/178003/48941969-43cb6900-ef26-11e8-9dc5-b566d39e433e.png)

![image](https://user-images.githubusercontent.com/178003/48941981-4af27700-ef26-11e8-8261-65f2c6bd05c7.png)

![image](https://user-images.githubusercontent.com/178003/48941988-4e85fe00-ef26-11e8-8f31-d930c9a56616.png)

The scores at the bottom should be calculated automatically - @helendallas to provide details on how this is done.

**Comment by timlinux** [comment]
The second column (sensitivity weighting) with numbers is internally used for SASS calculation and does not need to be shown to the user.

**Comment by timlinux** [comment]
The taxa listed should be linked back to the taxon table. Most are families so we need to make sure the taxonomy database supports not only species level data.

We don't necessarily need to show the orders (in bold text) if they don't have a sensitivity number next to them - though would be nice to keep them if possible.

The order of the tax listed above must be retained in the form.

**Comment by timlinux** [comment]
The development of the form should be driven by data. @helendallas should have an admin form / view that she can use to add /remove / tweak entries in the SASS form.

**Comment by timlinux** [comment]
The legacy database has both SASS v4 and SASS v5 data in it. We need to support versioning of the SASS sheet and be able to load up the old data too.

**Comment by dimasciput** [comment]
Implemented
