### ISSUE TITLE
Link source and metadata to each context layer, perhaps with an "i" button next to each layer.

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#522]

**Comment by timlinux** [comment]
We should should pull in the layer metadata’s abstract for each layer and have it linked to the I button. We should also show the upstream source of the layer.

**Comment by timlinux** [comment]
@NyakudyaA please make sure that any context layers we serve have their abstract populated. The abstract should at minimum contain:

short description of the layer
source of the layer
date of the layer if available
@Christiaanvdm to make sure this appears in the UI

**Comment by timlinux** [comment]
<img width="549" alt="screenshot 2018-12-04 at 09 43 07" src="https://user-images.githubusercontent.com/178003/49426369-0b8b1c80-f7a9-11e8-9238-e1dc25f6d98f.png">

**Comment by timlinux** [comment]
@carina1000 to come up with the design concept
@NyakudyaA make sure the metadata is populated
@Christiaanvdm to implement the UI

**Comment by NyakudyaA** [comment]
> @NyakudyaA please make sure that any context layers we serve have their abstract populated. The abstract should at minimum contain:
> 
> short description of the layer

This is already available in all layers
> source of the layer

A URL is provided as part of the abstract.
> date of the layer if available

All resources are available from the source sites provided a user needs to download them
> @Christiaanvdm to make sure this appears in the UI

**Comment by Christiaanvdm** [comment]
@dimasciput hi, just confirm if you want this data in the area to the right or rather in the right hand panel (the same place it is being done for the site details when you click a site.)

**Comment by timlinux** [comment]
@dimasciput suggests to use bootstrap popovers @Christiaanvdm

**Comment by carina1000** [comment]
@Christiaanvdm please see my UI suggestions below, let me know what you think.
![LayerInfo1.png]
![LayerInfo2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c495832690aaa789e6ed01e81fe086264c22703d46f9692584e22cee132d0359591aff44595f44fdab8c7ff5b23f75984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81b2bb8a4dc8e03f2ce08b9d02.png)

**Comment by carina1000** [comment]
![LayerInfo1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c495832690aaa789e6ee01e81fe086264c22703d46f9692584e22cee132d0359591aff44595f44fdab8c7ff5b23f75984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81b2bb8a4dc9e83b25e58a9d02.png)

**Comment by Christiaanvdm** [comment]
@carina1000 I’ve been looking at using popovers rather - I’m worried about your suggestions’ scalability and how the current drag + drop functionality might impact visibility?

**Comment by NyakudyaA** [comment]
@Christiaanvdm how are you getting this metadata ?. I hope you are passing the get capabilities to get the abstract of each layer.

https://maps.kartoza.com/geoserver/wms?service=wms&version=1.1.1&request=GetCapabilities

**Comment by carina1000** [comment]
OK @Christiaanvdm just thought we want to minimise popups but I see your point

**Comment by Christiaanvdm** [comment]
@NyakudyaA Thanks :D
@carina1000 Popover giving me a headache… your idea gaining traction.

**Comment by Christiaanvdm** [comment]
I just want to confirm that I should be using the properties in the layer object?

<img width="1184" alt="screenshot 2019-01-03 at 10 14 45" src="https://user-images.githubusercontent.com/34506346/50628451-d5c08b80-0f40-11e9-8c51-9433c6e54e91.png">

**Comment by Christiaanvdm** [comment]
I am just not exactly clear as to what data should be going inside here?

![django-bims-522 metadata](https://user-images.githubusercontent.com/34506346/51005856-3fe0be00-1549-11e9-85cd-f40912e48aaf.gif)

**Comment by Christiaanvdm** [comment]
I believe this is a good place to make a PR. Any other data we need to expose should be easy to adapt from what is already here.

**Comment by Christiaanvdm** [comment]
@NyakudyaA Could you please let me know what data you are passing that would be best to display?

**Comment by Christiaanvdm** [comment]
Leaving this here for my convenience:

mazano [3:21 PM]
http://maps.kartoza.com/geoserver/wms?request=getCapabilities

mazano [3:28 PM]
http://maps.kartoza.com/geoserver/kartoza/erf/wms?request=getCapabilities

mazano [3:35 PM]
something like this maybe https://openlayers.org/en/latest/examples/wms-capabilities.html

**Comment by gubuntu** [comment]
GeoServer (part) implements CSW https://docs.geoserver.org/stable/en/user/services/csw/tutorial.html 

(though it seems only privileged users can access it @NyakudyaA)

so you can use those queries also to retrieve metadata fields. 

Though @NyakudyaA it doesn't seem to manage all the other ISO fields like source, auther, publication date etc. ? If it did you wouldn't need to put them in the abstract but could compose your response from different fields

**Comment by dimasciput** [comment]
implemented
