### ISSUE TITLE
Layer confirmation

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#523]
It may be a good idea to confirm the context layers served up on http://www.sasdi.net/ as recommended by SANBI's technical team.

**Comment by timlinux** [comment]
@NyakudyaA please make sure that any context layers we serve have their abstract populated. The abstract should at minimum contain:

* short description of the layer
* source of the layer
* date of the layer if available

@Christiaanvdm to make sure this appears in the UI

**Comment by timlinux** [comment]
<img width="549" alt="screenshot 2018-12-04 at 09 43 07" src="https://user-images.githubusercontent.com/178003/49426369-0b8b1c80-f7a9-11e8-9238-e1dc25f6d98f.png">

**Comment by timlinux** [comment]
@carina1000 to come up with the design concept
@NyakudyaA make sure the metadata is populated
@Christiaanvdm to implement the UI

**Comment by dimasciput** [comment]
@toniolsen anything you want to still do here?

**Comment by toniolsen** [comment]
@dimasciput 
No, I think this issue can be closed.
