### ISSUE TITLE
Snap sites to nearest river

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#524]
Some sites are not on a river. Please snap these to their nearest river. 
![screen shot 2018-11-23 at 3 45 34 pm](https://user-images.githubusercontent.com/43198125/48946766-67e37600-ef37-11e8-8f29-44dc1d3de53f.png)

**Comment by helendallas** [comment]
Suggest leaving for now, as some of these are on small tributaries that are not on the rivers spatial layer
