### ISSUE TITLE
Need an "i" button to explain some terms.

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#525]
Terms in the system such as native, non-native, translocated and our five categories of endemism need an "i" button with definitions.

**Comment by timlinux** [comment]
@toniolsen I am moving this to version 2 as this is a good ramp up task for @Christiaanvdm 

I think maybe we can use flatpages here to establish a geenral help resource and link out to to that from the introjs tour.

**Comment by timlinux** [comment]
We should add a help button in the tool bar that will launch introjs tour

**Comment by Christiaanvdm** [comment]
@toniolsen Hi Toni, flat pages are simple templated pages that you can input your own data into. We can also setup some templating for you. We would like to do this in a manner that allows you to maintain the resources yourself as much as possible - Your feedback regarding this would be valuable if possible?

**Comment by Christiaanvdm** [comment]
@toniolsen That won’t be necesarry. After we update the current staging site I will be able to demonstrate what flat pages are and how they work - we can then discuss our strategy going forward more easily I believe.
