### ISSUE TITLE
Rename "consulting report" to "report" in the reference category filter

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#527]
This has been changed in the original data. Perhaps the latest version of the data needs to be uploaded. 
![screen shot 2018-11-23 at 4 11 28 pm](https://user-images.githubusercontent.com/43198125/48947684-9e6ec000-ef3a-11e8-8f50-52ac4bc4dc1d.png)

**Comment by dimasciput** [comment]
@toniolsen can we have the latest version of the data?

**Comment by toniolsen** [comment]
@dimasciput 
The latest version is in the Dropbox folder. Do you have access to this folder?
Data for Consolidation --> Fish data -->CFR Fish data --> CFR fish data for FBIS

**Comment by timlinux** [comment]
We should also start thinking about where we want to manage this data going forward:  on the FBIS platform or in the spreadsheet then deleting fish records on FBIS and re-importing. I prefer that we do it in the FBIS platform as things are going to get pretty confusing if we are dropping data and reimporting regularly. Also there are some tasks like GBIF, IUCN and context lookups that happen when we import that create more work for ourselves checking everything has run properly.

For systematic updates (e.g. changing consulting report to 'report') we can do these for you on the platform in the way that @Christiaanvdm has done, just write tickets for us....

**Comment by toniolsen** [comment]
@timlinux how do I update the data on the FBIS platform then?

**Comment by toniolsen** [comment]
@jeremyshelton see @timlinux comment

**Comment by jeremyshelton** [comment]
@timlinux thanks for the explanation. @toniolsen I agree that going the FBIS upload route sounds best. Perhaps @fimasciput can explan how we do this? Thanks

**Comment by Christiaanvdm** [comment]
Adding screenshot of solution as in PR (Pull Request):

<img width="339" alt="screenshot 2018-12-11 at 17 30 49" src="https://user-images.githubusercontent.com/34506346/49810787-9ac89f00-fd6a-11e8-869c-40d71ea36e5d.png">

**Comment by Vries14** [comment]
This has not yet been changed
![Screenshot from 2018-12-12 10-45-43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f2793dd4b168ee1236555a424aaf53444d04bea6d37ef5f22e7a98595abc856c5e72943b17f8eb871ebf01bb728e1bd6b2bf8f5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cf24de14951a11b3464ef647b.png)

**Comment by Vries14** [comment]
Changed to report and working with other filters
