### ISSUE TITLE
Incorporate the endemism categories into the origin filter.

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#528]
![screen shot 2018-11-23 at 4 18 54 pm](https://user-images.githubusercontent.com/43198125/48947966-ab3fe380-ef3b-11e8-8704-99e924b91421.png)

**Comment by timlinux** [comment]
In our workshop @jeremyshelton explained 5 categories:

1) National
2) Regional / provincial
3) catchment
4) subcatchment
5) etc.

@jeremyshelton or @toniolsen to provide the correct list from above

**Comment by timlinux** [comment]
@dimasciput to review the data model and update accordingly then add to the filter UI

**Comment by timlinux** [comment]
<img width="1069" alt="screenshot 2018-12-07 at 08 58 19" src="https://user-images.githubusercontent.com/178003/49632398-45a12c00-f9fe-11e8-829f-a198c24d416d.png">

Also @jeremyshelton can you please confirm that each taxon can have one endemic status only?

**Comment by jeremyshelton** [comment]
Yes, each taxon can have only one endemic status. AND, endemic species
(including all endemic categories) can only be native species (with respect
to origin) - i.e. not non-native or translocated.



www.frcsa.org.za

**Comment by toniolsen** [comment]
1.) Widespread (more than one Freshwater Ecoregion)
2.) Regional endemic level 1 (endemic to a Freshwater Ecoregion (e.g. CFE), more than one primary catchment)
3.) Regional endemic level 2 (endemic to one primary catchment)
4.) Micro-endemic level 1 (<5 rivers, within one primary catchment)
5.) Micro-endemic level 2 (1 river)

@timlinux , these are the 5 endemism categories as per the new fish data to be incorporated.

**Comment by jeremyshelton** [comment]
@timlinux @toniolsen 
Agreed.
