### ISSUE TITLE
Wrong term in the detailed dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#530]
The wrong term is being used in the detailed dashboard.
indigenous --> native
alien --> non-native
![screen shot 2018-11-23 at 4 36 45 pm](https://user-images.githubusercontent.com/43198125/48948738-4c2f9e00-ef3e-11e8-9100-829c0222ca02.png)

**Comment by Christiaanvdm** [comment]
I believe this has already been addressed.
[Uploading Screenshot 2018-12-06 at 11.40.47.png...]
