### ISSUE TITLE
Predictive text

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#536]
Incorporate predictive text and show full species list in species search (drops down underneath the search bar (see BioModelos and OBIS for example).

![screen shot 2018-11-26 at 11 58 36 am](https://user-images.githubusercontent.com/43198125/49007058-3820b200-f173-11e8-824d-b91c4ed0d4c2.png)
![screen shot 2018-11-26 at 12 01 59 pm](https://user-images.githubusercontent.com/43198125/49007076-3d7dfc80-f173-11e8-808f-17b062d62f9c.png)

**Comment by timlinux** [comment]
We can lift some logic from our ford2 project for this….

**Comment by Vries14** [comment]
predictive texts implemented like the examples
