### ISSUE TITLE
Graph downloads

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#537]
Improve resolution of the graphs for download in the detailed dashboard.

**Comment by timlinux** [comment]
Can you confirm if this is for version 2 or 3 @toniolsen ?

**Comment by toniolsen** [comment]
@timlinux, this could be for version 3

**Comment by jeremyshelton** [comment]
Link to #1217

**Comment by helendallas** [comment]
Closed via #1217

**Comment by jeremyshelton** [comment]
Merged with #1217
