### ISSUE TITLE
Base layers "i" button

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#540]
The base layers need an "i" button with the metadata.
![screen shot 2018-11-26 at 1 03 57 pm](https://user-images.githubusercontent.com/43198125/49010497-1a0b7f80-f17c-11e8-844b-bd55898475c1.png)

**Comment by NyakudyaA** [comment]
@toniolsen this feature already exists.

![i-button](https://user-images.githubusercontent.com/2510900/49010962-76bb6a00-f17d-11e8-9027-f9ca04d12883.png)

**Comment by dimasciput** [comment]
@NyakudyaA apparently it's missing in freshwater

**Comment by NyakudyaA** [comment]
> @NyakudyaA apparently it's missing in freshwater

Ohh. Thought it was coming from Django bims

**Comment by timlinux** [comment]
[Demo.xlsx](https://github.com/kartoza/django-bims/files/2619680/Demo.xlsx)
