### ISSUE TITLE
SASS Data Bulk Import Spreadsheet - for input please

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#547]
I have created a bulk import template for SASS data based on our discussion last week. 

Each row represents a unique Site Visit ( Site Code + Sampling Date), and includes all abiotic data (temp, cond, pH etc), and biotope ratings for each.

Then each SASS Taxon is given in the order of the SASS datasheet, per biotope so :
Taxon_S   - Taxon abundance in stones
Taxon_V   - Taxon abundance in vegetation
Taxon_G   - Taxon abundance in gravel/sand/mud
Taxon_T   - Taxon abundance for the site 

Is it possible to automate the Taxon_T, based on Taxon data per biotope (_S, _V, _G) , which would then need to be checked by the capturer for the site.  We are exploring it on excel.

There is also a Georeference conversion tool and a physico-chemical sheet in case the capturer have additional data for other parameters.

Please give feedback on this format for ingesting bulk SASS data into FBIS, before we start using it. If we were to provide a bulk upload option for SASS data on FBIS, this would be the format.
[CFR Invertebrate SASS Data Bulk Import Template.xlsx](https://github.com/kartoza/django-bims/files/2623152/CFR.Invertebrate.SASS.Data.Bulk.Import.Template.xlsx)

**Comment by timlinux** [comment]
@timlinux  to give Helen the thumbs up if the form format is good

**Comment by timlinux** [comment]
![screenshot 2019-01-30 at 10 09 25](https://user-images.githubusercontent.com/178003/51967132-30350500-2477-11e9-9bce-fc084d7657ab.png)

@helendallas for these can we please combine them into the header row

**Comment by helendallas** [comment]
Discussion around this  - no longer necessarily to have SASS bulk upload. Easy to do it per Site using the SASS Form, safer to in term of quality. @dimasciput This ticket can be closed.
