### ISSUE TITLE
Abiotic Data Table

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#548]
We need a table to store all abiotic data that is collected when algal/invertebrate/fish data are collected. I recommend it be based on the **dbo_BioChemCode** table in the Biobase.  This can be refined as there seem to be some redundant columns.

The attached table: Abiotic Data Variables includes all the original Biobase data. There are some new variables that we may want to add although I am not yet sure if they should be included in this table or if they should be separate.  Some have legacy data from Rivers DB such as Water Level, Velocity, Stream Width, Depth
[Abiotic Data Variables .xlsx](https://github.com/kartoza/django-bims/files/2623342/Abiotic.Data.Variables.xlsx)
.

**Comment by timlinux** [comment]
@carina1000 please work on a design concept for this for where and how we should display this data. Then we can pass over to @dimasciput to implement,

**Comment by timlinux** [comment]
@carina1000 any updates on this?

**Comment by timlinux** [comment]
@helendallas can you confirm if this is a priority for version 2 or something that can come in v3 once we have the other SASS functionality is in place? i.e. is there any dependency from SASS for this ticket?

**Comment by carina1000** [comment]
@dimasciput please hand this over to a developer

**Comment by helendallas** [comment]
Superseeded by  #1479
