### ISSUE TITLE
SASS Metric calculations

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#550]
SASS data generate three metrics:

- SASS Score
- Number of Taxa
- ASPT (Average Score Per Taxon)

SASS Score is the sum of the sensitivity weightings of all taxa recorded in a biotope (S, V, G) and/or at a site (Total).
Number of Taxa is the count of all taxa recorded in a biotope  (S, V, G)  and/or at a site (Total).
ASPT is SASS Score divided by Number of Taxa (expressed using 2 decimal places) recorded in a biotope  (S, V, G)  and/or at a site (Total).
An example is attached

[Silvermine River SASS5_Site 1.xlsx](https://github.com/kartoza/django-bims/files/2623494/Silvermine.River.SASS5_Site.1.xlsx)

SASS5 Sensitivity weightings have been provided in the SASS Data Form (see issue #520 )
Legacy Rivers DB has both SASS4 data and SASS5 data -  the sensitivity weightings are different for some taxa and some taxa disappear or appear from one version to another.  SASS4 data metrics (SASS Score, Number of Taxa and ASPT) need to be based on SASS4 sensitivity weightings (see issue #520 ).  Going forward all data will be SASS5 only.

@dimasciput please take careful note of this:

For both SASS4 and SASS5, there are two families that are given sensitivity weightings based on the number of species: 1 species, 2 species, > 2 species. These are **Baetidae** and **Hydropsychidae**, with sensitivity weightings of 4, 6 and 12 for 1 species, 2 species, > 2 species.

SASS metrics (SASS Score, Number of Taxa and ASPT) - should be presented for the Site as well as individual biotopes.

**Comment by timlinux** [comment]
![screenshot 2019-01-30 at 11 32 37](https://user-images.githubusercontent.com/178003/51971829-c6baf380-2482-11e9-9764-20c6b68cf983.png)


For the total column, the default value should be the greatest of S/V/GSM, editable by the user to override it if needed.
