### ISSUE TITLE
We need a multi-site dashboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#559]
When doing a filter that returns multiple sites I should be able to see a new panel and detailed dashboard which shows the summary across all the sites. For example a conservation officier wants to know all the sites for a given cartchment area and see a list of the species found in that catchment. We should have a nice summary dashboard e.g. number of endemics, number of translocated etc.

We whould have a nice report that can be printed for this too in same fashion as detailed dashboard.

CC @jeremyshelton @toniolsen

**Comment by Vries14** [comment]
Can view summary of multiple sites in detailed dashboard.  Able to download data in CSV format
