### ISSUE TITLE
We need a wiers context layer

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#563]
✓	Weir - THIS TABLE IS EMPTY - DO WE NEED IT? MS ACCESS contains 5271 weir records with lat longs which we could turn into a backdrop dataset if needed. Check to see if we can bring it in as a WMS / WFS layer from Water Affairs. Admire: Contact Mike Silberbauer.

**Comment by NyakudyaA** [comment]
@timlinux I have extracted the layer from the Ms Access and published this in Geoserver. We can add this layer to freshwater as a context layer.

I have emailed Mike to ask if we can get WMS/WFS feed from water affairs otherwise we use the one I have published.

**Comment by dimasciput** [comment]
@jeremyshelton @toniolsen is this priority for version 3? or can we close it?

**Comment by timlinux** [comment]
Closed based on discussion with FRC
