### ISSUE TITLE
Species breakdown origin and richness chart text is unreadable

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#565]
<img width="404" alt="screenshot 2018-12-05 at 16 29 23" src="https://user-images.githubusercontent.com/178003/49520020-09a98200-f8ab-11e8-9d7b-5667f9ca8171.png">

The text on these charts is unreadably small. Please find a way to make it larger.

**Comment by Christiaanvdm** [comment]
Chart is coming from the healthy rivers build.
