### ISSUE TITLE
The climate charts are still not showing all data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#566]
@mazano can you confirm that the full 12 months are added to the geocontext service now?

@dimasciput can you please update the context data for each site after @NyakudyaA confirms?

<img width="400" alt="screenshot 2018-12-05 at 16 31 51" src="https://user-images.githubusercontent.com/178003/49520263-8a687e00-f8ab-11e8-8898-26755502567b.png">

**Comment by NyakudyaA** [comment]
@timlinux all the data has been added to the context. There should be no missing months because all the layers are visible in Geoserver

**Comment by NyakudyaA** [comment]
@dimasciput let me look at this I think I have found what is causing this to occur.

The get feature info is failing for some of these layers.
![screenshot 2018-12-16 at 22 32 13](https://user-images.githubusercontent.com/2510900/50058531-7ada1680-0182-11e9-8d19-0078d07d15c5.png)

We might need to investigate all the layers to check out if there is any layer in having this problem.

@Vries14 can you please go through all the layers in GeoServer and view them in QGIS or directly in GeoServer and not if the get feature-info is working or not.

NB: If you load the layers in QGIS just use the `Identify` button to which layers are working and which ones are not.

**Comment by NyakudyaA** [comment]
@Christiaanvdm have you updated all context documents and can I check if all graphs are returning the full months
