### ISSUE TITLE
Average Monthly Rainfall graph of some sites not available

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#574]
![image](https://user-images.githubusercontent.com/45623652/49575833-5abd8280-f94c-11e8-8e19-33debd034eca.png)
Some sites do not have the average monthly rainfall graph available, as in the above example.

**Comment by timlinux** [comment]
@dimasciput can you pull out any specific sites that do not get context and then

**Comment by NyakudyaA** [comment]
@dimasciput I fixed all the layers that were not working and now I can get all the months
https://geocontext.kartoza.com/api/v1/geocontext/value/group/25.8694/-28.1796/rainfall_group/

![screenshot 2018-12-19 at 14 49 55](https://user-images.githubusercontent.com/2510900/50221338-776ea700-039d-11e9-8969-2eb86b1194de.png)
![screenshot 2018-12-19 at 14 50 09](https://user-images.githubusercontent.com/2510900/50221340-776ea700-039d-11e9-9bc5-f589cd632f0b.png)
![screenshot 2018-12-19 at 14 50 18](https://user-images.githubusercontent.com/2510900/50221341-78073d80-039d-11e9-8a73-f662ed4054b8.png)

**Comment by NyakudyaA** [comment]
> @dimasciput I fixed all the layers that were not working and now I can get all the months
> https://geocontext.kartoza.com/api/v1/geocontext/value/group/25.8694/-28.1796/rainfall_group/
> 
> ![screenshot 2018-12-19 at 14 49 55](https://user-images.githubusercontent.com/2510900/50221338-776ea700-039d-11e9-8969-2eb86b1194de.png)
> ![screenshot 2018-12-19 at 14 50 09](https://user-images.githubusercontent.com/2510900/50221340-776ea700-039d-11e9-9bc5-f589cd632f0b.png)
> ![screenshot 2018-12-19 at 14 50 18](https://user-images.githubusercontent.com/2510900/50221341-78073d80-039d-11e9-8a73-f662ed4054b8.png)

@dimasciput I am afraid that we might be doing in a spin on this issue. Is there any issues related to importing geocontext data. 

This request https://geocontext.kartoza.com/api/v1/geocontext/value/group/25.8694/-28.1796/rainfall_group/ 

produced all the months available for the different months but trying out the same request today results in some months missing. 
![screenshot 2019-01-16 at 17 30 01](https://user-images.githubusercontent.com/2510900/51259214-5f963d00-19b4-11e9-96f4-be66d9e4ad8f.png)

Even on my local machine I get all the months.
What is your take on the current situation ?

**Comment by NyakudyaA** [comment]
This has been pretty constant for now. All the records are available in GeoServer and are retrievable
