### ISSUE TITLE
We need to confirm the category field in collection records

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#576]
@jeremyshelton or @toniolsen can you confirm if having category in our data model still makes sense when we add the endemism attribute (see #528). Or will the endemism (e.g. restricted to catchment) and category (e.g. translocated) make sense to use together?

<img width="1519" alt="screenshot 2018-12-07 at 09 02 56" src="https://user-images.githubusercontent.com/178003/49632625-0e7f4a80-f9ff-11e8-8a9f-f748ad64a95c.png">

**Comment by toniolsen** [comment]
@timlinux 
Endemism and origin (e.g. native, non native, translocated) must be separate fields. Is that right, @jeremyshelton?

**Comment by jeremyshelton** [comment]
@timlinux @toniolsen 
Yes, that's correct. But the five 'endemism categories' all fall within the origin category 'native'

**Comment by dimasciput** [comment]
implemented
