### ISSUE TITLE
Fish sanctuaries layer-FishFSA and FishRehab symbol colours are too similar

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#577]
The colours of the legend for FishFSA and FishRehab fish sanctuaries are very similar and it is, therefore, hard to distinguish between the 2 on the map.

![image](https://user-images.githubusercontent.com/45623652/49633582-8733d600-fa02-11e8-86ab-ffa3ec30641a.png)

**Comment by barbaralr** [comment]
![image](https://user-images.githubusercontent.com/45623652/49633657-db3eba80-fa02-11e8-81c4-6a265bdc5224.png)
This image shows it clearer

**Comment by gubuntu** [comment]
@NyakudyaA simple copied the source BGIS style but I agree it can be improved. Boundaries should also not be drawn or at least polygons that do not have sanctuaries should not be show. Assign to @emsyvn

**Comment by NyakudyaA** [comment]
We already have a layer for Quaternary Catchment and we can ignore showing it in this case.

![screenshot 2018-12-07 at 12 56 42](https://user-images.githubusercontent.com/2510900/49643971-c6bceb00-fa1f-11e8-8f3e-e0022cad36ac.png)

all other styling issues will be allocated to @emsyvn
