### ISSUE TITLE
Secondary catchment area layer difficult to see

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#578]
![image](https://user-images.githubusercontent.com/45623652/49633994-1c839a00-fa04-11e8-9032-2ca51c98a5f2.png)
Colour used for secondary catchment area layer is very light and therefore difficult to see on the map.

**Comment by gubuntu** [comment]
@NyakudyaA please set up @emsyvn with geoserver access so she can tackle styling issues and improvements

**Comment by gubuntu** [comment]
Yes pls set up Emma on maps.kartoza.com (where else?)

**Comment by NyakudyaA** [comment]
> Yes pls set up Emma on maps.kartoza.com (where else?)

Have sent her the credentials in a direct slack message.

**Comment by NyakudyaA** [comment]
![screenshot 2018-12-07 at 16 09 48](https://user-images.githubusercontent.com/2510900/49652358-8a4ab880-fa3a-11e8-87ef-7287829900af.png)
