### ISSUE TITLE
We need to understand where ecological condition data comes from

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#600]
![screenshot 2018-12-13 at 12 40 26](https://user-images.githubusercontent.com/178003/49933487-6b35a600-fed4-11e8-9c18-d0edd70c52fe.png)

@toniolsen can you clarify - will this be coming from the fish spreadsheet or is there a place where we can fetch it from?

**Comment by toniolsen** [comment]
@timlinux Ecological condition only applies to the SASS data. The category correlates to a specific SASS score.
