### ISSUE TITLE
We need to confirm the name of each ‘drawer’ in the search panel

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#603]
![screenshot 2018-12-13 at 12 49 50](https://user-images.githubusercontent.com/178003/49933925-ad131c00-fed5-11e8-8035-e1722007138f.png)

@helendallas @toniolsen @jeremyshelton can you please confirm what the names of each panel section should be? Chatting with Helen today she requested that **Administrative areas** be renamed to **Spatial filter**.

@Christiaanvdm  once we have received the feedback from them, please update accordingly.

**Comment by Christiaanvdm** [comment]
@toniolsen @jeremyshelton Could you please confirm the final names of these containers?

**Comment by toniolsen** [comment]
@Christiaanvdm 

Here is the final list and order for the filters: 
Module
Temporal Scale
Spatial Scale
User Boundary
Ecological Condition
Origin
Endemism
Conservation Status
Reference Category
Study Reference
Collector/Assessor.

**Comment by Christiaanvdm** [comment]
@toniolsen Hi Toni, if possible, could you please give the info in the form:
Old name -> New name

**Comment by toniolsen** [comment]
@Christiaanvdm Hi
This is just the order we would like the filters to appear in. The only name change is:
Collector -> Collector/Assessor
