### ISSUE TITLE
Import SASS data

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#605]
We have threee legacy databases available:

* 1) Linked dump is for reference to see the full schema
* 2) Rivers dump: is all tables from rivers with data
* 3) Rivers dump relevant tables: removes all tables that are not needed and fish, IHI, landused

We need to use 3) above for the actual migration.

3 is what we need to use for SASS migration to FBIS
3 has water chem and biotopes
3 is coming via we transfer

**Comment by dimasciput** [comment]
- [ ] Check that all necessary data has been imported
