### ISSUE TITLE
Rainfall Rasters Graph- unit measurement not indicated

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#611]
![image](https://user-images.githubusercontent.com/45623652/49996210-1d35a680-ff97-11e8-9368-d25120605585.png)

The unit measurement of the rainfall (in the rainfall rasters graph) of a specified site is not indicated in heading nor in the y-axis name.

**Comment by NyakudyaA** [comment]
@dimasciput we can hardcode these in the graphs as they are not going to change. If you do a get legend for each of the layers you can see the units attached to this.

The units of measurement here is (mm)
