### ISSUE TITLE
Relative Humidity Rasters graph-unit measurement of relative humidity not indicated

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#612]
![image](https://user-images.githubusercontent.com/45623652/49996582-0e032880-ff98-11e8-8bfc-1a728f537c03.png)

No indication of unit measurement of humidity used in graph heading or y-axis title (e.g. percentage).

**Comment by NyakudyaA** [comment]
@dimasciput we can hardcode these in the graphs as they are not going to change. If you do a get legend for each of the layers you can see the units attached to this.

For this the unit is Percentage (%)

**Comment by dimasciput** [comment]
we don't have this graph anymore
