### ISSUE TITLE
Filters-add scrolling option when opening multiple filters

### ISSUE THREAD

**Issue by barbaralr** [kartoza/django-bims#617]
When opening and applying more than one filter, not possible to scroll down to see bottom filters. Not a big problem, but adding scrolling option wil ease use when applying multiple filters.

**Comment by barbaralr** [comment]
![image](https://user-images.githubusercontent.com/45623652/50303806-e11eac00-0496-11e9-85db-52f584d253bc.png)

**Comment by dimasciput** [comment]
Scrollbar has been added
