### ISSUE TITLE
Catchments should have labels in the map

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#621]
@NyakudyaA can you please add labels for the catchment boundaries (all levels) so that when we have a map we can see which catchment records are in?

![2019-01-03 05_49_40-window](https://user-images.githubusercontent.com/178003/50623175-e27eb880-0f1b-11e9-8096-8a9322b4972d.png)

**Comment by NyakudyaA** [comment]
I have added the labels in the Geoserver layers except for the quinary catchments because they do not have any column that can be used for labelling.

![screenshot 2019-01-16 at 15 18 27](https://user-images.githubusercontent.com/2510900/51251434-01f8f500-19a2-11e9-9546-b09a635f502f.png)

**Comment by NyakudyaA** [comment]
This has been done. We can reopen if you need to change the label properties
