### ISSUE TITLE
Make sure we email to admin when new users sign up

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#643]
Make sure that we email fbis@frcsa.org.za when new users sign up indicating that a new user is registered. The new user is from a recognised org the admin receiving the email should get a link in the email taking them to an admin page where they can tag the user as a data contributor.

**Comment by Christiaanvdm** [comment]
@dimasciput do we want this email sent as the user signs up or after they activate their account?

**Comment by dimasciput** [comment]
Duplicate https://github.com/kartoza/django-bims/issues/1236
