### ISSUE TITLE
We need a rivers layer colour coded according to geomorphological zones

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#646]

**Comment by gubuntu** [comment]
Just add a new named style in geoserver and call that when needed

**Comment by NyakudyaA** [comment]
Added a new style for the zones. Now we can request the rivers layer with the alternate style http://maps.kartoza.com/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:rivers-nfepa&styles=geomorphological_zones&bbox=1774016.875,-4141456.25,3790971.5,-2255659.25&width=768&height=718&srs=EPSG:3857&format=application/openlayers#

**Comment by Christiaanvdm** [comment]
LGTM
