### ISSUE TITLE
Make sure we get elevation in the geo context - use to order the sites in multiple site report by elevation descending

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#648]

**Comment by Christiaanvdm** [comment]
I just want confirm that it is the "Records Per Area" table I want to order?
<img width="1381" alt="screenshot 2019-01-30 at 08 45 45" src="https://user-images.githubusercontent.com/34506346/51963237-92880880-246b-11e9-8e16-6168082a4470.png">

**Comment by dimasciput** [comment]
@Christiaanvdm yes that's correct

**Comment by dimasciput** [comment]
Implemented
