### ISSUE TITLE
We need to import all the fish data from GBIF and reimport the FRC fish spreadsheet excluding the SAIAB data in FRC sheet

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#650]

**Comment by timlinux** [comment]
@dimasciput we can take the logic from species explorer to do this:

https://github.com/kartoza/SpeciesExplorer/blob/master/species_explorer/species_explorer_dialog.py#L139

@jeremyshelton to provide a list of taxa (or higher taxa) to fetch. Then we should recurseively fetch those taxa and all below them

**Comment by jeremyshelton** [comment]
Working on it. We  should have the fish taxa list ready later today and a working invertebrate list in the next few days. @toniolsen @helendallas @timlinux @dimasciput
