### ISSUE TITLE
For a site have a panel which shows mini sass and inaturalist records are nearby

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#652]
you can get minisass sites from http://minisass.org/en/map/ WFS

**Comment by jeremyshelton** [comment]
I think we leave this for v3?

**Comment by timlinux** [comment]
Jeremy to contact GroundTruth to garner their support.

**Comment by timlinux** [comment]
We could add the minisass as a WMS overlay with a popup that shows the data that they show on their site plus a link back to the minisass page.

**Comment by timlinux** [comment]
See #653

**Comment by timlinux** [comment]
We could import non reasearch grade records from inaturalist and have them tagged as such on our system so that we can filter them on or off per search.

@dimasciput to investigate how we can pull data from Inaturalist

**Comment by dimasciput** [comment]
Redundant https://github.com/kartoza/django-bims/issues/1182
