### ISSUE TITLE
Tutorial Tip Adjustments

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#659]
![screen shot 2019-01-14 at 11 34 17 am](https://user-images.githubusercontent.com/43198125/51105353-72acdf80-17f1-11e9-8e07-5634e0bc3ea6.png)

@Christiaanvdm

**Comment by Christiaanvdm** [comment]
## Tip 2 ##

screen shot 2019-01-14 at 11 34 35 am

**Comment by Christiaanvdm** [comment]
### Tip 3 ###
https://user-images.githubusercontent.com/43198125/51105797-b0f6ce80-17f2-11e9-99e1-f3eb84dbc2c9.png

**Comment by Christiaanvdm** [comment]
### Tip 4 ###

![image](https://user-images.githubusercontent.com/43198125/51105946-1a76dd00-17f3-11e9-8142-0d2681a722bd.png)

**Comment by Christiaanvdm** [comment]
## Tip 5 ##

[!image](https://user-images.githubusercontent.com/43198125/51106172-aee13f80-17f3-11e9-9ad7-92200a9bc1e5.png)

**Comment by Christiaanvdm** [comment]
### Tip 6 ###

![image](https://user-images.githubusercontent.com/34506346/51135217-2342cf80-1842-11e9-9a81-cbb57beadcbf.png)

**Comment by Christiaanvdm** [comment]
### Tip 7 ###

![image](https://user-images.githubusercontent.com/43198125/51106449-7d1ca880-17f4-11e9-9f73-b7ddb9d607cd.png)

**Comment by Christiaanvdm** [comment]
### Tip 8 ###

![image](https://user-images.githubusercontent.com/43198125/51106605-ef8d8880-17f4-11e9-8048-f45a2f82c3c0.png)

**Comment by Christiaanvdm** [comment]
### Tip 9 ###

![image](https://user-images.githubusercontent.com/43198125/51106718-3c715f00-17f5-11e9-840d-78e222cb5889.png)

**Comment by Christiaanvdm** [comment]
### Tip 10 ###

![image](https://user-images.githubusercontent.com/43198125/51106823-93773400-17f5-11e9-9d3c-2d27ae647214.png)

**Comment by Christiaanvdm** [comment]
### Tip 11 ###

![image](https://user-images.githubusercontent.com/43198125/51107058-64ad8d80-17f6-11e9-8cc0-a089b0e641c5.png)

**Comment by Christiaanvdm** [comment]
@toniolsen Regarding tip 3 and 4 - After implementing your suggestion for tip 3 it reads: "In order to find the data you need, use the search function." and tip 4 would then read: "with its many filters." - This sentence should possibly then start with a capital letter or it could read strangely if one reads the tutorial from start to finish?
