### ISSUE TITLE
Add zoom to home button In map page

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/django-bims#679]
# Problem

There are two buttons on the map navigation page. One to zoom in and another to zoom out.
It would be nice to include a ZOOM to HOME button that will allow a user to navigate from one position where he is zoomed in to view the whole extent of SA.

![screenshot 2019-01-16 at 12 05 19](https://user-images.githubusercontent.com/2510900/51241913-7b371e80-1987-11e9-8e70-206f6068fea4.png)

# Solution
Add the button

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
