### ISSUE TITLE
FBIS logo

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#685]
[FBIS logo_PDF.pdf](https://github.com/kartoza/django-bims/files/2767575/FBIS.logo_PDF.pdf)

Please add Jeremy's FBIS logo to the landing page.
@carina1000

**Comment by Christiaanvdm** [comment]
@toniolsen Hi Toni, Would you like us to replace both the logos in the header and footer with this new logo I assume? Also we will need to then review that font colour at the least - It will probably have to be white for clarity (this refers to the text at the bottom not the image's blue)

**Comment by carina1000** [comment]
@toniolsen let me know if you'd like me to rework the logo - keep with the same style just make it a bit more adaptable to our current website? I am also just a bit worried about scaling - It looks great large but could get lost in the header?

**Comment by toniolsen** [comment]
@Christiaanvdm 
Yes, please replace the logo in the header and footer with the new logo. Happy to change the font colour to white.
@carina1000 
Please rework the logo to what you think looks good. Maybe if you could make an example and we can see how it looks.

**Comment by carina1000** [comment]
Decided not to use this Logo
