### ISSUE TITLE
FBIS stamp

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#687]
Please create a FBIS stamp that will appear at the bottom of downloads (graphs and data).

![screen shot 2019-01-17 at 10 35 03 am](https://user-images.githubusercontent.com/43198125/51305481-aed77e80-1a43-11e9-8b72-cc807ee53fa9.png)

**Comment by Christiaanvdm** [comment]
@toniolsen Could you please get me a bigger version of the image intended as a stamp?

**Comment by toniolsen** [comment]
@Christiaanvdm 

Is this big enough? Also please note that the final stamp must have the correct final web address.

![screen shot 2019-01-28 at 8 40 09 am](https://user-images.githubusercontent.com/43198125/51818753-ae0eda00-22d8-11e9-8565-497ab73d5478.png)

**Comment by Christiaanvdm** [comment]
@toniolsen Excellent, thank you 👍

**Comment by toniolsen** [comment]
@Christiaanvdm 
Please park this issue for now, if you haven't already done it. Jeremy and I are working on a better logo design and will send that to you for the purpose of the "stamp" at a later stage.
