### ISSUE TITLE
Fish Species Overview Panel

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#694]
This is our final mockup for the fish species overview panel. Please note the comments.

@timlinux @Christiaanvdm @carina1000 

<img width="332" alt="fig 1 - species overview dashboard" src="https://user-images.githubusercontent.com/43198125/51385853-19161f00-1b29-11e9-8081-88a61a7cb46d.png">

**Comment by Christiaanvdm** [comment]
Current pannel for comparison: 

![newgif](https://user-images.githubusercontent.com/34506346/51983268-e82ad800-24a0-11e9-9920-f0af7fee24e4.gif)

**Comment by Christiaanvdm** [comment]
- [ ] Change heading to -> Species Overview
- [ ] Update species details to include indicated data
- [ ] Added link to IUCN species page
- [ ] Added title to image to give image information (e.g. gbif page) on mouse over

**Comment by Christiaanvdm** [comment]
Creating additional ticket for number of sites fish can be found in.

**Comment by carina1000** [comment]
Comment from meeting: Change conversation status to some sort of slider as @Christiaanvdm suggested

**Comment by carina1000** [comment]
Comment from meeting: Remove "link to" IUCN (3rd party database
