### ISSUE TITLE
Fish Species Detailed Dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#695]
This is what we would like the fish species detailed dashboard to look like. Please note the comments.

@timlinux @Christiaanvdm @carina1000 
<img width="1434" alt="fig 2 - species detailed dashboard" src="https://user-images.githubusercontent.com/43198125/51385440-fb948580-1b27-11e9-9ecf-6c7473d69e7c.png">

**Comment by carina1000** [comment]
Comment from meeting: Flip the order of Conservation status around - start with DD

**Comment by carina1000** [comment]
@Christiaanvdm please see designs here and in avocode
[FBIS_Dashboard Mocks (dragged) 2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46ceb6b310bda7a89ce1bd4ca54ff4d4044924783a44eb2f6284e42fba4632415d4d52be011a001ea9aacd39aca43921db080aecd73f5972926e14adb8821eed04ee738f4c80a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59c4bcd5ff64ae84552a217242e.pdf)
