### ISSUE TITLE
Fish Single Site Overview Panel

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#696]
This is what we would like the single site overview panel to look like. Please take note of the comments.

@timlinux @Christiaanvdm @carina1000 

<img width="308" alt="fig 3 - single site overview dashboard" src="https://user-images.githubusercontent.com/43198125/51385516-2f6fab00-1b28-11e9-9936-dbd95cb6f881.png">

**Comment by toniolsen** [comment]
@carina1000 
You have already done it, but just to make sure, remove the "sites" row underneath the "Biodiversity data" table.

**Comment by carina1000** [comment]
@Christiaanvdm please see design here and in avocode
[FBIS_Dashboard Mocks (dragged).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46ceb6b310bda7a89ce1bd4ca54ff4d4044924783a44eb2f6284e42fba463243434d0eee1e020a17b8eb8339a3e76d248b5d0dbfd76b0b27c33c11acb9d01aeb52be238e5d99a4fedb1294b7607caddecd5d340c041f83fe5830a09c4dc151f143e44556b65e.pdf)
