### ISSUE TITLE
Fish Single Site Detailed Dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#697]
This is our final mockup for the fish single site detailed dashboard. Please refer to both images and see the comments. Figure 4a is what we would like to feature in the table.

@timlinux @Christiaanvdm @carina1000 

<img width="1439" alt="fig 4 - single site detailed dashboard" src="https://user-images.githubusercontent.com/43198125/51385667-98572300-1b28-11e9-9b9e-9c186ce70e34.png">

<img width="225" alt="fig 4a - table inside single site detailed dashboard" src="https://user-images.githubusercontent.com/43198125/51385678-a3aa4e80-1b28-11e9-91dd-5a27aafcc349.png">

**Comment by carina1000** [comment]
Comment from meeting:
• Add fish icon at the top to show that you are on a fish record
• Sampling method should be included
• Records = Occurrences (this is standard throughout)

**Comment by Christiaanvdm** [comment]
• Remove number of sites in bottom picture's "Records and sites" drawer

**Comment by carina1000** [comment]
@Christiaanvdm please see this design here and in avocode
[FBIS_Dashboard Mocks (dragged) 2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46ceb6b310bda7a89ce1bd4ca54ff4d4044924783a44eb2f6284e42fba4632415d4d52be011a001ea9aacd39aca43921db080aecd73f5972926e14adb8821eed04ee738f4c80a4a0980e91b6697abad2c51a7c0c0f0a88f85734a59c4bcd5eff43e14e54ad1b242e.pdf)
