### ISSUE TITLE
Fish Multi-Site Overview Panel

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#698]
This is what we would like the multi-site overview panel to look like (i.e. if the user searches by area such as Ecoregion).

@timlinux @Christiaanvdm @carina1000 

<img width="323" alt="fig 5 - multi-site area overview dashboard" src="https://user-images.githubusercontent.com/43198125/51385949-6eeac700-1b29-11e9-83a9-fe3183591738.png">

**Comment by Christiaanvdm** [comment]
• Open detailed dashboard buttons for each column.
• No buttons for add data.

**Comment by carina1000** [comment]
@Christiaanvdm please see designs here and in avocode
[FBIS_Dashboard Mocks (dragged).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46ceb6b310bda7a89ce1bd4ca54ff4d4044924783a44eb2f6284e42fba463243434d0eee1e020a17b8eb8339a3e76d248b5d0dbfd76b0b27c33c11acb9d01aeb52be238e5d99a4fedb1294b7607caddecd5d340c041f83fe5830a09c4cc859f549e3485cb65e.pdf)

**Comment by Christiaanvdm** [comment]
![image](https://user-images.githubusercontent.com/34506346/54432571-469ad580-4732-11e9-996c-ffbd60c500b1.png)
