### ISSUE TITLE
Fish Multi-Site Detailed Dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#699]
This is what we would like the fish multi-site detailed dashboard to look like. Please see figure 4b for what we would like to feature in the table. 

@timlinux @Christiaanvdm @carina1000 

<img width="1439" alt="fig 6 - multi site detailed dashboard 2" src="https://user-images.githubusercontent.com/43198125/51386072-dacd2f80-1b29-11e9-9853-40640f0e9bc3.png">

<img width="222" alt="fig 4b - table insite multi-site area detailed dashboard" src="https://user-images.githubusercontent.com/43198125/51386094-f5070d80-1b29-11e9-9067-5305c0158341.png">

**Comment by Christiaanvdm** [comment]
Meeting comment: Filter history top left starts expanded

**Comment by carina1000** [comment]
@Christiaanvdm please see dashboard design here and in avocode
[FBIS_Dashboard Mocks (dragged).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46ceb6b310bda7a89ce1bd4ca54ff4d4044924783a44eb2f6284e42fba463243434d0eee1e020a17b8eb8339a3e76d248b5d0dbfd76b0b27c33c11acb9d01aeb52be238e5d99a4fedb1294b7607caddecd5d340c041f83fe5830a09c4dc15afe4ee74c5cb65e.pdf)
