### ISSUE TITLE
SASS Single Site Detailed Dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#700]
Please see our comments on the SASS single site detailed dashboard template. The original template can be found in in the FRC_Kartoza shared folder on Dropbox in SASS data and in the reporting folder. 

@timlinux @Christiaanvdm @carina1000 

![sass_single_site_detailed dashboard 1](https://user-images.githubusercontent.com/43198125/51388999-bd04c800-1b33-11e9-813f-69c5d86ca3d2.png)
![sass_single_site_detailed dashboard 2](https://user-images.githubusercontent.com/43198125/51389007-c2faa900-1b33-11e9-9ec2-14742058e7da.png)

**Comment by timlinux** [comment]
@toniolsen for navigating to the actual SASS forms we propose to do it from the sass count like this:

![screenshot 2019-02-04 at 11 30 26](https://user-images.githubusercontent.com/178003/52200119-8d162e00-2870-11e9-83f3-4e291e0f85dc.png)

**Comment by Christiaanvdm** [comment]
• Bar graphs will be coloured based on ecological category.
• Selected date should be selected

**Comment by timlinux** [comment]
[Generation of Ecological Categories for SASS data interpretation.docx](https://github.com/kartoza/django-bims/files/2839940/Generation.of.Ecological.Categories.for.SASS.data.interpretation.docx)

The document referenced in the diagram above is provided here.

**Comment by timlinux** [comment]
> @toniolsen for navigating to the actual SASS forms we propose to do it from the sass count like this:
> 
> ![screenshot 2019-02-04 at 11 30 26](https://user-images.githubusercontent.com/178003/52200119-8d162e00-2870-11e9-83f3-4e291e0f85dc.png)

Actually pertaining to this, @timlinux and @dimasciput think it will be clearer that we add a block on the main SASS dashboard which lists each SASS form completed for that site (with the option to click throght to any individual sass form).

**Comment by timlinux** [comment]
Also a couple more notes:

* Biotope ratings come from the top of the sass form
* Sensitivity come SASS.SassTaxon.sass5score attribute
* sensitivity chart is an aggregate query of total number of species per bracketed sensitivity group (tolerant, very tolerant etc.)

**Comment by toniolsen** [comment]
@helendallas Please see above comments. Are you happy with that process of obtaining an individual SASS form?

**Comment by toniolsen** [comment]
@timlinux @dimasciput 
Please see Helen's comment above.

**Comment by timlinux** [comment]
> [Generation of Ecological Categories for SASS data interpretation.docx](https://github.com/kartoza/django-bims/files/2839940/Generation.of.Ecological.Categories.for.SASS.data.interpretation.docx)
> 
> The document referenced in the diagram above is provided here.

On chatting with Helen, she provided the following sheet to further clarify the calculations:

[Ecological Category Expanded.xlsx](https://github.com/kartoza/django-bims/files/2840914/Ecological.Category.Expanded.xlsx)

**Comment by timlinux** [comment]
[Generation of Ecological Categories for SASS data interpretation.docx](https://github.com/kartoza/django-bims/files/2840920/Generation.of.Ecological.Categories.for.SASS.data.interpretation.docx)

I also updated the generation doc based on my discussion with @helendallas to make things clearer.

**Comment by timlinux** [comment]
@helendallas and friends:

I am also asking @dimasciput to add another block which is a table of all the SASS records for this site in the form:

Date | SASS Score | ASPT Score | Taxon Count
------------ | ------------- |---------------|-----------
[21 Feb 2019]() | 10 | 3| 200
[21 Feb 2019]() | 10 | 3| 200

etc.

When you click on the date, it would take you over to the actual sass form.

**Comment by helendallas** [comment]
Sounds fine thanks Tim and Dimas. 
Quick note - please use the terminology that is standard with SASS - so SASS Score (ideally SASS5 Score or SASS4 Score)
Number of Taxa (not Taxon Count)
ASPT (not ASPT Score)

**Comment by helendallas** [comment]
Please check to order for displaying SASS taxa and the hierarchy...order and family. It is very important that the order is retained, for both data capture, display and download.  Also applicable to csv downloads.

Left hand column should be higher level, next column family (where applicable)
See in SASS5_Data_sheet Revised for FBIS and SASS Taxa.pdf
[SASS Taxa.pdf](https://github.com/kartoza/django-bims/files/2883323/SASS.Taxa.pdf)

**Comment by helendallas** [comment]
You can remove abbreviation in parenthesis when full description is given:  stones in current (SIC) - remove (SIC) , similarly for others.  SASS record, biotopes...

**Comment by helendallas** [comment]
Proportion of sensitive taxa - please can you use the same colour palette as the ecol category - otherwise it looks to variable.  Get colour palette from Carina. (Blue, Green, Yellow, Red) - purple not used here, but is used for ecological category

**Comment by helendallas** [comment]
Please can you add a description that becomes visible when you put you mouse on "Proportion of sensitive to tolerant taxa) as follows:

Proportions based on sensitivity weightings as follows: Highly tolerant (1 to 3), Tolerant (4 to 7), Sensitive (8 to 11), Highly sensitive (12 to 15)

**Comment by dimasciput** [comment]
Hi @helendallas , thanks for the comments. But I think it's better if you create a different ticket instead so the developer will notice the issues.

**Comment by carina1000** [comment]
Please see Ecological Condition Colours here as well as in the FBIS Style Guide
![screen shot 2019-02-22 at 14 42 05](https://user-images.githubusercontent.com/35214829/53243290-0c4c9400-36b0-11e9-8bef-79d246bbff1d.png)
