### ISSUE TITLE
SASS Multiple Sites Detailed Dashboard

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#701]
Please see our comments on the SASS multiple sites detailed dashboard template. The original template can be found in in the FRC_Kartoza shared folder on Dropbox in SASS data and in the reporting folder. 

@timlinux @Christiaanvdm @carina1000 

![sass_multiple_site_detailed dashboard_1](https://user-images.githubusercontent.com/43198125/51389121-035a2700-1b34-11e9-991a-54757c79235f.png)
![sass_multiple_site_detailed dashboard_2](https://user-images.githubusercontent.com/43198125/51389129-081edb00-1b34-11e9-83c8-b629db32feb0.png)

**Comment by timlinux** [comment]
As discussed in our meeting on wed 6 feb for the map:

![image](https://user-images.githubusercontent.com/178003/52401076-88988200-2ac9-11e9-861f-8b254a0a1857.png)

We will show whatever layers the user has added in their project, no need to hard code the geomorphological zones here.

**Comment by timlinux** [comment]
* For graticule https://openlayers.org/en/latest/examples/graticule.html
* For scalebar https://openlayers.org/en/latest/examples/scale-line.html

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/52401651-e37ea900-2aca-11e9-8e58-8941ce866ca3.png)

Make the site code clickable to take you to the actual site sass dashboard.

I think we must ignore the drag and drop comment for now and make the dashboards static as far as possible with the exception of hyperlinks to other dashboards.

**Comment by timlinux** [comment]
![screenshot 2019-02-07 at 11 26 02](https://user-images.githubusercontent.com/178003/52401932-97803400-2acb-11e9-9e7e-027733fc8322.png)

Sass score average bar charts should be shown in the form of my screenie above (for all the mini charts)

**Comment by timlinux** [comment]
![screenshot 2019-02-07 at 11 32 40](https://user-images.githubusercontent.com/178003/52402113-18d7c680-2acc-11e9-88a9-9f5ca4462131.png)

Ignore squares and circles etc. in the chart - use the same symbol for all

Hover over a symbol should show the site id

**Comment by timlinux** [comment]
![screenshot 2019-02-07 at 11 39 28](https://user-images.githubusercontent.com/178003/52402483-0f029300-2acd-11e9-9fb6-1cea423f161a.png)


To be clear we discussed in our workshop on 7 Feb that we will do not interactive filter changing fro the dashboards - as far as possible we should treat the dashboards as non-interactive

**Comment by timlinux** [comment]
As discussed with @helendallas for cases where the selected sites cover multiple ecoregions/zones we will try to break it out into discrete scatterplots, up to a maximum of four charts. Each chart would have a header indicating the name of the ecoregion and zone.

If more than four unique combinations of ecoregion/zone exist we will show a simple table listing the unique ecoregions found across all the sites with a note below indicating that the charts are only displayed for multisite dashboards having < 4 unique combinations of ecoregion/zone.

![img_1232](https://user-images.githubusercontent.com/178003/52627786-da248080-2ebe-11e9-8e71-0e0b6006eebe.JPG)

**Comment by dimasciput** [comment]
@timlinux @toniolsen is there any limitation on how many sites we can display in the dashboard?

**Comment by dimasciput** [comment]
Implemented
