### ISSUE TITLE
Update information view of location site

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#71]
## Problem

Current look 

![screen shot 2018-06-28 at 2 08 03 pm](https://user-images.githubusercontent.com/1979569/42018596-d0625360-7adc-11e8-850a-35990c163f40.png)

## Solution

What we want

![screen shot 2018-06-28 at 2 10 52 pm](https://user-images.githubusercontent.com/1979569/42018708-16324f44-7add-11e8-8871-11cd3f431e9c.png)

child of https://github.com/kartoza/LEDET_BIMS/issues/183

**Comment by meomancer** [comment]
hi @gubuntu 
is this ticket still an issue?

Because the mockup already changed
and already has PR for that

PR : https://github.com/kartoza/django-bims/pull/192
New mockup : https://github.com/kartoza/LEDET_BIMS/issues/169#issuecomment-409573836

**Comment by gubuntu** [comment]
redundant
