### ISSUE TITLE
Improve clustering performance and results

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#710]
## Problem

Our current approach of clustering is not suitable for big data. Our plan to improve it is to do the clustering in the geoserver, here are couple of links that might help the process : 

- https://docs.geoserver.org/latest/en/user/data/database/postgis.html
- https://gis.stackexchange.com/questions/11567/spatial-clustering-with-postgis
- https://docs.geoserver.org/latest/en/user/data/database/sqlview.html

I've tried displaying location site with geoserver with simple query using sql view : 
![image](https://user-images.githubusercontent.com/1979569/51526389-d1fb9700-1e64-11e9-8b28-839a1a4dfc5f.png)

**Comment by gubuntu** [comment]
other suggestions:

## GeoServer rendering transformation - PointStacker
https://docs.geoserver.org/latest/en/user/styling/ysld/reference/transforms.html#point-stacker.  Send a filter and auth in the request or in a sqlview so just the desired points get clustered. The example renders the centroids of grid cells so we _should_ be able to render them as the grid cells themselves...

## postgis clustering
like we do in HS.io

## putting together our own custom rendering transformation / WPS

**Comment by dimasciput** [comment]
updated
