### ISSUE TITLE
filter panel not responsive

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#726]
![Screenshot 2019-01-25 at 16.12.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7b51e32a64c5b27ef113294f5f5c5cb053181d1ba6acda6fb4bc2e75db0d5fecd06b0d72c06942a9b9821fbe53bf74d84b86b3ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fc05cf44ee44552a3153071ab.png)

**Comment by dimasciput** [comment]
This will be changed in https://github.com/kartoza/django-bims/issues/730
