### ISSUE TITLE
Refactor User Model to use GeoNode's User

### ISSUE THREAD

**Issue by lucernae** [kartoza/django-bims#74]
We should use GeoNode's User model for BIMS.
This will remap foreign keys and several attributes.

child of #58 

child of https://github.com/kartoza/LEDET_BIMS/issues/4

**Comment by lucernae** [comment]
Why it doesn't automatically close, I wonder.

Anyway, there are several unittest fails because we use GeoNode's Profile.
See PR #94 .
But, I think it is now fairly straightforward to fix this, so I handover the issue back to @dimasciput .

**Comment by NyakudyaA** [comment]
@gubuntuI have tested this in relation to other tickets and  the basic permissions for Geonode are not filtering properly so users even if I assign users to groups I cannot filter them in Geonode

**Comment by gubuntu** [comment]
@NyakudyaA I think we can say the user model has been refactored so I'm closing this. Please move the layer filtering testing an comments to https://github.com/kartoza/LEDET_BIMS/issues/43
