### ISSUE TITLE
Tidy up panel buttons

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#742]
![image](https://user-images.githubusercontent.com/178003/51941904-61cdb200-241e-11e9-84ad-e2baac41d6df.png)

There will probably be more coming so can we

1) get them laid out nicely in a row
2) Change "Add Sass" to "SASS +"
3) Change "Open Detailed Dashboard" to just "Dashboard"

**Comment by Christiaanvdm** [comment]
- [ ] Get them laid out nicely in a row
- [ ] Change "Add Sass" to "SASS +"
- [ ] Change "Open Detailed Dashboard" to just "Dashboard"
