### ISSUE TITLE
We need to confirm whether sass score etc should be displayed (read only) on the SASS form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#748]
![screenshot 2019-01-30 at 09 31 05](https://user-images.githubusercontent.com/178003/51965312-c8c88680-2471-11e9-8d64-a9194441d6ed.png)

@helendallas can you please confirm if we want to show this, updating it automatically as we enter each taxon's data?

**Comment by Christiaanvdm** [comment]
See issue #550

**Comment by helendallas** [comment]
sorry, I didn't mean to close issue. Just comment. Still learning the ropes on GitHub:)

**Comment by dimasciput** [comment]
Has been added to the develop branch
