### ISSUE TITLE
We need a fish form!

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#749]
![screenshot 2019-01-30 at 11 45 18](https://user-images.githubusercontent.com/178003/51972643-91afa080-2484-11e9-802b-59e36a83bcbe.png)

The map should be at a large scale so you can validate the location

We should also be able to manually enter the lat/long - if there is an existing site withing 400m it shoudl warn you and allow you to  'attach' the record to that site.

If creating a new site then the user should be able to add a description and manually override the site code. The description and lat/long should be above the date on the above form mockup.

**Comment by timlinux** [comment]
All options (biotope / method etc.) should have a 'not specified' option if unknown

**Comment by timlinux** [comment]
Add taxon should allow selecting an existing taxon or creating a new one (with GBIF validation?)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/51973227-ce2fcc00-2485-11e9-9040-d6a90cd3cfab.png)

Alternative way of selecting the site would be to add the fish records from the side panel...by adding a button above

**Comment by dimasciput** [comment]
Hi @timlinux , should we show the form as popup or create a new page for this?

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux @toniolsen @carina1000 
A few changes to the fish for needed, then good to go:
1. Add option to indicate 'Study reference' and 'Reference category' below 'Collector'. Reference category to have drop-down options available (like on map). 
2. Options to add information on **sampling effort** next to **sampling method**: effort can be entered either as 'time (min)' or 'area (m)'. User needs to be able to choose which one they did, either with a drop-down or column options.
