### ISSUE TITLE
FBIS Map Background layer not clearing 

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#769]
There is a layer on my laptop that doesn't clear, both of live and staging site. Helen's laptop plus one other user.
![image](https://user-images.githubusercontent.com/45286876/52329994-e14e1900-29fc-11e9-891e-ab51ba2275b2.png)

Text from Tim's examination of my coding:
http://staging.healthyrivers.kartoza.com/bims_proxy/https://maps.tilehosting.com/data/v3/11/1133/1230.pbf.pict?key=GfepnJl8jdQrAm6UYO66

**Comment by dimasciput** [comment]
closing it now, will reopen if it's still have issue
