### ISSUE TITLE
Spatial filtering and geocontexts

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#774]
We need to update the way that the spatial scale works in relation to geocontext.

In the same way we have 'graphable' geocontext groups, we should establish a new group context called 'heirarchical' which expresses a heirachy between the layers. The order of layers / services in the group will be significant e.g.

"Catchement", "Quaternary catchment" ....

When a group is heirachical the spatial scale should express these relationships as a heirachical scale (as we currently see in admin boundaries).

@jeremyshelton / @toniolsen please share the spreadsheet that defines the list of spatial filters you wish to see.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/178003/52340017-59293d00-2a17-11e9-8ba1-3487355a4ec1.png">

All the spatial scale drawers should map to groups and should provide the same UI - a tree (or simple list for groups with a single entry) with a small filter box above the tree so that you can filter out non-matching nodes.

**Comment by timlinux** [comment]
This means the catchment / ecoregions should be reimplemented as the standardised tree.

**Comment by timlinux** [comment]
This also implies that for a given service in geocontext we need to be able to relate it to another so that we can e.g. find all the subcatchments that belong to a catchment. We can chat with @dimasciput to see how he modelled the political boundaries.

**Comment by timlinux** [comment]
For version two we discussed with FRC that we will not worry with heirachy and have a flat system of spatial filters so that it maps to existing geocontext implementation. So what we would like to see is one drawer for each filterable layer with no heirachy. In version 3 we will look at implementing the heirachy.

**Comment by dimasciput** [comment]
implemented
