### ISSUE TITLE
Create Site Detail Widget

### ISSUE THREAD

**Issue by Christiaanvdm** [kartoza/django-bims#778]
![sitedetails](https://user-images.githubusercontent.com/34506346/52402823-e9c25480-2acd-11e9-922d-9eae073ccad8.png)

**Comment by Christiaanvdm** [comment]
<img width="274" alt="screenshot 2019-02-11 at 13 47 29" src="https://user-images.githubusercontent.com/34506346/52561542-5b6b0d00-2e04-11e9-8f05-b2cdf00be5e4.png">

**Comment by carina1000** [comment]
Hi @Christiaanvdm I think we should reduce using all caps too frequently as it reduces legibility.
Check the spacing at the Site Coordinates tab and just ensure the blue is one that's in our colour palate :)
