### ISSUE TITLE
Retrieve the geomorphic data for each site

### ISSUE THREAD

**Issue by Christiaanvdm** [kartoza/django-bims#784]
FBIS have requested a geomorphological data field in their latest side panel. @NyakudyaA Could you please advise me as to what source would be the best for this data?

**Comment by NyakudyaA** [comment]
@Christiaanvdm I think they are referring to this layer

Source: http://maps.kartoza.com/geoserver/kartoza/wms?
layers_name= `kartoza:geoclass`
category_of_interest = `geo_class`
