### ISSUE TITLE
Update search results panel

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#79]
## Problem

Currently we display every occurrences of species in search result panel : 

![screen shot 2018-06-29 at 4 20 17 pm](https://user-images.githubusercontent.com/1979569/42084675-8261c68c-7bb8-11e8-979a-45ec18f4bb16.png)

## Proposed Solution

I think we should group them, and we can show the occurrences in different view : 

![sidepanel_psd___121___shape_1_copy__rgb_8_](https://user-images.githubusercontent.com/1979569/42085414-8ced90ac-7bba-11e8-8ce2-06825900aa7b.png)

**Comment by timlinux** [comment]
Agreed. Also showing the collector is not interesting unless working at an individual record level where we could expand out all the collection record info to show the taxonomy, collection date etc
