### ISSUE TITLE
Update freshwaterbiodiversity.org title

### ISSUE THREAD

**Issue by Christiaanvdm** [kartoza/django-bims#792]
## Problem ##

Title currently has a spelling error. It also shouldn't be healthy rivers.

<img width="418" alt="screenshot 2019-02-12 at 11 26 21" src="https://user-images.githubusercontent.com/34506346/52625169-0f2dd480-2eb9-11e9-8efb-59fab07a0bb8.png">

## Solution ##

Find out what this should be and fix in the freshwater repo.

**Comment by Christiaanvdm** [comment]
@timlinux I was thinking this should maybe just be Freshwater Biodiversity? I could also ask FBIS themselves?

**Comment by timlinux** [comment]
Remove all references to healhtyrivers [sic] and its permutations and rather refer to Freshwater Biodiversity everywhere please.

**Comment by dimasciput** [comment]
fixed
