### ISSUE TITLE
New map renderer needs better SLD

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#797]
Currently the sites are sometimes showing under the clusters:

![image](https://user-images.githubusercontent.com/178003/52700029-c725b500-2f7f-11e9-926e-e2f1fdde5bff.png)

@NyakudyaA Please review the SLD from @dimasciput and fix

**Comment by NyakudyaA** [comment]
@gubuntu I have been trying to improve this style for the FBIS clusters. 
* It looks like the green points are rendering underneath the big yellow clusters but in fact, these are actually at different sites. 
* I have been looking at using each rule as a
```
<FeatureTypeStyle>
 <Rule>
 
 </Rule>
</FeatureTypeStyle>
```
but once I incoperate the rendering transformation then it doesn't work.

* I am now thinking of just putting in scale based rendering to control what draws at a particular scale. ie the green points represent single sites.

* I could also reduce the size of the clusters but it won't solve how the map would look like.

Do you have any suggestion about how to improve this ?

**Comment by gubuntu** [comment]
what did we do for the Lutra project (Dartmoor heritage)?

you could switch to normal styling when really close and then to clustering at smaller scales, mutually exclusive

**Comment by NyakudyaA** [comment]
Thanks, @gubuntu I figured out how to implement this. 
![screenshot 2019-02-21 at 15 32 06](https://user-images.githubusercontent.com/2510900/53172550-45243480-35ee-11e9-9971-853ce5405a43.png)

I have put a rule to prevent the clusters to draw all the way ie when we close enough it renders the points rather than the cluster

**Comment by dimasciput** [comment]
Nice @NyakudyaA , it looks better.
