### ISSUE TITLE
Negative rates make bad stacked charts

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#802]
@helendallas currently we have these rates for site biotope ratings:

![screenshot 2019-02-14 at 10 55 27](https://user-images.githubusercontent.com/178003/52774919-197dd900-3047-11e9-955d-083e5622850b.png)

(see the ratings list [here](http://testing.healthyrivers.kartoza.com/admin/sass/rate/))

With the -1 rating for "Present, not rated" it makes our stacked bar chart look ugly:

![image 1](https://user-images.githubusercontent.com/178003/52774996-48944a80-3047-11e9-99c7-ee06e8d0adcc.png)

Having negative numbers for the stacked bar chart doesn't make sense to me - can we remove the negative entry or perhaps recode them so that they also have a 0 value?

CC @dimasciput

**Comment by helendallas** [comment]
The ratings above are mostly for catchment condition as well as some for biotopes.

Older data may not have the biotope ratings specified in which case it should be left blank.   I suspect that these are all **-1 = present, not rated**.  In which case can we not record them as present, not rated?

Also there are biotopes missing Marginal vegetation in current and marginal vegetation out of current  - both should be a shade of green and before aquatic vegetation. Then gravel, sand and mud all need to be in shades of brown/beige please.  Historic data may lump marginal vegetation as one....
