### ISSUE TITLE
Spatial filter layer details

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#805]
See the attached spreadsheet for the spatial layers (in order) we want to be able to filter by, the sources and short description of each layer.
The source and short description should be information available when selecting the layer in the form of an "I" button next to the heading. @carina1000 we discussed this today.

We have created folders for each layer in the Dropbox folder:
FRC_Kartoza Shared Folders for FBIS --> GIS Context Layers
We also have a folder for future layers we would like to include at a later stage.

Water Management Areas, Catchment, Critical Biodiversity Areas and Protected Areas layers are missing, but should become available in the next few days. 

@timlinux @Christiaanvdm @dimasciput @jeremyshelton 

[Kartoza ticket 1- Spatial filter breakdown.xlsx](https://github.com/kartoza/django-bims/files/2865139/Kartoza.ticket.1-.Spatial.filter.breakdown.xlsx)

**Comment by toniolsen** [comment]
Please ensure to retain the same order of the spatial layers list from the spreadsheet in the system.
i.e:

**1. River
2. Geomorphological zone
-Mountain headwater stream
-Mountain stream
-Transitional
-Upper foothills
-Lower foothills
-Lowland river
-Unclassified
3. Freshwater Ecoregion of the World
4. Province
5. Management area
-Water Management Area
-Sub Water Management Area
-River Management Units
6. Catchment
-Primary
-Secondary
-Tertiary
-Quaternary
-Quinary
7. SA Ecoregion
-Ecoregion Level 1
-Ecoregion Level 2
8. Critical Biodiversity Area (CBA)
-Protected area
-Critical biodiversity areas
-Ecological support areas
9. National Freshwater Ecosystem Priority Area (NFEPA)
-NFEPA fish sanctuaries (all species) 2011
-NFEPA fish sanctuaries 2011
-NFEPA river FEPAs 2011
-NFEPA Wetland clusters
-NFEPA Wetlands
-NFEPA Wetlands vegetation
10. Strategic Water Source Areas (WSA)**

@timlinux @dimasciput

**Comment by NyakudyaA** [comment]
@toniolsen There are some layers which we do not. Can you please clarify where we could source them.

**Comment by toniolsen** [comment]
@NyakudyaA @timlinux @dimasciput @jeremyshelton 

All the missing layers can be found in the shared Dropbox folder. 
FRC_Kartoza Shared Folder for FBIS --> GIS Context Layers.

**Comment by jeremyshelton** [comment]
<img width="1125" alt="Screenshot 2019-04-09 at 14 19 29" src="https://user-images.githubusercontent.com/44292029/55799808-8a36f400-5ad2-11e9-9329-f24150e89f8e.png">
@dimasciput @toniolsen @NyakudyaA

**Comment by NyakudyaA** [comment]
@toniolsen cc @jeremyshelton the only layer that is missing is **River Management Units** Where can I get this layer ?

**Comment by toniolsen** [comment]
@NyakudyaA 
We are still waiting for this layer from Nancy (SANBI). Hopefully we will get it by tomorrow. I will let you know as soon as we get it.
Thanks.

**Comment by dimasciput** [comment]
Implemented
