### ISSUE TITLE
Remove abbreviations for SASS biotopes

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#841]
You can remove abbreviation in parenthesis when full description is given: stones in current (SIC) - remove (SIC) , similarly for others. SASS record, biotopes...

@dimasciput @helendallas 
![screen shot 2019-02-20 at 9 58 33 am](https://user-images.githubusercontent.com/43198125/53075571-3195a280-34f6-11e9-9433-61fcdabb58bb.png)

**Comment by dimasciput** [comment]
Please address this issue @Christiaanvdm
