### ISSUE TITLE
Geomorphological zone - ecological categories

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#844]
@dimasciput @Christiaanvdm 
The document discussed

![screen shot 2019-02-20 at 11 17 50 am](https://user-images.githubusercontent.com/43198125/53080374-34e25b80-3501-11e9-88fa-918b731e902c.png)

**Comment by NyakudyaA** [comment]
This has been implemented in Geocontext now
![screenshot 2019-02-20 at 12 05 34](https://user-images.githubusercontent.com/2510900/53084313-43347580-3509-11e9-9459-a6862033566e.png)
