### ISSUE TITLE
Master fish species list for South Africa

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#859]
This is the Master fish species list for South Africa. It includes all taxonomic details, scientific authorities, habitat, origin, endemism and conservation status. 

[SA Master fish species list_Final.xlsx](https://github.com/kartoza/django-bims/files/2900750/SA.Master.fish.species.list_Final.xlsx)

@dimasciput @timlinux @jeremyshelton @helendallas

**Comment by dimasciput** [comment]
Thank you for the detailed list @toniolsen ! I converted to csv file here : 
[SA.Master.fish.species.zip](https://github.com/kartoza/django-bims/files/2903415/SA.Master.fish.species.zip)

I will start working on this.
