### ISSUE TITLE
About

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#864]
Please can you revise the text in the **About** at the top of the testing webpage:

The Freshwater Biodiversity Information System (FBIS) is a platform for visualising and sharing freshwater biodiversity information for South African rivers.  The current version of FBIS includes national algal data, national SASS (South African Scoring System) data from the legacy **Rivers Database**, national aquatic invertebrate data from the legacy **Biobase**, regional invertebrate (Western Cape) data and national fish data (including SAIAB data via GBIF). 

The FBIS is a project of the Freshwater Research Centre (www.frcsa.org.za) and Kartoza (www.kartoza.com) and is funded by the JRS Biodiversity Foundation and the South African National Biodiversity Institute (SANBI).  

The FBIS project builds on Kartoza's BIMS platform to provide freshwater biodiversity specific features. We strive to follow open standards and work with platforms such as GBIF, IUCN etc.

**Comment by timlinux** [comment]
Reassigned to just @Christiaanvdm so it is clear who should do it
