### ISSUE TITLE
add grid cluster option

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#868]
# problem

The current clustering solution through GeoServer is great and should remain the default

However, an alternative view is required, equivalent to the grid view in GBIF

This could be accessed from the UI as a separate layer or via a control that switches the clustering view. 

# Proposed solution

Use [ST_SnaptoGrid](http://postgis.refractions.net/docs/ST_SnapToGrid.html) in PostGIS (here's an [example](https://gis.stackexchange.com/a/11620)), either as a view or materialised view defined in the database and published in GeoServer or dynamically as a GeoServer SQL view layer

**Comment by gubuntu** [comment]
also look at https://github.com/biodiv/anycluster

**Comment by timlinux** [comment]
Out of scope, closing.
