### ISSUE TITLE
Permalink does not restore multisite dashboard

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#871]
Tried to use this

http://testing.healthyrivers.kartoza.com/sass/dashboard-multi-sites/?taxon=&search=Trichoptera&siteId=&collector=&category=&yearFrom=1996&yearTo=2008&months=2&boundary=&userBoundary=&referenceCategory=&riverCatchment=&reference=&endemic=&conservationStatus=%5B

To point a potential partner at a multisite report and we just see this:

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/178003/53523894-b9774000-3ae6-11e9-94d6-3aee2a4c5d3d.png">

**Comment by dimasciput** [comment]
fixed
