### ISSUE TITLE
Species detail panel is still a bit broken

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#881]
![forms](https://user-images.githubusercontent.com/178003/53587128-40cdbd80-3b92-11e9-90dc-d35c83b2ee44.gif)

Top heading cut off

Panel headers show hand cursor

Otherwise, it is looking nice!

**Comment by Christiaanvdm** [comment]
Also:

Back button + Close button on top heading not showing.

**Comment by Christiaanvdm** [comment]
Parent of https://github.com/kartoza/freshwaterbiodiversity.org/issues/309

**Comment by dimasciput** [comment]
fixed
