### ISSUE TITLE
Water Monitoring Sites

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#891]
from Mike Silbauer: SilberbauerM@dws.gov.za

Water quality monitoring sites
 
I maintain the following information at http://www.dwa.gov.za/iwqs/gis_data/ :
Monitoring points in Google Earth format (KMZ)
Monitoring points in shapefile format (including a DBF table and XML metadata)
It is feasible to download and unzip the shapefile programmatically.
 
The KML file system that I maintain for showing sites in Google Earth is at http://www.dwa.gov.za/iwqs/wms/data/WMS_pri_txt.asp:
Table of links to various types of data
Includes links to HTML tables for each primary drainage region
The attached R script web_read_monpoints.R shows how to download all the HTML tables programmatically.
 
Flow gauging sites
 
The hydrological section maintains an information service at http://www.dwa.gov.za/hydrology/
A list of verified data is at http://www.dwa.gov.za/hydrology/Verified/hymain.aspx
For a known monitoring site code, e.g. "A2H027" one can structure a URL to download the data for the site code automatically.
The attached R script flow_plot_www.R shows how to do this.
 
In order to reduce the load on the flow data server, the hydrology section has placed a limit on the number of records that one can download at once - I think it is 7000.
It is not a good idea to annoy the webmaster at hydrology - blacklisting is not nice L
 
One of my tasks for the year is to draw up a formal procedure for keeping the water quality server running after I leave.
 
cc @helendallas

**Comment by timlinux** [comment]
Historical and current flow guages should be shown maybe with a different symbol to differentiate them.

**Comment by jeremyshelton** [comment]
Here is the latest from Mike at DWS:

The hydrological services catalogue of verified flow data at each monitoring site is currently off-line. The IT section is in the process of migrating the www.dwa.gov.za domain to www.dws.gov.za , which is proving to be more tricky than envisaged.
 
The URL for hydrology is http://www.dwa.gov.za/hydrology/ and is likely to become https://www.dws.gov.za/hydrology/
