### ISSUE TITLE
Add sampling method to fish data summary

### ISSUE THREAD

**Issue by Christiaanvdm** [kartoza/django-bims#894]
Child of #875 
@dimasciput In which table/filed can sampling method be found (if it is available yet)?
![image](https://user-images.githubusercontent.com/34506346/53688619-50decc00-3d4f-11e9-815b-f8d73d09e76c.png)

**Comment by dimasciput** [comment]
@Christiaanvdm There is a model for sampling method, you can populate dummy data there. What you need to do here is to show the sampling method for all collection in chart.

**Comment by dimasciput** [comment]
Implemented
