### ISSUE TITLE
We need to figure out how to deal with not rated biotopes

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#905]
![image](https://user-images.githubusercontent.com/178003/53728744-1888dc00-3e7c-11e9-9e27-ce5a047e9c9b.png)

For SASS records that have a -1 in any biotope rating then we should exclude that SASS record from the chart. Under the chart we should add a strapline

> This chart shows only SASS Records which have biotope ratings.

**Comment by dimasciput** [comment]
Not rated will be displayed as 0 data
