### ISSUE TITLE
Put the chart label on the left Y axis label written vertically

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#908]
![image](https://user-images.githubusercontent.com/178003/53729176-330f8500-3e7d-11e9-8161-6d1d3c984f08.png)

**Comment by timlinux** [comment]
@ann26 sorry your PR #936 makes me realise my ticket is not clear. What we need is:

1) numerical markers keep their current orientation
2) Chart label is remove and rather used as Y axis title  (so SASS Scores goes to the left of the chart, written vertically.

Sorry about the confusion!

**Comment by ann26** [comment]
hi @timlinux  no problem, I've fixed it
