### ISSUE TITLE
Metrics data summary download tweaks

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#912]
![screenshot 2019-03-04 at 13 17 22](https://user-images.githubusercontent.com/178003/53730275-1d4f8f00-3e80-11e9-96b9-e3ec55cdf2f0.png)

Groups in sheet must be split out into separate columns and given appropriate column headers:

![image](https://user-images.githubusercontent.com/178003/53730229-fbeea300-3e7f-11e9-9b83-d879822c7247.png)

Also the ecological category (A, B etc.) needs to be added as a column

**Comment by timlinux** [comment]
Also in

![image](https://user-images.githubusercontent.com/178003/53730332-4a9c3d00-3e80-11e9-95cf-9df21a0eda6b.png)


The spatial (province etc. should be listed first and in the proper order) and then number of SASS records shown just before the metrics section

**Comment by dimasciput** [comment]
Fixed
