### ISSUE TITLE
Updated CFE data to import

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#916]
This is the updated CFE fish data to import along with the GBIF data.

@timlinux @dimasciput @jeremyshelton 

[CFR Fish Data for FBIS.xlsx](https://github.com/kartoza/django-bims/files/2926617/CFR.Fish.Data.for.FBIS.xlsx)

**Comment by toniolsen** [comment]
Please remember that data from the SAIAB database (South African Institute for Aquatic Biodiversity database) must not be included as this comes from GBIF.

**Comment by toniolsen** [comment]
@timlinux @dimasciput

**Comment by dimasciput** [comment]
updated
