### ISSUE TITLE
FSDD Filter History

### ISSUE THREAD

**Issue by Christiaanvdm** [kartoza/django-bims#981]
Child of #957 
![image](https://user-images.githubusercontent.com/34506346/54377933-df781500-468e-11e9-9f50-0ddee718a07a.png)

**Comment by Christiaanvdm** [comment]
FBIS asked for a list showing how the current view they are seeing is being displayed (i.e. how the data is was filtered before they got to the dashboard)

**Comment by dimasciput** [comment]
@ann26 use this function to render filter list as table → https://github.com/kartoza/django-bims/blob/develop/sass/static/js/utils/filter_list.js#L71
